### ISSUE TITLE
500 error while trying to automatically update

### ISSUE THREAD

**Issue by jimchamberlin7** [tidusjar/Ombi#1032]
#### Ombi Version:

V 1.XX.XX

#### Update Branch:

Stable/Early Access Preview/development
Stable
#### Operating System:

(Windows 10)

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Error Details

Nancy.RequestExecutionException: Oh noes! ---> Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'PlexRequests.Core.SettingModels.SystemSettings' does not contain a definition for 'UpdateAvailable'
   at CallSite.Target(Closure , CallSite , Object )
   at RazorOutput.RazorView.Execute()
   at Nancy.ViewEngines.Razor.NancyRazorViewBase`1.ExecuteView(String body, IDictionary`2 sectionContents)
   at CallSite.Target(Closure , CallSite , Object , Object , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at CallSite.Target(Closure , CallSite , Object , Object , Object )
   at Nancy.ViewEngines.Razor.RazorViewEngine.<>c__DisplayClass2b.b__2a(Stream stream)
   at Nancy.Responses.MaterialisingResponse.PreExecute(NancyContext context)
   --- End of inner exception stack trace ---
   at Nancy.NancyEngine.InvokeOnErrorHook(NancyContext context, ErrorPipeline pipeline, Exception ex))

```

#### Problem Description:

(Cannot update automatically receive 500 internal error when selecting 'Click Here' on new update banner and 'Status' in admin)

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Can you please fill in all the information from the template.
