### ISSUE TITLE
Error when selecting Authentication tab

### ISSUE THREAD

**Issue by CBers** [tidusjar/Ombi#1066]
#### Ombi Version:

V 2.1.1384

#### Update Branch:

development

#### Operating System:

W7

#### Mono Version (only if your not on windows)

(Place text here)

```
#### Applicable Logs (from `/logs/` directory or the Admin page):

2017/02/04 12:57:02.154 Ombi.Api.ApiRequest Error: System.InvalidOperationException: There is an error in XML document (2, 2). ---> System.InvalidOperationException: <errors xmlns=''> was not expected.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexFriends.Read5_MediaContainer()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at Ombi.Api.ApiRequest.DeserializeXml[T](String input) in C:\projects\requestplex\Ombi.Api\ApiRequest.cs:line 134 System.InvalidOperationException: There is an error in XML document (2, 2). ---> System.InvalidOperationException: <errors xmlns=''> was not expected.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexFriends.Read5_MediaContainer()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at Ombi.Api.ApiRequest.DeserializeXml[T](String input) in C:\projects\requestplex\Ombi.Api\ApiRequest.cs:line 134

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Get an "undefined" error when selecting Authentication tab

![screenshot 2017-02-04 at 13 02 57](https://cloud.githubusercontent.com/assets/1756472/22618664/640d8cc2-eada-11e6-9c9c-29a28416d81a.png)

I have both settings enabled:

![screenshot 2017-02-04 at 13 08 41](https://cloud.githubusercontent.com/assets/1756472/22618688/2500b21a-eadb-11e6-999c-f271b8e036ef.png)

#### Reproduction Steps:

Click on Authentication tab

**Comment by SuperPotatoMen** [comment]
@CBers did you use emby users for authentication?

**Comment by CBers** [comment]
No. 

I created a user manually, but I do see the Emby users in the list of users.

**Comment by tidusjar** [comment]
Strange. I'm not seeing this.

Can you open up the browser developer tools (press F12) and the Click Network, there should be something in red, click that and then press Preview and post the result in the preview window.

Like the below:
![image](https://cloud.githubusercontent.com/assets/6642220/22622243/642bb622-eb2d-11e6-8123-6b47c415e285.png)

**Comment by CBers** [comment]
Don't have a PREVIEW option.

![image](https://cloud.githubusercontent.com/assets/1756472/22626045/2528e994-eb9c-11e6-8809-d48950801052.png)

**Comment by tidusjar** [comment]
Sorry, once the developer tools are open. Refresh the page and generate the
error, it should be in red then.

**Comment by CBers** [comment]
I clicked on Authentication when the dev tools were open and posted the above.

**Comment by CBers** [comment]
From the LOGS page in Ombi dashboard:
...
System.InvalidOperationException: There is an error in XML document (2, 2). ---> System.InvalidOperationException: was not expected. at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexFriends.Read5_MediaContainer() --- End of inner exception stack trace --- at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events) at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader) at Ombi.Api.ApiRequest.DeserializeXml[T](String input) in C:\projects\requestplex\Ombi.Api\ApiRequest.cs:line 134	
...
