### ISSUE TITLE
User was not emailed that content was available.

### ISSUE THREAD

**Issue by diedrichg** [tidusjar/Ombi#1107]
#### Ombi Version:

V 2.1.1407

#### Update Branch:

development

#### Operating System:

Win8.1

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

A user requested a TV series that was already on the server but not in his library. I made the content available in his library which he was then notified by Emby that it was available but Ombi never emailed him that it was available. 

I did not "Approve" the request because the content was already in Sonarr/Emby, I only clicked the button that said that it was "Available" but he did not get an email saying as such.

#### Reproduction Steps:

1. Have SuperAwesomeTVShow - s01e01 in Library A in Emby. (User B does not have access to Library A)
2. User B requests SuperAwesomeTVShow - s01 (all seasons request)
3. Connect User B to Library A in Emby - content becomes viewable by User B within Emby.
4. Do not Approve the request, only mark it as Available (I have no idea if it would try to re-download within Sonarr since it already existed - too scared to try)
5. User B does not get emailed that it's available in Emby
6. Is this because Ombi is querying all the Emby libraries en masse, rather than looking at what each individual user has authorized access to?
7. Querying Emby libraries en masse could lead to children seeing available media that they shouldn't!

FWIW, here is my library/folder structure:

Master "TV" folder in Windows where Sonarr drops the TV shows/episodes
-M:\
--TV
-----Gotham
-----NCIS
-----The Flash (2014)
-----The Walking Dead

I then have User folders which acts as their library in Emby. The TV Series folders within each are symbolic links to the master TV folder listed above: (s) = symbolic link to the folder in M:\TV\SeriesName

-M:\
--User A
-----(s)Gotham
-----(s)NCIS
--User B
-----(s)The Flash (2014)
-----(s)The Walking Dead

*This allows me to simply symbolic link a single Series to numerous User Libraries (folders in this case).

Emby>Libraries
--User A Library
-----M:\User A
--User B Library
-----M:\User B

**Comment by SuperPotatoMen** [comment]
This need investigation, Can you give some logs after you hit the Available button?
Pleas don't use the development branch beceause a lot it is broken beceause of the development or implentation are not finished yet.

**Comment by diedrichg** [comment]
#### Applicable Logs (from `/logs/` directory or the Admin page):

```

2017/02/12 03:59:48.126 Ombi.Services.Jobs.FaultQueueHandler Error: System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Core.TvSenderOld.<SendToSonarr>d__12.MoveNext() in C:\projects\requestplex\Ombi.Core\TvSenderOld.cs:line 116
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Ombi.Services.Jobs.FaultQueueHandler.ProcessTvShow(RequestedModel tvModel, SonarrSettings sonarr, SickRageSettings sickrage) in C:\projects\requestplex\Ombi.Services\Jobs\FaultQueueHandler.cs:line 173
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Core.TvSenderOld.<SendToSonarr>d__12.MoveNext() in C:\projects\requestplex\Ombi.Core\TvSenderOld.cs:line 116<---
 System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Core.TvSenderOld.<SendToSonarr>d__12.MoveNext() in C:\projects\requestplex\Ombi.Core\TvSenderOld.cs:line 116
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Ombi.Services.Jobs.FaultQueueHandler.ProcessTvShow(RequestedModel tvModel, SonarrSettings sonarr, SickRageSettings sickrage) in C:\projects\requestplex\Ombi.Services\Jobs\FaultQueueHandler.cs:line 173
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Core.TvSenderOld.<SendToSonarr>d__12.MoveNext() in C:\projects\requestplex\Ombi.Core\TvSenderOld.cs:line 116<---

2017/02/12 09:59:48.133 Ombi.Services.Jobs.FaultQueueHandler Error: System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Core.TvSenderOld.<SendToSonarr>d__12.MoveNext() in C:\projects\requestplex\Ombi.Core\TvSenderOld.cs:line 116
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Ombi.Services.Jobs.FaultQueueHandler.ProcessTvShow(RequestedModel tvModel, SonarrSettings sonarr, SickRageSettings sickrage) in C:\projects\requestplex\Ombi.Services\Jobs\FaultQueueHandler.cs:line 173
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Core.TvSenderOld.<SendToSonarr>d__12.MoveNext() in C:\projects\requestplex\Ombi.Core\TvSenderOld.cs:line 116<---
 System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Core.TvSenderOld.<SendToSonarr>d__12.MoveNext() in C:\projects\requestplex\Ombi.Core\TvSenderOld.cs:line 116
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Ombi.Services.Jobs.FaultQueueHandler.ProcessTvShow(RequestedModel tvModel, SonarrSettings sonarr, SickRageSettings sickrage) in C:\projects\requestplex\Ombi.Services\Jobs\FaultQueueHandler.cs:line 173
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Core.TvSenderOld.<SendToSonarr>d__12.MoveNext() in C:\projects\requestplex\Ombi.Core\TvSenderOld.cs:line 116<---

2017/02/12 15:59:48.128 Ombi.Services.Jobs.FaultQueueHandler Error: System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Core.TvSenderOld.<SendToSonarr>d__12.MoveNext() in C:\projects\requestplex\Ombi.Core\TvSenderOld.cs:line 116
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Ombi.Services.Jobs.FaultQueueHandler.ProcessTvShow(RequestedModel tvModel, SonarrSettings sonarr, SickRageSettings sickrage) in C:\projects\requestplex\Ombi.Services\Jobs\FaultQueueHandler.cs:line 173
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Core.TvSenderOld.<SendToSonarr>d__12.MoveNext() in C:\projects\requestplex\Ombi.Core\TvSenderOld.cs:line 116<---
 System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Core.TvSenderOld.<SendToSonarr>d__12.MoveNext() in C:\projects\requestplex\Ombi.Core\TvSenderOld.cs:line 116
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Ombi.Services.Jobs.FaultQueueHandler.ProcessTvShow(RequestedModel tvModel, SonarrSettings sonarr, SickRageSettings sickrage) in C:\projects\requestplex\Ombi.Services\Jobs\FaultQueueHandler.cs:line 173
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Core.TvSenderOld.<SendToSonarr>d__12.MoveNext() in C:\projects\requestplex\Ombi.Core\TvSenderOld.cs:line 116<---



```

**Comment by SuperPotatoMen** [comment]
Wait a second, you hit the available button and you got a FaultQueueHandler error.
Are you sure you don't have other errors in your log?

**Comment by diedrichg** [comment]
Those were ALL the logs from today taken directly from the /logs folder

**Comment by SuperPotatoMen** [comment]
Can you set your log level to debug and do the available thing again?

**Comment by diedrichg** [comment]
Could not reproduce! Go figure. I was emailed that the content was marked as available by the admin account. Might as well close this. I'll reopen if I hear of this again.

**Comment by SuperPotatoMen** [comment]
Yeah, let us know if you have this error again!
