### ISSUE TITLE
SMTP Authentication not working with an Exchange mail server

### ISSUE THREAD

**Issue by mattenz** [tidusjar/Ombi#1144]
#### Ombi Version:

V 2.1.1427
#### Update Branch:

Early Access Preview

#### Operating System:

Windows Server 2016

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

2017/02/18 18:37:06.744 Ombi.Services.Notification.EmailMessageNotification Error: System.NotSupportedException: The SMTP server does not support authentication.
   at MailKit.Net.Smtp.SmtpClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
   at MailKit.MailService.Authenticate(String userName, String password, CancellationToken cancellationToken)
   at Ombi.Services.Notification.EmailMessageNotification.<Send>d__17.MoveNext() in C:\projects\requestplex\Ombi.Services\Notification\EmailMessageNotification.cs:line 264 System.NotSupportedException: The SMTP server does not support authentication.
   at MailKit.Net.Smtp.SmtpClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
   at MailKit.MailService.Authenticate(String userName, String password, CancellationToken cancellationToken)
   at Ombi.Services.Notification.EmailMessageNotification.<Send>d__17.MoveNext() in C:\projects\requestplex\Ombi.Services\Notification\EmailMessageNotification.cs:line 264
2017/02/18 18:37:06.931 Ombi.Services.Notification.NotificationService Error: Notification 'PushoverNotification' failed with exception System.InvalidCastException: Unable to cast object of type 'Ombi.Core.SettingModels.EmailNotificationSettings' to type 'Ombi.Core.SettingModels.PushoverNotificationSettings'.
   at Ombi.Services.Notification.PushoverNotification.<NotifyAsync>d__11.MoveNext() in C:\projects\requestplex\Ombi.Services\Notification\PushoverNotification.cs:line 62
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Services.Notification.NotificationService.<NotifyAsync>d__9.MoveNext() in C:\projects\requestplex\Ombi.Services\Notification\NotificationService.cs:line 95

```

#### Problem Description:

I'm using an Exchange 2016 server as my SMTP server for Ombi to use.  Exchange is setup so that it requires authentication for SMTP relay.  I have an account created for Ombi to use and all the details are correctly entered on the Mail Notification settings page, however the error in the log as above says the server doesn't support authentication.  

However, I know it does because if I use PowerShell to send a message it works if I use authentication and doesn't work without.  I tested with the following:
```
Send-MailMessage -Credential (get-credential) -To me@domain.com -From plex@domain.com -SmtpServer 192.168.0.113 -Subject test -body testing -Port 25
```

**Comment by mattenz** [comment]
Had a brain wave, right after posting this of course.  I hadn't scoped out my other unauthenticated receive connector in Exchange properly and it was listening on all IPs, so Ombi was hitting that receiver rather than the authenticated one.
