### ISSUE TITLE
Ombi not detecting anything added after the past two PMS updates

### ISSUE THREAD

**Issue by chrisausbun** [tidusjar/Ombi#1212]
#### Ombi Version:

V 2.1.1490

#### Update Branch:

Development

#### Media Sever:

Plex

#### Media Server Version:

1.4.3.3433

#### Operating System:

Windows 10 Home x64

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

2017/03/04 00:33:12.602 Ombi.Services.Jobs.PlexContentCacher Error: Failed to obtain Plex libraries Mono.Data.Sqlite.SqliteException (0x80004005): SQLite error
table PlexContent has no column named ItemId
   at Mono.Data.Sqlite.SQLite3.Prepare(SqliteConnection cnn, String strSql, SqliteStatement previous, UInt32 timeoutMS, String& strRemain)
   at Mono.Data.Sqlite.SqliteCommand.BuildNextCommand()
   at Mono.Data.Sqlite.SqliteCommand.GetStatement(Int32 index)
   at Mono.Data.Sqlite.SqliteDataReader.NextResult()
   at Mono.Data.Sqlite.SqliteDataReader..ctor(SqliteCommand cmd, CommandBehavior behave)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command)
   at SQLiteAdapter.Insert(IDbConnection connection, IDbTransaction transaction, Nullable`1 commandTimeout, String tableName, String columnList, String parameterList, IEnumerable`1 keyProperties, Object entityToInsert)
   at Dapper.Contrib.Extensions.SqlMapperExtensions.Insert[T](IDbConnection connection, T entityToInsert, IDbTransaction transaction, Nullable`1 commandTimeout)
   at Ombi.Store.Repository.BaseGenericRepository`1.Insert(T entity) in C:\projects\requestplex\Ombi.Store\Repository\BaseGenericRepository.cs:line 99
   at Ombi.Services.Jobs.PlexContentCacher.CachedLibraries(PlexSettings plexSettings) in C:\projects\requestplex\Ombi.Services\Jobs\PlexContentCacher.cs:line 270
2017/03/04 01:32:33.245 Ombi.Services.Jobs.PlexContentCacher Error: Failed to obtain Plex libraries Mono.Data.Sqlite.SqliteException (0x80004005): SQLite error
table PlexContent has no column named ItemId
   at Mono.Data.Sqlite.SQLite3.Prepare(SqliteConnection cnn, String strSql, SqliteStatement previous, UInt32 timeoutMS, String& strRemain)
   at Mono.Data.Sqlite.SqliteCommand.BuildNextCommand()
   at Mono.Data.Sqlite.SqliteCommand.GetStatement(Int32 index)
   at Mono.Data.Sqlite.SqliteDataReader.NextResult()
   at Mono.Data.Sqlite.SqliteDataReader..ctor(SqliteCommand cmd, CommandBehavior behave)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command)
   at SQLiteAdapter.Insert(IDbConnection connection, IDbTransaction transaction, Nullable`1 commandTimeout, String tableName, String columnList, String parameterList, IEnumerable`1 keyProperties, Object entityToInsert)
   at Dapper.Contrib.Extensions.SqlMapperExtensions.Insert[T](IDbConnection connection, T entityToInsert, IDbTransaction transaction, Nullable`1 commandTimeout)
   at Ombi.Store.Repository.BaseGenericRepository`1.Insert(T entity) in C:\projects\requestplex\Ombi.Store\Repository\BaseGenericRepository.cs:line 99
   at Ombi.Services.Jobs.PlexContentCacher.CachedLibraries(PlexSettings plexSettings) in C:\projects\requestplex\Ombi.Services\Jobs\PlexContentCacher.cs:line 270
2017/03/04 02:32:26.221 Ombi.Services.Jobs.PlexContentCacher Error: Failed to obtain Plex libraries Mono.Data.Sqlite.SqliteException (0x80004005): SQLite error
table PlexContent has no column named ItemId
   at Mono.Data.Sqlite.SQLite3.Prepare(SqliteConnection cnn, String strSql, SqliteStatement previous, UInt32 timeoutMS, String& strRemain)
   at Mono.Data.Sqlite.SqliteCommand.BuildNextCommand()
   at Mono.Data.Sqlite.SqliteCommand.GetStatement(Int32 index)
   at Mono.Data.Sqlite.SqliteDataReader.NextResult()
   at Mono.Data.Sqlite.SqliteDataReader..ctor(SqliteCommand cmd, CommandBehavior behave)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command)
   at SQLiteAdapter.Insert(IDbConnection connection, IDbTransaction transaction, Nullable`1 commandTimeout, String tableName, String columnList, String parameterList, IEnumerable`1 keyProperties, Object entityToInsert)
   at Dapper.Contrib.Extensions.SqlMapperExtensions.Insert[T](IDbConnection connection, T entityToInsert, IDbTransaction transaction, Nullable`1 commandTimeout)
   at Ombi.Store.Repository.BaseGenericRepository`1.Insert(T entity) in C:\projects\requestplex\Ombi.Store\Repository\BaseGenericRepository.cs:line 99
   at Ombi.Services.Jobs.PlexContentCacher.CachedLibraries(PlexSettings plexSettings) in C:\projects\requestplex\Ombi.Services\Jobs\PlexContentCacher.cs:line 270
2017/03/04 03:32:41.206 Ombi.Services.Jobs.PlexContentCacher Error: Failed to obtain Plex libraries Mono.Data.Sqlite.SqliteException (0x80004005): SQLite error
table PlexContent has no column named ItemId
   at Mono.Data.Sqlite.SQLite3.Prepare(SqliteConnection cnn, String strSql, SqliteStatement previous, UInt32 timeoutMS, String& strRemain)
   at Mono.Data.Sqlite.SqliteCommand.BuildNextCommand()
   at Mono.Data.Sqlite.SqliteCommand.GetStatement(Int32 index)
   at Mono.Data.Sqlite.SqliteDataReader.NextResult()
   at Mono.Data.Sqlite.SqliteDataReader..ctor(SqliteCommand cmd, CommandBehavior behave)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command)
   at SQLiteAdapter.Insert(IDbConnection connection, IDbTransaction transaction, Nullable`1 commandTimeout, String tableName, String columnList, String parameterList, IEnumerable`1 keyProperties, Object entityToInsert)
   at Dapper.Contrib.Extensions.SqlMapperExtensions.Insert[T](IDbConnection connection, T entityToInsert, IDbTransaction transaction, Nullable`1 commandTimeout)
   at Ombi.Store.Repository.BaseGenericRepository`1.Insert(T entity) in C:\projects\requestplex\Ombi.Store\Repository\BaseGenericRepository.cs:line 99
   at Ombi.Services.Jobs.PlexContentCacher.CachedLibraries(PlexSettings plexSettings) in C:\projects\requestplex\Ombi.Services\Jobs\PlexContentCacher.cs:line 270
2017/03/04 04:32:37.000 Ombi.Services.Jobs.PlexContentCacher Error: Failed to obtain Plex libraries Mono.Data.Sqlite.SqliteException (0x80004005): SQLite error
table PlexContent has no column named ItemId
   at Mono.Data.Sqlite.SQLite3.Prepare(SqliteConnection cnn, String strSql, SqliteStatement previous, UInt32 timeoutMS, String& strRemain)
   at Mono.Data.Sqlite.SqliteCommand.BuildNextCommand()
   at Mono.Data.Sqlite.SqliteCommand.GetStatement(Int32 index)
   at Mono.Data.Sqlite.SqliteDataReader.NextResult()
   at Mono.Data.Sqlite.SqliteDataReader..ctor(SqliteCommand cmd, CommandBehavior behave)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command)
   at SQLiteAdapter.Insert(IDbConnection connection, IDbTransaction transaction, Nullable`1 commandTimeout, String tableName, String columnList, String parameterList, IEnumerable`1 keyProperties, Object entityToInsert)
   at Dapper.Contrib.Extensions.SqlMapperExtensions.Insert[T](IDbConnection connection, T entityToInsert, IDbTransaction transaction, Nullable`1 commandTimeout)
   at Ombi.Store.Repository.BaseGenericRepository`1.Insert(T entity) in C:\projects\requestplex\Ombi.Store\Repository\BaseGenericRepository.cs:line 99
   at Ombi.Services.Jobs.PlexContentCacher.CachedLibraries(PlexSettings plexSettings) in C:\projects\requestplex\Ombi.Services\Jobs\PlexContentCacher.cs:line 270
2017/03/04 05:30:46.062 Ombi.UI.Program Info: This is not Mono 
2017/03/04 05:30:47.152 Ombi.Api.PlexApi Error: Exception when calling GetLibrarySections for Plex, Retrying 00:00:05 Ombi.Helpers.Exceptions.ApiRequestException: Got StatusCode=0 for .
   at Ombi.Api.ApiRequest.ExecuteXml[T](IRestRequest request, Uri baseUri) in C:\projects\requestplex\Ombi.Api\ApiRequest.cs:line 85
   at Ombi.Api.PlexApi.<>c__DisplayClass18_0.<GetLibrarySections>b__0() in C:\projects\requestplex\Ombi.Api\PlexApi.cs:line 168
   at Polly.Policy.<>c__DisplayClass8_0`1.<Execute>b__0()
   at Polly.RetrySyntax.<>c__DisplayClass14_0.<WaitAndRetry>b__1()
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`1 action, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory)
2017/03/04 05:30:53.276 Ombi.Api.PlexApi Error: Exception when calling GetLibrarySections for Plex, Retrying 00:00:10 Ombi.Helpers.Exceptions.ApiRequestException: Got StatusCode=0 for .
   at Ombi.Api.ApiRequest.ExecuteXml[T](IRestRequest request, Uri baseUri) in C:\projects\requestplex\Ombi.Api\ApiRequest.cs:line 85
   at Ombi.Api.PlexApi.<>c__DisplayClass18_0.<GetLibrarySections>b__0() in C:\projects\requestplex\Ombi.Api\PlexApi.cs:line 168
   at Polly.Policy.<>c__DisplayClass8_0`1.<Execute>b__0()
   at Polly.RetrySyntax.<>c__DisplayClass14_0.<WaitAndRetry>b__1()
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`1 action, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory)
2017/03/04 05:32:46.130 Ombi.Services.Jobs.PlexContentCacher Error: Failed to obtain Plex libraries Mono.Data.Sqlite.SqliteException (0x80004005): SQLite error
table PlexContent has no column named ItemId
   at Mono.Data.Sqlite.SQLite3.Prepare(SqliteConnection cnn, String strSql, SqliteStatement previous, UInt32 timeoutMS, String& strRemain)
   at Mono.Data.Sqlite.SqliteCommand.BuildNextCommand()
   at Mono.Data.Sqlite.SqliteCommand.GetStatement(Int32 index)
   at Mono.Data.Sqlite.SqliteDataReader.NextResult()
   at Mono.Data.Sqlite.SqliteDataReader..ctor(SqliteCommand cmd, CommandBehavior behave)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command)
   at SQLiteAdapter.Insert(IDbConnection connection, IDbTransaction transaction, Nullable`1 commandTimeout, String tableName, String columnList, String parameterList, IEnumerable`1 keyProperties, Object entityToInsert)
   at Dapper.Contrib.Extensions.SqlMapperExtensions.Insert[T](IDbConnection connection, T entityToInsert, IDbTransaction transaction, Nullable`1 commandTimeout)
   at Ombi.Store.Repository.BaseGenericRepository`1.Insert(T entity) in C:\projects\requestplex\Ombi.Store\Repository\BaseGenericRepository.cs:line 99
   at Ombi.Services.Jobs.PlexContentCacher.CachedLibraries(PlexSettings plexSettings) in C:\projects\requestplex\Ombi.Services\Jobs\PlexContentCacher.cs:line 270
2017/03/04 06:32:34.867 Ombi.Services.Jobs.PlexContentCacher Error: Failed to obtain Plex libraries Mono.Data.Sqlite.SqliteException (0x80004005): SQLite error
table PlexContent has no column named ItemId
   at Mono.Data.Sqlite.SQLite3.Prepare(SqliteConnection cnn, String strSql, SqliteStatement previous, UInt32 timeoutMS, String& strRemain)
   at Mono.Data.Sqlite.SqliteCommand.BuildNextCommand()
   at Mono.Data.Sqlite.SqliteCommand.GetStatement(Int32 index)
   at Mono.Data.Sqlite.SqliteDataReader.NextResult()
   at Mono.Data.Sqlite.SqliteDataReader..ctor(SqliteCommand cmd, CommandBehavior behave)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command)
   at SQLiteAdapter.Insert(IDbConnection connection, IDbTransaction transaction, Nullable`1 commandTimeout, String tableName, String columnList, String parameterList, IEnumerable`1 keyProperties, Object entityToInsert)
   at Dapper.Contrib.Extensions.SqlMapperExtensions.Insert[T](IDbConnection connection, T entityToInsert, IDbTransaction transaction, Nullable`1 commandTimeout)
   at Ombi.Store.Repository.BaseGenericRepository`1.Insert(T entity) in C:\projects\requestplex\Ombi.Store\Repository\BaseGenericRepository.cs:line 99
   at Ombi.Services.Jobs.PlexContentCacher.CachedLibraries(PlexSettings plexSettings) in C:\projects\requestplex\Ombi.Services\Jobs\PlexContentCacher.cs:line 270
2017/03/04 07:32:37.923 Ombi.Services.Jobs.PlexContentCacher Error: Failed to obtain Plex libraries Mono.Data.Sqlite.SqliteException (0x80004005): SQLite error
table PlexContent has no column named ItemId
   at Mono.Data.Sqlite.SQLite3.Prepare(SqliteConnection cnn, String strSql, SqliteStatement previous, UInt32 timeoutMS, String& strRemain)
   at Mono.Data.Sqlite.SqliteCommand.BuildNextCommand()
   at Mono.Data.Sqlite.SqliteCommand.GetStatement(Int32 index)
   at Mono.Data.Sqlite.SqliteDataReader.NextResult()
   at Mono.Data.Sqlite.SqliteDataReader..ctor(SqliteCommand cmd, CommandBehavior behave)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command)
   at SQLiteAdapter.Insert(IDbConnection connection, IDbTransaction transaction, Nullable`1 commandTimeout, String tableName, String columnList, String parameterList, IEnumerable`1 keyProperties, Object entityToInsert)
   at Dapper.Contrib.Extensions.SqlMapperExtensions.Insert[T](IDbConnection connection, T entityToInsert, IDbTransaction transaction, Nullable`1 commandTimeout)
   at Ombi.Store.Repository.BaseGenericRepository`1.Insert(T entity) in C:\projects\requestplex\Ombi.Store\Repository\BaseGenericRepository.cs:line 99
   at Ombi.Services.Jobs.PlexContentCacher.CachedLibraries(PlexSettings plexSettings) in C:\projects\requestplex\Ombi.Services\Jobs\PlexContentCacher.cs:line 270
2017/03/04 07:56:59.707 Ombi.UI.Program Info: This is not Mono 
2017/03/04 07:58:59.350 Ombi.Services.Jobs.PlexContentCacher Error: Failed to obtain Plex libraries Mono.Data.Sqlite.SqliteException (0x80004005): SQLite error
table PlexContent has no column named ItemId
   at Mono.Data.Sqlite.SQLite3.Prepare(SqliteConnection cnn, String strSql, SqliteStatement previous, UInt32 timeoutMS, String& strRemain)
   at Mono.Data.Sqlite.SqliteCommand.BuildNextCommand()
   at Mono.Data.Sqlite.SqliteCommand.GetStatement(Int32 index)
   at Mono.Data.Sqlite.SqliteDataReader.NextResult()
   at Mono.Data.Sqlite.SqliteDataReader..ctor(SqliteCommand cmd, CommandBehavior behave)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command)
   at SQLiteAdapter.Insert(IDbConnection connection, IDbTransaction transaction, Nullable`1 commandTimeout, String tableName, String columnList, String parameterList, IEnumerable`1 keyProperties, Object entityToInsert)
   at Dapper.Contrib.Extensions.SqlMapperExtensions.Insert[T](IDbConnection connection, T entityToInsert, IDbTransaction transaction, Nullable`1 commandTimeout)
   at Ombi.Store.Repository.BaseGenericRepository`1.Insert(T entity) in C:\projects\requestplex\Ombi.Store\Repository\BaseGenericRepository.cs:line 99
   at Ombi.Services.Jobs.PlexContentCacher.CachedLibraries(PlexSettings plexSettings) in C:\projects\requestplex\Ombi.Services\Jobs\PlexContentCacher.cs:line 270
2017/03/04 09:49:42.728 Ombi.Services.Jobs.PlexContentCacher Error: Failed to obtain Plex libraries Mono.Data.Sqlite.SqliteException (0x80004005): SQLite error
table PlexContent has no column named ItemId
   at Mono.Data.Sqlite.SQLite3.Prepare(SqliteConnection cnn, String strSql, SqliteStatement previous, UInt32 timeoutMS, String& strRemain)
   at Mono.Data.Sqlite.SqliteCommand.BuildNextCommand()
   at Mono.Data.Sqlite.SqliteCommand.GetStatement(Int32 index)
   at Mono.Data.Sqlite.SqliteDataReader.NextResult()
   at Mono.Data.Sqlite.SqliteDataReader..ctor(SqliteCommand cmd, CommandBehavior behave)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command)
   at SQLiteAdapter.Insert(IDbConnection connection, IDbTransaction transaction, Nullable`1 commandTimeout, String tableName, String columnList, String parameterList, IEnumerable`1 keyProperties, Object entityToInsert)
   at Dapper.Contrib.Extensions.SqlMapperExtensions.Insert[T](IDbConnection connection, T entityToInsert, IDbTransaction transaction, Nullable`1 commandTimeout)
   at Ombi.Store.Repository.BaseGenericRepository`1.Insert(T entity) in C:\projects\requestplex\Ombi.Store\Repository\BaseGenericRepository.cs:line 99
   at Ombi.Services.Jobs.PlexContentCacher.CachedLibraries(PlexSettings plexSettings) in C:\projects\requestplex\Ombi.Services\Jobs\PlexContentCacher.cs:line 270
2017/03/04 09:58:48.795 Ombi.Services.Jobs.PlexContentCacher Error: Failed to obtain Plex libraries Mono.Data.Sqlite.SqliteException (0x80004005): SQLite error
table PlexContent has no column named ItemId
   at Mono.Data.Sqlite.SQLite3.Prepare(SqliteConnection cnn, String strSql, SqliteStatement previous, UInt32 timeoutMS, String& strRemain)
   at Mono.Data.Sqlite.SqliteCommand.BuildNextCommand()
   at Mono.Data.Sqlite.SqliteCommand.GetStatement(Int32 index)
   at Mono.Data.Sqlite.SqliteDataReader.NextResult()
   at Mono.Data.Sqlite.SqliteDataReader..ctor(SqliteCommand cmd, CommandBehavior behave)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command)
   at SQLiteAdapter.Insert(IDbConnection connection, IDbTransaction transaction, Nullable`1 commandTimeout, String tableName, String columnList, String parameterList, IEnumerable`1 keyProperties, Object entityToInsert)
   at Dapper.Contrib.Extensions.SqlMapperExtensions.Insert[T](IDbConnection connection, T entityToInsert, IDbTransaction transaction, Nullable`1 commandTimeout)
   at Ombi.Store.Repository.BaseGenericRepository`1.Insert(T entity) in C:\projects\requestplex\Ombi.Store\Repository\BaseGenericRepository.cs:line 99
   at Ombi.Services.Jobs.PlexContentCacher.CachedLibraries(PlexSettings plexSettings) in C:\projects\requestplex\Ombi.Services\Jobs\PlexContentCacher.cs:line 270

```

#### Problem Description:

Ombi is not detecting any newly added content since the last two Plex Media Server updates.

#### Reproduction Steps:

Search for anything that has been added since the past two Plex Server updates.

**Comment by tidusjar** [comment]
Can you either,

1. Edit your Ombi.sqlite/PlexRequests.sqlite file using SQLiteBrowser and remove the Version 2200 record from the `VersionInfo` table. Then start Ombi
2. Start with a new database

**Comment by FlynnLives** [comment]
I am having the same issue, I have removed the old version record after stopping ombi. will report back if issue persists or not

**Comment by chrisausbun** [comment]
Thank you soooo much!!! Looks like removing that record totally did it. I would've hated to have to start with a new database. I've got over 50 users' requests and I also like keeping a record of all the issues I've resolved. Thanks again @tidusjar, you're awesome!!

**Comment by tidusjar** [comment]
It's that since you are using an early version, the migration run, but I edited the migration later on... And we check if the migration has run by using that version table, if it has run then we obviously don't run it again. But because I edited it after you run it then yeah...

**Comment by seanvree** [comment]
I had this problem too on Windows.  

Removing the 2200 record did it!

THX
