### ISSUE TITLE
Empty Newsletter:  IndexOutOfRangeException

### ISSUE THREAD

**Issue by ceolus** [tidusjar/Ombi#1231]
2.1.1366 Ombi Version:

V 1.XX.XX

#### Update Branch:

Stable/Early Access Preview/development

#### Media Sever:

Plex/Emby

#### Operating System:

Windows 10

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
2017/03/11 07:16:39.738 Ombi.Services.Jobs.StoreBackup Warn: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Ombi.Services.Jobs.StoreBackup.ParseName(String fileName) in C:\projects\requestplex\Ombi.Services\Jobs\StoreBackup.cs:line 157
   at Ombi.Services.Jobs.StoreBackup.DoWeNeedToBackup(String backupPath) in C:\projects\requestplex\Ombi.Services\Jobs\StoreBackup.cs:line 139
   at Ombi.Services.Jobs.StoreBackup.TakeBackup() in C:\projects\requestplex\Ombi.Services\Jobs\StoreBackup.cs:line 102 System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Ombi.Services.Jobs.StoreBackup.ParseName(String fileName) in C:\projects\requestplex\Ombi.Services\Jobs\StoreBackup.cs:line 157
   at Ombi.Services.Jobs.StoreBackup.DoWeNeedToBackup(String backupPath) in C:\projects\requestplex\Ombi.Services\Jobs\StoreBackup.cs:line 139
   at Ombi.Services.Jobs.StoreBackup.TakeBackup() in C:\projects\requestplex\Ombi.Services\Jobs\StoreBackup.cs:line 102
2017/03/11 07:16:39.832 Ombi.Services.Jobs.StoreBackup Warn: Exception when trying to copy the backup. 


(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Empty Newsletter

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by SuperPotatoMen** [comment]
Can you use our format and full it in?
