### ISSUE TITLE
Backup failed  IndexOutOfRangeException

### ISSUE THREAD

**Issue by ceolus** [tidusjar/Ombi#1232]
Ombi Version:

V 2.1.1336

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Media Server Version: 

1.4.3.3433

#### Operating System:

Windows 10

#### Applicable Logs (from `/logs/` directory or the Admin page):

2017/03/11 07:16:39.738 Ombi.Services.Jobs.StoreBackup Warn: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Ombi.Services.Jobs.StoreBackup.ParseName(String fileName) in C:\projects\requestplex\Ombi.Services\Jobs\StoreBackup.cs:line 157
   at Ombi.Services.Jobs.StoreBackup.DoWeNeedToBackup(String backupPath) in C:\projects\requestplex\Ombi.Services\Jobs\StoreBackup.cs:line 139
   at Ombi.Services.Jobs.StoreBackup.TakeBackup() in C:\projects\requestplex\Ombi.Services\Jobs\StoreBackup.cs:line 102 System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Ombi.Services.Jobs.StoreBackup.ParseName(String fileName) in C:\projects\requestplex\Ombi.Services\Jobs\StoreBackup.cs:line 157
   at Ombi.Services.Jobs.StoreBackup.DoWeNeedToBackup(String backupPath) in C:\projects\requestplex\Ombi.Services\Jobs\StoreBackup.cs:line 139
   at Ombi.Services.Jobs.StoreBackup.TakeBackup() in C:\projects\requestplex\Ombi.Services\Jobs\StoreBackup.cs:line 102
2017/03/11 07:16:39.832 Ombi.Services.Jobs.StoreBackup Warn: Exception when trying to copy the backup. 

#### Problem Description:

Empty Newsletter

**Comment by tidusjar** [comment]
That error is an error in backing up your database...

Is there anything else in the logs?

**Comment by SuperPotatoMen** [comment]
No answer. closing this one.
