### ISSUE TITLE
Plex Cacher job failed every time

### ISSUE THREAD

**Issue by SuperPotatoMen** [tidusjar/Ombi#1237]
#### Ombi Version:

V2.1.1514

#### Update Branch:

Early Access Preview

#### Media Sever:

Plex

#### Media Server Version:

 1.4.3.3433

#### Operating System:

Windows 10

#### Mono Version (only if your not on windows)

-

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Message	Area	Log Level	Date
Failed to obtain Plex libraries	Ombi.Services.Jobs.PlexContentCacher	Error	3/12/2017 11:33:45 PM
2017/03/12 11:45:53.864 Ombi.Services.Jobs.PlexContentCacher Error: Failed to obtain Plex libraries Mono.Data.Sqlite.SqliteException (0x80004005): SQLite error
table PlexContent has no column named ItemId
   at Mono.Data.Sqlite.SQLite3.Prepare(SqliteConnection cnn, String strSql, SqliteStatement previous, UInt32 timeoutMS, String& strRemain)
   at Mono.Data.Sqlite.SqliteCommand.BuildNextCommand()
   at Mono.Data.Sqlite.SqliteCommand.GetStatement(Int32 index)
   at Mono.Data.Sqlite.SqliteDataReader.NextResult()
   at Mono.Data.Sqlite.SqliteDataReader..ctor(SqliteCommand cmd, CommandBehavior behave)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command)
   at SQLiteAdapter.Insert(IDbConnection connection, IDbTransaction transaction, Nullable`1 commandTimeout, String tableName, String columnList, String parameterList, IEnumerable`1 keyProperties, Object entityToInsert)
   at Dapper.Contrib.Extensions.SqlMapperExtensions.Insert[T](IDbConnection connection, T entityToInsert, IDbTransaction transaction, Nullable`1 commandTimeout)
   at Ombi.Store.Repository.BaseGenericRepository`1.Insert(T entity) in C:\projects\requestplex\Ombi.Store\Repository\BaseGenericRepository.cs:line 99
   at Ombi.Services.Jobs.PlexContentCacher.CachedLibraries(PlexSettings plexSettings) in C:\projects\requestplex\Ombi.Services\Jobs\PlexContentCacher.cs:line 270

```

#### Problem Description:

Everytime the job plex cacher is running, it failed everytime. Ombi doesn't cache the content on my plex server

#### Reproduction Steps:

I run the job manualy and under the admin panel it will show only a error that the job failed.
I found in a path /logs/ where a whole different error shows up (see log text above)

**Comment by tidusjar** [comment]
You must have run a really early build. 

Can you delete the PlexContent table?

DELETE PlexContent in SQLiteBrowser

**Comment by SuperPotatoMen** [comment]
@tidusjar That did the trick. Thanks. I'm not sure how it is possible that i missed that colum. Maybe i upgraded in the past to a early dev build :/ (i can't remember lol)

**Comment by CystemDown** [comment]
Here is how to do it for those that dont know how to do sqlite stuff.

I'm on Ubuntu Server in this example. 

user@machine:~$ sqlite3 /opt/ombi/Release/PlexRequests.sqlite
SQLite version 3.8.2 2013-12-06 14:53:30
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> DROP TABLE PlexContent;
sqlite> .quit
user@machine:~$

**Comment by PotatoQuality** [comment]
@CystemDown thanks for you help. Didnt saw you post :(

**Comment by vicegold** [comment]
Any idea where the sqlite file is on a macOS installation? Can't find it anywhere, but i also have this problem.

**Comment by SturmB** [comment]
Okay, how can this be done in a Docker container? I'm getting `bash: sqlite3: command not found` when I try to run the first command inside the container (with `docker exec -it ombi /bin/bash`).
