### ISSUE TITLE
Automatically Mark as Available

### ISSUE THREAD

**Issue by camwise** [tidusjar/Ombi#1273]
#### Ombi Version:

V 	2.1.1548

#### Update Branch:

Early Access Preview

#### Media Sever:

Plex

#### Media Server Version:

 1.5.0.3501

#### Operating System:

Windows 10

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

I apologize if this is already listed, but couldn't find it when searching through the issues.

None of the TV Show, or Movie content that is being downloaded ever shows available on ombi.  Every movie that i have downloaded over the last few weeks seems to just be stuck in Ombi.  I can go manually mark as available, but that automatic step doesn't seem to be happening.

#### Reproduction Steps:

Download movie with CouchPotato and uTorrent.  CouchPotato moves and renames video file to proper directory for Plex to pickup.  Wait days and still no change on Ombi marking it as available.

**Comment by SuperPotatoMen** [comment]
Pleas provide debug logging from ombi when the cacher and available checker is running.

**Comment by camwise** [comment]
Below is the most recent logs:

`2017/03/20 10:18:32.395 Ombi.Services.Jobs.PlexContentCacher Error: Failed to obtain Plex libraries Mono.Data.Sqlite.SqliteException (0x80004005): SQLite error
table PlexContent has no column named ItemId
   at Mono.Data.Sqlite.SQLite3.Prepare(SqliteConnection cnn, String strSql, SqliteStatement previous, UInt32 timeoutMS, String& strRemain)
   at Mono.Data.Sqlite.SqliteCommand.BuildNextCommand()
   at Mono.Data.Sqlite.SqliteCommand.GetStatement(Int32 index)
   at Mono.Data.Sqlite.SqliteDataReader.NextResult()
   at Mono.Data.Sqlite.SqliteDataReader..ctor(SqliteCommand cmd, CommandBehavior behave)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command)
   at SQLiteAdapter.Insert(IDbConnection connection, IDbTransaction transaction, Nullable`1 commandTimeout, String tableName, String columnList, String parameterList, IEnumerable`1 keyProperties, Object entityToInsert)
   at Dapper.Contrib.Extensions.SqlMapperExtensions.Insert[T](IDbConnection connection, T entityToInsert, IDbTransaction transaction, Nullable`1 commandTimeout)
   at Ombi.Store.Repository.BaseGenericRepository`1.Insert(T entity) in C:\projects\requestplex\Ombi.Store\Repository\BaseGenericRepository.cs:line 99
   at Ombi.Services.Jobs.PlexContentCacher.CachedLibraries(PlexSettings plexSettings) in C:\projects\requestplex\Ombi.Services\Jobs\PlexContentCacher.cs:line 272
2017/03/20 10:19:06.531 Ombi.Services.Jobs.PlexContentCacher Error: Failed to obtain Plex libraries Mono.Data.Sqlite.SqliteException (0x80004005): SQLite error
table PlexContent has no column named ItemId
   at Mono.Data.Sqlite.SQLite3.Prepare(SqliteConnection cnn, String strSql, SqliteStatement previous, UInt32 timeoutMS, String& strRemain)
   at Mono.Data.Sqlite.SqliteCommand.BuildNextCommand()
   at Mono.Data.Sqlite.SqliteCommand.GetStatement(Int32 index)
   at Mono.Data.Sqlite.SqliteDataReader.NextResult()
   at Mono.Data.Sqlite.SqliteDataReader..ctor(SqliteCommand cmd, CommandBehavior behave)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command)
   at SQLiteAdapter.Insert(IDbConnection connection, IDbTransaction transaction, Nullable`1 commandTimeout, String tableName, String columnList, String parameterList, IEnumerable`1 keyProperties, Object entityToInsert)
   at Dapper.Contrib.Extensions.SqlMapperExtensions.Insert[T](IDbConnection connection, T entityToInsert, IDbTransaction transaction, Nullable`1 commandTimeout)
   at Ombi.Store.Repository.BaseGenericRepository`1.Insert(T entity) in C:\projects\requestplex\Ombi.Store\Repository\BaseGenericRepository.cs:line 99
   at Ombi.Services.Jobs.PlexContentCacher.CachedLibraries(PlexSettings plexSettings) in C:\projects\requestplex\Ombi.Services\Jobs\PlexContentCacher.cs:line 272
2017/03/20 10:19:11.392 Ombi.Services.Jobs.PlexAvailabilityChecker Info: Episode cache info is not available. tvdbid: 292124, season: 2, episode: 6 
2017/03/20 10:19:59.359 Ombi.Services.Jobs.PlexAvailabilityChecker Debug: Requests that will be updated count 0 
2017/03/20 10:20:21.283 Ombi.Services.Jobs.PlexContentCacher Debug: Getting Lib sections 
2017/03/20 10:20:21.311 Ombi.Services.Jobs.PlexContentCacher Debug: Going through sections now 
2017/03/20 10:20:21.335 Ombi.Services.Jobs.PlexContentCacher Debug: adding lib 
2017/03/20 10:20:21.364 Ombi.Services.Jobs.PlexContentCacher Debug: adding lib 
2017/03/20 10:20:21.405 Ombi.Services.Jobs.PlexContentCacher Debug: adding lib 
2017/03/20 10:20:21.428 Ombi.Services.Jobs.PlexContentCacher Debug: adding lib 
2017/03/20 10:20:21.482 Ombi.Services.Jobs.PlexContentCacher Debug: adding lib 
2017/03/20 10:20:21.704 Ombi.Services.Jobs.PlexContentCacher Debug: adding lib 
2017/03/20 10:20:21.734 Ombi.Services.Jobs.PlexContentCacher Debug: adding lib 
2017/03/20 10:20:21.803 Ombi.Services.Jobs.PlexContentCacher Debug: adding lib 
2017/03/20 10:20:22.673 Ombi.Services.Jobs.PlexContentCacher Debug: adding lib 
2017/03/20 10:20:22.809 Ombi.Services.Jobs.PlexContentCacher Debug: adding lib 
2017/03/20 10:20:23.693 Ombi.Services.Jobs.PlexContentCacher Debug: adding lib 
2017/03/20 10:20:23.755 Ombi.Services.Jobs.PlexContentCacher Debug: adding lib 
2017/03/20 10:20:23.772 Ombi.Services.Jobs.PlexContentCacher Debug: Going through all the items now 
2017/03/20 10:20:23.788 Ombi.Services.Jobs.PlexContentCacher Debug: Item count 12 
2017/03/20 10:20:47.479 Ombi.Services.Jobs.PlexContentCacher Debug: done all that, moving onto the DB now 
2017/03/20 10:20:47.534 Ombi.Services.Jobs.PlexContentCacher Debug: Exception: 
2017/03/20 10:20:47.552 Ombi.Services.Jobs.PlexContentCacher Debug: Mono.Data.Sqlite.SqliteException (0x80004005): SQLite error
table PlexContent has no column named ItemId
   at Mono.Data.Sqlite.SQLite3.Prepare(SqliteConnection cnn, String strSql, SqliteStatement previous, UInt32 timeoutMS, String& strRemain)
   at Mono.Data.Sqlite.SqliteCommand.BuildNextCommand()
   at Mono.Data.Sqlite.SqliteCommand.GetStatement(Int32 index)
   at Mono.Data.Sqlite.SqliteDataReader.NextResult()
   at Mono.Data.Sqlite.SqliteDataReader..ctor(SqliteCommand cmd, CommandBehavior behave)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command)
   at SQLiteAdapter.Insert(IDbConnection connection, IDbTransaction transaction, Nullable`1 commandTimeout, String tableName, String columnList, String parameterList, IEnumerable`1 keyProperties, Object entityToInsert)
   at Dapper.Contrib.Extensions.SqlMapperExtensions.Insert[T](IDbConnection connection, T entityToInsert, IDbTransaction transaction, Nullable`1 commandTimeout)
   at Ombi.Store.Repository.BaseGenericRepository`1.Insert(T entity) in C:\projects\requestplex\Ombi.Store\Repository\BaseGenericRepository.cs:line 99
   at Ombi.Services.Jobs.PlexContentCacher.CachedLibraries(PlexSettings plexSettings) in C:\projects\requestplex\Ombi.Services\Jobs\PlexContentCacher.cs:line 272 Mono.Data.Sqlite.SqliteException (0x80004005): SQLite error
table PlexContent has no column named ItemId
   at Mono.Data.Sqlite.SQLite3.Prepare(SqliteConnection cnn, String strSql, SqliteStatement previous, UInt32 timeoutMS, String& strRemain)
   at Mono.Data.Sqlite.SqliteCommand.BuildNextCommand()
   at Mono.Data.Sqlite.SqliteCommand.GetStatement(Int32 index)
   at Mono.Data.Sqlite.SqliteDataReader.NextResult()
   at Mono.Data.Sqlite.SqliteDataReader..ctor(SqliteCommand cmd, CommandBehavior behave)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command)
   at SQLiteAdapter.Insert(IDbConnection connection, IDbTransaction transaction, Nullable`1 commandTimeout, String tableName, String columnList, String parameterList, IEnumerable`1 keyProperties, Object entityToInsert)
   at Dapper.Contrib.Extensions.SqlMapperExtensions.Insert[T](IDbConnection connection, T entityToInsert, IDbTransaction transaction, Nullable`1 commandTimeout)
   at Ombi.Store.Repository.BaseGenericRepository`1.Insert(T entity) in C:\projects\requestplex\Ombi.Store\Repository\BaseGenericRepository.cs:line 99
   at Ombi.Services.Jobs.PlexContentCacher.CachedLibraries(PlexSettings plexSettings) in C:\projects\requestplex\Ombi.Services\Jobs\PlexContentCacher.cs:line 272
2017/03/20 10:20:47.574 Ombi.Services.Jobs.PlexContentCacher Error: Failed to obtain Plex libraries Mono.Data.Sqlite.SqliteException (0x80004005): SQLite error
table PlexContent has no column named ItemId
   at Mono.Data.Sqlite.SQLite3.Prepare(SqliteConnection cnn, String strSql, SqliteStatement previous, UInt32 timeoutMS, String& strRemain)
   at Mono.Data.Sqlite.SqliteCommand.BuildNextCommand()
   at Mono.Data.Sqlite.SqliteCommand.GetStatement(Int32 index)
   at Mono.Data.Sqlite.SqliteDataReader.NextResult()
   at Mono.Data.Sqlite.SqliteDataReader..ctor(SqliteCommand cmd, CommandBehavior behave)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command)
   at SQLiteAdapter.Insert(IDbConnection connection, IDbTransaction transaction, Nullable`1 commandTimeout, String tableName, String columnList, String parameterList, IEnumerable`1 keyProperties, Object entityToInsert)
   at Dapper.Contrib.Extensions.SqlMapperExtensions.Insert[T](IDbConnection connection, T entityToInsert, IDbTransaction transaction, Nullable`1 commandTimeout)
   at Ombi.Store.Repository.BaseGenericRepository`1.Insert(T entity) in C:\projects\requestplex\Ombi.Store\Repository\BaseGenericRepository.cs:line 99
   at Ombi.Services.Jobs.PlexContentCacher.CachedLibraries(PlexSettings plexSettings) in C:\projects\requestplex\Ombi.Services\Jobs\PlexContentCacher.cs:line 272
2017/03/20 10:23:42.385 Ombi.Services.Jobs.PlexAvailabilityChecker Debug: Requests that will be updated count 0 
`

**Comment by SuperPotatoMen** [comment]
Pleas follow the fix over here to fix it manauly: https://github.com/tidusjar/Ombi/issues/1237


@tidusjar can we make a migration script for the database that is checking if the database has a column named ItemId and make it anyway's if it doesn't exist? This is the 3 report (including myself) with this problem.

**Comment by camwise** [comment]
Ok following that fix from #1237 did fix it for me.  Thanks!  Sorry i missed it before submitting.

**Comment by SuperPotatoMen** [comment]
@camwise you can't know that. the search function on github is not very good ;)

**Comment by tidusjar** [comment]
There is a migration script. But it is my runs once so it's not run for you
guys!
