### ISSUE TITLE
Radarr cacher fails everytime

### ISSUE THREAD

**Issue by SuperPotatoMen** [tidusjar/Ombi#1274]
#### Ombi Version:

V2.1.1538

#### Update Branch:

development

#### Media Sever:

Plex

#### Media Server Version:

1.5

#### Operating System:

(Place text here)

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

2017/03/20 19:06:32.170 Ombi.Services.Jobs.RadarrCacher Error: Failed caching queued items from Radarr Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Ombi.Api.Models.Radarr.RadarrMovieContainer' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.RadarrApi.GetMovies(String apiKey, Uri baseUrl) in C:\projects\requestplex\Ombi.Api\RadarrApi.cs:line 166
   at Ombi.Services.Jobs.RadarrCacher.Queued() in C:\projects\requestplex\Ombi.Services\Jobs\RadarrCacher.cs:line 60
```

#### Problem Description:

Radarr cacher fails everytime. Api change?

**Comment by tidusjar** [comment]
Radarr version?

**Comment by SuperPotatoMen** [comment]
@tidusjar  v0.2.0.535

**Comment by tidusjar** [comment]
There were API changes in the Radarr develop branch. I made changed to support that

**Comment by SuperPotatoMen** [comment]
@tidusjar thanks :)
