### ISSUE TITLE
Notification Errors

### ISSUE THREAD

**Issue by leveraged7** [tidusjar/Ombi#1292]
#### Ombi Version:

V 2.1.1554

#### Update Branch:

Early Access Preview

#### Media Sever:

Plex

#### Media Server Version:
1.5.1.3520

#### Operating System:

Win 10 - Prof

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)


2017/03/28 12:58:02.452 Ombi.Services.Notification.NotificationService Error: Notification 'EmailMessageNotification' failed with exception System.InvalidCastException: Unable to cast object of type 'Ombi.Core.SettingModels.PushbulletNotificationSettings' to type 'Ombi.Core.SettingModels.EmailNotificationSettings'.
   at Ombi.Services.Notification.BaseNotification`1.<NotifyAsync>d__8.MoveNext() in C:\projects\requestplex\Ombi.Services\Notification\BaseNotification.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Services.Notification.NotificationService.<NotifyAsync>d__9.MoveNext() in C:\projects\requestplex\Ombi.Services\Notification\NotificationService.cs:line 95
2017/03/28 12:58:02.910 Ombi.Services.Notification.PushbulletNotification Error: Pushbullet api returned a null value, the notification did not get pushed 
2017/03/28 13:01:43.138 Ombi.Services.Notification.NotificationService Error: Notification 'EmailMessageNotification' failed with exception System.InvalidCastException: Unable to cast object of type 'Ombi.Core.SettingModels.PushbulletNotificationSettings' to type 'Ombi.Core.SettingModels.EmailNotificationSettings'.
   at Ombi.Services.Notification.BaseNotification`1.<NotifyAsync>d__8.MoveNext() in C:\projects\requestplex\Ombi.Services\Notification\BaseNotification.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Services.Notification.NotificationService.<NotifyAsync>d__9.MoveNext() in C:\projects\requestplex\Ombi.Services\Notification\NotificationService.cs:line 95
2017/03/28 13:01:44.480 Ombi.Services.Notification.PushbulletNotification Error: Pushbullet api returned a null value, the notification did not get pushed 
2017/03/28 13:02:27.965 Ombi.Services.Notification.NotificationService Error: Notification 'EmailMessageNotification' failed with exception System.InvalidCastException: Unable to cast object of type 'Ombi.Core.SettingModels.PushbulletNotificationSettings' to type 'Ombi.Core.SettingModels.EmailNotificationSettings'.
   at Ombi.Services.Notification.BaseNotification`1.<NotifyAsync>d__8.MoveNext() in C:\projects\requestplex\Ombi.Services\Notification\BaseNotification.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Services.Notification.NotificationService.<NotifyAsync>d__9.MoveNext() in C:\projects\requestplex\Ombi.Services\Notification\NotificationService.cs:line 95
2017/03/28 13:02:28.227 Ombi.Services.Notification.PushbulletNotification Error: Pushbullet api returned a null value, the notification did not get pushed 
2017/03/28 13:03:17.976 Ombi.UI.Modules.Admin.AdminModule Debug: Clicked Admin Mass Email Test 
2017/03/28 13:03:28.866 Ombi.UI.Modules.Admin.AdminModule Debug: Clicked Admin Mass Email Test 
2017/03/28 13:03:28.886 Ombi.Services.Jobs.RecentlyAddedNewsletter.RecentlyAddedNewsletter Debug: Starting Mass Email Test 
2017/03/28 13:03:28.940 Ombi.Services.Jobs.RecentlyAddedNewsletter.RecentlyAddedNewsletter Debug: Created Plain/HTML MIME body 
2017/03/28 13:03:29.742 Ombi.Services.Jobs.RecentlyAddedNewsletter.RecentlyAddedNewsletter Debug: Sending 
2017/03/28 13:03:30.695 Ombi.Services.Jobs.RecentlyAddedNewsletter.RecentlyAddedNewsletter Debug: Sent 


```

#### Problem Description:

So the Pushbullet Test Notification works GREAT! Also, the Mass Email Test Email Works great. I added several movies over the weekend and earlier this morning, so I figured when I ran the test newsletter email it would pick it up and send me an email. It did not. Also, I received a notification from within the Ombi App that the test email failed with exception. So I pulled the logs and I noticed that it says **"C:\projects\requestplex\..."** 

I don't have that folder on my system and never had it actually. So I don't know if that is contributing to anything or not, BUT ... I'm not the programming Jedi Masters that y'all are, so it could be m00t point.

**By the way, Ombi hasn't sent a Newsletter in a while despite media being added via the App itself and manually.** (I know that's that another issue but in the event it pertains to this issue, I am mentioning it.)
#### Reproduction Steps:

Run a test mass email, test push bullet notification, test newsletter setting.
As always, THANKS AGAIN FOR AN AMAZING APP!

**Comment by tidusjar** [comment]
HI,

Don't worry about "C:\projects\requestplex..." that is where the code is compiled on the build server.

**Comment by tidusjar** [comment]
I have fixed your error.

But you are having issues with the Newsletter though right? The error is unrelated to the newsletter.

**Comment by leveraged7** [comment]
Jamie,
  Yeah I am having issues with the Newsletter. I figured it was unrelated, I included that info in the event they were related. Thanks again for everything. I will go ahead and close this out.
