### ISSUE TITLE
Ombi has stopped working

### ISSUE THREAD

**Issue by Rakan-10** [tidusjar/Ombi#1306]
#### Ombi Version:

2.1.0

#### Update Branch:

Stable

#### Media Sever:

Plex 

#### Media Server Version:

v1.5.2.3557

#### Operating System:

Windows 10

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

Starting Up! Please wait, this can usually take a few seconds.
Version: 2.1.1577
Location of the database: C:\Ombi\Ombi.sqlite
no configuration section <common/logging> found - suppressing logging output
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.HttpListenerException: Failed to listen on prefix 'http://+:3579/' because it conflicts with an existing registration on the machine.
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at Microsoft.Owin.Host.HttpListener.OwinHttpListener.Start(HttpListener listener, Func`2 appFunc, IList`1 addresses, IDictionary`2 capabilities, Func`2 loggerFactory)
   at Microsoft.Owin.Host.HttpListener.OwinServerFactory.Create(Func`2 app, IDictionary`2 properties)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Owin.Hosting.ServerFactory.ServerFactoryAdapter.Create(IAppBuilder builder)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.StartServer(StartContext context)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
   at Microsoft.Owin.Hosting.Starter.DirectHostingStarter.Start(StartOptions options)
   at Microsoft.Owin.Hosting.Starter.HostingStarter.Start(StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.StartImplementation(IServiceProvider services, StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.Start(StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.Start[TStartup](StartOptions options)
   at Ombi.UI.Program.Main(String[] args) in C:\projects\requestplex\Ombi.UI\Program.cs:line 90

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.HttpListenerException: Failed to listen on prefix 'http://+:3579/' because it conflicts with an existing registration on the machine.
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at Microsoft.Owin.Host.HttpListener.OwinHttpListener.Start(HttpListener listener, Func`2 appFunc, IList`1 addresses, IDictionary`2 capabilities, Func`2 loggerFactory)
   at Microsoft.Owin.Host.HttpListener.OwinServerFactory.Create(Func`2 app, IDictionary`2 properties)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Owin.Hosting.ServerFactory.ServerFactoryAdapter.Create(IAppBuilder builder)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.StartServer(StartContext context)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
   at Microsoft.Owin.Hosting.Starter.DirectHostingStarter.Start(StartOptions options)
   at Microsoft.Owin.Hosting.Starter.HostingStarter.Start(StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.StartImplementation(IServiceProvider services, StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.Start(StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.Start[TStartup](StartOptions options)
   at Ombi.UI.Program.Main(String[] args) in C:\projects\requestplex\Ombi.UI\Program.cs:line 122

```

#### Problem Description:

"Ombi has stopped working"

ِNote that there is no "Unblock" option to uncheck in the zip file properties window.

I'm new to Ombi so i just jumped into the latest version (2.1) with the new name.

<img width="1680" alt="screen shot 2017-03-30 at 11 08 25 am" src="https://cloud.githubusercontent.com/assets/26788123/24494494/20aca18a-153b-11e7-810b-075e6bffa16e.png">
<img width="313" alt="screen shot 2017-03-30 at 11 08 48 am" src="https://cloud.githubusercontent.com/assets/26788123/24494493/20abd5d4-153b-11e7-95d8-a14d32000f5c.png">

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Looks like the port 3579 is already being used.

**Comment by Rakan-10** [comment]
thanks for your replay, is there a workaround for this?

**Comment by tidusjar** [comment]
You can change the port by specifying the following in the startup `-p portNumber`

e.g. 
```
Ombi.exe -p 8080
```

**Comment by Rakan-10** [comment]
I'm really sorry if i sounding like an stupid but is that what you mean?  

![Uploading Screen Shot 2017-03-30 at 11.50.58 AM.png…]()

**Comment by SuperPotatoMen** [comment]
You didn't run it on administration rights. The error say it already: "access is denied"

**Comment by Rakan-10** [comment]
it worked, thanks guys, looks awesome.
