### ISSUE TITLE
Newsletter - Blank Template

### ISSUE THREAD

**Issue by lewisco** [tidusjar/Ombi#1314]
#### Ombi Version:

V 2.2.0

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Media Server Version:

V 1.5.1.3520-ed60c70d6

#### Operating System:

Windows Server 2016 Standard

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

2017/03/31 09:31:02.756 Ombi.Services.Jobs.RecentlyAddedNewsletter.RecentlyAddedNewsletter Info: sending message to  
 from: "*****@*****.com" <*****@*****.com>
 Are we authenticated: True 
2017/03/31 09:31:32.078 Ombi.UI.Modules.Admin.AdminModule Debug: Clicked Admin Newsletter Email Test 
2017/03/31 09:31:32.109 Ombi.Services.Jobs.RecentlyAddedNewsletter.RecentlyAddedNewsletter Debug: Starting Recently Added Newsletter Test 
2017/03/31 09:31:32.312 Ombi.Services.Jobs.RecentlyAddedNewsletter.PlexRecentlyAddedNewsletter Debug: Loaded the template 
2017/03/31 09:31:32.328 Ombi.Services.Jobs.RecentlyAddedNewsletter.PlexRecentlyAddedNewsletter Debug: <!doctype html><html><head>    <meta name="viewport" content="width=device-width" />    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />    <title>Ombi</title>    <style media="all" type="text/css">        @media all {            .btn-primary table td:hover {                background-color: #34495e !important;            }            .btn-primary a:hover {                background-color: #34495e !important;                border-color: #34495e !important;            }        }        @media all {            .btn-secondary a:hover {                border-color: #34495e !important;                color: #34495e !important;            }        }        @media only screen and (max-width: 620px) {            table[class=body] h1 {                font-size: 28px !important;                margin-bottom: 10px !important;            }            table[class=body] h2 {                font-size: 22px !important;                margin-bottom: 10px !important;            }            table[class=body] h3 {                font-size: 16px !important;                margin-bottom: 10px !important;            }            table[class=body] p,            table[class=body] ul,            table[class=body] ol,            table[class=body] td,            table[class=body] span,            table[class=body] a {                font-size: 16px !important;            }            table[class=body] .wrapper,            table[class=body] .article {                padding: 10px !important;            }            table[class=body] .content {                padding: 0 !important;            }            table[class=body] .container {                padding: 0 !important;                width: 100% !important;            }            table[class=body] .header {                margin-bottom: 10px !important;            }            table[class=body] .main {                border-left-width: 0 !important;                border-radius: 0 !important;                border-right-width: 0 !important;            }            table[class=body] .btn table {                width: 100% !important;            }            table[class=body] .btn a {                width: 100% !important;            }            table[class=body] .img-responsive {                height: auto !important;                max-width: 100% !important;                width: auto !important;            }            table[class=body] .alert td {                border-radius: 0 !important;                padding: 10px !important;            }            table[class=body] .span-2,            table[class=body] .span-3 {                max-width: none !important;                width: 100% !important;            }            table[class=body] .receipt {                width: 100% !important;            }        }        @media all {            .ExternalClass {                width: 100%;            }                .ExternalClass,                .ExternalClass p,                .ExternalClass span,                .ExternalClass font,                .ExternalClass td,                .ExternalClass div {                    line-height: 100%;                }            .apple-link a {                color: inherit !important;                font-family: inherit !important;                font-size: inherit !important;                font-weight: inherit !important;                line-height: inherit !important;                text-decoration: none !important;            }        }    </style></head><body class="" style="font-family: sans-serif; -webkit-font-smoothing: antialiased; font-size: 14px; line-height: 1.4; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; background-color: #f6f6f6; margin: 0; padding: 0;">    <table border="0" cellpadding="0" cellspacing="0" class="body" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; background-color: #f6f6f6;" width="100%" bgcolor="#f6f6f6">        <tr>            <td style="font-family: sans-serif; font-size: 14px; vertical-align: top;" valign="top">&nbsp;</td>            <td class="container" style="font-family: sans-serif; font-size: 14px; vertical-align: top; display: block; Margin: 0 auto !important; max-width: 580px; padding: 10px; width: 580px;" width="580" valign="top">                <div class="content" style="box-sizing: border-box; display: block; Margin: 0 auto; max-width: 580px; padding: 10px;">                    <!-- START CENTERED WHITE CONTAINER -->                    <span class="preheader" style="color: transparent; display: none; height: 0; max-height: 0; max-width: 0; opacity: 0; overflow: hidden; mso-hide: all; visibility: hidden; width: 0;">Ombi Recently Added</span>                    <table class="main" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; background: #fff; border-radius: 3px;" width="100%">                        <!-- START MAIN CONTENT AREA -->                        <tr>                            <td class="wrapper" style="font-family: sans-serif; font-size: 14px; vertical-align: top; box-sizing: border-box; padding: 20px;" valign="top">                                <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;" width="100%">                                    <tr>                                        <td align="center">                                            <img src="http://i.imgur.com/qQsN78U.png"  width="400px" text-align="center" />                                        </td>                                    </tr>                                    <tr>                                        <td style="font-family: sans-serif; font-size: 14px; vertical-align: top;" valign="top">                                            <br />                                            <br />                                            <p style="font-family: sans-serif; font-size: 20px; font-weight: normal; margin: 0; Margin-bottom: 15px;">Here is a list of Movies and TV Shows that have recently been added!</p>                                        </td>                                    </tr>                                </table>                                                            </td>                        </tr>                        <!-- END MAIN CONTENT AREA -->                    </table>                    <!-- START FOOTER -->                    <div class="footer" style="clear: both; padding-top: 10px; text-align: center; width: 100%;">                        <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;" width="100%">                            <tr>                                <td class="content-block powered-by" style="font-family: sans-serif; vertical-align: top; padding-top: 10px; padding-bottom: 10px; font-size: 12px; color: #999999; text-align: center;" valign="top" align="center">                                    Powered by <a href="https://github.com/tidusjar/Ombi" style="color: #999999;  font-size: 12px; text-align: center; text-decoration: underline;">Ombi</a>                                </td>                            </tr>                        </table>                    </div>                    <!-- END FOOTER -->                    <!-- END CENTERED WHITE CONTAINER -->                </div>            </td>            <td style="font-family: sans-serif; font-size: 14px; vertical-align: top;" valign="top">&nbsp;</td>        </tr>    </table></body></html> 
2017/03/31 09:31:32.359 Ombi.Services.Jobs.RecentlyAddedNewsletter.RecentlyAddedNewsletter Debug: Entering SendNewsletter 
2017/03/31 09:31:32.431 Ombi.Services.Jobs.RecentlyAddedNewsletter.RecentlyAddedNewsletter Debug: Created Plain/HTML MIME body 
2017/03/31 09:31:33.558 Ombi.Services.Jobs.RecentlyAddedNewsletter.RecentlyAddedNewsletter Info: sending message to  
 from: "*****@*****.com" <*****@*****.com>
 Are we authenticated: True 
2017/03/31 09:31:33.590 Ombi.Services.Jobs.RecentlyAddedNewsletter.RecentlyAddedNewsletter Debug: Sending 
2017/03/31 09:31:34.808 Ombi.Services.Jobs.RecentlyAddedNewsletter.RecentlyAddedNewsletter Debug: Sent 


```

#### Problem Description:

The newsletter is just sending a blank template. Using smtp.outlook.com to relay the email.

#### Reproduction Steps:

Clicking Send test email to admin generates a blank email.

I had the same issue on V1.5 Ombi. I've now just started fresh with a new 2.2.0 install and its the same issue.

**Comment by SuperPotatoMen** [comment]
Did the cacher already finished his job?

**Comment by lewisco** [comment]
It has but I'm running the job again now. I am seeing errors in the log referencing a path that does not exist - C:\projects\requestplex\Ombi.Services

My path is C:\Ombi

```

2017/03/31 10:26:04.508 Ombi.Services.Jobs.RecentlyAddedNewsletter.PlexRecentlyAddedNewsletter Error: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Ombi.Services.Jobs.RecentlyAddedNewsletter.PlexRecentlyAddedNewsletter.GenerateMovieHtml(IEnumerable`1 recentlyAddedMovies, StringBuilder sb) in C:\projects\requestplex\Ombi.Services\Jobs\RecentlyAddedNewsletter\PlexRecentlyAddedNewsletter.cs:line 271 System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Ombi.Services.Jobs.RecentlyAddedNewsletter.PlexRecentlyAddedNewsletter.GenerateMovieHtml(IEnumerable`1 recentlyAddedMovies, StringBuilder sb) in C:\projects\requestplex\Ombi.Services\Jobs\RecentlyAddedNewsletter\PlexRecentlyAddedNewsletter.cs:line 271
2017/03/31 10:26:04.508 Ombi.Services.Jobs.RecentlyAddedNewsletter.PlexRecentlyAddedNewsletter Error: Error for movie with IMDB Id = com.plexapp.agents.none://ed4c047d6e5fe2721f4c53f464fe3b055f078661?lang=xn 

```

**Comment by SuperPotatoMen** [comment]
You can ignore the log referencing to that path.

Can you update your issue post with more logs arround the Value cannot be null?

**Comment by lewisco** [comment]
It just repeats the same block

```

2017/03/31 10:37:50.415 Ombi.Services.Jobs.RecentlyAddedNewsletter.PlexRecentlyAddedNewsletter Error: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Ombi.Services.Jobs.RecentlyAddedNewsletter.PlexRecentlyAddedNewsletter.GenerateMovieHtml(IEnumerable`1 recentlyAddedMovies, StringBuilder sb) in C:\projects\requestplex\Ombi.Services\Jobs\RecentlyAddedNewsletter\PlexRecentlyAddedNewsletter.cs:line 271 System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Ombi.Services.Jobs.RecentlyAddedNewsletter.PlexRecentlyAddedNewsletter.GenerateMovieHtml(IEnumerable`1 recentlyAddedMovies, StringBuilder sb) in C:\projects\requestplex\Ombi.Services\Jobs\RecentlyAddedNewsletter\PlexRecentlyAddedNewsletter.cs:line 271


```

I've ran the Plex Catcher job again and then run the email and now I get a message with all the lines and loads of movies that I don't recognize so thats better, same as the other issues now. Can probably close this.

**Comment by SuperPotatoMen** [comment]
The first time you run it you get all of your stuff in the email. the next time it will be good.

Pleas open a new issue if isn't
