### ISSUE TITLE
Admin and users can't login

### ISSUE THREAD

**Issue by jtpavlock** [tidusjar/Ombi#1336]
#### Ombi Version:

V 2.2.0

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Media Server Version:

1.4.4.3495

#### Operating System:

Windows 10

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

2017/04/03 06:31:01.666 Ombi.Api.ApiRequest Error: System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexFriends.Read5_MediaContainer()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at Ombi.Api.ApiRequest.DeserializeXml[T](String input) in C:\projects\requestplex\Ombi.Api\ApiRequest.cs:line 107 System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexFriends.Read5_MediaContainer()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at Ombi.Api.ApiRequest.DeserializeXml[T](String input) in C:\projects\requestplex\Ombi.Api\ApiRequest.cs:line 107

```

this is the best I can do from /logs/ since I can't access them on the site

#### Problem Description:

Myself (admin) and users can't login to service. After entering username and hitting login, the site pauses for a few seconds before popping up with "Incorrect username or password". Note I am just entering usernames at this stage

#### Reproduction Steps:

Trying to login to the site

**Comment by jtpavlock** [comment]
Don't know why, but for anyone searching I had to navigate to 

server:3579/login?redirect=/userlogin

instead of the main url to get login to work

**Comment by SgtBatten** [comment]
I am now having this exact issue, Thanks for the work around but no one can log in on the standard page.

**Comment by wiscokidd** [comment]
yeah i'm having the same issue. using `server:3579/login?redirect=/userlogin` works fine though.

**Comment by snickbit** [comment]
I'm having the same issue. You can just go to /login and it works fine. The /userlogin address fails. Only annoying because it automatically redirects to /userlogin. For the time being, i've put a link the in the landing page so my users can login conveniently. Hope this is fixed soon.

**Comment by FVGAZI** [comment]
This just happened to me today :(
The work around works, but it's a drag to have to send out a new URL to everyone.

**Comment by apatek1975** [comment]
This just happened to me today. Has anyone found a way to get this back to normal??

**Comment by Dyan654** [comment]
I had this exact same issue after changing my plex password and revoking access to all currently signed in applications. You can fix this by going to http://ip:port/login, logging into your local ombi admin account, and re-authenticating with Plex by generating a new access token.

**Comment by SavageCore** [comment]
Thanks for the work aroun @jtpavlock !
