### ISSUE TITLE
Issue requesting movie via radarr

### ISSUE THREAD

**Issue by kewlrobd** [tidusjar/Ombi#1423]
#### Ombi Version:

V 	2.2.1678

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Operating System:

Windows 2012 R2

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

2017/06/12 11:40:58.826 Ombi.Helpers.Analytics.Analytics Error: System.Net.WebException: The remote name could not be resolved: 'www.google-analytics.com'
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Helpers.Analytics.Analytics.<SendRequestAsync>d__15.MoveNext() in C:\projects\requestplex\Ombi.Helpers\Analytics\Analytics.cs:line 228
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Helpers.Analytics.Analytics.<TrackAsync>d__11.MoveNext() in C:\projects\requestplex\Ombi.Helpers\Analytics\Analytics.cs:line 161
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Helpers.Analytics.Analytics.<TrackEventAsync>d__5.MoveNext() in C:\projects\requestplex\Ombi.Helpers\Analytics\Analytics.cs:line 70 System.Net.WebException: The remote name could not be resolved: 'www.google-analytics.com'
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Helpers.Analytics.Analytics.<SendRequestAsync>d__15.MoveNext() in C:\projects\requestplex\Ombi.Helpers\Analytics\Analytics.cs:line 228
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Helpers.Analytics.Analytics.<TrackAsync>d__11.MoveNext() in C:\projects\requestplex\Ombi.Helpers\Analytics\Analytics.cs:line 161
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Helpers.Analytics.Analytics.<TrackEventAsync>d__5.MoveNext() in C:\projects\requestplex\Ombi.Helpers\Analytics\Analytics.cs:line 70
2017/06/12 11:40:59.076 Ombi.Core.MovieSender Error: 'Profile Id' must be greater than '0'. 


```

#### Problem Description:

When trying to request a movie via Radarr I get the following error, "Could not add movie, please contact your administrator"

#### Reproduction Steps:

I click Request and the error is produced.

**Comment by tidusjar** [comment]
Double check your settings, looks like they are not correct, check the quality profiles too.

**Comment by kewlrobd** [comment]
I just fired up a brand new VM running  ubuntu.  I installed both radarr and ombi and configured from scratch.  I am getting the same exact issue.

**Comment by tidusjar** [comment]
Can you take a screenshot of your settings please?

**Comment by kewlrobd** [comment]
![image](https://user-images.githubusercontent.com/29380205/27085275-d1f86b24-501c-11e7-883e-ea4c9eb9a1de.png)

Here is the Radarr settings within Ombi.  What other settings do you want to see?

**Comment by tidusjar** [comment]
ok,
You need to populate the Quality Profiles and the Default Root Folders.

**Comment by kewlrobd** [comment]
Well that did it.  The strange thing is I didn't have those and thought I had this working for about a day.  Thanks.

**Comment by tidusjar** [comment]
Cool!
