### ISSUE TITLE
Search, TV Shows, Suggestion not generating any suggestions

### ISSUE THREAD

**Issue by TempestF** [tidusjar/Ombi#1428]
#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
2017/06/14 16:32:44.798 Ombi.Api.ApiRequest Trace: Request made to http://api.tvmaze.com/shows/22928/episodes with status code OK. The response was [{"id":992915,"url":"http://www.tvmaze.com/episodes/992915/marvels-inhumans-1x01-episode-1","name":"Episode 1","season":1,"number":1,"airdate":"2017-09-22","airtime":"21:00","airstamp":"2017-09-22T21:00:00-04:00","runtime":60,"image":null,"summary":null,"_links":{"self":{"href":"http://api.tvmaze.com/episodes/992915"}}}] 
2017/06/14 16:32:44.914 Ombi.Api.TvMazeApi Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Api.TvMazeApi.ShowLookupByTheTvDbId(Int32 theTvDbId) in C:\projects\requestplex\Ombi.Api\TvMazeApi.cs:line 87 System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Api.TvMazeApi.ShowLookupByTheTvDbId(Int32 theTvDbId) in C:\projects\requestplex\Ombi.Api\TvMazeApi.cs:line 87

2017/06/14 16:32:46.378 Ombi.Api.TvMazeApi Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Api.TvMazeApi.ShowLookupByTheTvDbId(Int32 theTvDbId) in C:\projects\requestplex\Ombi.Api\TvMazeApi.cs:line 87 System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Api.TvMazeApi.ShowLookupByTheTvDbId(Int32 theTvDbId) in C:\projects\requestplex\Ombi.Api\TvMazeApi.cs:line 87
2017/06/14 16:32:46.495 Ombi.Api.TvMazeApi Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Api.TvMazeApi.ShowLookupByTheTvDbId(Int32 theTvDbId) in C:\projects\requestplex\Ombi.Api\TvMazeApi.cs:line 87 System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Api.TvMazeApi.ShowLookupByTheTvDbId(Int32 theTvDbId) in C:\projects\requestplex\Ombi.Api\TvMazeApi.cs:line 87
2017/06/14 16:32:46.809 Ombi.Api.ApiRequest Trace: Request made to http://api.tvmaze.com/shows/25948/episodes with status code OK. The response was [{"id":1096741,"url":"http://www.tvmaze.com/episodes/1096741/the-gifted-1x01-pilot","name":"Pilot","season":1,"number":1,"airdate":"","airtime":"","airstamp":null,"runtime":60,"image":null,"summary":null,"_links":{"self":{"href":"http://api.tvmaze.com/episodes/1096741"}}}] 
2017/06/14 16:32:46.927 Ombi.Api.TvMazeApi Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Api.TvMazeApi.ShowLookupByTheTvDbId(Int32 theTvDbId) in C:\projects\requestplex\Ombi.Api\TvMazeApi.cs:line 87 System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Api.TvMazeApi.ShowLookupByTheTvDbId(Int32 theTvDbId) in C:\projects\requestplex\Ombi.Api\TvMazeApi.cs:line 87


```

#### Problem Description:

Search -> TV Show ->  Suggestion (any option: Popular, Trending, Most Watched, Most Anticipated). An orange line will go across the top, but no suggestions will show up

#### Reproduction Steps:

Search -> TV Show ->  Suggestion (any option: Popular, Trending, Most Watched, Most Anticipated).
[2017-06-14.txt](https://github.com/tidusjar/Ombi/files/1075895/2017-06-14.txt)

**Comment by jaycedk** [comment]
Just noticed the same issue.

**Comment by TempestF** [comment]
May have been something in the setup.  I completely deleted everything Ombi, re-downloaded the most recent version, Installed, and is now working.
