### ISSUE TITLE
TV Maze Look-Up Not Working

### ISSUE THREAD

**Issue by Glynnryan** [tidusjar/Ombi#1440]
#### Ombi Version:

V 2.2.1678

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Media Server Version:

V 1.7.3.3937

#### Operating System:

Windows 10

#### Mono Version (only if your not on windows)

N/A

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
2017/06/22 07:30:35.289 Ombi.Core.Setup Error: Failed to cache Sonarr quality profiles! System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.Runtime.Caching.MemoryCacheEntry..ctor(String key, Object value, DateTimeOffset absExp, TimeSpan slidingExp, CacheItemPriority priority, Collection`1 dependencies, CacheEntryRemovedCallback removedCallback, MemoryCache cache)
   at System.Runtime.Caching.MemoryCache.AddOrGetExistingInternal(String key, Object value, CacheItemPolicy policy)
   at System.Runtime.Caching.MemoryCache.AddOrGetExisting(CacheItem item, CacheItemPolicy policy)
   at System.Runtime.Caching.MemoryCache.Add(CacheItem item, CacheItemPolicy policy)
   at Ombi.Helpers.MemoryCacheProvider.Set(String key, Object data, Int32 cacheTime) in C:\projects\requestplex\Ombi.Helpers\MemoryCacheProvider.cs:line 114
   at Ombi.Core.Setup.CacheSonarrQualityProfiles(ICacheProvider cacheProvider) in C:\projects\requestplex\Ombi.Core\Setup.cs:line 138
2017/06/22 07:30:35.289 Ombi.Core.Setup Error: Failed to cache Sonarr quality profiles! System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.Runtime.Caching.MemoryCacheEntry..ctor(String key, Object value, DateTimeOffset absExp, TimeSpan slidingExp, CacheItemPriority priority, Collection`1 dependencies, CacheEntryRemovedCallback removedCallback, MemoryCache cache)
   at System.Runtime.Caching.MemoryCache.AddOrGetExistingInternal(String key, Object value, CacheItemPolicy policy)
   at System.Runtime.Caching.MemoryCache.AddOrGetExisting(CacheItem item, CacheItemPolicy policy)
   at System.Runtime.Caching.MemoryCache.Add(CacheItem item, CacheItemPolicy policy)
   at Ombi.Helpers.MemoryCacheProvider.Set(String key, Object data, Int32 cacheTime) in C:\projects\requestplex\Ombi.Helpers\MemoryCacheProvider.cs:line 114
   at Ombi.Core.Setup.CacheRadarrQualityProfiles(ICacheProvider cacheProvider) in C:\projects\requestplex\Ombi.Core\Setup.cs:line 159
2017/06/22 07:30:39.001 Ombi.Api.ApiRequest Error: System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexLibraries.Read4_MediaContainer()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at Ombi.Api.ApiRequest.DeserializeXml[T](String input) in C:\projects\requestplex\Ombi.Api\ApiRequest.cs:line 107 System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexLibraries.Read4_MediaContainer()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at Ombi.Api.ApiRequest.DeserializeXml[T](String input) in C:\projects\requestplex\Ombi.Api\ApiRequest.cs:line 107
2017/06/22 10:13:47.352 Ombi.Api.TvMazeApi Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Api.TvMazeApi.ShowLookupByTheTvDbId(Int32 theTvDbId) in C:\projects\requestplex\Ombi.Api\TvMazeApi.cs:line 92 System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Api.TvMazeApi.ShowLookupByTheTvDbId(Int32 theTvDbId) in C:\projects\requestplex\Ombi.Api\TvMazeApi.cs:line 92
2017/06/22 10:13:49.995 Ombi.Api.TvMazeApi Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Api.TvMazeApi.ShowLookupByTheTvDbId(Int32 theTvDbId) in C:\projects\requestplex\Ombi.Api\TvMazeApi.cs:line 92 System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Api.TvMazeApi.ShowLookupByTheTvDbId(Int32 theTvDbId) in C:\projects\requestplex\Ombi.Api\TvMazeApi.cs:line 92
2017/06/22 10:13:50.222 Ombi.Api.TvMazeApi Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Api.TvMazeApi.ShowLookupByTheTvDbId(Int32 theTvDbId) in C:\projects\requestplex\Ombi.Api\TvMazeApi.cs:line 92 System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Api.TvMazeApi.ShowLookupByTheTvDbId(Int32 theTvDbId) in C:\projects\requestplex\Ombi.Api\TvMazeApi.cs:line 92
2017/06/22 10:13:51.051 Ombi.Api.TvMazeApi Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Api.TvMazeApi.ShowLookupByTheTvDbId(Int32 theTvDbId) in C:\projects\requestplex\Ombi.Api\TvMazeApi.cs:line 92 System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Api.TvMazeApi.ShowLookupByTheTvDbId(Int32 theTvDbId) in C:\projects\requestplex\Ombi.Api\TvMazeApi.cs:line 92
2017/06/22 10:13:51.493 Ombi.Api.TvMazeApi Error: Newtonsoft.Json.JsonSerializationException: Error converting value {null} to type 'System.Double'. Path 'runtime', line 1, position 182. ---> System.InvalidCastException: Null object cannot be converted to a value type.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.TvMazeApi.ShowLookupByTheTvDbId(Int32 theTvDbId) in C:\projects\requestplex\Ombi.Api\TvMazeApi.cs:line 92 Newtonsoft.Json.JsonSerializationException: Error converting value {null} to type 'System.Double'. Path 'runtime', line 1, position 182. ---> System.InvalidCastException: Null object cannot be converted to a value type.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.TvMazeApi.ShowLookupByTheTvDbId(Int32 theTvDbId) in C:\projects\requestplex\Ombi.Api\TvMazeApi.cs:line 92
```

#### Problem Description:

Clicking on a TV series title does not link to the TV Maze website for further information.
From the logs, it appears several jobs are looking to a path located in "C:\projects\requestplex..." however this path does not exist at Ombi is located within C:\Ombi per the installation instructions.

#### Reproduction Steps:

Click on a TV show title from one in the list of TV shows already requested.

**Comment by PotatoQuality** [comment]
Thanks for reporting this in.
Pleas ignore the fact that ombi is pointing to C:\projects\ , thats normal. Its a internal reference of the program.
i can't reproduce your problem.

**Comment by Glynnryan** [comment]
Thanks for getting back @PotatoQuality.

I am able to reproduce the issue as follows:

- Click "Requests" on top left of screen;
- Click on "TV Shows";
- Click on a TV show title:
<img width="471" alt="screen shot 2017-06-26 at 10 42 31" src="https://user-images.githubusercontent.com/24873199/27531274-45a06f1a-5a5c-11e7-8b2a-169da159990d.png">

- 404 Error page loads, trying to connect to IMDB and not TVMaze:
<img width="1013" alt="screen shot 2017-06-26 at 10 42 24" src="https://user-images.githubusercontent.com/24873199/27531253-3877296e-5a5c-11e7-8642-076444171010.png">

**Comment by Glynnryan** [comment]
@PotatoQuality, has this been resolved? Never heard back from ya after the last response...

**Comment by bulbajackel** [comment]
Heya I suggest checking out #1455

**Comment by Glynnryan** [comment]
@bulbajackel aaaah thank you mate. Completely forgot about V3.
