### ISSUE TITLE
cant added movie after updating

### ISSUE THREAD

**Issue by phairplay** [tidusjar/Ombi#1444]
#### Ombi Version:

V 2.2.1678

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Operating System:

windows 10

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

2017/06/24 00:24:31.342 Ombi.Services.Jobs.PlexAvailabilityChecker Debug: Requests that will be updated count 0 
2017/06/24 01:24:31.343 Ombi.Services.Jobs.PlexAvailabilityChecker Debug: Requests that will be updated count 0 
2017/06/24 02:24:31.350 Ombi.Services.Jobs.PlexAvailabilityChecker Debug: Requests that will be updated count 0 
2017/06/24 03:24:31.344 Ombi.Services.Jobs.PlexAvailabilityChecker Debug: Requests that will be updated count 0 
2017/06/24 04:24:31.354 Ombi.Services.Jobs.PlexAvailabilityChecker Debug: Requests that will be updated count 0 
2017/06/24 05:24:31.344 Ombi.Services.Jobs.PlexAvailabilityChecker Debug: Requests that will be updated count 0 
2017/06/24 06:24:31.324 Ombi.Services.Jobs.PlexAvailabilityChecker Debug: Requests that will be updated count 0 
2017/06/24 07:24:31.346 Ombi.Services.Jobs.PlexAvailabilityChecker Debug: Requests that will be updated count 0 
2017/06/24 07:51:45.152 Ombi.Api.ApiRequest Error: System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:8989
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at RestSharp.Http.GetRawResponse(HttpWebRequest request)
   at RestSharp.Http.GetResponse(HttpWebRequest request) System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:8989
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at RestSharp.Http.GetRawResponse(HttpWebRequest request)
   at RestSharp.Http.GetResponse(HttpWebRequest request)
2017/06/24 07:51:45.246 Ombi.Api.SonarrApi Error: Exception when calling GetProfiles for Sonarr, Retrying 00:00:02 Ombi.Helpers.Exceptions.ApiRequestException: Error retrieving response. Check inner details for more info. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:8989
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at RestSharp.Http.GetRawResponse(HttpWebRequest request)
   at RestSharp.Http.GetResponse(HttpWebRequest request)
   --- End of inner exception stack trace ---
   at Ombi.Api.ApiRequest.ExecuteJson[T](IRestRequest request, Uri baseUri) in C:\projects\requestplex\Ombi.Api\ApiRequest.cs:line 116
   at Ombi.Api.SonarrApi.<>c__DisplayClass6_0.<GetProfiles>b__1() in C:\projects\requestplex\Ombi.Api\SonarrApi.cs:line 60
   at Polly.Policy.<>c__DisplayClass8_0`1.<Execute>b__0()
   at Polly.RetrySyntax.<>c__DisplayClass14_0.<WaitAndRetry>b__1()
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`1 action, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory)
2017/06/24 07:51:46.637 Ombi.Api.ApiRequest Error: System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A socket operation was attempted to an unreachable network 192.168.0.21:32400
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at RestSharp.Http.GetRawResponse(HttpWebRequest request)
   at RestSharp.Http.GetResponse(HttpWebRequest request) System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A socket operation was attempted to an unreachable network 192.168.0.21:32400
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at RestSharp.Http.GetRawResponse(HttpWebRequest request)
   at RestSharp.Http.GetResponse(HttpWebRequest request)
2017/06/24 07:51:46.652 Ombi.Api.PlexApi Error: Exception when calling GetLibrarySections for Plex, Retrying 00:00:05 Ombi.Helpers.Exceptions.ApiRequestException: Error retrieving response. Check inner details for more info. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A socket operation was attempted to an unreachable network 192.168.0.21:32400
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at RestSharp.Http.GetRawResponse(HttpWebRequest request)
   at RestSharp.Http.GetResponse(HttpWebRequest request)
   --- End of inner exception stack trace ---
   at Ombi.Api.ApiRequest.ExecuteXml[T](IRestRequest request, Uri baseUri) in C:\projects\requestplex\Ombi.Api\ApiRequest.cs:line 100
   at Ombi.Api.PlexApi.<>c__DisplayClass18_0.<GetLibrarySections>b__0() in C:\projects\requestplex\Ombi.Api\PlexApi.cs:line 168
   at Polly.Policy.<>c__DisplayClass8_0`1.<Execute>b__0()
   at Polly.RetrySyntax.<>c__DisplayClass14_0.<WaitAndRetry>b__1()
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`1 action, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory)
2017/06/24 07:51:52.762 Ombi.Api.ApiRequest Error: System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 192.168.0.21:32400
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at RestSharp.Http.GetRawResponse(HttpWebRequest request)
   at RestSharp.Http.GetResponse(HttpWebRequest request) System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 192.168.0.21:32400
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at RestSharp.Http.GetRawResponse(HttpWebRequest request)
   at RestSharp.Http.GetResponse(HttpWebRequest request)
2017/06/24 07:51:52.762 Ombi.Api.PlexApi Error: Exception when calling GetLibrarySections for Plex, Retrying 00:00:10 Ombi.Helpers.Exceptions.ApiRequestException: Error retrieving response. Check inner details for more info. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 192.168.0.21:32400
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at RestSharp.Http.GetRawResponse(HttpWebRequest request)
   at RestSharp.Http.GetResponse(HttpWebRequest request)
   --- End of inner exception stack trace ---
   at Ombi.Api.ApiRequest.ExecuteXml[T](IRestRequest request, Uri baseUri) in C:\projects\requestplex\Ombi.Api\ApiRequest.cs:line 100
   at Ombi.Api.PlexApi.<>c__DisplayClass18_0.<GetLibrarySections>b__0() in C:\projects\requestplex\Ombi.Api\PlexApi.cs:line 168
   at Polly.Policy.<>c__DisplayClass8_0`1.<Execute>b__0()
   at Polly.RetrySyntax.<>c__DisplayClass14_0.<WaitAndRetry>b__1()
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`1 action, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory)
2017/06/24 07:56:46.559 Ombi.Services.Jobs.PlexAvailabilityChecker Debug: Requests that will be updated count 0 
2017/06/24 07:57:59.449 Ombi.UI.Modules.UserLoginModule Debug: Need to auth 
2017/06/24 07:57:59.902 Ombi.UI.Modules.UserLoginModule Debug: User is the account owner 
2017/06/24 07:58:00.149 Ombi.UI.Modules.UserLoginModule Debug: Friends list result = True 
2017/06/24 07:58:02.202 Ombi.UI.Modules.UserLoginModule Debug: Need to auth and also provide pass 
2017/06/24 07:58:14.663 Ombi.UI.Modules.UserLoginModule Debug: Need to auth and also provide pass 
2017/06/24 07:58:14.894 Ombi.UI.Modules.UserLoginModule Debug: Correct credentials, checking if the user is account owner or in the friends list 
2017/06/24 07:58:15.063 Ombi.UI.Modules.UserLoginModule Debug: User is the account owner 
2017/06/24 07:58:15.163 Ombi.UI.Modules.UserLoginModule Debug: We are authenticated! Setting session. 
2017/06/24 08:00:17.981 Ombi.UI.Modules.UserLoginModule Debug: Need to auth 
2017/06/24 08:00:18.233 Ombi.UI.Modules.UserLoginModule Debug: User is the account owner 
2017/06/24 08:00:18.396 Ombi.UI.Modules.UserLoginModule Debug: Friends list result = True 
2017/06/24 08:00:28.542 Ombi.UI.Modules.UserLoginModule Debug: Need to auth and also provide pass 
2017/06/24 08:00:28.827 Ombi.UI.Modules.UserLoginModule Debug: Correct credentials, checking if the user is account owner or in the friends list 
2017/06/24 08:00:28.926 Ombi.UI.Modules.UserLoginModule Debug: User is the account owner 
2017/06/24 08:00:29.004 Ombi.UI.Modules.UserLoginModule Debug: We are authenticated! Setting session. 
2017/06/24 08:03:30.870 Ombi.Services.Jobs.PlexAvailabilityChecker Debug: Requests that will be updated count 0 
2017/06/24 08:07:23.557 Ombi.Core.Setup Info: Begin executing GetProfiles call to Radarr for quality profiles 
2017/06/24 08:07:25.872 Ombi.Services.Jobs.PlexContentCacher Debug: Getting Lib sections 
2017/06/24 08:07:25.903 Ombi.Services.Jobs.PlexContentCacher Debug: Going through sections now 
2017/06/24 08:07:25.987 Ombi.Services.Jobs.PlexContentCacher Debug: adding lib 
2017/06/24 08:07:26.003 Ombi.Services.Jobs.PlexContentCacher Debug: adding lib 
2017/06/24 08:07:26.037 Ombi.Services.Jobs.PlexContentCacher Debug: adding lib 
2017/06/24 08:07:26.420 Ombi.Services.Jobs.PlexContentCacher Debug: adding lib 
2017/06/24 08:07:26.442 Ombi.Services.Jobs.PlexContentCacher Debug: adding lib 
2017/06/24 08:07:26.457 Ombi.Services.Jobs.PlexContentCacher Debug: adding lib 
2017/06/24 08:07:26.473 Ombi.Services.Jobs.PlexContentCacher Debug: Going through all the items now 
2017/06/24 08:07:26.489 Ombi.Services.Jobs.PlexContentCacher Debug: Item count 6 
2017/06/24 08:07:34.401 Ombi.Services.Jobs.PlexContentCacher Debug: done all that, moving onto the DB now 
2017/06/24 08:07:45.719 Ombi.Services.Jobs.PlexContentCacher Debug: Done movies 
2017/06/24 08:07:46.925 Ombi.Services.Jobs.PlexContentCacher Debug: Done TV 
2017/06/24 08:07:46.958 Ombi.Services.Jobs.PlexContentCacher Debug: Done albums 
2017/06/24 08:07:53.342 Ombi.UI.Modules.UserLoginModule Debug: Need to auth 
2017/06/24 08:07:53.741 Ombi.UI.Modules.UserLoginModule Debug: User is the account owner 
2017/06/24 08:07:53.964 Ombi.UI.Modules.UserLoginModule Debug: Friends list result = True 
2017/06/24 08:08:03.264 Ombi.UI.Modules.UserLoginModule Debug: Need to auth and also provide pass 
2017/06/24 08:08:03.510 Ombi.UI.Modules.UserLoginModule Debug: Correct credentials, checking if the user is account owner or in the friends list 
2017/06/24 08:08:03.610 Ombi.UI.Modules.UserLoginModule Debug: User is the account owner 
2017/06/24 08:08:03.695 Ombi.UI.Modules.UserLoginModule Debug: We are authenticated! Setting session. 
2017/06/24 08:10:12.868 Ombi.Core.MovieSender Error: Invalid Path 
2017/06/24 08:10:39.770 Ombi.Core.MovieSender Error: Invalid Path 
2017/06/24 08:12:25.852 Ombi.Services.Jobs.PlexAvailabilityChecker Debug: Requests that will be updated count 0 
2017/06/24 08:12:56.978 Ombi.Core.MovieSender Error: Invalid Path 
2017/06/24 08:15:29.286 Ombi.Core.MovieSender Error: Invalid Path 


```

#### Problem Description:

cant add movie after updating from 2.1 to 2.21

#### Reproduction Steps:
just updated from 2.1 to 2.21 now i cant add movie i get a message saying to contact the administrator 

i am the administrator and

**Comment by tidusjar** [comment]
Checked your settings?

**Comment by phairplay** [comment]
Yes all good
I'm logged in as admin 
Radarr connection is okay

**Comment by tidusjar** [comment]
` Error: Invalid Path ` Can you save your radarr settings again?

**Comment by phairplay** [comment]
Well dam!
That sorted it 
Many thanks
