### ISSUE TITLE
SQLite error
table PlexContent has no column named ItemId

### ISSUE THREAD

**Issue by didyouexpectthat** [tidusjar/Ombi#1474]
#### Ombi Version
V 2.2.1851
#### Update Branch:
Early Access Preview
#### Operating System:
Windows 8/Windows Server 2012
#### Log Level:
Debug
I upgraded to the Early Access Preview version of Ombi today.
Moved over my PlexRequests.sqlite from older Ombi version.
See log complain about failure to get libraries from Plex.
Notice this error in debug log:

```2017/07/14 18:58:24.335 Ombi.Services.Jobs.PlexContentCacher Debug: Mono.Data.Sqlite.SqliteException (0x80004005): SQLite error
table PlexContent has no column named ItemId
   at Mono.Data.Sqlite.SQLite3.Prepare(SqliteConnection cnn, String strSql, SqliteStatement previous, UInt32 timeoutMS, String& strRemain)
   at Mono.Data.Sqlite.SqliteCommand.BuildNextCommand()
   at Mono.Data.Sqlite.SqliteCommand.GetStatement(Int32 index)
   at Mono.Data.Sqlite.SqliteDataReader.NextResult()
   at Mono.Data.Sqlite.SqliteDataReader..ctor(SqliteCommand cmd, CommandBehavior behave)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command)
   at SQLiteAdapter.Insert(IDbConnection connection, IDbTransaction transaction, Nullable`1 commandTimeout, String tableName, String columnList, String parameterList, IEnumerable`1 keyProperties, Object entityToInsert)
   at Dapper.Contrib.Extensions.SqlMapperExtensions.Insert[T](IDbConnection connection, T entityToInsert, IDbTransaction transaction, Nullable`1 commandTimeout)
   at Ombi.Store.Repository.BaseGenericRepository`1.Insert(T entity) in C:\projects\requestplex\Ombi.Store\Repository\BaseGenericRepository.cs:line 99
   at Ombi.Services.Jobs.PlexContentCacher.CachedLibraries(PlexSettings plexSettings) in C:\projects\requestplex\Ombi.Services\Jobs\PlexContentCacher.cs:line 272 Mono.Data.Sqlite.SqliteException (0x80004005): SQLite error
table PlexContent has no column named ItemId
   at Mono.Data.Sqlite.SQLite3.Prepare(SqliteConnection cnn, String strSql, SqliteStatement previous, UInt32 timeoutMS, String& strRemain)
   at Mono.Data.Sqlite.SqliteCommand.BuildNextCommand()
   at Mono.Data.Sqlite.SqliteCommand.GetStatement(Int32 index)
   at Mono.Data.Sqlite.SqliteDataReader.NextResult()
   at Mono.Data.Sqlite.SqliteDataReader..ctor(SqliteCommand cmd, CommandBehavior behave)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command)
   at SQLiteAdapter.Insert(IDbConnection connection, IDbTransaction transaction, Nullable`1 commandTimeout, String tableName, String columnList, String parameterList, IEnumerable`1 keyProperties, Object entityToInsert)
   at Dapper.Contrib.Extensions.SqlMapperExtensions.Insert[T](IDbConnection connection, T entityToInsert, IDbTransaction transaction, Nullable`1 commandTimeout)
   at Ombi.Store.Repository.BaseGenericRepository`1.Insert(T entity) in C:\projects\requestplex\Ombi.Store\Repository\BaseGenericRepository.cs:line 99
   at Ombi.Services.Jobs.PlexContentCacher.CachedLibraries(PlexSettings plexSettings) in C:\projects\requestplex\Ombi.Services\Jobs\PlexContentCacher.cs:line 272
2017/07/14 18:58:24.413 Ombi.Services.Jobs.PlexContentCacher Error: Failed to obtain Plex libraries Mono.Data.Sqlite.SqliteException (0x80004005): SQLite error
table PlexContent has no column named ItemId
   at Mono.Data.Sqlite.SQLite3.Prepare(SqliteConnection cnn, String strSql, SqliteStatement previous, UInt32 timeoutMS, String& strRemain)
   at Mono.Data.Sqlite.SqliteCommand.BuildNextCommand()
   at Mono.Data.Sqlite.SqliteCommand.GetStatement(Int32 index)
   at Mono.Data.Sqlite.SqliteDataReader.NextResult()
   at Mono.Data.Sqlite.SqliteDataReader..ctor(SqliteCommand cmd, CommandBehavior behave)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command)
   at SQLiteAdapter.Insert(IDbConnection connection, IDbTransaction transaction, Nullable`1 commandTimeout, String tableName, String columnList, String parameterList, IEnumerable`1 keyProperties, Object entityToInsert)
   at Dapper.Contrib.Extensions.SqlMapperExtensions.Insert[T](IDbConnection connection, T entityToInsert, IDbTransaction transaction, Nullable`1 commandTimeout)
   at Ombi.Store.Repository.BaseGenericRepository`1.Insert(T entity) in C:\projects\requestplex\Ombi.Store\Repository\BaseGenericRepository.cs:line 99
   at Ombi.Services.Jobs.PlexContentCacher.CachedLibraries(PlexSettings plexSettings) in C:\projects\requestplex\Ombi.Services\Jobs\PlexContentCacher.cs:line 272
```

```
Application Version:	2.2.1851
OS: Windows 10
System Version:	4.0.30319.42000
Branch:	Early Access Preview
Log Level:	Debug
Database Location:	d:\Ombi\PlexRequests.sqlite
Running Directory:	d:\Ombi
```

**Comment by didyouexpectthat** [comment]
Should I rebuild my SQLite database? Or should the database have gone through an update at some time to include ItemId column name, and didn't?

**Comment by tidusjar** [comment]
Drop that table and restart Ombi
