### ISSUE TITLE
Movie Requests not displaying

### ISSUE THREAD

**Issue by sam-fakhreddine** [tidusjar/Ombi#1479]
#### Ombi Version
V 2.2.1678
#### Update Branch:
Stable
#### Operating System:
Windows 8/Windows Server 2012
#### Log Level:
Error
movie requests do not display

2017/07/30 20:18:18.417 Ombi.UI.Modules.RequestsModule Error: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Ombi.UI.Modules.RequestsModule.<GetMovies>d__57.MoveNext() in C:\projects\requestplex\Ombi.UI\Modules\RequestsModule.cs:line 191 System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Ombi.UI.Modules.RequestsModule.<GetMovies>d__57.MoveNext() in C:\projects\requestplex\Ombi.UI\Modules\RequestsModule.cs:line 191
2017/07/30 20:19:46.338 Ombi.UI.Modules.RequestsModule Error: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Ombi.UI.Modules.RequestsModule.<GetMovies>d__57.MoveNext() in C:\projects\requestplex\Ombi.UI\Modules\RequestsModule.cs:line 191 System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Ombi.UI.Modules.RequestsModule.<GetMovies>d__57.MoveNext() in C:\projects\requestplex\Ombi.UI\Modules\RequestsModule.cs:line 191

**Comment by sam-fakhreddine** [comment]
![ombi error](https://user-images.githubusercontent.com/6999657/28760501-ec0d1092-7564-11e7-851c-fb2b9cd7e7ce.png)

**Comment by tidusjar** [comment]
Can you check you Radarr settings and check your root folders.
