### ISSUE TITLE
Can't login behind reverse proxy

### ISSUE THREAD

**Issue by Grimshad** [tidusjar/Ombi#1483]
!! Version 2.X is not supported anymore. Pleas don't open a issue for the 2.x version.
See https://github.com/tidusjar/Ombi/issues/1455 for more information.

#### Ombi Version:

V 2.2.1

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Operating System:

W10

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):
The logs don't seem to show anything related to this, but here's the error
```
Error Details

Nancy.RequestExecutionException: Oh noes! ---> System.FormatException: Input string was not in a correct format.
at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
at Nancy.DynamicDictionaryValue.op_Implicit(DynamicDictionaryValue dynamicValue)
at Ombi.UI.Modules.UserLoginModule.d__48.MoveNext() in C:\projects\requestplex\Ombi.UI\Modules\UserLoginModule.cs:line 487
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Ombi.UI.Modules.UserLoginModule.<<-ctor>b__0_0>d.MoveNext() in C:\projects\requestplex\Ombi.UI\Modules\UserLoginModule.cs:line 81
--- End of inner exception stack trace ---
at Nancy.NancyEngine.InvokeOnErrorHook(NancyContext context, ErrorPipeline pipeline, Exception ex)

```
Actually this error occurs, not sure if it's related
```
System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.Xml.XmlException: Root element is missing. at System.Xml.XmlTextReaderImpl.Throw(Exception e) at System.Xml.XmlTextReaderImpl.ParseDocumentContent() at System.Xml.XmlTextReaderImpl.Read() at System.Xml.XmlTextReader.Read() at System.Xml.XmlReader.MoveToContent() at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexLibraries.Read4_MediaContainer() --- End of inner exception stack trace --- at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events) at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader) at Ombi.Api.ApiRequest.DeserializeXml[T](String input) in C:\projects\requestplex\Ombi.Api\ApiRequest.cs:line 107
```
#### Problem Description:

After entering username and clicking submit, this error occurs

#### Reproduction Steps:

put ombi behind ssl reverse proxy, attempt to login.

reverse proxy settings
`location /userlogin {
    proxy_pass http://$ip:3000/userlogin
}`

**Comment by PotatoQuality** [comment]
see the text above you reporting
