### ISSUE TITLE
Movies that exist in Radarr, do not show up as requested in search

### ISSUE THREAD

**Issue by jpeters** [tidusjar/Ombi#1560]
Ombi 2098
Radarr 0.2.0.870

If I have a movie that has been added to Radarr and I do a search in Ombi, it gives me the request button. If I click request, it gives an error that it has already been added.

Upon investigation I have found that the RadarrCache table is empty in the database. When RadarrCacher.cs performs the GetMovies function, it gets to the point of JsonConvert.DeserializeObject with the raw Json from the call. Here is the exception that it is throwing.

`{Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path '[2].alternativeTitles', line 177, position 7.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.<Request>d__51.MoveNext() in C:\Users\jpeters\source\repos\Ombi\src\Ombi.Api\Api.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter1.GetResult()
   at Ombi.Api.Radarr.RadarrApi.<GetMovies>d__10.MoveNext() in C:\Users\jpeters\source\repos\Ombi\src\Ombi.Api.Radarr\RadarrApi.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter1.GetResult()
   at Ombi.Schedule.Jobs.Radarr.RadarrCacher.<CacheContent>d__12.MoveNext() in C:\Users\jpeters\source\repos\Ombi\src\Ombi.Schedule\Jobs\Radarr\RadarrCacher.cs:line 44}`

I will look into this further, but thought if anyone knew what it was, they could share some insight.

**Comment by jpeters** [comment]
So the JSON output of the API must have changed between the master branch and the develop branch of Radarr. 

In the master branch, the JSON output has a node that looks similar to:

`"alternativeTitles": [
      "Assassin's Creed: The IMAX Experience"
    ],`

and in the develop branch, it produces this output:

`"alternativeTitles": [
      {
        "sourceType": "tmdb",
        "movieId": 7,
        "title": "Algorithm: The Hacker Movie",
        "sourceId": 281826,
        "votes": 0,
        "voteCount": 0,
        "language": "english",
        "id": 828
      }
    ],`

This does not deserialize properly onto the MovieResponse.cs because it is defined as 
`public List<string> alternativeTitles { get; set; }`

If we are not going to use the alternativeTitles in Ombi, I recommend we just do not attempt to deserialize the alternativeTitles. Otherwise, we may have to do a SystemStatus and then have some switch logic that defines a specific model that derives from MovieResponse, based on the version of Radarr.

I am happy to turn in a PR for either. Please let me know how you would like me to move forward.

**Comment by tidusjar** [comment]
I agree, just remove that property!

**Comment by tidusjar** [comment]
This should now be resolved.

**Comment by dejected1** [comment]
my problem is slightly different perhaps. Im also running the developer branch of radarr and ombi eap. 
If i do a search, i being the admin, it shows that the movie is already requested. If a user does a search, it doesn't show requested and lets the user request a movie that already exists in radarr. then when i try and approve it i get an error saying something went wrong.

**Comment by tidusjar** [comment]
In v3

**Comment by i2fat2kidnap** [comment]
I know that support for v2 has stopped, but I am unable to upgrade to v3 since there isn't 32-bit support yet. Would this be something you can easily do to V2? This is the only issue I have w/Ombi v2 currently.
