### ISSUE TITLE
Ombi 3.0.2111-DotNetCore: Unhandled Exception: System.ArgumentException: The path in 'value' must start with '/'.

### ISSUE THREAD

**Issue by straying1** [tidusjar/Ombi#1572]
Hi,

Whenever I try to start Ombi either manually or through systemd I get the above error. It was working fine yesterday. Ubuntu 17.04
/opt/OmbiV3 has 777 for permissions. Don't think it's a permissions issue.

Here is the full message:
```

Hello, and welcome to the  console application.
This application takes in a data file and attempts to import that data into our systems.
Valid options are:
Ombi 3.0.2111-DotNetCore
Copyright (C) 2017 Ombi

  -h, --host       (Default: http://*:5000) Set to a semicolon-separated (;)
                   list of URL prefixes to which the server should respond. For
                   example, http://localhost:123. Use "*" to indicate that the
                   server should listen for requests on any IP address or
                   hostname using the specified port and protocol (for example,
                   http://*:5000). The protocol (http:// or https://) must be
                   included with each URL. Supported formats vary between
                   servers.

  -s, --storage    Storage path, where we save the logs and database

  --help           Display this help screen.

  --version        Display version information.


Press any key to exit

We are running on
/opt/OmbiV3

Unhandled Exception: System.ArgumentException: The path in 'value' must start with '/'.
Parameter name: value
   at Microsoft.AspNetCore.Http.PathString..ctor(String value)
   at Ombi.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IMemoryCache cache, IServiceProvider serviceProvider) in C:\projects\requestplex\src\Ombi\Startup.cs:line 151
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Ombi.Program.Main(String[] args) in C:\projects\requestplex\src\Ombi\Program.cs:line 64
Aborted

```

Below is my systemd script.
```
[Unit]
Description=Systemd script to run Ombi as a service
After=network-online.target

[Service]
User=ombi
Group=media
WorkingDirectory=/opt/OmbiV3
Type=simple
ExecStart=/opt/OmbiV3/Ombi --host=http://*:3579

[Install]
WantedBy=multi-user.target

```

I am not sure what path 'value' is referencing.

**Comment by tidusjar** [comment]
Any idea what build you were running when it was working?

**Comment by straying1** [comment]
Yesterday, I think it was 3.0.0xxx. But that same build also stopped working this morning. So I thought an update might fix the issue but I guess not.

**Comment by tidusjar** [comment]
Strange, I cannot reproduce this on my end...

**Comment by straying1** [comment]
I blew away my current installation and re-installed Ombi.
It's working now. Still no idea why it would suddenly break like earlier though. I'll go ahead & close this as it's been more or less resolved. ¯\_(ツ)_/¯

Thank you for your prompt attention
