### ISSUE TITLE
serries is not added to Sonarr

### ISSUE THREAD

**Issue by halali** [tidusjar/Ombi#1576]
Hi,

im not able to add approved series to Sonarr
```
fail: Ombi.Core.Senders.TvSender[5001]
      Exception thrown when attempting to send series over to Sonarr
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Ombi.Api.Sonarr.SonarrApi.<GetSeriesById>d__7.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Sonarr\SonarrApi.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Core.Senders.TvSender.<SendToSonarr>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Core\Senders\TvSender.cs:line 155
```
Maybe is not related to this, but in my database is almost 400 000 records in SonarrEpisodeCache table and is increasing every day.

**Comment by tidusjar** [comment]
All the settings correct including profiles?

The sonarr episode cache sounds like a bug. I'll fix that one tomorrow

**Comment by PotatoQuality** [comment]
Use the template pleas instead of deleting it.

**Comment by halali** [comment]
Settings are good.

Now i thinking about that maybe i use unsupported version of sonarr 2.0.0.4991 its phantom release branch.
