### ISSUE TITLE
Exception thrown when attempting to cache the Plex Content

### ISSUE THREAD

**Issue by mannibis** [tidusjar/Ombi#1582]
#### Ombi build Version:

V 3.0.2124-DotNetCore

#### Update Branch:

Open Beta

#### Media Sever:

Plex
#### Operating System:

OSX High Sierra

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentCacher[0]
      Getting all content from server PLEX-Mac
warn: Ombi.Schedule.Jobs.Plex.PlexContentCacher[2000]
      Exception thrown when attempting to cache the Plex Content
System.AggregateException: One or more errors occurred. (The handler does not support custom handling of certificates with this combination of libcurl (7.54.0) and its SSL backend ("LibreSSL/2.0.20").) -$
-> System.PlatformNotSupportedException: The handler does not support custom handling of certificates with this combination of libcurl (7.54.0) and its SSL backend ("LibreSSL/2.0.20").
   at System.Net.Http.CurlHandler.SslProvider.SetSslOptions(EasyRequest easy, ClientCertificateOption clientCertOption)
   at System.Net.Http.CurlHandler.EasyRequest.InitializeCurl()
   at System.Net.Http.CurlHandler.MultiAgent.ActivateNewRequest(EasyRequest easy)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Api.<Request>d__8`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Plex.PlexApi.<GetLibrarySections>d__11.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 68
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Ombi.Schedule.Jobs.Plex.PlexContentCacher.GetAllContent(PlexServers plexSettings) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentCacher.cs:line 226
   at Ombi.Schedule.Jobs.Plex.PlexContentCacher.<StartTheCache>d__17.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentCacher.cs:line 96
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Schedule.Jobs.Plex.PlexContentCacher.<CacheContent>d__16.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentCacher.cs:line 78
---> (Inner Exception #0) System.PlatformNotSupportedException: The handler does not support custom handling of certificates with this combination of libcurl (7.54.0) and its SSL backend ("LibreSSL/2.0.20
").
   at System.Net.Http.CurlHandler.SslProvider.SetSslOptions(EasyRequest easy, ClientCertificateOption clientCertOption)
   at System.Net.Http.CurlHandler.EasyRequest.InitializeCurl()
   at System.Net.Http.CurlHandler.MultiAgent.ActivateNewRequest(EasyRequest easy)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Api.<Request>d__8`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Plex.PlexApi.<GetLibrarySections>d__11.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 68<---

```

#### Problem Description:

While running ./Ombi in tmux, I see this output in the terminal

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
In the Ombi settings. Is the ignore certificate errors enabled or disabled?

**Comment by mannibis** [comment]
Ignore cert errors is enabled but I still get this error.

**Comment by mannibis** [comment]
I also get this error (or similar) when running the Plex user importer.

See logs: https://pastebin.com/VMjxxQHM

**Comment by mannibis** [comment]
And now after re-trying to load my PLex Server in settings, it's telling me my user/pass is not correct, even though it had previously loaded the server just fine.

**Comment by tidusjar** [comment]
The error is interesting. 

The handler does not support custom handling of certificates with this combination of libcurl (7.54.0) and its SSL backend ("LibreSSL/2.0.20").

What version of libcurl, openssl and libressl do you have installed?

**Comment by PotatoQuality** [comment]
@mannibis do you already have more information for us?
