### ISSUE TITLE
Can't add to service, only mark as "Available" (throw SSL errors in log too)

### ISSUE THREAD

**Issue by Arno500** [tidusjar/Ombi#1591]
#### Ombi build Version:

V 3.0.2143

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Arch Linux with the latest zen kernel (4.13.7-1)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
2017-10-18 17:27:36.003 +02:00 [Information] Start installing Hangfire SQL objects...
2017-10-18 17:27:36.152 +02:00 [Information] Hangfire SQL objects installed.
2017-10-18 17:27:36.222 +02:00 [Information] Starting Hangfire Server
2017-10-18 17:27:36.231 +02:00 [Information] Using job storage: 'SQLite Server: Ombi.db'
2017-10-18 17:27:36.231 +02:00 [Information] Using the following options for Hangfire Server:
2017-10-18 17:27:36.231 +02:00 [Information]     Worker count: 1
2017-10-18 17:27:36.232 +02:00 [Information]     Listening queues: 'default'
2017-10-18 17:27:36.232 +02:00 [Information]     Shutdown timeout: 00:00:15
2017-10-18 17:27:36.232 +02:00 [Information]     Schedule polling interval: 00:00:15
2017-10-18 17:30:11.999 +02:00 [Warning] Failed to process the job '47': an exception occurred. Retry attempt 1 of 3 will be performed in 00:00:21.
System.PlatformNotSupportedException: The handler does not support custom handling of certificates with this combination of libcurl (7.56.0) and its SSL backend ("OpenSSL/1.1.0f").
   at System.Net.Http.CurlHandler.SslProvider.SetSslOptionsForUnsupportedBackend(EasyRequest easy, ClientCertificateProvider certProvider)
   at System.Net.Http.CurlHandler.SslProvider.SetSslOptions(EasyRequest easy, ClientCertificateOption clientCertOption)
   at System.Net.Http.CurlHandler.EasyRequest.InitializeCurl()
   at System.Net.Http.CurlHandler.MultiAgent.ActivateNewRequest(EasyRequest easy)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Api.<Request>d__8`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.CouchPotato.CouchPotatoApi.<GetMovies>d__6.MoveNext() in C:\projects\requestplex\src\Ombi.Api.CouchPotato\CouchPotatoApi.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Schedule.Jobs.Couchpotato.CouchPotatoCacher.<Start>d__5.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Couchpotato\CouchPotatoCacher.cs:line 101
2017-10-18 17:30:44.257 +02:00 [Information] 1 scheduled job(s) enqueued.
2017-10-18 17:30:59.218 +02:00 [Warning] Failed to process the job '47': an exception occurred. Retry attempt 2 of 3 will be performed in 00:01:02.

```

#### Problem Description:

I can't add movies to CouchPotato, it only allows to "Mark available" and search doesn't work everytime.

#### Reproduction Steps:

Configure a provider like CouchPotato and add a request. Just use it normally...

**Comment by tidusjar** [comment]
Can you please explain,

Can't add movies to CouchPotato? They do not show up in couch once you have requested/approved them?

What do you mean it only allows "Mark available" and search doesn't work.
What search?

**Comment by Arno500** [comment]
I only have the buttons "Mark Available" and "Remove" not "Accept", or anything like that.For search, I just don't have any results, and the spinner doesn't appear to show that it "process" the search.I can't test latest version now, because my server just died (probably because of Ombi as it stopped responding the instant I accessed it), so we'll need to wait Saturday.Le 19 oct. 2017 9:04 AM, Jamie <notifications@github.com> a écrit :Can you please explain,
Can't add movies to CouchPotato? They do not show up in couch once you have requested/approved them?
What do you mean it only allows "Mark available" and search doesn't work.
What search?

**Comment by tidusjar** [comment]
So the reason you do not have the "Accept" is because an admin requested that content. Administrators get approved automatically.

Please update to the latest version and after that:

Regarding the search that seems unusual. Can you check the browsers console.

I'm going to close this until you get back to me on this.

**Comment by Arno500** [comment]
My bad for adding content, it was perfectly sent to services, as I was admin.
For the search thought, couldn't resolve this, and I couldn't even access the login page on my computer (500 Internal Error in the console).
Then, I delete the old database, reconfigured Ombi, and everything started working fine !

Maybe you should indicate in the docs or README that every build can corrupt the database, and maybe needs resets from time to time.

Thanks you anyway, for the hard work you put in revamping a really good service ! (it's just painfully slow, tho, even when doing only basic things, we're not talking about Wolfram Alpha, or even Plex is faster at rendering web pages and content)
