### ISSUE TITLE
Cannot connect to Plex server

### ISSUE THREAD

**Issue by aka-charos** [tidusjar/Ombi#1593]
#### Ombi build Version:
V 3.0.2144
#### Update Branch:
Open Beta
#### Media Sever: 
Plex
#### Media Server Version: 
1.9.5.4339 
#### Operating System: 
Ubuntu 16.04

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):
root@localhost:/opt/ombi/Logs# cat log-20171018.txt
2017-10-18 19:16:36.998 -04:00 [Information] Start installing Hangfire SQL objects...
2017-10-18 19:16:37.060 -04:00 [Information] Hangfire SQL objects installed.
2017-10-18 19:16:37.088 -04:00 [Information] Starting Hangfire Server
2017-10-18 19:16:37.091 -04:00 [Information] Using job storage: 'SQLite Server: Ombi.db'
2017-10-18 19:16:37.092 -04:00 [Information] Using the following options for Hangfire Server:
2017-10-18 19:16:37.092 -04:00 [Information]     Worker count: 1
2017-10-18 19:16:37.092 -04:00 [Information]     Listening queues: 'default'
2017-10-18 19:16:37.092 -04:00 [Information]     Shutdown timeout: 00:00:15
2017-10-18 19:16:37.093 -04:00 [Information]     Schedule polling interval: 00:00:15
2017-10-18 19:17:17.147 -04:00 [Error] Could not test Plex
System.TypeInitializationException: The type initializer for 'System.Net.Http.CurlHandler' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Http' threw an exception. ---> System.TypeInitializationException: The type initializer for 'HttpInitializer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Net.Http.Native': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.Http.GetSslVersionDescription()
   at Interop.HttpInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.Http..cctor()
   --- End of inner exception stack trace ---
   at Interop.Http.GetSupportedFeatures()
   at System.Net.Http.CurlHandler..cctor()
   --- End of inner exception stack trace ---
   at System.Net.Http.CurlHandler..ctor()
   at System.Net.Http.HttpClientHandler..ctor()
   at Ombi.Api.Api.<GetHandler>d__6.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Api.<Request>d__8`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Plex.PlexApi.<GetStatus>d__9.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<Plex>d__49.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 201
2017-10-18 19:17:46.706 -04:00 [Error] Could not test Plex
System.TypeInitializationException: The type initializer for 'System.Net.Http.CurlHandler' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Http' threw an exception. ---> System.TypeInitializationException: The type initializer for 'HttpInitializer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Net.Http.Native': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.Http.GetSslVersionDescription()
   at Interop.HttpInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.Http..cctor()
   --- End of inner exception stack trace ---
   at Interop.Http.GetSupportedFeatures()
   at System.Net.Http.CurlHandler..cctor()
   --- End of inner exception stack trace ---
   at System.Net.Http.CurlHandler..ctor()
   at System.Net.Http.HttpClientHandler..ctor()
   at Ombi.Api.Api.<GetHandler>d__6.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Api.<Request>d__8`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Plex.PlexApi.<GetStatus>d__9.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<Plex>d__49.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 201
2017-10-18 19:17:59.607 -04:00 [Information] Hangfire Server stopped.
root@localhost:/opt/ombi/Logs# 

#### Problem Description: 
Plex server and Ombi reside on the same vps. Plex is up and running on default port.
- Ombi setup wizard does not pickup the request token although username and password are correct. Nothing happens (no error) but it can't connect.
- I skip the server selection and create the admin account to manually add the Plex server. Although all settings are correct, Ombi keeps complaining about wrong username/pass. 

The log error "System.DllNotFoundException: Unable to load DLL 'System.Net.Http.Native': The specified module or one of its dependencies could not be found." seems in relation to the issue.

#### Reproduction Steps:
-Downloaded latest build and extracted. Run ./.Ombi on ssh and fire up the browser for the wizard .
-Wizard does not work  (token) with my Plex server so I skip the server selection
-Create admin account and try to manually add the server.
- Added all settings including Plex Authorization Token and Machine Identifier (from Plex preference file) yet "test connectivity"  or "load server" fails.

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by gold007eye** [comment]
I am just starting to try V3 tonight and have just about the same results with slight variation.  I am able to get a Plex token successfully during the setup wizard, but than after that if I go to settings --> Media Server --> Plex and then try and click "Test Connectivity" I get "We could not connect to the Plex server".  If I try "Load Libraries" I get: "An error occurred while sending the request.  A connection to the server could not be established."

Server information even populates correctly other than I had to check SSL.

**Comment by tidusjar** [comment]
Run apt-get install libcurl4-openssl-dev

**Comment by gold007eye** [comment]
I should have clarified on my part of the same issue.  I am running this on windows 7 and having the issue.  Any suggestions?

**Comment by tidusjar** [comment]
@gold007eye Please open a different issue
