### ISSUE TITLE
v3 slack notification

### ISSUE THREAD

**Issue by goofballtech** [tidusjar/Ombi#1594]
#### Ombi build Version:

3.0.2144
--

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Windows Server 2016

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
2017-10-18 15:46:25.862 -05:00 [Error] Failed to send Slack Notification
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: o. Path '', line 1, position 1.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.<Request>d__8`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 81
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Slack.SlackApi.<PushAsync>d__5.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Slack\SlackApi.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.Agents.SlackNotification.<Send>d__16.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Agents\SlackNotification.cs:line 152
2017-10-18 16:16:22.934 -05:00 [Error] Failed to send Slack Notification
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: o. Path '', line 1, position 1.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.<Request>d__8`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 81
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Slack.SlackApi.<PushAsync>d__5.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Slack\SlackApi.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.Agents.SlackNotification.<Send>d__16.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Agents\SlackNotification.cs:line 152
2017-10-18 18:14:55.835 -05:00 [Error] StatusCode: 429, Reason: 
2017-10-18 18:14:55.892 -05:00 [Error] StatusCode: 429, Reason: 

```

#### Problem Description:

attempted an add a show to sonarr just to test, wanted to see a slack notification and sonarr to start pulling episodes. Got the above fore the notification portion. I saw the other issue posted earlier about Slack but that seemed be a slightly different issue so i wanted to post this as well to have it covered. 

#### Reproduction Steps:

Added a show with Slack notifications active. 

Thanks for a great product.

**Comment by tidusjar** [comment]
Hey!

Are your slack settings all filled in and correct?

**Comment by goofballtech** [comment]
Yes. The test post worked successfully.
 Used the same data for plexpy and it posts successfully. Actually set them up at the same time.
