### ISSUE TITLE
Cacher running continuously

### ISSUE THREAD

**Issue by Jakesparrow** [tidusjar/Ombi#1598]
#### Ombi build Version:

V 3.0.2147

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Server 2012 r2

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2017-10-19 02:09:19.985 -04:00 [Warning] Failed to process the job '115': an exception occurred. Retry attempt 1 of 1 will be performed in 00:00:40.
System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__16.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 196
2017-10-19 02:10:04.147 -04:00 [Information] 1 scheduled job(s) enqueued.
2017-10-19 02:14:04.045 -04:00 [Error] Failed to process the job '115': an exception occurred.
System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__16.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 196
2017-10-19 08:37:31.155 -04:00 [Warning] Failed to process the job '158': an exception occurred. Retry attempt 1 of 1 will be performed in 00:00:27.
System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__16.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 196
2017-10-19 08:38:11.162 -04:00 [Information] 1 scheduled job(s) enqueued.
2017-10-19 08:42:10.343 -04:00 [Error] Failed to process the job '158': an exception occurred.
System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__16.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 196
2017-10-19 08:57:22.408 -04:00 [Warning] Exception when testing Email Notifications
System.InvalidOperationException: The SMTP server does not support authentication.
   at Ombi.Notifications.GenericEmailProvider.<SendAdHoc>d__4.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 90
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<Email>d__48.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 180
2017-10-19 08:58:10.157 -04:00 [Warning] Exception when testing Email Notifications
System.InvalidOperationException: 5.7.0 Must issue a STARTTLS command first. v65sm7887124ywc.56 - gsmtp
   at Ombi.Notifications.GenericEmailProvider.<SendAdHoc>d__4.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 90
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<Email>d__48.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 180
2017-10-19 08:58:12.698 -04:00 [Warning] Exception when testing Email Notifications
System.InvalidOperationException: 5.7.0 Must issue a STARTTLS command first. a144sm7910828ywh.35 - gsmtp
   at Ombi.Notifications.GenericEmailProvider.<SendAdHoc>d__4.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 90
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<Email>d__48.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 180
2017-10-19 09:13:16.055 -04:00 [Information] Start installing Hangfire SQL objects...
2017-10-19 09:13:16.238 -04:00 [Information] Hangfire SQL objects installed.
2017-10-19 09:13:16.347 -04:00 [Information] Starting Hangfire Server
2017-10-19 09:13:16.360 -04:00 [Information] Using job storage: 'SQLite Server: Ombi.db'
2017-10-19 09:13:16.361 -04:00 [Information] Using the following options for Hangfire Server:
2017-10-19 09:13:16.361 -04:00 [Information]     Worker count: 1
2017-10-19 09:13:16.361 -04:00 [Information]     Listening queues: 'default'
2017-10-19 09:13:16.361 -04:00 [Information]     Shutdown timeout: 00:00:15
2017-10-19 09:13:16.361 -04:00 [Information]     Schedule polling interval: 00:00:15
2017-10-19 09:13:16.620 -04:00 [Information] 1 servers were removed due to timeout


```

#### Problem Description:

Plex Episode Cacher runs continuously. It takes a very long time to complete, and every now and then when I try logging in to Ombi, if it's running sluggish, I'll go check, and it'll be running the cacher again. 
![scheduler](https://user-images.githubusercontent.com/17485169/31772812-c4e022aa-b4ae-11e7-914b-8e0575afe2fb.JPG)

#### Reproduction Steps:

It definitely starts when I restart the application. I'm not sure if it would start up at a certain time interval though.

**Comment by tidusjar** [comment]
That's a lot of episodes!

Regarding the Auto updater, it's trying to launch the process to actually do the update, but I see you are running Ombi thought NSSM, that's not supported yet, so I suggest you turn off auto update from the settings.

Regarding the episode cacher, I am planning to make the schedules customizable at some point.

Currently it's set to run 20 minutes past the hour. 

Can you go to localhost:5000/hangfire and look at the jobs tab, completed jobs and tell me how long it took your PlexEpisodeCacher to run? 

As you can see I am processing the episodes in batches of 50, I could potentially increase the batch sizes, that would also speed up the process.

**Comment by Jakesparrow** [comment]
Thanks for the reply! I will turn off auto updater. No worries. It's not hard to copy/paste with new files anyway. I just need to backup my .db file right?

Here is the completed jobs from Hangfire:

Thanks for all you do man!

![image](https://user-images.githubusercontent.com/17485169/31774142-e0c6f986-b4b2-11e7-8bb4-a2a1e7a1b501.png)

**Comment by tidusjar** [comment]
Wow! You must have a large lib!

I'll look into optimizing the jobs.

To manually upgrade, just unzip into the current directory and overwrite everything. It will not overwrite your database.

**Comment by Jakesparrow** [comment]
It is quite extensive, yes! Thanks for everything!

**Comment by tidusjar** [comment]
Ok, so in the plex settings there is an "advanced" switch, if you enable that then scroll down there is a "Episode Batch Size" field, by default we query plex in batches of 50, but I suggest you make it a bit higher e.g. 150-200 and it should speed things up. 

Keep going higher until it seems to work nicely :)
