### ISSUE TITLE
Unable to create an admin account

### ISSUE THREAD

**Issue by Tamburra** [tidusjar/Ombi#1604]
#### Ombi build Version:

Ombi 3.0.2151-DotNetCore

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Ubuntu 16.04.3 LTS

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2017-10-21 08:26:10.014 -04:00 [Information] Start installing Hangfire SQL objects...
2017-10-21 08:26:10.105 -04:00 [Information] Hangfire SQL objects installed.
2017-10-21 08:26:10.140 -04:00 [Information] Starting Hangfire Server
2017-10-21 08:26:10.143 -04:00 [Information] Using job storage: 'SQLite Server: Ombi.db'
2017-10-21 08:26:10.143 -04:00 [Information] Using the following options for Hangfire Server:
2017-10-21 08:26:10.143 -04:00 [Information]     Worker count: 1
2017-10-21 08:26:10.144 -04:00 [Information]     Listening queues: 'default'
2017-10-21 08:26:10.144 -04:00 [Information]     Shutdown timeout: 00:00:15
2017-10-21 08:26:10.144 -04:00 [Information]     Schedule polling interval: 00:00:15

```

#### Problem Description:

I just downloaded and installed the Ombi software and loaded it up in my browser.  I got the token for Plex successfully and was then brought to the create admin account page.  I am unable to create an admin account.  Any time i enter in details on the screen and click the Finish button I get a popup notification at the top right saying "Error in creating user
There was an error... You might want to put this on Github..."  I do not know how to proceed.  I do not see any errors in my logs. Permissions are set to correct user recursively on the Ombi directory.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
I cannot seem to reproduce this, what browser are you using?

Can you try a different browser?

**Comment by Tamburra** [comment]
Safari and Chrome.  I am trying to configure with https.  Am I suppose to run this via http? or start ombi with a certain command?  

(Default: http://*:5000) Set to a semicolon-separated (;) list of URL prefixes to which the server should respond. For example, http://localhost:123. Use "*" to indicate that the server should listen for requests on 
                   any IP address or hostname using the specified port and protocol (for example, http://*:5000). The protocol (http:// or https://) must be included with each URL. Supported formats vary between servers.

**Comment by tidusjar** [comment]
Ok, 

I just pushed a new build with some logging around when we create the initial user.

It's currently building but can you please install version 3.0.2156 and try again, you should see reasons why it failed in your logs now.

**Comment by Tamburra** [comment]
2017-10-21 17:15:58.215 -04:00 [Information] Start installing Hangfire SQL objects...
2017-10-21 17:15:58.387 -04:00 [Information] Hangfire SQL objects installed.
2017-10-21 17:15:58.412 -04:00 [Information] Starting Hangfire Server
2017-10-21 17:15:58.415 -04:00 [Information] Using job storage: 'SQLite Server: Ombi.db'
2017-10-21 17:15:58.415 -04:00 [Information] Using the following options for Hangfire Server:
2017-10-21 17:15:58.415 -04:00 [Information]     Worker count: 1
2017-10-21 17:15:58.415 -04:00 [Information]     Listening queues: 'default'
2017-10-21 17:15:58.415 -04:00 [Information]     Shutdown timeout: 00:00:15
2017-10-21 17:15:58.415 -04:00 [Information]     Schedule polling interval: 00:00:15


No updated logs with newest build.

I attached 2 screenshots.  Not sure if that leads to anything.
![screen shot 2017-10-21 at 5 22 43 pm](https://user-images.githubusercontent.com/16267805/31856021-5c59cb54-b685-11e7-817d-1751003f8a48.png)
![screen shot 2017-10-21 at 5 21 22 pm](https://user-images.githubusercontent.com/16267805/31856023-60387fea-b685-11e7-8f45-9c4d964adede.png)

**Comment by Tamburra** [comment]
After going back to the main url I am brought to the admin page with no fields to enter data in.

Logging out brings me back to the initial setup up page.

![screen shot 2017-10-21 at 5 34 02 pm](https://user-images.githubusercontent.com/16267805/31856065-672cc2d8-b686-11e7-975a-02399c9943a1.png)

**Comment by tidusjar** [comment]
Interesting, it seems that the user is getting created but it's unauthorised, so maybe the roles are not being assigned. Pushing a new build with more logging to see if the role is being assigned to the user.

**Comment by Tamburra** [comment]
Getting this error when I try to run the new build.

`kyle@home-server:/opt/Ombi$ ./Ombi
Hello, welcome to Ombi
Valid options are:
Ombi 3.0.2160-DotNetCore
Copyright (C) 2017 Ombi

  -h, --host       (Default: http://*:5000) Set to a semicolon-separated (;) 
                   list of URL prefixes to which the server should respond. For
                   example, http://localhost:123. Use "*" to indicate that the 
                   server should listen for requests on any IP address or 
                   hostname using the specified port and protocol (for example,
                   http://*:5000). The protocol (http:// or https://) must be 
                   included with each URL. Supported formats vary between 
                   servers.

  -s, --storage    Storage path, where we save the logs and database

  --help           Display this help screen.

  --version        Display version information.




Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options)
   at Ombi.Store.Context.OmbiContext..ctor() in C:\projects\requestplex\src\Ombi.Store\Context\OmbiContext.cs:line 17
   at Ombi.Program.Main(String[] args) in C:\projects\requestplex\src\Ombi\Program.cs:line 40
Aborted (core dumped)`

**Comment by PotatoQuality** [comment]
@Tamburra pleas try again with the new build :)

**Comment by Tamburra** [comment]
```

2017-10-23 07:01:52.757 -04:00 [Information] Start installing Hangfire SQL objects...
2017-10-23 07:01:52.806 -04:00 [Information] Hangfire SQL objects installed.
2017-10-23 07:01:52.830 -04:00 [Information] Starting Hangfire Server
2017-10-23 07:01:52.832 -04:00 [Information] Using job storage: 'SQLite Server: Ombi.db'
2017-10-23 07:01:52.833 -04:00 [Information] Using the following options for Hangfire Server:
2017-10-23 07:01:52.833 -04:00 [Information]     Worker count: 1
2017-10-23 07:01:52.833 -04:00 [Information]     Listening queues: 'default'
2017-10-23 07:01:52.833 -04:00 [Information]     Shutdown timeout: 1.00:00:00
2017-10-23 07:01:52.833 -04:00 [Information]     Schedule polling interval: 00:00:15
2017-10-23 07:04:44.863 -04:00 [Information] Created User "kyle"
2017-10-23 07:04:44.979 -04:00 [Information] Created the roles
2017-10-23 07:04:45.097 -04:00 [Information] Added the Admin role
```

This is what I am getting in my logs now.  When I get the create admin screen and enter in credentials and click the Finish button I do not get the error notification pop up, but nothing seems to happen on the screen.  I click the button a 2nd time and then i get the popup.  No new log information is reported after clicking the Finish button a 2nd time.  Still happening within both browsers Safari and Chrome.  When back to the main domain url I am brought to the admin homepage where it says welcome "kyle" at the to right as if I am logged in. It seems I can click around just like before but with limited or no text fields as my screenshot above shows.

**Comment by Tamburra** [comment]
Would attaching or sending my database file over help in seeing what the issue would be?

**Comment by tidusjar** [comment]
Yes please to tidusjar@gmail.com

**Comment by Tamburra** [comment]
Ok.  I have some further information.  The issues I was having above was when i was installing Ombi to my server remotely.  I was just onsite with the server and installed Ombi through my local IP in the browser instead of Reverse Proxy and it installed fine.  Through my local IP in the browser everything loads fine.  When i view the site through my domain name using reverse proxy with base url set as /ombi, it seems some urls are not being fed the base url and I am getting errors on the page.  You can see that JS files and language files are not showing the /ombi in the urls even though it is set within the config of Ombi and also in my Apache config.  I have attached some screenshots of what I am seeing now through reverse proxy setup with Apache.  I think what ever I am experiencing now was root cause for the installation failure before but not sure what I can do to alleviate this.  Any ideas?

`    <Location /ombi>
        ProxyPreserveHost On
        ProxyPass http://127.0.0.1:5000/ombi
        ProxyPassReverse http://127.0.0.1:5000/ombi
    </Location>`

![screen shot 2017-10-28 at 8 17 44 am](https://user-images.githubusercontent.com/16267805/32134354-d9e95eca-bbb9-11e7-9917-76d84e7bff62.png)
![screen shot 2017-10-28 at 8 18 48 am](https://user-images.githubusercontent.com/16267805/32134356-ddb4c5b2-bbb9-11e7-90b7-de4d12fc4666.png)

**Comment by tidusjar** [comment]
The above should be fixed. Is this now resolved?
