### ISSUE TITLE
Last update broke ombi to start up

### ISSUE THREAD

**Issue by PotatoQuality** [tidusjar/Ombi#1607]
#### Ombi build Version:

V  3.0.2160

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Windows 10

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

Hello, welcome to Ombi
Valid options are:
Ombi 3.0.2160-DotNetCore
Copyright (C) 2017 Ombi

  -h, --host       (Default: http://*:5000) Set to a semicolon-separated (;)
                   list of URL prefixes to which the server should respond. For
                   example, http://localhost:123. Use "*" to indicate that the
                   server should listen for requests on any IP address or
                   hostname using the specified port and protocol (for example,
                   http://*:5000). The protocol (http:// or https://) must be
                   included with each URL. Supported formats vary between
                   servers.

  -s, --storage    Storage path, where we save the logs and database

  --help           Display this help screen.

  --version        Display version information.




Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options)
   at Ombi.Store.Context.OmbiContext..ctor() in C:\projects\requestplex\src\Ombi.Store\Context\OmbiContext.cs:line 17
   at Ombi.Program.Main(String[] args) in C:\projects\requestplex\src\Ombi\Program.cs:line 40


```

#### Problem Description:

Ombi doesn't startup anymore.

#### Reproduction Steps:

Last update broke starting up ombi.

**Comment by tidusjar** [comment]
#a567dea
