### ISSUE TITLE
Movies on Plex server shows up as requested

### ISSUE THREAD

**Issue by sliddjur** [tidusjar/Ombi#1613]
#### Ombi build Version:

3.0.2165

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Ubuntu 17.10

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
Oct 23 21:35:56 ubuntu-www Ombi[5176]: info: Ombi.Schedule.Jobs.Plex.PlexContentCacher[0]
Oct 23 21:35:56 ubuntu-www Ombi[5176]:       Processing TV Shows
Oct 23 21:35:56 ubuntu-www Ombi[5176]: warn: Ombi.Schedule.Jobs.Plex.PlexContentCacher[2000]
Oct 23 21:35:56 ubuntu-www Ombi[5176]:       Exception thrown when attempting to cache the Plex Content
Oct 23 21:35:56 ubuntu-www Ombi[5176]: System.NullReferenceException: Object reference not set to an instance of an object.
Oct 23 21:35:56 ubuntu-www Ombi[5176]:    at Ombi.Schedule.Jobs.Plex.PlexContentCacher.<StartTheCache>d__17.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentCacher.cs:line 106
Oct 23 21:35:56 ubuntu-www Ombi[5176]: --- End of stack trace from previous location where exception was thrown ---
Oct 23 21:35:56 ubuntu-www Ombi[5176]:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Oct 23 21:35:56 ubuntu-www Ombi[5176]:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Oct 23 21:35:56 ubuntu-www Ombi[5176]:    at Ombi.Schedule.Jobs.Plex.PlexContentCacher.<CacheContent>d__16.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentCacher.cs:line 78

```

#### Problem Description:

Movies on Plex server shows up as requested
Recently requested shows up as requested
In my particular case the request is sent to radarr successfully.

#### Reproduction Steps:

Request a movie

**Comment by PotatoQuality** [comment]
@tidusjar can you look at this one?

**Comment by tidusjar** [comment]
I think I fixed it this morning  Can you please try latest

**Comment by lundgrenolof** [comment]
It is still the same for me. I updated just 5 mins ago.

**Comment by tidusjar** [comment]
Can you try the latest build?
