### ISSUE TITLE
Bug - Wizard / Cannot go past plex login for token / Wizard Page

### ISSUE THREAD

**Issue by Admin9705** [tidusjar/Ombi#1643]
#### Ombi build Version:

3.0.2237

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

1.96

#### Operating System:

Ubuntu 16.04

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Unable to go past login page for plex token verification.  I type my username and password and hit the submit button and nothing happens.  I tried three different machines, using chrome, safari, and firefox; windows and macs and no luck.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Anything in the browsers console?

**Comment by Rydako** [comment]
I've run into the same issue - 

Browser console says

ERROR Object { _body: error, status: 0, ok: false, statusText: "", headers: Object, type: 3, url: null }  vendor.js:8:349
	_ http://192.168.2.61:5000/dist/vendor.js:8:349
	vendor_4ad81305a02f342ba66e</</_o</t.prototype.handleError http://192.168.2.61:5000/dist/vendor.js:155:242
	next http://192.168.2.61:5000/dist/vendor.js:169:9077
	vendor_4ad81305a02f342ba66e</</ps</e.prototype.subscribe/r< http://192.168.2.61:5000/dist/vendor.js:169:3599
	vendor_4ad81305a02f342ba66e</l</e.prototype.__tryOrUnsub http://192.168.2.61:5000/dist/vendor.js:375:3238
	vendor_4ad81305a02f342ba66e</l</e.prototype.next http://192.168.2.61:5000/dist/vendor.js:375:2513
	vendor_4ad81305a02f342ba66e</u</e.prototype._next http://192.168.2.61:5000/dist/vendor.js:375:1555
	vendor_4ad81305a02f342ba66e</u</e.prototype.next http://192.168.2.61:5000/dist/vendor.js:375:1238
	vendor_4ad81305a02f342ba66e</p</e.prototype.next http://192.168.2.61:5000/dist/vendor.js:375:4404
	vendor_4ad81305a02f342ba66e</</ps</e.prototype.emit http://192.168.2.61:5000/dist/vendor.js:169:3358
	onHandleError/< http://192.168.2.61:5000/dist/vendor.js:36:1213
	vendor_4ad81305a02f342ba66e</</</</p</t.prototype.invoke http://192.168.2.61:5000/dist/vendor.js:1083:7379
	vendor_4ad81305a02f342ba66e</</</</u</i.prototype.run http://192.168.2.61:5000/dist/vendor.js:1083:2526
	vendor_4ad81305a02f342ba66e</</ds</t.prototype.runOutsideAngular http://192.168.2.61:5000/dist/vendor.js:169:5223
	onHandleError http://192.168.2.61:5000/dist/vendor.js:36:1175
	vendor_4ad81305a02f342ba66e</</</</p</t.prototype.handleError http://192.168.2.61:5000/dist/vendor.js:1083:7459
	vendor_4ad81305a02f342ba66e</</</</u</i.prototype.runTask http://192.168.2.61:5000/dist/vendor.js:1083:3274
	vendor_4ad81305a02f342ba66e</</</</d</e.invokeTask http://192.168.2.61:5000/dist/vendor.js:1083:9192
	h http://192.168.2.61:5000/dist/vendor.js:1055:3376
	f

**Comment by tidusjar** [comment]
What about your log files? In /logs/ directory

**Comment by Rydako** [comment]
Not reporting anything other than it's startup information. I'm new to Ombi, first install. Anyway to turn on verbose or a higher level of logging?

`root@sv-ombi:/opt/ombi/Logs# cat *
2017-10-29 19:32:41.522 +13:00 [Information] Start installing Hangfire SQL objects...
2017-10-29 19:32:41.677 +13:00 [Information] Hangfire SQL objects installed.
2017-10-29 19:32:41.720 +13:00 [Information] Starting Hangfire Server
2017-10-29 19:32:41.724 +13:00 [Information] Using job storage: 'SQLite Server: Ombi.db'
2017-10-29 19:32:41.724 +13:00 [Information] Using the following options for Hangfire Server:
2017-10-29 19:32:41.724 +13:00 [Information]     Worker count: 1
2017-10-29 19:32:41.724 +13:00 [Information]     Listening queues: 'default'
2017-10-29 19:32:41.725 +13:00 [Information]     Shutdown timeout: 1.00:00:00
2017-10-29 19:32:41.725 +13:00 [Information]     Schedule polling interval: 00:00:15
2017-10-29 19:32:53.368 +13:00 [Information] Hangfire Server stopped.
2017-10-29 19:33:37.791 +13:00 [Information] Start installing Hangfire SQL objects...
2017-10-29 19:33:37.857 +13:00 [Information] Hangfire SQL objects installed.
2017-10-29 19:33:37.888 +13:00 [Information] Starting Hangfire Server
2017-10-29 19:33:37.893 +13:00 [Information] Using job storage: 'SQLite Server: Ombi.db'
2017-10-29 19:33:37.893 +13:00 [Information] Using the following options for Hangfire Server:
2017-10-29 19:33:37.893 +13:00 [Information]     Worker count: 1
2017-10-29 19:33:37.893 +13:00 [Information]     Listening queues: 'default'
2017-10-29 19:33:37.893 +13:00 [Information]     Shutdown timeout: 1.00:00:00
2017-10-29 19:33:37.893 +13:00 [Information]     Schedule polling interval: 00:00:15
2017-10-29 19:46:04.486 +13:00 [Information] Hangfire Server stopped.
2017-10-29 19:48:17.356 +13:00 [Information] Start installing Hangfire SQL objects...
2017-10-29 19:48:17.423 +13:00 [Information] Hangfire SQL objects installed.
2017-10-29 19:48:17.453 +13:00 [Information] Starting Hangfire Server
2017-10-29 19:48:17.457 +13:00 [Information] Using job storage: 'SQLite Server: Ombi.db'
2017-10-29 19:48:17.457 +13:00 [Information] Using the following options for Hangfire Server:
2017-10-29 19:48:17.457 +13:00 [Information]     Worker count: 1
2017-10-29 19:48:17.458 +13:00 [Information]     Listening queues: 'default'
2017-10-29 19:48:17.458 +13:00 [Information]     Shutdown timeout: 1.00:00:00
2017-10-29 19:48:17.458 +13:00 [Information]     Schedule polling interval: 00:00:15
2017-10-29 19:56:40.312 +13:00 [Information] Hangfire Server stopped.
2017-10-29 19:56:50.008 +13:00 [Information] Start installing Hangfire SQL objects...
2017-10-29 19:56:50.075 +13:00 [Information] Hangfire SQL objects installed.
2017-10-29 19:56:50.104 +13:00 [Information] Starting Hangfire Server
2017-10-29 19:56:50.109 +13:00 [Information] Using job storage: 'SQLite Server: Ombi.db'
2017-10-29 19:56:50.109 +13:00 [Information] Using the following options for Hangfire Server:
2017-10-29 19:56:50.109 +13:00 [Information]     Worker count: 1
2017-10-29 19:56:50.109 +13:00 [Information]     Listening queues: 'default'
2017-10-29 19:56:50.109 +13:00 [Information]     Shutdown timeout: 1.00:00:00
2017-10-29 19:56:50.109 +13:00 [Information]     Schedule polling interval: 00:00:15
2017-10-29 19:57:17.209 +13:00 [Information] Start installing Hangfire SQL objects...
2017-10-29 19:57:17.274 +13:00 [Information] Hangfire SQL objects installed.
2017-10-29 19:57:17.304 +13:00 [Information] Starting Hangfire Server
2017-10-29 19:57:17.308 +13:00 [Information] Using job storage: 'SQLite Server: Ombi.db'
2017-10-29 19:57:17.308 +13:00 [Information] Using the following options for Hangfire Server:
2017-10-29 19:57:17.308 +13:00 [Information]     Worker count: 1
2017-10-29 19:57:17.308 +13:00 [Information]     Listening queues: 'default'
2017-10-29 19:57:17.308 +13:00 [Information]     Shutdown timeout: 1.00:00:00
2017-10-29 19:57:17.309 +13:00 [Information]     Schedule polling interval: 00:00:15
2017-10-29 19:57:31.472 +13:00 [Information] Start installing Hangfire SQL objects...
2017-10-29 19:57:31.538 +13:00 [Information] Hangfire SQL objects installed.
2017-10-29 19:57:31.569 +13:00 [Information] Starting Hangfire Server
2017-10-29 19:57:31.573 +13:00 [Information] Using job storage: 'SQLite Server: Ombi.db'
2017-10-29 19:57:31.573 +13:00 [Information] Using the following options for Hangfire Server:
2017-10-29 19:57:31.573 +13:00 [Information]     Worker count: 1
2017-10-29 19:57:31.573 +13:00 [Information]     Listening queues: 'default'
2017-10-29 19:57:31.573 +13:00 [Information]     Shutdown timeout: 1.00:00:00
2017-10-29 19:57:31.573 +13:00 [Information]     Schedule polling interval: 00:00:15
2017-10-29 19:58:48.709 +13:00 [Information] Start installing Hangfire SQL objects...
2017-10-29 19:58:48.780 +13:00 [Information] Hangfire SQL objects installed.
2017-10-29 19:58:48.812 +13:00 [Information] Starting Hangfire Server
2017-10-29 19:58:48.816 +13:00 [Information] Using job storage: 'SQLite Server: Ombi.db'
2017-10-29 19:58:48.816 +13:00 [Information] Using the following options for Hangfire Server:
2017-10-29 19:58:48.816 +13:00 [Information]     Worker count: 1
2017-10-29 19:58:48.816 +13:00 [Information]     Listening queues: 'default'
2017-10-29 19:58:48.816 +13:00 [Information]     Shutdown timeout: 1.00:00:00
2017-10-29 19:58:48.817 +13:00 [Information]     Schedule polling interval: 00:00:15
`

**Comment by tidusjar** [comment]
You cannot configure the logging yet. Can someone open their console and then go through the wizard and capture all the errors to post here?

I cannot recreate this issue

**Comment by Niksal12** [comment]
I am having the same issue on Ubuntu 16.04 LTS
I just pulled it again (3.0.2244) and I tried to go through the wizard. Below is all that I get from the console. Nothing additional gets logged to the console when I attempt to log in, just what is from startup.


```
Ombi:/opt/Ombi$ sudo ./Ombi
Hello, welcome to Ombi
Valid options are:
Ombi 3.0.2244-DotNetCore
Copyright (C) 2017 Ombi

  -h, --host       (Default: http://*:5000) Set to a semicolon-separated (;)
                   list of URL prefixes to which the server should respond. For
                   example, http://localhost:123. Use "*" to indicate that the
                   server should listen for requests on any IP address or
                   hostname using the specified port and protocol (for example,
                   http://*:5000). The protocol (http:// or https://) must be
                   included with each URL. Supported formats vary between
                   servers.

  -s, --storage    Storage path, where we save the logs and database

  --help           Display this help screen.

  --version        Display version information.



We are running on http://*:5000
/opt/Ombi
info: Hangfire.SQLite.SQLiteStorage[0]
      Start installing Hangfire SQL objects...
info: Hangfire.SQLite.SQLiteStorage[0]
      Hangfire SQL objects installed.
info: Hangfire.BackgroundJobServer[0]
      Starting Hangfire Server
info: Hangfire.BackgroundJobServer[0]
      Using job storage: 'SQLite Server: Ombi.db'
info: Hangfire.BackgroundJobServer[0]
      Using the following options for Hangfire Server:
info: Hangfire.BackgroundJobServer[0]
          Worker count: 1
info: Hangfire.BackgroundJobServer[0]
          Listening queues: 'default'
info: Hangfire.BackgroundJobServer[0]
          Shutdown timeout: 1.00:00:00
info: Hangfire.BackgroundJobServer[0]
          Schedule polling interval: 00:00:15
Hosting environment: Production
Content root path: /opt/Ombi
Now listening on: http://[::]:5000
Application started. Press Ctrl+C to shut down.

```

**Comment by PotatoQuality** [comment]
he mean web console

**Comment by Niksal12** [comment]
@PotatoQuality That look better?

**Comment by PotatoQuality** [comment]
yeah :D

**Comment by PotatoQuality** [comment]
Thanks ;-)

**Comment by tidusjar** [comment]
OK! You see this error in the console:
```
{_body: "", status: 500, ok: false, statusText: "Internal Server Error"
```

Can you go on the network tab for that request (should be in red) and click on it then press the preview/response tab and post that?

**Comment by Niksal12** [comment]
Those tabs are blank, unless I am doing something wrong.
![1](https://user-images.githubusercontent.com/31196044/32149004-cd131652-bcd4-11e7-9329-ef21b2f67c2e.PNG)
![2](https://user-images.githubusercontent.com/31196044/32149005-cd2e1894-bcd4-11e7-8e4c-14d043206fd6.PNG)
![3](https://user-images.githubusercontent.com/31196044/32149006-cd404834-bcd4-11e7-9c3d-718b99bee292.PNG)

**Comment by tidusjar** [comment]
Nope you are doing it all correct, just pushed out a new build with some additional logging. can you please give it a go?

**Comment by Niksal12** [comment]
`crit: Ombi.Controllers.External.PlexController[0]
      Error when trying to sign into Plex.tv
System.TypeInitializationException: The type initializer for 'System.Net.Http.CurlHandler' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Http' threw an exception. ---> System.TypeInitializationException: The type initializer for 'HttpInitializer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Net.Http.Native': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.Http.GetSslVersionDescription()
   at Interop.HttpInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.Http..cctor()
   --- End of inner exception stack trace ---
   at Interop.Http.GetSupportedFeatures()
   at System.Net.Http.CurlHandler..cctor()
   --- End of inner exception stack trace ---
   at System.Net.Http.CurlHandler..ctor()
   at System.Net.Http.HttpClientHandler..ctor()
   at Ombi.Api.Api.<GetHandler>d__6.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Api.<Request>d__8`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Plex.PlexApi.<SignIn>d__8.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.PlexController.<SignIn>d__8.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\PlexController.cs:line 55
`

**Comment by tidusjar** [comment]
Install this: https://github.com/tidusjar/Ombi/wiki/Common-Errors#systemnethttpcurlhandler

**Comment by Niksal12** [comment]
Installing System.Net.Http.CurlHandler fixed it, I already had the other installed.

**Comment by tidusjar** [comment]
@Admin9705 can you also try?

**Comment by Admin9705** [comment]
Will do!

**Comment by Rydako** [comment]
I had didn't have libunwind8 installed, (Have now installed it) but libcurl4-openssl-dev was installed.
Still not working for me though. Have installed your new build, but doesn't seem to be logging anything extra.

Spotted this in syslog - seems to occur directly after I press the Request token button

[448348.100070] traps: Ombi[30645] general protection ip:7f0afe588d6d sp:7f0ab7102c60 error:0 in libcrypto.so.1.0.0[7f0afe44d000+1cd000]

**Comment by Admin9705** [comment]
May sound odd, but I ran the wizard on my iphone in safari and it worked... though for nothing else.  I got it to work and upgraded to the latest version using this:

sudo cp /opt/Ombi/Ombi.db /tmp/
sudo systemctl stop ombi.service
sudo rm -r /opt/Ombi/
sudo mkdir /opt/Ombi && cd /opt/Ombi
sudo wget https://ci.appveyor.com/api/buildjobs/4q3xv7l475np7ovj/artifacts/linux.tar.gz
sudo tar -xzf linux.tar.gz
sudo rm - r /opt/Ombi/Ombi.db
cd /tmp
sudo cp Ombi.db /opt/Ombi/Ombi.db
sudo rm -r /tmp/Ombi.db
sudo chmod 755 /opt/Ombi
sudo systemctl start ombi.service
sudo systemctl status ombi.service

**Comment by tidusjar** [comment]
Is this still an issue guys?

**Comment by Admin9705** [comment]
Not for me, but I have not tried a default install. I have a vm I can test
on tonight. I’ll report back.

**Comment by Rydako** [comment]
I'm still having issues stated above, but I haven't had the time to properly test and investigate yet.

I'm running inside a Debian LXD container, so possible I'm just missing other libraries that would normally be included in a standard debian install. 

Does Ombi expect a specific libcrypto version?

**Comment by phoenisis** [comment]
I'm having the same issue !
Error 500 on : 

- POST /api/v1/Plex/Libraries
- POST /api/v1/tester/plex 
- POST /api/v1/Settings/Plex/

I don't know if it relative to the issue, but in all the POST failing request, the ip field is set to `ip:""`

**Comment by tidusjar** [comment]
@phoenisis if you have HTTP 500 errors there should be some logs, can you check please.

**Comment by phoenisis** [comment]
It is possible to set Ombi in a verbose mode ? 
The only logs that I can show you are form the network and the console.

![capture d ecran 2017-11-07 a 14 19 12](https://user-images.githubusercontent.com/3032945/32495755-46489080-c3c7-11e7-913f-f07f1277ad59.png)
![capture d ecran 2017-11-07 a 14 19 51](https://user-images.githubusercontent.com/3032945/32495756-467963e0-c3c7-11e7-8952-d3080b9a027f.png)

**Comment by tidusjar** [comment]
I mean in the /logs folder

**Comment by phoenisis** [comment]
It doesn't go more than : 
```2017-11-07 14:51:49.951 +01:00 [Information] Start installing Hangfire SQL objects...
2017-11-07 14:51:50.109 +01:00 [Information] Hangfire SQL objects installed.
2017-11-07 14:51:50.183 +01:00 [Information] Starting Hangfire Server
2017-11-07 14:51:50.192 +01:00 [Information] Using job storage: 'SQLite Server: Ombi.db'
2017-11-07 14:51:50.192 +01:00 [Information] Using the following options for Hangfire Server:
2017-11-07 14:51:50.192 +01:00 [Information]     Worker count: 1
2017-11-07 14:51:50.193 +01:00 [Information]     Listening queues: 'default'
2017-11-07 14:51:50.193 +01:00 [Information]     Shutdown timeout: 1.00:00:00
2017-11-07 14:51:50.193 +01:00 [Information]     Schedule polling interval: 00:00:15

**Comment by tidusjar** [comment]
Wait this is for the settings menu. Please open a new bug about this. This is not related to this issue.

**Comment by phoenisis** [comment]
No, this is totally related. 

And I find out the issue ! When I load server, it load my two servers, I select one and it set every information in the left part, but leave/clear the `Hostname or IP` field.

I need to set if after select the server and there is no more issue for submitting
![2017-11-07_16-20-36](https://user-images.githubusercontent.com/3032945/32501267-defe750a-c3d7-11e7-99bc-60f733f84d37.gif)

**Comment by tidusjar** [comment]
This is not related. this issue is to do with the user creation on the wizard screen.

**Comment by tidusjar** [comment]
Not really regarding the OpenSSL issue, i'm not sure about that.

Has anyone been able to investigate any further?

**Comment by zenety** [comment]
A few days ago I had this exact same problem. Redownloaded the latest artifact and it's working fine for me now.

**Comment by BrandonEckert** [comment]
I am receiving the same error with my new install of the latest 3.x Ombi.

**Comment by PotatoQuality** [comment]
Pleas open an new issue

**Comment by edmoore-mq** [comment]
Fresh install having the same issue.
Ubuntu installed from apt

**Comment by Admin9705** [comment]
Same issue. I stopped using as a result.
