### ISSUE TITLE
Enable Notification for Auto Approve

### ISSUE THREAD

**Issue by masau** [tidusjar/Ombi#1659]
#### Ombi build Version:

V 3.0.2268

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Arch Linux

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

fail: Ombi.Notifications.GenericEmailProvider[0]
      Exception when attempting to send email
System.ArgumentException: The string can't be null or empty.
   at EnsureThat.EnsureArg.IsNotNullOrEmpty(String value, String paramName)
   at Ombi.Notifications.GenericEmailProvider.<Send>d__6.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 104
fail: Ombi.Notifications.NotificationService[4000]
      Failed to notify for notification: Ombi.Notifications.Agents.EmailNotification
System.ArgumentException: The string can't be null or empty.
   at EnsureThat.EnsureArg.IsNotNullOrEmpty(String value, String paramName)
   at Ombi.Notifications.GenericEmailProvider.<Send>d__6.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 154
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.Agents.EmailNotification.<Send>d__14.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Agents\EmailNotification.cs:line 162
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.Agents.EmailNotification.<RequestApproved>d__12.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Agents\EmailNotification.cs:line 144
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.Interfaces.BaseNotification`1.<NotifyAsync>d__31.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.Interfaces.BaseNotification`1.<NotifyAsync>d__30.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.NotificationService.<NotifyAsync>d__9.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\NotificationService.cs:line 83

```

#### Problem Description:

Email notification works with test email, but isn't send when a new request is made (New Request email is enabled and Subject and Message are both default). Instead I get the above error message.

#### Reproduction Steps:

Set up email notifications, make sure New Request is enabled and request a new tv show or movie.

**Comment by tidusjar** [comment]
Make sure your settings are all filled out:

We require the recipient to have an email address, in your settings you need a sender address and a host.

**Comment by masau** [comment]
They are/were, but after more testing it appears that the email causing the error wasn't occurring on New Request, but rather on Request Approved because the user I was testing with didn't have an email address.

It appears that New Request emails aren't sent if autoapprove is on, which is disappointing - I was hoping to get notifications when a request is added so that I can decide if I want to see if manual intervention in Radarr/Sonarr is necessary or not (i.e. for old movies or tv shows).

This might be the issue for #1660 as well.

Can we get the option to either always get New Request emails?

**Comment by tidusjar** [comment]
AH yes,

Administrators and Auto Approve roles do not get notifications. 

This has been a request a few times... I'll think about it.

**Comment by Magic815** [comment]
I would like to note that I believe this also impacts pushbullet notices.

I'm trying to get New Request messages sent to me (the admin) via pushbullet - even if Autoapprove is on for the requester. In my use case, I have autoapprove on for all users, but I have "do not search" set in Sonarr and Radarr. This makes it so that it auto-adds to Sonarr/Radarr, but then allows me to choose the exact release I want to get via manual searching.

Some sort of setting that allows all requests to be sent to the admin (via email, pushbullet, etc.) regardless of autoapprove settings on the user making the request would be great!

**Comment by zin105** [comment]
Another vote for gettting a notification even if auto approve is enabled.

**Comment by L0rdBootysniffer** [comment]
+1 this request

**Comment by andmillionaire** [comment]
+1 this request

I like to get notified of new requests even if auto approve is on.

**Comment by tidusjar** [comment]
Ok, That's enough 1+'s.

I'll get it done

**Comment by tidusjar** [comment]
Done, notifications are sent by default regardless of the user roles. If you do not want notifications for auto approve then there is a new option in the Ombi Settings to ignore these
