### ISSUE TITLE
Latest Update - PLEASE READ

### ISSUE THREAD

**Issue by tidusjar** [tidusjar/Ombi#1669]
Hi All,

Due to a bug that needed fixing it was not possible to migrate the database, with the latest update you need to delete your Ombi.db file and start again.

Really sorry about this.

**Comment by goldenpipes** [comment]
Can the db be separated from the rest of the information?  such as users and notification settings as well as the downloader settings?

**Comment by tidusjar** [comment]
It could be but would be a lot of work for very little benefit

**Comment by christronyxyocum** [comment]
What version exactly? If we were/are on an older version, are we ok?

**Comment by goldenpipes** [comment]
with all of the database needing to be rebuilt when the cacher breaks having to restart everything is a pain.   That seems like a huge benefit, being able to reset the DB without losing all your settings.

**Comment by samwiseg00** [comment]
+1 for settings being separate from the db... Or at least a way to export just the settings and re import them...

**Comment by didyouexpectthat** [comment]
For reference for people who come in the future, this is the error you will see in the Logs.

```
Unhandled Exception: Microsoft.Data.Sqlite.SqliteException: SQLite Error 1: 'table "ApplicationConfiguration" already exists'.
at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
at Ombi.Program.Main(String[] args) in C:\projects\requestplex\src\Ombi\Program.cs:line 40
```

**Comment by drewbitt** [comment]
That's too bad. Hopefully this can be avoided in the future.

**Comment by dhruvb14** [comment]
Been crazy busy at work the last month and half. @tidusjar what exactly was changed that would not allow for a clean EF Migration? I use EF in prod @ customers and have never had a scenario that with a bit of SQL queries I couldn't fix EF migrations. Just curious...

**Comment by tidusjar** [comment]
Sqlite doesn't support the drop of foreign keys and columns via migrations. There is no built in code to migrate manually either. This was a one time thing in a non stable codebase
