### ISSUE TITLE
Can't start Ombi after update.

### ISSUE THREAD

**Issue by MrPryor** [tidusjar/Ombi#1681]
#### Ombi build Version:

V 3.0.2310

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Windows 10 64bit

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

Unhandled Exception: Microsoft.Data.Sqlite.SqliteException: SQLite Error 14: 'unable to open database file'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteDatabaseCreator.Create()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Ombi.Program.Main(String[] args) in C:\projects\requestplex\src\Ombi\Program.cs:line 40

```

#### Problem Description:

(Can't start Ombi after updating. )

#### Reproduction Steps:

Updated to v3.0.2310

**Comment by tidusjar** [comment]
You had some permissions issue confirmed over discord.

**Comment by NeeWii** [comment]
@tidusjar - I've also been running into this issue. Running Ombi v3.0.3173 on MacOS High Sierra.

I can get Ombi to run without any difficulty when I do so through terminal, however I need to have it run at start-up/in the background so I'm trying to get a LaunchAgent .plist to run it. For some reason, when running via a LaunchAgent .plist it fails every time with an identical error to the original poster above.

I've tried running chmod -R 777 on the Ombi folder, but still getting the same error message. Is there anything else you can think of I could try?
