### ISSUE TITLE
table 'ApplicationConfiguration' already exists

### ISSUE THREAD

**Issue by nathanstorms** [tidusjar/Ombi#1696]
#### Ombi build Version:

V 3.0.2330.0

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Windows Server 2016

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

Unhandled Exception: Microsoft.Data.Sqlite.SqliteException: SQLite Error 1: 'table "ApplicationConfiguration" already exists'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Ombi.Program.Main(String[] args) in C:\projects\requestplex\src\Ombi\Program.cs:line 40

#### Problem Description:

Unable to upgrade.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by Codehhh** [comment]
https://github.com/tidusjar/Ombi/issues/1669
