### ISSUE TITLE
DogNZB TV add to watchlist error

### ISSUE THREAD

**Issue by sprintexx** [tidusjar/Ombi#1707]
#### Ombi build Version:

V 3.0.2350
#### Update Branch:

DotNetCore

#### Media Sever:

Plex

#### Media Server Version:

NA
#### Operating System:

Centos 7

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
c\Ombi\Controllers\External\TesterController.cs:line 205
2017-11-12 10:17:26.907 -05:00 [Error] StatusCode: BadRequest, Reason: Bad Request
2017-11-12 10:17:26.955 -05:00 [Error] StatusCode: NotFound, Reason: Not Found
2017-11-12 10:17:26.957 -05:00 [Error] StatusCode: NotFound, Reason: Not Found
2017-11-12 10:17:27.135 -05:00 [Error] StatusCode: NotFound, Reason: Not Found
2017-11-12 10:17:27.306 -05:00 [Error] StatusCode: NotFound, Reason: Not Found
2017-11-12 10:17:27.325 -05:00 [Error] StatusCode: NotFound, Reason: Not Found
2017-11-12 10:28:20.130 -05:00 [Error] StatusCode: NotFound, Reason: Not Found
2017-11-12 10:28:20.143 -05:00 [Error] StatusCode: BadRequest, Reason: Bad Request
2017-11-12 10:28:20.345 -05:00 [Error] StatusCode: NotFound, Reason: Not Found
2017-11-12 10:31:04.875 -05:00 [Error] StatusCode: BadRequest, Reason: Bad Request
2017-11-12 10:31:04.969 -05:00 [Error] StatusCode: NotFound, Reason: Not Found
2017-11-12 10:31:05.076 -05:00 [Error] StatusCode: NotFound, Reason: Not Found
2017-11-12 10:31:11.818 -05:00 [Error] Error when adding TV Shows to DogNzb
System.InvalidOperationException: There is an error in XML document (2, 8). ---> System.InvalidOperat
ionException: <error xmlns=''> was not expected.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderDogNzbAddResult.Read3_uuid(
)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, X
mlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at Ombi.Api.DogNzb.DogNzbApi.<AddTvShow>d__6.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Do
gNzb\DogNzbApi.cs:line 56
2017-11-12 10:31:39.444 -05:00 [Error] StatusCode: BadRequest, Reason: Bad Request
2017-11-12 10:31:39.542 -05:00 [Error] StatusCode: NotFound, Reason: Not Found
2017-11-12 10:31:39.660 -05:00 [Error] StatusCode: NotFound, Reason: Not Found
2017-11-12 10:33:10.521 -05:00 [Error] StatusCode: BadRequest, Reason: Bad Request
2017-11-12 10:33:10.624 -05:00 [Error] StatusCode: NotFound, Reason: Not Found
2017-11-12 10:33:10.731 -05:00 [Error] StatusCode: NotFound, Reason: Not Found
2017-11-12 10:36:43.227 -05:00 [Error] Error when adding TV Shows to DogNzb
System.InvalidOperationException: There is an error in XML document (2, 8). ---> System.InvalidOperat
ionException: <error xmlns=''> was not expected.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderDogNzbAddResult.Read3_uuid(
)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, X
mlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at Ombi.Api.DogNzb.DogNzbApi.<AddTvShow>d__6.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Do
gNzb\DogNzbApi.cs:line 56
2017-11-12 10:44:16.908 -05:00 [Error] StatusCode: NotFound, Reason: Not Found
2017-11-12 10:44:17.009 -05:00 [Error] StatusCode: NotFound, Reason: Not Found
2017-11-12 10:44:17.140 -05:00 [Error] StatusCode: NotFound, Reason: Not Found
2017-11-12 10:44:17.228 -05:00 [Error] StatusCode: NotFound, Reason: Not Found
2017-11-12 10:44:17.343 -05:00 [Error] StatusCode: NotFound, Reason: Not Found
2017-11-12 10:44:17.433 -05:00 [Error] StatusCode: NotFound, Reason: Not Found
2017-11-12 10:44:17.537 -05:00 [Error] StatusCode: NotFound, Reason: Not Found
2017-11-12 10:44:17.549 -05:00 [Error] StatusCode: NotFound, Reason: Not Found
2017-11-12 10:44:17.746 -05:00 [Error] StatusCode: NotFound, Reason: Not Found
2017-11-12 10:45:06.570 -05:00 [Error] Error when adding TV Shows to DogNzb
System.InvalidOperationException: There is an error in XML document (2, 8). ---> System.InvalidOperat
ionException: <error xmlns=''> was not expected.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderDogNzbAddResult.Read3_uuid(
)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, X
mlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at Ombi.Api.DogNzb.DogNzbApi.<AddTvShow>d__6.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Do
gNzb\DogNzbApi.cs:line 56
2017-11-12 10:45:15.556 -05:00 [Error] Error when adding TV Shows to DogNzb
System.InvalidOperationException: There is an error in XML document (2, 8). ---> System.InvalidOperat
ionException: <error xmlns=''> was not expected.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderDogNzbAddResult.Read3_uuid(
)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, X
mlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at Ombi.Api.DogNzb.DogNzbApi.<AddTvShow>d__6.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Do
gNzb\DogNzbApi.cs:line 56
2017-11-12 10:45:56.718 -05:00 [Error] StatusCode: NotFound, Reason: Not Found
2017-11-12 10:47:47.006 -05:00 [Error] StatusCode: NotFound, Reason: Not Found
```

#### Problem Description:

Brand new install.  Added API key for TV and Movies.  Movies work completely fine.  When adding a TVshow via the UI, everything looks as you would expect.  but in the logs  i get the above messages and never see the tv show added to the watch list.

#### Reproduction Steps:

Attempted to add some older shows (Fresh Prince) and a newer one Guy's Big Project.  I understand by reading the docs that specific episodes are not available via DogNZB, but i was expecting the new show to be added to the watch list which maybe i am misunderstanding.  Thank you for your time.

**Comment by tidusjar** [comment]
API must have changed. I'll take a look

**Comment by sprintexx** [comment]
Thanks much!

**Comment by tidusjar** [comment]
Looks like when adding old shows that are no longer airing, you cannot add them via the watchlist. It should show an error in the UI saying that it cannot add it.

Please confirm
