### ISSUE TITLE
Not All Movies Marked As Available Even Though They Are

### ISSUE THREAD

**Issue by dshokouhi** [tidusjar/Ombi#1710]
#### Ombi build Version:

V 3.0.2351

#### Update Branch:

DotNetCore

#### Media Sever:

Plex

#### Media Server Version:

1.9.7.4441

#### Operating System:

Windows 7

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2017-11-13 10:20:41.002 -08:00 [Warning] Failed to process the job '1437': an exception occurred. Retry attempt 1 of 3 will be performed in 00:00:32.
Hangfire.BackgroundJobClientException: Background job creation failed. See inner exception for details. ---> Microsoft.Data.Sqlite.SqliteException: SQLite Error 5: 'database is locked'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteScalar()
   at Dapper.SqlMapper.ExecuteScalarImpl[T](IDbConnection cnn, CommandDefinition& command)
   at Dapper.SqlMapper.ExecuteScalar[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType)
   at Hangfire.SQLite.SQLiteStorageConnection.<>c__DisplayClass5_0.<CreateExpiredJob>b__0(DbConnection connection)
   at Hangfire.SQLite.SQLiteStorage.UseConnection[T](Func`2 func, Boolean isWriteLock)
   at Hangfire.SQLite.SQLiteStorageConnection.CreateExpiredJob(Job job, IDictionary`2 parameters, DateTime createdAt, TimeSpan expireIn)
   at Hangfire.Client.CoreBackgroundJobFactory.Create(CreateContext context)
   at Hangfire.Client.BackgroundJobFactory.<>c__DisplayClass7_0.<CreateWithFilters>b__0()
   at Hangfire.Client.BackgroundJobFactory.InvokeClientFilter(IClientFilter filter, CreatingContext preContext, Func`1 continuation)
   at Hangfire.Client.BackgroundJobFactory.Create(CreateContext context)
   at Hangfire.BackgroundJobClient.Create(Job job, IState state)
   --- End of inner exception stack trace ---
   at Hangfire.BackgroundJobClient.Create(Job job, IState state)
   at Ombi.Schedule.Jobs.Plex.PlexAvailabilityChecker.<ProcessMovies>d__8.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexAvailabilityChecker.cs:line 143
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Schedule.Jobs.Plex.PlexAvailabilityChecker.<Start>d__6.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexAvailabilityChecker.cs:line 35
2017-11-13 10:21:26.062 -08:00 [Information] 1 scheduled job(s) enqueued.
2017-11-13 10:22:11.097 -08:00 [Warning] Failed to process the job '1437': an exception occurred. Retry attempt 2 of 3 will be performed in 00:00:28.
Hangfire.BackgroundJobClientException: Background job creation failed. See inner exception for details. ---> Microsoft.Data.Sqlite.SqliteException: SQLite Error 5: 'database is locked'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteScalar()
   at Dapper.SqlMapper.ExecuteScalarImpl[T](IDbConnection cnn, CommandDefinition& command)
   at Dapper.SqlMapper.ExecuteScalar[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType)
   at Hangfire.SQLite.SQLiteStorageConnection.<>c__DisplayClass5_0.<CreateExpiredJob>b__0(DbConnection connection)
   at Hangfire.SQLite.SQLiteStorage.UseConnection[T](Func`2 func, Boolean isWriteLock)
   at Hangfire.SQLite.SQLiteStorageConnection.CreateExpiredJob(Job job, IDictionary`2 parameters, DateTime createdAt, TimeSpan expireIn)
   at Hangfire.Client.CoreBackgroundJobFactory.Create(CreateContext context)
   at Hangfire.Client.BackgroundJobFactory.<>c__DisplayClass7_0.<CreateWithFilters>b__0()
   at Hangfire.Client.BackgroundJobFactory.InvokeClientFilter(IClientFilter filter, CreatingContext preContext, Func`1 continuation)
   at Hangfire.Client.BackgroundJobFactory.Create(CreateContext context)
   at Hangfire.BackgroundJobClient.Create(Job job, IState state)
   --- End of inner exception stack trace ---
   at Hangfire.BackgroundJobClient.Create(Job job, IState state)
   at Ombi.Schedule.Jobs.Plex.PlexAvailabilityChecker.<ProcessMovies>d__8.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexAvailabilityChecker.cs:line 143
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Schedule.Jobs.Plex.PlexAvailabilityChecker.<Start>d__6.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexAvailabilityChecker.cs:line 35
2017-11-13 10:22:41.282 -08:00 [Information] 1 scheduled job(s) enqueued.
2017-11-13 10:23:26.197 -08:00 [Warning] Failed to process the job '1437': an exception occurred. Retry attempt 3 of 3 will be performed in 00:00:43.
Hangfire.BackgroundJobClientException: Background job creation failed. See inner exception for details. ---> Microsoft.Data.Sqlite.SqliteException: SQLite Error 5: 'database is locked'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteScalar()
   at Dapper.SqlMapper.ExecuteScalarImpl[T](IDbConnection cnn, CommandDefinition& command)
   at Dapper.SqlMapper.ExecuteScalar[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType)
   at Hangfire.SQLite.SQLiteStorageConnection.<>c__DisplayClass5_0.<CreateExpiredJob>b__0(DbConnection connection)
   at Hangfire.SQLite.SQLiteStorage.UseConnection[T](Func`2 func, Boolean isWriteLock)
   at Hangfire.SQLite.SQLiteStorageConnection.CreateExpiredJob(Job job, IDictionary`2 parameters, DateTime createdAt, TimeSpan expireIn)
   at Hangfire.Client.CoreBackgroundJobFactory.Create(CreateContext context)
   at Hangfire.Client.BackgroundJobFactory.<>c__DisplayClass7_0.<CreateWithFilters>b__0()
   at Hangfire.Client.BackgroundJobFactory.InvokeClientFilter(IClientFilter filter, CreatingContext preContext, Func`1 continuation)
   at Hangfire.Client.BackgroundJobFactory.Create(CreateContext context)
   at Hangfire.BackgroundJobClient.Create(Job job, IState state)
   --- End of inner exception stack trace ---
   at Hangfire.BackgroundJobClient.Create(Job job, IState state)
   at Ombi.Schedule.Jobs.Plex.PlexAvailabilityChecker.<ProcessMovies>d__8.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexAvailabilityChecker.cs:line 143
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Schedule.Jobs.Plex.PlexAvailabilityChecker.<Start>d__6.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexAvailabilityChecker.cs:line 35
2017-11-13 10:24:11.232 -08:00 [Information] 1 scheduled job(s) enqueued.
2017-11-13 10:24:56.277 -08:00 [Error] Failed to process the job '1437': an exception occurred.
Hangfire.BackgroundJobClientException: Background job creation failed. See inner exception for details. ---> Microsoft.Data.Sqlite.SqliteException: SQLite Error 5: 'database is locked'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteScalar()
   at Dapper.SqlMapper.ExecuteScalarImpl[T](IDbConnection cnn, CommandDefinition& command)
   at Dapper.SqlMapper.ExecuteScalar[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType)
   at Hangfire.SQLite.SQLiteStorageConnection.<>c__DisplayClass5_0.<CreateExpiredJob>b__0(DbConnection connection)
   at Hangfire.SQLite.SQLiteStorage.UseConnection[T](Func`2 func, Boolean isWriteLock)
   at Hangfire.SQLite.SQLiteStorageConnection.CreateExpiredJob(Job job, IDictionary`2 parameters, DateTime createdAt, TimeSpan expireIn)
   at Hangfire.Client.CoreBackgroundJobFactory.Create(CreateContext context)
   at Hangfire.Client.BackgroundJobFactory.<>c__DisplayClass7_0.<CreateWithFilters>b__0()
   at Hangfire.Client.BackgroundJobFactory.InvokeClientFilter(IClientFilter filter, CreatingContext preContext, Func`1 continuation)
   at Hangfire.Client.BackgroundJobFactory.Create(CreateContext context)
   at Hangfire.BackgroundJobClient.Create(Job job, IState state)
   --- End of inner exception stack trace ---
   at Hangfire.BackgroundJobClient.Create(Job job, IState state)
   at Ombi.Schedule.Jobs.Plex.PlexAvailabilityChecker.<ProcessMovies>d__8.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexAvailabilityChecker.cs:line 143
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Schedule.Jobs.Plex.PlexAvailabilityChecker.<Start>d__6.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexAvailabilityChecker.cs:line 35
2017-11-13 11:20:38.782 -08:00 [Warning] Failed to process the job '1444': an exception occurred. Retry attempt 1 of 3 will be performed in 00:00:21.
Hangfire.BackgroundJobClientException: Background job creation failed. See inner exception for details. ---> Microsoft.Data.Sqlite.SqliteException: SQLite Error 5: 'database is locked'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteScalar()
   at Dapper.SqlMapper.ExecuteScalarImpl[T](IDbConnection cnn, CommandDefinition& command)
   at Dapper.SqlMapper.ExecuteScalar[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType)
   at Hangfire.SQLite.SQLiteStorageConnection.<>c__DisplayClass5_0.<CreateExpiredJob>b__0(DbConnection connection)
   at Hangfire.SQLite.SQLiteStorage.UseConnection[T](Func`2 func, Boolean isWriteLock)
   at Hangfire.SQLite.SQLiteStorageConnection.CreateExpiredJob(Job job, IDictionary`2 parameters, DateTime createdAt, TimeSpan expireIn)
   at Hangfire.Client.CoreBackgroundJobFactory.Create(CreateContext context)
   at Hangfire.Client.BackgroundJobFactory.<>c__DisplayClass7_0.<CreateWithFilters>b__0()
   at Hangfire.Client.BackgroundJobFactory.InvokeClientFilter(IClientFilter filter, CreatingContext preContext, Func`1 continuation)
   at Hangfire.Client.BackgroundJobFactory.Create(CreateContext context)
   at Hangfire.BackgroundJobClient.Create(Job job, IState state)
   --- End of inner exception stack trace ---
   at Hangfire.BackgroundJobClient.Create(Job job, IState state)
   at Ombi.Schedule.Jobs.Plex.PlexAvailabilityChecker.<ProcessMovies>d__8.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexAvailabilityChecker.cs:line 143
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Schedule.Jobs.Plex.PlexAvailabilityChecker.<Start>d__6.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexAvailabilityChecker.cs:line 35
2017-11-13 11:21:08.867 -08:00 [Information] 1 scheduled job(s) enqueued.
2017-11-13 11:21:53.862 -08:00 [Warning] Failed to process the job '1444': an exception occurred. Retry attempt 2 of 3 will be performed in 00:01:14.
Hangfire.BackgroundJobClientException: Background job creation failed. See inner exception for details. ---> Microsoft.Data.Sqlite.SqliteException: SQLite Error 5: 'database is locked'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteScalar()
   at Dapper.SqlMapper.ExecuteScalarImpl[T](IDbConnection cnn, CommandDefinition& command)
   at Dapper.SqlMapper.ExecuteScalar[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType)
   at Hangfire.SQLite.SQLiteStorageConnection.<>c__DisplayClass5_0.<CreateExpiredJob>b__0(DbConnection connection)
   at Hangfire.SQLite.SQLiteStorage.UseConnection[T](Func`2 func, Boolean isWriteLock)
   at Hangfire.SQLite.SQLiteStorageConnection.CreateExpiredJob(Job job, IDictionary`2 parameters, DateTime createdAt, TimeSpan expireIn)
   at Hangfire.Client.CoreBackgroundJobFactory.Create(CreateContext context)
   at Hangfire.Client.BackgroundJobFactory.<>c__DisplayClass7_0.<CreateWithFilters>b__0()
   at Hangfire.Client.BackgroundJobFactory.InvokeClientFilter(IClientFilter filter, CreatingContext preContext, Func`1 continuation)
   at Hangfire.Client.BackgroundJobFactory.Create(CreateContext context)
   at Hangfire.BackgroundJobClient.Create(Job job, IState state)
   --- End of inner exception stack trace ---
   at Hangfire.BackgroundJobClient.Create(Job job, IState state)
   at Ombi.Schedule.Jobs.Plex.PlexAvailabilityChecker.<ProcessMovies>d__8.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexAvailabilityChecker.cs:line 143
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Schedule.Jobs.Plex.PlexAvailabilityChecker.<Start>d__6.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexAvailabilityChecker.cs:line 35
2017-11-13 11:23:08.927 -08:00 [Information] 1 scheduled job(s) enqueued.
2017-11-13 11:23:53.947 -08:00 [Warning] Failed to process the job '1444': an exception occurred. Retry attempt 3 of 3 will be performed in 00:00:49.
Hangfire.BackgroundJobClientException: Background job creation failed. See inner exception for details. ---> Microsoft.Data.Sqlite.SqliteException: SQLite Error 5: 'database is locked'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteScalar()
   at Dapper.SqlMapper.ExecuteScalarImpl[T](IDbConnection cnn, CommandDefinition& command)
   at Dapper.SqlMapper.ExecuteScalar[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType)
   at Hangfire.SQLite.SQLiteStorageConnection.<>c__DisplayClass5_0.<CreateExpiredJob>b__0(DbConnection connection)
   at Hangfire.SQLite.SQLiteStorage.UseConnection[T](Func`2 func, Boolean isWriteLock)
   at Hangfire.SQLite.SQLiteStorageConnection.CreateExpiredJob(Job job, IDictionary`2 parameters, DateTime createdAt, TimeSpan expireIn)
   at Hangfire.Client.CoreBackgroundJobFactory.Create(CreateContext context)
   at Hangfire.Client.BackgroundJobFactory.<>c__DisplayClass7_0.<CreateWithFilters>b__0()
   at Hangfire.Client.BackgroundJobFactory.InvokeClientFilter(IClientFilter filter, CreatingContext preContext, Func`1 continuation)
   at Hangfire.Client.BackgroundJobFactory.Create(CreateContext context)
   at Hangfire.BackgroundJobClient.Create(Job job, IState state)
   --- End of inner exception stack trace ---
   at Hangfire.BackgroundJobClient.Create(Job job, IState state)
   at Ombi.Schedule.Jobs.Plex.PlexAvailabilityChecker.<ProcessMovies>d__8.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexAvailabilityChecker.cs:line 143
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Schedule.Jobs.Plex.PlexAvailabilityChecker.<Start>d__6.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexAvailabilityChecker.cs:line 35
2017-11-13 11:24:53.982 -08:00 [Information] 1 scheduled job(s) enqueued.
2017-11-13 11:25:39.027 -08:00 [Error] Failed to process the job '1444': an exception occurred.
Hangfire.BackgroundJobClientException: Background job creation failed. See inner exception for details. ---> Microsoft.Data.Sqlite.SqliteException: SQLite Error 5: 'database is locked'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteScalar()
   at Dapper.SqlMapper.ExecuteScalarImpl[T](IDbConnection cnn, CommandDefinition& command)
   at Dapper.SqlMapper.ExecuteScalar[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType)
   at Hangfire.SQLite.SQLiteStorageConnection.<>c__DisplayClass5_0.<CreateExpiredJob>b__0(DbConnection connection)
   at Hangfire.SQLite.SQLiteStorage.UseConnection[T](Func`2 func, Boolean isWriteLock)
   at Hangfire.SQLite.SQLiteStorageConnection.CreateExpiredJob(Job job, IDictionary`2 parameters, DateTime createdAt, TimeSpan expireIn)
   at Hangfire.Client.CoreBackgroundJobFactory.Create(CreateContext context)
   at Hangfire.Client.BackgroundJobFactory.<>c__DisplayClass7_0.<CreateWithFilters>b__0()
   at Hangfire.Client.BackgroundJobFactory.InvokeClientFilter(IClientFilter filter, CreatingContext preContext, Func`1 continuation)
   at Hangfire.Client.BackgroundJobFactory.Create(CreateContext context)
   at Hangfire.BackgroundJobClient.Create(Job job, IState state)
   --- End of inner exception stack trace ---
   at Hangfire.BackgroundJobClient.Create(Job job, IState state)
   at Ombi.Schedule.Jobs.Plex.PlexAvailabilityChecker.<ProcessMovies>d__8.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexAvailabilityChecker.cs:line 143
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Schedule.Jobs.Plex.PlexAvailabilityChecker.<Start>d__6.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexAvailabilityChecker.cs:line 35


```

#### Problem Description:

Availability of movies is partially working.

#### Reproduction Steps:

1. Request several movies (at least 7)
2. Approve each movie manually to radarr
3. Let Radarr do its thing to download
4. Check Ombi a little while later
5. Not all movies get marked as available only some do

**Comment by tidusjar** [comment]
#1720
