### ISSUE TITLE
Issue with Telegram notification for New Request

### ISSUE THREAD

**Issue by Danguard** [tidusjar/Ombi#1711]
#### Ombi build Version:

V 3.0.2351

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

1.9.7.4441

#### Operating System:

Windows 10 Professional

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
fail: Ombi.Notifications.NotificationService[4000]
      Failed to notify for notification: Ombi.Notifications.Agents.TelegramNotification
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Notifications.Agents.TelegramNotification.<RequestApproved>d__14.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Agents\TelegramNotification.cs:line 102
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.Interfaces.BaseNotification`1.<NotifyAsync>d__31.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.Interfaces.BaseNotification`1.<NotifyAsync>d__30.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.NotificationService.<NotifyAsync>d__9.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\NotificationService.cs:line 83
fail: Ombi.Notifications.NotificationService[4000]
      Failed to notify for notification: Ombi.Notifications.Agents.TelegramNotification
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Notifications.Agents.TelegramNotification.<RequestApproved>d__14.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Agents\TelegramNotification.cs:line 102
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.Interfaces.BaseNotification`1.<NotifyAsync>d__31.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.Interfaces.BaseNotification`1.<NotifyAsync>d__30.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.NotificationService.<NotifyAsync>d__9.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\NotificationService.cs:line 83
fail: Ombi.Api.Api[1000]
      StatusCode: 429, Reason:
fail: Ombi.Api.Api[1000]
      StatusCode: 429, Reason:
fail: Ombi.Notifications.NotificationService[4000]
      Failed to notify for notification: Ombi.Notifications.Agents.TelegramNotification
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Notifications.Agents.TelegramNotification.<RequestApproved>d__14.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Agents\TelegramNotification.cs:line 102
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.Interfaces.BaseNotification`1.<NotifyAsync>d__31.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.Interfaces.BaseNotification`1.<NotifyAsync>d__30.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.NotificationService.<NotifyAsync>d__9.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\NotificationService.cs:line 83

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

When requesting a movie (with auto approval turned on or off, it doesn't matter), there's no notification on telegram for new request done. 
The test for telegram bot is working and the "request available" is working too.

#### Reproduction Steps:

Tried to add a movie request, it worked nicely, received the ok from Ombi for it, but there's no telegram action on the group.
From the log there's no information about it, but running ombi from command prompt i got the information i wrote above.
I was unable to make it work, dunno if it's something i've done not in the right way.. 

Could you confirm if it's an issue? Any way i can help you?

Thank you.

**Comment by tidusjar** [comment]
What's your template set up as?

**Comment by Danguard** [comment]
i changed the "Request Approved" in the following:
Subject:
{ApplicationName}: your request has been approved

Message:
Hello! Your request for {Title} has been approved!


Everything else is as default.

Obviously the check on Enable is set.

**Comment by Danguard** [comment]
Never mind, got it working.
Going to close this issue, was a problem by my side.
Sorry.

**Comment by Danguard** [comment]
Well.. guess i should have checked better, the issue is still there.
New request is working correctly, but once i approve the request, the error appears again.
No notification on telegram and same error:

'fail: Ombi.Notifications.NotificationService[4000]
      Failed to notify for notification: Ombi.Notifications.Agents.TelegramNotification
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Notifications.Agents.TelegramNotification.<AvailableRequest>d__15.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Agents\TelegramNotification.cs:line 114
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.Interfaces.BaseNotification`1.<NotifyAsync>d__31.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 76
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.Interfaces.BaseNotification`1.<NotifyAsync>d__30.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.NotificationService.<NotifyAsync>d__9.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\NotificationService.cs:line 83'

Templates for Request Approved:
(HTML Formatting)

Message:
La richiesta per <b>{Title}</b> è stata approvata.

**Comment by didyouexpectthat** [comment]
I believe I also have this in 2386, but no error in the Logs folder??? Very strange. 
I didn't get the two notifications for the two movies I added...  I tried to test a Telegram notification, it passed.
My `New Request` value is
```
User '{RequestedUser}' requested {Type} '{Title}'.
Request Date: {RequestedDate}
#plexrequests
```
And my `Request Approved` value is 
```
Request for {Title} was approved.
#plexrequests
```

**Comment by tidusjar** [comment]
Can you try with the latest build?

**Comment by Danguard** [comment]
Installed 3.0.2410

With Subject ' Test ' under Request Approved there's no error on ombi, but there's no notification neither.

Changing Subject to ' {ApplicationName}: your request has been approved ' this time doesn't give me any error, but still no notification.

HTML Formatting

**Comment by tidusjar** [comment]
The subject is not used with Telegram

**Comment by Danguard** [comment]
True, but it was still a way to have some kind of information about the issue i was encountering.
Now i don't have any information from logs nor from ombi started from command prompt to help you out.
Any other way to help you finding the bug?

**Comment by Danguard** [comment]
Installed 3.0.2440
Now the telegram notifications are working correctly.
Thank you.
