### ISSUE TITLE
Not automatically marking 'Available' and sending email 

### ISSUE THREAD

**Issue by bcpletcher** [tidusjar/Ombi#1715]
#### Ombi build Version:

V 3.0.2356

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

 v3.27.1

#### Operating System:

Windows 10 (Docker)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2017-11-15 12:55:16.701 -05:00 [Information] Start installing Hangfire SQL objects...
2017-11-15 12:55:16.909 -05:00 [Information] Hangfire SQL objects installed.
2017-11-15 12:55:16.968 -05:00 [Information] Starting Hangfire Server
2017-11-15 12:55:16.983 -05:00 [Information] Using job storage: 'SQLite Server: /config/Ombi.db'
2017-11-15 12:55:16.983 -05:00 [Information] Using the following options for Hangfire Server:
2017-11-15 12:55:16.983 -05:00 [Information]     Worker count: 1
2017-11-15 12:55:16.984 -05:00 [Information]     Listening queues: 'default'
2017-11-15 12:55:16.984 -05:00 [Information]     Shutdown timeout: 1.00:00:00
2017-11-15 12:55:16.984 -05:00 [Information]     Schedule polling interval: 00:00:15
2017-11-15 13:00:10.603 -05:00 [Warning] Failed to process the job '134': an exception occurred. Retry attempt 1 of 1 will be performed in 00:00:16.
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: T. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.<Request>d__8`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Service.OmbiService.<GetUpdates>d__10.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Service\OmbiService.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 218
2017-11-15 13:00:33.422 -05:00 [Information] 1 scheduled job(s) enqueued.
2017-11-15 13:00:44.554 -05:00 [Error] Failed to process the job '134': an exception occurred.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 218
2017-11-15 13:05:15.281 -05:00 [Error] StatusCode: 429, Reason: 
2017-11-15 13:05:15.292 -05:00 [Error] StatusCode: 429, Reason: 
2017-11-15 13:05:15.336 -05:00 [Error] StatusCode: 429, Reason: 
2017-11-15 13:26:48.489 -05:00 [Error] StatusCode: 429, Reason: 
2017-11-15 13:26:48.518 -05:00 [Error] StatusCode: 429, Reason: 
2017-11-15 13:26:48.536 -05:00 [Error] StatusCode: 429, Reason: 
2017-11-15 13:26:48.789 -05:00 [Error] StatusCode: 429, Reason: 
2017-11-15 13:26:48.823 -05:00 [Error] StatusCode: 429, Reason: 
2017-11-15 13:26:48.973 -05:00 [Error] StatusCode: 429, Reason: 
2017-11-15 13:26:49.006 -05:00 [Error] StatusCode: 429, Reason: 
2017-11-15 13:26:49.022 -05:00 [Error] StatusCode: 429, Reason: 
2017-11-15 13:26:49.058 -05:00 [Error] StatusCode: 429, Reason: 
2017-11-15 13:26:49.084 -05:00 [Error] StatusCode: 429, Reason: 
2017-11-15 13:26:49.091 -05:00 [Error] StatusCode: 429, Reason: 
2017-11-15 13:26:49.223 -05:00 [Error] StatusCode: 429, Reason: 
2017-11-15 13:26:49.278 -05:00 [Error] StatusCode: 429, Reason: 
2017-11-15 13:26:49.278 -05:00 [Error] StatusCode: 429, Reason: 
2017-11-15 13:26:49.316 -05:00 [Error] StatusCode: 429, Reason: 
2017-11-15 13:26:49.377 -05:00 [Error] StatusCode: 429, Reason: 
2017-11-15 13:26:49.392 -05:00 [Error] StatusCode: 429, Reason: 
2017-11-15 13:26:49.577 -05:00 [Error] StatusCode: 429, Reason: 
2017-11-15 13:26:49.584 -05:00 [Error] StatusCode: 429, Reason: 
2017-11-15 13:26:49.603 -05:00 [Error] StatusCode: 429, Reason: 
2017-11-15 13:26:49.617 -05:00 [Error] StatusCode: 429, Reason: 
2017-11-15 13:26:49.747 -05:00 [Error] StatusCode: 429, Reason: 
2017-11-15 13:26:49.762 -05:00 [Error] StatusCode: 429, Reason: 

```

#### Problem Description:

When a movie is marked approved, it will send over to Radarr and Sabnzbd will do its thing. Once completed Radarr will show it is available and Plex allows me to watch it. Ombi, however, does not mark it as Available and will not send notification email to requester. Email does works for Requested and Approved as expected along with when I manually mark it as available.

#### Reproduction Steps:
1) Non admin adds movie request
2) Admin approves it, gets sent to Radarr/Sabnzbd
3) Finishes and becomes available in Plex

--Gave Ombi time to process, and tried multiple movie requests with no luck.

**Comment by PotatoQuality** [comment]
https://github.com/tidusjar/Ombi/issues/1714

**Comment by PotatoQuality** [comment]
@tidusjar  can you give this your light?

**Comment by bcpletcher** [comment]
Thank you for looking into the matter! Can I provide anymore information to help you guys out?

**Comment by tidusjar** [comment]
I cannot seem to recreate this. 

Is this still an issue?

**Comment by bcpletcher** [comment]
I will try another movie and report back with the logs for said day if it is still occuring
