### ISSUE TITLE
Ombi.Schedule.Jobs.Plex.PlexAvailabilityChecker

### ISSUE THREAD

**Issue by mike3y** [tidusjar/Ombi#1718]
#### Ombi build Version:

V 3.0.2356

#### Update Branch:

DotNetCore

#### Media Sever:

Plex

#### Media Server Version:

1.9.7.4460 

#### Operating System:

Windows 2012 R2

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

at Ombi.Schedule.Jobs.Plex.PlexAvailabilityChecker.<Start>d__6.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexAvailabilityChecker.cs:line 35

I don't have this directory. My guess is that it's looking at the developer's computer for this directory.

#### Reproduction Steps:

Just letting it run... It does this all day.

**Comment by Unimatrix0** [comment]
Is this supposed to be a bug report? Where’s the problem description? Where are the logs?

**Comment by tidusjar** [comment]
That path is the compiled path, where the application was compiled, it has no bearing other than a stack trace.

What's your plex settings like?

**Comment by didyouexpectthat** [comment]
I was getting this as well.
```
2017-11-16 16:26:02.157 -08:00 [Error] Failed to process the job '2174': an exception occurred.
Hangfire.BackgroundJobClientException: Background job creation failed. See inner exception for details. ---> Microsoft.Data.Sqlite.SqliteException: SQLite Error 5: 'database is locked'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteScalar()
   at Dapper.SqlMapper.ExecuteScalarImpl[T](IDbConnection cnn, CommandDefinition& command)
   at Dapper.SqlMapper.ExecuteScalar[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType)
   at Hangfire.SQLite.SQLiteStorageConnection.<>c__DisplayClass5_0.<CreateExpiredJob>b__0(DbConnection connection)
   at Hangfire.SQLite.SQLiteStorage.UseConnection[T](Func`2 func, Boolean isWriteLock)
   at Hangfire.SQLite.SQLiteStorageConnection.CreateExpiredJob(Job job, IDictionary`2 parameters, DateTime createdAt, TimeSpan expireIn)
   at Hangfire.Client.CoreBackgroundJobFactory.Create(CreateContext context)
   at Hangfire.Client.BackgroundJobFactory.<>c__DisplayClass7_0.<CreateWithFilters>b__0()
   at Hangfire.Client.BackgroundJobFactory.InvokeClientFilter(IClientFilter filter, CreatingContext preContext, Func`1 continuation)
   at Hangfire.Client.BackgroundJobFactory.Create(CreateContext context)
   at Hangfire.BackgroundJobClient.Create(Job job, IState state)
   --- End of inner exception stack trace ---
   at Hangfire.BackgroundJobClient.Create(Job job, IState state)
   at Ombi.Schedule.Jobs.Plex.PlexAvailabilityChecker.<ProcessMovies>d__8.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexAvailabilityChecker.cs:line 143
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Schedule.Jobs.Plex.PlexAvailabilityChecker.<Start>d__6.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexAvailabilityChecker.cs:line 35
```
