### ISSUE TITLE
Command line switches do not work as documented

### ISSUE THREAD

**Issue by jasonlyle88** [tidusjar/Ombi#1719]
#### Ombi build Version:

V 3.0.2356

#### Update Branch:

Open Beta

#### Operating System:

```
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
```

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

/opt/ombi3/Ombi -h "http://*:5000" -s "/opt/ombi3"
Hello, welcome to Ombi
Valid options are:
Ombi 3.0.2356-DotNetCore
Copyright (C) 2017 Ombi

  -h, --host       (Default: http://*:5000) Set to a semicolon-separated (;)
                   list of URL prefixes to which the server should respond. For
                   example, http://localhost:123. Use "*" to indicate that the
                   server should listen for requests on any IP address or
                   hostname using the specified port and protocol (for example,
                   http://*:5000). The protocol (http:// or https://) must be
                   included with each URL. Supported formats vary between
                   servers.

  -s, --storage    Storage path, where we save the logs and database

  --help           Display this help screen.

  --version        Display version information.



We are running on

Unhandled Exception: System.FormatException: The short switch '-h' is not defined in the switch mappings.
   at Microsoft.Extensions.Configuration.CommandLine.CommandLineConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Ombi.Program.Main(String[] args) in C:\projects\requestplex\src\Ombi\Program.cs:line 64
Aborted (core dumped)

```

#### Problem Description:

The command line switches for Ombi don't work appropriately. -h and -s dont work; --h and --s work as well as --host and --storage

#### Reproduction Steps:

Try running on linux by specifying either the host or storage command line switches as -h or -s

**Comment by mkeedlinger** [comment]
Same problem here.

**Comment by mkeedlinger** [comment]
@tidusjar Much thanks! Have a great day!
