### ISSUE TITLE
Email notification doesn't send by ombi

### ISSUE THREAD

**Issue by PotatoQuality** [tidusjar/Ombi#1722]
#### Ombi build Version:

V 3.0.2363

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

1.7.430

#### Operating System:

Windows 10

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

fail: Ombi.Api.Api[1000]
      StatusCode: NotFound, Reason: Not Found
fail: Ombi.Notifications.GenericEmailProvider[0]
      Exception when attempting to send email
System.ArgumentNullException: Value can not be null.
   at EnsureThat.EnsureArg.IsNotNull[T](T value, String paramName)
   at EnsureThat.EnsureArg.IsNotNullOrEmpty(String value, String paramName)
   at Ombi.Notifications.GenericEmailProvider.<Send>d__6.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 104
fail: Ombi.Notifications.NotificationService[4000]
      Failed to notify for notification: Ombi.Notifications.Agents.EmailNotification
System.ArgumentNullException: Value can not be null.
   at EnsureThat.EnsureArg.IsNotNull[T](T value, String paramName)
   at EnsureThat.EnsureArg.IsNotNullOrEmpty(String value, String paramName)
   at Ombi.Notifications.GenericEmailProvider.<Send>d__6.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 154
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.Agents.EmailNotification.<Send>d__14.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Agents\EmailNotification.cs:line 162
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.Agents.EmailNotification.<RequestApproved>d__12.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Agents\EmailNotification.cs:line 144
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.Interfaces.BaseNotification`1.<NotifyAsync>d__31.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.Interfaces.BaseNotification`1.<NotifyAsync>d__30.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.NotificationService.<NotifyAsync>d__9.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\NotificationService.cs:line 83
```

#### Problem Description:

Email notification doesn't be sended by Ombi after tv show or movie is available on plex.

Test mail is working.

Also when i mark something manually "available" it is still not working

#### Reproduction Steps:

![image](https://user-images.githubusercontent.com/2944704/32982243-9283c3a8-cc81-11e7-8838-e1ef53c12581.png)

**Comment by tidusjar** [comment]
The user who requested has a email address?

**Comment by PotatoQuality** [comment]
@tidusjar  Yes, i'm testing it on my own admin account.

**Comment by tidusjar** [comment]
Email sender is filled out in the settings too right?

**Comment by PotatoQuality** [comment]
@tidusjar  Yes, i just marked it above with a white block.

**Comment by mmozeiko** [comment]
Yup, I have same issue - misbehaving notifications (most of time - no notifications) in #1660.

**Comment by tidusjar** [comment]
I cannot recreate this by pressing the Mark Available button

**Comment by tidusjar** [comment]
Can you try with the latest build?

**Comment by mmozeiko** [comment]
I've been running commit 237acc9 for last two days - so far good, all notifications arrive for me as expected.
