### ISSUE TITLE
Updater fails to launch custom update script

### ISSUE THREAD

**Issue by Unimatrix0** [tidusjar/Ombi#1726]
#### Ombi build Version:

V 3.0.2367

#### Update Branch:

Open Beta

#### Operating System:

Ubuntu 16.04.03 LTS

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
2017-11-21 11:36:42.795 -06:00 [Warning] Failed to process the job '2': an exception occurred. Retry attempt 1 of 1 will be performed in 00:00:33.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.GetArgs(UpdateSettings settings) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 231
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.RunScript(UpdateSettings settings, String downloadUrl) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 249
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 218
```

#### Problem Description:

Ombi automatic updater fails to launch custom update script.

#### Reproduction Steps:

1. Set a custom update script.
2. Check for update
3. Update
4. ???
5. Profit...I mean fail...

**Comment by tidusjar** [comment]
Looks like i've already fixed this, can you try the latest version?

**Comment by Unimatrix0** [comment]
Didn't work with 2377, gonna test 2378

**Comment by tidusjar** [comment]
If that doesn't work can you post the error?

**Comment by Unimatrix0** [comment]
Doesn't work on 2378 either. No error messages (or other log output) though.

**Comment by tidusjar** [comment]
OK looks like the issue has been fixed. 

Make sure the settings are like the following:
![image](https://user-images.githubusercontent.com/6642220/33420842-0c4fe926-d5a8-11e7-83e8-3c2ddd5ba128.png)

**Comment by tidusjar** [comment]
Any luck?
