### ISSUE TITLE
Error creating the admin user

### ISSUE THREAD

**Issue by L0rdBootysniffer** [tidusjar/Ombi#1729]
#### Ombi build Version:

V 3.0.2379

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

1.9.6.4429

#### Operating System:

Ubuntu 17.04

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2017-11-21 18:36:48.392 -05:00 [Information] Start installing Hangfire SQL objects...
2017-11-21 18:36:48.616 -05:00 [Information] Hangfire SQL objects installed.
2017-11-21 18:36:48.648 -05:00 [Information] Starting Hangfire Server
2017-11-21 18:36:48.651 -05:00 [Information] Using job storage: 'SQLite Server: Schedules.db'
2017-11-21 18:36:48.652 -05:00 [Information] Using the following options for Hangfire Server:
2017-11-21 18:36:48.652 -05:00 [Information]     Worker count: 1
2017-11-21 18:36:48.652 -05:00 [Information]     Listening queues: 'default'
2017-11-21 18:36:48.652 -05:00 [Information]     Shutdown timeout: 1.00:00:00
2017-11-21 18:36:48.652 -05:00 [Information]     Schedule polling interval: 00:00:15
2017-11-21 18:36:52.172 -05:00 [Information] Hangfire Server stopped.
2017-11-21 18:41:45.589 -05:00 [Information] Start installing Hangfire SQL objects...
2017-11-21 18:41:45.685 -05:00 [Information] Hangfire SQL objects installed.
2017-11-21 18:41:45.717 -05:00 [Information] Starting Hangfire Server
2017-11-21 18:41:45.721 -05:00 [Information] Using job storage: 'SQLite Server: Schedules.db'
2017-11-21 18:41:45.721 -05:00 [Information] Using the following options for Hangfire Server:
2017-11-21 18:41:45.721 -05:00 [Information]     Worker count: 1
2017-11-21 18:41:45.721 -05:00 [Information]     Listening queues: 'default'
2017-11-21 18:41:45.721 -05:00 [Information]     Shutdown timeout: 1.00:00:00
2017-11-21 18:41:45.721 -05:00 [Information]     Schedule polling interval: 00:00:15
2017-11-21 18:42:27.279 -05:00 [Information] Created User "xxxxx"
2017-11-21 18:42:27.484 -05:00 [Information] Created the roles
2017-11-21 18:42:27.671 -05:00 [Information] Added the Admin role
2017-11-21 18:42:28.250 -05:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized
2017-11-21 18:49:50.870 -05:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized
2017-11-21 18:52:46.224 -05:00 [Information] Error occurred during execution of 'ServerHeartbeat' process. Execution will be retried (attempt #2) in 00:00:04 seconds.
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 8: 'attempt to write a readonly database'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader)
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command)
   at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType)
   at Hangfire.SQLite.SQLiteStorageConnection.<>c__DisplayClass16_0.<Heartbeat>b__0(DbConnection connection)
   at Hangfire.SQLite.SQLiteStorage.<>c__DisplayClass19_0.<UseConnection>b__0(DbConnection connection)
   at Hangfire.SQLite.SQLiteStorage.UseConnection[T](Func`2 func, Boolean isWriteLock)
   at Hangfire.SQLite.SQLiteStorage.UseConnection(Action`1 action, Boolean isWriteLock)
   at Hangfire.Server.ServerHeartbeat.Execute(BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
2017-11-21 18:52:50.228 -05:00 [Warning] Error occurred during execution of 'ServerHeartbeat' process. Execution will be retried (attempt #3) in 00:00:06 seconds.
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 8: 'attempt to write a readonly database'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader)
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command)
   at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType)
   at Hangfire.SQLite.SQLiteStorageConnection.<>c__DisplayClass16_0.<Heartbeat>b__0(DbConnection connection)
   at Hangfire.SQLite.SQLiteStorage.<>c__DisplayClass19_0.<UseConnection>b__0(DbConnection connection)
   at Hangfire.SQLite.SQLiteStorage.UseConnection[T](Func`2 func, Boolean isWriteLock)
   at Hangfire.SQLite.SQLiteStorage.UseConnection(Action`1 action, Boolean isWriteLock)
   at Hangfire.Server.ServerHeartbeat.Execute(BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
2017-11-21 18:52:56.233 -05:00 [Error] Error occurred during execution of 'ServerHeartbeat' process. Execution will be retried (attempt #4) in 00:00:13 seconds.
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 8: 'attempt to write a readonly database'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader)
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command)
   at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType)
   at Hangfire.SQLite.SQLiteStorageConnection.<>c__DisplayClass16_0.<Heartbeat>b__0(DbConnection connection)
   at Hangfire.SQLite.SQLiteStorage.<>c__DisplayClass19_0.<UseConnection>b__0(DbConnection connection)
   at Hangfire.SQLite.SQLiteStorage.UseConnection[T](Func`2 func, Boolean isWriteLock)
   at Hangfire.SQLite.SQLiteStorage.UseConnection(Action`1 action, Boolean isWriteLock)
   at Hangfire.Server.ServerHeartbeat.Execute(BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
2017-11-21 18:53:00.951 -05:00 [Information] Error occurred during execution of 'RecurringJobScheduler' process. Execution will be retried (attempt #2) in 00:00:02 seconds.
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 8: 'attempt to write a readonly database'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader)
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command)
   at Hangfire.SQLite.SQLiteStorageConnection.<>c__DisplayClass12_0.<SetRangeInHash>b__0(DbConnection connection, DbTransaction transaction)
   at Hangfire.SQLite.SQLiteStorage.<>c__DisplayClass21_0.<UseTransaction>b__0(DbConnection connection, DbTransaction transaction)
   at Hangfire.SQLite.SQLiteStorage.<>c__DisplayClass22_0`1.<UseTransaction>b__0(DbConnection connection)
   at Hangfire.SQLite.SQLiteStorage.UseConnection[T](Func`2 func, Boolean isWriteLock)
   at Hangfire.SQLite.SQLiteStorage.UseTransaction[T](Func`3 func, Nullable`1 isolationLevel)
   at Hangfire.SQLite.SQLiteStorage.UseTransaction(Action`2 action)
   at Hangfire.Server.RecurringJobScheduler.TryScheduleJob(JobStorage storage, IStorageConnection connection, String recurringJobId, IReadOnlyDictionary`2 recurringJob)
   at Hangfire.Server.RecurringJobScheduler.<>c__DisplayClass8_0.<Execute>b__0(IStorageConnection connection)
   at Hangfire.Server.RecurringJobScheduler.UseConnectionDistributedLock(JobStorage storage, Action`1 action)
   at Hangfire.Server.RecurringJobScheduler.Execute(BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
2017-11-21 18:53:09.236 -05:00 [Error] Error occurred during execution of 'ServerHeartbeat' process. Execution will be retried (attempt #5) in 00:00:21 seconds.
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 8: 'attempt to write a readonly database'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader)
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command)
   at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType)
   at Hangfire.SQLite.SQLiteStorageConnection.<>c__DisplayClass16_0.<Heartbeat>b__0(DbConnection connection)
   at Hangfire.SQLite.SQLiteStorage.<>c__DisplayClass19_0.<UseConnection>b__0(DbConnection connection)
   at Hangfire.SQLite.SQLiteStorage.UseConnection[T](Func`2 func, Boolean isWriteLock)
   at Hangfire.SQLite.SQLiteStorage.UseConnection(Action`1 action, Boolean isWriteLock)
   at Hangfire.Server.ServerHeartbeat.Execute(BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
2017-11-21 18:53:28.620 -05:00 [Information] Hangfire Server stopped.
2017-11-21 18:53:42.308 -05:00 [Information] Start installing Hangfire SQL objects...
2017-11-21 18:53:42.364 -05:00 [Information] Hangfire SQL objects installed.
2017-11-21 18:53:42.389 -05:00 [Information] Starting Hangfire Server
2017-11-21 18:53:42.392 -05:00 [Information] Using job storage: 'SQLite Server: Schedules.db'
2017-11-21 18:53:42.392 -05:00 [Information] Using the following options for Hangfire Server:
2017-11-21 18:53:42.393 -05:00 [Information]     Worker count: 1
2017-11-21 18:53:42.393 -05:00 [Information]     Listening queues: 'default'
2017-11-21 18:53:42.393 -05:00 [Information]     Shutdown timeout: 1.00:00:00
2017-11-21 18:53:42.393 -05:00 [Information]     Schedule polling interval: 00:00:15
2017-11-21 18:55:32.810 -05:00 [Information] Hangfire Server stopped.
2017-11-21 18:56:39.635 -05:00 [Information] Start installing Hangfire SQL objects...
2017-11-21 18:56:39.695 -05:00 [Information] Hangfire SQL objects installed.
2017-11-21 18:56:39.723 -05:00 [Information] Starting Hangfire Server
2017-11-21 18:56:39.726 -05:00 [Information] Using job storage: 'SQLite Server: Schedules.db'
2017-11-21 18:56:39.726 -05:00 [Information] Using the following options for Hangfire Server:
2017-11-21 18:56:39.726 -05:00 [Information]     Worker count: 1
2017-11-21 18:56:39.727 -05:00 [Information]     Listening queues: 'default'
2017-11-21 18:56:39.727 -05:00 [Information]     Shutdown timeout: 1.00:00:00
2017-11-21 18:56:39.727 -05:00 [Information]     Schedule polling interval: 00:00:15
2017-11-21 19:07:55.100 -05:00 [Information] Hangfire Server stopped.
2017-11-21 19:08:14.276 -05:00 [Information] Start installing Hangfire SQL objects...
2017-11-21 19:08:14.365 -05:00 [Information] Hangfire SQL objects installed.
2017-11-21 19:08:14.391 -05:00 [Information] Starting Hangfire Server
2017-11-21 19:08:14.395 -05:00 [Information] Using job storage: 'SQLite Server: Schedules.db'
2017-11-21 19:08:14.395 -05:00 [Information] Using the following options for Hangfire Server:
2017-11-21 19:08:14.395 -05:00 [Information]     Worker count: 1
2017-11-21 19:08:14.395 -05:00 [Information]     Listening queues: 'default'
2017-11-21 19:08:14.395 -05:00 [Information]     Shutdown timeout: 1.00:00:00
2017-11-21 19:08:14.395 -05:00 [Information]     Schedule polling interval: 00:00:15


```

#### Problem Description:

Failed to create admin user

#### Reproduction Steps:

See above. If I choose to make Plex user the admin, I get "Could not get the Plex Admin Information"

If I choose to make my own local admin user, I get "There was an error... You might want to put this on Github..."

**Comment by tidusjar** [comment]
Looks like the application doesn't have the permissions to write to `Ombi.db`

```
 'attempt to write a readonly database'.
```

Can you please check the permissions

**Comment by L0rdBootysniffer** [comment]
I checked. Nothing seemed out of the ordinary. I even chmod 777'd everything in that directory to see if it would potentially work.

**Comment by tidusjar** [comment]
I'd recommend deleting the `Ombi.db` and `Schedules.db` and trying again with the new permissions now.

**Comment by L0rdBootysniffer** [comment]
I left the permissions at 777 and deleted Ombi.db and Schedules.db, but I get:

.
info: Ombi.Controllers.IdentityController[0]
      Created User xxxxx
info: Ombi.Controllers.IdentityController[0]
      Created the roles
info: Ombi.Controllers.IdentityController[0]
      Added the Admin role
fail: Ombi.Api.Api[1000]
      StatusCode: Unauthorized, Reason: Unauthorized

**Comment by tidusjar** [comment]
Can you get past the wizard?

**Comment by L0rdBootysniffer** [comment]
No, I'm unable to get past both assigning the Plex user as admin via the authentication token and creating a local admin profile.

**Comment by L0rdBootysniffer** [comment]
Figured it out. For some very weird reason the www-data user/group owned my root directory. When I switched the permissions back it worked just fine. Sorry for the headache.
