### ISSUE TITLE
Pushover 'New Request' notification: NullReferenceException

### ISSUE THREAD

**Issue by frebib** [tidusjar/Ombi#1732]
#### Ombi build Version:

V 3.0.2379-DotNetCore

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

Latest, whatever that is

#### Operating System:

Linux x64

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
fail: Ombi.Notifications.NotificationService[4000]
      Failed to notify for notification: Ombi.Notifications.Agents.PushoverNotification
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Notifications.Agents.PushoverNotification.<AvailableRequest>d__15.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Agents\PushoverNotification.cs:line 118
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.Interfaces.BaseNotification`1.<NotifyAsync>d__31.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 76
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.Interfaces.BaseNotification`1.<NotifyAsync>d__30.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.NotificationService.<NotifyAsync>d__9.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\NotificationService.cs:line 83
```

When a film is requested, Ombi fails to send the pushover notification and spits out this error. Hitting the 'Test' button sends a notification

**Comment by tidusjar** [comment]
What's your RequestAvailable template for Pushover?

**Comment by tidusjar** [comment]
Can you try this with the latest build?

**Comment by frebib** [comment]
I'm using all the default templates, with all notifications for Pushover enabled.

Just tested on 3.0.2409 and got no errors but also no notification.
Is there a more verbose logging option?
Also does requesting as admin also trigger the notifications?

**Comment by frebib** [comment]
I thought I'd just test 'Pushbullet' as I have that installed too and after filling out the required fields and hitting 'Test' it spits this into the logs:
```
fail: Ombi.Api.Api[1000]
      StatusCode: BadRequest, Reason: Bad Request
```

**Comment by Fr00t** [comment]
Just wanted to chime in and say that I've got the same issue. Old version had the same logs as OP, and newest (Think it was .2422) has no errors in logs, but still no Pushover notifications.

**Comment by frebib** [comment]
Still not working as of 2460. Is there anything else I can try to debug this?
