### ISSUE TITLE
Switches don't work / Can't change port

### ISSUE THREAD

**Issue by welcometopwn** [tidusjar/Ombi#1733]
#### Ombi build Version:

V 3.0.2381

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Windows Server 2016

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

Ombi.exe -h http://*:9005
Hello, welcome to Ombi
Valid options are:
Ombi 3.0.2381-DotNetCore
Copyright (C) 2017 Ombi

  -h, --host       (Default: http://*:5000) Set to a semicolon-separated (;)
                   list of URL prefixes to which the server should respond. For
                   example, http://localhost:123. Use "*" to indicate that the
                   server should listen for requests on any IP address or
                   hostname using the specified port and protocol (for example,
                   http://*:5000). The protocol (http:// or https://) must be
                   included with each URL. Supported formats vary between
                   servers.

  -s, --storage    Storage path, where we save the logs and database

  --help           Display this help screen.

  --version        Display version information.



We are running on http://*:9005

Unhandled Exception: System.FormatException: The short switch '-h' is not defined in the switch mappings.
   at Microsoft.Extensions.Configuration.CommandLine.CommandLineConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Ombi.Program.Main(String[] args) in C:\projects\requestplex\src\Ombi\Program.cs:line 64

```

#### Problem Description:

Switches do not work for the command line

#### Reproduction Steps:

Run Ombi with -h, -s switch

**Comment by tidusjar** [comment]
Try --h. There is already a bug open about this but thanks!

**Comment by tidusjar** [comment]
#1719
