### ISSUE TITLE
Cannot communicate with CouchPotato

### ISSUE THREAD

**Issue by BrandonEckert** [tidusjar/Ombi#1735]
#### Ombi build Version:

V 3.0.2386 

#### Update Branch:

Open Beta

#### Media Sever:

Plex/Emby

#### Operating System:

Debian 9 x64

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(2017-11-24 18:40:39.191 -05:00 [Information] Start installing Hangfire SQL objects...
2017-11-24 18:40:39.245 -05:00 [Information] Hangfire SQL objects installed.
2017-11-24 18:40:39.270 -05:00 [Information] Starting Hangfire Server
2017-11-24 18:40:39.273 -05:00 [Information] Using job storage: 'SQLite Server: Schedules.db'
2017-11-24 18:40:39.273 -05:00 [Information] Using the following options for Hangfire Server:
2017-11-24 18:40:39.273 -05:00 [Information]     Worker count: 1
2017-11-24 18:40:39.273 -05:00 [Information]     Listening queues: 'default'
2017-11-24 18:40:39.273 -05:00 [Information]     Shutdown timeout: 1.00:00:00
2017-11-24 18:40:39.273 -05:00 [Information]     Schedule polling interval: 00:00:15
2017-11-24 18:41:00.568 -05:00 [Error] Could not test CP
System.TypeInitializationException: The type initializer for 'System.Net.Http.CurlHandler' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Http' threw an exception. ---> S$
 (Exception from HRESULT: 0x8007007E)
   at Interop.Http.GetSslVersionDescription()
   at Interop.HttpInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.Http..cctor()
   --- End of inner exception stack trace ---
   at Interop.Http.GetSupportedFeatures()
   at System.Net.Http.CurlHandler..cctor()
   --- End of inner exception stack trace ---
   at System.Net.Http.CurlHandler..ctor()
   at System.Net.Http.HttpClientHandler..ctor()
   at Ombi.Api.Api.<GetHandler>d__6.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Api.<Request>d__8`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.CouchPotato.CouchPotatoApi.<Status>d__4.MoveNext() in C:\projects\requestplex\src\Ombi.Api.CouchPotato\CouchPotatoApi.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<CouchPotato>d__59.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 278
2017-11-24 18:41:29.530 -05:00 [Error] Could not test CP
System.TypeInitializationException: The type initializer for 'System.Net.Http.CurlHandler' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Http' threw an exception. ---> S$
 (Exception from HRESULT: 0x8007007E)
   at Interop.Http.GetSslVersionDescription()
   at Interop.HttpInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.Http..cctor()
   --- End of inner exception stack trace ---
   at Interop.Http.GetSupportedFeatures()
   at System.Net.Http.CurlHandler..cctor()
   --- End of inner exception stack trace ---
   at System.Net.Http.CurlHandler..ctor()
   at System.Net.Http.HttpClientHandler..ctor()
   at Ombi.Api.Api.<GetHandler>d__6.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Api.<Request>d__8`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.CouchPotato.CouchPotatoApi.<Status>d__4.MoveNext() in C:\projects\requestplex\src\Ombi.Api.CouchPotato\CouchPotatoApi.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<CouchPotato>d__59.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 278


```

#### Problem Description:
I have CouchPotato setup and working on the same server that I installed Ombi 3 on.
I have filled out the correct server, port, username, password, and api key. Upon hitting "Test Connectivity", I receive a pop up that "Successfully Saved the couch potato settings". I am however unable to utilize Couch Potato through Omb, nor does the "get quality profiles" populate the drop down.
#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
https://github.com/tidusjar/Ombi/wiki/Common-Errors#systemnethttpcurlhandler
