### ISSUE TITLE
New Install does not see Plex Library and is Stuck on "Processing Request".

### ISSUE THREAD

**Issue by rjsears** [tidusjar/Ombi#1738]
#### Ombi build Version:

V 3.0.2386

#### Update Branch:

DotNetCore

#### Media Sever:

Plex

#### Media Server Version:

1.9.7.4460

#### Operating System:

Ubuntu 17

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2017-11-25 20:09:17.760 -07:00 [Information] Start installing Hangfire SQL objects...
2017-11-25 20:09:17.834 -07:00 [Information] Hangfire SQL objects installed.
2017-11-25 20:09:17.865 -07:00 [Information] Starting Hangfire Server
2017-11-25 20:09:17.868 -07:00 [Information] Using job storage: 'SQLite Server: Schedules.db'
2017-11-25 20:09:17.869 -07:00 [Information] Using the following options for Hangfire Server:
2017-11-25 20:09:17.869 -07:00 [Information]     Worker count: 1
2017-11-25 20:09:17.869 -07:00 [Information]     Listening queues: 'default'
2017-11-25 20:09:17.869 -07:00 [Information]     Shutdown timeout: 1.00:00:00
2017-11-25 20:09:17.870 -07:00 [Information]     Schedule polling interval: 00:00:15
2017-11-25 20:30:03.129 -07:00 [Error] StatusCode: 429, Reason:
2017-11-25 20:30:03.140 -07:00 [Error] StatusCode: 429, Reason:
2017-11-25 20:30:04.626 -07:00 [Error] StatusCode: 429, Reason:
2017-11-25 20:30:07.343 -07:00 [Error] StatusCode: 429, Reason:
```

#### Problem Description:

Fresh install. Connected to Plex server, when I click the "Test Connectivity" buttons, comes back ok.

When I search for something that is already in Plex, it allows me to add it as a new request instead of telling me that it is already there. I have verified that the token and machine identifier are both correct.

Regardless, even if I add it as a request and approve the request it never pushes the show to Couchpotato even when it has been requested, it is a just stuck on "Processing Request". 

#### Reproduction Steps:

Add new request, approve request.

**Comment by PotatoQuality** [comment]
Pleas run importer manually and place after the run the logs over here

**Comment by rjsears** [comment]
'''
2017-11-26 00:25:36.238 -07:00 [Information] Hangfire Server stopped.
2017-11-26 00:25:43.701 -07:00 [Information] Start installing Hangfire SQL objects...
2017-11-26 00:25:43.773 -07:00 [Information] Hangfire SQL objects installed.
2017-11-26 00:25:43.804 -07:00 [Information] Starting Hangfire Server
2017-11-26 00:25:43.808 -07:00 [Information] Using job storage: 'SQLite Server: Schedules.db'
2017-11-26 00:25:43.808 -07:00 [Information] Using the following options for Hangfire Server:
2017-11-26 00:25:43.809 -07:00 [Information]     Worker count: 1
2017-11-26 00:25:43.809 -07:00 [Information]     Listening queues: 'default'
2017-11-26 00:25:43.810 -07:00 [Information]     Shutdown timeout: 1.00:00:00
2017-11-26 00:25:43.810 -07:00 [Information]     Schedule polling interval: 00:00:15
2017-11-26 05:00:19.935 -07:00 [Warning] Failed to process the job '94': an exception occurred. Retry attempt 1 of 1 will be performed in 00:00:25.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 219
2017-11-26 05:00:49.846 -07:00 [Information] 1 scheduled job(s) enqueued.
2017-11-26 05:04:30.022 -07:00 [Information] Hangfire Server stopped.
2017-11-26 05:04:49.784 -07:00 [Information] Start installing Hangfire SQL objects...
2017-11-26 05:04:49.856 -07:00 [Information] Hangfire SQL objects installed.
2017-11-26 05:04:49.888 -07:00 [Information] Starting Hangfire Server
2017-11-26 05:04:49.892 -07:00 [Information] Using job storage: 'SQLite Server: Schedules.db'
2017-11-26 05:04:49.892 -07:00 [Information] Using the following options for Hangfire Server:
2017-11-26 05:04:49.892 -07:00 [Information]     Worker count: 1
2017-11-26 05:04:49.893 -07:00 [Information]     Listening queues: 'default'
2017-11-26 05:04:49.893 -07:00 [Information]     Shutdown timeout: 1.00:00:00
2017-11-26 05:04:49.893 -07:00 [Information]     Schedule polling interval: 00:00:15
2017-11-26 11:00:13.689 -07:00 [Warning] Failed to process the job '137': an exception occurred. Retry attempt 1 of 1 will be performed in 00:00:30.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 219
2017-11-26 11:00:57.193 -07:00 [Information] 1 scheduled job(s) enqueued.
'''

**Comment by rjsears** [comment]
This was from the previous night:

```--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.CouchPotato.CouchPotatoApi.<Status>d__4.MoveNext() in C:\projects\requestplex\src\Ombi.Api.CouchPotato\CouchPotatoApi.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<CouchPotato>d__59.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 278
2017-11-25 22:43:57.307 -07:00 [Error] StatusCode: NotFound, Reason: Not Found
2017-11-25 22:43:57.309 -07:00 [Error] Could not test CP
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.<Request>d__8`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 84
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.CouchPotato.CouchPotatoApi.<Status>d__4.MoveNext() in C:\projects\requestplex\src\Ombi.Api.CouchPotato\CouchPotatoApi.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<CouchPotato>d__59.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 278
2017-11-25 22:43:59.480 -07:00 [Error] StatusCode: NotFound, Reason: Not Found
2017-11-25 22:43:59.482 -07:00 [Error] Could not test CP
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.<Request>d__8`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 84
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.CouchPotato.CouchPotatoApi.<Status>d__4.MoveNext() in C:\projects\requestplex\src\Ombi.Api.CouchPotato\CouchPotatoApi.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<CouchPotato>d__59.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 278
2017-11-25 23:59:12.303 -07:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized
```

**Comment by PotatoQuality** [comment]
Pleas run the import plex library  and after it finished pleas post your log file over here.

**Comment by rjsears** [comment]
OK, I don't have a "Import Plex Library" anythere that I can find. I do have a "Manually Run Cacher". Is this what you are referring to above?

To try and make things easier I switched libraries on my Plex to contain a single movie, and that movie is the exact same movie I am searching for in Ombi. I just pushed the "Manually Run Cacher" button and there have been no changes in the logs as all. Not sure if it takes some time to run or not.

**Comment by tidusjar** [comment]
Interesting,

Can you do the following for me?

Run the in the browser: 
http://localhost:32400/library/sections?X-Plex-Token=PLEXTOKEN

That should show you all the libraries, find the correct library and the `key` part.
Then:

http://localhost:32400/library/sections/KEY/all?X-Plex-Token=PLEXTOKEN

That should list this 1 movie? 

Can you confirm this

**Comment by rjsears** [comment]
Worked just fine. I can see the Library and the single movie listed as well.

**Comment by Aegrum** [comment]
I have what appears to be the same issues as above.

When I go to http://localhost:32400/library/sections?X-Plex-Token=[PLEX TOKEN IN OMBI] I can see the libraries fine. However, when I go to http://localhost:32400/library/sections/KEY/all?X-Plex-Token=[PLEX TOKEN IN OMBI] I get 400 Bad Request.

Here is the log after I run Plex Cacher manually:
`warn: Ombi.Schedule.Jobs.Plex.PlexContentSync[2000]
      Exception thrown when attempting to cache the Plex Content
Newtonsoft.Json.JsonReaderException: Could not convert string to integer: medium. Path 'MediaContainer.Metadata[0].Media[0].Part[0].Stream[0].level', line 1, position 2008.
   at Newtonsoft.Json.JsonReader.ReadInt32String(String s)
   at Newtonsoft.Json.JsonTextReader.FinishReadQuotedNumber(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsInt32()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.<Request>d__8`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 84
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Plex.PlexApi.<GetMetadata>d__15.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 107
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.<StartTheCache>d__17.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 207
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.<CacheContent>d__16.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 79`

**Comment by Aegrum** [comment]
Nevermind! Apparently I had an issue with one particular movie that was causing the above error. When I removed the offending movie (The Hangover 2), the problem resolved itself and all the content now caches.
