### ISSUE TITLE
Unable to Update Ombi

### ISSUE THREAD

**Issue by Fiala06** [tidusjar/Ombi#1739]
#### Ombi build Version:

V 3.0.2379

#### Update Branch:

DotNetCore

#### Media Sever:

Plex

#### Operating System:

Windows 10 Pro x64

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2017-11-25 04:00:58.116 -08:00 [Warning] Failed to process the job '494': an exception occurred. Retry attempt 1 of 1 will be performed in 00:00:16.
System.IO.IOException: The process cannot access the file 'Remotion.Linq.dll' because it is being used by another process.
   at System.IO.Win32FileSystem.RemoveDirectoryHelper(String fullPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Win32FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 218
2017-11-25 04:01:16.620 -08:00 [Information] 1 scheduled job(s) enqueued.
2017-11-25 04:02:24.652 -08:00 [Information] Start installing Hangfire SQL objects...
2017-11-25 04:02:24.701 -08:00 [Information] Hangfire SQL objects installed.
2017-11-25 04:02:24.723 -08:00 [Information] Starting Hangfire Server
2017-11-25 04:02:24.725 -08:00 [Information] Using job storage: 'SQLite Server: Schedules.db'
2017-11-25 04:02:24.725 -08:00 [Information] Using the following options for Hangfire Server:
2017-11-25 04:02:24.725 -08:00 [Information]     Worker count: 1
2017-11-25 04:02:24.726 -08:00 [Information]     Listening queues: 'default'
2017-11-25 04:02:24.726 -08:00 [Information]     Shutdown timeout: 1.00:00:00
2017-11-25 04:02:24.726 -08:00 [Information]     Schedule polling interval: 00:00:15

```

#### Problem Description:

I've noticed ombi isn't updating itself. After a look at the cron jobs, I've noticed its suppose to update every 6 hrs it looks like. Hasn't been working. Enable automatic updates is checked. 

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by L0rdBootysniffer** [comment]
To add to this, I'm unable to launch Ombi after updating. It looks like it could be related to your problem:

```

We are running on
/opt/Ombi
info: Hangfire.SQLite.SQLiteStorage[0]
      Start installing Hangfire SQL objects...
info: Hangfire.SQLite.SQLiteStorage[0]
      Hangfire SQL objects installed.
info: Hangfire.BackgroundJobServer[0]
      Starting Hangfire Server
info: Hangfire.BackgroundJobServer[0]
      Using job storage: 'SQLite Server: Schedules.db'
info: Hangfire.BackgroundJobServer[0]
      Using the following options for Hangfire Server:
info: Hangfire.BackgroundJobServer[0]
          Worker count: 1
info: Hangfire.BackgroundJobServer[0]
          Listening queues: 'default'
info: Hangfire.BackgroundJobServer[0]
          Shutdown timeout: 1.00:00:00
info: Hangfire.BackgroundJobServer[0]
          Schedule polling interval: 00:00:15

Unhandled Exception: System.InvalidOperationException: Expression object should be not null.
   at Hangfire.Common.Job.FromExpression(LambdaExpression methodCall, Type explicitType)
   at Ombi.Schedule.JobSetup.Setup() in C:\projects\requestplex\src\Ombi.Schedule\JobSetup.cs:line 46
   at Ombi.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IMemoryCache cache, IServiceProvider serviceProvider) in C:\projects\requestplex\src\Ombi\Startup.cs:line 186
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Ombi.Program.Main(String[] args) in C:\projects\requestplex\src\Ombi\Program.cs:line 64

```

**Comment by tidusjar** [comment]
#1460

**Comment by Fiala06** [comment]
Thanks, whats the best way to update then without losing my settings?

**Comment by tidusjar** [comment]
Download the new zip and overwrite everything

**Comment by Fiala06** [comment]
Yeah tried that still says there is an update. Stopped the service, overwrote all the files, rebooted. Cleared cache. 

Still have: Version: 3.0.2404 (New Update Available)

**Comment by Fiala06** [comment]
Thanks, got it working!
