### ISSUE TITLE
Ombi fails to launch after latest update for Sickrage

### ISSUE THREAD

**Issue by didyouexpectthat** [tidusjar/Ombi#1740]
#### Ombi build Version:

V 3.0.2387 (upgraded from 2386)

#### Update Branch:

DotNetCore

#### Media Server:

Plex

#### Media Server Version:

N/a

#### Operating System:

Debian 8

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
2017-11-27 07:55:17.575 -08:00 [Information] Start installing Hangfire SQL objects...
2017-11-27 07:55:17.662 -08:00 [Information] Hangfire SQL objects installed.
2017-11-27 07:55:17.703 -08:00 [Information] Starting Hangfire Server
2017-11-27 07:55:17.708 -08:00 [Information] Using job storage: 'SQLite Server: Schedules.db'
2017-11-27 07:55:17.708 -08:00 [Information] Using the following options for Hangfire Server:
2017-11-27 07:55:17.708 -08:00 [Information]     Worker count: 1
2017-11-27 07:55:17.709 -08:00 [Information]     Listening queues: 'default'
2017-11-27 07:55:17.709 -08:00 [Information]     Shutdown timeout: 1.00:00:00
2017-11-27 07:55:17.709 -08:00 [Information]     Schedule polling interval: 00:00:15
2017-11-27 07:55:27.953 -08:00 [Information] Start installing Hangfire SQL objects...
2017-11-27 07:55:28.036 -08:00 [Information] Hangfire SQL objects installed.
2017-11-27 07:55:28.076 -08:00 [Information] Starting Hangfire Server
2017-11-27 07:55:28.081 -08:00 [Information] Using job storage: 'SQLite Server: Schedules.db'
2017-11-27 07:55:28.082 -08:00 [Information] Using the following options for Hangfire Server:
2017-11-27 07:55:28.082 -08:00 [Information]     Worker count: 1
2017-11-27 07:55:28.082 -08:00 [Information]     Listening queues: 'default'
2017-11-27 07:55:28.082 -08:00 [Information]     Shutdown timeout: 1.00:00:00
2017-11-27 07:55:28.082 -08:00 [Information]     Schedule polling interval: 00:00:15
2017-11-27 07:55:38.571 -08:00 [Information] Start installing Hangfire SQL objects...
2017-11-27 07:55:38.657 -08:00 [Information] Hangfire SQL objects installed.
2017-11-27 07:55:38.698 -08:00 [Information] Starting Hangfire Server
2017-11-27 07:55:38.703 -08:00 [Information] Using job storage: 'SQLite Server: Schedules.db'
2017-11-27 07:55:38.703 -08:00 [Information] Using the following options for Hangfire Server:
2017-11-27 07:55:38.703 -08:00 [Information]     Worker count: 1
2017-11-27 07:55:38.703 -08:00 [Information]     Listening queues: 'default'
2017-11-27 07:55:38.703 -08:00 [Information]     Shutdown timeout: 1.00:00:00
2017-11-27 07:55:38.703 -08:00 [Information]     Schedule polling interval: 00:00:15
```
```
Nov 27 07:57:23 plexrequests Ombi[19388]: Unhandled Exception: System.InvalidOperationException: Unable to resolve service for type 'Ombi.Schedule.Jobs.SickRage.ISickRageSync' while attempting to activate 'Ombi.Schedule.JobSetup'.
Nov 27 07:57:23 plexrequests Ombi[19388]: at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, ISet`1 callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
Nov 27 07:57:23 plexrequests Ombi[19388]: at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, ISet`1 callSiteChain)
Nov 27 07:57:23 plexrequests Ombi[19388]: at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, ISet`1 callSiteChain)
Nov 27 07:57:23 plexrequests Ombi[19388]: at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, ISet`1 callSiteChain)
Nov 27 07:57:23 plexrequests Ombi[19388]: at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, ISet`1 callSiteChain)
Nov 27 07:57:23 plexrequests Ombi[19388]: at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType, ServiceProvider serviceProvider)
Nov 27 07:57:23 plexrequests Ombi[19388]: at System.Collections.Concurrent.ConcurrentDictionaryExtensions.GetOrAdd[TKey,TValue,TArg](ConcurrentDictionary`2 dictionary, TKey key, Func`3 valueFactory, TArg arg)
Nov 27 07:57:23 plexrequests Ombi[19388]: at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
Nov 27 07:57:23 plexrequests Ombi[19388]: at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
Nov 27 07:57:23 plexrequests Ombi[19388]: at Ombi.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IMemoryCache cache, IServiceProvider serviceProvider) in C:\projects\requestplex\src\Ombi\Startup.cs:line 181
Nov 27 07:57:23 plexrequests Ombi[19388]: --- End of stack trace from previous location where exception was thrown ---
Nov 27 07:57:23 plexrequests Ombi[19388]: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Nov 27 07:57:23 plexrequests Ombi[19388]: at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
Nov 27 07:57:23 plexrequests Ombi[19388]: at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
Nov 27 07:57:23 plexrequests Ombi[19388]: at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
Nov 27 07:57:23 plexrequests Ombi[19388]: at Ombi.Program.Main(String[] args) in C:\projects\requestplex\src\Ombi\Program.cs:line 64
Nov 27 07:57:23 plexrequests systemd[1]: ombi.service: main process exited, code=killed, status=6/ABRT
Nov 27 07:57:23 plexrequests systemd[1]: Unit ombi.service entered failed state.
```

#### Problem Description:

After upgrade fail to launch Ombi.

#### Reproduction Steps:

Upgrade and see error. Cannot start Ombi now.

**Comment by mike3y** [comment]
I just downloaded as of 11:03am.

It says in the description that crash was fixed, but it's still crashing.

**Comment by tidusjar** [comment]
What's the error @mike3y

**Comment by didyouexpectthat** [comment]
When I updated, I got 3.0.2387, but I just updated again and got 3.0.2388.

Now on 2388, I get this.
```
Nov 27 08:08:09 plexrequests Ombi[27474]: Unhandled Exception: System.InvalidOperationException: Expression object should be not null.
Nov 27 08:08:09 plexrequests Ombi[27474]: at Hangfire.Common.Job.FromExpression(LambdaExpression methodCall, Type explicitType)
Nov 27 08:08:09 plexrequests Ombi[27474]: at Ombi.Schedule.JobSetup.Setup() in C:\projects\requestplex\src\Ombi.Schedule\JobSetup.cs:line 46
Nov 27 08:08:09 plexrequests Ombi[27474]: at Ombi.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IMemoryCache cache, IServiceProvider serviceProvider) in C:\projects\requestplex\src\Ombi\Startup.cs:line 186
Nov 27 08:08:09 plexrequests Ombi[27474]: --- End of stack trace from previous location where exception was thrown ---
Nov 27 08:08:09 plexrequests Ombi[27474]: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Nov 27 08:08:09 plexrequests Ombi[27474]: at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
Nov 27 08:08:09 plexrequests Ombi[27474]: at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
Nov 27 08:08:09 plexrequests Ombi[27474]: at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
Nov 27 08:08:09 plexrequests Ombi[27474]: at Ombi.Program.Main(String[] args) in C:\projects\requestplex\src\Ombi\Program.cs:line 64
Nov 27 08:08:09 plexrequests systemd[1]: ombi.service: main process exited, code=killed, status=6/ABRT
Nov 27 08:08:09 plexrequests systemd[1]: Unit ombi.service entered failed state.
```

**Comment by mike3y** [comment]
Thanks that worked

**Comment by mike3y** [comment]
I lied. It now loads, but trying to get to the website it's stuck on "Loading..."

**Comment by didyouexpectthat** [comment]
Agree with mike3y.
This is all the logs show. 

```2017-11-27 09:37:30.940 -08:00 [Information] Start installing Hangfire SQL objects...
2017-11-27 09:37:31.038 -08:00 [Information] Hangfire SQL objects installed.
2017-11-27 09:37:31.081 -08:00 [Information] Starting Hangfire Server
2017-11-27 09:37:31.086 -08:00 [Information] Using job storage: 'SQLite Server: Schedules.db'
2017-11-27 09:37:31.086 -08:00 [Information] Using the following options for Hangfire Server:
2017-11-27 09:37:31.086 -08:00 [Information]     Worker count: 1
2017-11-27 09:37:31.086 -08:00 [Information]     Listening queues: 'default'
2017-11-27 09:37:31.086 -08:00 [Information]     Shutdown timeout: 1.00:00:00
2017-11-27 09:37:31.086 -08:00 [Information]     Schedule polling interval: 00:00:15
2017-11-27 09:38:18.473 -08:00 [Warning] Failed to process the job '1202': an exception occurred. Retry attempt 1 of 1 will be performed in 00:00:38.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 219
2017-11-27 09:39:02.411 -08:00 [Information] 1 scheduled job(s) enqueued.
2017-11-27 09:39:18.042 -08:00 [Error] Failed to process the job '1202': an exception occurred.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 219
```
