### ISSUE TITLE
SickRage issues

### ISSUE THREAD

**Issue by didyouexpectthat** [tidusjar/Ombi#1744]
#### Ombi build Version:

V 3.0.2404

#### Update Branch:

DotNetCore

#### Media Sever:

Plex

#### Media Server Version:

N/A

#### Operating System:

Debian 8

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
kNov 27 17:11:14 plexrequests systemd[1]: Starting Systemd script to run Ombi as a service...
Nov 27 17:11:14 plexrequests systemd[1]: Started Systemd script to run Ombi as a service.
Nov 27 17:11:15 plexrequests Ombi[4075]: Hello, welcome to Ombi
Nov 27 17:11:15 plexrequests Ombi[4075]: Valid options are:
Nov 27 17:11:15 plexrequests Ombi[4075]: Ombi 3.0.2404-DotNetCore
Nov 27 17:11:15 plexrequests Ombi[4075]: Copyright (C) 2017 Ombi
Nov 27 17:11:15 plexrequests Ombi[4075]: -h, --host       (Default: http://*:5000) Set to a semicolon-separated (;)
Nov 27 17:11:15 plexrequests Ombi[4075]: list of URL prefixes to which the server should respond. For
Nov 27 17:11:15 plexrequests Ombi[4075]: example, http://localhost:123. Use "*" to indicate that the
Nov 27 17:11:15 plexrequests Ombi[4075]: server should listen for requests on any IP address or
Nov 27 17:11:15 plexrequests Ombi[4075]: hostname using the specified port and protocol (for example,
Nov 27 17:11:15 plexrequests Ombi[4075]: http://*:5000). The protocol (http:// or https://) must be
Nov 27 17:11:15 plexrequests Ombi[4075]: included with each URL. Supported formats vary between
Nov 27 17:11:15 plexrequests Ombi[4075]: servers.
Nov 27 17:11:15 plexrequests Ombi[4075]: -s, --storage    Storage path, where we save the logs and database
Nov 27 17:11:15 plexrequests Ombi[4075]: --help           Display this help screen.
Nov 27 17:11:15 plexrequests Ombi[4075]: --version        Display version information.
Nov 27 17:11:17 plexrequests Ombi[4075]: We are running on
Nov 27 17:11:17 plexrequests Ombi[4075]: /opt/ombi
Nov 27 17:11:20 plexrequests Ombi[4075]: info: Hangfire.SQLite.SQLiteStorage[0]
Nov 27 17:11:20 plexrequests Ombi[4075]: Start installing Hangfire SQL objects...
Nov 27 17:11:20 plexrequests Ombi[4075]: info: Hangfire.SQLite.SQLiteStorage[0]
Nov 27 17:11:20 plexrequests Ombi[4075]: Hangfire SQL objects installed.
Nov 27 17:11:20 plexrequests Ombi[4075]: info: Hangfire.BackgroundJobServer[0]
Nov 27 17:11:20 plexrequests Ombi[4075]: Starting Hangfire Server
Nov 27 17:11:20 plexrequests Ombi[4075]: info: Hangfire.BackgroundJobServer[0]
Nov 27 17:11:20 plexrequests Ombi[4075]: Using job storage: 'SQLite Server: Schedules.db'
Nov 27 17:11:20 plexrequests Ombi[4075]: info: Hangfire.BackgroundJobServer[0]
Nov 27 17:11:20 plexrequests Ombi[4075]: Using the following options for Hangfire Server:
Nov 27 17:11:20 plexrequests Ombi[4075]: info: Hangfire.BackgroundJobServer[0]
Nov 27 17:11:20 plexrequests Ombi[4075]: Worker count: 1
Nov 27 17:11:20 plexrequests Ombi[4075]: info: Hangfire.BackgroundJobServer[0]
Nov 27 17:11:20 plexrequests Ombi[4075]: Listening queues: 'default'
Nov 27 17:11:20 plexrequests Ombi[4075]: info: Hangfire.BackgroundJobServer[0]
Nov 27 17:11:20 plexrequests Ombi[4075]: Shutdown timeout: 1.00:00:00
Nov 27 17:11:20 plexrequests Ombi[4075]: info: Hangfire.BackgroundJobServer[0]
Nov 27 17:11:20 plexrequests Ombi[4075]: Schedule polling interval: 00:00:15
Nov 27 17:11:22 plexrequests Ombi[4075]: Hosting environment: Production
Nov 27 17:11:22 plexrequests Ombi[4075]: Content root path: /opt/ombi
Nov 27 17:11:22 plexrequests Ombi[4075]: Now listening on: http://[::]:5001
Nov 27 17:11:22 plexrequests Ombi[4075]: Application started. Press Ctrl+C to shut down.
Nov 27 17:24:03 plexrequests Ombi[4075]: fail: Ombi.Api.Api[1000]
Nov 27 17:24:03 plexrequests Ombi[4075]: StatusCode: NotFound, Reason: Not Found
Nov 27 17:24:03 plexrequests Ombi[4075]: fail: Ombi.Api.Api[1000]
Nov 27 17:24:03 plexrequests Ombi[4075]: StatusCode: NotFound, Reason: Not Found
Nov 27 17:24:04 plexrequests Ombi[4075]: fail: Ombi.Api.Api[1000]
Nov 27 17:24:04 plexrequests Ombi[4075]: StatusCode: BadRequest, Reason: Bad Request
Nov 27 17:24:04 plexrequests Ombi[4075]: fail: Ombi.Api.Api[1000]
Nov 27 17:24:04 plexrequests Ombi[4075]: StatusCode: NotFound, Reason: Not Found
Nov 27 17:24:04 plexrequests Ombi[4075]: fail: Ombi.Api.Api[1000]
Nov 27 17:24:04 plexrequests Ombi[4075]: StatusCode: NotFound, Reason: Not Found
Nov 27 17:24:05 plexrequests Ombi[4075]: fail: Ombi.Api.Api[1000]
Nov 27 17:24:05 plexrequests Ombi[4075]: StatusCode: NotFound, Reason: Not Found
Nov 27 17:24:05 plexrequests Ombi[4075]: fail: Ombi.Api.Api[1000]
Nov 27 17:24:05 plexrequests Ombi[4075]: StatusCode: NotFound, Reason: Not Found
Nov 27 17:24:05 plexrequests Ombi[4075]: fail: Ombi.Api.Api[1000]
Nov 27 17:24:05 plexrequests Ombi[4075]: StatusCode: NotFound, Reason: Not Found
Nov 27 17:24:06 plexrequests Ombi[4075]: fail: Ombi.Api.Api[1000]
Nov 27 17:24:06 plexrequests Ombi[4075]: StatusCode: NotFound, Reason: Not Found
Nov 27 17:24:06 plexrequests Ombi[4075]: fail: Ombi.Api.Api[1000]
Nov 27 17:24:06 plexrequests Ombi[4075]: StatusCode: BadRequest, Reason: Bad Request
Nov 27 17:24:06 plexrequests Ombi[4075]: fail: Ombi.Api.Api[1000]
Nov 27 17:24:06 plexrequests Ombi[4075]: StatusCode: NotFound, Reason: Not Found
Nov 27 17:24:06 plexrequests Ombi[4075]: fail: Ombi.Api.Api[1000]
Nov 27 17:24:06 plexrequests Ombi[4075]: StatusCode: NotFound, Reason: Not Found
Nov 27 17:25:51 plexrequests Ombi[4075]: fail: Ombi.Notifications.GenericEmailProvider[0]
Nov 27 17:25:51 plexrequests Ombi[4075]: Exception when attempting to send email
Nov 27 17:25:51 plexrequests Ombi[4075]: System.ArgumentNullException: Value can not be null.
Nov 27 17:25:51 plexrequests Ombi[4075]: at EnsureThat.EnsureArg.IsNotNull[T](T value, String paramName)
Nov 27 17:25:51 plexrequests Ombi[4075]: at EnsureThat.EnsureArg.IsNotNullOrEmpty(String value, String paramName)
Nov 27 17:25:51 plexrequests Ombi[4075]: at Ombi.Notifications.GenericEmailProvider.<Send>d__6.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 104
Nov 27 17:25:51 plexrequests Ombi[4075]: fail: Ombi.Notifications.NotificationService[4000]
Nov 27 17:25:51 plexrequests Ombi[4075]: Failed to notify for notification: Ombi.Notifications.Agents.EmailNotification
Nov 27 17:25:51 plexrequests Ombi[4075]: System.ArgumentNullException: Value can not be null.
Nov 27 17:25:51 plexrequests Ombi[4075]: at EnsureThat.EnsureArg.IsNotNull[T](T value, String paramName)
Nov 27 17:25:51 plexrequests Ombi[4075]: at EnsureThat.EnsureArg.IsNotNullOrEmpty(String value, String paramName)
Nov 27 17:25:51 plexrequests Ombi[4075]: at Ombi.Notifications.GenericEmailProvider.<Send>d__6.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 154
Nov 27 17:25:51 plexrequests Ombi[4075]: --- End of stack trace from previous location where exception was thrown ---
Nov 27 17:25:51 plexrequests Ombi[4075]: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Nov 27 17:25:51 plexrequests Ombi[4075]: at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Nov 27 17:25:51 plexrequests Ombi[4075]: at Ombi.Notifications.Agents.EmailNotification.<Send>d__14.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Agents\EmailNotification.cs:line 162
Nov 27 17:25:51 plexrequests Ombi[4075]: --- End of stack trace from previous location where exception was thrown ---
Nov 27 17:25:51 plexrequests Ombi[4075]: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Nov 27 17:25:51 plexrequests Ombi[4075]: at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Nov 27 17:25:51 plexrequests Ombi[4075]: at Ombi.Notifications.Agents.EmailNotification.<RequestApproved>d__12.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Agents\EmailNotification.cs:line 144
Nov 27 17:25:51 plexrequests Ombi[4075]: --- End of stack trace from previous location where exception was thrown ---
Nov 27 17:25:51 plexrequests Ombi[4075]: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Nov 27 17:25:51 plexrequests Ombi[4075]: at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Nov 27 17:25:51 plexrequests Ombi[4075]: at Ombi.Notifications.Interfaces.BaseNotification`1.<NotifyAsync>d__31.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 79
Nov 27 17:25:51 plexrequests Ombi[4075]: --- End of stack trace from previous location where exception was thrown ---
Nov 27 17:25:51 plexrequests Ombi[4075]: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Nov 27 17:25:51 plexrequests Ombi[4075]: at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Nov 27 17:25:51 plexrequests Ombi[4075]: at Ombi.Notifications.Interfaces.BaseNotification`1.<NotifyAsync>d__30.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 43
Nov 27 17:25:51 plexrequests Ombi[4075]: --- End of stack trace from previous location where exception was thrown ---
Nov 27 17:25:51 plexrequests Ombi[4075]: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Nov 27 17:25:51 plexrequests Ombi[4075]: at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Nov 27 17:25:51 plexrequests Ombi[4075]: at Ombi.Notifications.NotificationService.<NotifyAsync>d__9.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\NotificationService.cs:line 83
Nov 27 17:30:07 plexrequests Ombi[4075]: info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
Nov 27 17:30:07 plexrequests Ombi[4075]: Starting Plex Content Cacher
Nov 27 17:30:07 plexrequests Ombi[4075]: info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
Nov 27 17:30:07 plexrequests Ombi[4075]: Getting all content from server plexrequests
Nov 27 17:30:08 plexrequests Ombi[4075]: info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
Nov 27 17:30:08 plexrequests Ombi[4075]: We found 2 items
Nov 27 17:30:08 plexrequests Ombi[4075]: info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
Nov 27 17:30:08 plexrequests Ombi[4075]: Processing Movies
Nov 27 17:30:08 plexrequests Ombi[4075]: info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
Nov 27 17:30:08 plexrequests Ombi[4075]: Processing TV Shows
Nov 27 17:30:09 plexrequests Ombi[4075]: info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
Nov 27 17:30:09 plexrequests Ombi[4075]: We already have show xxxxx checking for new season
..
Nov 27 17:30:21 plexrequests Ombi[4075]: info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
Nov 27 17:30:21 plexrequests Ombi[4075]: We already have show xxxxx checking for new season
Nov 27 17:30:21 plexrequests Ombi[4075]: info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
Nov 27 17:30:21 plexrequests Ombi[4075]: Starting EP Cacher
Nov 27 17:30:24 plexrequests Ombi[4075]: info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
Nov 27 17:30:24 plexrequests Ombi[4075]: Total Epsiodes found for TV = 9104
Nov 27 17:30:28 plexrequests Ombi[4075]: info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
Nov 27 17:30:28 plexrequests Ombi[4075]: Processed 1000 more episodes. Total Remaining 8104
..
Nov 27 17:30:48 plexrequests Ombi[4075]: info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
Nov 27 17:30:48 plexrequests Ombi[4075]: We have finished caching the episodes.
Nov 27 17:35:04 plexrequests Ombi[4075]: fail: Ombi.Schedule.Jobs.SickRage.SickRageSync[2009]
Nov 27 17:35:04 plexrequests Ombi[4075]: Exception when trying to cache SickRage
Nov 27 17:35:04 plexrequests Ombi[4075]: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: SickRageCache'.
Nov 27 17:35:04 plexrequests Ombi[4075]: at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
Nov 27 17:35:04 plexrequests Ombi[4075]: at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
Nov 27 17:35:04 plexrequests Ombi[4075]: at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
Nov 27 17:35:04 plexrequests Ombi[4075]: at System.Data.Common.DbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
Nov 27 17:35:04 plexrequests Ombi[4075]: --- End of stack trace from previous location where exception was thrown ---
Nov 27 17:35:04 plexrequests Ombi[4075]: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Nov 27 17:35:04 plexrequests Ombi[4075]: at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Nov 27 17:35:04 plexrequests Ombi[4075]: at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.<ExecuteAsync>d__17.MoveNext()
Nov 27 17:35:04 plexrequests Ombi[4075]: --- End of stack trace from previous location where exception was thrown ---
Nov 27 17:35:04 plexrequests Ombi[4075]: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Nov 27 17:35:04 plexrequests Ombi[4075]: at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Nov 27 17:35:04 plexrequests Ombi[4075]: at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.<ExecuteSqlCommandAsync>d__13.MoveNext()
Nov 27 17:35:04 plexrequests Ombi[4075]: --- End of stack trace from previous location where exception was thrown ---
Nov 27 17:35:04 plexrequests Ombi[4075]: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Nov 27 17:35:04 plexrequests Ombi[4075]: at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Nov 27 17:35:04 plexrequests Ombi[4075]: at Ombi.Schedule.Jobs.SickRage.SickRageSync.<Start>d__6.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\SickRage\SickRageSync.cs:line 51
```

#### Problem Description:

Some issues I encountered were:
1. I searched a show I had and it showed as **Available** as well as **View on Plex**, everything great.
1a. I searched another show I had, it did not show as **Available** on the right, but showed **View on Plex**. See screenshot below
![image](https://user-images.githubusercontent.com/1329077/33297952-9794f1f0-d398-11e7-825c-6bb9e46c05f8.png)
1b. I clicked **Request** expecting that it would turn to **Available** but it did not.
1c. I have all but 3 episodes of the show, so not sure if this has anything to do with the logic involved... but it could also be that only the first item shows as being Available while no other ones do.

2. I'm getting all the errors above. I do not acknowledge these errors from any other day of logging I have. 
2a. As mentioned in 1b, I clicked the **Request** button and it tried at that time to send out an e-mail and a Telegram msg. I did not get an e-mail for this.

3. After the sync, it threw an exception for missing SR Cache table 

4. I requested a new TV show; Ombi confirmed that it was successful but I have no idea what actually happened. Sickrage did not have an entry for the show. Nothing in the logs, either. 
![image](https://user-images.githubusercontent.com/1329077/33298936-098bc2d4-d39e-11e7-8191-096debf120fd.png)
Then I tried to readd the same show because it is in a unrequested state; get this message: 
![image](https://user-images.githubusercontent.com/1329077/33298919-f0bdc8ba-d39d-11e7-84f8-cc4e7e3cfcec.png)

5. I went to search for a new show and when it searched, it returned all of these:
```
2017-11-27 18:09:21.996 -08:00 [Error] StatusCode: BadRequest, Reason: Bad Request
2017-11-27 18:09:22.343 -08:00 [Error] StatusCode: NotFound, Reason: Not Found
2017-11-27 18:09:22.433 -08:00 [Error] StatusCode: NotFound, Reason: Not Found
2017-11-27 18:09:22.717 -08:00 [Error] StatusCode: NotFound, Reason: Not Found
2017-11-27 18:09:23.259 -08:00 [Error] StatusCode: NotFound, Reason: Not Found
2017-11-27 18:09:23.613 -08:00 [Error] StatusCode: NotFound, Reason: Not Found
2017-11-27 18:09:23.729 -08:00 [Error] StatusCode: NotFound, Reason: Not Found
2017-11-27 18:09:24.003 -08:00 [Error] StatusCode: BadRequest, Reason: Bad Request
2017-11-27 18:09:24.360 -08:00 [Error] StatusCode: NotFound, Reason: Not Found
2017-11-27 18:09:24.506 -08:00 [Error] StatusCode: NotFound, Reason: Not Found
```

6. My Chrome console is flooded with items. 
![image](https://user-images.githubusercontent.com/1329077/33299038-94efb510-d39e-11e7-9545-41b54aa3252f.png)

#### Reproduction Steps:

Since starting, all I have done is start Ombi, open the UI and visit the Sickrage; then I fixed the job schedule I wanted; then I clicked through the remaining menu options just to review if everything looked right (just a habit of mine). I didn't notice all the errors until after I went looking for why my shows are _Available_ but not **Available**

**Comment by tidusjar** [comment]
Regarding 1.
It will only show as Available if you have every single episode. If you do not have every episode then the user still can request the remaining episodes.

2. Either your Mail settings is not filled in correctly or the email address of the recipient is not present.

3. I can fix that... Oops

4. Sickrage integration is still a WIP i'd say.

**Comment by tidusjar** [comment]
Since the missing migrations are now present. Can you please try again?

**Comment by didyouexpectthat** [comment]
1. That makes sense. Thanks.
2. They were working just fine the other day, and have made zero changes to email. When I click test, I am getting the same experience as clicking "submit" -- it is not sending a test e-mail. I am not getting any logs about e-mail today. 
3. Cool story.
4. :) 


This happened earlier this morning; can you tell me what happened?
```2017-11-28 08:06:21.006 -08:00 [Information] 9 servers were removed due to timeout
2017-11-28 08:11:21.071 -08:00 [Information] 26 servers were removed due to timeout
2017-11-28 08:16:21.089 -08:00 [Information] 25 servers were removed due to timeout
2017-11-28 08:21:21.108 -08:00 [Information] 25 servers were removed due to timeout
2017-11-28 08:26:21.124 -08:00 [Information] 24 servers were removed due to timeout
2017-11-28 08:31:21.143 -08:00 [Information] 26 servers were removed due to timeout
2017-11-28 08:36:21.160 -08:00 [Information] 25 servers were removed due to timeout
2017-11-28 08:41:21.179 -08:00 [Information] 24 servers were removed due to timeout
2017-11-28 08:46:21.199 -08:00 [Information] 25 servers were removed due to timeout
2017-11-28 08:51:21.223 -08:00 [Information] 25 servers were removed due to timeout
2017-11-28 08:56:21.253 -08:00 [Information] 25 servers were removed due to timeout
2017-11-28 09:01:21.272 -08:00 [Information] 25 servers were removed due to timeout
2017-11-28 09:06:21.327 -08:00 [Information] 25 servers were removed due to timeout
2017-11-28 09:11:21.342 -08:00 [Information] 23 servers were removed due to timeout
2017-11-28 09:16:21.355 -08:00 [Information] 10 servers were removed due to timeout
2017-11-28 09:21:21.376 -08:00 [Information] 9 servers were removed due to timeout
2017-11-28 09:26:21.391 -08:00 [Information] 7 servers were removed due to timeout
2017-11-28 09:31:21.423 -08:00 [Information] 7 servers were removed due to timeout
2017-11-28 09:36:21.447 -08:00 [Information] 5 servers were removed due to timeout
2017-11-28 09:41:21.476 -08:00 [Information] 1 servers were removed due to timeout```
20-something servers???

**Comment by tidusjar** [comment]
It seems that Hangfire timed out for some reason. Hangfire is our background processor. 

What did you do to your email to fix it?

I'll close this since all issues have been resolved?

**Comment by didyouexpectthat** [comment]
Once I hit test and it said bad password in the logs (strange) so I typed it in again and hit submit and then test and the e-mail seems okay.
I'll look for new errors and keep you updated. Thanks!
