### ISSUE TITLE
Automatic update does not work

### ISSUE THREAD

**Issue by rafuz** [tidusjar/Ombi#1753]
#### Ombi build Version:

V 3.0.2407

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

not relevant

#### Operating System:

Ubuntu 17.04

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
Nov 29 17:43:26 ***.org Ombi[3839]:       We are linux
Nov 29 17:43:27 ***.org Ombi[3839]: info: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
Nov 29 17:43:27 ***.org Ombi[3839]:       Downloading the file linux.tar.gz from https://ci.appveyor.com/api/buildjobs/ngq9c0dew582r13e/artifacts/linux.tar.gz
Nov 29 17:44:34 ***.org Ombi[3839]: fail: Hangfire.AutomaticRetryAttribute[0]
Nov 29 17:44:34 ***.org Ombi[3839]:       Failed to process the job '240': an exception occurred.
Nov 29 17:44:34 ***.org Ombi[3839]: System.ComponentModel.Win32Exception (0x80004005): Permission denied
Nov 29 17:44:34 ***.org Ombi[3839]:    at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Int32& lpChildPid,
Nov 29 17:44:34 ***.org Ombi[3839]:    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
Nov 29 17:44:34 ***.org Ombi[3839]:    at System.Diagnostics.Process.Start()
Nov 29 17:44:34 ***.org Ombi[3839]:    at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 219

```

#### Problem Description:

Automatic update does not work (never worked for me)

**Comment by Flaxee** [comment]
I believe the built-in auto updater is not working at the moment?
You can use this instead: https://github.com/Unimatrix0/update_ombi

**Comment by PotatoQuality** [comment]
https://github.com/tidusjar/Ombi/issues/1460
