### ISSUE TITLE
Sonarr Sync doesn't finish

### ISSUE THREAD

**Issue by iVirus** [tidusjar/Ombi#1759]
#### Ombi build Version:

3.0.2410

#### Update Branch:

DotNetCore

#### Media Sever:

Plex

#### Media Server Version:

1.9.7.4460

#### Operating System:

Ubuntu 16.04 (Docker)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

fail: Ombi.Schedule.Jobs.Sonarr.SonarrSync[2006]
      Exception when trying to cache Sonarr
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Api.<Request>d__8`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Sonarr.SonarrApi.<GetEpisodes>d__10.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Sonarr\SonarrApi.cs:line 123
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Schedule.Jobs.Sonarr.SonarrSync.<Start>d__6.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Sonarr\SonarrSync.cs:line 61

```

#### Problem Description:

Ombi doesn't finish syncing with Sonarr. Logs state "A task was canceled."
Hangfire indicates the job finished successfully but the logs say different.

![image](https://user-images.githubusercontent.com/946926/33416806-a9a0285a-d55b-11e7-9f92-c83a89ef4249.png)

#### Reproduction Steps:

Clean install of Ombi.
No settings changed other than for Sonarr.
"Get Quality Profiles" succeeds.
"Get Root Folders" succeeds. 
"Test Connectivity" succeeds.

I have a sufficiently large collection of media. Maybe the task is timing out?

![image](https://user-images.githubusercontent.com/946926/33416897-29978486-d55c-11e7-9f15-d7f3433c08e7.png)

**Comment by tidusjar** [comment]
Does this happen every time?

**Comment by iVirus** [comment]
Yes, as far as I can tell. I have yet to see a successful sync on this fresh install and everything I search for shows up as “Not Requested.” 

I should note that this has succeeded before. Ombi had been working flawlessly for a few weeks. However, I’m not sure if it stopped working because I added a decent amount of media (and tipped over a timeout/breaking point) or if it’s due to an Ombi upgrade. I doubt this is due to a new bug.

**Comment by iVirus** [comment]
Just upgraded to the latest version and it doesn’t seem to be an issue anymore. I’ll keep an eye out.

**Comment by cbarratt** [comment]
How did you get the above job view? I need to try track down/debug my plex db sync / cache

**Comment by iVirus** [comment]
I believe the problem is with Sonarr, the container, or NAS it's running on.

I threw together a quick script to see how long it took to pull the list of episodes for each series. It got about 1/5 down the list (based on the seriesId and number of series I have, assuming contiguous IDs) and stopped (timed out after about 2 minutes with no output). I investigated that specific series and found no problems so I ran the script again. It stopped at a different point. Odd. I ran it once more and it again stopped at a different point. I restarted my Sonarr container and immediately triggered a sync in Ombi - success.

This is the script for anyone interested:
```
#!/bin/bash
sonarrHost=localhost
sonarrPort=8989
apiKey=e7205api15224sonarr37633keye106d

for seriesId in $(curl -s "http://${sonarrHost}:${sonarrPort}/api/series?apikey=${apiKey}" | jq -r '.[].id'); do
  echo "-- $seriesId --"
  curl -w '%{time_total}s\n' -o /dev/null -s "http://${sonarrHost}:${sonarrPort}/api/episode?seriesId=${seriesId}&apikey=${apiKey}"
done
```
