### ISSUE TITLE
Ombi unable to connect to plex (or anything else)

### ISSUE THREAD

**Issue by chase211** [tidusjar/Ombi#1781]
#### Ombi build Version:

V3.0.2440

#### Update Branch:

dotnetcore

#### Media Sever:

Plex

#### Media Server Version:

n/a

#### Operating System:

ubuntu 16.04

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2017-12-05 15:12:50.543 -06:00 [Error] Could not test Plex
System.TypeInitializationException: The type initializer for 'System.Net.Http.CurlHandler' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Http' threw an exception. ---> System.TypeInitializationEx$
 (Exception from HRESULT: 0x8007007E)
   at Interop.Http.GetSslVersionDescription()
   at Interop.HttpInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.Http..cctor()
   --- End of inner exception stack trace ---
   at Interop.Http.GetSupportedFeatures()
   at System.Net.Http.CurlHandler..cctor()
   --- End of inner exception stack trace ---
   at System.Net.Http.CurlHandler..ctor()
   at System.Net.Http.HttpClientHandler..ctor()
   at Ombi.Api.Api.<GetHandler>d__6.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Api.<Request>d__8`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Plex.PlexApi.<GetStatus>d__9.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<Plex>d__55.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 235

```

#### Problem Description:

I can't connect to plex (or couchpotato or sonarr for that matter). This is a fresh install (first time using ombi) so I'm not sure if this is just user error or if something is being blocked on my end.

No proxy/VPN involved

#### Reproduction Steps:

1. Try to test connection with plex or any other service after verifying info is correct. 
2. recieve error

**Comment by tidusjar** [comment]
Please read common issues on the wiki.
