### ISSUE TITLE
Many Pages Not Working When Going Through Reverse Proxy

### ISSUE THREAD

**Issue by Twiggy159** [tidusjar/Ombi#1809]
#### Ombi build Version:

V 3.0.2503 - DotNetCore

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

1.10.1.4602

#### Operating System:

unRAID 6.3.5 / ombi-preview Docker

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
2017-12-21 12:28:43.123 -06:00 [Information] Start installing Hangfire SQL objects...
2017-12-21 12:28:43.537 -06:00 [Information] Hangfire SQL objects installed.
2017-12-21 12:28:43.596 -06:00 [Information] Starting Hangfire Server
2017-12-21 12:28:43.602 -06:00 [Information] Using job storage: 'SQLite Server: /config/Schedules.db'
2017-12-21 12:28:43.602 -06:00 [Information] Using the following options for Hangfire Server:
2017-12-21 12:28:43.603 -06:00 [Information]     Worker count: 1
2017-12-21 12:28:43.603 -06:00 [Information]     Listening queues: 'default'
2017-12-21 12:28:43.603 -06:00 [Information]     Shutdown timeout: 1.00:00:00
2017-12-21 12:28:43.603 -06:00 [Information]     Schedule polling interval: 00:00:15
2017-12-21 12:29:36.346 -06:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized
2017-12-21 12:29:58.672 -06:00 [Information] Created User "admin"
2017-12-21 12:29:58.913 -06:00 [Information] Created the roles
2017-12-21 12:29:59.156 -06:00 [Information] Added the Admin role
2017-12-21 12:31:52.685 -06:00 [Information] Start installing Hangfire SQL objects...
2017-12-21 12:31:52.750 -06:00 [Information] Hangfire SQL objects installed.
2017-12-21 12:31:52.783 -06:00 [Information] Starting Hangfire Server
2017-12-21 12:31:52.787 -06:00 [Information] Using job storage: 'SQLite Server: /config/Schedules.db'
2017-12-21 12:31:52.787 -06:00 [Information] Using the following options for Hangfire Server:
2017-12-21 12:31:52.787 -06:00 [Information]     Worker count: 1
2017-12-21 12:31:52.787 -06:00 [Information]     Listening queues: 'default'
2017-12-21 12:31:52.787 -06:00 [Information]     Shutdown timeout: 1.00:00:00
2017-12-21 12:31:52.787 -06:00 [Information]     Schedule polling interval: 00:00:15
2017-12-21 12:38:52.434 -06:00 [Information] Hangfire Server stopped.
2017-12-21 12:39:09.850 -06:00 [Information] Start installing Hangfire SQL objects...
2017-12-21 12:39:09.972 -06:00 [Information] Hangfire SQL objects installed.
2017-12-21 12:39:10.030 -06:00 [Information] Starting Hangfire Server
2017-12-21 12:39:10.037 -06:00 [Information] Using job storage: 'SQLite Server: /config/Schedules.db'
2017-12-21 12:39:10.037 -06:00 [Information] Using the following options for Hangfire Server:
2017-12-21 12:39:10.037 -06:00 [Information]     Worker count: 1
2017-12-21 12:39:10.037 -06:00 [Information]     Listening queues: 'default'
2017-12-21 12:39:10.037 -06:00 [Information]     Shutdown timeout: 1.00:00:00
2017-12-21 12:39:10.038 -06:00 [Information]     Schedule polling interval: 00:00:15
2017-12-21 12:41:56.084 -06:00 [Error] Could not test Plex
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Couldn't connect to server
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Api.<Request>d__8`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Plex.PlexApi.<GetStatus>d__9.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<Plex>d__55.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 235
2017-12-21 12:44:54.822 -06:00 [Warning] Exception when testing Email Notifications
System.InvalidOperationException: The remote certificate is invalid according to the validation procedure.
   at Ombi.Notifications.GenericEmailProvider.<SendAdHoc>d__5.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<Email>d__54.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 214
2017-12-21 12:48:51.101 -06:00 [Information] Hangfire Server stopped.
2017-12-21 12:49:08.854 -06:00 [Information] Start installing Hangfire SQL objects...
2017-12-21 12:49:08.992 -06:00 [Information] Hangfire SQL objects installed.
2017-12-21 12:49:09.052 -06:00 [Information] Starting Hangfire Server
2017-12-21 12:49:09.058 -06:00 [Information] Using job storage: 'SQLite Server: /config/Schedules.db'
2017-12-21 12:49:09.058 -06:00 [Information] Using the following options for Hangfire Server:
2017-12-21 12:49:09.058 -06:00 [Information]     Worker count: 1
2017-12-21 12:49:09.059 -06:00 [Information]     Listening queues: 'default'
2017-12-21 12:49:09.059 -06:00 [Information]     Shutdown timeout: 1.00:00:00
2017-12-21 12:49:09.059 -06:00 [Information]     Schedule polling interval: 00:00:15
2017-12-21 12:55:12.024 -06:00 [Error] StatusCode: 429, Reason: 
2017-12-21 12:55:12.037 -06:00 [Error] StatusCode: 429, Reason: 
2017-12-21 12:56:36.931 -06:00 [Information] Start installing Hangfire SQL objects...
2017-12-21 12:56:37.052 -06:00 [Information] Hangfire SQL objects installed.
2017-12-21 12:56:37.111 -06:00 [Information] Starting Hangfire Server
2017-12-21 12:56:37.117 -06:00 [Information] Using job storage: 'SQLite Server: /config/Schedules.db'
2017-12-21 12:56:37.117 -06:00 [Information] Using the following options for Hangfire Server:
2017-12-21 12:56:37.117 -06:00 [Information]     Worker count: 1
2017-12-21 12:56:37.118 -06:00 [Information]     Listening queues: 'default'
2017-12-21 12:56:37.118 -06:00 [Information]     Shutdown timeout: 1.00:00:00
2017-12-21 12:56:37.118 -06:00 [Information]     Schedule polling interval: 00:00:15

```

#### Problem Description:

When accessing the WebUI from [ServerIP]:[Port] I can access the WebUI and its subpages with no issue. When going through my reverse proxy of [domainname]/request I can still hit it but after logging in I cannot get any subpages to load with information or search for movies or shows. The pages load but are just blank. I have the /request Base URL added in the settings.

#### Reproduction Steps:

Connect to the Ombi site via domain name instead of direct ip:port.

**Comment by Neaox** [comment]
I'm using a reverse proxy, it's working for me. Could you provide your server config/proxy config?

**Comment by Twiggy159** [comment]
Using letsencrypt with nginx:

```
# listening on port 80 disabled by default, remove the "#" signs to enable
# redirect all traffic to https
server {
	listen 80;
	server_name _;
	return 301 https://$host$request_uri;
}

# main server block
server {
	listen 443 ssl default_server;

	root /config/www/public_html;
	index index.html index.htm index.php;

	server_name _;

	ssl_certificate /config/keys/letsencrypt/fullchain.pem;
	ssl_certificate_key /config/keys/letsencrypt/privkey.pem;
	ssl_dhparam /config/nginx/dhparams.pem;
	ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';
	ssl_prefer_server_ciphers on;

	client_max_body_size 0;

	location / {
		try_files $uri $uri/ /index.html /index.php?$args =404;
	}

	location ~ \.php$ {
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		# With php7-cgi alone:
		fastcgi_pass 127.0.0.1:9000;
		# With php7-fpm:
		#fastcgi_pass unix:/var/run/php7-fpm.sock;
		fastcgi_index index.php;
		include /etc/nginx/fastcgi_params;
	}
	location /request {
		proxy_pass http://IP:PORT/request;
		include /config/nginx/proxy-control.conf;
	}
}

```
IP and PORT in /request are filled out to my server's IP and the appropriate port.

In proxy-control.conf
```
proxy_connect_timeout   59s;
proxy_send_timeout      600;
proxy_read_timeout      600;
proxy_buffer_size       64k;
proxy_buffers           16 32k;
proxy_pass_header       Set-Cookie;
proxy_hide_header       Vary;

proxy_busy_buffers_size         64k;
proxy_temp_file_write_size      64k;

proxy_set_header        Accept-Encoding         '';
proxy_ignore_headers    Cache-Control           Expires;
proxy_set_header        Referer                 $http_referer;
proxy_set_header        Host                    $host;
proxy_set_header        Cookie                  $http_cookie;
proxy_set_header        X-Real-IP               $remote_addr;
proxy_set_header        X-Forwarded-Host        $host;
proxy_set_header        X-Forwarded-Server      $host;
proxy_set_header        X-Forwarded-For         $proxy_add_x_forwarded_for;

proxy_set_header        X-Forwarded-Port        '443';
proxy_set_header        X-Forwarded-Ssl         on;
proxy_set_header        X-Forwarded-Proto       https;
proxy_set_header        Authorization           '';

proxy_redirect          default;
port_in_redirect        off;
```

Like I said earlier, I have no issue hitting the website or even loading the pages such as User Management or Settings, but they load blank unless I access it via IP:Port directly.

**Comment by Neaox** [comment]
I was having issues where none of the resources would load (scripts, Styles, images), if you open a console are you getting 404s for your resources?

**Comment by Neaox** [comment]
If you do see 404s for the resources, check your nginx error/access logs to see what paths are actually being accessed.

**Comment by Twiggy159** [comment]
Not seeing any issues with 404s for the resources. I am seeing a bunch of 401 errors when hitting it for various things however.

**Comment by tidusjar** [comment]
Did you restart Ombi after changing the base url?

Also from your log: `System.Net.Http.CurlException: Couldn't connect to server`

Looks like we cannot connect to Plex, please check your settings

**Comment by Twiggy159** [comment]
I have restarted Ombi after making the change. Still no change in behavior.

Interesting that that is showing. The configuration looks good and verifies it can connect just fine. It was able to scan the libraries as well and is successfully showing when a movie or TV show is already on my Plex.

**Comment by tidusjar** [comment]
Please post a screenshot of your console
also try and logout and back in

**Comment by Twiggy159** [comment]
Sorry when you mean the console, would the docker SSH terminal work? I'm running this as a docker on unRAID so I don't have any kind of console that comes up. I can also pull up logs as it runs as well, but they don't seem very useful.

This is a copy/paste from that log as the docker restarts:

```

-------------------------------------
_ _ _
| |___| (_) ___
| / __| | |/ _ \
| \__ \ | | (_) |
|_|___/ |_|\___/
|_|

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donations/
-------------------------------------
GID/UID
-------------------------------------

User uid: 911
User gid: 911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
[cont-init.d] 30-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Hello, welcome to Ombi
Valid options are:
Ombi 3.0.2503-DotNetCore
Copyright (C) 2017 Ombi

-h, --host (Default: http://*:5000) Set to a semicolon-separated (;)
list of URL prefixes to which the server should respond. For
example, http://localhost:123. Use "*" to indicate that the
server should listen for requests on any IP address or
hostname using the specified port and protocol (for example,
http://*:5000). The protocol (http:// or https://) must be
included with each URL. Supported formats vary between
servers.

-s, --storage Storage path, where we save the logs and database

--help Display this help screen.

--version Display version information.



We are running on

i
[40m[32minfo[39m[22m[49m: Hangfire.SQLite.SQLiteStorage[0]
Start installing Hangfire SQL objects...
[40m[32minfo[39m[22m[49m: Hangfire.SQLite.SQLiteStorage[0]
Hangfire SQL objects installed.
[40m[32minfo[39m[22m[49m: Hangfire.BackgroundJobServer[0]
Starting Hangfire Server
[40m[32minfo[39m[22m[49m: Hangfire.BackgroundJobServer[0]
Using job storage: 'SQLite Server: /config/Schedules.db'
[40m[32minfo[39m[22m[49m: Hangfire.BackgroundJobServer[0]
Using the following options for Hangfire Server:
[40m[32minfo[39m[22m[49m: Hangfire.BackgroundJobServer[0]
Worker count: 1
[40m[32minfo[39m[22m[49m: Hangfire.BackgroundJobServer[0]
Listening queues: 'default'
[40m[32minfo[39m[22m[49m: Hangfire.BackgroundJobServer[0]
Shutdown timeout: 1.00:00:00
[40m[32minfo[39m[22m[49m: Hangfire.BackgroundJobServer[0]
Schedule polling interval: 00:00:15
[40m[32minfo[39m[22m[49m: Hangfire.SQLite.SQLiteStorage[0]
Start installing Hangfire SQL objects...
[40m[32minfo[39m[22m[49m: Hangfire.SQLite.SQLiteStorage[0]
Hangfire SQL objects installed.
[40m[32minfo[39m[22m[49m: Hangfire.BackgroundJobServer[0]
Starting Hangfire Server
[40m[32minfo[39m[22m[49m: Hangfire.BackgroundJobServer[0]
Using job storage: 'SQLite Server: /config/Schedules.db'
[40m[32minfo[39m[22m[49m: Hangfire.BackgroundJobServer[0]
Using the following options for Hangfire Server:
[40m[32minfo[39m[22m[49m: Hangfire.BackgroundJobServer[0]
Worker count: 1
[40m[32minfo[39m[22m[49m: Hangfire.BackgroundJobServer[0]
Listening queues: 'default'
[40m[32minfo[39m[22m[49m: Hangfire.BackgroundJobServer[0]
Shutdown timeout: 1.00:00:00
[40m[32minfo[39m[22m[49m: Hangfire.BackgroundJobServer[0]
Schedule polling interval: 00:00:15
Hosting environment: Production
Content root path: /app/ombi
Now listening on: http://0.0.0.0:3579
Application started. Press Ctrl+C to shut down.
```

I've logged out and back in but still no change.

**Comment by tidusjar** [comment]
Sorry I mean the browser's console

**Comment by Twiggy159** [comment]
Ah my apologies. Looking there it definitely looks like I'm getting a 401 error for some reason.

![mstsc_2017-12-21_15-32-28](https://user-images.githubusercontent.com/21014339/34275750-43acadb0-e664-11e7-967d-51c322074e97.png)

**Comment by goldenpipes** [comment]
this isnt that LANG issue like on the LXC containers right?

**Comment by Twiggy159** [comment]
I'm not sure I'm familiar with that issue.

**Comment by goldenpipes** [comment]
https://github.com/tidusjar/Ombi/wiki/Installation#linux-systems

**Comment by Twiggy159** [comment]
This is what the locale command reports:

```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE=C
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
Does LC_ALL have to be assigned for Ombi or does it pull from one of the other variables?

**Comment by tidusjar** [comment]
Is this still an issue?

**Comment by dejected1** [comment]
im having the same issue after upgrading from 3.2509 to 3.2538. Everyting was working great through reverse proxy then after upgrade it loads blank. if i specify the /landingpage at the end of my proxy address i get the landing page and can log in but all frames except the header won't load. I found the note in the help for reverse proxy and ammend my ngnix to look like this: 

#ombiv3
		location /ombi/ {
		#auth_request /auth-user;
       	 	proxy_pass http://192.168.2.87:5000;
			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection keep-alive;
			proxy_set_header Host $host;
			proxy_cache_bypass $http_upgrade;
		}
			if ($http_referer ~* /ombi/) {
				rewrite ^/dist/([0-9\d*]).js /ombi/dist/$1.js last;
		}

The only change this made was i get a "loading..." when going to my reverse proxy address instead of a 404.

**Comment by tidusjar** [comment]
what's in the console?

**Comment by dejected1** [comment]
Failed to load resource: the server responded with a status of 404 (Not Found)
vendor.css Failed to load resource: the server responded with a status of 404 (Not Found)
vendor.js Failed to load resource: the server responded with a status of 404 (Not Found)
main.js Failed to load resource: the server responded with a status of 404 (Not Found)
6landingpage:1 Error in event handler for (unknown): TypeError: Cannot read property 'state' of undefined
    at chrome-extension://enmgcoifcfalfohmfibbhiaojhafpehm/content.js:10:24
loading.css Failed to load resource: the server responded with a status of 404 (Not Found)
vendor.css Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by dejected1** [comment]
i also got: 
ombi v3 (plex requests) has responded, proceeding with load
organizr.asuscomm.com/:64 GET http://organizr.asuscomm.com:9111/loading.css?v=k33zb3c0-ToEQSx13OJIBKNSzNyG6g4V29uA0YpYiV0 net::ERR_ABORTED
organizr.asuscomm.com/:66 GET http://organizr.asuscomm.com:9111/dist/vendor.js?v=zO-p-yXBv7xvaFHp6pPIgDdVgqVz3JWtL39OMPBXr48 net::ERR_ABORTED
organizr.asuscomm.com/:65 GET http://organizr.asuscomm.com:9111/dist/vendor.css?v=2GCDoRZwuCMsB5hCBgLZvUpd336ZXIhrNwnyCorabRo net::ERR_ABORTED
organizr.asuscomm.com/:67 GET http://organizr.asuscomm.com:9111/dist/main.js?v=fNMIEZdGQ9_J5tAP0M8eMLnJg9A5cQraxWWcGlTQmRE 404 (Not Found)

**Comment by tidusjar** [comment]
Did you restart ombi after settings the base url inside the ombi settings?

**Comment by dejected1** [comment]
i did. i had a alternate base url before upgrading and it was working fine. Once i started having problems i changed it back to default to match the settings i found for ngnix. no change. i did restart the ombi several times thou.

**Comment by tidusjar** [comment]
If you are use a RP like e.g. tld.com/request then your base url in ombi needs to be `/request`

**Comment by dejected1** [comment]
thats how i have it. i go to the address. i get the loading... like its going to work and then nothing. if i manually add /ombi/landingpage to end of my proxy address it pop up and i can log in. but after loging in it just load the ombi header and nothing else. clicking on any of the header buttons doesnt chagne the main frame, it just stays  blank.

**Comment by tidusjar** [comment]
must be something wrong with your RP settings. Please open a new issue.

**Comment by dejected1** [comment]
i didn't change proxy settings at all between updates. it worked on 3.2509 then stopped working on 3.2538. I can open another inc if you like but i dont think thats the issue. Plus more than just me was having the issue.

**Comment by dejected1** [comment]
maybe this well help?

![how to](https://user-images.githubusercontent.com/26720061/34464759-58172d9e-ee4c-11e7-9b27-6b42348c8357.gif)

**Comment by dejected1** [comment]
i restored to the older version of omib v3 and my reverse proxy started working just fine. i guess ill just wait to update until release.

**Comment by tidusjar** [comment]
Please look at the reverse proxy wiki page. There is a new bit that you
need.to add to your config file
