### ISSUE TITLE
Requested movies not added to radarr (similar log error for sonarr)

### ISSUE THREAD

**Issue by orangemooncreative** [tidusjar/Ombi#1812]
#### Ombi build Version:

3.0.2509

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

MacOS High Sierra 10.13.2

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page) - Terminal Log:

```

Error When adding movie to Radarr
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Ombi.Api.Radarr.Models.RadarrAddMovieResponse' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Radarr.RadarrApi.<AddMovie>d__11.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Radarr\RadarrApi.cs:line 95

```

#### Problem Description:

While testing out the request functionality with my admin account, I realized that none of my requests are being added to Radarr or Sonarr although both are connected successfully. The above error message is what is being thrown in terminal.

**Comment by tidusjar** [comment]
Are you using a base URL in radarr?

**Comment by orangemooncreative** [comment]
@tidusjar that was the issue. had a base url listed in radarr even though i don't use it. removed and able to add movies perfectly. thanks! 

i also removed it from sonarr but i'm still having an issue with adding tv shows to sonarr from ombi. i tested using an upcoming show. the request was added in ombi but was not sent over to sonarr. i checked sonarr to see if i could manually add the show in case for some reason it was not in the database. it can be manually added fine. 

the terminal error is below. any thoughts?

```
fail: Ombi.Api.Api[1000]
      StatusCode: NotFound, Reason: Not Found
fail: Ombi.Api.Api[1000]
      StatusCode: NotFound, Reason: Not Found
fail: Ombi.Api.Api[1000]
      StatusCode: NotFound, Reason: Not Found
fail: Ombi.Api.Api[1000]
      StatusCode: NotFound, Reason: Not Found
fail: Ombi.Api.Api[1000]
      StatusCode: NotFound, Reason: Not Found
fail: Ombi.Api.Api[1000]
      StatusCode: NotFound, Reason: Not Found
fail: Ombi.Api.Api[1000]
      StatusCode: NotFound, Reason: Not Found
fail: Ombi.Api.Api[1000]
      StatusCode: NotFound, Reason: Not Found
fail: Ombi.Api.Api[1000]
      StatusCode: NotFound, Reason: Not Found
fail: Ombi.Api.Api[1000]
      StatusCode: BadRequest, Reason: Bad Request
fail: Ombi.Core.Senders.TvSender[5001]
      Exception thrown when attempting to send series over to Sonarr
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Ombi.Api.Sonarr.SonarrApi.<GetSeriesById>d__7.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Sonarr\SonarrApi.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Core.Senders.TvSender.<SendToSonarr>d__24.MoveNext() in C:\projects\requestplex\src\Ombi.Core\Senders\TvSender.cs:line 176
fail: Ombi.Api.Api[1000]
      StatusCode: BadGateway, Reason: Bad Gateway
fail: Ombi.Api.Api[1000]
      StatusCode: BadGateway, Reason: Bad Gateway

```

**Comment by goldenpipes** [comment]
try re-entering your API code from sonarr into ombi and hitting save then getting the rootfolders and quality profiles. then try again.  I had this issue before.  I actually had to generate a new API key in Sonarr first.

**Comment by orangemooncreative** [comment]
@goldenpipes thanks! i will try this.
