### ISSUE TITLE
Ombi stops at "Loading" screen. Browser console screenshot included.

### ISSUE THREAD

**Issue by kars85** [tidusjar/Ombi#1827]
#### Ombi build Version:

V 3.0.2534

#### Update Branch:

DotNetCore

#### Media Sever:

Plex

#### Media Server Version:

1.11.0.4633

#### Operating System:

Ubuntu Server 16.04 

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2017-12-29 07:44:38.335 -06:00 [Information]     Schedule polling interval: 00:00:15
2017-12-29 08:00:56.412 -06:00 [Warning] Exception when testing Email Notifications
System.InvalidOperationException: Unable to transfer data on the transport connection: Connection reset by peer.
   at Ombi.Notifications.GenericEmailProvider.<SendAdHoc>d__5.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<Email>d__54.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 214
2017-12-29 08:10:50.473 -06:00 [Information] Hangfire Server stopped.
2017-12-29 08:11:19.616 -06:00 [Information] Start installing Hangfire SQL objects...
2017-12-29 08:11:19.788 -06:00 [Information] Hangfire SQL objects installed.
2017-12-29 08:11:19.856 -06:00 [Information] Starting Hangfire Server
2017-12-29 08:11:19.867 -06:00 [Information] Using job storage: 'SQLite Server: Schedules.db'
2017-12-29 08:11:19.868 -06:00 [Information] Using the following options for Hangfire Server:
2017-12-29 08:11:19.868 -06:00 [Information]     Worker count: 1
2017-12-29 08:11:19.869 -06:00 [Information]     Listening queues: 'default'
2017-12-29 08:11:19.869 -06:00 [Information]     Shutdown timeout: 1.00:00:00
2017-12-29 08:11:19.869 -06:00 [Information]     Schedule polling interval: 00:00:15
2017-12-29 08:18:25.859 -06:00 [Information] Hangfire Server stopped.
2017-12-29 08:35:04.873 -06:00 [Information] Start installing Hangfire SQL objects...
2017-12-29 08:35:04.924 -06:00 [Information] Hangfire SQL objects installed.
2017-12-29 08:35:04.946 -06:00 [Information] Starting Hangfire Server
2017-12-29 08:35:04.949 -06:00 [Information] Using job storage: 'SQLite Server: Schedules.db'
2017-12-29 08:35:04.949 -06:00 [Information] Using the following options for Hangfire Server:
2017-12-29 08:35:04.949 -06:00 [Information]     Worker count: 1
2017-12-29 08:35:04.950 -06:00 [Information]     Listening queues: 'default'
2017-12-29 08:35:04.950 -06:00 [Information]     Shutdown timeout: 1.00:00:00
2017-12-29 08:35:04.950 -06:00 [Information]     Schedule polling interval: 00:00:15


```

#### Problem Description:
When browsing Ombi through my nginx reverse proxy outside my network, all that happens is the "Loading" page appears, then stops. Nothing happens after that. I've attached the browser console screenshot of the error.

![screenshot](https://user-images.githubusercontent.com/6616548/34442193-138d355a-ec86-11e7-9812-870c8b20fb28.jpg)

#### Reproduction Steps:
Try to load Ombi through a reverse proxy.

**Comment by tidusjar** [comment]
See #1822
