### ISSUE TITLE
Ombi v3 not working through nginx proxy

### ISSUE THREAD

**Issue by josharmour** [tidusjar/Ombi#1829]
#### Ombi build Version:

3.0.2534

#### Update Branch:

It just says latest

#### Media Sever:

Plex

#### Media Server Version:

Not the problem

#### Operating System:

Ubuntu LTS

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page): Nothing worth noting, couldn't test couch a few times:

```
zues@virtualbox:/opt/Ombi/Logs$ cat log-20171229.txt
2017-12-29 13:23:23.392 -08:00 [Information] Start installing Hangfire SQL objects...
2017-12-29 13:23:23.523 -08:00 [Information] Hangfire SQL objects installed.
2017-12-29 13:23:23.546 -08:00 [Information] Starting Hangfire Server
2017-12-29 13:23:23.549 -08:00 [Information] Using job storage: 'SQLite Server: Schedules.db'
2017-12-29 13:23:23.550 -08:00 [Information] Using the following options for Hangfire Server:
2017-12-29 13:23:23.550 -08:00 [Information]     Worker count: 1
2017-12-29 13:23:23.551 -08:00 [Information]     Listening queues: 'default'
2017-12-29 13:23:23.552 -08:00 [Information]     Shutdown timeout: 1.00:00:00
2017-12-29 13:23:23.552 -08:00 [Information]     Schedule polling interval: 00:00:15
2017-12-29 13:37:54.783 -08:00 [Information] Hangfire Server stopped.
2017-12-29 13:38:20.412 -08:00 [Information] Start installing Hangfire SQL objects...
2017-12-29 13:38:20.467 -08:00 [Information] Hangfire SQL objects installed.
2017-12-29 13:38:20.490 -08:00 [Information] Starting Hangfire Server
2017-12-29 13:38:20.494 -08:00 [Information] Using job storage: 'SQLite Server: Schedules.db'
2017-12-29 13:38:20.495 -08:00 [Information] Using the following options for Hangfire Server:
2017-12-29 13:38:20.495 -08:00 [Information]     Worker count: 1
2017-12-29 13:38:20.496 -08:00 [Information]     Listening queues: 'default'
2017-12-29 13:38:20.496 -08:00 [Information]     Shutdown timeout: 1.00:00:00
2017-12-29 13:38:20.496 -08:00 [Information]     Schedule polling interval: 00:00:15
2017-12-29 13:42:26.420 -08:00 [Information] Created User "josharmour"
2017-12-29 13:42:26.535 -08:00 [Information] Created the roles
2017-12-29 13:42:26.640 -08:00 [Information] Added the Admin role
2017-12-29 13:53:40.342 -08:00 [Information] Hangfire Server stopped.
2017-12-29 13:53:43.342 -08:00 [Information] Start installing Hangfire SQL objects...
2017-12-29 13:53:43.392 -08:00 [Information] Hangfire SQL objects installed.
2017-12-29 13:53:43.414 -08:00 [Information] Starting Hangfire Server
2017-12-29 13:53:43.418 -08:00 [Information] Using job storage: 'SQLite Server: Schedules.db'
2017-12-29 13:53:43.419 -08:00 [Information] Using the following options for Hangfire Server:
2017-12-29 13:53:43.419 -08:00 [Information]     Worker count: 1
2017-12-29 13:53:43.419 -08:00 [Information]     Listening queues: 'default'
2017-12-29 13:53:43.420 -08:00 [Information]     Shutdown timeout: 1.00:00:00
2017-12-29 13:53:43.420 -08:00 [Information]     Schedule polling interval: 00:00:15
2017-12-29 14:01:18.358 -08:00 [Information] Hangfire Server stopped.
2017-12-29 14:01:21.474 -08:00 [Information] Start installing Hangfire SQL objects...
2017-12-29 14:01:21.526 -08:00 [Information] Hangfire SQL objects installed.
2017-12-29 14:01:21.551 -08:00 [Information] Starting Hangfire Server
2017-12-29 14:01:21.554 -08:00 [Information] Using job storage: 'SQLite Server: Schedules.db'
2017-12-29 14:01:21.554 -08:00 [Information] Using the following options for Hangfire Server:
2017-12-29 14:01:21.555 -08:00 [Information]     Worker count: 1
2017-12-29 14:01:21.555 -08:00 [Information]     Listening queues: 'default'
2017-12-29 14:01:21.555 -08:00 [Information]     Shutdown timeout: 1.00:00:00
2017-12-29 14:01:21.555 -08:00 [Information]     Schedule polling interval: 00:00:15
2017-12-29 14:18:45.584 -08:00 [Information] Hangfire Server stopped.
2017-12-29 14:18:48.621 -08:00 [Information] Start installing Hangfire SQL objects...
2017-12-29 14:18:48.670 -08:00 [Information] Hangfire SQL objects installed.
2017-12-29 14:18:48.691 -08:00 [Information] Starting Hangfire Server
2017-12-29 14:18:48.694 -08:00 [Information] Using job storage: 'SQLite Server: Schedules.db'
2017-12-29 14:18:48.695 -08:00 [Information] Using the following options for Hangfire Server:
2017-12-29 14:18:48.695 -08:00 [Information]     Worker count: 1
2017-12-29 14:18:48.695 -08:00 [Information]     Listening queues: 'default'
2017-12-29 14:18:48.696 -08:00 [Information]     Shutdown timeout: 1.00:00:00
2017-12-29 14:18:48.696 -08:00 [Information]     Schedule polling interval: 00:00:15
2017-12-29 14:37:10.161 -08:00 [Error] Could not test CP
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.<Request>d__8`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 80
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.CouchPotato.CouchPotatoApi.<Status>d__4.MoveNext() in C:\projects\requestplex\src\Ombi.Api.CouchPotato\CouchPotatoApi.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<CouchPotato>d__59.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 319
2017-12-29 14:37:15.346 -08:00 [Error] Could not test CP
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.<Request>d__8`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 80
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.CouchPotato.CouchPotatoApi.<Status>d__4.MoveNext() in C:\projects\requestplex\src\Ombi.Api.CouchPotato\CouchPotatoApi.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<CouchPotato>d__59.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 319
2017-12-29 14:37:17.801 -08:00 [Error] Could not test CP
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.<Request>d__8`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 80
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.CouchPotato.CouchPotatoApi.<Status>d__4.MoveNext() in C:\projects\requestplex\src\Ombi.Api.CouchPotato\CouchPotatoApi.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<CouchPotato>d__59.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 319
2017-12-29 14:39:00.527 -08:00 [Error] Could not test CP
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Api.<Request>d__8`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.CouchPotato.CouchPotatoApi.<Status>d__4.MoveNext() in C:\projects\requestplex\src\Ombi.Api.CouchPotato\CouchPotatoApi.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<CouchPotato>d__59.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 319
2017-12-29 14:39:02.963 -08:00 [Error] Could not test CP
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Api.<Request>d__8`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.CouchPotato.CouchPotatoApi.<Status>d__4.MoveNext() in C:\projects\requestplex\src\Ombi.Api.CouchPotato\CouchPotatoApi.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<CouchPotato>d__59.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 319
2017-12-29 14:39:07.472 -08:00 [Error] Could not test CP
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Api.<Request>d__8`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.CouchPotato.CouchPotatoApi.<Status>d__4.MoveNext() in C:\projects\requestplex\src\Ombi.Api.CouchPotato\CouchPotatoApi.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<CouchPotato>d__59.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 319
2017-12-29 14:39:36.373 -08:00 [Error] Could not test CP
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Api.<Request>d__8`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.CouchPotato.CouchPotatoApi.<Status>d__4.MoveNext() in C:\projects\requestplex\src\Ombi.Api.CouchPotato\CouchPotatoApi.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<CouchPotato>d__59.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 319
2017-12-29 14:39:55.139 -08:00 [Error] Could not test CP
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Api.<Request>d__8`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.CouchPotato.CouchPotatoApi.<Status>d__4.MoveNext() in C:\projects\requestplex\src\Ombi.Api.CouchPotato\CouchPotatoApi.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<CouchPotato>d__59.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 319
2017-12-29 14:40:40.542 -08:00 [Error] Could not test CP
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Api.<Request>d__8`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.CouchPotato.CouchPotatoApi.<Status>d__4.MoveNext() in C:\projects\requestplex\src\Ombi.Api.CouchPotato\CouchPotatoApi.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<CouchPotato>d__59.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 319
2017-12-29 15:11:41.060 -08:00 [Information] Hangfire Server stopped.
2017-12-29 15:13:43.910 -08:00 [Information] Start installing Hangfire SQL objects...
2017-12-29 15:13:44.056 -08:00 [Information] Hangfire SQL objects installed.
2017-12-29 15:13:44.113 -08:00 [Information] Starting Hangfire Server
2017-12-29 15:13:44.120 -08:00 [Information] Using job storage: 'SQLite Server: Schedules.db'
2017-12-29 15:13:44.121 -08:00 [Information] Using the following options for Hangfire Server:
2017-12-29 15:13:44.121 -08:00 [Information]     Worker count: 1
2017-12-29 15:13:44.122 -08:00 [Information]     Listening queues: 'default'
2017-12-29 15:13:44.122 -08:00 [Information]     Shutdown timeout: 1.00:00:00
2017-12-29 15:13:44.123 -08:00 [Information]     Schedule polling interval: 00:00:15


```

#### Problem Description:

I can access ombi directly via localip:5000/ombi (the base url I've set)
I can't access it via nginx either at DDNS/ombi or LOCALIP/ombi

I've setup the nginx config location of (I have some commented out but I've tested with them enabled as well.  The reason they are commented out is because they are in my proxy common section above also).

```
  location /ombi/ {
    if ($http_referer ~* /ombi/) {
      rewrite ^/dist/([0-9\d*]).js /ombi/dist/$1.js last;
    }
    proxy_pass http://127.0.0.1:5000;
#    proxy_set_header Host $host;
#    proxy_set_header X-Forwarded-Host $server_name;
#    proxy_set_header X-Real-IP $remote_addr;
#    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Ssl on; # This needs to be here for Ombi to work, even though it's in proxy.conf
#    proxy_set_header X-Forwarded-Proto $scheme;
#    proxy_read_timeout  90;
#    proxy_redirect http://127.0.0.1:5000 https://$host;
  }

```

I've had both strict redirect turned on for https (via lets encrypt) and allow http.  Note, this doesn't matter as much since I can hit the other sites that are proxied through it fine.  

I am intending to use muximux to iframe ombi and other services.

**Comment by josharmour** [comment]
I believe it may have to do with this 

from the nginx error logs

```

2017/12/29 16:23:33 [error] 1768#1768: *5301 open() "/var/www/dist/2.js" failed (2: No such file or directory), client: 192.168.86.1, server: DDNS, request: "GET /dist/2.js HTTP/2.0", host: "DDNS", referrer: "https://DDNS/ombi/"
2017/12/29 16:23:40 [error] 1768#1768: *5301 FastCGI sent in stderr: "PHP message: PHP Warning:  file_get_contents(): Filename cannot be empty in /var/www/muximux/muximux.php on line 1122" while reading response header from upstream, client: 192.168.86.1, server: DDNS, request: "GET /muximux/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.1-fpm.sock:", host: "DDNS"
2017/12/29 16:23:43 [error] 1768#1768: *5301 FastCGI sent in stderr: "PHP message: PHP Warning:  file_get_contents(): Filename cannot be empty in /var/www/muximux/muximux.php on line 1122" while reading response header from upstream, client: 192.168.86.1, server: DDNS, request: "POST /muximux/index.php HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.1-fpm.sock:", host: "DDNS", referrer: "https://DDNS/muximux/"
2017/12/29 16:23:44 [error] 1768#1768: *5301 open() "/var/www/dist/2.js" failed (2: No such file or directory), client: 192.168.86.1, server: DDNS, request: "GET /dist/2.js HTTP/2.0", host: "DDNS", referrer: "https://DDNS/ombi/"
2017/12/29 16:23:45 [error] 1768#1768: *5301 open() "/var/www/dist/2.js" failed (2: No such file or directory), client: 192.168.86.1, server: DDNS, request: "GET /dist/2.js HTTP/2.0", host: "DDNS", referrer: "https://DDNS/ombi/"
2017/12/29 16:23:55 [error] 1768#1768: *5301 open() "/var/www/dist/2.js" failed (2: No such file or directory), client: 192.168.86.1, server: DDNS, request: "GET /dist/2.js HTTP/2.0", host: "DDNS", referrer: "https://DDNS/ombi/"
2017/12/29 16:23:56 [error] 1768#1768: *5301 open() "/var/www/dist/2.js" failed (2: No such file or directory), client: 192.168.86.1, server: DDNS, request: "GET /dist/2.js HTTP/2.0", host: "DDNS", referrer: "https://DDNS/ombi/"
2017/12/29 16:24:03 [error] 1768#1768: *5301 open() "/var/www/dist/2.js" failed (2: No such file or directory), client: 192.168.86.1, server: DDNS, request: "GET /dist/2.js HTTP/2.0", host: "DDNS", referrer: "https://DDNS/ombi/"
zues@virtualbox:/opt/Ombi/Logs$

```

**Comment by josharmour** [comment]
I suspect its the code from this page: https://github.com/tidusjar/Ombi/wiki/Nginx-Reverse-Proxy-examples-(Linux)

It suggests a rewrite in the reverse config as such:

```
if ($http_referer ~* /ombi/) {
    rewrite ^/dist/([0-9\d*]).js /ombi/dist/$1.js last;
}
```

However it may not work with a base url?

**Comment by josharmour** [comment]
Answer is a slightly different variation of the nginx config:
```
# ombi v3
        location /ombi/ {
        proxy_pass http://127.0.0.1:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection keep-alive;
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
}
        if ($http_referer ~* /ombi/) {
                rewrite ^/dist/([0-9\d*]).js /ombi/dist/$1.js last;
        }

```

Note, I also had mistakenly put the rewrite function inside of the ombi location, when it actually needed to go after.
