### ISSUE TITLE
Apache Rewrite still not working, please see my code

### ISSUE THREAD

**Issue by infamouswb** [tidusjar/Ombi#1837]
#### Ombi build Version:

V: 3.0.2541
--

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

not needed

#### Operating System:

Ubuntu 16.04

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
Most Recent:
2018-01-01 01:00:17.111 -05:00 [Warning] Failed to process the job '7062': an exception occurred. Retry attempt 1 of 1 will be performed in 00:00:26.
System.ComponentModel.Win32Exception (0x80004005): Permission denied
   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 220
2018-01-01 01:00:53.801 -05:00 [Information] 1 scheduled job(s) enqueued.
2018-01-01 01:01:15.600 -05:00 [Error] Failed to process the job '7062': an exception occurred.
System.ComponentModel.Win32Exception (0x80004005): Permission denied
   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 220
2018-01-01 07:00:19.410 -05:00 [Warning] Failed to process the job '7111': an exception occurred. Retry attempt 1 of 1 will be performed in 00:00:37.
System.ComponentModel.Win32Exception (0x80004005): Permission denied
   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 220
2018-01-01 07:00:58.761 -05:00 [Information] 1 scheduled job(s) enqueued.
2018-01-01 07:01:17.461 -05:00 [Error] Failed to process the job '7111': an exception occurred.
System.ComponentModel.Win32Exception (0x80004005): Permission denied
   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 220
2018-01-01 13:00:25.460 -05:00 [Warning] Failed to process the job '7160': an exception occurred. Retry attempt 1 of 1 will be performed in 00:00:37.
System.ComponentModel.Win32Exception (0x80004005): Permission denied
   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 220
2018-01-01 13:01:02.683 -05:00 [Information] 1 scheduled job(s) enqueued.
2018-01-01 13:01:26.400 -05:00 [Error] Failed to process the job '7160': an exception occurred.
System.ComponentModel.Win32Exception (0x80004005): Permission denied
   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 220
2018-01-01 13:49:25.266 -05:00 [Information] Hangfire Server stopped.
2018-01-01 13:49:29.651 -05:00 [Information] Start installing Hangfire SQL objects...
2018-01-01 13:49:29.697 -05:00 [Information] Hangfire SQL objects installed.
2018-01-01 13:49:29.718 -05:00 [Information] Starting Hangfire Server
2018-01-01 13:49:29.721 -05:00 [Information] Using job storage: 'SQLite Server: Schedules.db'
2018-01-01 13:49:29.721 -05:00 [Information] Using the following options for Hangfire Server:
2018-01-01 13:49:29.721 -05:00 [Information]     Worker count: 1
2018-01-01 13:49:29.721 -05:00 [Information]     Listening queues: 'default'
2018-01-01 13:49:29.721 -05:00 [Information]     Shutdown timeout: 1.00:00:00
2018-01-01 13:49:29.721 -05:00 [Information]     Schedule polling interval: 00:00:15
2018-01-01 14:35:15.656 -05:00 [Information] Hangfire Server stopped.
2018-01-01 14:35:19.597 -05:00 [Information] Start installing Hangfire SQL objects...
2018-01-01 14:35:19.641 -05:00 [Information] Hangfire SQL objects installed.
2018-01-01 14:35:19.662 -05:00 [Information] Starting Hangfire Server
2018-01-01 14:35:19.665 -05:00 [Information] Using job storage: 'SQLite Server: Schedules.db'
2018-01-01 14:35:19.665 -05:00 [Information] Using the following options for Hangfire Server:
2018-01-01 14:35:19.665 -05:00 [Information]     Worker count: 1
2018-01-01 14:35:19.665 -05:00 [Information]     Listening queues: 'default'
2018-01-01 14:35:19.665 -05:00 [Information]     Shutdown timeout: 1.00:00:00
2018-01-01 14:35:19.665 -05:00 [Information]     Schedule polling interval: 00:00:15

```

#### Problem Description:

I tried using the rewrite noted here: https://github.com/tidusjar/Ombi/wiki/Nginx-Reverse-Proxy-examples-(Linux)

For the first part I have:

<Location /ombi>
Allow from 0.0.0.0
ProxyPass http://127.0.0.1:5000/ombi
ProxyPassReverse http://127.0.0.1:5000/ombi
</Location>

This has been working. However for the additional requirement for V3, I have the following, which I tried by best to convert the if nginx statement to Apache, however I have still having the same external issue:

RewriteEngine on
RewriteCond %{HTTP_REFERER} ^/ombi/ [NC]
RewriteRule ^/dist/([0-9\d*]).js /ombi/dist/$1.js [L]
</Location>

#### Reproduction Steps:

Access ombi externally from a server hosting the application using Apache.

**Comment by infamouswb** [comment]
I also tried:

<IfModule mod_rewrite.c>
RewriteEngine on
RewriteCond %{REQUEST_URI} !^/ombi/
RewriteRule ^/dist/([0-9\d*]).js /ombi/dist/$1.js [L]
</IfModule>

but no success :(

**Comment by G4Zz0L1** [comment]
Same here, I've seen anothere issue here, with same problem, the #1834

**Comment by infamouswb** [comment]
@G4Zz0L1 Have you tried anything different then what I mentioned? Someone out there show some love for Apache plz, lol.

**Comment by G4Zz0L1** [comment]
I've tried almost everything I've found on the web, something similar to your rewrite, and also other different thing totally different, but I can't get it to work properly

**Comment by tidusjar** [comment]
Sorry guys I cannot assist on this, My knowledge of Nginx or Apache is pretty limited, It should be as straightforward as just rewrite `/dist/1.js` to `/ombi/dist/1.js` where the number `1` could potentially be any number, currently I think it only goes up to `4`.

Can you not do something like:

    RewriteRule ^/dist/([0-9\d*]).js$ /ombi/dist/$1.js [NC,L]

**Comment by G4Zz0L1** [comment]
We're talking about the v3? Because my files are named completely different. Here the 404's are: loading.css, vendor.css, vendor.js and main.js.

Currently redirecting everyting to localhost:5000 and still 404. There are any log in ombi, for the web part, or something that I could check?

**Comment by tidusjar** [comment]
Have you set the base url in the Ombi Settings? Then restart Ombi?

**Comment by G4Zz0L1** [comment]
Yup, I've also tried that. But that base url it's only for the server on localhost, as far as I've seen, and it doesn't change the result for the proxied files.

**Comment by G4Zz0L1** [comment]
Wait, I've done it! You sent me to the right path!

After puth `/ombi` in the base url config, the rewrite on apache seems to work properly now (yesterday was failing, I don't know why)

`RewriteRule ^/ombi$ https://g4zz0l1.dyndns.info/ombi/ [R=301,L]
    RewriteCond %{HTTP_REFERER} "https://g4zz0l1.dyndns.info/ombi/"
    RewriteCond %{REQUEST_URI} !^/ombi
    RewriteRule ^(.*)$ /ombi$1 [R=301,L]
    <Location /ombi/>
        ProxyPass "http://localhost:5000/" connectiontimeout=5 timeout=30 keepalive=on
        ProxyPassReverse "http://localhost:5000/"
    </Location>`

**Comment by infamouswb** [comment]
@G4Zz0L1 Thanks for showing the code. For some reason it still doesn't work for me. In your code where you put weburl, you mean your external hostname right? That's what I changed it to, but no luck. I'm determined to get this working!

**Comment by G4Zz0L1** [comment]
Yep, it's my ddns URL. It works ok now. You've put also the /ombi part in the config?

**Comment by infamouswb** [comment]
@G4Zz0L1 which part do you mean? How come in your ProxyPass and ProxyPassReverse you dont have /ombi at the end and just / ? By not working, I mean it still loads the page but it is blank. Just the dark grey back loads.

For me my ombi base url setting is /ombi

**Comment by G4Zz0L1** [comment]
Dunno, it's working like that.

Yep, I was talking about the ombi settings itself. I don't know, it seems ok that way.

In the console what files gives you error?

**Comment by infamouswb** [comment]
@G4Zz0L1 I am getting: 

GET https://mywebsite.net/dist/2.js net::ERR_ABORTED

**Comment by infamouswb** [comment]
@G4Zz0L1  nevermind, Silly me left out RewriteEngine on on top of the rewriterules you have! Amazing job! Thank you so much! I think @tidusjar should post the solution in the reverseproxy wiki for whoever uses Apache.

**Comment by G4Zz0L1** [comment]
Good!
+1 I think that the apache version added could help someone like us, in the future.

**Comment by tidusjar** [comment]
Can someone create a wiki entry for this!? 

Thanks !!

**Comment by infamouswb** [comment]
@tidusjar Done! Hope is all good! This issue can be closed :)
