### ISSUE TITLE
deleted movie is still available

### ISSUE THREAD

**Issue by cm86** [tidusjar/Ombi#1866]
#### Ombi build Version:

V 3.0.2566

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Ubuntu 16.04

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2018-01-05 15:12:20.210 +01:00 [Error] StatusCode: Forbidden, Reason: Site Disabled, RequestUri: https://ombiservice.azurewebsites.net/api/update/DotNetCore
2018-01-05 15:12:34.200 +01:00 [Error] StatusCode: Forbidden, Reason: Site Disabled, RequestUri: https://ombiservice.azurewebsites.net/api/update/DotNetCore
2018-01-05 15:12:50.730 +01:00 [Error] StatusCode: Forbidden, Reason: Site Disabled, RequestUri: https://ombiservice.azurewebsites.net/api/update/DotNetCore
2018-01-05 15:13:30.470 +01:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://plex.tv/users/sign_in.json
2018-01-05 15:13:43.381 +01:00 [Error] StatusCode: Forbidden, Reason: Site Disabled, RequestUri: https://ombiservice.azurewebsites.net/api/update/DotNetCore
2018-01-05 15:14:41.029 +01:00 [Error] StatusCode: Forbidden, Reason: Site Disabled, RequestUri: https://ombiservice.azurewebsites.net/api/update/DotNetCore
2018-01-05 15:19:41.241 +01:00 [Warning] Exception when testing Email Notifications
System.InvalidOperationException: 5.5.1 Authentication Required. Learn more at
5.5.1  https://support.google.com/mail/?p=WantAuthError i6sm3913555eda.6 - gsmtp
   at Ombi.Notifications.GenericEmailProvider.<SendAdHoc>d__5.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 94
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<Email>d__54.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 214
2018-01-05 15:20:08.113 +01:00 [Warning] Exception when testing Email Notifications
System.InvalidOperationException: 5.5.1 Authentication Required. Learn more at
5.5.1  https://support.google.com/mail/?p=WantAuthError n3sm3928271edb.46 - gsmtp
   at Ombi.Notifications.GenericEmailProvider.<SendAdHoc>d__5.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 94
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<Email>d__54.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 214
2018-01-05 15:23:56.944 +01:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/93456?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos
2018-01-05 15:23:56.954 +01:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/332114?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos
2018-01-05 15:23:56.963 +01:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/324852?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos
2018-01-05 15:23:57.054 +01:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/20352?api_key=b8eabaf5608b88d0298aa189dd90bf00
2018-01-05 15:23:57.055 +01:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/0?api_key=b8eabaf5608b88d0298aa189dd90bf00
2018-01-05 15:23:57.066 +01:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/0?api_key=b8eabaf5608b88d0298aa189dd90bf00
2018-01-05 15:23:57.075 +01:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/0?api_key=b8eabaf5608b88d0298aa189dd90bf00
2018-01-05 15:23:57.085 +01:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/268511?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos
2018-01-05 15:23:57.089 +01:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/350562?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos
2018-01-05 15:23:57.195 +01:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/0?api_key=b8eabaf5608b88d0298aa189dd90bf00
2018-01-05 15:23:57.200 +01:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/0?api_key=b8eabaf5608b88d0298aa189dd90bf00
2018-01-05 15:23:57.227 +01:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/280549?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos
2018-01-05 15:23:57.232 +01:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/79468?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos
2018-01-05 15:23:57.239 +01:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/61226?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos
2018-01-05 15:23:57.337 +01:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/0?api_key=b8eabaf5608b88d0298aa189dd90bf00
2018-01-05 15:23:57.344 +01:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/0?api_key=b8eabaf5608b88d0298aa189dd90bf00
2018-01-05 15:23:57.353 +01:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/0?api_key=b8eabaf5608b88d0298aa189dd90bf00
2018-01-05 15:24:37.111 +01:00 [Error] StatusCode: Forbidden, Reason: Site Disabled, RequestUri: https://ombiservice.azurewebsites.net/api/update/DotNetCore
2018-01-05 15:25:50.680 +01:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/141052?api_key=b8eabaf5608b88d0298aa189dd90bf00
2018-01-05 15:25:50.710 +01:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/317091?api_key=b8eabaf5608b88d0298aa189dd90bf00
2018-01-05 15:26:11.418 +01:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/332114?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos
2018-01-05 15:26:11.449 +01:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/93456?api_key=b8eabaf5608b88d0298aa189dd90bf00
2018-01-05 15:26:11.543 +01:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/0?api_key=b8eabaf5608b88d0298aa189dd90bf00
2018-01-05 15:28:27.768 +01:00 [Error] StatusCode: Forbidden, Reason: Site Disabled, RequestUri: https://ombiservice.azurewebsites.net/api/update/DotNetCore
2018-01-05 15:43:07.388 +01:00 [Error] StatusCode: Forbidden, Reason: Site Disabled, RequestUri: https://ombiservice.azurewebsites.net/api/update/DotNetCore
2018-01-05 16:09:41.619 +01:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/40044?api_key=b8eabaf5608b88d0298aa189dd90bf00
2018-01-05 16:09:41.638 +01:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/18994?api_key=b8eabaf5608b88d0298aa189dd90bf00
2018-01-05 16:13:31.234 +01:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://plex.tv/users/sign_in.json
2018-01-05 16:16:04.075 +01:00 [Error] StatusCode: Forbidden, Reason: Site Disabled, RequestUri: https://ombiservice.azurewebsites.net/api/update/DotNetCore
2018-01-05 16:34:28.895 +01:00 [Error] StatusCode: Forbidden, Reason: Site Disabled, RequestUri: https://ombiservice.azurewebsites.net/api/update/DotNetCore
2018-01-05 16:37:40.976 +01:00 [Error] StatusCode: Forbidden, Reason: Site Disabled, RequestUri: https://ombiservice.azurewebsites.net/api/update/DotNetCore
2018-01-05 16:39:21.695 +01:00 [Error] StatusCode: Forbidden, Reason: Site Disabled, RequestUri: https://ombiservice.azurewebsites.net/api/update/DotNetCore
2018-01-05 16:59:50.861 +01:00 [Error] StatusCode: Forbidden, Reason: Site Disabled, RequestUri: https://ombiservice.azurewebsites.net/api/update/DotNetCore
2018-01-05 19:00:11.444 +01:00 [Warning] Failed to process the job '40': an exception occurred. Retry attempt 1 of 1 will be performed in 00:00:33.
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.<Request>d__8`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Service.OmbiService.<GetUpdates>d__10.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Service\OmbiService.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 220
2018-01-05 19:00:52.367 +01:00 [Information] 1 scheduled job(s) enqueued.
2018-01-05 19:00:56.707 +01:00 [Error] Failed to process the job '40': an exception occurred.
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.<Request>d__8`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Service.OmbiService.<GetUpdates>d__10.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Service\OmbiService.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 220
2018-01-05 19:05:34.266 +01:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/106631?api_key=b8eabaf5608b88d0298aa189dd90bf00
2018-01-05 19:05:34.308 +01:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/183154?api_key=b8eabaf5608b88d0298aa189dd90bf00
2018-01-05 19:10:18.384 +01:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/1893?api_key=b8eabaf5608b88d0298aa189dd90bf00
2018-01-05 19:10:18.384 +01:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/74849?api_key=b8eabaf5608b88d0298aa189dd90bf00
2018-01-05 19:20:01.988 +01:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/45417?api_key=b8eabaf5608b88d0298aa189dd90bf00
2018-01-05 19:20:01.993 +01:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/340448?api_key=b8eabaf5608b88d0298aa189dd90bf00
2018-01-05 19:20:02.120 +01:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/search/movie?api_key=b8eabaf5608b88d0298aa189dd90bf00&query=Wulver
2018-01-05 19:20:02.926 +01:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/search/movie?api_key=b8eabaf5608b88d0298aa189dd90bf00&query=Wulverine
2018-01-05 19:20:46.034 +01:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/276148?api_key=b8eabaf5608b88d0298aa189dd90bf00
2018-01-05 19:20:46.040 +01:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/121133?api_key=b8eabaf5608b88d0298aa189dd90bf00
2018-01-05 19:24:02.964 +01:00 [Error] StatusCode: Forbidden, Reason: Site Disabled, RequestUri: https://ombiservice.azurewebsites.net/api/update/DotNetCore
2018-01-05 19:30:16.749 +01:00 [Error] StatusCode: Forbidden, Reason: Site Disabled, RequestUri: https://ombiservice.azurewebsites.net/api/update/DotNetCore
2018-01-05 19:34:16.490 +01:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/183154?api_key=b8eabaf5608b88d0298aa189dd90bf00
2018-01-05 19:34:16.502 +01:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/106631?api_key=b8eabaf5608b88d0298aa189dd90bf00


2018-01-06 01:00:22.283 +01:00 [Warning] Failed to process the job '93': an exception occurred. Retry attempt 1 of 1 will be performed in 00:00:35.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 220
2018-01-06 01:01:10.847 +01:00 [Information] 1 scheduled job(s) enqueued.
2018-01-06 01:01:22.788 +01:00 [Error] Failed to process the job '93': an exception occurred.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 220
2018-01-06 07:00:42.962 +01:00 [Warning] Failed to process the job '143': an exception occurred. Retry attempt 1 of 1 will be performed in 00:00:37.
System.ComponentModel.Win32Exception (0x80004005): Permission denied
   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 220
2018-01-06 07:01:20.114 +01:00 [Information] 1 scheduled job(s) enqueued.
2018-01-06 07:01:58.673 +01:00 [Error] Failed to process the job '143': an exception occurred.
System.ComponentModel.Win32Exception (0x80004005): Permission denied
   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 220
2018-01-06 12:28:08.585 +01:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/78885?api_key=b8eabaf5608b88d0298aa189dd90bf00
2018-01-06 12:28:08.622 +01:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/280966?api_key=b8eabaf5608b88d0298aa189dd90bf00
2018-01-06 12:28:09.292 +01:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/search/movie?api_key=b8eabaf5608b88d0298aa189dd90bf00&query=Tho
2018-01-06 12:28:10.331 +01:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/search/movie?api_key=b8eabaf5608b88d0298aa189dd90bf00&query=Thor
2018-01-06 12:34:39.741 +01:00 [Warning] Failed to process the job '194': an exception occurred. Retry attempt 1 of 1 will be performed in 00:00:25.
System.ComponentModel.Win32Exception (0x80004005): Permission denied
   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 220
2018-01-06 12:35:11.808 +01:00 [Information] 1 scheduled job(s) enqueued.
2018-01-06 12:35:57.646 +01:00 [Error] Failed to process the job '194': an exception occurred.
System.ComponentModel.Win32Exception (0x80004005): Permission denied
   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 220
2018-01-06 13:00:47.667 +01:00 [Warning] Failed to process the job '196': an exception occurred. Retry attempt 1 of 1 will be performed in 00:00:23.
System.ComponentModel.Win32Exception (0x80004005): Permission denied
   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 220
2018-01-06 13:01:11.931 +01:00 [Information] 1 scheduled job(s) enqueued.
2018-01-06 13:01:53.093 +01:00 [Error] Failed to process the job '196': an exception occurred.
System.ComponentModel.Win32Exception (0x80004005): Permission denied
   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 220
2018-01-06 13:49:28.790 +01:00 [Error] StatusCode: Forbidden, Reason: Site Disabled, RequestUri: https://ombiservice.azurewebsites.net/api/update/DotNetCore
2018-01-06 13:49:36.606 +01:00 [Error] StatusCode: Forbidden, Reason: Site Disabled, RequestUri: https://ombiservice.azurewebsites.net/api/update/DotNetCore
2018-01-06 19:00:08.088 +01:00 [Warning] Failed to process the job '245': an exception occurred. Retry attempt 1 of 1 will be performed in 00:00:20.
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.<Request>d__8`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Service.OmbiService.<GetUpdates>d__10.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Service\OmbiService.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 220
2018-01-06 19:00:33.422 +01:00 [Information] 1 scheduled job(s) enqueued.
2018-01-06 19:00:38.302 +01:00 [Error] Failed to process the job '245': an exception occurred.
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.<Request>d__8`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Service.OmbiService.<GetUpdates>d__10.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Service\OmbiService.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 220
2018-01-06 20:18:29.271 +01:00 [Error] StatusCode: Forbidden, Reason: Site Disabled, RequestUri: https://ombiservice.azurewebsites.net/api/update/DotNetCore
2018-01-06 20:19:28.108 +01:00 [Error] StatusCode: Forbidden, Reason: Site Disabled, RequestUri: https://ombiservice.azurewebsites.net/api/update/DotNetCore
2018-01-06 20:19:53.673 +01:00 [Error] StatusCode: Forbidden, Reason: Site Disabled, RequestUri: https://ombiservice.azurewebsites.net/api/update/DotNetCore
2018-01-06 20:20:00.679 +01:00 [Error] StatusCode: Forbidden, Reason: Site Disabled, RequestUri: https://ombiservice.azurewebsites.net/api/update/DotNetCore
2018-01-06 20:21:32.995 +01:00 [Error] StatusCode: Forbidden, Reason: Site Disabled, RequestUri: https://ombiservice.azurewebsites.net/api/update/DotNetCore
2018-01-06 20:27:37.558 +01:00 [Error] StatusCode: Forbidden, Reason: Site Disabled, RequestUri: https://ombiservice.azurewebsites.net/api/update/DotNetCore
2018-01-06 20:35:50.495 +01:00 [Error] StatusCode: Forbidden, Reason: Site Disabled, RequestUri: https://ombiservice.azurewebsites.net/api/update/DotNetCore
2018-01-06 20:36:31.344 +01:00 [Error] StatusCode: Forbidden, Reason: Site Disabled, RequestUri: https://ombiservice.azurewebsites.net/api/update/DotNetCore
2018-01-06 20:45:22.130 +01:00 [Error] StatusCode: Forbidden, Reason: Site Disabled, RequestUri: https://ombiservice.azurewebsites.net/api/update/DotNetCore
2018-01-06 23:35:35.561 +01:00 [Error] StatusCode: Forbidden, Reason: Site Disabled, RequestUri: https://ombiservice.azurewebsites.net/api/update/DotNetCore
2018-01-06 23:36:04.608 +01:00 [Error] StatusCode: Forbidden, Reason: Site Disabled, RequestUri: https://ombiservice.azurewebsites.net/api/update/DotNetCore
2018-01-06 23:36:55.424 +01:00 [Error] StatusCode: Forbidden, Reason: Site Disabled, RequestUri: https://ombiservice.azurewebsites.net/api/update/DotNetCore
2018-01-06 23:39:29.664 +01:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://plex.tv/users/sign_in.json
2018-01-06 23:40:46.903 +01:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://plex.tv/users/sign_in.json
2018-01-06 23:42:09.053 +01:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://plex.tv/users/sign_in.json
2018-01-06 23:45:38.472 +01:00 [Error] StatusCode: Forbidden, Reason: Site Disabled, RequestUri: https://ombiservice.azurewebsites.net/api/update/DotNetCore
2018-01-06 23:53:03.014 +01:00 [Error] StatusCode: Forbidden, Reason: Site Disabled, RequestUri: https://ombiservice.azurewebsites.net/api/update/DotNetCore
2018-01-06 23:53:29.502 +01:00 [Error] StatusCode: Forbidden, Reason: Site Disabled, RequestUri: https://ombiservice.azurewebsites.net/api/update/DotNetCore
2018-01-06 23:53:49.727 +01:00 [Error] StatusCode: Forbidden, Reason: Site Disabled, RequestUri: https://ombiservice.azurewebsites.net/api/update/DotNetCore
2018-01-06 23:55:49.177 +01:00 [Error] StatusCode: Forbidden, Reason: Site Disabled, RequestUri: https://ombiservice.azurewebsites.net/api/update/DotNetCore


```

#### Problem Description:

I deleted some movies in PMS but they are still marked as available in Ombi.
Cancelled the connection to PMS and the movies are still available.
Reconnection is not helping.

#### Reproduction Steps:

Delete a movie in PMS.
Check if it's still available in Ombi.

**Comment by cm86** [comment]
So i have a workaround for deleting movies in the ombi.db

first i have created a bash script:

`sudo nano nameofthescript.sh`
insert:

```
#!/bin/bash
sudo sqlite3 /opt/Ombi/Ombi.db "select * from PlexServerContent where Title like '%$1%'"
read -p " Delete really?! Going on with pressing Enter!"
sudo sqlite3 /opt/Ombi/Ombi.db "delete from PlexServerContent where Title like '%$1%'"
sudo sqlite3 /opt/Ombi/Ombi.db "select * from PlexServerContent where Title like '%$1%'"
```
then call the script like:

bash sudo nameofthescript.sh <title of the movie>

Close and moved to feathub as feature request
[Make a deleted movie in plex unavailable in ombi](https://feathub.com/tidusjar/Ombi/+220)

**Comment by estavez** [comment]
This function really needs to be added. Se my post here about it: https://github.com/tidusjar/Ombi/issues/1566#issuecomment-428004457

**Comment by s0mm3rb** [comment]
+1 this is needed
