### ISSUE TITLE
Job 509 Crashing OMBI

### ISSUE THREAD

**Issue by kfulgham** [tidusjar/Ombi#1874]
#### Ombi build Version:

3.0.2509

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Windows 10

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
2018-01-05 17:01:26.811 -07:00 [Error] Failed to process the job '417': an exception occurred.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 220
2018-01-05 17:41:35.129 -07:00 [Information] Hangfire Server stopped.


2018-01-07 17:00:45.810 -07:00 [Information] 1 scheduled job(s) enqueued.
2018-01-07 17:01:27.232 -07:00 [Information] Hangfire Server stopped.


2018-01-09 17:00:17.007 -07:00 [Warning] Failed to process the job '509': an exception occurred. Retry attempt 1 of 1 will be performed in 00:00:22.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 220
2018-01-09 17:00:53.247 -07:00 [Information] 1 scheduled job(s) enqueued.
2018-01-09 17:01:26.170 -07:00 [Information] Hangfire Server stopped.

```

#### Problem Description:

Ombi has been crashing regularly. It appears as though it's related to a job trying to run? I have to manually restart the service at least every day.

#### Reproduction Steps:

Leave Ombi running for several hours.

**Comment by tidusjar** [comment]
Turn off the automatic updater. It's not ready yet anyway.
