### ISSUE TITLE
Email Notifications Settings Not Saving / Sending 

### ISSUE THREAD

**Issue by Comfubar** [tidusjar/Ombi#1890]
<!--- 

Ombi Version:

V 3.0.2610

Update Branch: Stable

Media Server: Plex

Media Server Version:

Version 1.11.0.4666 

Operating System:

Windows 10
Mono Version (only if you are not on windows)

(Place text here)
Applicable Logs (from /logs/ directory or the Admin page):
```
2018-01-13 02:27:36.867 -05:00 [Warning] Exception when testing Email Notifications
System.InvalidOperationException: The SMTP server has unexpectedly disconnected.
   at Ombi.Notifications.GenericEmailProvider.<SendAdHoc>d__5.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 94
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<Email>d__54.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 214
2018-01-13 02:28:56.952 -05:00 [Warning] Exception when testing Email Notifications
System.InvalidOperationException: The SMTP server has unexpectedly disconnected.
   at Ombi.Notifications.GenericEmailProvider.<SendAdHoc>d__5.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 94
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<Email>d__54.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 214
2018-01-13 02:30:43.080 -05:00 [Warning] Exception when testing Email Notifications
System.InvalidOperationException: The SMTP server has unexpectedly disconnected.
   at Ombi.Notifications.GenericEmailProvider.<SendAdHoc>d__5.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 94
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<Email>d__54.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 214
2018-01-13 02:39:16.986 -05:00 [Warning] Exception when testing Email Notifications
System.InvalidOperationException: The SMTP server has unexpectedly disconnected.
   at Ombi.Notifications.GenericEmailProvider.<SendAdHoc>d__5.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 94
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<Email>d__54.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 214
2018-01-13 02:40:01.094 -05:00 [Debug] Removing outdated records from the 'AggregatedCounter' table...
2018-01-13 02:40:01.095 -05:00 [Debug] Removing outdated records from the 'Job' table...

```

#### Problem Description:
Email Notification and Setup Erroring 

When submitting sometimes the email and password will not save when submitted it seems it finally has but now I'm getting errors when sending a Test 

#### Reproduction Steps:

setting up email for ombi / Using 2FA (Two Factor Auth) Password for email pass as sometimes needed testing with actual pass again as the same result happens with both

**Comment by Comfubar** [comment]
For some odd Reason Github is stating my Post is no description is provided just incase ti shows the same for you please let me know 

I pastebinned the post here just in case as well 

https://pastebin.com/2fvNkdLH

**Comment by tidusjar** [comment]
I don't know what SMTP provider you are using but it seems that we are opening the connecting but your SMTP is closing it straight away when it shouldn't. That's what the log is telling me

**Comment by Comfubar** [comment]
Looks like after I unchecked 

Disable TLS/SSL
Disable Certificate Checking

It started to work correctly
