### ISSUE TITLE
Catching movies don't work

### ISSUE THREAD

**Issue by MrTwIXx** [tidusjar/Ombi#1893]
#### Ombi build Version:

V 3.0.2672

#### Update Branch:

Open Beta

#### Media Sever:

Plex Cloud

#### Media Server Version:

1.9.1.260

#### Operating System:

Windows 10

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2018-01-13 14:43:46.341 +01:00 [Information] Start installing Hangfire SQL objects...
2018-01-13 14:43:46.405 +01:00 [Information] Hangfire SQL objects installed.
2018-01-13 14:43:46.425 +01:00 [Information] Starting Hangfire Server
2018-01-13 14:43:46.427 +01:00 [Information] Using job storage: 'SQLite Server: Schedules.db'
2018-01-13 14:43:46.427 +01:00 [Information] Using the following options for Hangfire Server:
2018-01-13 14:43:46.427 +01:00 [Information]     Worker count: 1
2018-01-13 14:43:46.427 +01:00 [Information]     Listening queues: 'default'
2018-01-13 14:43:46.427 +01:00 [Information]     Shutdown timeout: 1.00:00:00
2018-01-13 14:43:46.427 +01:00 [Information]     Schedule polling interval: 00:00:15
2018-01-13 14:43:46.433 +01:00 [Debug] Background process 'BackgroundProcessingServer' started.
2018-01-13 14:43:46.670 +01:00 [Debug] Background process 'ServerHeartbeat' started.
2018-01-13 14:43:46.671 +01:00 [Debug] Background process 'ServerWatchdog' started.
2018-01-13 14:43:46.672 +01:00 [Debug] Background process 'Hangfire.SQLite.ExpirationManager' started.
2018-01-13 14:43:46.674 +01:00 [Debug] Background process 'Worker #b14e7351' started.
2018-01-13 14:43:46.675 +01:00 [Debug] Background process 'DelayedJobScheduler' started.
2018-01-13 14:43:46.676 +01:00 [Debug] Background process 'RecurringJobScheduler' started.
2018-01-13 14:43:46.681 +01:00 [Debug] Removing outdated records from the 'AggregatedCounter' table...
2018-01-13 14:43:46.840 +01:00 [Debug] Removing outdated records from the 'Job' table...
2018-01-13 14:43:46.863 +01:00 [Debug] Removing outdated records from the 'List' table...
2018-01-13 14:43:46.866 +01:00 [Debug] Removing outdated records from the 'Set' table...
2018-01-13 14:43:46.868 +01:00 [Debug] Removing outdated records from the 'Hash' table...

```

#### Problem Description:

Caching from movies don't work. Series worked, but the catcher always fails after some movies.

#### Reproduction Steps:

Start the manual catcher in the Plex Tab.

**Comment by tidusjar** [comment]
How do you know it's failing?

Can you please provide some more information because this issue doesn't tell me much

**Comment by MrTwIXx** [comment]
Because it don't get updated and I see the following in the cmd.

```
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Getting all content from server TwIXx's VoD
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Lib 4 is not monitored, so skipping
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Lib 2 is not monitored, so skipping
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Lib 3 is not monitored, so skipping
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We found 1 items
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Processing Movies
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Adding movie 13 Hours: The Secret Soldiers of Benghazi
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Adding movie 21
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Adding movie 47 Meters Down
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Adding movie Alibi.com
warn: Ombi.Schedule.Jobs.Plex.PlexContentSync[2000]
      Exception thrown when attempting to cache the Plex Content
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: Der Server lieferte eine ungültige oder unbekannte Rückmeldung
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.OmbiHttpClient.<SendAsync>d__5.MoveNext() in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Api.<Request>d__6`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 34
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Plex.PlexApi.<GetMetadata>d__15.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 106
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.<StartTheCache>d__17.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 207
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.<CacheContent>d__16.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 80
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting EP Cacher
```

After that no films are added and the catcher don't start again.

**Comment by tidusjar** [comment]
Well the error is in there. 

Der Server lieferte eine ungültige oder unbekannte Rückmeldung

Looks like Plex is being very strange with the API command. Can you restart Plex and see if that helps?

**Comment by MrTwIXx** [comment]
Did it already. Don't help

**Comment by tidusjar** [comment]
I'm not sure what to suggest, it's an error outside of ombi. 

Are they in the same network?

**Comment by MrTwIXx** [comment]
No, I use Plex Cloud so the Plex server is in the USA and I'm in europe.

**Comment by jaycedk** [comment]
Der Server lieferte eine ungültige oder unbekannte Rückmeldung is not showing up in themoviedb.org

[https://www.themoviedb.org/search?language=da-DK&query=Der+Server+lieferte+eine+ung%C3%BCltige+oder+unbekannte+R%C3%BCckmeldung]https://www.themoviedb.org/search?language=da-DK&query=Der+Server+lieferte+eine+ung%C3%BCltige+oder+unbekannte+R%C3%BCckmeldung

Can you remove the movie from plex, rescan, empty trash and try again.

**Comment by tidusjar** [comment]
I've not had time to look into this.

Please keep in mind this is an open source project that I am not being paid for, I have a full-time job, wife, and a baby.

For now all I can assume is that Plex instance is not available when Ombi is trying to connect to it (since I know the Plex instances do shut down) so I'm not sure what can be done about this.

**Comment by tidusjar** [comment]
Have you been able to investigate when these errors happen that the Plex Could instance is available?

**Comment by MrTwIXx** [comment]
I have done the following.

1. Deleted Plex Cloud
2. Created a new Plex Cloud
3. Made a fresh install of Ombi

Nothing helped.

So I'm watching an episode from a tv-serie and cache the movies. At the moment it seems that that is working, but it chache the movies very very slowly. Last time the caching was very fast. I will post an update if it worked.

**Comment by tidusjar** [comment]
I think my original assumption is correct, that the Plex Cloud instance is shutting down when we are attempting to communicate with it. There is not much I can do about this.

I wouldn't expect the caching to be fast since it's going over the internet from EU > US and back, plus it could potentially be a lot of data.

**Comment by MrTwIXx** [comment]
Sure. It added a lot of movies, but if I search it now, it don't say available. 

So I will start playing now a long movie and will start the catcher, I hope it will add the movies

**Comment by MrTwIXx** [comment]
Ombi only add the movies if the chacher will finish

**Comment by MrTwIXx** [comment]
It don't work anymore. I cached my 4K movies, these are only 5 movies.

Now I started a movie and I want to catch my other movies more than 200, but it fails every time :(

**Comment by tidusjar** [comment]
Any more logs other than what we have?

**Comment by MrTwIXx** [comment]
I got always the same error message, so no new log

**Comment by tidusjar** [comment]
What hostname are you using to connect to Plex?
