### ISSUE TITLE
Ombi started crashing on me

### ISSUE THREAD

**Issue by aenyan** [tidusjar/Ombi#1895]
#### Ombi build Version:

V 3.0.2386

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:
Windows 10 1703

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2018-01-13 18:43:54.267 -05:00 [Information] Start installing Hangfire SQL objects...
2018-01-13 18:43:54.470 -05:00 [Information] Hangfire SQL objects installed.
2018-01-13 18:43:54.541 -05:00 [Information] Starting Hangfire Server
2018-01-13 18:43:54.545 -05:00 [Information] Using job storage: 'SQLite Server: Schedules.db'
2018-01-13 18:43:54.546 -05:00 [Information] Using the following options for Hangfire Server:
2018-01-13 18:43:54.546 -05:00 [Information]     Worker count: 1
2018-01-13 18:43:54.546 -05:00 [Information]     Listening queues: 'default'
2018-01-13 18:43:54.546 -05:00 [Information]     Shutdown timeout: 1.00:00:00
2018-01-13 18:43:54.547 -05:00 [Information]     Schedule polling interval: 00:00:15
2018-01-13 18:44:00.954 -05:00 [Warning] Failed to process the job '8068': an exception occurred. Retry attempt 1 of 1 will be performed in 00:00:24.
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.<Request>d__8`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 84
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Service.OmbiService.<GetUpdates>d__10.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Service\OmbiService.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 219
2018-01-13 18:44:25.109 -05:00 [Information] 1 scheduled job(s) enqueued.
2018-01-13 18:44:43.023 -05:00 [Warning] Failed to process the job '8072': an exception occurred. Retry attempt 1 of 1 will be performed in 00:00:24.
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.<Request>d__8`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 84
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Service.OmbiService.<GetUpdates>d__10.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Service\OmbiService.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 219
2018-01-13 18:44:46.820 -05:00 [Error] Failed to process the job '8068': an exception occurred.
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.<Request>d__8`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 84
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Service.OmbiService.<GetUpdates>d__10.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Service\OmbiService.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 219
2018-01-13 18:45:10.304 -05:00 [Information] 1 scheduled job(s) enqueued.
2018-01-13 18:45:20.785 -05:00 [Error] Failed to process the job '8072': an exception occurred.
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.<Request>d__8`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 84
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Service.OmbiService.<GetUpdates>d__10.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Service\OmbiService.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 219
2018-01-13 18:46:53.143 -05:00 [Error] StatusCode: Forbidden, Reason: Site Disabled
2018-01-13 18:46:55.557 -05:00 [Error] StatusCode: Forbidden, Reason: Site Disabled
2018-01-13 18:46:55.564 -05:00 [Error] StatusCode: Forbidden, Reason: Site Disabled
2018-01-13 18:48:03.926 -05:00 [Error] StatusCode: Forbidden, Reason: Site Disabled
2018-01-13 18:48:07.560 -05:00 [Error] StatusCode: Forbidden, Reason: Site Disabled
2018-01-13 18:48:09.620 -05:00 [Error] StatusCode: Forbidden, Reason: Site Disabled
2018-01-13 18:48:12.878 -05:00 [Error] StatusCode: Forbidden, Reason: Site Disabled
2018-01-13 18:48:16.065 -05:00 [Error] StatusCode: Forbidden, Reason: Site Disabled
2018-01-13 18:48:16.096 -05:00 [Error] StatusCode: Forbidden, Reason: Site Disabled
2018-01-13 18:48:28.162 -05:00 [Error] StatusCode: Forbidden, Reason: Site Disabled
2018-01-13 18:57:26.615 -05:00 [Error] StatusCode: Forbidden, Reason: Site Disabled
2018-01-13 19:00:34.138 -05:00 [Warning] Failed to process the job '8078': an exception occurred. Retry attempt 1 of 1 will be performed in 00:00:42.
System.IO.IOException: The directory is not empty
   at System.IO.Win32FileSystem.RemoveDirectoryHelper(String fullPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Win32FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 219
2018-01-13 19:01:26.060 -05:00 [Information] 1 scheduled job(s) enqueued.


```

#### Problem Description:

Shit be crashin' yo

#### Reproduction Steps:

No clue what's causing the issue. Ombi config has been untouched outside of branch updates distributed via admin page since install several months ago. Started crashing yesterday and had to launch 4 times before it pretended to be stable overnight.

**Comment by tidusjar** [comment]
Please manually update, you are 200+ builds behind.
