### ISSUE TITLE
Unable to connect to CouchPotato on macOS

### ISSUE THREAD

**Issue by weisheng** [tidusjar/Ombi#1917]
#### Ombi build Version:

V 3.0.2738

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

1.11.0.666

#### Operating System:

macOS High Sierra 10.13.2

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2018-01-22 04:44:54.111 +08:00 [Information] Start installing Hangfire SQL objects...
2018-01-22 04:44:54.169 +08:00 [Information] Hangfire SQL objects installed.
2018-01-22 04:44:54.196 +08:00 [Information] Starting Hangfire Server
2018-01-22 04:44:54.199 +08:00 [Information] Using job storage: 'SQLite Server: Schedules.db'
2018-01-22 04:44:54.199 +08:00 [Information] Using the following options for Hangfire Server:
2018-01-22 04:44:54.199 +08:00 [Information]     Worker count: 1
2018-01-22 04:44:54.200 +08:00 [Information]     Listening queues: 'default'
2018-01-22 04:44:54.200 +08:00 [Information]     Shutdown timeout: 1.00:00:00
2018-01-22 04:44:54.200 +08:00 [Information]     Schedule polling interval: 00:00:15
2018-01-22 04:44:54.208 +08:00 [Debug] Background process 'BackgroundProcessingServer' started.
2018-01-22 04:44:54.338 +08:00 [Debug] Background process 'ServerHeartbeat' started.
2018-01-22 04:44:54.338 +08:00 [Debug] Background process 'ServerWatchdog' started.
2018-01-22 04:44:54.338 +08:00 [Debug] Background process 'Hangfire.SQLite.ExpirationManager' started.
2018-01-22 04:44:54.339 +08:00 [Debug] Background process 'Worker #113b5d34' started.
2018-01-22 04:44:54.341 +08:00 [Debug] Background process 'DelayedJobScheduler' started.
2018-01-22 04:44:54.342 +08:00 [Debug] Removing outdated records from the 'AggregatedCounter' table...
2018-01-22 04:44:54.344 +08:00 [Debug] Background process 'RecurringJobScheduler' started.
2018-01-22 04:44:54.368 +08:00 [Debug] Removing outdated records from the 'Job' table...
2018-01-22 04:44:55.464 +08:00 [Debug] Removing outdated records from the 'List' table...
2018-01-22 04:44:55.465 +08:00 [Debug] Removing outdated records from the 'Set' table...
2018-01-22 04:44:55.469 +08:00 [Debug] Removing outdated records from the 'Hash' table...
2018-01-22 04:47:52.221 +08:00 [Error] Could not test CP
System.PlatformNotSupportedException: The handler does not support custom handling of certificates with this combination of libcurl (7.54.0) and its SSL backend ("LibreSSL/2.0.20").
   at System.Net.Http.CurlHandler.SslProvider.SetSslOptions(EasyRequest easy, ClientCertificateOption clientCertOption)
   at System.Net.Http.CurlHandler.EasyRequest.InitializeCurl()
   at System.Net.Http.CurlHandler.MultiAgent.ActivateNewRequest(EasyRequest easy)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.OmbiHttpClient.<SendAsync>d__5.MoveNext() in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Api.<Request>d__6`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 34
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.CouchPotato.CouchPotatoApi.<Status>d__4.MoveNext() in C:\projects\requestplex\src\Ombi.Api.CouchPotato\CouchPotatoApi.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<CouchPotato>d__59.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 319

```

#### Problem Description:

I'm unable to connect to CouchPotato despite checking "Ignore any certificate errors". The advice for a "System.Net.Http.CurlHandler" error in the wiki does not apply to macOS.

**Comment by tidusjar** [comment]
Do you have the ignore certificate errors enabled in the ombi settings?

**Comment by weisheng** [comment]
Yes I've enabled that setting.

**Comment by tidusjar** [comment]
Turn it off. Looks like your version of libreSSL does not support it.

**Comment by weisheng** [comment]
Do you mean turn off SSL in CouchPotato or turn off the Ombi setting to ignore errors? I'm still unable to connect when unchecking the Ombi setting.

**Comment by tidusjar** [comment]
Please turn off the ombi setting (restart Ombi just to make sure) and then post the logs when connecting to couch potato.

**Comment by weisheng** [comment]
`2018-01-22 05:34:03.844 +08:00 [Information] Start installing Hangfire SQL objects...
2018-01-22 05:34:03.907 +08:00 [Information] Hangfire SQL objects installed.
2018-01-22 05:34:03.934 +08:00 [Information] Starting Hangfire Server
2018-01-22 05:34:03.937 +08:00 [Information] Using job storage: 'SQLite Server: Schedules.db'
2018-01-22 05:34:03.937 +08:00 [Information] Using the following options for Hangfire Server:
2018-01-22 05:34:03.937 +08:00 [Information]     Worker count: 1
2018-01-22 05:34:03.938 +08:00 [Information]     Listening queues: 'default'
2018-01-22 05:34:03.938 +08:00 [Information]     Shutdown timeout: 1.00:00:00
2018-01-22 05:34:03.938 +08:00 [Information]     Schedule polling interval: 00:00:15
2018-01-22 05:34:03.946 +08:00 [Debug] Background process 'BackgroundProcessingServer' started.
2018-01-22 05:34:04.078 +08:00 [Debug] Background process 'ServerHeartbeat' started.
2018-01-22 05:34:04.079 +08:00 [Debug] Background process 'ServerWatchdog' started.
2018-01-22 05:34:04.083 +08:00 [Debug] Background process 'Hangfire.SQLite.ExpirationManager' started.
2018-01-22 05:34:04.084 +08:00 [Debug] Background process 'Worker #03b90486' started.
2018-01-22 05:34:04.087 +08:00 [Debug] Removing outdated records from the 'AggregatedCounter' table...
2018-01-22 05:34:04.088 +08:00 [Debug] Background process 'DelayedJobScheduler' started.
2018-01-22 05:34:04.088 +08:00 [Debug] Background process 'RecurringJobScheduler' started.
2018-01-22 05:34:05.164 +08:00 [Debug] Removing outdated records from the 'Job' table...
2018-01-22 05:34:05.191 +08:00 [Debug] Removing outdated records from the 'List' table...
2018-01-22 05:34:05.192 +08:00 [Debug] Removing outdated records from the 'Set' table...
2018-01-22 05:34:05.194 +08:00 [Debug] Removing outdated records from the 'Hash' table...
2018-01-22 05:34:37.802 +08:00 [Error] Could not test CP
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Peer certificate cannot be authenticated with given CA certificates
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.OmbiHttpClient.<SendAsync>d__5.MoveNext() in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Api.<Request>d__6`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 34
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.CouchPotato.CouchPotatoApi.<Status>d__4.MoveNext() in C:\projects\requestplex\src\Ombi.Api.CouchPotato\CouchPotatoApi.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<CouchPotato>d__59.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 319
2018-01-22 05:34:42.426 +08:00 [Error] Could not test CP
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Peer certificate cannot be authenticated with given CA certificates
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.OmbiHttpClient.<SendAsync>d__5.MoveNext() in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Api.<Request>d__6`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 34
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.CouchPotato.CouchPotatoApi.<Status>d__4.MoveNext() in C:\projects\requestplex\src\Ombi.Api.CouchPotato\CouchPotatoApi.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<CouchPotato>d__59.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 319
`

**Comment by jamjop** [comment]
Does couch potato still work?

**Comment by tidusjar** [comment]
Hmm instresting...

Can you try the following?

Grab a copy of the latest libcurl compiled with openssl support:

`brew install curl --with-openssl`
You probably don't want to force the entire OS to use the non-Apple version of libcurl, so you'll likely want to use the `DYLD_LIBRARY_PATH` environment variable instead of using brew to force link the binaries into the regular path of the OS.

`export DYLD_LIBRARY_PATH=/usr/local/opt/curl/lib${DYLD_LIBRARY_PATH:+:$DYLD_LIBRARY_PATH}`

Restart Ombi and then try (with the ignore certificates enabled)

**Comment by weisheng** [comment]
```

2018-01-22 17:02:26.107 +08:00 [Information] Start installing Hangfire SQL objects...
2018-01-22 17:02:26.174 +08:00 [Information] Hangfire SQL objects installed.
2018-01-22 17:02:26.204 +08:00 [Information] Starting Hangfire Server
2018-01-22 17:02:26.207 +08:00 [Information] Using job storage: 'SQLite Server: Schedules.db'
2018-01-22 17:02:26.207 +08:00 [Information] Using the following options for Hangfire Server:
2018-01-22 17:02:26.207 +08:00 [Information]     Worker count: 1
2018-01-22 17:02:26.207 +08:00 [Information]     Listening queues: 'default'
2018-01-22 17:02:26.207 +08:00 [Information]     Shutdown timeout: 1.00:00:00
2018-01-22 17:02:26.207 +08:00 [Information]     Schedule polling interval: 00:00:15
2018-01-22 17:02:26.217 +08:00 [Debug] Background process 'BackgroundProcessingServer' started.
2018-01-22 17:02:26.358 +08:00 [Debug] Background process 'ServerHeartbeat' started.
2018-01-22 17:02:26.358 +08:00 [Debug] Background process 'ServerWatchdog' started.
2018-01-22 17:02:26.358 +08:00 [Debug] Background process 'Hangfire.SQLite.ExpirationManager' started.
2018-01-22 17:02:26.359 +08:00 [Debug] Background process 'Worker #fa7660f0' started.
2018-01-22 17:02:26.361 +08:00 [Debug] Background process 'DelayedJobScheduler' started.
2018-01-22 17:02:26.362 +08:00 [Debug] Background process 'RecurringJobScheduler' started.
2018-01-22 17:02:26.363 +08:00 [Debug] Removing outdated records from the 'AggregatedCounter' table...
2018-01-22 17:02:27.435 +08:00 [Debug] Removing outdated records from the 'Job' table...
2018-01-22 17:02:27.451 +08:00 [Debug] Removing outdated records from the 'List' table...
2018-01-22 17:02:27.452 +08:00 [Debug] Removing outdated records from the 'Set' table...
2018-01-22 17:02:27.453 +08:00 [Debug] Removing outdated records from the 'Hash' table...
2018-01-22 17:02:56.694 +08:00 [Error] Could not test CP
System.PlatformNotSupportedException: The handler does not support custom handling of certificates with this combination of libcurl (7.54.0) and its SSL backend ("LibreSSL/2.0.20").
   at System.Net.Http.CurlHandler.SslProvider.SetSslOptions(EasyRequest easy, ClientCertificateOption clientCertOption)
   at System.Net.Http.CurlHandler.EasyRequest.InitializeCurl()
   at System.Net.Http.CurlHandler.MultiAgent.ActivateNewRequest(EasyRequest easy)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.OmbiHttpClient.<SendAsync>d__5.MoveNext() in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Api.<Request>d__6`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 34
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.CouchPotato.CouchPotatoApi.<Status>d__4.MoveNext() in C:\projects\requestplex\src\Ombi.Api.CouchPotato\CouchPotatoApi.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<CouchPotato>d__59.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 319

```

**Comment by tidusjar** [comment]
Well the differences between v2 and v3 are huge, we have swapped out the backend technology so we no longer need mono.

But it looks like this configuration is not compatible to use custom certificate callbacks (to ignore certificate errors): https://github.com/dotnet/corefx/issues/9728

The only thing I can currently suggest is that you fix the certificate you are using.

I cannot do anything more until the .net framework add the ability to handle custom certificate callbacks on those versions of libcurl on macOS.
