### ISSUE TITLE
Welcome email wont send

### ISSUE THREAD

**Issue by sfranke89** [tidusjar/Ombi#1920]
#### Ombi build Version:

V 3.0.2742

#### Update Branch:

DotNetCore

#### Media Sever:

Plex/Emby

#### Operating System:

Windows10

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2018-01-22 15:07:02.554 -06:00 [Warning] Exception when testing Email Notifications
System.InvalidOperationException: 5.7.1 Unable to relay
   at Ombi.Notifications.GenericEmailProvider.<SendAdHoc>d__5.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 94
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<Email>d__54.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 214

```

#### Problem Description:

Test emails will go through but not the welcome email. If i put in Gmail settings everything works just fine. My internal exchange server works but not thru ombi

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by sfranke89** [comment]
i should note that it did work in v2

**Comment by PotatoQuality** [comment]
5.7.1 Unable to relay is comming from your exchange server.
Check your config on your exchange server pleas.
