### ISSUE TITLE
Docker rebooting over and over and not starting

### ISSUE THREAD

**Issue by ajhong2** [tidusjar/Ombi#1924]
#### Ombi build Version:

V 3.0? Latest from the docker.

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Unraid/Docker

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```


ErrorWarningSystemArrayLogin

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...

-------------------------------------
_ ()
| | ___ _ __
| | / __| | | / \
| | \__ \ | | | () |
|_| |___/ |_| \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donations/
-------------------------------------
GID/UID
-------------------------------------

User uid: 99
User gid: 100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
[cont-init.d] 30-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Hello, welcome to Ombi
Valid options are:
Ombi 3.0.2768-DotNetCore
Copyright (C) 2018 Ombi

-h, --host (Default: http://*:5000) Set to a semicolon-separated (;)
list of URL prefixes to which the server should respond. For
example, http://localhost:123. Use "*" to indicate that the
server should listen for requests on any IP address or
hostname using the specified port and protocol (for example,
http://*:5000). The protocol (http:// or https://) must be
included with each URL. Supported formats vary between
servers.

-s, --storage Storage path, where we save the logs and database

--help Display this help screen.

--version Display version information.



We are running on

i
[40m[32minfo[39m[22m[49m: Hangfire.SQLite.SQLiteStorage[0]
Start installing Hangfire SQL objects...
[40m[32minfo[39m[22m[49m: Hangfire.SQLite.SQLiteStorage[0]
Hangfire SQL objects installed.
[40m[32minfo[39m[22m[49m: Hangfire.BackgroundJobServer[0]
Starting Hangfire Server
[40m[32minfo[39m[22m[49m: Hangfire.BackgroundJobServer[0]
Using job storage: 'SQLite Server: /config/Schedules.db'
[40m[32minfo[39m[22m[49m: Hangfire.BackgroundJobServer[0]
Using the following options for Hangfire Server:
[40m[32minfo[39m[22m[49m: Hangfire.BackgroundJobServer[0]
Worker count: 1
[40m[32minfo[39m[22m[49m: Hangfire.BackgroundJobServer[0]
Listening queues: 'default'
[40m[32minfo[39m[22m[49m: Hangfire.BackgroundJobServer[0]
Shutdown timeout: 1.00:00:00
[40m[32minfo[39m[22m[49m: Hangfire.BackgroundJobServer[0]
Schedule polling interval: 00:00:15
[40m[37mdbug[39m[22m[49m: Hangfire.Server.BackgroundProcessingServer[0]
Background process 'BackgroundProcessingServer' started.
[40m[37mdbug[39m[22m[49m: Hangfire.Server.ServerHeartbeat[0]
Background process 'ServerHeartbeat' started.
[40m[37mdbug[39m[22m[49m: Hangfire.Server.ServerWatchdog[0]
Background process 'ServerWatchdog' started.
[40m[37mdbug[39m[22m[49m: Hangfire.SQLite.ExpirationManager[0]
Background process 'Hangfire.SQLite.ExpirationManager' started.
[40m[37mdbug[39m[22m[49m: Hangfire.Server.Worker[0]
Background process 'Worker #b0f2ada3' started.
[40m[37mdbug[39m[22m[49m: Hangfire.Server.DelayedJobScheduler[0]
Background process 'DelayedJobScheduler' started.
[40m[37mdbug[39m[22m[49m: Hangfire.Server.RecurringJobScheduler[0]
Background process 'RecurringJobScheduler' started.
[40m[37mdbug[39m[22m[49m: Hangfire.SQLite.ExpirationManager[0]
Removing outdated records from the 'AggregatedCounter' table...
[40m[37mdbug[39m[22m[49m: Hangfire.SQLite.ExpirationManager[0]
Removing outdated records from the 'Job' table...
[40m[37mdbug[39m[22m[49m: Hangfire.SQLite.ExpirationManager[0]
Removing outdated records from the 'List' table...
[40m[37mdbug[39m[22m[49m: Hangfire.SQLite.ExpirationManager[0]
Removing outdated records from the 'Set' table...
[40m[37mdbug[39m[22m[49m: Hangfire.SQLite.ExpirationManager[0]
Removing outdated records from the 'Hash' table...

Unhandled Exception: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
at Ombi.Store.Context.OmbiContext.Seed() in C:\projects\requestplex\src\Ombi.Store\Context\OmbiContext.cs:line 196
at Ombi.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IMemoryCache cache, IServiceProvider serviceProvider) in C:\projects\requestplex\src\Ombi\Startup.cs:line 188
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
at Ombi.Program.Main(String[] args) in C:\projects\requestplex\src\Ombi\Program.cs:line 64
Hello, welcome to Ombi
Valid options are:
Ombi 3.0.2768-DotNetCore
Copyright (C) 2018 Ombi

-h, --host (Default: http://*:5000) Set to a semicolon-separated (;)
list of URL prefixes to which the server should respond. For
example, http://localhost:123. Use "*" to indicate that the
server should listen for requests on any IP address or
hostname using the specified port and protocol (for example,
http://*:5000). The protocol (http:// or https://) must be
included with each URL. Supported formats vary between
servers.

-s, --storage Storage path, where we save the logs and database

--help Display this help screen.

--version Display version information.



We are running on

i
[40m[32minfo[39m[22m[49m: Hangfire.SQLite.SQLiteStorage[0]
Start installing Hangfire SQL objects...
[40m[32minfo[39m[22m[49m: Hangfire.SQLite.SQLiteStorage[0]
Hangfire SQL objects installed.
[40m[32minfo[39m[22m[49m: Hangfire.BackgroundJobServer[0]
Starting Hangfire Server
[40m[32minfo[39m[22m[49m: Hangfire.BackgroundJobServer[0]
Using job storage: 'SQLite Server: /config/Schedules.db'
[40m[32minfo[39m[22m[49m: Hangfire.BackgroundJobServer[0]
Using the following options for Hangfire Server:
[40m[32minfo[39m[22m[49m: Hangfire.BackgroundJobServer[0]
Worker count: 1
[40m[32minfo[39m[22m[49m: Hangfire.BackgroundJobServer[0]
Listening queues: 'default'
[40m[32minfo[39m[22m[49m: Hangfire.BackgroundJobServer[0]
Shutdown timeout: 1.00:00:00
[40m[32minfo[39m[22m[49m: Hangfire.BackgroundJobServer[0]
Schedule polling interval: 00:00:15
[40m[37mdbug[39m[22m[49m: Hangfire.Server.BackgroundProcessingServer[0]
Background process 'BackgroundProcessingServer' started.
[40m[37mdbug[39m[22m[49m: Hangfire.Server.ServerHeartbeat[0]
Background process 'ServerHeartbeat' started.
[40m[37mdbug[39m[22m[49m: Hangfire.Server.ServerWatchdog[0]
Background process 'ServerWatchdog' started.
[40m[37mdbug[39m[22m[49m: Hangfire.SQLite.ExpirationManager[0]
Background process 'Hangfire.SQLite.ExpirationManager' started.
[40m[37mdbug[39m[22m[49m: Hangfire.Server.DelayedJobScheduler[0]
Background process 'DelayedJobScheduler' started.
[40m[37mdbug[39m[22m[49m: Hangfire.Server.Worker[0]
Background process 'Worker #e9632344' started.
[40m[37mdbug[39m[22m[49m: Hangfire.Server.RecurringJobScheduler[0]
Background process 'RecurringJobScheduler' started.
[40m[37mdbug[39m[22m[49m: Hangfire.SQLite.ExpirationManager[0]
Removing outdated records from the 'AggregatedCounter' table...
[40m[37mdbug[39m[22m[49m: Hangfire.SQLite.ExpirationManager[0]
Removing outdated records from the 'Job' table...
[40m[37mdbug[39m[22m[49m: Hangfire.SQLite.ExpirationManager[0]
Removing outdated records from the 'List' table...
[40m[37mdbug[39m[22m[49m: Hangfire.SQLite.ExpirationManager[0]
Removing outdated records from the 'Set' table...
[40m[37mdbug[39m[22m[49m: Hangfire.SQLite.ExpirationManager[0]
Removing outdated records from the 'Hash' table...

Unhandled Exception: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
at Ombi.Store.Context.OmbiContext.Seed() in C:\projects\requestplex\src\Ombi.Store\Context\OmbiContext.cs:line 196
at Ombi.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IMemoryCache cache, IServiceProvider serviceProvider) in C:\projects\requestplex\src\Ombi\Startup.cs:line 188
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
at Ombi.Program.Main(String[] args) in C:\projects\requestplex\src\Ombi\Program.cs:line 64
Hello, welcome to Ombi
Valid options are:
Ombi 3.0.2768-DotNetCore
Copyright (C) 2018 Ombi

-h, --host (Default: http://*:5000) Set to a semicolon-separated (;)
list of URL prefixes to which the server should respond. For
example, http://localhost:123. Use "*" to indicate that the
server should listen for requests on any IP address or
hostname using the specified port and protocol (for example,
http://*:5000). The protocol (http:// or https://) must be
included with each URL. Supported formats vary between
servers.

-s, --storage Storage path, where we save the logs and database

--help Display this help screen.

--version Display version information.



[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

```
[log-20180123.txt](https://github.com/tidusjar/Ombi/files/1658570/log-20180123.txt)

#### Problem Description:

Docker restarts over and over. I have deleted both Ombi.db and Schedules.db as well as done a fresh install with a new appdata directory.

#### Reproduction Steps:

Fresh install? Not entirely sure.

**Comment by CoderKiwi** [comment]
I was just about to file an issue for this. I'm getting the exact same issue. 

I deleted all files and the container and etc., redownloaded the image and ran it via clean install. So there are zero settings configured from me (other than Docker env vars).

I get the same exceptions as above.

**Comment by designgears** [comment]
Came here to file the same report, tested on a clean install as well, same issue.

**Comment by Admin9705** [comment]
We posted it as an article for others! Thanks @designgears for the heads up! @tidusjar hey, it's Eric! Keep up the good work with ombi 3!
