### ISSUE TITLE
Ombi v3 will not update on QNAP

### ISSUE THREAD

**Issue by ckersey2** [tidusjar/Ombi#1926]
#### Ombi build Version:

V 3.0.2450

#### Update Branch:

DotNetCore

#### Media Sever:

Plex

#### Media Server Version:

1.11.0.4666

#### Operating System:

QNAP Firmware Version 4.3.4.0435

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2018-01-23 22:03:20.928 -05:00 [Warning] Failed to process the job '16': an exception occurred. Retry attempt 1 of 1 will be performed in 00:00:44.
System.ComponentModel.Win32Exception (0x80004005): Permission denied
   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 220
2018-01-23 22:04:10.748 -05:00 [Information] 1 scheduled job(s) enqueued.
2018-01-23 22:05:21.793 -05:00 [Error] Failed to process the job '16': an exception occurred.
System.ComponentModel.Win32Exception (0x80004005): Permission denied
   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 220
2018-01-23 22:25:03.888 -05:00 [Warning] Failed to process the job '29': an exception occurred. Retry attempt 1 of 1 will be performed in 00:00:43.
System.ComponentModel.Win32Exception (0x80004005): Permission denied
   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 220
2018-01-23 22:25:59.159 -05:00 [Information] 1 scheduled job(s) enqueued.

```

#### Problem Description:

I have Ombi v3 installed on my QNAP NAS. It says there is an update. When I click update it says that it kicks off the job but it looks like it fails in the logs and never updates. I even tried to use a scheduled job through Ombi and it did not work.

#### Reproduction Steps:

Either click update from System>Update or set a scheduled update job from the Jobs page.

**Comment by tidusjar** [comment]
Yeah I'm aware of this. These issues are in the update issue.

**Comment by ckersey2** [comment]
How do I install the update?

**Comment by tidusjar** [comment]
To manually do it you need to overwrite all the files with the latest zip. 
But with qnap I know a specific package is created. So I guess you'll have to create a new package with the latest binaries.

**Comment by slimshizn** [comment]
https://qnapclub.eu/en/qpkg/487

**Comment by tidusjar** [comment]
That is very out of date

**Comment by slimshizn** [comment]
Unfortunately that is all I could find for QNAP users. I tried the update feature on it and it says its “up to date”. Thanks for the quick reply.

**Comment by WeirDave** [comment]
This thread explains to me why I can't get this to work! Now if I can find a tutorial on creating a QNAP package from the latest binaries I would give it a try.

**Comment by slimshizn** [comment]
Just install one that you find and copy paste the updated files over to
your ombi directory. Works fine I'm on the latest.

**Comment by WeirDave** [comment]
> 
Just install one that you find and copy paste the updated files over to your ombi directory. Works fine I'm on the latest.

>

**Comment by WeirDave** [comment]
Can you give me just a bit more information on how I can do this? It's been quite a while for me to be back in the linux world but I'd like to try
