### ISSUE TITLE
Microsoft.Data.Sqlite.SqliteException

### ISSUE THREAD

**Issue by jthomisee** [tidusjar/Ombi#1946]
#### Ombi build Version:

V 3.0.2842-DotNetCore

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Ubuntu 16.04

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

Feb 02 17:56:38 media Ombi[4525]: Unhandled Exception: Microsoft.Data.Sqlite.SqliteException: SQLite Error 19: 'FOREIGN KEY constraint failed'.
Feb 02 17:56:38 media Ombi[4525]:    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
Feb 02 17:56:38 media Ombi[4525]:    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
Feb 02 17:56:38 media Ombi[4525]:    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
Feb 02 17:56:38 media Ombi[4525]:    at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 para
Feb 02 17:56:38 media Ombi[4525]:    at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
Feb 02 17:56:38 media Ombi[4525]:    at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
Feb 02 17:56:38 media Ombi[4525]:    at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
Feb 02 17:56:38 media Ombi[4525]:    at Ombi.Program.Main(String[] args) in C:\projects\requestplex\src\Ombi\Program.cs:line 40

```

#### Problem Description:

Upgraded to 3.0.2842 and seeing the above error on service start and then crashes

#### Reproduction Steps:

Upgrade to 3.0.2842 and start the service

**Comment by tidusjar** [comment]
There is a build currently in progress that will fix this. Try and update in about 20 mins

**Comment by jthomisee** [comment]
Confirmed fixed. thanks
