### ISSUE TITLE
Updated To Latest Version - Ombi Wont Load

### ISSUE THREAD

**Issue by Migz93** [tidusjar/Ombi#1963]
#### Ombi build Version:

V 3.0.2879

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

N/A

#### Operating System:

Debian Linux 9.0

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):
No idea if these logs are even applicable, but it's the only section of error in a 200 line log.
```

2018-02-11 02:19:14.583 +00:00 [Information] Start installing Hangfire SQL objects...
2018-02-11 02:19:14.764 +00:00 [Information] Hangfire SQL objects installed.
2018-02-11 02:19:14.839 +00:00 [Information] Starting Hangfire Server
2018-02-11 02:19:14.848 +00:00 [Information] Using job storage: 'SQLite Server: Schedules.db'
2018-02-11 02:19:14.848 +00:00 [Information] Using the following options for Hangfire Server:
2018-02-11 02:19:14.848 +00:00 [Information]     Worker count: 1
2018-02-11 02:19:14.849 +00:00 [Information]     Listening queues: 'default'
2018-02-11 02:19:14.849 +00:00 [Information]     Shutdown timeout: 1.00:00:00
2018-02-11 02:19:14.849 +00:00 [Information]     Schedule polling interval: 00:00:15
2018-02-11 02:19:14.872 +00:00 [Debug] Background process 'BackgroundProcessingServer' started.
2018-02-11 02:19:15.322 +00:00 [Debug] Background process 'ServerHeartbeat' started.
2018-02-11 02:19:15.326 +00:00 [Debug] Background process 'ServerWatchdog' started.
2018-02-11 02:19:15.330 +00:00 [Debug] Background process 'Worker #3d131173' started.
2018-02-11 02:19:15.332 +00:00 [Debug] Background process 'DelayedJobScheduler' started.
2018-02-11 02:19:15.340 +00:00 [Debug] Background process 'Hangfire.SQLite.ExpirationManager' started.
2018-02-11 02:19:15.361 +00:00 [Debug] Background process 'RecurringJobScheduler' started.
2018-02-11 02:19:15.361 +00:00 [Debug] Removing outdated records from the 'AggregatedCounter' table...
2018-02-11 02:19:16.419 +00:00 [Debug] Removing outdated records from the 'Job' table...
2018-02-11 02:19:16.602 +00:00 [Debug] Removing outdated records from the 'List' table...
2018-02-11 02:19:16.631 +00:00 [Debug] Removing outdated records from the 'Set' table...
2018-02-11 02:19:16.672 +00:00 [Debug] Removing outdated records from the 'Hash' table...
2018-02-11 02:20:36.259 +00:00 [Warning] Failed to process the job '2': an exception occurred. Retry attempt 1 of 3 will be performed in 00:00:33.
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.<ExecuteDbDataReaderAsync>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.<ExecuteAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<BufferlessMoveNext>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<MoveNext>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Linq.AsyncEnumerable.<FirstOrDefault_>d__165`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.<MoveNext>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<ExecuteSingletonAsyncQuery>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Store.Repository.SettingsJsonRepository.<GetAsync>d__8.MoveNext() in C:\projects\requestplex\src\Ombi.Store\Repository\SettingsJsonRepository.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Settings.Settings.SettingsService`1.<<GetSettingsAsync>b__11_0>d.MoveNext() in C:\projects\requestplex\src\Ombi.Settings\Settings\SettingsService.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Helpers.CacheService.<GetOrAdd>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Settings.Settings.SettingsService`1.<GetSettingsAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.<CacheContent>d__16.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 66

```

#### Problem Description:

There was an available update earlier which i ran the update_ombi.sh script located here
https://github.com/Unimatrix0/update_ombi

Once the update complete i was then unable to access Ombi, i tried through my nginx proxy and then locally through the IP but neither worked. I confirmed the service was running.
After multiple reboots of the server and the service i backed up my /opt/Ombi folder, wiped everything from it and redownloaded Ombi. This seemed to load as i was shown the initial set up Ombi screen. I then stopped Ombi, copied my backed up Ombi.db file back so that it would have all my set up and requests, started Ombi and then i get the same issue as before of it not loading.

#### Reproduction Steps:

Fresh install of latest version of Ombi works fine, copy my Ombi.db from an older version and then Ombi doesn't work :(

**Comment by Migz93** [comment]
It turns out Ombi does eventually load, rebooted my server once more to try before getting into bed. Ombi still didn't work, a little while later I get a notification to say Ombi was responding and can confirm it's now up. Checked the VM ombi is running in and its been up for 13 minutes, I don't remember Ombi ever taking this long to initially load? If that is normal though then please feel free to close this off.

**Comment by tidusjar** [comment]
Looks like there was some sort of process locking the database. So it couldn't read from it. Not sure what I can do about this since that's out of my control.

**Comment by Migz93** [comment]
No problem, as i said it eventually loaded anyway which might have been expected behaviour, i've never tried to laod Ombi straight after restarting/
