### ISSUE TITLE
Permission denied when running automatic updater

### ISSUE THREAD

**Issue by erodewald** [tidusjar/Ombi#1979]
#### Ombi build Version:

V 3.0.2820

#### Update Branch:

Open Beta

#### Operating System:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial
```

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
System.ComponentModel.Win32Exception (0x80004005): Permission denied
   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 227

```

#### Problem Description:

Should auto update without an exception

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
https://github.com/tidusjar/Ombi/issues/1460
