### ISSUE TITLE
Ombi crash after auto update (System.FormatException: Unrecognized argument format)

### ISSUE THREAD

**Issue by PotatoQuality** [tidusjar/Ombi#1989]
#### Ombi build Version:

V 3.0.2896

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

1.1

#### Operating System:

Windows 10

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
 =======================================
        Starting the Ombi Updater
 =======================================
[8480]: Killing process
[8480]: Waiting for exit
[8480]: Process terminated successfully
Found 0 processes with the name: Ombi
Hello, welcome to Ombi
Valid options are:
Ombi 3.0.2896-DotNetCore
Copyright (C) 2018 Ombi

  -h, --host       (Default: http://*:5000) Set to a semicolon-separated (;)
                   list of URL prefixes to which the server should respond. For
                   example, http://localhost:123. Use "*" to indicate that the
                   server should listen for requests on any IP address or
                   hostname using the specified port and protocol (for example,
                   http://*:5000). The protocol (http:// or https://) must be
                   included with each URL. Supported formats vary between
                   servers.

  -s, --storage    Storage path, where we save the logs and database

  --help           Display this help screen.

  --version        Display version information.



We are running on

Unhandled Exception: System.FormatException: Unrecognized argument format: 'http://*:5000'.
   at Microsoft.Extensions.Configuration.CommandLine.CommandLineConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Ombi.Program.Main(String[] args) in C:\projects\requestplex\src\Ombi\Program.cs:line 70


```

#### Problem Description:

After auto update, ombi crash

#### Reproduction Steps:

auto update

**Comment by tidusjar** [comment]
Auto update is actually working for you?

**Comment by PotatoQuality** [comment]
@tidusjar Yes :)

**Comment by tidusjar** [comment]
Can you download this build: https://ci.appveyor.com/project/tidusjar/requestplex/build/3.0.2902

There is an update, can you use the inbuilt updater to update to 3.0.2903?

**Comment by halali** [comment]
had same error, and now it work for me
