### ISSUE TITLE
Plex Cacher not logging anything / not working.

### ISSUE THREAD

**Issue by bagobones** [tidusjar/Ombi#1990]
#### Ombi build Version:

V 3.0.2896

lsiodev/ombi-preview docker

#### Media Sever:

Plex

#### Media Server Version:

1.11.3.4803

#### Operating System:

Linux / Synology/ Docker

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2018-02-18 22:28:59.404 -08:00 [Information] Start installing Hangfire SQL objects...
2018-02-18 22:28:59.576 -08:00 [Information] Hangfire SQL objects installed.
2018-02-18 22:28:59.662 -08:00 [Information] Starting Hangfire Server
2018-02-18 22:28:59.674 -08:00 [Information] Using job storage: 'SQLite Server: /config/Schedules.db'
2018-02-18 22:28:59.674 -08:00 [Information] Using the following options for Hangfire Server:
2018-02-18 22:28:59.675 -08:00 [Information]     Worker count: 1
2018-02-18 22:28:59.676 -08:00 [Information]     Listening queues: 'default'
2018-02-18 22:28:59.676 -08:00 [Information]     Shutdown timeout: 1.00:00:00
2018-02-18 22:28:59.676 -08:00 [Information]     Schedule polling interval: 00:00:15
2018-02-18 22:28:59.705 -08:00 [Debug] Background process 'BackgroundProcessingServer' started.
2018-02-18 22:29:00.964 -08:00 [Debug] Background process 'ServerHeartbeat' started.
2018-02-18 22:29:00.966 -08:00 [Debug] Background process 'ServerWatchdog' started.
2018-02-18 22:29:00.975 -08:00 [Debug] Background process 'Hangfire.SQLite.ExpirationManager' started.
2018-02-18 22:29:00.980 -08:00 [Debug] Background process 'Worker #c8dd3e9d' started.
2018-02-18 22:29:00.990 -08:00 [Debug] Removing outdated records from the 'AggregatedCounter' table...
2018-02-18 22:29:00.992 -08:00 [Debug] Background process 'RecurringJobScheduler' started.
2018-02-18 22:29:00.992 -08:00 [Debug] Background process 'DelayedJobScheduler' started.
2018-02-18 22:29:01.452 -08:00 [Debug] Removing outdated records from the 'Job' table...
2018-02-18 22:29:02.938 -08:00 [Debug] Removing outdated records from the 'List' table...
2018-02-18 22:29:02.943 -08:00 [Debug] Removing outdated records from the 'Set' table...
2018-02-18 22:29:04.297 -08:00 [Debug] Removing outdated records from the 'Hash' table...
2018-02-18 22:36:24.106 -08:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/300022
2018-02-18 22:36:24.098 -08:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/295859
2018-02-18 22:36:24.250 -08:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/338798

```

NOTE following the fan art TV URLS shows the following. I suspect we need to have individual API keys to make larger numbers of queries to this service.

```
{
    "status": "error",
    "error message": "API key is required"
}
```

#### Problem Description:

Caching / checking for plex content seems to have stopped working without error. I have removed and re-added the plex server, the TEST button always works, and the manual cache button triggers but leaves no logs indicating it is doing anything.

**Comment by tidusjar** [comment]
Is Plex enabled?

**Comment by bagobones** [comment]
Yes the "Enable" check box is checked., the test button for the connection works. However the manual run seems to do nothing in the logs, and the scheduled task does not seem to also run.

I would scrub it all and start over but I have a few users now and requests pending, so I would prefer not to slam the reset button.

**Comment by tidusjar** [comment]
Can you delete the schedule.db

**Comment by bagobones** [comment]
Did, restarted, it recreated but still not seeing anything new in the logs.

Also by restarting the docker I am now running 3.0.2900
```
2018-02-19 11:33:35.244 -08:00 [Information] Start installing Hangfire SQL objects...
2018-02-19 11:33:47.884 -08:00 [Information] Hangfire SQL objects installed.
2018-02-19 11:33:47.965 -08:00 [Information] Starting Hangfire Server
2018-02-19 11:33:47.974 -08:00 [Information] Using job storage: 'SQLite Server: /config/Schedules.db'
2018-02-19 11:33:47.974 -08:00 [Information] Using the following options for Hangfire Server:
2018-02-19 11:33:47.975 -08:00 [Information]     Worker count: 1
2018-02-19 11:33:47.975 -08:00 [Information]     Listening queues: 'default'
2018-02-19 11:33:47.976 -08:00 [Information]     Shutdown timeout: 1.00:00:00
2018-02-19 11:33:47.976 -08:00 [Information]     Schedule polling interval: 00:00:15
2018-02-19 11:33:48.012 -08:00 [Debug] Background process 'BackgroundProcessingServer' started.
2018-02-19 11:33:49.280 -08:00 [Debug] Background process 'ServerHeartbeat' started.
2018-02-19 11:33:49.284 -08:00 [Debug] Background process 'ServerWatchdog' started.
2018-02-19 11:33:49.285 -08:00 [Debug] Background process 'Hangfire.SQLite.ExpirationManager' started.
2018-02-19 11:33:49.297 -08:00 [Debug] Background process 'Worker #ef8dd813' started.
2018-02-19 11:33:49.302 -08:00 [Debug] Background process 'DelayedJobScheduler' started.
2018-02-19 11:33:49.307 -08:00 [Debug] Background process 'RecurringJobScheduler' started.
2018-02-19 11:33:49.316 -08:00 [Debug] Removing outdated records from the 'AggregatedCounter' table...
2018-02-19 11:33:50.168 -08:00 [Debug] Removing outdated records from the 'Job' table...
2018-02-19 11:33:50.192 -08:00 [Debug] Removing outdated records from the 'List' table...
2018-02-19 11:33:50.195 -08:00 [Debug] Removing outdated records from the 'Set' table...
2018-02-19 11:33:50.198 -08:00 [Debug] Removing outdated records from the 'Hash' table...
2018-02-19 11:36:07.745 -08:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/300022
2018-02-19 11:36:07.744 -08:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/295859
2018-02-19 11:36:07.962 -08:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/338798
2018-02-19 12:03:50.202 -08:00 [Debug] Removing outdated records from the 'AggregatedCounter' table...
2018-02-19 12:03:50.237 -08:00 [Debug] Removing outdated records from the 'Job' table...
2018-02-19 12:03:50.258 -08:00 [Debug] Removing outdated records from the 'List' table...
2018-02-19 12:03:50.280 -08:00 [Debug] Removing outdated records from the 'Set' table...
2018-02-19 12:03:50.293 -08:00 [Debug] Removing outdated records from the 'Hash' table...
2018-02-19 12:33:50.311 -08:00 [Debug] Removing outdated records from the 'AggregatedCounter' table...
2018-02-19 12:33:50.317 -08:00 [Debug] Removing outdated records from the 'Job' table...
2018-02-19 12:33:50.319 -08:00 [Debug] Removing outdated records from the 'List' table...
2018-02-19 12:33:50.322 -08:00 [Debug] Removing outdated records from the 'Set' table...
2018-02-19 12:33:50.339 -08:00 [Debug] Removing outdated records from the 'Hash' table...
2018-02-19 13:03:50.341 -08:00 [Debug] Removing outdated records from the 'AggregatedCounter' table...
2018-02-19 13:03:50.368 -08:00 [Debug] Removing outdated records from the 'Job' table...
2018-02-19 13:03:50.403 -08:00 [Debug] Removing outdated records from the 'List' table...
2018-02-19 13:03:50.408 -08:00 [Debug] Removing outdated records from the 'Set' table...
2018-02-19 13:03:50.444 -08:00 [Debug] Removing outdated records from the 'Hash' table...
2018-02-19 13:33:50.509 -08:00 [Debug] Removing outdated records from the 'AggregatedCounter' table...
2018-02-19 13:33:50.517 -08:00 [Debug] Removing outdated records from the 'Job' table...
2018-02-19 13:33:50.520 -08:00 [Debug] Removing outdated records from the 'List' table...
2018-02-19 13:33:50.526 -08:00 [Debug] Removing outdated records from the 'Set' table...
2018-02-19 13:33:50.532 -08:00 [Debug] Removing outdated records from the 'Hash' table...
2018-02-19 14:03:50.534 -08:00 [Debug] Removing outdated records from the 'AggregatedCounter' table...
2018-02-19 14:03:50.566 -08:00 [Debug] Removing outdated records from the 'Job' table...
2018-02-19 14:03:50.569 -08:00 [Debug] Removing outdated records from the 'List' table...
2018-02-19 14:03:50.576 -08:00 [Debug] Removing outdated records from the 'Set' table...
2018-02-19 14:03:50.594 -08:00 [Debug] Removing outdated records from the 'Hash' table...
2018-02-19 14:33:50.595 -08:00 [Debug] Removing outdated records from the 'AggregatedCounter' table...
2018-02-19 14:33:50.597 -08:00 [Debug] Removing outdated records from the 'Job' table...
2018-02-19 14:33:50.599 -08:00 [Debug] Removing outdated records from the 'List' table...
2018-02-19 14:33:50.601 -08:00 [Debug] Removing outdated records from the 'Set' table...
2018-02-19 14:33:50.603 -08:00 [Debug] Removing outdated records from the 'Hash' table...
2018-02-19 15:03:50.605 -08:00 [Debug] Removing outdated records from the 'AggregatedCounter' table...
2018-02-19 15:03:50.606 -08:00 [Debug] Removing outdated records from the 'Job' table...
2018-02-19 15:03:50.608 -08:00 [Debug] Removing outdated records from the 'List' table...
2018-02-19 15:03:50.610 -08:00 [Debug] Removing outdated records from the 'Set' table...
2018-02-19 15:03:50.611 -08:00 [Debug] Removing outdated records from the 'Hash' table...
2018-02-19 15:33:50.613 -08:00 [Debug] Removing outdated records from the 'AggregatedCounter' table...
2018-02-19 15:33:50.714 -08:00 [Debug] Removing outdated records from the 'Job' table...
2018-02-19 15:33:50.716 -08:00 [Debug] Removing outdated records from the 'List' table...
2018-02-19 15:33:50.729 -08:00 [Debug] Removing outdated records from the 'Set' table...
2018-02-19 15:33:50.741 -08:00 [Debug] Removing outdated records from the 'Hash' table...
2018-02-19 16:03:50.742 -08:00 [Debug] Removing outdated records from the 'AggregatedCounter' table...
2018-02-19 16:03:50.744 -08:00 [Debug] Removing outdated records from the 'Job' table...
2018-02-19 16:03:50.746 -08:00 [Debug] Removing outdated records from the 'List' table...
2018-02-19 16:03:50.747 -08:00 [Debug] Removing outdated records from the 'Set' table...
2018-02-19 16:03:50.749 -08:00 [Debug] Removing outdated records from the 'Hash' table...
2018-02-19 16:33:50.751 -08:00 [Debug] Removing outdated records from the 'AggregatedCounter' table...
2018-02-19 16:33:50.774 -08:00 [Debug] Removing outdated records from the 'Job' table...
2018-02-19 16:33:50.776 -08:00 [Debug] Removing outdated records from the 'List' table...
2018-02-19 16:33:50.777 -08:00 [Debug] Removing outdated records from the 'Set' table...
2018-02-19 16:33:50.779 -08:00 [Debug] Removing outdated records from the 'Hash' table...
2018-02-19 17:03:50.781 -08:00 [Debug] Removing outdated records from the 'AggregatedCounter' table...
2018-02-19 17:03:50.860 -08:00 [Debug] Removing outdated records from the 'Job' table...
2018-02-19 17:03:50.881 -08:00 [Debug] Removing outdated records from the 'List' table...
2018-02-19 17:03:50.909 -08:00 [Debug] Removing outdated records from the 'Set' table...
2018-02-19 17:03:50.955 -08:00 [Debug] Removing outdated records from the 'Hash' table...
2018-02-19 17:33:50.979 -08:00 [Debug] Removing outdated records from the 'AggregatedCounter' table...
2018-02-19 17:33:51.051 -08:00 [Debug] Removing outdated records from the 'Job' table...
2018-02-19 17:33:51.053 -08:00 [Debug] Removing outdated records from the 'List' table...
2018-02-19 17:33:51.060 -08:00 [Debug] Removing outdated records from the 'Set' table...
2018-02-19 17:33:51.062 -08:00 [Debug] Removing outdated records from the 'Hash' table...
2018-02-19 18:03:51.064 -08:00 [Debug] Removing outdated records from the 'AggregatedCounter' table...
2018-02-19 18:03:51.111 -08:00 [Debug] Removing outdated records from the 'Job' table...
2018-02-19 18:03:51.113 -08:00 [Debug] Removing outdated records from the 'List' table...
2018-02-19 18:03:51.120 -08:00 [Debug] Removing outdated records from the 'Set' table...
2018-02-19 18:03:51.124 -08:00 [Debug] Removing outdated records from the 'Hash' table...
2018-02-19 18:19:08.449 -08:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/300022
2018-02-19 18:19:08.452 -08:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/295859
2018-02-19 18:19:08.601 -08:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/338798
```

**Comment by tidusjar** [comment]
Anything from the docker logs or stdout?

**Comment by bagobones** [comment]
Upgraded from 3.0.2900 to 3.0.2917 and did a manual refresh..

Good news!. Movies started getting detected again and show as fulfilled!

Bad News! TV is still not working.

The logs still show little to nothing helpful.

I am running this on a Synology Docker setup so the stdout goes to a UI, I might have to dig in via SSH to get the data I want.. I have a large movie library and TV library so stdout is FULL of  "We already have movie" messages.

I was able to however find these errors, looks like episode caching is running but crashing on some content

'''
2018-02-25 20:20:21,stdout,[40m[32minfo[39m[22m[49m: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]

2018-02-25 20:19:31,stdout,"      Notification options: Ombi.Notifications.Models.NotificationOptions, Req: Ombi.Store.Entities.Requests.MovieRequests, Settings: Ombi.Settings.Settings.Models.CustomizationSettings"
2018-02-25 20:19:31,stdout,[40m[37mdbug[39m[22m[49m: Ombi.Notifications.Agents.PushoverNotification[0]

2018-02-25 20:19:31,stdout,   at Ombi.Notifications.NotificationService.<NotifyAsync>d__9.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\NotificationService.cs:line 82

2018-02-25 20:19:31,stdout,   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

2018-02-25 20:19:31,stdout,   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

2018-02-25 20:19:31,stdout,--- End of stack trace from previous location where exception was thrown ---

2018-02-25 20:19:31,stdout,   at Ombi.Notifications.Interfaces.BaseNotification`1.<NotifyAsync>d__31.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 50

2018-02-25 20:19:31,stdout,   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

2018-02-25 20:19:31,stdout,   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

2018-02-25 20:19:31,stdout,--- End of stack trace from previous location where exception was thrown ---

2018-02-25 20:19:31,stdout,   at Ombi.Notifications.Interfaces.BaseNotification`1.<NotifyAsync>d__32.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 85

2018-02-25 20:19:31,stdout,   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

2018-02-25 20:19:31,stdout,   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

2018-02-25 20:19:31,stdout,--- End of stack trace from previous location where exception was thrown ---

2018-02-25 20:19:31,stdout,   at Ombi.Notifications.Agents.EmailNotification.<AvailableRequest>d__20.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Agents\EmailNotification.cs:line 267

2018-02-25 20:19:31,stdout,   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

2018-02-25 20:19:31,stdout,   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

2018-02-25 20:19:31,stdout,--- End of stack trace from previous location where exception was thrown ---

2018-02-25 20:19:31,stdout,   at Ombi.Notifications.Agents.EmailNotification.<Send>d__21.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Agents\EmailNotification.cs:line 272

2018-02-25 20:19:31,stdout,   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

2018-02-25 20:19:31,stdout,   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

2018-02-25 20:19:31,stdout,--- End of stack trace from previous location where exception was thrown ---

2018-02-25 20:19:31,stdout,   at Ombi.Notifications.GenericEmailProvider.<Send>d__6.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 154

2018-02-25 20:19:31,stdout,"   at EnsureThat.EnsureArg.IsNotNullOrEmpty(String value, String paramName)"
2018-02-25 20:19:31,stdout,"   at EnsureThat.EnsureArg.IsNotNull[T](T value, String paramName)"
2018-02-25 20:19:31,stdout,System.ArgumentNullException: Value can not be null.

2018-02-25 20:19:31,stdout,      Failed to notify for notification: Ombi.Notifications.Agents.EmailNotification

2018-02-25 20:19:31,stdout,[41m[30mfail[39m[22m[49m: Ombi.Notifications.NotificationService[4000]

2018-02-25 20:19:31,stdout,   at Ombi.Notifications.GenericEmailProvider.<Send>d__6.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 104

2018-02-25 20:19:31,stdout,"   at EnsureThat.EnsureArg.IsNotNullOrEmpty(String value, String paramName)"
2018-02-25 20:19:31,stdout,"   at EnsureThat.EnsureArg.IsNotNull[T](T value, String paramName)"
2018-02-25 20:19:31,stdout,System.ArgumentNullException: Value can not be null.

2018-02-25 20:19:31,stdout,      Exception when attempting to send email

2018-02-25 20:19:31,stdout,[41m[30mfail[39m[22m[49m: Ombi.Notifications.GenericEmailProvider[0]

2018-02-25 20:19:28,stdout,"      Notification options: Ombi.Notifications.Models.NotificationOptions, Req: Ombi.Store.Entities.Requests.MovieRequests, Settings: Ombi.Settings.Settings.Models.CustomizationSettings"
2018-02-25 20:19:28,stdout,[40m[37mdbug[39m[22m[49m: Ombi.Notifications.Agents.EmailNotification[0]

2018-02-25 20:19:27,stdout,"      Notification options: Ombi.Notifications.Models.NotificationOptions, Req: Ombi.Store.Entities.Requests.MovieRequests, Settings: Ombi.Settings.Settings.Models.CustomizationSettings"
2018-02-25 20:19:27,stdout,[40m[37mdbug[39m[22m[49m: Ombi.Notifications.Agents.EmailNotification[0]

2018-02-25 20:19:11,stdout,      We have finished caching the episodes.

2018-02-25 20:19:11,stdout,[40m[32minfo[39m[22m[49m: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]

2018-02-25 20:19:11,stdout,      Processed 150 more episodes. Total Remaining 34
'''

**Comment by bagobones** [comment]
FYI TV episodes still don't seem to be caching / showing status in 3.0.2960.

If I have time I will delete the DB and start over, I will have to recreate some local users unfortunately.

**Comment by bagobones** [comment]
Did a full purge (deleted all files / db etc), switched to the official Linxserver IO image, version is now 3.0.2970

Shows now show the "Available" tag if you search for one that is already in plex, however individual episodes for a show do not seem to be showing "Available" when they should.

**Comment by tidusjar** [comment]
https://github.com/tidusjar/Ombi/wiki/FAQ#ombi-is-not-picking-up-tv-shows-and-episodes-as-available

**Comment by bagobones** [comment]
Confirmed that the Agent was TheTVDB as it always should have been. I do regularly keep up with Plex updates so if something is not being passed by plex in current beta/plexpass releases maybe there is something I can manually check for you.

Is there a place in the OMBI DB for me to double check as well?

I checked the XML data via plex web for the episodes as well here are two episodes, one old and one new.

```
<MediaContainer size="1" allowSync="1" identifier="com.plexapp.plugins.library" librarySectionID="2" librarySectionTitle="TV Shows" librarySectionUUID="47be6408-1bd6-4199-a665-c1819f976be2" mediaTagPrefix="/system/bundle/media/flags/" mediaTagVersion="1519709489">
<Video ratingKey="8526" key="/library/metadata/8526" parentRatingKey="8525" grandparentRatingKey="8404" guid="com.plexapp.agents.thetvdb://73871/1/1?lang=en" librarySectionTitle="TV Shows" librarySectionID="2" librarySectionKey="/library/sections/2" type="episode" title="Space Pilot 3000" grandparentKey="/library/metadata/8404" parentKey="/library/metadata/8525" grandparentTitle="Futurama" parentTitle="Season 1" contentRating="TV-14" summary="Fry, a 20th-century New-York pizza delivery boy receives a prank call and is frozen in a capsule and wakes up in year 2999. He meets an alien named Leela that wants to assign his permanent career... delivery boy. Fry refuses, so he escapes. He then meets Bender, a robot who likes to drink and has suicidal tendencies. Together, they start running away from Leela, arriving to the ruins of old New York. Leela finds them, but instead of inserting the permanent chip on Fry, she removes her own. All three go to Prof. Hubert Farnsworth's house, Fry's only living relative, becoming his new space crew." index="1" parentIndex="1" rating="8.0" year="1999" thumb="/library/metadata/8526/thumb/1507214470" parentThumb="/library/metadata/8525/thumb/1500779923" grandparentThumb="/library/metadata/8404/thumb/1466979507" duration="1294760" originallyAvailableAt="1999-03-28" addedAt="1156983929" updatedAt="1507214470">
<Media videoResolution="480" id="10091" duration="1294760" bitrate="1134" width="640" height="480" aspectRatio="1.33" audioChannels="2" audioCodec="ac3" videoCodec="mpeg4" container="avi" videoFrameRate="PAL" videoProfile="simple">
<Part accessible="1" exists="1" id="84627" key="/library/parts/84627/1156983929/file.avi" duration="1294760" file="/volume1/media/Video/TV Archive/Futurama/Season 1/Futurama - S01E01 - Space Pilot 3000.avi" size="183474176" container="avi" videoProfile="simple">
<Stream id="169974" streamType="1" codec="mpeg4" index="0" bitrate="932" bitDepth="8" chromaSubsampling="4:2:0" frameRate="25.000" height="480" level="3" profile="simple" refFrames="1" width="640"/>
<Stream id="169975" streamType="2" selected="1" codec="ac3" index="1" channels="2" bitrate="192" audioChannelLayout="stereo" samplingRate="48000" streamIdentifier="1"/>
</Part>
</Media>
<Director id="13193" filter="director=13193" tag="Rich Moore"/>
<Director id="13194" filter="director=13194" tag="Gregg Vanzo"/>
<Writer id="10586" filter="writer=10586" tag="Matt Groening"/>
<Writer id="13188" filter="writer=13188" tag="David X. Cohen"/>
<Extras size="0"></Extras>
</Video>
</MediaContainer>
```

```
<MediaContainer size="1" allowSync="1" identifier="com.plexapp.plugins.library" librarySectionID="2" librarySectionTitle="TV Shows" librarySectionUUID="47be6408-1bd6-4199-a665-c1819f976be2" mediaTagPrefix="/system/bundle/media/flags/" mediaTagVersion="1519709489">
<Video ratingKey="42990" key="/library/metadata/42990" parentRatingKey="41039" grandparentRatingKey="4021" guid="com.plexapp.agents.thetvdb://263365/5/11?lang=en" librarySectionTitle="TV Shows" librarySectionID="2" librarySectionKey="/library/sections/2" type="episode" title="All the Comforts of Home" grandparentKey="/library/metadata/4021" parentKey="/library/metadata/41039" grandparentTitle="Marvel's Agents of S.H.I.E.L.D." parentTitle="Season 5" contentRating="TV-PG" summary="Coulson and the team set out to rewrite the course of humanity's fate; they're unaware that their efforts will dramatically change one S.H.I.E.L.D. agent's life." index="11" parentIndex="5" viewCount="2" lastViewedAt="1520062394" year="2018" thumb="/library/metadata/42990/thumb/1520047437" art="/library/metadata/4021/art/1520047439" parentThumb="/library/metadata/41039/thumb/1520047439" grandparentThumb="/library/metadata/4021/thumb/1520047439" grandparentArt="/library/metadata/4021/art/1520047439" grandparentTheme="/library/metadata/4021/theme/1520047439" duration="2513928" originallyAvailableAt="2018-03-02" addedAt="1520047352" updatedAt="1520047437">
<Media videoResolution="720" id="92906" duration="2513928" bitrate="2792" width="1280" height="718" aspectRatio="1.78" audioChannels="6" audioCodec="ac3" videoCodec="h264" container="mkv" videoFrameRate="24p" videoProfile="high">
<Part accessible="1" exists="1" id="110560" key="/library/parts/110560/1520047326/file.mkv" duration="2513928" file="/volume1/media/Video/TV/Marvel's Agents of S.H.I.E.L.D/Season 5/Marvels.Agents.of.S.H.I.E.L.D.S05E11.720p.mkv" size="877210785" container="mkv" videoProfile="high">
<Stream id="227806" streamType="1" default="1" codec="h264" index="0" bitrate="2408" bitDepth="8" chromaLocation="left" chromaSubsampling="4:2:0" colorRange="tv" colorSpace="bt709" frameRate="23.976" hasScalingMatrix="0" height="718" level="41" profile="high" refFrames="5" scanType="progressive" width="1280"/>
<Stream id="227807" streamType="2" selected="1" default="1" codec="ac3" index="1" channels="6" bitrate="384" audioChannelLayout="5.1(side)" samplingRate="48000"/>
</Part>
</Media>
<Director id="12251" filter="director=12251" tag="Kate Woods"/>
<Writer id="12243" filter="writer=12243" tag="Drew Z. Greenberg"/>
<Extras size="0"></Extras>
</Video>
</MediaContainer>
```

**Comment by tidusjar** [comment]
Interesting. Can you run the job and post the stdout ?

**Comment by bagobones** [comment]
I have the output but it basically lists my entire library which is fairly large... No errors, just lots of processing x episodes responses, which is better than when I opened this ticket.

It clearly goes through every series and every episode.. The total found and the total processed all look correct and it gets to the "We have finished caching the episodes"

I opened the OMBI.DB in an sql lite editor and it appears that both the series and the episodes are in the cache with IDs.

At the SEARCH level the Series DOES show as available in plex and has the correct link to plex.

The ONLY thing wrong at this point is that individual episodes show "Processing Request" instead of available and requests never auto complete when all episodes are available.

**Comment by tidusjar** [comment]
Ok. 

Can you reopen the database and check the episode requests table and tell me if the episodes are marked as available in that table?

**Comment by bagobones** [comment]
I ran some queries against the DB, looks like the episodes are missing from the PlexEpisode DB.

Ran the following and found a lot of Series without episodes but not all
```
select PlexServerContent.*,  count(PlexEpisode.GrandparentKey)
from PlexServerContent
left join PlexEpisode ON PlexServerContent.Key=PlexEpisode.GrandparentKey 
where PlexServerContent.TvDbID notnull
group by PlexServerContent.Key
```
I can not see any correlation between the series with no episodes in the DB vs those that do.

**Comment by tidusjar** [comment]
@bagobones can you jump on discord and Pm me?
