### ISSUE TITLE
Can't connect to Plex during install

### ISSUE THREAD

**Issue by 19wolf** [tidusjar/Ombi#2015]
#### Ombi build Version:

V 3.0.2918-DotNetCore

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

1.11.3.4803

#### Operating System:

Linux Debian 4.15.3-041503-generic #201802120730 SMP Mon Feb 12 07:31:14 UTC 2018 x86_64 GNU/Linux

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
/opt/ombi# ./Ombi
Hello, welcome to Ombi
Valid options are:
Ombi 3.0.2918-DotNetCore
Copyright (C) 2018 Ombi

  --host       (Default: http://*:5000) Set to a semicolon-separated (;) list 
               of URL prefixes to which the server should respond. For example,
               http://localhost:123. Use "*" to indicate that the server should
               listen for requests on any IP address or hostname using the 
               specified port and protocol (for example, http://*:5000). The 
               protocol (http:// or https://) must be included with each URL. 
               Supported formats vary between servers.

  --storage    Storage path, where we save the logs and database

  --help       Display this help screen.

  --version    Display version information.



We are running on 
/opt/ombi
Hosting environment: Production
Content root path: /opt/ombi
Now listening on: http://[::]:5000
Application started. Press Ctrl+C to shut down.
dbug: Ombi.Controllers.External.PlexController[0]
      OK, signing into Plex
dbug: Ombi.Controllers.External.PlexController[0]
      This is our first time, good to go!
crit: Ombi.Controllers.External.PlexController[0]
      Error when trying to sign into Plex.tv
System.TypeInitializationException: The type initializer for 'System.Net.Http.CurlHandler' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Http' threw an exception. ---> System.TypeInitializationException: The type initializer for 'HttpInitializer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Net.Http.Native': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.Http.GetSslVersionDescription()
   at Interop.HttpInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.Http..cctor()
   --- End of inner exception stack trace ---
   at Interop.Http.GetSupportedFeatures()
   at System.Net.Http.CurlHandler..cctor()
   --- End of inner exception stack trace ---
   at System.Net.Http.CurlHandler..ctor()
   at System.Net.Http.HttpClientHandler..ctor()
   at Ombi.Api.OmbiHttpClient.<GetHandler>d__8.MoveNext() in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 94
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.OmbiHttpClient.<Setup>d__7.MoveNext() in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 77
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.OmbiHttpClient.<SendAsync>d__5.MoveNext() in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Api.<Request>d__6`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 34
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Plex.PlexApi.<SignIn>d__8.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.PlexController.<SignIn>d__8.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\PlexController.cs:line 53
```

#### Problem Description:

When running the wizard, cannot connect to Plex. I put in my username and password and click the button and nothing happens. Tried from several OSes and browsers

#### Reproduction Steps:

1. Download Linux.tar.gz from https://github.com/tidusjar/Ombi/releases/tag/Ombi-v3.0.2881
2. `tar xzf linux.tar.gz`
3. `chmod +x Ombi`
4. `./Ombi`
5. Go to http://-ip-:5000
6. Start -> Plex -> enter credentials -> nothing

**Comment by tidusjar** [comment]
https://github.com/tidusjar/Ombi/wiki/Common-Errors
