### ISSUE TITLE
Ombi 3.0.2960 no longer scans second Plex Server

### ISSUE THREAD

**Issue by xunil75** [tidusjar/Ombi#2038]
#### Ombi build Version:

3.0.2960

#### Update Branch:

Open Beta

#### Media Sever:

Plex Media Server

#### Media Server Version:

1.12.0.4829

#### Operating System:

Ubuntu 16.04 Server

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
2018-03-05 01:00:35.360 +01:00 [Information] 1 scheduled job(s) enqueued.
2018-03-05 07:00:42.440 +01:00 [Information] 1 scheduled job(s) enqueued.
2018-03-05 08:29:49.545 +01:00 [Debug] Searching : "Shape"
2018-03-05 08:29:49.844 +01:00 [Debug] Search Result: "Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.Mo$
2018-03-05 08:29:51.480 +01:00 [Debug] Searching : "Shape"
2018-03-05 08:29:51.623 +01:00 [Debug] Search Result: "Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.Mo$
2018-03-05 09:03:40.191 +01:00 [Debug] Searching : "the shape"
2018-03-05 09:03:40.501 +01:00 [Debug] Search Result: "Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.Mo$
```
#### Problem Description:

I have two Plex Servers, both configured under /Settings/Plex. Searching for a Movie/TV-Show before the Ombi 3.0.2960 version used to work properly and I have had always the correct results. However now with this version, I get results only from the first server, even the Movies I already have on the second server can be requested again although I already have them. I believe Ombi is ignoring the second Server even if it is properly configured.

**Comment by tidusjar** [comment]
Can you manually run the job from the plex settings and then post the result from stdout?

**Comment by xunil75** [comment]
Hi Jamie, if you mean "Manually Run Cacher" yes I did it but since I didn't not see any changes on the Logs (tail -f log-20180305.txt) I decided to remove the second Plex Server and re-add it again, I then runed the Cacher one more time after testing connectivity and making sure Plex Authorization Token and Machine Identifier were correct, I still don't see any activity on the Log. I only see something if I search for something.

Here the lat log, I hope this is the correct log you wanted:

```
2018-03-05 10:26:12.569 +01:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/170514?api_key=b8eabaf5608b88d0298aa189dd90bf00
2018-03-05 10:26:12.583 +01:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/299145?api_key=b8eabaf5608b88d0298aa189dd90bf00
2018-03-05 10:26:12.613 +01:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/search/movie?api_key=b8eabaf5608b88d0298aa189dd90bf00&query=straw
2018-03-05 10:26:12.691 +01:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/406141?api_key=b8eabaf5608b88d0298aa189dd90bf00
2018-03-05 10:26:16.223 +01:00 [Debug] Searching : "straw dogs"
2018-03-05 10:26:16.360 +01:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/search/movie?api_key=b8eabaf5608b88d0298aa189dd90bf00&query=straw dogs
2018-03-05 10:26:20.704 +01:00 [Debug] Searching : "straw"
2018-03-05 10:26:20.857 +01:00 [Debug] Search Result: "Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult"
2018-03-05 10:36:15.279 +01:00 [Debug] Searching : "the shape"
2018-03-05 10:36:15.577 +01:00 [Debug] Search Result: "Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult"
```

**Comment by tidusjar** [comment]
Are there any logs from stdout?

**Comment by xunil75** [comment]
how do you get those Logs?

**Comment by xunil75** [comment]
Hi Jamie, ok, I know what you meant. Apparently, Ombi is scanning correctly the files on the new server but it is somehow not able to show them as available since it always gives me the chance to request them. In the stdout log is clearly to see that he does the job well. Should I delete a specific .db and restart Ombi?

```
Mar  5 12:12:06 plex Ombi[8520]:       Getting all content from server Marco's Plex Server 2
Mar  5 12:12:06 plex Ombi[8520]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
Mar  5 12:12:06 plex Ombi[8520]:       We found 2 items
Mar  5 12:12:06 plex Ombi[8520]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
Mar  5 12:12:06 plex Ombi[8520]:       Processing Movies
Mar  5 12:12:07 plex Ombi[8520]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
Mar  5 12:12:07 plex Ombi[8520]:       Adding movie Annabelle
Mar  5 12:12:07 plex Ombi[8520]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
Mar  5 12:12:07 plex Ombi[8520]:       Adding movie Annabelle: Creation
Mar  5 12:12:07 plex Ombi[8520]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
Mar  5 12:12:07 plex Ombi[8520]:       Adding movie Jigsaw
Mar  5 12:12:07 plex Ombi[8520]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
Mar  5 12:12:07 plex Ombi[8520]:       Adding movie M.F.A.
Mar  5 12:12:07 plex Ombi[8520]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
Mar  5 12:12:07 plex Ombi[8520]:       Adding movie Murder on the Orient Express
Mar  5 12:12:07 plex Ombi[8520]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
Mar  5 12:12:07 plex Ombi[8520]:       Adding movie The Shape of Water
Mar  5 12:12:07 plex Ombi[8520]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
Mar  5 12:12:07 plex Ombi[8520]:       We already have movie Three Billboards Outside Ebbing, Missouri
Mar  5 12:12:07 plex Ombi[8520]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
Mar  5 12:12:07 plex Ombi[8520]:       Processing TV Shows
Mar  5 12:12:07 plex Ombi[8520]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
Mar  5 12:12:07 plex Ombi[8520]:       New show Ghost Wars, so add it
Mar  5 12:12:07 plex Ombi[8520]: #033[40m#033[1m#033[33mwarn#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexContentSync[2008]
Mar  5 12:12:07 plex Ombi[8520]:       Exception thrown when attempting to cache the Plex Content
Mar  5 12:12:07 plex Ombi[8520]: System.InvalidOperationException: The instance of entity type 'PlexServerContent' cannot be tracked because another instance with the same key value for {'Key'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
Mar  5 12:12:07 plex Ombi[8520]:    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)
Mar  5 12:12:07 plex Ombi[8520]:    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
Mar  5 12:12:07 plex Ombi[8520]:    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges)
Mar  5 12:12:07 plex Ombi[8520]:    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode node)
Mar  5 12:12:07 plex Ombi[8520]:    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph(EntityEntryGraphNode node, Func`2 handleNode)
Mar  5 12:12:07 plex Ombi[8520]:    at Microsoft.EntityFrameworkCore.DbContext.SetEntityStates(IEnumerable`1 entities, EntityState entityState)
Mar  5 12:12:07 plex Ombi[8520]:    at Ombi.Store.Repository.Repository`1.<AddRange>d__6.MoveNext() in C:\projects\requestplex\src\Ombi.Store\Repository\Repository.cs:line 41
Mar  5 12:12:07 plex Ombi[8520]: --- End of stack trace from previous location where exception was thrown ---
Mar  5 12:12:07 plex Ombi[8520]:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Mar  5 12:12:07 plex Ombi[8520]:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Mar  5 12:12:07 plex Ombi[8520]:    at Ombi.Schedule.Jobs.Plex.PlexContentSync.<StartTheCache>d__17.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 340
Mar  5 12:12:07 plex Ombi[8520]: --- End of stack trace from previous location where exception was thrown ---
Mar  5 12:12:07 plex Ombi[8520]:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Mar  5 12:12:07 plex Ombi[8520]:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Mar  5 12:12:07 plex Ombi[8520]:    at Ombi.Schedule.Jobs.Plex.PlexContentSync.<CacheContent>d__16.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 81
Mar  5 12:12:07 plex Ombi[8520]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
Mar  5 12:12:07 plex Ombi[8520]:       Starting EP Cacher
Mar  5 12:12:07 plex Ombi[8520]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
Mar  5 12:12:07 plex Ombi[8520]:       Total Epsiodes found for Tagalog TV Shows = 145
Mar  5 12:12:07 plex Ombi[8520]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
Mar  5 12:12:07 plex Ombi[8520]:       We have finished caching the episodes.
Mar  5 12:12:07 plex Ombi[8520]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
Mar  5 12:12:07 plex Ombi[8520]:       Total Epsiodes found for TV Shows Kids = 162
Mar  5 12:12:08 plex Ombi[8520]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
Mar  5 12:12:08 plex Ombi[8520]:       Processed 150 more episodes. Total Remaining 12
Mar  5 12:12:08 plex Ombi[8520]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
Mar  5 12:12:08 plex Ombi[8520]:       We have finished caching the episodes.
Mar  5 12:12:08 plex Ombi[8520]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
Mar  5 12:12:08 plex Ombi[8520]:       Total Epsiodes found for TV-Shows = 3003
Mar  5 12:12:08 plex Ombi[8520]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
Mar  5 12:12:08 plex Ombi[8520]:       Processed 150 more episodes. Total Remaining 2853
Mar  5 12:12:08 plex Ombi[8520]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
Mar  5 12:12:08 plex Ombi[8520]:       Processed 150 more episodes. Total Remaining 2703
Mar  5 12:12:08 plex Ombi[8520]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
Mar  5 12:12:08 plex Ombi[8520]:       Processed 150 more episodes. Total Remaining 2553
Mar  5 12:12:09 plex Ombi[8520]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
Mar  5 12:12:09 plex Ombi[8520]:       Processed 150 more episodes. Total Remaining 2403
Mar  5 12:12:09 plex Ombi[8520]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
Mar  5 12:12:09 plex Ombi[8520]:       Processed 150 more episodes. Total Remaining 2253
Mar  5 12:12:09 plex Ombi[8520]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
Mar  5 12:12:09 plex Ombi[8520]:       Processed 150 more episodes. Total Remaining 2103
Mar  5 12:12:09 plex Ombi[8520]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
Mar  5 12:12:09 plex Ombi[8520]:       Processed 150 more episodes. Total Remaining 1953
Mar  5 12:12:10 plex Ombi[8520]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
Mar  5 12:12:10 plex Ombi[8520]:       Processed 150 more episodes. Total Remaining 1803
Mar  5 12:12:10 plex Ombi[8520]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
Mar  5 12:12:10 plex Ombi[8520]:       Processed 150 more episodes. Total Remaining 1653
Mar  5 12:12:10 plex Ombi[8520]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
Mar  5 12:12:10 plex Ombi[8520]:       Processed 150 more episodes. Total Remaining 1503
Mar  5 12:12:10 plex Ombi[8520]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
Mar  5 12:12:10 plex Ombi[8520]:       Processed 150 more episodes. Total Remaining 1353
Mar  5 12:12:10 plex Ombi[8520]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
Mar  5 12:12:10 plex Ombi[8520]:       Processed 150 more episodes. Total Remaining 1203
Mar  5 12:12:11 plex Ombi[8520]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
Mar  5 12:12:11 plex Ombi[8520]:       Processed 150 more episodes. Total Remaining 1053
Mar  5 12:12:11 plex Ombi[8520]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
Mar  5 12:12:11 plex Ombi[8520]:       Processed 150 more episodes. Total Remaining 903
Mar  5 12:12:11 plex Ombi[8520]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
Mar  5 12:12:11 plex Ombi[8520]:       Processed 150 more episodes. Total Remaining 753
Mar  5 12:12:11 plex Ombi[8520]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
Mar  5 12:12:11 plex Ombi[8520]:       Processed 150 more episodes. Total Remaining 603
Mar  5 12:12:12 plex Ombi[8520]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
Mar  5 12:12:12 plex Ombi[8520]:       Processed 150 more episodes. Total Remaining 453
Mar  5 12:12:12 plex Ombi[8520]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
Mar  5 12:12:12 plex Ombi[8520]:       Processed 150 more episodes. Total Remaining 303
Mar  5 12:12:12 plex Ombi[8520]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
Mar  5 12:12:12 plex Ombi[8520]:       Processed 150 more episodes. Total Remaining 153
Mar  5 12:12:12 plex Ombi[8520]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
Mar  5 12:12:12 plex Ombi[8520]:       Processed 150 more episodes. Total Remaining 3
Mar  5 12:12:12 plex Ombi[8520]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
Mar  5 12:12:12 plex Ombi[8520]:       We have finished caching the episodes.
Mar  5 12:12:12 plex Ombi[8520]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
Mar  5 12:12:12 plex Ombi[8520]:       Total Epsiodes found for TV-Shows = 13
Mar  5 12:12:12 plex Ombi[8520]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
Mar  5 12:12:12 plex Ombi[8520]:       We have finished caching the episodes.
Mar  5 12:13:01 plex CRON[539]: (root) CMD (bash /usr/local/bin/quickbox/system/set_interface)
Mar  5 12:13:29 plex Ombi[8520]: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Ombi.Controllers.SearchController[0]
Mar  5 12:13:29 plex Ombi[8520]:       Searching : M.F.A
Mar  5 12:13:29 plex Ombi[8520]: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Ombi.Core.Engine.MovieSearchEngine[0]
Mar  5 12:13:29 plex Ombi[8520]:       Search Result: Ombi.Api.TheMovieDb.Models.MovieSearchResult
```

**Comment by xunil75** [comment]
Here's as well a small example:

Searching for the Movie "Jigsaw" which I have on the second Plex Server and the result is "Request"

`Mar  5 12:48:15 plex Ombi[8520]:       Searching : Jigsaw
Mar  5 12:48:15 plex Ombi[8520]: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Ombi.Core.Engine.MovieSearchEngine[0]
Mar  5 12:48:15 plex Ombi[8520]:       Search Result: Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult
Mar  5 12:48:42 plex Ombi[8520]: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Ombi.Controllers.SearchController[0]`

Searching for the Movie "Primal Fear" which I have on the first Plex Server and the result is "Available"

`Mar  5 12:48:42 plex Ombi[8520]:       Searching : Primal Fear
Mar  5 12:48:42 plex Ombi[8520]: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Ombi.Core.Engine.MovieSearchEngine[0]
Mar  5 12:48:42 plex Ombi[8520]:       Search Result: Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult`

**Comment by tidusjar** [comment]
@xunil75 Please can you PM me on discord?
