### ISSUE TITLE
Access to the path '/root/.dotnet/corefx/cryptography/x509stores/ca' is denied. - Permission denied

### ISSUE THREAD

**Issue by dephcon** [tidusjar/Ombi#2046]
#### Ombi build Version:
3.0.2970
#### Update Branch:
master
#### Media Sever:
Plex
#### Operating System:
LinuxServer.io Docker container

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

Error thrown when attempting to obtain the plex libs
System.UnauthorizedAccessException: Access to the path '/root/.dotnet/corefx/cryptography/x509stores/ca' is denied. ---> System.IO.IOException: Permission denied
--- End of inner exception stack trace ---
at System.IO.UnixFileSystem.CreateDirectory(String fullPath)
at System.IO.Directory.CreateDirectory(String path)
at Internal.Cryptography.Pal.DirectoryBasedStoreProvider.Add(ICertificatePal certPal)
at System.Security.Cryptography.X509Certificates.X509Store.Add(X509Certificate2 certificate)
at Internal.Cryptography.Pal.ChainPal.SaveIntermediateCertificates(X509ChainElement[] chainElements, HashSet`1 downloaded)
at Internal.Cryptography.Pal.ChainPal.BuildChain(Boolean useMachineContext, ICertificatePal cert, X509Certificate2Collection extraStore, OidCollection applicationPolicy, OidCollection certificatePolicy, X509RevocationMode revocationMode, X509RevocationFlag revocationFlag, DateTime verificationTime, TimeSpan timeout)
at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate, Boolean throwOnException)
at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate)
at System.Net.Security.CertificateValidation.BuildChainAndVerifyProperties(X509Chain chain, X509Certificate2 remoteCertificate, Boolean checkCertName, String hostName)
at System.Net.Http.CurlHandler.SslProvider.VerifyCertChain(SafeX509StoreCtxHandle storeCtx, EasyRequest easy)
at System.Net.Http.CurlHandler.SslProvider.VerifyCertChain(IntPtr storeCtxPtr, IntPtr curlPtr)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Ombi.Api.OmbiHttpClient.<SendAsync>d__5.MoveNext() in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Ombi.Api.Api.<Request>d__6`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 34
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Ombi.Api.Plex.PlexApi.<GetLibrarySections>d__12.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 74
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Ombi.Controllers.External.PlexController.<GetPlexLibraries>d__9.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\PlexController.cs:line 105

```

#### Problem Description:

I receive this error when attempting to load my plex libraries with SSL:
Access to the path '/root/.dotnet/corefx/cryptography/x509stores/ca' is denied. - Permission denied

I've checked Ignore any certificate errors in settings as i was getting an SSL cert error before.

#### Reproduction Steps:
Click Load Libraries

**Comment by tidusjar** [comment]
I've never seen this.

can you please try this: https://stackoverflow.com/a/42345327/3329836

**Comment by dephcon** [comment]
`
mkdir -p /root/.dotnet/corefx/cryptography/x509stores/ca
sudo chgrp www-data  /root/.dotnet/corefx/cryptography/x509stores/ca
`

didn't help, unless i need to use a different user/group for this app?

**Comment by starbuck93** [comment]
I'm also having this problem. Exactly the same as @dephcon. LinuxServer.io docker, Ombi V3, trying to load libraries. Here is the stack trace from the error.

```      
            Error thrown when attempting to obtain the plex libs
System.UnauthorizedAccessException: Access to the path '/root/.dotnet/corefx/cryptography/x509stores/ca' is denied. ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.UnixFileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Internal.Cryptography.Pal.DirectoryBasedStoreProvider.Add(ICertificatePal certPal)
   at System.Security.Cryptography.X509Certificates.X509Store.Add(X509Certificate2 certificate)
   at Internal.Cryptography.Pal.ChainPal.SaveIntermediateCertificates(X509ChainElement[] chainElements, HashSet`1 downloaded)
   at Internal.Cryptography.Pal.ChainPal.BuildChain(Boolean useMachineContext, ICertificatePal cert, X509Certificate2Collection extraStore, OidCollection applicationPolicy, OidCollection certificatePolicy, X509RevocationMode revocationMode, X509RevocationFlag revocationFlag, DateTime verificationTime, TimeSpan timeout)
   at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate, Boolean throwOnException)
   at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate)
   at System.Net.Security.CertificateValidation.BuildChainAndVerifyProperties(X509Chain chain, X509Certificate2 remoteCertificate, Boolean checkCertName, String hostName)
   at System.Net.Http.CurlHandler.SslProvider.VerifyCertChain(SafeX509StoreCtxHandle storeCtx, EasyRequest easy)
   at System.Net.Http.CurlHandler.SslProvider.VerifyCertChain(IntPtr storeCtxPtr, IntPtr curlPtr)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.OmbiHttpClient.<SendAsync>d__5.MoveNext() in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Api.<Request>d__6`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 34
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Plex.PlexApi.<GetLibrarySections>d__12.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 74
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.PlexController.<GetPlexLibraries>d__9.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\PlexController.cs:line 105
```

Also, "Test Connectivity" fails with this:
```
      Could not test Plex
System.UnauthorizedAccessException: Access to the path '/root/.dotnet/corefx/cryptography/x509stores/ca' is denied. ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.UnixFileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Internal.Cryptography.Pal.DirectoryBasedStoreProvider.Add(ICertificatePal certPal)
   at System.Security.Cryptography.X509Certificates.X509Store.Add(X509Certificate2 certificate)
   at Internal.Cryptography.Pal.ChainPal.SaveIntermediateCertificates(X509ChainElement[] chainElements, HashSet`1 downloaded)
   at Internal.Cryptography.Pal.ChainPal.BuildChain(Boolean useMachineContext, ICertificatePal cert, X509Certificate2Collection extraStore, OidCollection applicationPolicy, OidCollection certificatePolicy, X509RevocationMode revocationMode, X509RevocationFlag revocationFlag, DateTime verificationTime, TimeSpan timeout)
   at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate, Boolean throwOnException)
   at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate)
   at System.Net.Security.CertificateValidation.BuildChainAndVerifyProperties(X509Chain chain, X509Certificate2 remoteCertificate, Boolean checkCertName, String hostName)
   at System.Net.Http.CurlHandler.SslProvider.VerifyCertChain(SafeX509StoreCtxHandle storeCtx, EasyRequest easy)
   at System.Net.Http.CurlHandler.SslProvider.VerifyCertChain(IntPtr storeCtxPtr, IntPtr curlPtr)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.OmbiHttpClient.<SendAsync>d__5.MoveNext() in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Api.<Request>d__6`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 34
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Plex.PlexApi.<GetStatus>d__9.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<Plex>d__55.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 235
```

I ran the commands that dephcon mentioned in the docker container with `docker exec -it ombi3 /bin/bash`, restarted the container and it did not fix anything.

**Comment by starbuck93** [comment]
https://github.com/tidusjar/Ombi/issues/1650#issuecomment-341457798 fixed it for me. Here is what I ran to finally get it to work.

`docker exec -it ombi /bin/bash`
then
`chmod 777 /root -R`
`chgrp abc /root/.dotnet -R`

#1538 is also related to this issue.

**Comment by dephcon** [comment]
@aptalca is this something you can add to the base container?

**Comment by louis-lau** [comment]
You should NEVER have to chmod 777 in normal conditions. I don't know what user and group ombi runs as using docker. but chmod 755 should be plenty

**Comment by dephcon** [comment]
@louis-lau 755 works as well ;)

**Comment by magma2007** [comment]
This is an issue with the fact that DotNet is using the HOME variable to try and place the cached certificate into /root.

I've submitted an issue and fix for the problem to the docker repo: linuxserver/docker-ombi#25
