### ISSUE TITLE
Radarr error when requesting movie

### ISSUE THREAD

**Issue by majorbeef** [tidusjar/Ombi#2082]
#### Ombi build Version:

V 3.0.3030

#### Update Branch:

Master

#### Media Sever:

Plex

#### Operating System:

Unraid 6.4.1 - Linuxserver.io container

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
2018-03-18 01:14:45.083 -05:00 [Error] Error When adding movie to Radarr, Reponse: "[
  {
    \"title\": \"10 Cloverfield Lane\",
    \"alternativeTitles\": [
      {
        \"sourceType\": \"tmdb\",
        \"movieId\": 1,
        \"title\": \"Ten Cloverfield Lane\",
        \"sourceId\": 333371,
        \"votes\": 0,
        \"voteCount\": 0,
        \"language\": \"english\",
        \"id\": 4
      },

### A lot more movies in the log####

Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Ombi.Api.Radarr.Models.RadarrAddMovieResponse' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Radarr.RadarrApi.<AddMovie>d__13.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Radarr\RadarrApi.cs:line 111

```

#### Problem Description:

Requesting movie does not add movie to Radarr.

#### Reproduction Steps:

Request a movie.

**Comment by tidusjar** [comment]
Do you have a base URL set in radarr?

**Comment by majorbeef** [comment]
Ya. I didn't think I needed it since I was using the local IP. I put it in and now it is working.

Thanks.
