### ISSUE TITLE
Error in cmd console

### ISSUE THREAD

**Issue by RimfireFoShizzle** [tidusjar/Ombi#2116]
#### Ombi build Version:

V 3.0.3111

#### Update Branch:

Master

#### Media Sever:

Plex

#### Media Server Version:

 1.12.1.4885

#### Operating System:

Windows 10 Pro - Version 1709 - Build 16299.192

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

fail: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[0]
      Exception thrown in the OmbiUpdater, see previous messages
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Schedule.Processor.ChangeLogProcessor.<Process>d__6.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Processor\ChangeLogProcessor.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 99

```

#### Problem Description:

I noticed this error in the cmd console and don't understand what it says or what causes it.
IIRC I didn't get this error in the previous version I had installed (v3.0.2970).

Not very tech savvy (can get most things working with some help though) so I'd appreciate any help.

Already googled this issue but couldn't find any related issues.

#### Reproduction Steps:

Unknown

**Comment by PotatoQuality** [comment]
Pleas post the whole error in it. We missing now the previous error.

**Comment by tidusjar** [comment]
@PotatoQuality the error that he's provided is fine :) i know what this is.
