### ISSUE TITLE
Blank black login page / Reverse Proxy

### ISSUE THREAD

**Issue by XmemphistoX** [tidusjar/Ombi#2131]
#### Ombi build Version:

V 3.0.3111

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Operating System:

Win10

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

````
2018-04-06 05:00:38.988 -07:00 [Information] 1 scheduled job(s) enqueued.
2018-04-06 11:02:33.081 -07:00 [Information] 1 scheduled job(s) enqueued.
2018-04-06 11:03:12.747 -07:00 [Debug] Search Result: "Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult"
2018-04-06 11:03:53.227 -07:00 [Debug] Search Result: "Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult"
2018-04-06 11:05:42.076 -07:00 [Information] Sent mass email to user "OBFUSCATED" @ "OBFUSCATED@gmail.com"
2018-04-06 11:07:57.040 -07:00 [Information] Sent mass email to user "OBFUSCATED" @ "OBFUSCATED@gmail.com"
2018-04-06 11:09:00.050 -07:00 [Information] Sent mass email to user "OBFUSCATED" @ "OBFUSCATED@outlook.com"
2018-04-06 11:20:44.841 -07:00 [Warning] Exception when testing Email Notifications
System.InvalidOperationException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond OBFUSCATED:25
   at Ombi.Notifications.GenericEmailProvider.<SendAdHoc>d__5.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 94
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<Email>d__57.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 218
2018-04-06 11:20:47.225 -07:00 [Warning] Exception when testing Email Notifications
System.InvalidOperationException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond OBFUSCATED:25
   at Ombi.Notifications.GenericEmailProvider.<SendAdHoc>d__5.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 94
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<Email>d__57.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 218
2018-04-06 11:21:04.380 -07:00 [Information] Sent mass email to user "OBFUSCATED" @ "OBFUSCATED@outlook.com"
2018-04-06 11:22:50.797 -07:00 [Information] Sent mass email to user "OBFUSCATED" @ "OBFUSCATED@outlook.com"
2018-04-06 11:23:21.983 -07:00 [Warning] Exception when testing Email Notifications
System.InvalidOperationException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond OBFUSCATED:25
   at Ombi.Notifications.GenericEmailProvider.<SendAdHoc>d__5.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 94
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<Email>d__57.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 218
2018-04-06 11:23:31.979 -07:00 [Information] Sent mass email to user "OBFUSCATED" @ "OBFUSCATED@outlook.com"
2018-04-06 11:23:53.809 -07:00 [Information] Sent mass email to user "OBFUSCATED" @ "OBFUSCATED@hotmail.com"
2018-04-06 11:24:16.565 -07:00 [Warning] Exception when testing Email Notifications
System.InvalidOperationException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond OBFUSCATED:25
   at Ombi.Notifications.GenericEmailProvider.<SendAdHoc>d__5.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 94
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<Email>d__57.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 218
2018-04-06 11:24:37.196 -07:00 [Warning] Exception when testing Email Notifications
System.InvalidOperationException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond OBFUSCATED:25
   at Ombi.Notifications.GenericEmailProvider.<SendAdHoc>d__5.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 94
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<Email>d__57.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 218
2018-04-06 11:24:50.914 -07:00 [Information] Sent mass email to user "OBFUSCATED" @ "OBFUSCATED@gmail.com"
2018-04-06 11:25:48.057 -07:00 [Information] Sent mass email to user "OBFUSCATED" @ "OBFUSCATED@outlook.com"
2018-04-06 11:25:53.927 -07:00 [Information] Sent mass email to user "OBFUSCATED" @ "OBFUSCATED@outlook.com"
2018-04-06 11:28:03.687 -07:00 [Debug] Search Result: "Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult"
2018-04-06 11:31:29.244 -07:00 [Debug] Search Result: "Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult"
2018-04-06 11:31:38.516 -07:00 [Debug] Search Result: "Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult"
2018-04-06 11:31:39.067 -07:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/399035?OBFUSCATED
2018-04-06 11:31:39.069 -07:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/316029?OBFUSCATED
2018-04-06 11:31:39.199 -07:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/316029?OBFUSCATED Because we got Status Code: 429
2018-04-06 11:31:39.199 -07:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/399035?OBFUSCATED Because we got Status Code: 429
2018-04-06 11:32:21.470 -07:00 [Debug] Search Result: "Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult"
2018-04-06 11:33:35.684 -07:00 [Debug] Search Result: "Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult"
2018-04-06 11:33:45.906 -07:00 [Debug] Search Result: "Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult"
2018-04-06 11:33:48.535 -07:00 [Debug] Search Result: "Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult"
2018-04-06 11:45:57.785 -07:00 [Debug] Search Result: "Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult"
2018-04-06 11:46:16.590 -07:00 [Debug] Searching : "t"
2018-04-06 11:46:16.731 -07:00 [Debug] Search Result: "Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult"
2018-04-06 11:46:17.345 -07:00 [Debug] Searching : "teh"
2018-04-06 11:46:17.437 -07:00 [Debug] Search Result: "Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult"
2018-04-06 11:46:18.063 -07:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/384600?OBFUSCATED
2018-04-06 11:46:18.110 -07:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/117368?OBFUSCATED
2018-04-06 11:46:18.152 -07:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/384600?OBFUSCATED Because we got Status Code: 429
2018-04-06 11:46:18.193 -07:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/117368?OBFUSCATED Because we got Status Code: 429
2018-04-06 11:46:19.022 -07:00 [Debug] Searching : "spi"
2018-04-06 11:46:19.105 -07:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/search/movie?OBFUSCATED&query=spi
2018-04-06 11:46:19.194 -07:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/search/movie?OBFUSCATED&query=spi Because we got Status Code: 429
2018-04-06 11:46:21.652 -07:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/500890?OBFUSCATED&append_to_response=videos,release_dates
2018-04-06 11:46:21.737 -07:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/500890?OBFUSCATED&append_to_response=videos,release_dates Because we got Status Code: 429
2018-04-06 11:46:29.304 -07:00 [Debug] Search Result: "Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult"
2018-04-06 11:46:37.815 -07:00 [Debug] Searching : "spinning man"
2018-04-06 11:46:37.904 -07:00 [Debug] Search Result: "Ombi.Api.TheMovieDb.Models.MovieSearchResult"
2018-04-06 11:47:25.129 -07:00 [Debug] Searching : "the titan"
2018-04-06 11:47:25.233 -07:00 [Debug] Search Result: "Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult"

````

#### Problem Description:

When initially visiting the webpage, I get a black login screen.  I see the loading bar up top but it loads to nothing but a black page.  When I refresh the page, the login window shows up.  Reverse Proxy conf below.

````
		location /ombi {		
			return 301 $scheme://$host/ombi/;		
		}
		location /ombi/ {
			proxy_pass http://127.0.0.1:5000;
			proxy_set_header Host $host;
			proxy_set_header X-Forwarded-Host $server_name;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Ssl on;
			proxy_set_header X-Forwarded-Proto $scheme;
			proxy_read_timeout  90;
			proxy_redirect http://127.0.0.1:5000 https://$host;
		}
		if ($http_referer ~* /ombi/) {
				rewrite ^/dist/(.*) $scheme://$host/ombi/dist/$1 permanent;
}
````

#### Reproduction Steps:

New web session, load the webpage, black login screen.  Refresh again and it works.

**Comment by tidusjar** [comment]
Please check the wiki for the reverse proxy example.
