### ISSUE TITLE
3.0.3164 - New Update Available and updates to v3.0.3111

### ISSUE THREAD

**Issue by nivong** [tidusjar/Ombi#2144]
#### Ombi build Version:

v3.0.3164

#### Update Branch:

Open

#### Media Sever:

Plex

#### Operating System:

Windows 10 latest update

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      Starting Update job
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      Path: C:\Users\Miner\Downloads\windows
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      Product Version 3.0.3164-master
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      Version 3.0.3164
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      Branch Version master
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      Version 3.0.3164
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      Branch master
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      Looking for updates now
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      Updates: Ombi.Core.Processor.UpdateModel
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      Service Version v3.0.3111 (2018-03-27)
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      OS Information: Microsoft Windows 10.0.16299  X64
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      We are Windows
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      Found the download! windows.zip
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      URL https://github.com/tidusjar/Ombi/releases/download/v3.0.3111/windows.zip
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      Clearing out Temp Path
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      Downloading the file windows.zip from https://github.com/tidusjar/Ombi/releases/download/v3.0.3111/windows.zip
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      Zip Dir: C:\Users\Miner\Downloads\windows\Ombi.zip
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      Starting Download
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      Starting the DownloadAsync
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      Finished Download
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      Extracting ZIP
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      Finished Extracting files
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      Starting the Ombi.Updater process
fail: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[0]
      Exception thrown in the OmbiUpdater, see previous messages
System.InvalidOperationException: The Process object must have the UseShellExecute property set to false in order to start a process as a user.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 234
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      Starting Update job
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      Path: C:\Users\Miner\Downloads\windows
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      Product Version 3.0.3164-master
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      Version 3.0.3164
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      Branch Version master
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      Version 3.0.3164
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      Branch master
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      Looking for updates now
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      Updates: Ombi.Core.Processor.UpdateModel
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      Service Version v3.0.3111 (2018-03-27)
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      OS Information: Microsoft Windows 10.0.16299  X64
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      We are Windows
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      Found the download! windows.zip
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      URL https://github.com/tidusjar/Ombi/releases/download/v3.0.3111/windows.zip
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      Clearing out Temp Path
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      Downloading the file windows.zip from https://github.com/tidusjar/Ombi/releases/download/v3.0.3111/windows.zip
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      Zip Dir: C:\Users\Miner\Downloads\windows\Ombi.zip
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      Starting Download
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      Starting the DownloadAsync
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      Finished Download
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      Extracting ZIP
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      Finished Extracting files
dbug: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[6000]
      Starting the Ombi.Updater process
fail: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[0]
      Exception thrown in the OmbiUpdater, see previous messages
System.InvalidOperationException: The Process object must have the UseShellExecute property set to false in order to start a process as a user.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 234
```

#### Problem Description:

It updates to v3.0.3111
as a bonus there are 2 errors in the process

#### Reproduction Steps:

Update to the latest and click update in the admin menu.

**Comment by jalmansor** [comment]
I'm seeing this as well, though running in Docker on Linux

**Comment by tidusjar** [comment]
dupe #1460
