### ISSUE TITLE
Buttons hard to see with movie backgrounds

### ISSUE THREAD

**Issue by diedrichg** [tidusjar/Ombi#2160]
#### Ombi build Version:

V 3.0.3179

#### Update Branch:

Beta

#### Media Sever:

Emby

#### Media Server Version:

3.3.1.0

#### Operating System:

Win10

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2018-04-15 00:05:18.516 -04:00 [Error] Provider Id on tv "America's Test Kitchen From Cook's Illustrated" is null
2018-04-15 00:11:46.897 -04:00 [Error] Could not test Newsletter
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.<ExecuteDbDataReaderAsync>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.<ExecuteAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<BufferlessMoveNext>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<MoveNext>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Linq.AsyncEnumerable.<FirstOrDefault_>d__165`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.<MoveNext>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.<MoveNextCore>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.<MoveNext>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<ExecuteSingletonAsyncQuery>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Store.Repository.NotificationTemplatesRepository.<GetTemplate>d__7.MoveNext() in C:\projects\requestplex\src\Ombi.Store\Repository\NotificationTemplatesRepository.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.<Start>d__12.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\NewsletterJob.cs:line 65
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<NewsletterTest>d__65.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 383
2018-04-15 00:19:59.554 -04:00 [Debug] Searching : "rio"
2018-04-15 00:19:59.721 -04:00 [Debug] Search Result: "Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult"
2018-04-15 00:20:41.165 -04:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/272094
2018-04-15 00:20:41.404 -04:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/70331
2018-04-15 00:20:41.522 -04:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/0
2018-04-15 00:20:41.554 -04:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/77954
2018-04-15 00:20:41.643 -04:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/0
2018-04-15 00:20:41.758 -04:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/0
2018-04-15 00:50:42.169 -04:00 [Debug] Starting to move the files
2018-04-15 00:50:42.203 -04:00 [Debug] We are currently in dir "C:\ProgramData\Ombi"
2018-04-15 00:50:42.205 -04:00 [Debug] Ombi is installed at null
2018-04-15 00:50:42.217 -04:00 [Debug] Created dir "\de"
2018-04-15 00:50:42.217 -04:00 [Debug] Created dir "\es"
2018-04-15 00:50:42.218 -04:00 [Debug] Created dir "\fr"
2018-04-15 00:50:42.218 -04:00 [Debug] Created dir "\it"
2018-04-15 00:50:42.218 -04:00 [Debug] Created dir "\ja"
2018-04-15 00:50:42.218 -04:00 [Debug] Created dir "\ko"
2018-04-15 00:50:42.219 -04:00 [Debug] Created dir "\Logs"
2018-04-15 00:50:42.219 -04:00 [Debug] Created dir "\refs"
2018-04-15 00:50:42.219 -04:00 [Debug] Created dir "\ru"
2018-04-15 00:50:42.220 -04:00 [Debug] Created dir "\Templates"
2018-04-15 00:50:42.220 -04:00 [Debug] Created dir "\Views"
2018-04-15 00:50:42.220 -04:00 [Debug] Created dir "\wwwroot"
2018-04-15 00:50:42.221 -04:00 [Debug] Created dir "\zh"
2018-04-15 00:50:42.221 -04:00 [Debug] Created dir "\zh-Hans"
2018-04-15 00:50:42.221 -04:00 [Debug] Created dir "\zh-Hant"
2018-04-15 00:50:42.222 -04:00 [Debug] Created dir "\Views\Home"
2018-04-15 00:50:42.222 -04:00 [Debug] Created dir "\Views\Shared"
2018-04-15 00:50:42.222 -04:00 [Debug] Created dir "\wwwroot\dist"
2018-04-15 00:50:42.223 -04:00 [Debug] Created dir "\wwwroot\images"
2018-04-15 00:50:42.223 -04:00 [Debug] Created dir "\wwwroot\translations"
2018-04-15 00:50:42.223 -04:00 [Debug] Created dir "\wwwroot\images\favicon"
2018-04-15 01:23:58.597 -04:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/272094
2018-04-15 01:23:58.711 -04:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/70331
2018-04-15 01:23:58.800 -04:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/0
2018-04-15 01:23:58.823 -04:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/77954
2018-04-15 01:23:58.979 -04:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/0
2018-04-15 01:23:59.009 -04:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/0

```

#### Problem Description:

The Request/Available/Similar buttons are very difficult to see with certain movie backgrounds overpowering the color of the buttons. I'd suggest bringing the movie background alpha down quite low, around 30 or 20%, or not at all - keep it a dark color to match the theme giving it a nice clean look.

**Comment by diedrichg** [comment]
![2018-04-15 01_49_27-ombi](https://user-images.githubusercontent.com/9559987/38775387-6556dce8-404f-11e8-8fb7-a121b7af115c.png)

**Comment by D34DC3N73R** [comment]
I added a dark transparent background (and some padding) to the buttons in my custom css.
`button.btn, .btn-success-outline {background-color: rgba(0,0,0,0.8) !important; margin: 4px 0; }`

![untitled-1](https://user-images.githubusercontent.com/9123670/38831159-6027e4f4-4173-11e8-97cc-790a3aaa9233.jpg)

**Comment by diedrichg** [comment]
Ah! Much better. Thanks! I was not aware there was some CSS magic available to be edited. I too don't like the zero padding and even reported it as a GUI bug but it was rejected.

**Comment by D34DC3N73R** [comment]
There is now a place in the backend to define custom css (/Settings/Customization) and themes, so I would think lots of these minor things that come down to personal preference can just be defined here. Or even make your own theme if you don't like the default look.

**Comment by anojht** [comment]
Can you close this issue please, a new UI overhaul is being worked on through [layercake ](https://github.com/leram84/layer.Cake) for ombi and as mentioned above customization is possible through CSS in the settings. Thanks for reporting the issue!
