### ISSUE TITLE
Submit button in middle of the Jobs page

### ISSUE THREAD

**Issue by diedrichg** [tidusjar/Ombi#2163]
Ombi build Version:
V 3.0.3179

Update Branch:
Beta

Media Sever:
Emby

Media Server Version:
3.3.1.0

Operating System:
Win10

Ombi Applicable Logs (from /logs/ directory or the Admin page):

2018-04-15 00:05:18.516 -04:00 [Error] Provider Id on tv "America's Test Kitchen From Cook's Illustrated" is null
2018-04-15 00:11:46.897 -04:00 [Error] Could not test Newsletter
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.<ExecuteDbDataReaderAsync>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.<ExecuteAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<BufferlessMoveNext>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<MoveNext>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Linq.AsyncEnumerable.<FirstOrDefault_>d__165`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.<MoveNext>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.<MoveNextCore>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.<MoveNext>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<ExecuteSingletonAsyncQuery>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Store.Repository.NotificationTemplatesRepository.<GetTemplate>d__7.MoveNext() in C:\projects\requestplex\src\Ombi.Store\Repository\NotificationTemplatesRepository.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.<Start>d__12.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\NewsletterJob.cs:line 65
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<NewsletterTest>d__65.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 383
2018-04-15 00:19:59.554 -04:00 [Debug] Searching : "rio"
2018-04-15 00:19:59.721 -04:00 [Debug] Search Result: "Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult"
2018-04-15 00:20:41.165 -04:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/272094
2018-04-15 00:20:41.404 -04:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/70331
2018-04-15 00:20:41.522 -04:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/0
2018-04-15 00:20:41.554 -04:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/77954
2018-04-15 00:20:41.643 -04:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/0
2018-04-15 00:20:41.758 -04:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/0
2018-04-15 00:50:42.169 -04:00 [Debug] Starting to move the files
2018-04-15 00:50:42.203 -04:00 [Debug] We are currently in dir "C:\ProgramData\Ombi"
2018-04-15 00:50:42.205 -04:00 [Debug] Ombi is installed at null
2018-04-15 00:50:42.217 -04:00 [Debug] Created dir "\de"
2018-04-15 00:50:42.217 -04:00 [Debug] Created dir "\es"
2018-04-15 00:50:42.218 -04:00 [Debug] Created dir "\fr"
2018-04-15 00:50:42.218 -04:00 [Debug] Created dir "\it"
2018-04-15 00:50:42.218 -04:00 [Debug] Created dir "\ja"
2018-04-15 00:50:42.218 -04:00 [Debug] Created dir "\ko"
2018-04-15 00:50:42.219 -04:00 [Debug] Created dir "\Logs"
2018-04-15 00:50:42.219 -04:00 [Debug] Created dir "\refs"
2018-04-15 00:50:42.219 -04:00 [Debug] Created dir "\ru"
2018-04-15 00:50:42.220 -04:00 [Debug] Created dir "\Templates"
2018-04-15 00:50:42.220 -04:00 [Debug] Created dir "\Views"
2018-04-15 00:50:42.220 -04:00 [Debug] Created dir "\wwwroot"
2018-04-15 00:50:42.221 -04:00 [Debug] Created dir "\zh"
2018-04-15 00:50:42.221 -04:00 [Debug] Created dir "\zh-Hans"
2018-04-15 00:50:42.221 -04:00 [Debug] Created dir "\zh-Hant"
2018-04-15 00:50:42.222 -04:00 [Debug] Created dir "\Views\Home"
2018-04-15 00:50:42.222 -04:00 [Debug] Created dir "\Views\Shared"
2018-04-15 00:50:42.222 -04:00 [Debug] Created dir "\wwwroot\dist"
2018-04-15 00:50:42.223 -04:00 [Debug] Created dir "\wwwroot\images"
2018-04-15 00:50:42.223 -04:00 [Debug] Created dir "\wwwroot\translations"
2018-04-15 00:50:42.223 -04:00 [Debug] Created dir "\wwwroot\images\favicon"
2018-04-15 01:23:58.597 -04:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/272094
2018-04-15 01:23:58.711 -04:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/70331
2018-04-15 01:23:58.800 -04:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/0
2018-04-15 01:23:58.823 -04:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/77954
2018-04-15 01:23:58.979 -04:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/0
2018-04-15 01:23:59.009 -04:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/0

Problem Description:
On the Jobs page, the Submit button is located in the middle of the page rather than at the bottom like all the other pages. This is on both Chrome mobile browser and Windows Firefox.

Reproduction Steps:

**Comment by tidusjar** [comment]
Fixed in develop
