### ISSUE TITLE
New requests not being sent to Sonarr

### ISSUE THREAD

**Issue by TUiZHD** [tidusjar/Ombi#2168]
#### Ombi build Version:

V 3.0.3173

#### Update Branch:

Master

#### Media Sever:

Plex

#### Media Server Version:

Plex Media Server 1.12.2.4929-29f6d1796

#### Operating System:

Windows 10 (64bit)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2018-04-16 23:37:49.129 +01:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/76580
2018-04-16 23:37:49.097 +01:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/153221
2018-04-16 23:37:49.653 +01:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/317354
2018-04-16 23:37:49.899 +01:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/74101
2018-04-16 23:37:50.108 +01:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/209441
2018-04-16 23:38:05.960 +01:00 [Error] StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://192.168.1.5:8989/api/series/0
2018-04-16 23:38:06.041 +01:00 [Error] Exception thrown when attempting to send series over to Sonarr
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Ombi.Api.Sonarr.Models.SonarrSeries' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.<Request>d__6`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 74
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Sonarr.SonarrApi.<UpdateSeries>d__8.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Sonarr\SonarrApi.cs:line 88
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Core.Senders.TvSender.<SendToSonarr>d__25.MoveNext() in C:\projects\requestplex\src\Ombi.Core\Senders\TvSender.cs:line 207
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Core.Senders.TvSender.<SendToSonarr>d__24.MoveNext() in C:\projects\requestplex\src\Ombi.Core\Senders\TvSender.cs:line 176

```

#### Problem Description:

Ombi doesn't seem to be sending over the request to Sonarr at all.

#### Reproduction Steps:

Search for TV Show, selected 2 episodes from latest season, hit submit, check requests and confirm they are there, check Sonarr and nothing has been requested/queued.

**Comment by tidusjar** [comment]
Make sure your base URL is filled in on the ombi settings of you are using it in sonarr

**Comment by TUiZHD** [comment]
Feel like a right idiot now, I could of sworn I added it in. Fully fixed and working.

Absolutely love using Ombi thanks for all the hard work.
