### ISSUE TITLE
--Baseurl not working

### ISSUE THREAD

**Issue by userdocs** [tidusjar/Ombi#2170]
If I use the base `--baseurl /path` ombi it does not seem to be used by ombi.

when i enter the url with the base path it redirects to the default url. if i enter the `url:port` with no base path it loads ombi as normal and i can see the base url is not set in the configuration. it was used in the startup command.

chrome gives me this error

```
ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'testme/search'
```

**Comment by userdocs** [comment]
I can only restart by ctrl c in my shell. I am not using the system.

Even if I do that it does not seem to take effect.

If I set the base url manually inside the app and restart using ctrl c it works and I can proxy pass. It is only the start-up command that is not working as expected. I use it like this (but even just `---baseurl /testme`  does not work.)

```
./Ombi --host http://*:23456 --baseurl /$(whoami)/ombi
``` 

Am I doing something wrong or is the combination of host and baseurl an issue?

**Comment by userdocs** [comment]
My specific requirement is to be able to set the base url as:

```
--baseurl /username/ombi
```

I am using feralhosting and in order or proxypass properly with https the base url  needs to be set like this. I can manually set this in ombi once it has loaded, in the configuration, and it works as i require. I appreciate this is not a standard approach and don't assume it is your problem, but it does work if i set it manually. The only issue i am having is using the `--baseurl` method. I have a working proxypass but currently it requires that i load the application first using a  basic method:

```
./Ombi --host http://*:23456
```

Then visit the url:port and configure the base url as `/username/ombi`

and restart.

Is there a way this `--baseurl` method can work for more specific paths requirements? In an ideal world if i could use:

```
--baseurl /$(whoami)/ombi
```

it would be perfect.

**Comment by liaralabs** [comment]
Seconded on this issue.

Finally had some time to test the new changes, and the CLI argument appears to do nothing on my end.

**Comment by userdocs** [comment]
It appears it does not save the config to the database. If i read the pull request properly it grabs the setting from here:

![1](https://user-images.githubusercontent.com/16525024/39088668-0b170762-45ae-11e8-9b45-2be2fc9b3aa4.jpg)

And will apply it and save it here. But as you can see there is nothing.

![2](https://user-images.githubusercontent.com/16525024/39088669-0b2c5d9c-45ae-11e8-8115-e4f19cfe34d0.jpg)

If i set it manually it becomes this.

![3](https://user-images.githubusercontent.com/16525024/39088670-0b44389a-45ae-11e8-9fe4-39db8fa715e4.jpg)

**Comment by tidusjar** [comment]
Fixed in develop

**Comment by userdocs** [comment]
Ombi 3.0.3220-develop via https://ci.appveyor.com/project/tidusjar/requestplex/branch/develop/artifacts

I download ombi and start it with this command.

```
./Ombi --host http://*:33454 --baseurl /$(whoami)/ombi
```

Then i get this error.

```
We are running on http://*:33454
/media/DiskID/username/ombitest
Application startup exception: System.InvalidOperationException: The instance of entity type 'GlobalSettings' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph(EntityEntryGraphNode node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
   at Ombi.Store.Repository.SettingsJsonRepository.Update(GlobalSettings entity) in C:\projects\requestplex\src\Ombi.Store\Repository\SettingsJsonRepository.cs:line 84
   at Ombi.Settings.Settings.SettingsService`1.SaveSettings(T model) in C:\projects\requestplex\src\Ombi.Settings\Settings\SettingsService.cs:line 91
   at Ombi.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IMemoryCache cache, IServiceProvider serviceProvider) in C:\projects\requestplex\src\Ombi\Startup.cs:line 185
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

Unhandled Exception: System.InvalidOperationException: The instance of entity type 'GlobalSettings' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph(EntityEntryGraphNode node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
   at Ombi.Store.Repository.SettingsJsonRepository.Update(GlobalSettings entity) in C:\projects\requestplex\src\Ombi.Store\Repository\SettingsJsonRepository.cs:line 84
   at Ombi.Settings.Settings.SettingsService`1.SaveSettings(T model) in C:\projects\requestplex\src\Ombi.Settings\Settings\SettingsService.cs:line 91
   at Ombi.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IMemoryCache cache, IServiceProvider serviceProvider) in C:\projects\requestplex\src\Ombi\Startup.cs:line 185
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Ombi.Program.Main(String[] args) in C:\projects\requestplex\src\Ombi\Program.cs:line 94
Aborted
```

The next time i run ombi it works, but there are issues.

It loads via my nginx proxypass but does not properly load as it would if i set it manually.

![4](https://user-images.githubusercontent.com/16525024/39095289-e470309c-4635-11e8-9d34-30356de9ae4e.jpg)

The i cannot actually get past this stage.

![57](https://user-images.githubusercontent.com/16525024/39095294-129eee22-4636-11e8-9238-756227d84f35.jpg)

It seems we are almost there but something is not quite right just yet.

**Comment by tidusjar** [comment]
Damn! It was working fine for me!
