### ISSUE TITLE
Mattermost notification fails

### ISSUE THREAD

**Issue by gfriloux** [tidusjar/Ombi#2175]
#### Ombi build Version:

Version 3.0.3185
Using latest docker image from https://hub.docker.com/r/linuxserver/ombi/

#### Branch

master

#### Media Sever:

Emby

#### Mattermost version:

4.9.0

#### Operating System:

GNU/Linux

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2018-04-19 23:58:18.558 +02:00 [Error] Failed to send Mattermost Notification
System.ArgumentNullException: Value cannot be null.
Parameter name: uriString
   at System.Uri..ctor(String uriString)
   at Ombi.Notifications.Agents.MattermostNotification.<Send>d__19.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Agents\MattermostNotification.cs:line 201

```

#### Problem Description:

Trying to setup mattermost notifications.
WebUI says its OK, but message never arrives, and logs says it failed.

#### Reproduction Steps:
Go to Settings / Notifications / Mattermost.
Set the Incoming Webhook Url.

Click the `Test` button.
It will send a query to https://ombi.fqdn/api/v1/tester/mattermost with following data : 
```
channel |  
enabled | true
iconUrl | null
username | Ombi
webhookUrl | https://mattermost.fqdn/hooks/kz456r77xigx8y1ero8gsdfjsc
```
This http call returns a 200 code, and "true".
Logs says theres an error.

Inside the SQLite DB, the GlobalSettings contains what seems to be a valid entry : 
```
6|{"WebhookUrl":"https://mattermost.fqdn/hooks/kz456r77xigx8y1ero8gsdfjsc","Channel":"","Username":"Ombi","Enabled":true,"Id":6}|MattermostNotificationSettings
```

Triggering events also doesnt end up sending notifications to mattermost.

**Comment by tidusjar** [comment]
You can find the version of the settings about page.

**Comment by gfriloux** [comment]
Hu, i am very tired those days... It was in front of me !
I update my first comment.

**Comment by tidusjar** [comment]
Do you have an IconURL? Does it work if you add it?

**Comment by gfriloux** [comment]
Ok i have set a channel and an icon to make sure there is nothing empty.
The Web UI still says everything is OK.

Inside the Ombi logs, i get : 
```
2018-04-20 12:13:50.687 +02:00 [Error] Failed to send Mattermost Notification
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Api.Mattermost.Models.MatterhookClient.<PostAsync>d__5.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Mattermost\Models\MattermostClient.cs:line 164
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Mattermost.MattermostApi.<PushAsync>d__2.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Mattermost\MattermostApi.cs:line 20
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.Agents.MattermostNotification.<Send>d__19.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Agents\MattermostNotification.cs:line 216
```

inside Ombi's SQLite DB, i have : 
```
6|{"WebhookUrl":"https://mattermost.fqdn/hooks/kz456r77xigx8y1ero8gsdfjsc","Channel":"Demandes","Username":"Ombi","IconUrl":"https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/ombi.png","Enabled":true,"Id":6}|MattermostNotificationSettings
```

This time, mattermost complains (on the original post, there wasnt any query sent to mattermost) : 
```
[2018/04/20 12:03:29 CEST] [EROR] /hooks/r461ocj4giy88piutbzhm3r65o:IncomingWebhookRequestFromJson code=400 rid=r4kreqkb1fdb7jdds7ymikhdfw uid= ip=172.17.0.4 Unable to parse incoming data [details: unexpected EOF]
```

**Comment by gravufo** [comment]
I also have this issue:
```
fail: Ombi.Notifications.Agents.MattermostNotification[4004]
      Failed to send Mattermost Notification
System.ArgumentNullException: Value cannot be null.
Parameter name: uriString
   at System.Uri..ctor(String uriString)
   at Ombi.Notifications.Agents.MattermostNotification.<Send>d__19.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Agents\MattermostNotification.cs:line 201
```

On top of that, the message that is displayed in the UI when testing the connection is as follows: "Successfully sent a Mattermost message, please check the **discord** channel". It should not say "discord channel".

**Comment by gfriloux** [comment]
In this case, it should not even say "Successfully sent" =)

**Comment by gfriloux** [comment]
I use a docker image for Ombi (https://hub.docker.com/r/linuxserver/ombi/), and not going to break my infra for this.

But, if you need to make tests, i can probably send you a webhook URL to my own mattermost instance so you can try.

**Comment by anojht** [comment]
This has been fixed in develop. Thanks to @gfriloux for helping us resolve this!
