### ISSUE TITLE
Not able to send Newsletter

### ISSUE THREAD

**Issue by MiuiSwitzerland** [tidusjar/Ombi#2188]
#### Ombi build Version:

V 3.0.3223
--

#### Open Beta Branch:

Dev

#### Media Sever:

Plex

#### Operating System:

Ubuntu 16.4

#### Syslog Error:

```
Apr 23 22:59:54 Plex-Server Ombi[5311]:       Error when attempting to create newsletter
Apr 23 22:59:54 Plex-Server Ombi[5311]: System.FormatException: Input string was not in a correct format.
Apr 23 22:59:54 Plex-Server Ombi[5311]:    at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
Apr 23 22:59:54 Plex-Server Ombi[5311]:    at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
Apr 23 22:59:54 Plex-Server Ombi[5311]:    at lambda_method(Closure , ValueBuffer )
Apr 23 22:59:54 Plex-Server Ombi[5311]:    at System.Linq.Enumerable.WhereEnumerableIterator`1.GetCount(Boolean onlyIfCheap)
Apr 23 22:59:54 Plex-Server Ombi[5311]:    at lambda_method(Closure , QueryContext )
Apr 23 22:59:54 Plex-Server Ombi[5311]:    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass17_1`1.<CompileQueryCore>b__0(QueryContext qc)
Apr 23 22:59:54 Plex-Server Ombi[5311]:    at System.Linq.Queryable.Count[TSource](IQueryable`1 source)
Apr 23 22:59:54 Plex-Server Ombi[5311]:    at Ombi.Schedule.Jobs.Ombi.NewsletterJob.<Start>d__13.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\NewsletterJob.

```

#### Problem Description:

This happens on a new install. Just Ombi.db and Schedule.db were reused.

#### Reproduction Steps:

nothing here, no errors on the web-interface.

**Comment by elit3ge** [comment]
I think this may be simular as #2134

**Comment by tidusjar** [comment]
Fixed in develop
