### ISSUE TITLE
'/var/empty/.dotnet/corefx/cryptography/x509stores/ca' is denied.

### ISSUE THREAD

**Issue by DamienNightbane** [tidusjar/Ombi#2196]
#### Ombi build Version:

V 3.0.3185

#### Update Branch:

Master

#### Media Sever:

Plex

#### Media Server Version:

1.12.3.4973

#### Operating System:

Ubuntu 16.04.4 LTS

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

2018-04-25 16:59:55.311 -04:00 [Error] Could not test Plex
System.UnauthorizedAccessException: Access to the path '/var/empty/.dotnet/corefx/cryptography/x509stores/ca' is denied. ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.UnixFileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Internal.Cryptography.Pal.DirectoryBasedStoreProvider.Add(ICertificatePal certPal)
   at System.Security.Cryptography.X509Certificates.X509Store.Add(X509Certificate2 certificate)
   at Internal.Cryptography.Pal.ChainPal.SaveIntermediateCertificates(X509ChainElement[] chainElements, HashSet`1 downloaded)
   at Internal.Cryptography.Pal.ChainPal.BuildChain(Boolean useMachineContext, ICertificatePal cert, X509Certificate2Collection extraStore, OidCollection applicationPolicy, OidCollection certificatePolicy, X509RevocationMode revocationMode, X509RevocationFlag revocationFlag, DateTime verificationTime, TimeSpan timeout)
   at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate, Boolean throwOnException)
   at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate)
   at System.Net.Security.CertificateValidation.BuildChainAndVerifyProperties(X509Chain chain, X509Certificate2 remoteCertificate, Boolean checkCertName, String hostName)
   at System.Net.Http.CurlHandler.SslProvider.VerifyCertChain(SafeX509StoreCtxHandle storeCtx, EasyRequest easy)
   at System.Net.Http.CurlHandler.SslProvider.VerifyCertChain(IntPtr storeCtxPtr, IntPtr curlPtr)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.OmbiHttpClient.<SendAsync>d__5.MoveNext() in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Api.<Request>d__6`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Plex.PlexApi.<GetStatus>d__9.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<Plex>d__58.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 239

#### Problem Description:

When I hit the Test Connectivity button on the Plex Configuration Page it is not able to connect. I suspect /var/empty/ may be the problem.

#### Reproduction Steps:

1. Configure Plex with SSL (including ignore SSL)
2. Test Connectivity

**Comment by tidusjar** [comment]
Can you give ombi permission to that?

**Comment by DamienNightbane** [comment]
/var/empty doesn't exist...I can create but will it auto create the rest?

![image](https://user-images.githubusercontent.com/38737693/39276448-0bd92c00-48b7-11e8-8d19-bbaedf5eccf5.png)

**Comment by tidusjar** [comment]
This is a .net core thing and not ombi so I'm not sure. Give it a go.

**Comment by DamienNightbane** [comment]
Creating /var/empty and setting permissions as below fixed it!

![image](https://user-images.githubusercontent.com/38737693/39276865-f98732e8-48b8-11e8-85ee-98c9b0557d2d.png)

Thanks for the quick response I was a little skeptical about /var/empty......wasn't sure if that actually was intended or should have been a different directory.
