### ISSUE TITLE
Can't connect to Plex Media Server

### ISSUE THREAD

**Issue by mindfrost82** [tidusjar/Ombi#2206]
#### Ombi build Version:

V 3.0.3255

#### Update Branch:

Developer

#### Media Sever:

Plex

#### Media Server Version:

1.12.3.4973

#### Operating System:

Windows 10 Creators Update Enterprise x64

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2018-04-27 20:17:01.325 -05:00 [Error] Could not test Plex
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A connection with the server could not be established
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.OmbiHttpClient.<SendAsync>d__5.MoveNext() in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Api.<Request>d__6`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Plex.PlexApi.<GetStatus>d__13.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 84
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<Plex>d__58.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 239

```

#### Problem Description:

Upgraded to 3255 and it fixed the Plex Auth Token when setting it up, but I can't get it to connect to my Plex server, even using a LAN IP with the correct port.

Logging in with my Plex account detects the servers, but using the Load Libraries and Test Connection buttons both fail.

#### Reproduction Steps:

Tried LAN IP and host name.  Port is open.  Tried SSL on and off.

**Comment by mindfrost82** [comment]
I'm not sure what was different, but I was able to manually create a new entry and it worked.
