### ISSUE TITLE
Ombi can not connect to PMS

### ISSUE THREAD

**Issue by steve18275** [tidusjar/Ombi#2210]
<!--- 

!! Please use the Support / bug report template, otherwise we will close the Github issue !!

#### Ombi build Version:

3.0.3239 (New Update Available)

Issue for another task, it wont let me update 

#### Update Branch:

Open 

#### Media Sever:

Plex

#### Media Server Version:

1.12.3.4973

#### Operating System:

Win 10 Pro, for both machine Ombi is installed on and PMS

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2018-04-28 16:10:25.180 -04:00 [Error] Could not test Plex
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A security error occurred
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.OmbiHttpClient.<SendAsync>d__5.MoveNext() in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Api.<Request>d__6`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Plex.PlexApi.<GetStatus>d__13.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 84
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<Plex>d__58.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 239

```

#### Problem Description:

I have ombi installed on machine 1 and it will connect to any of the servers i have locally. 
I do require SSL for PMS and i have tested with that on and off no luck. 
Router is pfsense. 

#### Reproduction Steps:

Simply click test connectivity within ombi with IP and port entered manually

**Comment by tidusjar** [comment]
All the log tells me is A security error occurred.

You have also not filled out the whole template.
