### ISSUE TITLE
Could not connect to CouchPotato

### ISSUE THREAD

**Issue by angarod** [tidusjar/Ombi#2212]
#### Ombi build Version:

V  3.0.3274 

#### Update Branch:

develop

#### Media Sever:

Plex

#### Operating System:

Debian Stretch 

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2018-04-30 18:44:38.063 +02:00 [Error] Could not test CP
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.OmbiHttpClient.<SendAsync>d__5.MoveNext() in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Api.<Request>d__6`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.CouchPotato.CouchPotatoApi.<Status>d__4.MoveNext() in C:\projects\requestplex\src\Ombi.Api.CouchPotato\CouchPotatoApi.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<CouchPotato>d__62.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 323


```

#### Problem Description:

Ombi cannot connect to CP.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by anojht** [comment]
Hello are you still facing this problem on the latest version?

**Comment by Indebt1** [comment]
Having same issue with sonarr and radarr.  Same error messages but replace couchpotato with sonarr.
On build version 3313.

**Comment by anojht** [comment]
@angarod did you click the get quality profiles button select a profile and save before hitting test conneciton?
