### ISSUE TITLE
Newsletter issue, Movies are found, tv shows aren't

### ISSUE THREAD

**Issue by ThePierce** [tidusjar/Ombi#2217]
#### Ombi build Version:

V 3.0.3268
-- | --

#### Update Branch:

Master

#### Media Sever:

Plex 

#### Media Server Version:

1.3.0.5003

#### Operating System:

Ubuntu 16.04

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2018-05-01 11:19:14.333 +02:00 [Information] Plex Movies to send: 228
2018-05-01 11:19:14.344 +02:00 [Information] Emby Movies to send: 0
2018-05-01 11:19:15.848 +02:00 [Information] Plex Episodes to send: 0
2018-05-01 11:19:15.849 +02:00 [Information] Emby Episodes to send: 0
2018-05-01 11:19:17.093 +02:00 [Error] StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://api.tvmaze.com/lookup/shows?thetvdb=0
2018-05-01 11:19:17.118 +02:00 [Error] Error when processing Plex TV "Flashpoint"
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.<ProcessPlexTv>d__22.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\NewsletterJob.cs:line 500
2018-05-01 11:47:46.461 +02:00 [Information] Plex Movies to send: 228
2018-05-01 11:47:46.462 +02:00 [Information] Emby Movies to send: 0
2018-05-01 11:47:47.910 +02:00 [Information] Plex Episodes to send: 0
2018-05-01 11:47:47.911 +02:00 [Information] Emby Episodes to send: 0
2018-05-01 11:47:48.965 +02:00 [Error] StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://api.tvmaze.com/lookup/shows?thetvdb=0
2018-05-01 11:47:48.965 +02:00 [Error] Error when processing Plex TV "Flashpoint"
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.<ProcessPlexTv>d__22.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\NewsletterJob.cs:line 500
2018-05-01 12:18:18.395 +02:00 [Information] Plex Movies to send: 228
2018-05-01 12:18:18.398 +02:00 [Information] Emby Movies to send: 0
2018-05-01 12:18:20.059 +02:00 [Information] Plex Episodes to send: 0
2018-05-01 12:18:20.060 +02:00 [Information] Emby Episodes to send: 0
2018-05-01 12:18:21.201 +02:00 [Error] StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://api.tvmaze.com/lookup/shows?thetvdb=0
2018-05-01 12:18:21.205 +02:00 [Error] Error when processing Plex TV "Flashpoint"
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.<ProcessPlexTv>d__22.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\NewsletterJob.cs:line 500



```

#### Problem Description:

When i try to send out a newsletter test, i receive an email. In that email i see my recently added movies, but Ombi can't find my recently added TV Shows/Episodes

#### Reproduction Steps:

Manually update plex database ==> send newsletter test.

**Comment by tidusjar** [comment]
Are TV shows being added?

There are lots of fixes and improvements in the develop branch. Can you try that out?

**Comment by ThePierce** [comment]
TV shows are added, your develop branch tip worked :) tnx!
