### ISSUE TITLE
Plex Cacher not catching everything

### ISSUE THREAD

**Issue by jasonlyle88** [tidusjar/Ombi#2244]
#### Ombi build Version:

V 3.0.3304

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

1.13.0.5023

#### Operating System:

```
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
```

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
Not sure what logs would be relevant here. If you let me know, I will be happy to provide them

```

#### Problem Description:

Ombi does not show either of the "It" movies (1990 and 2017) as being available. I have tried running a full sync with the movies both not requested or both requested and it has made no difference, they always show up as not available.

#### Reproduction Steps:

Add "It" movies to Plex, sync to Ombi.

**Comment by tidusjar** [comment]
Can you check if they are in the PlexServerContent table

**Comment by jasonlyle88** [comment]
@tidusjar I would be happy to do that if you can walk me through how to do it.

**Comment by tidusjar** [comment]
Use SQLite (depending on your OS) and open up the `Ombi.db` and go to the tables mentioned above

**Comment by jasonlyle88** [comment]
Easy enough. Both are in that table. Below is the information from sqlman

```
"Id"  , "AddedAt"                     , "ImdbId", "Key"   , "Quality" , "ReleaseYear" , "TheMovieDbId", "Title" , "TvDbId", "Type", "Url"
"1814", "2018-02-07 15:20:06.2761197" , ""      , "33454" , "1080"    , "2017"        , ""            , "It"    , ""      , "0"   , "https://app.plex.tv/web/app#!/server/[REMOVED FOR SECURITY]/details?key=library%2Fmetadata%2F33454"
"1929", "2018-02-22 05:20:39.9181145" , ""      , "36699" , "1080"    , "1990"        , "477433"      , "It"    , ""      , "0"   , "https://app.plex.tv/web/app#!/server/[REMOVED FOR SECURITY]/details?key=library%2Fmetadata%2F36699"

```

**Comment by tidusjar** [comment]
It's because at each don't seem to have much info on them. 

Ideally we want a MovieDbId and ImdbId. Can you run the refresh metadata and then check the table after? Give it a good 10 mins just to be sure

**Comment by jasonlyle88** [comment]
I wasn't sure where you meant, so I refreshed the metadata on Plex, waited 10 minutes, then went in to Ombi and clicked "Manually Run Full Sync" (I believe that triggers a metadata refresh in Ombi as well), waited 10 minutes, and then checked Ombi.db. No change, both rows are exactly the same.

**Comment by tidusjar** [comment]
Ok. There should be some logs from the metadata refresh. Stuff like looking for IMDb for X title

**Comment by jasonlyle88** [comment]
This is from a full metadata refresh. I stopped the service, deleted logs, started the service and let it run all the way through. Stopped the service and copied the logs.

[https://www.dropbox.com/s/afl9r5u4ogii4ft/ombi3_log.log?dl=0](https://www.dropbox.com/s/afl9r5u4ogii4ft/ombi3_log.log?dl=0)

**Comment by d4rk22** [comment]
I am experiencing this same issue. I have a very large library with around 65TB of content. I've noticed that if I manually run a recently added sync, those items appear correctly as Available but a full sync does not add the back catalog items.

Ombi build Version:

V 3.0.3330

Update Branch:

master

Media Sever:

Plex
Media Server Version:

3.0.3330
Operating System:

Ubuntu 16.04
Linux 4.4.0-124-generic #148-Ubuntu SMP

**Comment by jasonlyle88** [comment]
This is is still an issue with me on the latest stable (3.0.3346).

I see the following in the logs (not sure if it has anything to do with this issue or not):

```
warn: Ombi.Schedule.Jobs.Plex.PlexContentSync[2008]
      Exception thrown when attempting to cache the Plex Content in server pendragon-plex
System.InvalidOperationException: The instance of entity type 'PlexServerContent' cannot be tracked because another instance with the same key value for {'Key'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph(EntityEntryGraphNode node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityStates(IEnumerable`1 entities, EntityState entityState)
   at Ombi.Store.Repository.Repository`1.<AddRange>d__8.MoveNext() in C:\projects\requestplex\src\Ombi.Store\Repository\Repository.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.<ProcessServer>d__21.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 216
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.<StartTheCache>d__20.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 136

```

Furthermore, `Cobra Kai` is in Plex, but does not show as available in Ombi. I noticed the following lines in regards to `Cobra Kai`:
```
warn: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[0]
      The episode title Ace Degenerate we cannot find the parent series. The episode grandparentKey = 43206, grandparentTitle = Cobra Kai
warn: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[0]
      The episode title Strike First we cannot find the parent series. The episode grandparentKey = 43206, grandparentTitle = Cobra Kai
warn: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[0]
      The episode title Esqueleto we cannot find the parent series. The episode grandparentKey = 43206, grandparentTitle = Cobra Kai
warn: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[0]
      The episode title Cobra Kai Never Dies we cannot find the parent series. The episode grandparentKey = 43206, grandparentTitle = Cobra Kai
warn: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[0]
      The episode title Counterbalance we cannot find the parent series. The episode grandparentKey = 43206, grandparentTitle = Cobra Kai
warn: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[0]
      The episode title Quiver we cannot find the parent series. The episode grandparentKey = 43206, grandparentTitle = Cobra Kai
warn: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[0]
      The episode title All Valley we cannot find the parent series. The episode grandparentKey = 43206, grandparentTitle = Cobra Kai
warn: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[0]
      The episode title Molting we cannot find the parent series. The episode grandparentKey = 43206, grandparentTitle = Cobra Kai
warn: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[0]
      The episode title Different but Same  we cannot find the parent series. The episode grandparentKey = 43206, grandparentTitle = Cobra Kai
warn: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[0]
      The episode title Mercy we cannot find the parent series. The episode grandparentKey = 43206, grandparentTitle = Cobra Kai

```
