### ISSUE TITLE
Database is Locked

### ISSUE THREAD

**Issue by maxpower47** [tidusjar/Ombi#2253]
#### Ombi build Version:

V 3.0.3304-master

#### Media Sever:

Plex

#### Operating System:

[Linuxserver.io image](https://hub.docker.com/r/linuxserver/ombi/) on Ubuntu 16.04 host

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```


Application startup exception: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlCommand(DatabaseFacade databaseFacade, RawSqlString sql, IEnumerable`1 parameters)
   at Ombi.Store.Context.OmbiContext.Seed() in C:\projects\requestplex\src\Ombi.Store\Context\OmbiContext.cs:line 107
   at Ombi.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IMemoryCache cache, IServiceProvider serviceProvider) in C:\projects\requestplex\src\Ombi\Startup.cs:line 206
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

Unhandled Exception: Microsoft.Data.Sqlite.SqliteException: SQLite Error 5: 'database is locked'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlCommand(DatabaseFacade databaseFacade, RawSqlString sql, IEnumerable`1 parameters)
   at Ombi.Store.Context.OmbiContext.Seed() in C:\projects\requestplex\src\Ombi.Store\Context\OmbiContext.cs:line 107
   at Ombi.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IMemoryCache cache, IServiceProvider serviceProvider) in C:\projects\requestplex\src\Ombi\Startup.cs:line 206
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Ombi.Program.Main(String[] args) in C:\projects\requestplex\src\Ombi\Program.cs:line 94

```

#### Problem Description:

After updating the image, application locks up shortly after startup.  Sometimes it will never load, sometimes the login page will load but will not actually allow logging in.

**Comment by Pahiro** [comment]
Double check to make sure db isn't read only. sudo chmod 755 /opt/Ombi -R, then check to make sure nothing else is locking the db using sudo fuser /opt/Ombi/Ombi.db. Use sudo to make sure you read all processes. If there's more than one, find out more info about the process or just do a kill -9. Lastly, copy the db and overwrite it with the copy. This will de-reference all locks.

**Comment by rustymyers** [comment]
This seems to occur for me when a docker container is restarted while some job is running. It created an Ombi.db-journal file and kept restarting with the database lock error.

**Comment by SlothCroissant** [comment]
Can confirm this is happening on rogueosb/ombi as well still.

Previous issue I had on it: https://github.com/tidusjar/Ombi/issues/2214

**Comment by gravufo** [comment]
I just hit the issue today. I basically tried restarting the container (there was probably a job running) and it got locked. I couldn't get the service back up, but I restarted the whole server (probably could've just restarted the docker daemon, but I was being lazy) and then the container was able to start.

**Comment by tidusjar** [comment]
Is this happening with the latest update?

**Comment by SlothCroissant** [comment]
Rebuilding container, will try to reproduce the issue. My containers only restart nightly for UnRAID backups normally, but will look to trigger it manually if possible.

**Comment by rustymyers** [comment]
I have not had the issue occur in the past few days after updating.

**Comment by aptalca** [comment]
Several issues I had with sqlite in the past:

1) Don't put sqlite (config folder) on a remote share, it has to be local
2) On unraid, try putting the config folder on /mnt/cache or /mnt/disk, and not /mnt/user (sqlite also doesn't like FUSE very much)
3) On unraid, if you have a btrfs cache pool, large sustained writes to the cache pool can cause an io spike, during which time the apps will not be able to access the database (VM will also pause and such)
