### ISSUE TITLE
TV Shows can't be cached.

### ISSUE THREAD

**Issue by 4everfun** [tidusjar/Ombi#2261]
#### Ombi build Version:

V 3.0.3330

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Ubuntu 18.04

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
warn: Ombi.Schedule.Jobs.Plex.PlexContentSync[2008]
      Exception thrown when attempting to cache the Plex Content in server Plex
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> Microsoft.Data.Sqlite.SqliteException: SQLite Error 19: 'UNIQUE constraint failed: PlexServerContent.Id'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.<ExecuteDbDataReaderAsync>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.<ExecuteAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.<ExecuteAsync>d__32.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.<ExecuteAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.<ExecuteAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__61.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.DbContext.<SaveChangesAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Store.Repository.Repository`1.<AddRange>d__8.MoveNext() in C:\projects\requestplex\src\Ombi.Store\Repository\Repository.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.<ProcessTvShow>d__22.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 480
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.<ProcessServer>d__21.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 187
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.<StartTheCache>d__20.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 136
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting EP Cacher
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Total Epsiodes found for TV = 14619
warn: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[0]
      The episode title Pilot we cannot find the parent series. The episode grandparentKey = 5418, grandparentTitle = 2 Broke Girls
warn: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[0]
      The episode title And the Break-up Scene we cannot find the parent series. The episode grandparentKey = 5418, grandparentTitle = 2 Broke Girls
warn: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[0]
      The episode title And Strokes of Goodwill we cannot find the parent series. The episode grandparentKey = 5418, grandparentTitle = 2 Broke Girls

```

#### Problem Description:

The TV shows are not properly cached. When I search for a show that's already added on Plex it appears to be not in Ombi. This problem does not appear when dealing with movies.

#### Reproduction Steps:

This happens when I try to manually refresh the Plex cache from the Media Server tab. I already tried deleting the whole the PlexEpisode and PlexServerContent tables and even deleting the whole database.

**Comment by tidusjar** [comment]
Can you please delete all the records from your PlexServerContent, PleaseSeasons and PlexEpisodes table in the ombi.db

**Comment by 4everfun** [comment]
Unfortunately, it gives the same error. I even tried deleting the database and reconfigure everything.

**Comment by etheralm** [comment]
Sorry I forgot to mention that apart from the parent warnings I also get the same exception: 

`Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> Microsoft.Data.Sqlite.SqliteException: SQLite Error 19: 'UNIQUE constraint failed: PlexServerContent.Id'.`

**Comment by etheralm** [comment]
Thank you! I can confirm that it works fine in the latest version.
