### ISSUE TITLE
Docker - SQLite Error 14 - Unable to open database file.

### ISSUE THREAD

**Issue by Phelms215** [tidusjar/Ombi#2293]
#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
{"error":"SQLite Error 14: 'unable to open database file'."}
2018-05-31 04:44:48.146 +00:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: http://10.255.255.1:32400/
2018-05-31 04:44:48.201 +00:00 [Error] Could not test Plex
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.<Request>d__6`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 74
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Plex.PlexApi.<GetStatus>d__13.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 84
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<Plex>d__61.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 242
2018-05-31 04:46:12.684 +00:00 [Debug] Search Result: "Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult,
Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult"
2018-05-31 04:46:31.832 +00:00 [Debug] Search Result: "Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult,
Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult"
```

#### Problem Description:
Randomly - when attempting to visit OMBI website loading takes a while and eventually fails with error message below. Not sure how to get logs in the docker container.

{"error":"SQLite Error 14: 'unable to open database file'."}

#### Reproduction Steps:
Waiting game and it crashes on its own. Restarting container solves the problem for a short while.

**Comment by tidusjar** [comment]
Strange. Do you have any other processes that might be accessing the file,

Which docker container are you using

**Comment by Trenchguns** [comment]
Coming into same issue:
Application startup exception: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 14: 'unable to open database file'.
at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader)
at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command)
at Hangfire.SQLite.SQLiteWriteOnlyTransaction.<>c__DisplayClass19_0.<SetRangeInHash>b__0(DbConnection connection, DbTransaction transaction)
at Hangfire.SQLite.SQLiteWriteOnlyTransaction.<Commit>b__3_0(DbConnection connection, DbTransaction transaction)
at Hangfire.SQLite.SQLiteStorage.<>c__DisplayClass21_0.<UseTransaction>b__0(DbConnection connection, DbTransaction transaction)
at Hangfire.SQLite.SQLiteStorage.<>c__DisplayClass22_0`1.<UseTransaction>b__0(DbConnection connection)
at Hangfire.SQLite.SQLiteStorage.UseConnection[T](Func`2 func, Boolean isWriteLock)
at Hangfire.SQLite.SQLiteStorage.UseTransaction[T](Func`3 func, Nullable`1 isolationLevel)
at Hangfire.SQLite.SQLiteStorage.UseTransaction(Action`2 action)
at Hangfire.RecurringJobManager.AddOrUpdate(String recurringJobId, Job job, String cronExpression, RecurringJobOptions options)
at Ombi.Schedule.JobSetup.Setup() in C:\projects\requestplex\src\Ombi.Schedule\JobSetup.cs:line 58
at Ombi.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IMemoryCache cache, IServiceProvider serviceProvider) in C:\projects\requestplex\src\Ombi\Startup.cs:line 208
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

Unhandled Exception: Microsoft.Data.Sqlite.SqliteException: SQLite Error 14: 'unable to open database file'.
at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader)
at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command)
at Hangfire.SQLite.SQLiteWriteOnlyTransaction.<>c__DisplayClass19_0.<SetRangeInHash>b__0(DbConnection connection, DbTransaction transaction)
at Hangfire.SQLite.SQLiteWriteOnlyTransaction.<Commit>b__3_0(DbConnection connection, DbTransaction transaction)
at Hangfire.SQLite.SQLiteStorage.<>c__DisplayClass21_0.<UseTransaction>b__0(DbConnection connection, DbTransaction transaction)
at Hangfire.SQLite.SQLiteStorage.<>c__DisplayClass22_0`1.<UseTransaction>b__0(DbConnection connection)
at Hangfire.SQLite.SQLiteStorage.UseConnection[T](Func`2 func, Boolean isWriteLock)
at Hangfire.SQLite.SQLiteStorage.UseTransaction[T](Func`3 func, Nullable`1 isolationLevel)
at Hangfire.SQLite.SQLiteStorage.UseTransaction(Action`2 action)
at Hangfire.RecurringJobManager.AddOrUpdate(String recurringJobId, Job job, String cronExpression, RecurringJobOptions options)
at Ombi.Schedule.JobSetup.Setup() in C:\projects\requestplex\src\Ombi.Schedule\JobSetup.cs:line 58
at Ombi.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IMemoryCache cache, IServiceProvider serviceProvider) in C:\projects\requestplex\src\Ombi\Startup.cs:line 208
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
at Ombi.Program.Main(String[] args) in C:\projects\requestplex\src\Ombi\Program.cs:line 94
Ombi 3.0.3376-develop


Running 3.0.3376, unraid docker.

**Comment by aptalca** [comment]
Is your config folder on a remote share? Sqlite hates being on a remote share. Put it on a local path.

If not, is your config folder on /mnt/user/blah? If so, try putting it on either /mnt/cache/blah or /mnt/diskX/blah because sqlite can also have issues with FUSE, which unraid uses for the array
