### ISSUE TITLE
we cannot find the parent series

### ISSUE THREAD

**Issue by dudeman27** [tidusjar/Ombi#2299]
#### Ombi build Version:

V 3.0.3368

#### Update Branch:

Master

#### Media Sever:

Plex

#### Media Server Version:

1.13.0.5023

#### Operating System:

Windows 10 64 bit

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

warn: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[0]
      The episode title Point of Impact we cannot find the parent series. The episode grandparentKey = 236794, grandparentTitle = Shooter
warn: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[0]
      The episode title Exfil we cannot find the parent series. The episode grandparentKey = 236794, grandparentTitle = Shooter
warn: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[0]
      The episode title Overwatch we cannot find the parent series. The episode grandparentKey = 236794, grandparentTitle = Shooter
warn: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[0]
      The episode title Recon By Fire we cannot find the parent series. The episode grandparentKey = 236794, grandparentTitle = Shooter
warn: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[0]
      The episode title Killing Zone we cannot find the parent series. The episode grandparentKey = 236794, grandparentTitle = Shooter
warn: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[0]
      The episode title Danger Close we cannot find the parent series. The episode grandparentKey = 236794, grandparentTitle = Shooter
warn: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[0]
      The episode title Red on Red we cannot find the parent series. The episode grandparentKey = 236794, grandparentTitle = Shooter
warn: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[0]
      The episode title Ballistic Advantage we cannot find the parent series. The episode grandparentKey = 236794, grandparentTitle = Shooter
warn: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[0]
      The episode title The Hunting Party we cannot find the parent series. The episode grandparentKey = 236794, grandparentTitle = Shooter
warn: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[0]
      The episode title Remember The Alamo we cannot find the parent series. The episode grandparentKey = 236794, grandparentTitle = Shooter
warn: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[0]
      The episode title Don't Mess with Texas we cannot find the parent series. The episode grandparentKey = 236794, grandparentTitle = Shooter
warn: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[0]
      The episode title The Dark End of the Street we cannot find the parent series. The episode grandparentKey = 236794, grandparentTitle = Shooter
warn: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[0]
      The episode title The Man Called Noon we cannot find the parent series. The episode grandparentKey = 236794, grandparentTitle = Shooter
warn: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[0]
      The episode title Across the Rio Grande we cannot find the parent series. The episode grandparentKey = 236794, grandparentTitle = Shooter
warn: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[0]
      The episode title Someplace Like Bolivia we cannot find the parent series. The episode grandparentKey = 236794, grandparentTitle = Shooter
warn: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[0]
      The episode title That'll Be the Day we cannot find the parent series. The episode grandparentKey = 236794, grandparentTitle = Shooter

```

This appears in the log files. When searching for it on TheMovieDB I'm able to find it:

```
2018-06-04 17:36:41.627 -06:00 [Debug] Searching : "Shooter"
2018-06-04 17:36:41.895 -06:00 [Debug] Search Result: "Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult"
2018-06-04 17:37:13.838 -06:00 [Debug] Searching : "Shoot"
2018-06-04 17:37:14.001 -06:00 [Debug] Search Result: "Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult"
2018-06-04 17:37:22.880 -06:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/293787
2018-06-04 17:37:23.897 -06:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/303499
2018-06-04 17:37:23.901 -06:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/315767
2018-06-04 17:37:24.172 -06:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/343393
2018-06-04 17:37:24.578 -06:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/83670
2018-06-04 17:39:31.358 -06:00 [Debug] Search Result: "Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult"
```

#### Problem Description:

When trying to run the full sync I receive the above error. It also happens for The Office (US)

#### Reproduction Steps:

Run the full sync

**Comment by dudeman27** [comment]
Oddly enough, I noticed this happening prior to the above error in the console. After removing this show from Plex, both Shooter and The Office now process successfully.

```
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      New show Marvel's The Punisher, so add it
warn: Ombi.Schedule.Jobs.Plex.PlexContentSync[2008]
      Exception thrown when attempting to cache the Plex Content in server David-PlexServer
System.InvalidOperationException: The instance of entity type 'PlexServerContent' cannot be tracked because another instance with the same key value for {'Key'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph(EntityEntryGraphNode node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityStates(IEnumerable`1 entities, EntityState entityState)
   at Ombi.Store.Repository.Repository`1.<AddRange>d__8.MoveNext() in C:\projects\requestplex\src\Ombi.Store\Repository\Repository.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.<ProcessServer>d__21.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 216
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.<StartTheCache>d__20.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 136
```
Feel free to close. I'm leaving it open in case you want more info.
