### ISSUE TITLE
Cannot connect to Radarr or Sonarr

### ISSUE THREAD

**Issue by lucidonlinenet** [tidusjar/Ombi#2346]
#### Ombi build Version:

V 3.0.3407

#### Update Branch:

Master

#### Media Sever:

Plex

#### Operating System:

Windows 10

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2018-06-20 18:55:16.877 +01:00 [Error] Could not test Radarr
System.Net.Http.HttpRequestException: The requested address is not valid in its context ---> System.Net.Sockets.SocketException: The requested address is not valid in its context
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request) in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
   at Ombi.Api.Radarr.RadarrApi.SystemStatus(String apiKey, String baseUrl) in C:\projects\requestplex\src\Ombi.Api.Radarr\RadarrApi.cs:line 44
   at Ombi.Controllers.External.TesterController.Radarr(RadarrSettings settings) in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 285

```

#### Problem Description:

Ombi can no longer connect to radarr or sonarr after latest update. Was working fine before today.

**Comment by lucidonlinenet** [comment]
Ok so I had to change radarr and sonarr to the IP and ports of the machine they and ombi are on.  Before I just had my public facing domain url (e.g. http://mydomain.com/radarr).

**Comment by fenduru** [comment]
I'm also running into this - it was working when I configured a few months ago but now it does not. I cannot specify an IP as sonarr and radarr are running in Docker containers behind an Nginx reverse proxy.

**Comment by jamjop** [comment]
Same things happening to me, worked before now it doesn’t. Guess I’ll reinstall ombi

**Comment by tidusjar** [comment]
Use develop branch

**Comment by theDwiz01** [comment]
Cant connect either.  Have Sonarr and Radarr on PC for years.  Installed Ombi today.  Copied over Radarr info, worked instantly. Copied over Sonarr and just says "Please check your entered values" when I test.  Tried "localhost" as well as internal and external IP.  I regularly use NZB360 which connects fine internally/externally.  Even changed my API in Sonarr to a new key to test that but still no luck. No SSL port is 8989 which is open by firewall.  Using 3.0.3587 (never used any previous version either).  Ideas?
