### ISSUE TITLE
Ombi Not Picking Up Newly Added Plex Assets 

### ISSUE THREAD

**Issue by mdthejericho** [tidusjar/Ombi#2348]
#### Ombi build Version:

V 3.0.3407

#### Update Branch:

master

#### Media Sever:

Plex

#### Media Server Version:

Version 1.12.0.4829 

#### Operating System:

Ubuntu 16.04

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

#033[40m#033[1m#033[33mwarn#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexContentSync[2008]
Jun 21 09:30:53 VPN Ombi[1213]:       Exception thrown when attempting to cache the Plex Content in server XXXXXXXXX
Jun 21 09:30:53 VPN Ombi[1213]: System.InvalidOperationException: The instance of entity type 'PlexServerContent' cannot be tracked because another instance with the same key value for {'Key'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
Jun 21 09:30:53 VPN Ombi[1213]:    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)
Jun 21 09:30:53 VPN Ombi[1213]:    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
Jun 21 09:30:53 VPN Ombi[1213]:    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
Jun 21 09:30:53 VPN Ombi[1213]:    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges)
Jun 21 09:30:53 VPN Ombi[1213]:    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Nullable`1 forceStateWhenUnknownKey)
Jun 21 09:30:53 VPN Ombi[1213]:    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode node, Boolean force)
Jun 21 09:30:53 VPN Ombi[1213]:    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode node, TState state, Func`3 handleNode)
Jun 21 09:30:53 VPN Ombi[1213]:    at Microsoft.EntityFrameworkCore.DbContext.SetEntityStates(IEnumerable`1 entities, EntityState entityState)
Jun 21 09:30:53 VPN Ombi[1213]:    at Ombi.Store.Repository.Repository`1.AddRange(IEnumerable`1 content, Boolean save) in C:\projects\requestplex\src\Ombi.Store\Repository\Repository.cs:line 41
Jun 21 09:30:53 VPN Ombi[1213]:    at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessServer(PlexServers servers, Boolean recentlyAddedSearch) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 184
Jun 21 09:30:53 VPN Ombi[1213]:    at Ombi.Schedule.Jobs.Plex.PlexContentSync.StartTheCache(PlexSettings plexSettings, Boolean recentlyAddedSearch) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 132



```

#### Problem Description:

Ombi does not detect any additions to Plex which means the Ombi database never gets updated and users do not get emails when requests are fulfilled. 

#### Reproduction Steps:

None. It was working fine and then this started about two weeks ago? 

Looking at this https://github.com/tidusjar/Ombi/issues/1582 I do have "Ignore Certificate Errors" checked.

**Comment by tidusjar** [comment]
Can you PM me on Discord please?

**Comment by tidusjar** [comment]
Fixed in develop
