### ISSUE TITLE
Ombi + Sonarr - Shows Added have no watched episodes when All is requested.

### ISSUE THREAD

**Issue by clovisd** [tidusjar/Ombi#2371]
#### Ombi build Version:
v 3.0.3421
#### Update Branch:
DEBIAN REPO
#### Media Sever:
Plex v 1.13.3.5223
Sonarr v 2.0.0.5228
Mono v 5.12.0.226
#### Operating System:
Ubuntu 17.04x
#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):
```
2018-07-01 19:16:07.404 -05:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/332747
2018-07-01 19:16:16.387 -05:00 [Error] Exception thrown when attempting to send series over to Sonarr
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSeries result, SonarrSettings s) in C:\projects\requestplex\src\Ombi.Core\Senders\TvSender.cs:line 257
   at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model) in C:\projects\requestplex\src\Ombi.Core\Senders\TvSender.cs:line 190
```
#### Problem Description:
When shows are requested in Ombi by either someone with AutoApprove or a request gets approved, the show gets added to Sonarr but no episodes are requested. See screenshots:
1. https://cdn.discordapp.com/attachments/375036155206434816/463139642410139649/unknown.png
2. https://cdn.discordapp.com/attachments/375036155206434816/463147727967223809/unknown.png

This was tested with multiple tv series but in all tests, I tried adding shows that weren't watched by Sonarr or had ever been seen by Sonarr before (brand new) and in all cases, I requested all seasons and episodes.

#### Reproduction Steps:
1. Get the latest version of Sonarr
2. Get the latest version of Ombi
3. Link them Up
4. Request a Show
5. Voila!

**Comment by clovisd** [comment]
This might be related: #2359

**Comment by tidusjar** [comment]
Fixed in develop

**Comment by clovisd** [comment]
This seems to still be happening for shows being approved in Ombi that where added before this update.

Not too big an issue but still.

**Comment by goldenpipes** [comment]
was this the same issue?

seems a lot like it.
https://www.youtube.com/watch?v=b3rA8BIbToM&feature=youtu.be

request show as admin, all is well.
request show as non-admin, marks latest season as monitored but no episodes.
