### ISSUE TITLE
Ombi refuses to start

### ISSUE THREAD

**Issue by RikT** [tidusjar/Ombi#2373]
#### Ombi build Version:

V 3.0.3421

#### Update Branch:

Master

#### Media Sever:

Plex

#### Media Server Version:

1.13.2.5154

#### Operating System:

Ubuntu 18.04

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
/opt/Ombi/Ombi --baseurl /ombi --host http://127.0.0.1:3000
Hello, welcome to Ombi
Valid options are:
Ombi 3.0.3421-master
Copyright (C) 2018 Ombi

  --host       (Default: http://*:5000) Set to a semicolon-separated (;) list
               of URL prefixes to which the server should respond. For example,
               http://localhost:123. Use "*" to indicate that the server should
               listen for requests on any IP address or hostname using the
               specified port and protocol (for example, http://*:5000). The
               protocol (http:// or https://) must be included with each URL.
               Supported formats vary between servers.

  --storage    Storage path, where we save the logs and database

  --baseurl    The base URL for reverse proxy scenarios

  --help       Display this help screen.

  --version    Display version information.



We are running on http://127.0.0.1:3000

Unhandled Exception: System.ArgumentOutOfRangeException: Version's parameters must be greater than or equal to zero.
Parameter name: revision
   at System.Version..ctor(Int32 major, Int32 minor, Int32 build, Int32 revision)
   at System.Environment.<>c.<.cctor>b__79_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.AspNetCore.Hosting.WebHostBuilderIISExtensions.UseIISIntegration(IWebHostBuilder hostBuilder)
   at Microsoft.AspNetCore.WebHost.CreateDefaultBuilder(String[] args)
   at Ombi.Program.BuildWebHost(String[] args) in C:\projects\requestplex\src\Ombi\Program.cs:line 114
   at Ombi.Program.Main(String[] args) in C:\projects\requestplex\src\Ombi\Program.cs:line 94
Aborted (core dumped)

```

#### Problem Description:

Ombi will not start

**Comment by tidusjar** [comment]
Use -h

**Comment by RikT** [comment]
thats not very informative dude Use -h where as far as I can see that would be for help which gives no other info and just still continues to happen
