### ISSUE TITLE
SQLite Error 5: 'database is locked'.

### ISSUE THREAD

**Issue by soaringswine** [tidusjar/Ombi#2375]
#### Ombi build Version:

V 3.0.3421

#### Update Branch:

Master

#### Media Sever:

Plex

#### Operating System:

Windows 10 64 bit

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2018-07-06 17:52:22.947 -04:00 [Error] Could not test Plex
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at lambda_method(Closure )
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at Ombi.Settings.Settings.SettingsService`1.<GetSettings>b__10_0() in C:\projects\requestplex\src\Ombi.Settings\Settings\SettingsService.cs:line 32
   at Ombi.Helpers.CacheService.GetOrAdd[T](String cacheKey, Func`1 factory, DateTime absoluteExpiration) in C:\projects\requestplex\src\Ombi.Helpers\CacheService.cs:line 67
   at Ombi.Settings.Settings.SettingsService`1.GetSettings() in C:\projects\requestplex\src\Ombi.Settings\Settings\SettingsService.cs:line 29
   at Ombi.Api.Plex.PlexApi.get_ApplicationName() in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 35
   at Ombi.Api.Plex.PlexApi.AddHeaders(Request request) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 253
   at Ombi.Api.Plex.PlexApi.GetStatus(String authToken, String uri) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 83
   at Ombi.Controllers.External.TesterController.Plex(PlexServers settings) in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 242


```

#### Problem Description:

This issue comes up anytime Ombi tries to cache Radarr, Sonarr, or Plex. I've made sure that the Ombi folder is owned by the user running it, I've also tried running Ombi as administrator.

#### Reproduction Steps:

Start Ombi and wait.

**Comment by tidusjar** [comment]
Please update
