### ISSUE TITLE
Unable to login, Internal Error and missing token

### ISSUE THREAD

**Issue by Erbros** [tidusjar/Ombi#2376]
#### Ombi build Version:

V Ombi 3.0.3421-master

#### Update Branch:

master

#### Media Sever:

Plex

#### Media Server Version:

Version 1.13.2.5154

#### Operating System:

Ubuntu 

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

The logs don't say anything about the problem.
```

2018-07-06 23:03:25.043 +02:00 [Information] 1 scheduled job(s) enqueued.
2018-07-06 23:30:28.940 +02:00 [Information] 1 scheduled job(s) enqueued.
2018-07-06 23:31:44.278 +02:00 [Information] 1 scheduled job(s) enqueued.
2018-07-06 23:32:44.461 +02:00 [Information] 1 scheduled job(s) enqueued.


```

But the browser logs might tell a bit more:

When trying to use regular login:

```

vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1 POST http://[REDACTED]/ombi/api/v1/token/ 500 (Internal Server Error)

```

When trying to use Plex Authentication:

```

POST http://[REDACTED]/ombi/api/v1/token/ 500 (Internal Server Error)
ERROR 
e {headers: t, status: 500, statusText: "Internal Server Error", url: "http://[REDACTED]/ombi/api/v1/token/", ok: false, …}
error
:
{error: "Request headers must contain only ASCII characters."}
headers
:
t {normalizedNames: Map(0), lazyUpdate: null, lazyInit: ƒ}
message
:
"Http failure response for http://[REDACTED]/ombi/api/v1/token/: 500 Internal Server Error"
name
:
"HttpErrorResponse"
ok
:
false
status
:
500
statusText
:
"Internal Server Error"
url
:
"http://[REDACTED]/ombi/api/v1/token/"

```

#### Problem Description:

I were able to login with both methods previously, suddenly I wasn't able to anymore. No changes to configuration or anything. I checked the .db, and see that the token-table is empty, not sure if that might be a problem or if that's how it's supposed to be. Is there any way to give myself a local password I can login with through the database?

#### Reproduction Steps:

To be honest, not really sure. I imported my users, enabled plex auth and had everything working for a week.

**Comment by Erbros** [comment]
Btw, forgot to mention that I also checked if this might be due to the reverse proxy, but same issue on http://localhost:3579/ombi/login

**Comment by Erbros** [comment]
Sorry, got a bit panicky while trying to redact my website info and closed the issue.

**Comment by tidusjar** [comment]
Please try develop

**Comment by Erbros** [comment]
```
Ombi.Schedule.Jobs.Plex.PlexContentSync[2008]
      Exception thrown when attempting to cache the Plex Content in server ErbrosPlex
System.Net.Http.HttpRequestException: Request headers must contain only ASCII characters.
   at System.Net.Http.HttpConnection.WriteStringAsync(String s)
   at System.Net.Http.HttpConnection.WriteHeadersAsync(HttpHeaders headers, String cookiesFromContainer)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request) in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
   at Ombi.Api.Plex.PlexApi.GetLibrarySections(String authToken, String plexFullHost) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 107
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.GetAllContent(PlexServers plexSettings, Boolean recentlyAddedSearch) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 560
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessServer(PlexServers servers, Boolean recentlyAddedSearch) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 154
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.StartTheCache(PlexSettings plexSettings, Boolean recentlyAddedSearch) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 132

```

Found this when I checked my docker logs.

I've been looking for hours now trying to figure out how to update to dev, but to no avail. Since I'm using a docker container, it's not as easy changing to dev channel as I thought it would be. Afaik the server will auto update when a new master is released? I'll just have to wait =)

**Comment by tidusjar** [comment]
What are your request headers you are sending?

You can view this by opening the browsers console > network > press a
request> there should be the request headers

**Comment by Erbros** [comment]
The last error was from the docker logs, not the browser.

I don't find the request headers by typing "a request" in the network tab in the developer tools.

This is the request header for the token which is failing.

```

POST /ombi/api/v1/token/ HTTP/1.1
Host: xxxxxxxx
Connection: keep-alive
Content-Length: 91
Accept: application/json, text/plain, */*
Origin: http://xxxxxxx
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
Content-Type: application/json
Referer: http://xxxxxxxx/ombi/login
Accept-Encoding: gzip, deflate
Accept-Language: nb,en-GB;q=0.9,en;q=0.8,en-US;q=0.7
Cookie: manage_view=thumb; wanted_view=thumb; snatched_view=list; soon_view=thumb; suggest_view=thumb; late_view=list; imdb_movies_in_theaters_view=thumb; blu_ray_com_new_releases_view=thumb; imdb_box_office_view=thumb; imdb_top_250_movies_view=thumb; ys-torrentGrid=o%3Acolumns%3Da%253Ao%25253Aid%25253Ds%2525253Aqueue%25255Ewidth%25253Dn%2525253A30%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Ds%2525253Aname%25255Ewidth%25253Dn%2525253A378%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A2%25255Ewidth%25253Dn%2525253A75%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A3%25255Ewidth%25253Dn%2525253A150%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A4%25255Ewidth%25253Dn%2525253A50%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A5%25255Ewidth%25253Dn%2525253A51%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A6%25255Ewidth%25253Dn%2525253A60%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A7%25255Ewidth%25253Dn%2525253A60%25255Ehidden%25253Db%2525253A1%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A8%25255Ewidth%25253Dn%2525253A60%25255Ehidden%25253Db%2525253A1%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A9%25255Ewidth%25253Dn%2525253A60%25255Ehidden%25253Db%2525253A1%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A10%25255Ewidth%25253Dn%2525253A60%25255Ehidden%25253Db%2525253A1%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A11%25255Ewidth%25253Dn%2525253A80%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A12%25255Ewidth%25253Dn%2525253A120%25255Ehidden%25253Db%2525253A1%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A13%25255Ewidth%25253Dn%2525253A120%25255Ehidden%25253Db%2525253A1%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A14%25255Ewidth%25253Dn%2525253A75%25255Ehidden%25253Db%2525253A1%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A15%25255Ewidth%25253Dn%2525253A75%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A16%25255Ewidth%25253Dn%2525253A75%25255Ehidden%25253Db%2525253A1%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A17%25255Ewidth%25253Dn%2525253A75%25255Ehidden%25253Db%2525253A1%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A18%25255Ewidth%25253Dn%2525253A75%25255Ehidden%25253Db%2525253A1%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A19%25255Ewidth%25253Dn%2525253A100%5Esort%3Do%253Afield%253Ds%25253Atime_added%255Edirection%253Ds%25253AASC; tautulli_token_5a18e60c4ff94fca80ca64eadf89d1ec=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpudWxsLCJ1c2VyIjoiRXJicm9zIiwiZXhwIjoxNTMyMjk5MzcwLCJ1c2VyX2dyb3VwIjoiYWRtaW4ifQ.XpDlZIZK6IRbuW9io2HyLloVJZX0jaYO163Q2_IaNnw; PHPSESSID=dsfg34cj04mjv96c9ph7c9oco3; Organizr_Token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6IjRmMWcyM2ExMmFhIn0.eyJpc3MiOiJPcmdhbml6ciIsImF1ZCI6Ik9yZ2FuaXpyIiwianRpIjoiNGYxZzIzYTEyYWEiLCJpYXQiOjE1MzA2OTY3NDQsImV4cCI6MTUzMTMwMTU0NCwidXNlcm5hbWUiOiJlcmJyb3MiLCJyb2xlIjoiYWRtaW4ifQ.t3Dz4s9OmNFoiD4Tegh-zu1KYqSYMlXFzZCCjUNMPMI; cookiePassword=; login_cookie=3785167ea6ffec0bad78bef5f8348b8a276a54f1; login_salt=131; _pk_id.1.e25e=f0020c79050d51ee.1520184710.21.1531072290.1531072075.

```

Sorry if this wasn't what you needed.

**Comment by tidusjar** [comment]
Please update and try.

**Comment by Erbros** [comment]
Not sure if you found the bug or not, but the error occurs if one uses special characters in the "Application Name" on the Customization page. Like I called it "Ønskebrønnen", and it refused to sign in. Changed it back to "Wishlist", all clear.

This might have been what you've fixed already, as I'm having some issue updating beyond 3.0.3421. Just thought I'd let you know just in case.

**Comment by tidusjar** [comment]
Ah interesting, it's basically saying Plex will not accept that as a X-Plex-Product header (we send the Application Name to them for OAuth and so it appears correctly in the Access List). 

So I'm not sure we can fix this because Plex will not accept it.

Please view this issue about the updating #2421

**Comment by tidusjar** [comment]
Yeah there's an open issue about this https://github.com/tidusjar/Ombi/issues/2427
