### ISSUE TITLE
Some users can not login, StatusCode: Unauthorized

### ISSUE THREAD

**Issue by skinnyzaz** [tidusjar/Ombi#2397]
First of all I love your work and appreciate it very much!! Its an awesome tool for plex.

#### Ombi build Version:

V 3.0.3477

#### Update Branch:

master

#### Media Sever:

Plex

#### Media Server Version:

Version 1.13.4.5271

#### Operating System:

Ubuntu 14.04

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.ErrorHandlingMiddleware.<Invoke>d__2.MoveNext() in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24
fail: Ombi.Api.Api[1000]
      StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://plex.tv/users/sign_in.json
fail: Ombi.Api.Api[1000]
      StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://plex.tv/users/sign_in.json
fail: Ombi.Api.Api[1000]
      StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://plex.tv/users/sign_in.json
fail: Ombi.Api.Api[1000]
      StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://plex.tv/users/sign_in.json
fail: Ombi.Api.Api[1000]
      StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://plex.tv/users/sign_in.json
fail: Ombi.Api.Api[1000]
      StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://plex.tv/users/sign_in.json

```

#### Problem Description:

a small percent of the users who try to login to ombi are unable to. When they try I see Unauthorized error. This is a fresh install of ombi, it was installed and setup 1 day ago. I have 2 different plex servers connected to ombi not sure if that could be causing an issue.

**Comment by tidusjar** [comment]
Can you please include more of the error. It looks like it's been cut off

**Comment by skinnyzaz** [comment]
Where do I find the logs? Do I need to enable them? I took those messages from the terminal as I watched a user try to login.

**Comment by tidusjar** [comment]
/logs/ directory.

**Comment by skinnyzaz** [comment]
opps had to refresh the directory before it appeared. Here is yesterdays log

[log-20180722.txt](https://github.com/tidusjar/Ombi/files/2222004/log-20180722.txt)
