### ISSUE TITLE
Unable to setup Ombi with Plex

### ISSUE THREAD

**Issue by Zogheen** [tidusjar/Ombi#2410]
#### Ombi build Version:

V 3.0.3477

#### Update Branch:

Master

#### Media Sever:

Plex

#### Media Server Version:

3.61.1

#### Operating System:

Ubuntu Server 18.04
Hosted on Google Cloud Platform using an f1micro VM

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

The only logs I could find were the syslogs (If I missed others please let me know where to look)

```

Jul 31 00:31:53 ltscon2 Ombi[6927]: Hello, welcome to Ombi
Jul 31 00:31:53 ltscon2 Ombi[6927]: Valid options are:
Jul 31 00:31:53 ltscon2 Ombi[6927]: Ombi 3.0.3477-master
Jul 31 00:31:53 ltscon2 Ombi[6927]: Copyright (C) 2018 Ombi
Jul 31 00:31:53 ltscon2 Ombi[6927]:   --host       (Default: http://*:5000) Set to a semicolon-separated (;) list
Jul 31 00:31:53 ltscon2 Ombi[6927]:                of URL prefixes to which the server should respond. For example,
Jul 31 00:31:53 ltscon2 Ombi[6927]:                http://localhost:123. Use "*" to indicate that the server should
Jul 31 00:31:53 ltscon2 Ombi[6927]:                listen for requests on any IP address or hostname using the
Jul 31 00:31:53 ltscon2 Ombi[6927]:                specified port and protocol (for example, http://*:5000). The
Jul 31 00:31:53 ltscon2 Ombi[6927]:                protocol (http:// or https://) must be included with each URL.
Jul 31 00:31:53 ltscon2 Ombi[6927]:                Supported formats vary between servers.
Jul 31 00:31:53 ltscon2 Ombi[6927]:   --storage    Storage path, where we save the logs and database
Jul 31 00:31:53 ltscon2 Ombi[6927]:   --baseurl    The base URL for reverse proxy scenarios
Jul 31 00:31:53 ltscon2 Ombi[6927]:   --help       Display this help screen.
Jul 31 00:31:53 ltscon2 Ombi[6927]:   --version    Display version information.
Jul 31 00:31:55 ltscon2 Ombi[6927]: We are running on
Jul 31 00:31:55 ltscon2 Ombi[6927]: /opt/Ombi
Jul 31 00:32:00 ltscon2 Ombi[6927]: Hosting environment: Production
Jul 31 00:32:00 ltscon2 Ombi[6927]: Content root path: /opt/Ombi
Jul 31 00:32:00 ltscon2 Ombi[6927]: Now listening on: http://[::]:5000
Jul 31 00:32:00 ltscon2 Ombi[6927]: Application started. Press Ctrl+C to shut down.
Jul 31 00:32:29 ltscon2 Ombi[6927]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
Jul 31 00:32:29 ltscon2 Ombi[6927]:       Starting Plex Content Cacher
Jul 31 00:32:29 ltscon2 Ombi[6927]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
Jul 31 00:32:29 ltscon2 Ombi[6927]:       Starting to cache the content on server Server 1
Jul 31 00:34:09 ltscon2 Ombi[6927]: #033[40m#033[1m#033[33mwarn#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexContentSync[2008]
Jul 31 00:34:09 ltscon2 Ombi[6927]:       Exception thrown when attempting to cache the Plex Content in server Server 1
Jul 31 00:34:09 ltscon2 Ombi[6927]: System.Threading.Tasks.TaskCanceledException: A task was canceled.
Jul 31 00:34:09 ltscon2 Ombi[6927]:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
Jul 31 00:34:09 ltscon2 Ombi[6927]:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Jul 31 00:34:09 ltscon2 Ombi[6927]:    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
Jul 31 00:34:09 ltscon2 Ombi[6927]:    at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
Jul 31 00:34:09 ltscon2 Ombi[6927]: --- End of stack trace from previous location where exception was thrown ---
Jul 31 00:34:09 ltscon2 Ombi[6927]:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Jul 31 00:34:09 ltscon2 Ombi[6927]:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
Jul 31 00:34:09 ltscon2 Ombi[6927]:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Jul 31 00:34:09 ltscon2 Ombi[6927]:    at Ombi.Api.OmbiHttpClient.<SendAsync>d__5.MoveNext() in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
Jul 31 00:34:09 ltscon2 Ombi[6927]: --- End of stack trace from previous location where exception was thrown ---
Jul 31 00:34:09 ltscon2 Ombi[6927]:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Jul 31 00:34:09 ltscon2 Ombi[6927]:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
Jul 31 00:34:09 ltscon2 Ombi[6927]:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Jul 31 00:34:09 ltscon2 Ombi[6927]:    at Ombi.Api.Api.<Request>d__6`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
Jul 31 00:34:09 ltscon2 Ombi[6927]: --- End of stack trace from previous location where exception was thrown ---
Jul 31 00:34:09 ltscon2 Ombi[6927]:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Jul 31 00:34:09 ltscon2 Ombi[6927]:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
Jul 31 00:34:09 ltscon2 Ombi[6927]:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Jul 31 00:34:09 ltscon2 Ombi[6927]:    at Ombi.Api.Plex.PlexApi.<GetLibrarySections>d__17.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 109
Jul 31 00:34:09 ltscon2 Ombi[6927]: --- End of stack trace from previous location where exception was thrown ---
Jul 31 00:34:09 ltscon2 Ombi[6927]:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Jul 31 00:34:09 ltscon2 Ombi[6927]:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
Jul 31 00:34:09 ltscon2 Ombi[6927]:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Jul 31 00:34:09 ltscon2 Ombi[6927]:    at Ombi.Schedule.Jobs.Plex.PlexContentSync.<GetAllContent>d__26.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 560
Jul 31 00:34:09 ltscon2 Ombi[6927]: --- End of stack trace from previous location where exception was thrown ---
Jul 31 00:34:09 ltscon2 Ombi[6927]:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Jul 31 00:34:09 ltscon2 Ombi[6927]:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
Jul 31 00:34:09 ltscon2 Ombi[6927]:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Jul 31 00:34:09 ltscon2 Ombi[6927]:    at Ombi.Schedule.Jobs.Plex.PlexContentSync.<ProcessServer>d__24.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 154
Jul 31 00:34:09 ltscon2 Ombi[6927]: --- End of stack trace from previous location where exception was thrown ---
Jul 31 00:34:09 ltscon2 Ombi[6927]:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Jul 31 00:34:09 ltscon2 Ombi[6927]:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
Jul 31 00:34:09 ltscon2 Ombi[6927]:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Jul 31 00:34:09 ltscon2 Ombi[6927]:    at Ombi.Schedule.Jobs.Plex.PlexContentSync.<StartTheCache>d__23.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 132

```

#### Problem Description:

I'm new to Ombi and I like to use Google Cloud for web hosting, so I took a fresh VM and followed the linux installation guide. Everything progressed smoothly, and soon I was able to access the ombi setup.

Here is where the problem comes in: 
    Using a username/password to request a token fails ('Could not get the Plex Admin Information').
    Continue with Plex will bring you to the plex account and then upon authorization will bring you back to the Ombi page and hang at "Please Wait".
    Choosing to skip the Plex setup and create an admin account fails ('There was an error... you might want to put this on Github...').

The logs above are from a restart into 'Continue with Plex' and the subsequent hang.

Other info:
    Ombi is the only service added to the server.
    A reinstall of Ombi and reboot of the system were tried.
    I read in another issue somewhere that file ownership could be a problem so I tried giving the Ombi user ownership of the /opt/Ombi/ folder and its contents, no luck (it was owned by root after install).
    The browser console contains no errors (I was looking at the other issue related to emby)
        Although when at the Plex.tv auth page theres an error, but it looks like is on Plex's end:

```

auth:9 GET https://www.googletagmanager.com/gtm.js?id=GTM-KX9D26&l=GOOGLE_TAG_MANAGER_DATA_LAYER 0 ()
(anonymous) @ auth:9
(anonymous) @ auth:9

```

If you would like logs of the other ways to continue I'll upload them (Didn't want to confuse the post)

#### Reproduction Steps:

Fresh install
Access over browser
Attempt to access either plex or skip.

**Comment by Zogheen** [comment]
On the Dev build I can complete server setup. I did have to go in and fix the server IP, it had pulled the internal IP and not the external.
Also, I don't know if you want this in another issue, but update (it says one is available but it's not on the repo) and syncing appear to be broken.
