### ISSUE TITLE
Ombi Java errors

### ISSUE THREAD

**Issue by Gosse1984** [tidusjar/Ombi#2428]
#### Ombi build Version:

V 3.0.3346

#### Update Branch:

Master

#### Media Sever:

Plex

#### Media Server Version:

1.13.5.5291

#### Operating System:

Centos 7

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2018-08-05 02:50:05.848 +01:00 [Debug] Searching : "Ter"
2018-08-05 02:50:09.761 +01:00 [Debug] Searching : "Terminator"
2018-08-05 03:25:05.254 +01:00 [Debug] Searching : "ter"
2018-08-05 03:25:07.896 +01:00 [Debug] Searching : "termin"
2018-08-05 03:25:09.886 +01:00 [Debug] Searching : "terminA"
2018-08-05 03:25:10.721 +01:00 [Debug] Searching : "terminAT"
2018-08-05 05:33:57.828 +01:00 [Debug] Searching : "Ter"
2018-08-05 05:34:00.437 +01:00 [Debug] Searching : "Termin"
2018-08-05 05:34:02.289 +01:00 [Debug] Searching : "Terminator"
2018-08-05 05:34:45.117 +01:00 [Debug] Searching : "Terminator"
2018-08-05 05:34:51.089 +01:00 [Debug] Searching : "Terminator"
2018-08-05 05:34:58.560 +01:00 [Debug] Searching : "Terminator"
2018-08-05 08:27:27.515 +01:00 [Debug] Searching : "Ter"
2018-08-05 08:27:30.921 +01:00 [Debug] Searching : "Terminator"
2018-08-05 09:05:56.018 +01:00 [Debug] Searching : "Termin"
2018-08-05 09:05:58.021 +01:00 [Debug] Searching : "Terminator"
2018-08-05 14:45:37.608 +01:00 [Debug] Searching : "Ter"
2018-08-05 14:45:39.191 +01:00 [Debug] Searching : "Terminar"
2018-08-05 14:45:41.500 +01:00 [Debug] Searching : "Terminator"
2018-08-05 15:44:37.985 +01:00 [Debug] Searching : "terminator"
2018-08-05 15:45:04.194 +01:00 [Error] Could not test Plex
System.PlatformNotSupportedException: The handler does not support custom handling of certificates with this combination of libcurl (7.29.0) and its SSL backend ("NSS/3.34").
   at System.Net.Http.CurlHandler.SslProvider.SetSslOptionsForUnsupportedBackend(EasyRequest easy, ClientCertificateProvider certProvider)
   at System.Net.Http.CurlHandler.SslProvider.SetSslOptions(EasyRequest easy, ClientCertificateOption clientCertOption)
   at System.Net.Http.CurlHandler.EasyRequest.InitializeCurl()
   at System.Net.Http.CurlHandler.MultiAgent.ActivateNewRequest(EasyRequest easy)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.OmbiHttpClient.<SendAsync>d__5.MoveNext() in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Api.<Request>d__6`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Plex.PlexApi.<GetStatus>d__13.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 84
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<Plex>d__61.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 242

```

#### Problem Description:

Ombi won't search for any films or TV program's nor will it test any existing connections (log shows trying to connect to plex media server)

#### Reproduction Steps:

Start to search for film in search field

**Comment by tidusjar** [comment]
Please update to the develop branch. This has been fixed in there. Also this is not a Java app :D
