### ISSUE TITLE
Newsletter not sending to users not in Ombi

### ISSUE THREAD

**Issue by kewlrobd** [tidusjar/Ombi#2457]
#### Ombi build Version:

V 3.0.587

#### Update Branch:

master

#### Media Sever:

Plex

#### Operating System:

Windows 2012 R2

#### Problem Description:

I have two addresses in the 'Add External Email (For users that are not in Ombi)' section of the newsletter settings.  Neither address is receiving the newsletter email.  I checked my sent messages and there were no messages sent.

**Comment by tidusjar** [comment]
Can you double check the build version you posted. 

Also are there any logs when an email gets sent?

**Comment by kewlrobd** [comment]
Sorry, I omitted the 3.  Version, 3.0.3587.  

Updated this yesterday but as a fresh install as instructed.  There is only the one log file and this is all of its contents.  

```

2018-08-20 19:12:47.270 -06:00 [Error] Something bad happened, ErrorMiddleware caught this
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 77
   at Ombi.Api.FanartTv.FanartTvApi.GetTvImages(Int32 tvdbId, String token) in C:\projects\requestplex\src\Ombi.Api.FanartTv\FanartTvApi.cs:line 27
   at Ombi.Controllers.ImagesController.GetBackgroundImage() in C:\projects\requestplex\src\Ombi\Controllers\ImagesController.cs:line 212
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 50
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24
2018-08-20 20:16:52.374 -06:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/254470?api_key=b8eabaf5608b88d0298aa189dd90bf00
2018-08-20 20:16:52.405 -06:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/197759?api_key=b8eabaf5608b88d0298aa189dd90bf00
2018-08-20 20:16:52.513 -06:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/197759?api_key=b8eabaf5608b88d0298aa189dd90bf00 Because we got Status Code: TooManyRequests
2018-08-20 20:16:52.513 -06:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/254470?api_key=b8eabaf5608b88d0298aa189dd90bf00 Because we got Status Code: TooManyRequests
2018-08-20 20:16:52.807 -06:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/79697?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates
2018-08-20 20:16:52.809 -06:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/45032?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates
2018-08-20 20:16:52.820 -06:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/117416?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates
2018-08-20 20:16:52.828 -06:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/306051?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates
2018-08-20 20:16:52.905 -06:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/45032?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates Because we got Status Code: TooManyRequests
2018-08-20 20:16:52.908 -06:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/79697?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates Because we got Status Code: TooManyRequests
2018-08-20 20:16:52.917 -06:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/117416?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates Because we got Status Code: TooManyRequests
2018-08-20 20:16:52.918 -06:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/306051?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates Because we got Status Code: TooManyRequests


```

**Comment by kewlrobd** [comment]
The Newsletter went out again today and didn't include those users.  The only new logs since earlier this week are below.  Do I somehow not have logging enabled?  I looked around the settings and don't see where I can increase logging.  

```
2018-08-24 10:01:22.960 -06:00 [Information] 1 scheduled job(s) enqueued.
```

**Comment by tidusjar** [comment]
I can't reproduce this and don't see any issues with the code, are the email addresses correctly formatted?
