### ISSUE TITLE
Issues not working

### ISSUE THREAD

**Issue by timmish** [tidusjar/Ombi#2471]
#### Ombi build Version:

V 3.0.3587

#### Update Branch:

Master

#### Media Sever:

Plex

#### Media Server Version:

1.13.6.5339

#### Operating System:

Docker image from linuxserver

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

The following logs are written just as the "Submit" button for the issue is pressed.
```

`
2018-08-27T20:05:45.331583722Z fail: Ombi.ErrorHandlingMiddleware[0]


2018-08-27T20:05:45.331630475Z       Something bad happened, ErrorMiddleware caught this


2018-08-27T20:05:45.331641431Z Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> Microsoft.Data.Sqlite.SqliteException: SQLite Error 1: 'table Issues has no column named UserReportedId'.


2018-08-27T20:05:45.331650748Z    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)


2018-08-27T20:05:45.331658480Z    at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()


2018-08-27T20:05:45.331666787Z    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)


2018-08-27T20:05:45.331674877Z    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)


2018-08-27T20:05:45.331683224Z    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)


2018-08-27T20:05:45.331691809Z    at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)


2018-08-27T20:05:45.331715267Z    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)


2018-08-27T20:05:45.331723667Z    --- End of inner exception stack trace ---


2018-08-27T20:05:45.331730636Z    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)


2018-08-27T20:05:45.331737779Z    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(DbContext _, ValueTuple`2 parameters, CancellationToken cancellationToken)


2018-08-27T20:05:45.331745395Z    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IReadOnlyList`1 entriesToSave, CancellationToken cancellationToken)


2018-08-27T20:05:45.331752939Z    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)


2018-08-27T20:05:45.331763551Z    at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)


2018-08-27T20:05:45.331771761Z    at Ombi.Store.Repository.Repository`1.Add(T content) in C:\projects\requestplex\src\Ombi.Store\Repository\Repository.cs:line 50


2018-08-27T20:05:45.331780521Z    at Ombi.Controllers.IssuesController.CreateIssue(Issues i) in C:\projects\requestplex\src\Ombi\Controllers\IssuesController.cs:line 135


2018-08-27T20:05:45.331788915Z    at lambda_method(Closure , Object )


2018-08-27T20:05:45.331795983Z    at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)


2018-08-27T20:05:45.331804738Z    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()


2018-08-27T20:05:45.331811468Z    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()


2018-08-27T20:05:45.331818292Z    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)


2018-08-27T20:05:45.331825871Z    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)


2018-08-27T20:05:45.331834833Z    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()


2018-08-27T20:05:45.331842436Z    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()


2018-08-27T20:05:45.331850335Z    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)


2018-08-27T20:05:45.331857978Z    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)


2018-08-27T20:05:45.331866054Z    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()


2018-08-27T20:05:45.331882408Z    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()


2018-08-27T20:05:45.331890802Z    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)


2018-08-27T20:05:45.331898529Z    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)


2018-08-27T20:05:45.331906239Z    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)


2018-08-27T20:05:45.332039628Z    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)


2018-08-27T20:05:45.332055473Z    at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)


2018-08-27T20:05:45.332168622Z    at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 50


2018-08-27T20:05:45.332182759Z    at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24`

```

#### Problem Description:

When an issue is submitted, the button does the pressed animation and is no longer clickable, but nothing more happens. Issues are switched on and i tried multiple issue types.

**Comment by tidusjar** [comment]
How did you get into this state, did this happen after updating?

**Comment by tidusjar** [comment]
Strange,
No the logs are fine I understand the issue but I do not understand how it's in that state, it's like a bad migration had run into the database but this would have happened months ago.

1. You have a few options, Either delete your Ombi.db and let Ombi recreate it (means you will have to start again).
1. Email me the DB and i'll fix it manually
1. I can create you the SQL script and you run it against the DB to fix it.

**Comment by timmish** [comment]
Alright, got it. Sent it to you via email.

**Comment by estavez** [comment]
Running same Ombi version 3.0.3587 on master branch.
Plex Media Server just updated with no change to Version 1.13.7.5369

I have the same issue, this issue started after the last auto updater crashed the ombi setup on this issue: https://github.com/tidusjar/Ombi/issues/2456 

I did a copy Ombi.db process and completely removed and reinstalled Ombi app and then copied the Ombi.db back so my database was not lost, everything but the "Request Issue" function works again.

See this pic of the error all users see when they click on a random movie or tv show, nothing happens than a black line: https://imgur.com/a/S3BSEha 

How do we solve this issue? 

I think this issue is not only me who are affected after the "Stuck on loading following update to 3.0.3587 #2456" there could be a lot out the with the same issue but maybe without knowing it yet. I don't see it as an future solution for you to email the DB if a lot others has this issue? So maybe you could look into making a script that people can run them selves to fix the issue?

**Comment by tidusjar** [comment]
That's because you have not set up any issue categories.
