### ISSUE TITLE
OMBI Login

### ISSUE THREAD

**Issue by stefanelul2000** [tidusjar/Ombi#2483]
#### Ombi build Version:

V 3.0.3587

#### Update Branch:

master

#### Media Sever:

Plex

#### Media Server Version:

1.13.6.5339

#### Operating System:

Windows Server 2016

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
2018-08-29 22:02:38.857 +03:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://plex.tv/users/sign_in.json
2018-08-29 22:02:58.651 +03:00 [Information] Created User "stefanelul2000"
2018-08-29 22:02:59.202 +03:00 [Information] Created the roles
2018-08-29 22:02:59.393 +03:00 [Information] Added the Admin role
2018-08-29 22:10:58.283 +03:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://plex.tv/users/sign_in.json
2018-08-29 22:10:59.736 +03:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://plex.tv/users/sign_in.json
2018-08-29 22:11:02.139 +03:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://plex.tv/users/sign_in.json
2018-08-29 22:15:00.962 +03:00 [Error] Could not test Plex
System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request) in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
   at Ombi.Api.Plex.PlexApi.GetStatus(String authToken, String uri) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 97
   at Ombi.Controllers.External.TesterController.Plex(PlexServers settings) in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 242

```

#### Problem Description:

I've enabled users to login without passwords and even after that, I input a random name and it prompts me to put a passowrd.

**Comment by stefanelul2000** [comment]
Realized that The usernames don't have to be random, they have to exist in the DB.
