### ISSUE TITLE
Can not connect to plex

### ISSUE THREAD

**Issue by CojakSilverBack** [tidusjar/Ombi#2491]
#### Ombi build Version:

V 3.0.3587

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

1.13.3.5223

#### Operating System:

Plex and Ombi are running on separate server 2012 R2

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
2018-08-31 12:17:30.022 -06:00 [Error] Could not test Plex
System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request) in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
   at Ombi.Api.Plex.PlexApi.GetStatus(String authToken, String uri) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 97
   at Ombi.Controllers.External.TesterController.Plex(PlexServers settings) in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 242


```

#### Problem Description:

Ombi unable to connect to Plex

#### Reproduction Steps:

Plex configuration page type in username password for plex select server from drop down list click on test connectivity

**Comment by tidusjar** [comment]
Please check your settings for it.

**Comment by CojakSilverBack** [comment]
![ombi](https://user-images.githubusercontent.com/22101909/44934367-cbd81300-ad29-11e8-8a9b-976c6198899e.jpg)
![server](https://user-images.githubusercontent.com/22101909/44934392-dd211f80-ad29-11e8-830c-f3312d24c592.jpg)

**Comment by CojakSilverBack** [comment]
I have tried the external port and the private port with the same results

**Comment by tidusjar** [comment]
Put in all the internal information. Press test and then upload the logs please.

**Comment by CojakSilverBack** [comment]
[log-20180831.txt](https://github.com/tidusjar/Ombi/files/2341598/log-20180831.txt)

**Comment by Haywood78** [comment]
Not sure if this is your issue? On my build I had to set internal port 32400 Plex by default and check SSL. No issues since. Hope this helps.

**Comment by CojakSilverBack** [comment]
[log-20180905.txt](https://github.com/tidusjar/Ombi/files/2353724/log-20180905.txt)

**Comment by CojakSilverBack** [comment]
OK so after a ton of troubleshoot I think I have fixed it.  I went into Plex and deleted the connections from Ombi v2 and the new connections from v3 as well has one I still had from Plex Requests. I will still not able to connect so I went back to localhost:5000/Wizard/Plex and setup the connection again but instead of using a token I used plex auth option. After this was successful, I was then able to go into the settings > Media Server > Plex options and add my server, I still had to change the Port it was using from the external port to the internal port (32400). In plex I had also changed my network connections in plex to preferred from required but not sure that made that big of a difference I was able to change back to required and still have it connect.

**Comment by CojakSilverBack** [comment]
Testing it again the change from preferred from required did have an effect.

**Comment by binarypower2** [comment]
Same issues, same logs. Changed network "secure connections" to preferred from required. Now works.

**Comment by torres3490** [comment]
I had this problem, the fix is below

1. Go to ........OMBI /SETTINGS/--->MEDIA SERVER/PLEX
2.Login to plex using your username and password; LOAD SERVERS / SELECT your desired server
Once selected , the problem lies in the "HOSTNAME or IP" box

My fix
3.Go to this website
https://www.noip.com/
4.Create account and Download the software and install.
5.Open software, and create a host.
once created, start the host
6. Copy and paste the web address to your host in the
"HOSTNAME or IP" box in Ombi
7. Hit "LOAD LIBRARIES"
8. DONE :-))
