### ISSUE TITLE
Ombi not adding requests to Radarr

### ISSUE THREAD

**Issue by envintus** [tidusjar/Ombi#2504]
#### Ombi build Version:

V 3.0.3587

#### Update Branch:

master

#### Media Sever:

Plex

#### Media Server Version:

1.13.7.5369

#### Operating System:

Windows 10

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

$ tail -f log-20180911.txt
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request) in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
   at Ombi.Api.Plex.PlexApi.GetStatus(String authToken, String uri) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 97
   at Ombi.Controllers.External.TesterController.Plex(PlexServers settings) in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 242

```

#### Problem Description:

When requests to add movies are made Ombi is not adding the movies to Radarr. I do not see sync jobs running in the logs. I have double-checked both my Plex and Radarr integrations in Ombi. Both are configured correctly and testing connections is successful. I've attempted to schedule the Radarr job to run every minute in hopes I can observe it run in the logs, but to no avail I do not see any activity.

#### Reproduction Steps:

Using Windows 10 install PMS, Radarr, Ombi and integrate all three. Then add a movie via the request screen in Ombi.

**Comment by tidusjar** [comment]
Is radarr enabled in the settings?

**Comment by envintus** [comment]
Thanks for replying. Yes, Radarr is enabled. FWIW, all three pieces of software are collocated on the system.

**Comment by envintus** [comment]
@tidusjar I tried a few more requests and they were processed and added to Radarr correctly. I also see the activity in the logs. Not sure what happened to the previous requests.

Thanks again for a really great piece of software and providing me with your time & support.
