### ISSUE TITLE
Ombi Failing to send Newsletter via email

### ISSUE THREAD

**Issue by RikT** [tidusjar/Ombi#2515]
#### Ombi build Version:

V 3.0.3587

#### Update Branch:

Master

#### Media Sever:

Plex

#### Operating System:

Windows 10

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2018-09-17 18:40:25.347 +01:00 [Error] Something bad happened, ErrorMiddleware caught this
System.ObjectDisposedException: Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'OmbiContext'.
   at Microsoft.EntityFrameworkCore.DbContext.CheckDisposed()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Internal.IDbContextDependencies.get_QueryProvider()
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor..ctor(IEvaluatableExpressionFilter evaluatableExpressionFilter, IParameterValues parameterValues, IDiagnosticsLogger`1 logger, DbContext context, Boolean parameterize, Boolean generateContextAccessors)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryModelGenerator.ExtractParameters(IDiagnosticsLogger`1 logger, Expression query, IParameterValues parameterValues, Boolean parameterize, Boolean generateContextAccessors)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, LambdaExpression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, Expression`1 predicate, CancellationToken cancellationToken)
   at Ombi.Store.Repository.SettingsJsonRepository.GetAsync(String settingsName)
   at Ombi.Settings.Settings.SettingsService`1.<GetSettingsAsync>b__11_0() in C:\projects\requestplex\src\Ombi.Settings\Settings\SettingsService.cs:line 51
   at Ombi.Helpers.CacheService.GetOrAdd[T](String cacheKey, Func`1 factory, DateTime absoluteExpiration)
   at Ombi.Settings.Settings.SettingsService`1.GetSettingsAsync()
   at Ombi.Api.OmbiHttpClient.<GetHandler>b__8_0() in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 86
   at Ombi.Helpers.CacheService.GetOrAdd[T](String cacheKey, Func`1 factory, DateTime absoluteExpiration)
   at Ombi.Api.OmbiHttpClient.GetHandler() in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 86
   at Ombi.Api.OmbiHttpClient.Setup() in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 77
   at Ombi.Api.OmbiHttpClient.GetStringAsync(Uri requestUri) in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 67
   at Ombi.Schedule.Processor.ChangeLogProcessor.Process(String branch) in C:\projects\requestplex\src\Ombi.Schedule\Processor\ChangeLogProcessor.cs:line 36
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.UpdateAvailable(String branch, String currentVersion) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 62
   at Ombi.Controllers.JobController.<CheckForUpdateCached>b__10_0() in C:\projects\requestplex\src\Ombi\Controllers\JobController.cs:line 84
   at Ombi.Helpers.CacheService.GetOrAdd[T](String cacheKey, Func`1 factory, DateTime absoluteExpiration) in C:\projects\requestplex\src\Ombi.Helpers\CacheService.cs:line 38
   at Ombi.Controllers.JobController.CheckForUpdateCached() in C:\projects\requestplex\src\Ombi\Controllers\JobController.cs:line 79
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 50
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24

```

#### Problem Description:

It seems that ombi has stopped sending newsletter emails since last update

#### Reproduction Steps:

Just Upgraded

**Comment by tidusjar** [comment]
Can you check develop builds?
