### ISSUE TITLE
Ombi to Radarr sync fails every time

### ISSUE THREAD

**Issue by leijurv** [tidusjar/Ombi#2544]
Latest Docker from readme (the tag updated 4 days ago, September 23)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

    \"qualityProfileId\": 4,
    \"id\": 1
  }
]"
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Ombi.Api.Radarr.Models.RadarrAddMovieResponse' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Radarr.RadarrApi.AddMovie(Int32 tmdbId, String title, Int32 year, Int32 qualityId, String rootPath, String apiKey, String baseUrl, Boolean searchNow, String minimumAvailability) in C:\projects\requestplex\src\Ombi.Api.Radarr\RadarrApi.cs:line 111
2018-09-24 20:21:49.149 -07:00 [Error] Something bad happened, ErrorMiddleware caught this
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Core.Senders.MovieSender.SendToRadarr(MovieRequests model, RadarrSettings settings) in C:\projects\requestplex\src\Ombi.Core\Senders\MovieSender.cs:line 104
   at Ombi.Core.Senders.MovieSender.Send(MovieRequests model) in C:\projects\requestplex\src\Ombi.Core\Senders\MovieSender.cs:line 45
   at Ombi.Core.Engine.MovieRequestEngine.ApproveMovie(MovieRequests request) in C:\projects\requestplex\src\Ombi.Core\Engine\MovieRequestEngine.cs:line 351
   at Ombi.Core.Engine.MovieRequestEngine.RequestMovie(MovieRequestViewModel model) in C:\projects\requestplex\src\Ombi.Core\Engine\MovieRequestEngine.cs:line 105
   at Ombi.Controllers.RequestController.RequestMovie(MovieRequestViewModel movie) in C:\projects\requestplex\src\Ombi\Controllers\RequestController.cs:line 77
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 50
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24

```

#### Problem Description:

Ombi to Radarr sync fails every time

**Comment by tidusjar** [comment]
Does your Radarr install have a Root Url/Base Url? is it in the ombi radarr settings?

**Comment by l-t-k** [comment]
Same here. And same problem with Sonarr. Using ombi, radarr and sonarr with linuxserver.io docker. All of them have webroot /appname:
/ombi
/radarr
/sonarr

Log file:
https://pastebin.com/DGgzKc87

**Comment by tidusjar** [comment]
From your log @l-t-k There are a few unauthorized messages meaning the API key is correct, we are sending the one you provided but Radarr is rejecting it.

**Comment by luxus** [comment]
i tested the Radarr connection and it worked fine.
as soon I add request a movie I got this https://gist.github.com/luxus/8a58aef97775a2bc22b13ec228dbb43a

**Comment by tidusjar** [comment]
@luxus that issue is common when radarr has a base URL setup and it's missing from the ombi settings.

**Comment by luxus** [comment]
Radarr is running on a subdomain, not in a subdirectory 
It was working, don’t know what’s happened 
What can I check in the Radarr configuration?

**Comment by tidusjar** [comment]
Please check with the latest release

**Comment by luxus** [comment]
Works again
