### ISSUE TITLE
To many requests?

### ISSUE THREAD

**Issue by screamq3** [tidusjar/Ombi#2552]
#### Ombi build Version:

V 3.0.3823

#### Update Branch:

Open Beta

#### Media Sever:

Plex/Emby

#### Operating System:

Windows Server 2012

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

2018-10-01 06:53:10.636 +01:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/489493?api_key=b8eabaf5608b88d0298aa189dd90bf00
2018-10-01 06:53:10.851 +01:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/489493?api_key=b8eabaf5608b88d0298aa189dd90bf00 Because we got Status Code: TooManyRequests
2018-10-01 06:53:12.579 +01:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/597?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates
2018-10-01 06:53:12.661 +01:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/597?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates Because we got Status Code: TooManyRequests
2018-10-01 07:06:27.891 +01:00 [Error] Something bad happened, ErrorMiddleware caught this
System.ArgumentNullException: Value cannot be null.
Parameter name: entity
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
   at Microsoft.EntityFrameworkCore.DbContext.Remove[TEntity](TEntity entity)
   at Ombi.Store.Repository.Repository`1.Delete(T request) in C:\projects\requestplex\src\Ombi.Store\Repository\Repository.cs:line 57
   at Ombi.Core.Engine.MovieRequestEngine.RemoveMovieRequest(Int32 requestId) in C:\projects\requestplex\src\Ombi.Core\Engine\MovieRequestEngine.cs:line 416
   at Ombi.Controllers.RequestController.DeleteRequest(Int32 requestId) in C:\projects\requestplex\src\Ombi\Controllers\RequestController.cs:line 101
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 50
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24
2018-10-01 07:06:35.325 +01:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/280546?api_key=b8eabaf5608b88d0298aa189dd90bf00
2018-10-01 07:06:35.452 +01:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/280546?api_key=b8eabaf5608b88d0298aa189dd90bf00 Because we got Status Code: TooManyRequests
2018-10-01 07:06:36.603 +01:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/14597?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates
2018-10-01 07:06:36.681 +01:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/14597?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates Because we got Status Code: TooManyRequests
2018-10-01 07:17:30.109 +01:00 [Error] Something bad happened, ErrorMiddleware caught this
System.ArgumentNullException: Value cannot be null.
Parameter name: entity
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
   at Microsoft.EntityFrameworkCore.DbContext.Remove[TEntity](TEntity entity)
   at Ombi.Store.Repository.Repository`1.Delete(T request) in C:\projects\requestplex\src\Ombi.Store\Repository\Repository.cs:line 57
   at Ombi.Core.Engine.MovieRequestEngine.RemoveMovieRequest(Int32 requestId) in C:\projects\requestplex\src\Ombi.Core\Engine\MovieRequestEngine.cs:line 416
   at Ombi.Controllers.RequestController.DeleteRequest(Int32 requestId) in C:\projects\requestplex\src\Ombi\Controllers\RequestController.cs:line 101
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 50
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24
2018-10-01 07:17:35.664 +01:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/61856?api_key=b8eabaf5608b88d0298aa189dd90bf00
2018-10-01 07:17:35.792 +01:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/61856?api_key=b8eabaf5608b88d0298aa189dd90bf00 Because we got Status Code: TooManyRequests
2018-10-01 07:17:36.308 +01:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/search/movie?api_key=b8eabaf5608b88d0298aa189dd90bf00&query=lassie 2005
2018-10-01 07:17:36.391 +01:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/search/movie?api_key=b8eabaf5608b88d0298aa189dd90bf00&query=lassie 2005 Because we got Status Code: TooManyRequests
2018-10-01 07:17:37.012 +01:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/14597?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates
2018-10-01 07:17:37.101 +01:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/14597?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates Because we got Status Code: TooManyRequests

```

#### Problem Description:

Can i change the Api key within ombi? Why is this happening?

#### Reproduction Steps:

Restarted / Reinstalled, still persists

**Comment by screamq3** [comment]
Only happening with movies, TV-shows are all fine just themoviedb api

**Comment by tidusjar** [comment]
This is nothing to worry about, using your own API key will result in the same, the API limits are per IP. 

It's because we are querying the API a lot during searching.

**Comment by tidusjar** [comment]
I'm not sure what you mean. Ombi requires a lot of metadata from TheMovieDb which may end up with multiple API calls for a single movie.

**Comment by screamq3** [comment]
2018-10-01 16:52:10.780 +01:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/10307?api_key=b8eabaf5608b88d0298aa189dd90bf00 Because we got Status Code: TooManyRequests
2018-10-01 16:52:10.798 +01:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/87955?api_key=b8eabaf5608b88d0298aa189dd90bf00 Because we got Status Code: TooManyRequests
2018-10-01 16:52:11.220 +01:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/search/movie?api_key=b8eabaf5608b88d0298aa189dd90bf00&query=Still
2018-10-01 16:52:11.297 +01:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/search/movie?api_key=b8eabaf5608b88d0298aa189dd90bf00&query=Still Because we got Status Code: TooManyRequests
2018-10-01 16:52:13.651 +01:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/search/movie?api_key=b8eabaf5608b88d0298aa189dd90bf00&query=Still A
2018-10-01 16:52:13.729 +01:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/search/movie?api_key=b8eabaf5608b88d0298aa189dd90bf00&query=Still A Because we got Status Code: TooManyRequests
2018-10-01 16:52:15.466 +01:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/search/movie?api_key=b8eabaf5608b88d0298aa189dd90bf00&query=Still Alice
2018-10-01 16:52:15.542 +01:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/search/movie?api_key=b8eabaf5608b88d0298aa189dd90bf00&query=Still Alice Because we got Status Code: TooManyRequests
2018-10-01 16:52:23.091 +01:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/2165?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates
2018-10-01 16:52:23.138 +01:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/43939?api_key=b8eabaf5608b88d0298aa189dd90bf00
2018-10-01 16:52:23.166 +01:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/828?api_key=b8eabaf5608b88d0298aa189dd90bf00
2018-10-01 16:52:23.169 +01:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/2165?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates Because we got Status Code: TooManyRequests
2018-10-01 16:52:23.215 +01:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/43939?api_key=b8eabaf5608b88d0298aa189dd90bf00 Because we got Status Code: TooManyRequests
2018-10-01 16:52:23.243 +01:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/828?api_key=b8eabaf5608b88d0298aa189dd90bf00 Because we got Status Code: TooManyRequests
2018-10-01 16:53:11.819 +01:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/348350?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates
2018-10-01 16:53:11.896 +01:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/348350?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates Because we got Status Code: TooManyRequests
2018-10-01 16:53:11.961 +01:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/439079?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates
2018-10-01 16:53:12.039 +01:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/439079?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates Because we got Status Code: TooManyRequests
2018-10-01 16:53:12.447 +01:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/135870?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates
2018-10-01 16:53:12.526 +01:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/135870?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates Because we got Status Code: TooManyRequests
2018-10-01 16:53:13.679 +01:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/299536?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates
2018-10-01 16:53:13.756 +01:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/299536?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates Because we got Status Code: TooManyRequests
2018-10-01 15:20:12.799 +01:00 [Error] Something bad happened, ErrorMiddleware caught this
System.InvalidOperationException: An exception was thrown while attempting to evaluate a LINQ query parameter expression. To show additional information call EnableSensitiveDataLogging() when overriding DbContext.OnConfiguring. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure )
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor.Evaluate(Expression expression, String& parameterName)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor.Evaluate(Expression expression, String& parameterName)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor.TryExtractParameter(Expression expression)
   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor.VisitUnary(UnaryExpression unaryExpression)
   at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor.ExtractParameters(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, LambdaExpression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.AnyAsync[TSource](IQueryable`1 source, Expression`1 predicate, CancellationToken cancellationToken)
   at Ombi.Core.Engine.MovieSearchEngine.CheckForSubscription(SearchMovieViewModel viewModel)
   at Ombi.Core.Engine.MovieSearchEngine.ProcessSingleMovie(SearchMovieViewModel viewMovie, Boolean lookupExtraInfo) in C:\projects\requestplex\src\Ombi.Core\Engine\MovieSearchEngine.cs:line 170
   at Ombi.Core.Engine.MovieSearchEngine.ProcessSingleMovie(MovieSearchResult movie) in C:\projects\requestplex\src\Ombi.Core\Engine\MovieSearchEngine.cs:line 195
   at Ombi.Core.Engine.MovieSearchEngine.TransformMovieResultsToResponse(IEnumerable`1 movies) in C:\projects\requestplex\src\Ombi.Core\Engine\MovieSearchEngine.cs:line 147
   at Ombi.Core.Engine.MovieSearchEngine.PopularMovies() in C:\projects\requestplex\src\Ombi.Core\Engine\MovieSearchEngine.cs:line 93
   at Ombi.Controllers.SearchController.Popular() in C:\projects\requestplex\src\Ombi\Controllers\SearchController.cs:line 87
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 50
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24



Any of that corrupt or must i change something bud? Does it matter its not linked to a plex account? I know on TMDB if you register which i have, it allows more requests per minute. Is there a way to change the api to my personal one buddy? Have checked through the folder, nothing pops out in front of me of what file to edit. Thanks in advance

**Comment by screamq3** [comment]
still got this error? wont even add one movie? What can be done
