### ISSUE TITLE
fail: Ombi.Api.Api[1000]  Status Code: TooManyRequests fail: Ombi.Api.Api[1000]

### ISSUE THREAD

**Issue by screamq3** [tidusjar/Ombi#2572]
#### Ombi build Version:

V 3.0.3858

#### Update Branch:

Open Beta

#### Media Sever:

NA
#### Operating System:

Windows Server 2012

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

Hello, welcome to Ombi
Valid options are:
Ombi 3.0.3858-develop
Copyright (C) 2018 Ombi

  --host       (Default: http://*:5000) Set to a semicolon-separated (;) list
               of URL prefixes to which the server should respond. For example,
               http://localhost:123. Use "*" to indicate that the server should
               listen for requests on any IP address or hostname using the
               specified port and protocol (for example, http://*:5000). The
               protocol (http:// or https://) must be included with each URL.
               Supported formats vary between servers.

  --storage    Storage path, where we save the logs and database

  --baseurl    The base URL for reverse proxy scenarios

  --help       Display this help screen.

  --version    Display version information.



We are running on
C:\NewRequester
Hosting environment: Production
Content root path: C:\NewRequester
Now listening on: http://[::]:5000
Application started. Press Ctrl+C to shut down.
fail: Ombi.Api.Api[1000]
      StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.o
rg/3/movie/120?api_key=b8eabaf5608b88d0298aa189dd90bf00
fail: Ombi.Api.Api[1000]
      Retrying RequestUri: http://api.themoviedb.org/3/movie/120?api_key=b8eabaf
5608b88d0298aa189dd90bf00 Because we got Status Code: TooManyRequests
info: Ombi.Notifications.Agents.MobileNotification[0]
      there are no admins to send a notification for RequestApproved, for agent
Mobile
fail: Ombi.Api.Api[1000]
      StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.o
rg/3/movie/433277?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=vi
deos,release_dates
fail: Ombi.Api.Api[1000]
      Retrying RequestUri: http://api.themoviedb.org/3/movie/433277?api_key=b8ea
baf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates Because we
got Status Code: TooManyRequests
fail: Ombi.Api.Api[1000]
      StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.o
rg/3/movie/69843?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=vid
eos,release_dates
fail: Ombi.Api.Api[1000]
      Retrying RequestUri: http://api.themoviedb.org/3/movie/69843?api_key=b8eab
af5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates Because we g
ot Status Code: TooManyRequests
fail: Ombi.Api.Api[1000]
      StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.o
rg/3/search/movie?api_key=b8eabaf5608b88d0298aa189dd90bf00&query=Hocus
fail: Ombi.Api.Api[1000]
      Retrying RequestUri: http://api.themoviedb.org/3/search/movie?api_key=b8ea
baf5608b88d0298aa189dd90bf00&query=Hocus Because we got Status Code: TooManyRequ
ests
fail: Ombi.Api.Api[1000]
      StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.o
rg/3/movie/531158?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=vi
deos,release_dates
fail: Ombi.Api.Api[1000]
      Retrying RequestUri: http://api.themoviedb.org/3/movie/531158?api_key=b8ea
baf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates Because we
got Status Code: TooManyRequests
info: Ombi.Schedule.Jobs.Couchpotato.CouchPotatoSync[2007]
      Getting all active movies from CP
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server NEW (LB1) MOVIES + SERIES 0-9 / A-
H + Live TV
warn: Ombi.Schedule.Jobs.Plex.PlexContentSync[2008]
      Exception thrown when attempting to cache the Plex Content in server NEW (
LB1) MOVIES + SERIES 0-9 / A-H + Live TV
System.Net.Http.HttpRequestException: A connection attempt failed because the co
nnected party did not properly respond after a period of time, or established co
nnection failed because connected host has failed to respond ---> System.Net.Soc
kets.SocketException: A connection attempt failed because the connected party di
d not properly respond after a period of time, or established connection failed
because connected host has failed to respond
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, Cancel
lationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, Cancel
lationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessag
e request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask
`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage r
equest, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Canc
ellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRe
questMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request) in C:\projec
ts\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Om
bi.Api\Api.cs:line 38
   at Ombi.Api.Plex.PlexApi.GetLibrarySections(String authToken, String plexFull
Host) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 120
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.GetAllContent(PlexServers plexSett
ings, Boolean recentlyAddedSearch) in C:\projects\requestplex\src\Ombi.Schedule\
Jobs\Plex\PlexContentSync.cs:line 578
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessServer(PlexServers servers,
 Boolean recentlyAddedSearch) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\
Plex\PlexContentSync.cs:line 154
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.StartTheCache(PlexSettings plexSet
tings, Boolean recentlyAddedSearch) in C:\projects\requestplex\src\Ombi.Schedule
\Jobs\Plex\PlexContentSync.cs:line 132
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server BACKUP (LB2) MOVIES + SERIES I-Z +
 Live TV
warn: Ombi.Schedule.Jobs.Plex.PlexContentSync[2008]
      Exception thrown when attempting to cache the Plex Content in server BACKU
P (LB2) MOVIES + SERIES I-Z + Live TV
System.Net.Http.HttpRequestException: A connection attempt failed because the co
nnected party did not properly respond after a period of time, or established co
nnection failed because connected host has failed to respond ---> System.Net.Soc
kets.SocketException: A connection attempt failed because the connected party di
d not properly respond after a period of time, or established connection failed
because connected host has failed to respond
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, Cancel
lationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, Cancel
lationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessag
e request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask
`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage r
equest, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Canc
ellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRe
questMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request) in C:\projec
ts\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Om
bi.Api\Api.cs:line 38
   at Ombi.Api.Plex.PlexApi.GetLibrarySections(String authToken, String plexFull
Host) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 120
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.GetAllContent(PlexServers plexSett
ings, Boolean recentlyAddedSearch) in C:\projects\requestplex\src\Ombi.Schedule\
Jobs\Plex\PlexContentSync.cs:line 578
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessServer(PlexServers servers,
 Boolean recentlyAddedSearch) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\
Plex\PlexContentSync.cs:line 154
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.StartTheCache(PlexSettings plexSet
tings, Boolean recentlyAddedSearch) in C:\projects\requestplex\src\Ombi.Schedule
\Jobs\Plex\PlexContentSync.cs:line 132
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server NEW (LB1) MOVIES + SERIES 0-9 / A-
H + Live TV
warn: Ombi.Schedule.Jobs.Plex.PlexContentSync[2008]
      Exception thrown when attempting to cache the Plex Content in server NEW (
LB1) MOVIES + SERIES 0-9 / A-H + Live TV
System.Net.Http.HttpRequestException: A connection attempt failed because the co
nnected party did not properly respond after a period of time, or established co
nnection failed because connected host has failed to respond ---> System.Net.Soc
kets.SocketException: A connection attempt failed because the connected party di
d not properly respond after a period of time, or established connection failed
because connected host has failed to respond
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, Cancel
lationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, Cancel
lationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessag
e request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask
`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage r
equest, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Canc
ellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRe
questMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request) in C:\projec
ts\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Om
bi.Api\Api.cs:line 38
   at Ombi.Api.Plex.PlexApi.GetLibrarySections(String authToken, String plexFull
Host) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 120
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.GetAllContent(PlexServers plexSett
ings, Boolean recentlyAddedSearch) in C:\projects\requestplex\src\Ombi.Schedule\
Jobs\Plex\PlexContentSync.cs:line 578
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessServer(PlexServers servers,
 Boolean recentlyAddedSearch) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\
Plex\PlexContentSync.cs:line 154
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.StartTheCache(PlexSettings plexSet
tings, Boolean recentlyAddedSearch) in C:\projects\requestplex\src\Ombi.Schedule
\Jobs\Plex\PlexContentSync.cs:line 132
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server BACKUP (LB2) MOVIES + SERIES I-Z +
 Live TV
warn: Ombi.Schedule.Jobs.Plex.PlexContentSync[2008]
      Exception thrown when attempting to cache the Plex Content in server BACKU
P (LB2) MOVIES + SERIES I-Z + Live TV
System.Net.Http.HttpRequestException: A connection attempt failed because the co
nnected party did not properly respond after a period of time, or established co
nnection failed because connected host has failed to respond ---> System.Net.Soc
kets.SocketException: A connection attempt failed because the connected party di
d not properly respond after a period of time, or established connection failed
because connected host has failed to respond
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, Cancel
lationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, Cancel
lationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessag
e request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask
`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage r
equest, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Canc
ellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRe
questMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request) in C:\projec
ts\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Om
bi.Api\Api.cs:line 38
   at Ombi.Api.Plex.PlexApi.GetLibrarySections(String authToken, String plexFull
Host) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 120
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.GetAllContent(PlexServers plexSett
ings, Boolean recentlyAddedSearch) in C:\projects\requestplex\src\Ombi.Schedule\
Jobs\Plex\PlexContentSync.cs:line 578
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessServer(PlexServers servers,
 Boolean recentlyAddedSearch) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\
Plex\PlexContentSync.cs:line 154
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.StartTheCache(PlexSettings plexSet
tings, Boolean recentlyAddedSearch) in C:\projects\requestplex\src\Ombi.Schedule
\Jobs\Plex\PlexContentSync.cs:line 132
fail: Ombi.Api.Api[1000]
      StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.o
rg/3/movie/9550?api_key=b8eabaf5608b88d0298aa189dd90bf00
fail: Ombi.Api.Api[1000]
      StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.o
rg/3/movie/22643?api_key=b8eabaf5608b88d0298aa189dd90bf00
fail: Ombi.Api.Api[1000]
      StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.o
rg/3/movie/509632?api_key=b8eabaf5608b88d0298aa189dd90bf00
fail: Ombi.Api.Api[1000]
      Retrying RequestUri: http://api.themoviedb.org/3/movie/9550?api_key=b8eaba
f5608b88d0298aa189dd90bf00 Because we got Status Code: TooManyRequests
fail: Ombi.Api.Api[1000]
      Retrying RequestUri: http://api.themoviedb.org/3/movie/22643?api_key=b8eab
af5608b88d0298aa189dd90bf00 Because we got Status Code: TooManyRequests
fail: Ombi.Api.Api[1000]
      Retrying RequestUri: http://api.themoviedb.org/3/movie/509632?api_key=b8ea
baf5608b88d0298aa189dd90bf00 Because we got Status Code: TooManyRequests
fail: Ombi.Api.Api[1000]
      StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.o
rg/3/movie/496466?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=vi
deos,release_dates
fail: Ombi.Api.Api[1000]
      Retrying RequestUri: http://api.themoviedb.org/3/movie/496466?api_key=b8ea
baf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates Because we
got Status Code: TooManyRequests
info: Ombi.Notifications.Agents.MobileNotification[0]
      there are no admins to send a notification for NewRequest, for agent Mobil
e

```

#### Problem Description:

Since day one of installing Ombi not one movie has come down. Each time api reaches its limit (there must be a way of setting up own api as i know themoviedb caps Apis if ombi is all using the same then this problem will always remain). TV Shows works fine its just movies. How can i solve this? it's been like this over a week, it doeskin even add movies to couch just stays "Processing". Anybody able to help? Thanks in advance.

#### Reproduction Steps:

Request another movie, same error appears all the time.

**Comment by tidusjar** [comment]
I told you in the previous issue that you opened you hitting the API limits does not matter. It's just a warning.

**Comment by screamq3** [comment]
Should it still send to couch then? as nothing is getting sent, it can grab api from couch, when you hit test connectivity just says successfully saved settings etc
