### ISSUE TITLE
Base Install ./Ombi fails with Version issue

### ISSUE THREAD

**Issue by btrebbien** [tidusjar/Ombi#2590]
#### Ombi build Version:

V 3.0.3795

#### Update Branch:

master

#### Media Sever:

Plex

#### Media Server Version:

N/A as Ombi cannot start yet.

#### Operating System:

Linux Mint host OS. Running Ombi in Ubuntu 16.04 docker container

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

root@133c0d0331b0:/opt/Ombi# ./Ombi
Hello, welcome to Ombi
Valid options are:
Ombi 3.0.3795-master
Copyright (C) 2018 Ombi

  --host       (Default: http://*:5000) Set to a semicolon-separated (;) list 
               of URL prefixes to which the server should respond. For example,
               http://localhost:123. Use "*" to indicate that the server should
               listen for requests on any IP address or hostname using the 
               specified port and protocol (for example, http://*:5000). The 
               protocol (http:// or https://) must be included with each URL. 
               Supported formats vary between servers.

  --storage    Storage path, where we save the logs and database

  --baseurl    The base URL for reverse proxy scenarios

  --help       Display this help screen.

  --version    Display version information.



We are running on http://*:5000

Unhandled Exception: System.ArgumentOutOfRangeException: Version's parameters must be greater than or equal to zero.
Parameter name: revision
   at System.Version..ctor(Int32 major, Int32 minor, Int32 build, Int32 revision)
   at System.Environment.<>c.<.cctor>b__79_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.AspNetCore.Hosting.WebHostBuilderIISExtensions.UseIISIntegration(IWebHostBuilder hostBuilder)
   at Microsoft.AspNetCore.WebHost.CreateDefaultBuilder(String[] args)
   at Ombi.Program.BuildWebHost(String[] args) in C:\projects\requestplex\src\Ombi\Program.cs:line 114
   at Ombi.Program.Main(String[] args) in C:\projects\requestplex\src\Ombi\Program.cs:line 94
Aborted (core dumped)

root@133c0d0331b0:/opt/Ombi# ./Ombi --version
Ombi 3.0.3795-master

CommandLine.VersionRequestedError
Hello, welcome to Ombi
Valid options are:
Ombi 3.0.3795-master
Copyright (C) 2018 Ombi

  --host       (Default: http://*:5000) Set to a semicolon-separated (;) list 
               of URL prefixes to which the server should respond. For example,
               http://localhost:123. Use "*" to indicate that the server should
               listen for requests on any IP address or hostname using the 
               specified port and protocol (for example, http://*:5000). The 
               protocol (http:// or https://) must be included with each URL. 
               Supported formats vary between servers.

  --storage    Storage path, where we save the logs and database

  --baseurl    The base URL for reverse proxy scenarios

  --help       Display this help screen.

  --version    Display version information.



We are running on 

Unhandled Exception: System.ArgumentOutOfRangeException: Version's parameters must be greater than or equal to zero.
Parameter name: revision
   at System.Version..ctor(Int32 major, Int32 minor, Int32 build, Int32 revision)
   at System.Environment.<>c.<.cctor>b__79_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.AspNetCore.Hosting.WebHostBuilderIISExtensions.UseIISIntegration(IWebHostBuilder hostBuilder)
   at Microsoft.AspNetCore.WebHost.CreateDefaultBuilder(String[] args)
   at Ombi.Program.BuildWebHost(String[] args) in C:\projects\requestplex\src\Ombi\Program.cs:line 114
   at Ombi.Program.Main(String[] args) in C:\projects\requestplex\src\Ombi\Program.cs:line 94
Aborted (core dumped)

```

#### Problem Description:

Was having issue with Linuxserver docker container so came to https://github.com/tidusjar/Ombi/wiki/Installation to do a clean install following Apt repo (The easy way, only Debian based distros). I created a basic docker container with just the steps listed (see below reproduction steps) and exec'd into the container and ran the base ./Ombi command as shown in the install. I consistently get Version parameter must be greater than zero with both types of installs.

#### Reproduction Steps:

Dockerfile:
from ubuntu:16.04
RUN apt-get update -y && apt-get install -y wget 
RUN echo "deb [arch=amd64,armhf] http://repo.ombi.turd.me/stable/ jessie main" | tee "/etc/apt/sources.list.d/ombi.list"
RUN wget -qO - https://repo.ombi.turd.me/pubkey.txt | apt-key add -
RUN apt update && apt install -y ombi
EXPOSE 5000

$ docker run -tid -p 5000:5000 image bash
$ docker exec -ti container bash
$ cd /opt/Ombi
$ ./Ombi

**Comment by tidusjar** [comment]
Dont pass in `--version`. I've not added that yet,

**Comment by btrebbien** [comment]
The issue is not with passing in the - - version. The app won't start with just running ./Ombi  it fails with the unhandled exception

**Comment by tidusjar** [comment]
Oh ok, @louis-lau any ideas ?

**Comment by louis-lau** [comment]
You should use `--storage /etc/Ombi/` when using the apt repo, as the .deb expects the db to be there when updating. Other than that, I don't think this is an issue with the repo. @btrebbien does this also happen outside of docker for you?
