### ISSUE TITLE
Allow Ombi Token creation using oAuth Token

### ISSUE THREAD

**Issue by causefx** [tidusjar/Ombi#2591]
I have finally implemented Plex oAuth in org v2 and would like to inquire about obtaining an Ombi users Token using their oAuth Token.  Tautulli and org already do this now.  Was hoping you would allow it as well...

Thanks for your time.

**Comment by tidusjar** [comment]
Done in develop.

The API is in swagger POST: `api/v1/token/plextoken` with body 

    {
        "plexToken": "TokenHere"
    }

**Comment by causefx** [comment]
getting Error 500 on api....

{"error":"Object reference not set to an instance of an object."}

**Comment by causefx** [comment]
Full log error:

```
2018-10-26 15:33:08.228 -07:00 [Error] Something bad happened, ErrorMiddleware caught this
System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , OmbiUser )
   at System.Linq.AsyncEnumerable.WhereEnumerableAsyncIterator`1.MoveNextCore(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)
   at Ombi.Core.Authentication.OmbiUserManager.GetOmbiUserFromPlexToken(String plexToken) in C:\projects\requestplex\src\Ombi.Core\Authentication\OmbiUserManager.cs:line 112
   at Ombi.Controllers.TokenController.GetTokenWithPlexToken(PlexTokenAuthentication model) in C:\projects\requestplex\src\Ombi\Controllers\TokenController.cs:line 109
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 50
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24
```

**Comment by causefx** [comment]
Just spitballing but you wrote this:

```
        [HttpPost("plextoken")]
        public async Task<IActionResult> GetTokenWithPlexToken([FromBody] PlexTokenAuthentication model)
        {
            if (!model.PlexToken.HasValue())
            {
                return BadRequest("Token was not provided");
            }
            var user = await _userManager.GetOmbiUserFromPlexToken(model.PlexToken);
            if (user == null)
            {
                return Unauthorized();
            }
            return await CreateToken(true, user);
        }
```

you already had other stuff working, would this work:

```
[HttpPost("plextoken")]
public async Task<IActionResult> GetTokenWithPlexToken([FromBody] PlexTokenAuthentication model)
{
	if (!model.PlexToken.HasValue())
	{
		return BadRequest("Token was not provided");
	}
	// Let's look for the users account
	var account = await _plexOAuthManager.GetAccount(model.PlexToken);

	// Get the ombi user
	var user = await _userManager.FindByNameAsync(account.user.username);

	if (user == null)
	{
		// Could this be an email login?
		user = await _userManager.FindByEmailAsync(account.user.email);

		if (user == null)
		{
			return new UnauthorizedResult();
		}
	}

	return await CreateToken(true, user);
}
```

**Comment by tidusjar** [comment]
So the error above has been fixed?

The reason why I didn't do something like the above is that means i'm attempting to match on either the username or email.

The implimentation of `GetOmbiUserFromPlexToken` matches the user using the PlexId rather than the username or email address.

**Comment by causefx** [comment]
yes sir. tested and works. thanks for the response
