### ISSUE TITLE
TV-Show Search don´t work - Exception when calling ShowLookupByTheTvDbId

### ISSUE THREAD

**Issue by NikolasHanss** [tidusjar/Ombi#2595]
#### Ombi build Version:

V 3.0.3795 

#### Update Branch:

MASTER

#### Media Sever:

Plex

#### Media Server Version:

1.13.8.5395-10d48da0d

#### Operating System:

UnRAID Docker

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2018-10-17 16:05:54.488 +02:00 [Error] Exception when calling ShowLookupByTheTvDbId with id:81189
Newtonsoft.Json.JsonReaderException: Input string '61f' is not a valid number. Path '', line 1, position 3.
   at Newtonsoft.Json.JsonTextReader.ParseReadNumber(ReadType readType, Char firstChar, Int32 initialPosition)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 77
   at Ombi.Api.TvMaze.TvMazeApi.ShowLookupByTheTvDbId(Int32 theTvDbId) in C:\projects\requestplex\src\Ombi.Api.TvMaze\TvMazeApi.cs:line 58
2018-10-17 16:05:54.488 +02:00 [Error] Exception when calling ShowLookupByTheTvDbId with id:121361
Newtonsoft.Json.JsonReaderException: Input string '62b' is not a valid number. Path '', line 1, position 3.
   at Newtonsoft.Json.JsonTextReader.ParseReadNumber(ReadType readType, Char firstChar, Int32 initialPosition)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 77
   at Ombi.Api.TvMaze.TvMazeApi.ShowLookupByTheTvDbId(Int32 theTvDbId) in C:\projects\requestplex\src\Ombi.Api.TvMaze\TvMazeApi.cs:line 58
2018-10-17 16:05:54.524 +02:00 [Error] Exception when calling ShowLookupByTheTvDbId with id:153021
Newtonsoft.Json.JsonReaderException: Input string '64d' is not a valid number. Path '', line 1, position 3.
   at Newtonsoft.Json.JsonTextReader.ParseReadNumber(ReadType readType, Char firstChar, Int32 initialPosition)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 77
   at Ombi.Api.TvMaze.TvMazeApi.ShowLookupByTheTvDbId(Int32 theTvDbId) in C:\projects\requestplex\src\Ombi.Api.TvMaze\TvMazeApi.cs:line 58
2018-10-17 16:05:54.596 +02:00 [Error] Exception when calling ShowLookupByTheTvDbId with id:80379
Newtonsoft.Json.JsonSerializationException: Error converting value 616 to type 'Ombi.Api.TvMaze.Models.TvMazeShow'. Path '', line 1, position 3. ---> System.ArgumentException: Could not cast or convert from System.Int64 to Ombi.Api.TvMaze.Models.TvMazeShow.
   at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
   at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 77
   at Ombi.Api.TvMaze.TvMazeApi.ShowLookupByTheTvDbId(Int32 theTvDbId) in C:\projects\requestplex\src\Ombi.Api.TvMaze\TvMazeApi.cs:line 58
2018-10-17 16:05:54.623 +02:00 [Error] Exception when calling ShowLookupByTheTvDbId with id:176941
Newtonsoft.Json.JsonReaderException: Input string '42b' is not a valid number. Path '', line 1, position 3.
   at Newtonsoft.Json.JsonTextReader.ParseReadNumber(ReadType readType, Char firstChar, Int32 initialPosition)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 77
   at Ombi.Api.TvMaze.TvMazeApi.ShowLookupByTheTvDbId(Int32 theTvDbId) in C:\projects\requestplex\src\Ombi.Api.TvMaze\TvMazeApi.cs:line 58
2018-10-17 16:05:54.642 +02:00 [Error] Exception when calling ShowLookupByTheTvDbId with id:79349
Newtonsoft.Json.JsonSerializationException: Error converting value 436 to type 'Ombi.Api.TvMaze.Models.TvMazeShow'. Path '', line 1, position 3. ---> System.ArgumentException: Could not cast or convert from System.Int64 to Ombi.Api.TvMaze.Models.TvMazeShow.
   at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
   at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 77
   at Ombi.Api.TvMaze.TvMazeApi.ShowLookupByTheTvDbId(Int32 theTvDbId) in C:\projects\requestplex\src\Ombi.Api.TvMaze\TvMazeApi.cs:line 58
2018-10-17 16:05:54.692 +02:00 [Error] Exception when calling ShowLookupByTheTvDbId with id:75760
Newtonsoft.Json.JsonReaderException: Input string '5ca' is not a valid number. Path '', line 1, position 3.
   at Newtonsoft.Json.JsonTextReader.ParseReadNumber(ReadType readType, Char firstChar, Int32 initialPosition)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 77
   at Ombi.Api.TvMaze.TvMazeApi.ShowLookupByTheTvDbId(Int32 theTvDbId) in C:\projects\requestplex\src\Ombi.Api.TvMaze\TvMazeApi.cs:line 58
2018-10-17 16:05:54.722 +02:00 [Error] Exception when calling ShowLookupByTheTvDbId with id:257655
Newtonsoft.Json.JsonReaderException: Input string '5d5' is not a valid number. Path '', line 1, position 3.
   at Newtonsoft.Json.JsonTextReader.ParseReadNumber(ReadType readType, Char firstChar, Int32 initialPosition)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 77
   at Ombi.Api.TvMaze.TvMazeApi.ShowLookupByTheTvDbId(Int32 theTvDbId) in C:\projects\requestplex\src\Ombi.Api.TvMaze\TvMazeApi.cs:line 58
2018-10-17 16:05:54.746 +02:00 [Error] Exception when calling ShowLookupByTheTvDbId with id:79168
Newtonsoft.Json.JsonReaderException: Input string '4fc' is not a valid number. Path '', line 1, position 3.
   at Newtonsoft.Json.JsonTextReader.ParseReadNumber(ReadType readType, Char firstChar, Int32 initialPosition)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 77
   at Ombi.Api.TvMaze.TvMazeApi.ShowLookupByTheTvDbId(Int32 theTvDbId) in C:\projects\requestplex\src\Ombi.Api.TvMaze\TvMazeApi.cs:line 58
2018-10-17 16:05:54.777 +02:00 [Error] Exception when calling ShowLookupByTheTvDbId with id:73739
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: a. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 77
   at Ombi.Api.TvMaze.TvMazeApi.ShowLookupByTheTvDbId(Int32 theTvDbId) in C:\projects\requestplex\src\Ombi.Api.TvMaze\TvMazeApi.cs:line 58


```

#### Problem Description:

I can`t Request and Report TV-Shows, the search sometimes are working. Just reinstalled all and the problem is the Same. Movies are working fine.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Does this happen with everything you search?

**Comment by NikolasHanss** [comment]
> 
> 
> Does this happen with everything you search?

No, only with the TV-Shows. Sometimes the search works, but only in 1/10 cases.
The Request and Report feature never works.

I can give you access to my server, if it helps.

**Comment by tidusjar** [comment]
If you search the same thing in Https://demo.ombi.io does it happen?

**Comment by NikolasHanss** [comment]
I've got a DNS Error, "Error 1016 Ray ID: 46b5b92468912be8 • 2018-10-17 21:05:25 UTC
Origin DNS error"

**Comment by tidusjar** [comment]
My fault!

Try now.

**Comment by NikolasHanss** [comment]
> 
> 
> My fault!
> 
> Try now.

No, this does not work either. Only the search works fine (better than on my Server).

**Comment by NikolasHanss** [comment]
To request a TV Show. The search works fine.

**Comment by tidusjar** [comment]
I'm slightly confused now. You are having issues on the request or search on your instance?

**Comment by NikolasHanss** [comment]
I looked at the consol and get this Error, while searching for TV-Shows 

```
error: Object { error: "Object reference not set to an instance of an object." }
​
headers: Object { normalizedNames: Map(0), lazyUpdate: null, lazyInit: lazyInit()
 }
​
message: "Http failure response for http://192.168.10.15:3579/api/v1/Request/TV/: 500 Internal Server Error"
​
name: "HttpErrorResponse"
​
ok: false
​
status: 500
​
statusText: "Internal Server Error"
​
url: "http://192.168.10.15:3579/api/v1/Request/TV/"
​
<prototype>: Object { constructor: e()
 }

```

**Comment by tidusjar** [comment]
Have you tried the latest build?

**Comment by NikolasHanss** [comment]
Ok, it was the IPv6 routing....

**Comment by tidusjar** [comment]
Really? That's new news to me. Sorry I couldn't get back to you with an answer.

**Comment by NikolasHanss** [comment]
No Problem 👍
