### ISSUE TITLE
Email Notifications

### ISSUE THREAD

**Issue by overdox** [tidusjar/Ombi#2596]
#### Ombi build Version:
V  3.0.3795

#### Update Branch:
Open Beta

#### Media Sever:
Emby

#### Operating System:
Debian 9.5

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
2018-10-17 21:21:44.223 +02:00 [Warning] Exception when testing Email Notifications
System.InvalidOperationException: Invalid URI: The hostname could not be parsed.
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 94
   at Ombi.Controllers.External.TesterController.Email(EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 225

2018-10-17 21:23:45.582 +02:00 [Warning] Exception when testing Email Notifications
System.InvalidOperationException: Invalid URI: The hostname could not be parsed.
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 94
   at Ombi.Controllers.External.TesterController.Email(EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 225

2018-10-17 21:27:00.749 +02:00 [Warning] Exception when testing Email Notifications
System.InvalidOperationException: Invalid URI: The hostname could not be parsed.
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 94
   at Ombi.Controllers.External.TesterController.Email(EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 225

```

#### Problem Description:

Email notifications no longer work, the settings are saving without any errors, however if I try to send a test email the abowe error shows up in the logs. 
The settings are fine as I have used them in the past and are still using with other applications on the same server.

**Comment by tidusjar** [comment]
The host you are using for your email is not correct.

**Comment by overdox** [comment]
Have you changed how it works then? Cause I have not touched the settings, and they worked just fine before, and still works on other applications that I use.

**Comment by overdox** [comment]
Ok this is very odd, but I just copy pasted the exact same details into the settings and now it worked...
Disregard my previous statement...I guess...

**Comment by tidusjar** [comment]
Yeah nothing has changed with that!
