### ISSUE TITLE
Ombi fails on radar request

### ISSUE THREAD

**Issue by choldi** [tidusjar/Ombi#2604]
#### Ombi build Version:

Ombi
Version | 3.0.3919
Branch | master

### Update branch: 

master

#### Media Sever:

Emby

### Operating System:

Debian scratch 9.5
Docker image from linuxserver

Docker-compose.yml
ombi:
image: linuxserver/ombi:latest
container_name: ombi
environment:
TZ: 'Europe/Madrid'
restart: unless-stopped
volumes:
- ./config/ombi:/config
- /etc/localtime:/etc/localtime:ro
environment:
- TZ=Europe/Madrid
- PGID=0
- PUID=0

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

2018-10-19 20:38:15.435 +02:00 [Error] Something bad happened, ErrorMiddleware caught this
System.NullReferenceException: Object reference not set to an instance of an object.
at Ombi.Controllers.ImagesController.GetTvBanner(Int32 tvdbid) in C:\projects\requestplex\src\Ombi\Controllers\ImagesController.cs:line 42
at lambda_method(Closure , Object )
at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 50
at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24

#### Problem Description:

When I add a TV seriee request it won't process

ombi not working sending series to radarr.
Seems that ombi has been upgrade to solve that problem
tidusjar/Ombi#2544

But the last version won't solve the problem

**Comment by tidusjar** [comment]
Your issue makes no sense.

TV series wont process and it's not sending it to radarr? That is correct. 

Radarr is for movies.
