### ISSUE TITLE
Unable to get New request notification using pushover

### ISSUE THREAD

**Issue by Handl3vogn** [tidusjar/Ombi#2609]
#### Ombi build Version:

V 3.0.3923

#### Update Branch:

Master

#### Media Sever:

Emby

#### Operating System:

Unraid 6.6.2
Linuxserver/docker

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2018-10-20 10:53:50.882 +02:00 [Error] Something bad happened, ErrorMiddleware caught this
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Controllers.ImagesController.GetTvBanner(Int32 tvdbid) in C:\projects\requestplex\src\Ombi\Controllers\ImagesController.cs:line 42
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 50
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24

```

#### Problem Description:

I do not get new request notification when using pushover.
Other notifications seems to work like test and request approved.

Edit:
Found similar issue on reddit
https://www.reddit.com/r/Ombi/comments/9n8ekg/ombi_not_sending_request_notifications_to_pushover/

**Comment by tidusjar** [comment]
All pushover notifications go to what was specified in the settings. 

I've not got around to looking into this yet.

**Comment by gokou340** [comment]
I'm also having this issue. Test and Approved notifications are appearing, but when I request from a test account, I do not get a notification.

Here are the errors of my log file:
`2018-11-07 15:20:18.645 -07:00 [Error] Something bad happened, ErrorMiddleware caught this
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Schedule.Processor.ChangeLogProcessor.GetGitubRelease(Release release, String releaseTag) in C:\projects\requestplex\src\Ombi.Schedule\Processor\ChangeLogProcessor.cs:line 177
   at Ombi.Schedule.Processor.ChangeLogProcessor.Process(String branch) in C:\projects\requestplex\src\Ombi.Schedule\Processor\ChangeLogProcessor.cs:line 84
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.UpdateAvailable(String branch, String currentVersion) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 62
   at Ombi.Controllers.JobController.<CheckForUpdateCached>b__10_0() in C:\projects\requestplex\src\Ombi\Controllers\JobController.cs:line 84
   at Ombi.Helpers.CacheService.GetOrAdd[T](String cacheKey, Func`1 factory, DateTime absoluteExpiration) in C:\projects\requestplex\src\Ombi.Helpers\CacheService.cs:line 38
   at Ombi.Controllers.JobController.CheckForUpdateCached() in C:\projects\requestplex\src\Ombi\Controllers\JobController.cs:line 79
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 50
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24
2018-11-07 15:24:03.039 -07:00 [Error] Something bad happened, ErrorMiddleware caught this
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Schedule.Processor.ChangeLogProcessor.GetGitubRelease(Release release, String releaseTag) in C:\projects\requestplex\src\Ombi.Schedule\Processor\ChangeLogProcessor.cs:line 177
   at Ombi.Schedule.Processor.ChangeLogProcessor.Process(String branch) in C:\projects\requestplex\src\Ombi.Schedule\Processor\ChangeLogProcessor.cs:line 84
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.UpdateAvailable(String branch, String currentVersion) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 62
   at Ombi.Controllers.JobController.<CheckForUpdateCached>b__10_0() in C:\projects\requestplex\src\Ombi\Controllers\JobController.cs:line 84
   at Ombi.Helpers.CacheService.GetOrAdd[T](String cacheKey, Func`1 factory, DateTime absoluteExpiration) in C:\projects\requestplex\src\Ombi.Helpers\CacheService.cs:line 38
   at Ombi.Controllers.JobController.CheckForUpdateCached() in C:\projects\requestplex\src\Ombi\Controllers\JobController.cs:line 79
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 50
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24
`

**Comment by gokou340** [comment]
I just fixed my issue. It was due to what I found previously that was supposed to be fixed in a dev version back in August with invalid characters. I had to remove the ### '

@vladware I changed my "New Request" to the following and I started receiving requests notifications.
`Hello! The user {UserName} has requested the {Type} {Title}! Please log in to approve this request. Request Date: {RequestedDate}`
