### ISSUE TITLE
Cannot connect to local plex server with forced HTTPS

### ISSUE THREAD

**Issue by rix1337** [tidusjar/Ombi#2614]
#### Ombi build Version:

V 3.0.3923

#### Update Branch:

master

#### Media Sever:

Plex

#### Media Server Version:

Version 3.69.1 

#### Operating System:

Docker

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2018-10-21 20:24:20.060 +02:00 [Error] Could not test Plex
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---

```

#### Problem Description:

Ombi tries to verify the validity of plex certificates even when running locally. We need an option to disable this strict test. The workaround below is not ideal, since the local hostname can change at every plex server boot.

#### Reproduction Steps:

Force plex to only allow secure connection.

Set up plex server with local ip + port + ssl in ombi.

Test fails.

Set valid local hostname from plex certificate (`10-10-0-1.randomcharacters.plex.direct`).

Test successful.

**Comment by tidusjar** [comment]
You can disable certificate validation in the ombi settings

**Comment by Ing-Med** [comment]
Sorry, am i blind or something. Where is this Option in the settings? I am having the same Problem.

v 3.0. 4119

Thanks

**Comment by phaelon74** [comment]
Disabling certification validation in OMBI settings is not resolving this for me.  What gives?

3.0.4538
--

**Comment by phaelon74** [comment]
> Disabling certification validation in OMBI settings is not resolving this for me. What gives?
> 
> ## 3.0.4538

I fixed it.  I found this https://github.com/tidusjar/Ombi/issues/2762 which talked about how the setting contrary to the look of the GUI, does not take effect until restart.  My anger has calmed, but is still upset that the GUI doesn't tell you, you need to restart to take effect.
