### ISSUE TITLE
Plex login "unauthorised" error

### ISSUE THREAD

**Issue by norrisp90** [tidusjar/Ombi#2615]
#### Ombi build Version:

V 3.0.3930

#### Update Branch:

develop

#### Media Sever:

Plex 1.13.8.5395 

#### Operating System:

Ubuntu 18.04.1 LTS

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2018-10-22 20:11:21.223 +00:00 [Error] Something bad happened, ErrorMiddleware caught this
System.ArgumentNullException: Value cannot be null.
Parameter name: user
   at Microsoft.AspNetCore.Identity.UserManager`1.IsInRoleAsync(TUser user, String role)
   at Ombi.Core.Engine.Interfaces.BaseEngine.IsInRole(String roleName) in C:\projects\requestplex\src\Ombi.Core\Engine\Interfaces\BaseEngine.cs:line 42
   at Ombi.Core.Engine.BaseMediaEngine.HideFromOtherUsers() in C:\projects\requestplex\src\Ombi.Core\Engine\BaseMediaEngine.cs:line 114
   at Ombi.Core.Engine.MusicRequestEngine.GetRequests(Int32 count, Int32 position, OrderFilterModel orderFilter) in C:\projects\requestplex\src\Ombi.Core\Engine\MusicR$
   at Ombi.Controllers.MusicRequestController.GetRequests(Int32 count, Int32 position, Int32 orderType, Int32 statusType, Int32 availabilityType) in C:\projects\reques$
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Objec$
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 50
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24


```

#### Problem Description:

Cannot login after updating to latest. Try to login with Plex account and get error "Unauthorised" and these in log.

#### Reproduction Steps:

Upgrade to latest, try and login with plex account.

**Comment by tidusjar** [comment]
Are you sure that user is correct?

The log doesn't show any errors regarding logging in
