### ISSUE TITLE
Scheduled Jobs Not Running

### ISSUE THREAD

**Issue by jwor80** [tidusjar/Ombi#2619]
#### Ombi build Version:

V 3.0.3923

#### Update Branch:

master

#### Media Sever:

Emby

#### Media Server Version:

3.5.3.0

#### Operating System:

Windows 10

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

No log file being created

```

#### Problem Description:

Scheduled jobs do not appear to be running. Log files are not being created after a job should have ran and newsletters are not going out.

#### Reproduction Steps:

My Emby sync job is set to (50 * * * *) and the newsletter is scheduled for (0 * * * *). With these settings I would expect at 10 minutes until the hour ombi would pull in any new TV Shows or Movies and on the hour it would send out a newsletter with the new Shows/Movies. I am not receiving a newsletter nor is a log file being created in the Log directory.

**Comment by tidusjar** [comment]
Are new movies being added?


Do they show as available in the search?

**Comment by jwor80** [comment]
After upgrading to 3.0.3945 I'm seeing a log file and I received a newsletter for a new movie.  I'll have to wait and see if new episodes go out in the newsletter.

**Comment by tidusjar** [comment]
You can manually trigger the newsletter to see if you have a movie right now?

**Comment by jwor80** [comment]
I believe something is wrong with my EmbyEpisodes DB.  Example: In Emby "The Big Bang Theory S12E06" is the last episode however the Ombi search page shows I have S12E07 and I see that episode was added into the OmbiExternal.db on on 10/24/18.

**Comment by jwor80** [comment]
When I manually triggered the newsletter nothing went out but I'm not sure there are any new movies or episodes that would show up. However I did find the following in the log file which I find strange because I'm using emby not plex.

2018-10-26 14:56:39.565 -05:00 [Error] Something bad happened, ErrorMiddleware caught this
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Schedule.Processor.ChangeLogProcessor.GetGitubRelease(Release release, String releaseTag) in C:\projects\requestplex\src\Ombi.Schedule\Processor\ChangeLogProcessor.cs:line 177
   at Ombi.Schedule.Processor.ChangeLogProcessor.Process(String branch) in C:\projects\requestplex\src\Ombi.Schedule\Processor\ChangeLogProcessor.cs:line 84
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.UpdateAvailable(String branch, String currentVersion) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 62
   at Ombi.Controllers.JobController.<CheckForUpdateCached>b__10_0() in C:\projects\requestplex\src\Ombi\Controllers\JobController.cs:line 84
   at Ombi.Helpers.CacheService.GetOrAdd[T](String cacheKey, Func`1 factory, DateTime absoluteExpiration) in C:\projects\requestplex\src\Ombi.Helpers\CacheService.cs:line 38
   at Ombi.Controllers.JobController.CheckForUpdateCached() in C:\projects\requestplex\src\Ombi\Controllers\JobController.cs:line 79
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 50
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24

**Comment by jwor80** [comment]
I removed my OmbiExternal.db and let it rebuild.  When I view the database I see future episodes that I do not have.  I'm wondering if they are not going out in the newsletter because they are not considered "new" since they existed in the DB before the last newsletter went out.

**Comment by jwor80** [comment]
I'm closing this issue because I believe the scheduled jobs are running but TV Shows are not working correctly with the newsletter. I'll log a new issue with a better description.
