### ISSUE TITLE
Another 'can't find my shows' type of thing? Maybe.

### ISSUE THREAD

**Issue by Archigos** [tidusjar/Ombi#2627]
#### Ombi build Version:

V 3.0.3945-master

#### Update Branch:

Master

#### Media Sever:

Plex

#### Media Server Version:

3.67.1

#### Operating System:

MacOS Mojave 10.14

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2018-10-30 02:00:56.143 -04:00 [Information] 1 scheduled job(s) enqueued.
2018-10-30 08:00:48.803 -04:00 [Information] 1 scheduled job(s) enqueued.
2018-10-30 14:00:51.079 -04:00 [Information] 1 scheduled job(s) enqueued.
2018-10-30 20:18:25.806 -04:00 [Information] 1 scheduled job(s) enqueued.
2018-10-30 21:55:38.257 -04:00 [Error] Something bad happened, ErrorMiddleware caught this
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Schedule.Processor.ChangeLogProcessor.GetGitubRelease(Release release, String releaseTag) in C:\projects\requestplex\src\Ombi.Schedule\Processor\ChangeLogProcessor.cs:line 177
   at Ombi.Schedule.Processor.ChangeLogProcessor.Process(String branch) in C:\projects\requestplex\src\Ombi.Schedule\Processor\ChangeLogProcessor.cs:line 84
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.UpdateAvailable(String branch, String currentVersion) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 62
   at Ombi.Controllers.JobController.<CheckForUpdateCached>b__10_0() in C:\projects\requestplex\src\Ombi\Controllers\JobController.cs:line 84
   at Ombi.Helpers.CacheService.GetOrAdd[T](String cacheKey, Func`1 factory, DateTime absoluteExpiration) in C:\projects\requestplex\src\Ombi.Helpers\CacheService.cs:line 38
   at Ombi.Controllers.JobController.CheckForUpdateCached() in C:\projects\requestplex\src\Ombi\Controllers\JobController.cs:line 79
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 50
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24
2018-10-30 21:56:19.801 -04:00 [Error] Something bad happened, ErrorMiddleware caught this
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Schedule.Processor.ChangeLogProcessor.GetGitubRelease(Release release, String releaseTag) in C:\projects\requestplex\src\Ombi.Schedule\Processor\ChangeLogProcessor.cs:line 177
   at Ombi.Schedule.Processor.ChangeLogProcessor.Process(String branch) in C:\projects\requestplex\src\Ombi.Schedule\Processor\ChangeLogProcessor.cs:line 84
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.UpdateAvailable(String branch, String currentVersion) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 62
   at Ombi.Controllers.JobController.<CheckForUpdateCached>b__10_0() in C:\projects\requestplex\src\Ombi\Controllers\JobController.cs:line 84
   at Ombi.Helpers.CacheService.GetOrAdd[T](String cacheKey, Func`1 factory, DateTime absoluteExpiration) in C:\projects\requestplex\src\Ombi.Helpers\CacheService.cs:line 38
   at Ombi.Controllers.JobController.CheckForUpdateCached() in C:\projects\requestplex\src\Ombi\Controllers\JobController.cs:line 79
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 50
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24
2018-10-30 23:32:28.518 -04:00 [Error] Something bad happened, ErrorMiddleware caught this
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Schedule.Processor.ChangeLogProcessor.GetGitubRelease(Release release, String releaseTag) in C:\projects\requestplex\src\Ombi.Schedule\Processor\ChangeLogProcessor.cs:line 177
   at Ombi.Schedule.Processor.ChangeLogProcessor.Process(String branch) in C:\projects\requestplex\src\Ombi.Schedule\Processor\ChangeLogProcessor.cs:line 84
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.UpdateAvailable(String branch, String currentVersion) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 62
   at Ombi.Controllers.JobController.<CheckForUpdateCached>b__10_0() in C:\projects\requestplex\src\Ombi\Controllers\JobController.cs:line 84
   at Ombi.Helpers.CacheService.GetOrAdd[T](String cacheKey, Func`1 factory, DateTime absoluteExpiration) in C:\projects\requestplex\src\Ombi.Helpers\CacheService.cs:line 38
   at Ombi.Controllers.JobController.CheckForUpdateCached() in C:\projects\requestplex\src\Ombi\Controllers\JobController.cs:line 79
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 50
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24
2018-10-30 23:33:04.011 -04:00 [Error] Something bad happened, ErrorMiddleware caught this
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Schedule.Processor.ChangeLogProcessor.GetGitubRelease(Release release, String releaseTag) in C:\projects\requestplex\src\Ombi.Schedule\Processor\ChangeLogProcessor.cs:line 177
   at Ombi.Schedule.Processor.ChangeLogProcessor.Process(String branch) in C:\projects\requestplex\src\Ombi.Schedule\Processor\ChangeLogProcessor.cs:line 84
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.UpdateAvailable(String branch, String currentVersion) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 62
   at Ombi.Controllers.JobController.<CheckForUpdateCached>b__10_0() in C:\projects\requestplex\src\Ombi\Controllers\JobController.cs:line 84
   at Ombi.Helpers.CacheService.GetOrAdd[T](String cacheKey, Func`1 factory, DateTime absoluteExpiration) in C:\projects\requestplex\src\Ombi.Helpers\CacheService.cs:line 38
   at Ombi.Controllers.JobController.CheckForUpdateCached() in C:\projects\requestplex\src\Ombi\Controllers\JobController.cs:line 79
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 50
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24

```

#### Problem Description:

No idea what is causing the issue that ErrorMiddleware is catching all the time, but that happens very frequent. However, the issue I'm posting about is yet another 'it's not finding my shows available'. I have searched your FAQ and other places around the net to know enough that TVMaze must have the TVDb ID for it to work properly, but the shows I'm seeing this with it's hard to believe that they wouldn't have the ID {Ex. "The Walking Dead", "The Big Bang Theory", etc.} (not sure where to check, but it doesn't appear in the logs). I also verified in Plex that my TV library is set to use TheTVDb and I forced refreshed the metadata again just to be sure.

When you first log into Ombi and you see the search bar with the 'example' movies and tv shows is where I'm noticing that it's not finding my media. I haven't really gone in depth searching for my stuff to see exactly what it did and didn't find, but it seems to be way worse with my tv then my movies.

I'm willing to provide more information, including a copy of my Plex database, a created Ombi Admin, etc. if needed but only to someone that is proven as part of this project. I can also create any requested screenshots, etc. that I can make available via Dropbox.

#### Reproduction Steps:

No idea what steps could/would reproduce this.

**Comment by tidusjar** [comment]
Hi,

I am assuming you are referring to ombi not marking things as available when searching?

Or are you on about something else?

**Comment by Archigos** [comment]
Correct, it's not marking them all, for example, in this screenshot, it shows Game of Thrones, Walking Dead, and Big Bang Theory (which I have all of each) but only GoT shows as available.
![screenshot 2018-10-31 17 24 13 2 copy](https://user-images.githubusercontent.com/891049/47819958-62c54980-dd32-11e8-9beb-4fc9a5f55771.jpg)

**Comment by tidusjar** [comment]
Press request and then select...

What episodes are not appearing as available?

**Comment by Archigos** [comment]
Going to select for a few of the ones I had the problem with showed either a multipart episode (in Sonarr) that Plex has a single episode, therefore the second part shows 'missing' which is my fault. But the rest of the problem shows have episodes that haven't aired yet as pending, so I understand why it's not saying everything is available.

But while looking into this more I noticed another problem and also have a suggestion (which I can repost in another section later if you want).  So the new 'problem' I noticed is that Ombi has 'found' some movies that aren't available as being there... an example of what I mean is I happened to be viewing the "Popular Movies" list and it claimed I have *Schindler's List* but when you click the "View on Plex" it takes me to the TV show *Torchwood*. I've found two movies so far doing this (don't remember the other movie, but it went to a different tv show), but I haven't really looked that hard since I have such a large library.

And the quick suggestion, if a show is either partially/mostly available, or all current aired episodes are there, could the text be changed a little to show that... I mainly use Ombi to allow my parents to make requests or see what's available and I've had them call me more than once because they have a show they want (which I have), they see the Request button and apparently don't notice the little popup box saying that the episodes requested are available.

**Comment by tidusjar** [comment]
Please try out the develop branch, there have already been changes around
this

**Comment by Archigos** [comment]
What would be the easiest way to switch over to the Dev branch on a Mac since I assume I'd have to compile it? (unsure how)

**Comment by tidusjar** [comment]
Any news on the rest?

**Comment by Archigos** [comment]
It seems to have fixed most, but not all of the shows. The *Schindler's List* / *Torchwood* issue is still there and an example of the TV shows, although *The Walking Dead* now shows available, *Arrow (2012)* still has "Request" shown, but when you go to select all currently aired episodes are available, but the latest season has a handful of "Processing Request" on episodes that haven't aired yet. I haven't dug into enough to see exactly how many 'errors' are there, but doing quick searches on some that were messed up shows most (like 80%+) are fixed compared to before.

**Comment by DrAg0n141** [comment]
I have the same issue, where i can change the branch? I have the Linuxserver Docker installed.

**Comment by Archigos** [comment]
@DrAg0n141 From what I can see, you can't change the branch inside Ombi itself. What I ended up doing was downloading the Dev branch from the AppVeyor link on the main page, killing the current Ombi that was running and just overwrite the files with the new ones and start it back up.

No idea if that's a 'good' way to do with for a Docker version, but I'd say, back up your current one and give it a try. Worse case, you can restore the backup and wait for Jamie to respond.

**Comment by tidusjar** [comment]
There is a docker by the lsio team that looks at the Dev branch.

**Comment by tidusjar** [comment]
Is this still an issue now @Archigos

**Comment by Archigos** [comment]
Sorry, I haven’t replied back.... One of the drives in my server took a dump and corrupted the entire system so I’ve frantically been trying to fix it by moving data around. The last I remember Ombi had found most of the "missing" shows but still had that issue I mentioned with Arrow for example and the Schindler's List/Torchwood thing. Once I’m able to restore all my media and set up fresh libraries in Plex I’ll give it another try, but it’s looking like it’ll be at least a week for them to send my warranty replacement drive (and pray I didn’t lose everything else because of it).

**Comment by goldenpipes** [comment]
So for me I was able to request the episodes I did not have. After running a full sync I got processing request.

**Comment by goldenpipes** [comment]
What status are we expecting for a series that is currently airing?

**Comment by Archigos** [comment]
As I had said, the other shows (even current airing ones) showed as Available after switching to the Dev branch, I was just pointing out that Arrow (possibly others) still showed as Request (which is fine for me, but was a bit confusing to the users I had set Ombi up for in the first place, they assumed it meant I didn't have that show at all).

I'm still attempting to recover/restore data from the dead drive I mentioned a few days ago so I can't test anything right now and once I finish replacing the drive I just decided I was going to scrap the Sonarr/Radarr/Lidarr installs I had since my Plex database is gone and would reimport everything fresh.

**Comment by goldenpipes** [comment]
I see what what you mean.

When Episodes haven't aired its not marked as available simply because it physically can't be available.

Maybe there should be an IF_UNAIRED=IGNORE or something.

@tidusjar what you think?

**Comment by tidusjar** [comment]
So in the Dev branch if you have every aired episode then we show the series as available (unaired episodes are not marked as available). If you do not have every aired episodes then it's not available. 

Does this clear the question up?

**Comment by Archigos** [comment]
It makes sense, but I was on the Dev branch when I had the issue with Arrow, but other still airing shows were marked.

**Comment by tidusjar** [comment]
Yeah it's hard to say what has gone on with that right now as you know lol. I guess just let us know when you get around to reinstalling ombi?

**Comment by Archigos** [comment]
If everything goes well, it'll be later tonight or tomorrow. I know it's a pain trying to figure this out when my stuff is broken. :)
