### ISSUE TITLE
Requests stuck on processing (Radarr)

### ISSUE THREAD

**Issue by darkcloud784** [tidusjar/Ombi#2632]
#### Ombi build Version:

V 3.0.3945

#### Update Branch:

Open

#### Media Sever:

Plex

#### Operating System:

Ubuntu 16.04

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
2018-11-04 11:53:14.155 -06:00 [Error] Something bad happened, ErrorMiddleware caught this
System.Net.Http.HttpRequestException: Connection refused ---> System.Net.Sockets.SocketException: Connection refused
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request) in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
   at Ombi.Api.Radarr.RadarrApi.GetProfiles(String apiKey, String baseUrl) in C:\projects\requestplex\src\Ombi.Api.Radarr\RadarrApi.cs:line 28
   at Ombi.Controllers.External.RadarrController.GetProfiles() in C:\projects\requestplex\src\Ombi\Controllers\External\RadarrController.cs:line 68
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 50
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24
2018-11-04 11:53:29.609 -06:00 [Error] Something bad happened, ErrorMiddleware caught this
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Schedule.Processor.ChangeLogProcessor.GetGitubRelease(Release release, String releaseTag) in C:\projects\requestplex\src\Ombi.Schedule\Processor\ChangeLogProcessor.cs:line 177
   at Ombi.Schedule.Processor.ChangeLogProcessor.Process(String branch) in C:\projects\requestplex\src\Ombi.Schedule\Processor\ChangeLogProcessor.cs:line 84
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.UpdateAvailable(String branch, String currentVersion) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 62
   at Ombi.Controllers.JobController.<CheckForUpdateCached>b__10_0() in C:\projects\requestplex\src\Ombi\Controllers\JobController.cs:line 84
   at Ombi.Helpers.CacheService.GetOrAdd[T](String cacheKey, Func`1 factory, DateTime absoluteExpiration) in C:\projects\requestplex\src\Ombi.Helpers\CacheService.cs:line 38
   at Ombi.Controllers.JobController.CheckForUpdateCached() in C:\projects\requestplex\src\Ombi\Controllers\JobController.cs:line 79
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 50
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24

```

#### Problem Description:

Ombi says it connection successful to radarr, but is not syncing with it. All my requests are stuck in processing. I get the above error in the logs. I have no reverse proxy setup for radarr or ombi. This is a fresh installation of ombi.

#### Reproduction Steps:

Install radarr, do basic configuration , install ombi also do basic configuration for radarr including API key, root directories and quality settings. Then attempt to add something to OMBI and wait for it to attempt sync to radarr. None of the movies requested will show up in radarr.

**Comment by tidusjar** [comment]
Looking at the logs ombi is trying to connect but it's coming back saying the connection has been refused. Maybe try a different IP or hostname, also check any firewalls you have.

**Comment by darkcloud784** [comment]
> Looking at the logs ombi is trying to connect but it's coming back saying the connection has been refused. Maybe try a different IP or hostname, also check any firewalls you have.

I have disabled the firewall. There is only 1 IP, and its not a network issue. In fact, when I go to Ombi and test the connection it is successful. It can even pull the root paths and quality profiles without issues.

**Comment by tidusjar** [comment]
That's not what the logs are saying. Is the enable button checked in the settings?

**Comment by darkcloud784** [comment]
![radarrombi](https://user-images.githubusercontent.com/989990/47969578-33b71c80-e03f-11e8-99c7-05387e58fbea.PNG)

**Comment by tidusjar** [comment]
Ok, so when you request a movie and approve it, it does not end up in Radarr?

Can you please request a movie, approve it so it gets sent to radarr and then show me the log files for that?

**Comment by darkcloud784** [comment]
> Ok, so when you request a movie and approve it, it does not end up in Radarr?
> 
> Can you please request a movie, approve it so it gets sent to radarr and then show me the log files for that?

No it does not end up in Radarr, and what I provided was the log output I got. The only other relevant log output I have referencing ombi is the following.

`
Nov  4 20:32:22 organizer Ombi[1165]: #033[41m#033[30mfail#033[39m#033[22m#033[49m: Ombi.ErrorHandlingMiddleware[0]
Nov  4 20:32:22 organizer Ombi[1165]:       Something bad happened, ErrorMiddleware caught this
Nov  4 20:32:22 organizer Ombi[1165]: System.NullReferenceException: Object reference not set to an instance of an object.
Nov  4 20:32:22 organizer Ombi[1165]:    at Ombi.Core.Senders.MovieSender.RadarrRootPath(Int32 overrideId, RadarrSettings settings) in C:\projects\requestplex\src\Ombi.Core\Senders\MovieSender.cs:line 165
Nov  4 20:32:22 organizer Ombi[1165]:    at Ombi.Core.Senders.MovieSender.SendToRadarr(MovieRequests model, RadarrSettings settings) in C:\projects\requestplex\src\Ombi.Core\Senders\MovieSender.cs:line 106
Nov  4 20:32:22 organizer Ombi[1165]:    at Ombi.Core.Senders.MovieSender.Send(MovieRequests model) in C:\projects\requestplex\src\Ombi.Core\Senders\MovieSender.cs:line 50
Nov  4 20:32:22 organizer Ombi[1165]:    at Ombi.Core.Engine.MovieRequestEngine.ApproveMovie(MovieRequests request) in C:\projects\requestplex\src\Ombi.Core\Engine\MovieRequestEngine.cs:line 353
Nov  4 20:32:22 organizer Ombi[1165]:    at Ombi.Core.Engine.MovieRequestEngine.RequestMovie(MovieRequestViewModel model) in C:\projects\requestplex\src\Ombi.Core\Engine\MovieRequestEngine.cs:line 106
Nov  4 20:32:22 organizer Ombi[1165]:    at Ombi.Controllers.RequestController.RequestMovie(MovieRequestViewModel movie) in C:\projects\requestplex\src\Ombi\Controllers\RequestController.cs:line 84
Nov  4 20:32:22 organizer Ombi[1165]:    at lambda_method(Closure , Object )
Nov  4 20:32:22 organizer Ombi[1165]:    at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Nov  4 20:32:22 organizer Ombi[1165]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
Nov  4 20:32:22 organizer Ombi[1165]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
Nov  4 20:32:22 organizer Ombi[1165]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
Nov  4 20:32:22 organizer Ombi[1165]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Nov  4 20:32:22 organizer Ombi[1165]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
Nov  4 20:32:22 organizer Ombi[1165]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
Nov  4 20:32:22 organizer Ombi[1165]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Nov  4 20:32:22 organizer Ombi[1165]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Nov  4 20:32:22 organizer Ombi[1165]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
Nov  4 20:32:22 organizer Ombi[1165]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
Nov  4 20:32:22 organizer Ombi[1165]:    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Nov  4 20:32:22 organizer Ombi[1165]:    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Nov  4 20:32:22 organizer Ombi[1165]:    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
Nov  4 20:32:22 organizer Ombi[1165]:    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
Nov  4 20:32:22 organizer Ombi[1165]:    at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
Nov  4 20:32:22 organizer Ombi[1165]:    at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 50
Nov  4 20:32:22 organizer Ombi[1165]:    at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24
Nov  4 20:32:45 organizer Ombi[1165]: #033[41m#033[30mfail#033[39m#033[22m#033[49m: Ombi.ErrorHandlingMiddleware[0]
Nov  4 20:32:45 organizer Ombi[1165]:       Something bad happened, ErrorMiddleware caught this
Nov  4 20:32:45 organizer Ombi[1165]: System.NullReferenceException: Object reference not set to an instance of an object.
Nov  4 20:32:45 organizer Ombi[1165]:    at Ombi.Schedule.Processor.ChangeLogProcessor.GetGitubRelease(Release release, String releaseTag) in C:\projects\requestplex\src\Ombi.Schedule\Processor\ChangeLogProcessor.cs:line 177
Nov  4 20:32:45 organizer Ombi[1165]:    at Ombi.Schedule.Processor.ChangeLogProcessor.Process(String branch) in C:\projects\requestplex\src\Ombi.Schedule\Processor\ChangeLogProcessor.cs:line 84
Nov  4 20:32:45 organizer Ombi[1165]:    at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.UpdateAvailable(String branch, String currentVersion) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 62
Nov  4 20:32:45 organizer Ombi[1165]:    at Ombi.Controllers.JobController.<CheckForUpdateCached>b__10_0() in C:\projects\requestplex\src\Ombi\Controllers\JobController.cs:line 84
Nov  4 20:32:45 organizer Ombi[1165]:    at Ombi.Helpers.CacheService.GetOrAdd[T](String cacheKey, Func`1 factory, DateTime absoluteExpiration) in C:\projects\requestplex\src\Ombi.Helpers\CacheService.cs:line 38
Nov  4 20:32:45 organizer Ombi[1165]:    at Ombi.Controllers.JobController.CheckForUpdateCached() in C:\projects\requestplex\src\Ombi\Controllers\JobController.cs:line 79
Nov  4 20:32:45 organizer Ombi[1165]:    at lambda_method(Closure , Object )
Nov  4 20:32:45 organizer Ombi[1165]:    at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Nov  4 20:32:45 organizer Ombi[1165]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
Nov  4 20:32:45 organizer Ombi[1165]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
Nov  4 20:32:45 organizer Ombi[1165]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
Nov  4 20:32:45 organizer Ombi[1165]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Nov  4 20:32:45 organizer Ombi[1165]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
Nov  4 20:32:45 organizer Ombi[1165]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
Nov  4 20:32:45 organizer Ombi[1165]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Nov  4 20:32:45 organizer Ombi[1165]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Nov  4 20:32:45 organizer Ombi[1165]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
Nov  4 20:32:45 organizer Ombi[1165]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
Nov  4 20:32:45 organizer Ombi[1165]:    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Nov  4 20:32:45 organizer Ombi[1165]:    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Nov  4 20:32:45 organizer Ombi[1165]:    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
Nov  4 20:32:45 organizer Ombi[1165]:    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
Nov  4 20:32:45 organizer Ombi[1165]:    at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
Nov  4 20:32:45 organizer Ombi[1165]:    at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 50
Nov  4 20:32:45 organizer Ombi[1165]:    at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24
Nov  4 20:37:41 organizer Ombi[1165]: #033[41m#033[30mfail#033[39m#033[22m#033[49m: Ombi.ErrorHandlingMiddleware[0]
Nov  4 20:37:41 organizer Ombi[1165]:       Something bad happened, ErrorMiddleware caught this
Nov  4 20:37:41 organizer Ombi[1165]: System.NullReferenceException: Object reference not set to an instance of an object.
Nov  4 20:37:41 organizer Ombi[1165]:    at Ombi.Core.Senders.MovieSender.RadarrRootPath(Int32 overrideId, RadarrSettings settings) in C:\projects\requestplex\src\Ombi.Core\Senders\MovieSender.cs:line 165
Nov  4 20:37:41 organizer Ombi[1165]:    at Ombi.Core.Senders.MovieSender.SendToRadarr(MovieRequests model, RadarrSettings settings) in C:\projects\requestplex\src\Ombi.Core\Senders\MovieSender.cs:line 106
Nov  4 20:37:41 organizer Ombi[1165]:    at Ombi.Core.Senders.MovieSender.Send(MovieRequests model) in C:\projects\requestplex\src\Ombi.Core\Senders\MovieSender.cs:line 50
Nov  4 20:37:41 organizer Ombi[1165]:    at Ombi.Core.Engine.MovieRequestEngine.ApproveMovie(MovieRequests request) in C:\projects\requestplex\src\Ombi.Core\Engine\MovieRequestEngine.cs:line 353
Nov  4 20:37:41 organizer Ombi[1165]:    at Ombi.Core.Engine.MovieRequestEngine.RequestMovie(MovieRequestViewModel model) in C:\projects\requestplex\src\Ombi.Core\Engine\MovieRequestEngine.cs:line 106
Nov  4 20:37:41 organizer Ombi[1165]:    at Ombi.Controllers.RequestController.RequestMovie(MovieRequestViewModel movie) in C:\projects\requestplex\src\Ombi\Controllers\RequestController.cs:line 84
Nov  4 20:37:41 organizer Ombi[1165]:    at lambda_method(Closure , Object )
Nov  4 20:37:41 organizer Ombi[1165]:    at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Nov  4 20:37:41 organizer Ombi[1165]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
Nov  4 20:37:41 organizer Ombi[1165]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
Nov  4 20:37:41 organizer Ombi[1165]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
Nov  4 20:37:41 organizer Ombi[1165]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Nov  4 20:37:41 organizer Ombi[1165]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
Nov  4 20:37:41 organizer Ombi[1165]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
Nov  4 20:37:41 organizer Ombi[1165]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Nov  4 20:37:41 organizer Ombi[1165]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Nov  4 20:37:41 organizer Ombi[1165]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
Nov  4 20:37:41 organizer Ombi[1165]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
Nov  4 20:37:41 organizer Ombi[1165]:    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Nov  4 20:37:41 organizer Ombi[1165]:    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Nov  4 20:37:41 organizer Ombi[1165]:    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
Nov  4 20:37:41 organizer Ombi[1165]:    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
Nov  4 20:37:41 organizer Ombi[1165]:    at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
Nov  4 20:37:41 organizer Ombi[1165]:    at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 50
Nov  4 20:37:41 organizer Ombi[1165]:    at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24
`

**Comment by angdigi** [comment]
I'm also having the same issue. Let me know how I can help.

**Comment by maui1911** [comment]
I have the same issue, for months acutally. Sonarr fine, Radarr configuration fine but does not add movies to it.

**Comment by FinnHagen** [comment]
![radarr](https://user-images.githubusercontent.com/45092581/48609145-a69b8e00-e983-11e8-8836-e9a574501838.png)

Same problem here. Tried the API key change. Didn't work. Until I realized I have forgotten to check the enable box.... Stupid me... Now its working.

**Comment by tidusjar** [comment]
Wouldn't have been the first time someone has done that 😥

**Comment by FinnHagen** [comment]
But yeah, changing the API Key for both Radarr and SickRage made them both work for me.
And of course, checking the enable box!

**Comment by darkcloud784** [comment]
> Generate a new Api Key in radarr and enter the new key in ombi and try it. Sometimes the config.xml gets corrupted. Alternatively deleting the config.xml for radarr/sonarr resets your api key port and base url settings.
> 
> Also are you using reverse proxy or anything?
> 
> Cheers

I've tried re-installing radarr, re-installing ombi with no luck. I have all the users set to auto-approve, I receive no other errors in the syslog. Radarr has no proxy, my base url information is all in a picture above.

**Comment by tidusjar** [comment]
That does help. I'll see if I can put more logging around that area or see if I can identify the issue.

**Comment by tidusjar** [comment]
This has been fixed in develop
