### ISSUE TITLE
Ombi not marking movies as available

### ISSUE THREAD

**Issue by DormantCheese** [tidusjar/Ombi#2637]
#### Ombi build Version:

V 3.0.3945

#### Update Branch:

master

#### Media Sever:

Plex

#### Media Server Version:

Plex 1.13.9.54.56

#### Operating System:

Plex system: Ubuntu 16.04.5 LTS
Ombi system: Ubuntu 18.04.1 LTS

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
$ less /opt/Ombi/Logs/log-20181110.txt
2018-11-10 17:16:13.723 +00:00 [Error] Something bad happened, ErrorMiddleware caught this
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Schedule.Processor.ChangeLogProcessor.GetGitubRelease(Release release, String releaseTag) in C:\projects\requestplex\src\Ombi.Schedule\Processor\ChangeLogProcessor.cs:line 177
   at Ombi.Schedule.Processor.ChangeLogProcessor.Process(String branch) in C:\projects\requestplex\src\Ombi.Schedule\Processor\ChangeLogProcessor.cs:line 84
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.UpdateAvailable(String branch, String currentVersion) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 62
   at Ombi.Controllers.JobController.<CheckForUpdateCached>b__10_0() in C:\projects\requestplex\src\Ombi\Controllers\JobController.cs:line 84
   at Ombi.Helpers.CacheService.GetOrAdd[T](String cacheKey, Func`1 factory, DateTime absoluteExpiration) in C:\projects\requestplex\src\Ombi.Helpers\CacheService.cs:line 38
   at Ombi.Controllers.JobController.CheckForUpdateCached() in C:\projects\requestplex\src\Ombi\Controllers\JobController.cs:line 79
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 50
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24


```

#### Problem Description:

Previously, I had Ombi installed on the same host as Plex (home NAS), but after an update to the latest version prevented Ombi from starting, I installed Ombi on a new DigitalOcean droplet. Ombi is able to connect to my Plex instance, as it's pulling my list of libraries, but nothing is getting marked as available. If I go to the Settings/Plex page and click the Test Connectivity button, I get a message in the upper right saying "Successfully connected to the Plex server {servername}!" If I click the Manually Run Full Sync button, I get a message saying "Triggered the Plex Full Sync" and nothing else happens.

Also, I ran tail -f against the log file and it seems the only time anything was written was when I loaded the Settings/About page.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

1. Navigate to the Settings/Plex page
2. After entering Plex server info, manually select the libraries to monitor
3. Submit the form
4. Click the Manually Run Full Sync button
5. No movies or TV shows are marked as available

**Comment by Dimmerworld** [comment]
Getting a similar issue, only affects movies (Radarr), not tv shows,

**Comment by pyto00** [comment]
Exactly the same problem. Running Ombi also external on Digital Ocean Droplet.
See issue #2626

**Comment by tidusjar** [comment]
dupe
