### ISSUE TITLE
Sonarr ..

### ISSUE THREAD

**Issue by grego31430** [tidusjar/Ombi#2643]
#### Ombi build Version:

V 3.0.3970

#### Update Branch:

Beta

#### Media Sever:

Emby

#### Operating System:

Debian

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2018-11-14 19:21:52.607 +01:00 [Error] Something bad happened, ErrorMiddleware caught this
System.ArgumentNullException: Value cannot be null.
Parameter name: s
   at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model)
   at Ombi.Core.Senders.TvSender.Send(ChildRequests model) in C:\projects\requestplex\src\Ombi.Core\Senders\TvSender.cs:line 52
   at Ombi.Core.Engine.TvRequestEngine.AfterRequest(ChildRequests model) in C:\projects\requestplex\src\Ombi.Core\Engine\TvRequestEngine.cs:line 604
   at Ombi.Core.Engine.TvRequestEngine.AddRequest(TvRequests model) in C:\projects\requestplex\src\Ombi.Core\Engine\TvRequestEngine.cs:line 567
   at Ombi.Core.Engine.TvRequestEngine.RequestTvShow(TvRequestViewModel tv) in C:\projects\requestplex\src\Ombi.Core\Engine\TvRequestEngine.cs:line 134
   at Ombi.Controllers.RequestController.RequestTv(TvRequestViewModel tv) in C:\projects\requestplex\src\Ombi\Controllers\RequestController.cs:line 280
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 50
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24


```

#### Problem Description:

Not sync with Sonarr, and when request for a TV show this error wirte in Logs File

#### Reproduction Steps:
Just config Sonarr, and request a TV show

**Comment by tidusjar** [comment]
Is all your sonarr settings all setup?

**Comment by grego31430** [comment]
yes

**Comment by grego31430** [comment]
![screenshot_2018-11-14 ombi](https://user-images.githubusercontent.com/22960003/48510517-5eca1900-e854-11e8-8af7-04cfa7d2643a.png)

**Comment by goldenpipes** [comment]
Do you have plex or emy setup? Ombi doesn't sync with sonarr. It pushes to sonarr.

**Comment by grego31430** [comment]
Yes, I have Emby setup

**Comment by tidusjar** [comment]
Does the user you are requesting with have a custom path or quality?

**Comment by grego31430** [comment]
I need to up, Ombi is a great software, and I really want to fix this issue :/

**Comment by goldenpipes** [comment]
what does sonarr show for that show?

**Comment by grego31430** [comment]
Nothing, the show is downloaded and added, without missing episode

**Comment by goldenpipes** [comment]
what media server are you using? Plex or Emby?

**Comment by grego31430** [comment]
I use Emby

**Comment by goldenpipes** [comment]
@grego31430 is this still an issue for you?
