### ISSUE TITLE
Crash on start v3.0.3945

### ISSUE THREAD

**Issue by muadeeb** [tidusjar/Ombi#2645]
#### Ombi build Version:

V 3.0.3945

#### Update Branch:

Master

#### Media Sever:

Plex

#### Media Server Version:

1.13.9.5456

#### Operating System:

Ubuntu 18.04.1

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

Output of journalctl -u ombi.service -n 50

```

Nov 14 20:46:17 Ryoko Ombi[10420]: Hello, welcome to Ombi
Nov 14 20:46:17 Ryoko Ombi[10420]: Valid options are:
Nov 14 20:46:17 Ryoko Ombi[10420]: Ombi 3.0.3945-master
Nov 14 20:46:17 Ryoko Ombi[10420]: Copyright (C) 2018 Ombi
Nov 14 20:46:17 Ryoko Ombi[10420]:   --host       (Default: http://*:5000) Set to a semicolon-separated (;) list
Nov 14 20:46:17 Ryoko Ombi[10420]:                of URL prefixes to which the server should respond. For example,
Nov 14 20:46:17 Ryoko Ombi[10420]: Copyright (C) 2018 Ombi
Nov 14 20:46:17 Ryoko Ombi[10420]:   --host       (Default: http://*:5000) Set to a semicolon-separated (;) list
Nov 14 20:46:17 Ryoko Ombi[10420]:                of URL prefixes to which the server should respond. For example,
Nov 14 20:46:17 Ryoko Ombi[10420]:                http://localhost:123. Use "*" to indicate that the server should
Nov 14 20:46:17 Ryoko Ombi[10420]:                listen for requests on any IP address or hostname using the
Nov 14 20:46:17 Ryoko Ombi[10420]:                specified port and protocol (for example, http://*:5000). The
Nov 14 20:46:17 Ryoko Ombi[10420]:                protocol (http:// or https://) must be included with each URL.
Nov 14 20:46:17 Ryoko Ombi[10420]:                Supported formats vary between servers.
Nov 14 20:46:17 Ryoko Ombi[10420]:   --storage    Storage path, where we save the logs and database
Nov 14 20:46:17 Ryoko Ombi[10420]:   --baseurl    The base URL for reverse proxy scenarios
Nov 14 20:46:17 Ryoko Ombi[10420]:   --help       Display this help screen.
Nov 14 20:46:17 Ryoko Ombi[10420]:   --version    Display version information.
Nov 14 20:46:19 Ryoko Ombi[10420]: We are running on
Nov 14 20:46:19 Ryoko Ombi[10420]: Unhandled Exception: System.ArgumentOutOfRangeException: Version's parameters must be greater than or equal to zero.
Nov 14 20:46:19 Ryoko Ombi[10420]: Parameter name: revision
Nov 14 20:46:19 Ryoko Ombi[10420]:    at System.Version..ctor(Int32 major, Int32 minor, Int32 build, Int32 revision)
Nov 14 20:46:19 Ryoko Ombi[10420]:    at System.Environment.<>c.<.cctor>b__79_0()
Nov 14 20:46:19 Ryoko Ombi[10420]:    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
Nov 14 20:46:19 Ryoko Ombi[10420]:    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
Nov 14 20:46:19 Ryoko Ombi[10420]:    at System.Lazy`1.CreateValue()
Nov 14 20:46:19 Ryoko Ombi[10420]:    at Microsoft.AspNetCore.Hosting.WebHostBuilderIISExtensions.UseIISIntegration(IWebHostBuilder hostBuilder)
Nov 14 20:46:19 Ryoko Ombi[10420]:    at Microsoft.AspNetCore.WebHost.CreateDefaultBuilder(String[] args)
Nov 14 20:46:19 Ryoko Ombi[10420]:    at Ombi.Program.BuildWebHost(String[] args) in C:\projects\requestplex\src\Ombi\Program.cs:line 249
Nov 14 20:46:19 Ryoko Ombi[10420]:    at Ombi.Program.Main(String[] args) in C:\projects\requestplex\src\Ombi\Program.cs:line 96
Nov 14 20:46:19 Ryoko systemd[1]: ombi.service: Main process exited, code=dumped, status=6/ABRT
Nov 14 20:46:19 Ryoko systemd[1]: ombi.service: Failed with result 'core-dump'.

```

#### Mono Version

```

Mono JIT compiler version 5.16.0.179 (tarball Thu Oct  4 10:29:21 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          yes(3.6.0svn-mono-/)
        GC:            sgen (concurrent by default)

```

#### Problem Description:

Service crashes shortly after launch

#### Reproduction Steps:

Crashes occurred after an update of Ombi to 3945 on the 14th

**Comment by tidusjar** [comment]
I out are passing in an invalid command called revision. Dont do that
