### ISSUE TITLE
type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.

### ISSUE THREAD

**Issue by PrathikGopal** [tidusjar/Ombi#2674]
#### Ombi build Version:

Latest TAG of LSIO 

#### Update Branch:

Docker -LSIO

#### Media Sever:

Plex

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
2018-12-08 00:47:15.928 +05:30 [Error] StatusCode: TooManyRequests, Reason: Too Many Requests, RequestUri: http://api.tvmaze.com/shows/9672/episodes
2018-12-08 00:47:16.160 +05:30 [Error] StatusCode: TooManyRequests, Reason: Too Many Requests, RequestUri: http://api.tvmaze.com/lookup/shows?thetvdb=79285
2018-12-08 00:47:16.369 +05:30 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.tvmaze.com/shows/0/episodes
2018-12-08 00:47:16.401 +05:30 [Error] StatusCode: TooManyRequests, Reason: Too Many Requests, RequestUri: http://api.tvmaze.com/lookup/shows?thetvdb=71180
2018-12-08 00:47:16.552 +05:30 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.tvmaze.com/shows/0/episodes
2018-12-08 00:47:16.849 +05:30 [Error] Something bad happened, ErrorMiddleware caught this
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[Ombi.Api.TvMaze.Models.TvMazeEpisodes]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'name', line 1, position 8.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 77
   at Ombi.Api.TvMaze.TvMazeApi.EpisodeLookup(Int32 showId) in C:\projects\requestplex\src\Ombi.Api.TvMaze\TvMazeApi.cs:line 49
   at Ombi.Core.Engine.TvSearchEngine.GetShowInformation(Int32 tvdbid) in C:\projects\requestplex\src\Ombi.Core\Engine\TvSearchEngine.cs:line 79
   at Ombi.Controllers.SearchController.GetShowInfo(Int32 tvdbId) in C:\projects\requestplex\src\Ombi\Controllers\SearchController.cs:line 141
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 50
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24

```

#### Problem Description:

Application failing to start, 
tried clean install, removed config folders, still failing
it seems to repeat the above errors

#### Reproduction Steps:

Install LSIO version of latest Ombi on docker

**Comment by tobbenb** [comment]
This looks like an error caused by too many requests to the tvmaze api. Why it's crashing is hard to say. Probably better to report to the ombi devs.

**Comment by tidusjar** [comment]
It wouldn't stop it from starting up. 

When you say it fails to start, what do you mean?

**Comment by PrathikGopal** [comment]
@tidusjar the error doesn't get the UI to come up, the logs keep repeating the above error and doesnt let the UI to come up.

**Comment by tidusjar** [comment]
I think there is something else going on otherwise everyone including myself would have this issue

**Comment by PrathikGopal** [comment]
For now i have removed the container, it was causing excessive cpu usage. i will try moving it to a new stack this weekend.

**Comment by PrathikGopal** [comment]
This issue got self resolved, i had removed the container it for a while as it was not resolving, but i tried it today and it worked like a charm. thanks for your attention on the issue.
