### ISSUE TITLE
Requests fail against Sonarr v3 when series already exists

### ISSUE THREAD

**Issue by fudgedelic** [tidusjar/Ombi#2691]
#### Ombi build Version:

V 3.0.4036

#### Update Branch:

master

#### Media Sever:

Plex 

#### Media Server Version:

1.14.0.5470

#### Operating System:

Windows 10 Pro and Windows Server Datacenter 2019

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2018-12-15 13:44:45.309 -06:00 [Error] Exception thrown when attempting to send series over to Sonarr
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Ombi.Api.Sonarr.Models.SonarrSeries' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 77
   at Ombi.Api.Sonarr.SonarrApi.UpdateSeries(SonarrSeries updated, String apiKey, String baseUrl) in C:\projects\requestplex\src\Ombi.Api.Sonarr\SonarrApi.cs:line 89
   at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSeries result, SonarrSettings s) in C:\projects\requestplex\src\Ombi.Core\Senders\TvSender.cs:line 358
   at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model) in C:\projects\requestplex\src\Ombi.Core\Senders\TvSender.cs:line 261

Serialization exception occurs because SonarrApi is returning an error:

Invalid request Validation failed: 
 -- Language profile does not exist

Actual response object:

[
  {
    "propertyName": "LanguageProfileId",
    "errorMessage": "Language profile does not exist",
    "attemptedValue": 0,
    "formattedMessageArguments": [],
    "formattedMessagePlaceholderValues": {
      "propertyName": "Language Profile Id",
      "propertyValue": 0
    }
  }
]

Sonarr Log portion:

System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.DecisionEngine.Specifications.LanguageSpecification.IsSatisfiedBy(RemoteEpisode subject, SearchCriteriaBase searchCriteria) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\DecisionEngine\Specifications\LanguageSpecification.cs:line 0
   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker.EvaluateSpec(IDecisionEngineSpecification spec, RemoteEpisode remoteEpisode, SearchCriteriaBase searchCriteriaBase) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\DecisionEngine\DownloadDecisionMaker.cs:line 152
```

#### Problem Description:

Ombi will throw an exception when requesting an existing series against Sonarr v3.  This failed request also seems to cause Sonarr to throw NREs from the download decision maker - presumably from the now invalid Language Profile Id but I am less certain on this part.

#### Reproduction Steps:

Add a new series request for a single season or episode against a Sonarr v3 instance - this works.
Add another request/modify request to add additional seasons/episodes - this throws an exception.
Sonarr logs may start throwing NREs on the evaluation of the initial request from download decision maker.

I believe this may be as simple as just adding the new languageProfileId field to the SonarrSeries model.  For a new series the proper v3 check logic adds the field to the request and everything works.  When it is an existing series this field is not currently being returned in the GetSeries call in TvSender.cs and so it is being passed back as 0.  I pulled down the master branch to build and debug locally.  Testing this change against my v3 Sonarr instance resolved the issue I was encountering.  I'm uncertain if this would have implications against Sonarr v2 though.

**Comment by fudgedelic** [comment]
If you prefer I could do some regression testing against sonarr v2 and just submit a PR if everything checks out.

**Comment by tidusjar** [comment]
This has been fixed in the develop branch! 🎉 🎈

**Comment by fudgedelic** [comment]
Good deal, thanks for the patch!
