### ISSUE TITLE
No logs and email won't work

### ISSUE THREAD

**Issue by wredwards** [tidusjar/Ombi#2705]
#### Ombi build Version:

V 3.0.4036 

#### Update Branch:

whatever the default is

#### Media Sever:

Plex

#### Media Server Version:

Version 1.14.1.5488

#### Operating System:

Ubuntu - 18.04

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
● ombi.service - Ombi - PMS Requests System
   Loaded: loaded (/lib/systemd/system/ombi.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2018-12-28 06:40:54 CST; 1h 49min ago
 Main PID: 4142 (Ombi)
    Tasks: 32 (limit: 4915)
   CGroup: /system.slice/ombi.service
           └─4142 /opt/Ombi/Ombi --storage /etc/Ombi/

Dec 28 08:21:39 beast Ombi[4142]: warn: Ombi.Controllers.External.TesterController[0]
Dec 28 08:21:39 beast Ombi[4142]:       Exception when testing Email Notifications
Dec 28 08:21:39 beast Ombi[4142]: System.InvalidOperationException: The SMTP server has unexpectedly disconnected.
Dec 28 08:21:39 beast Ombi[4142]:    at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 94
Dec 28 08:21:39 beast Ombi[4142]:    at Ombi.Controllers.External.TesterController.Email(EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 225
Dec 28 08:29:19 beast Ombi[4142]: warn: Ombi.Controllers.External.TesterController[0]
Dec 28 08:29:19 beast Ombi[4142]:       Exception when testing Email Notifications
Dec 28 08:29:19 beast Ombi[4142]: System.InvalidOperationException: The SMTP server has unexpectedly disconnected.
Dec 28 08:29:19 beast Ombi[4142]:    at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 94
Dec 28 08:29:19 beast Ombi[4142]:    at Ombi.Controllers.External.TesterController.Email(EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 225




```

#### Problem Description:

Really have 2 issues at the moment - 1) no logs, no logs option on admin in Ombi
 2) not getting email test to work - using smtp.gmail.com:465
I've even tried to give Ombi a less secure app password

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Try port 587

**Comment by wredwards** [comment]
will search more - thanks
