### ISSUE TITLE
SQLite Error 5: 'database is locked' when trying to log in

### ISSUE THREAD

**Issue by norbertgaal** [tidusjar/Ombi#2716]
#### Ombi build Version:

3.0.4036-master

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

1.14.1.5488

#### Operating System:

Linux (Docker)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
2019-01-04 18:01:22.825 +00:00 [Error] Something bad happened, ErrorMiddleware caught this
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)
   at Microsoft.AspNetCore.Identity.UserManager`1.FindByNameAsync(String userName)
   at Ombi.Controllers.TokenController.OAuth(Int32 pinId) in C:\projects\requestplex\src\Ombi\Controllers\TokenController.cs:line 181
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 50
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24
2019-01-04 18:09:22.215 +00:00 [Error] Something bad happened, ErrorMiddleware caught this
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.Data.Sqlite.SqliteConnectionExtensions.ExecuteNonQuery(SqliteConnection connection, String commandText)
   at Microsoft.Data.Sqlite.SqliteTransaction.Commit()
   at Microsoft.EntityFrameworkCore.Storage.RelationalTransaction.Commit()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(DbContext _, ValueTuple`2 parameters, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IReadOnlyList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Ombi.Store.Repository.AuditRepository.Record(AuditType type, AuditArea area, String description, String user) in C:\projects\requestplex\src\Ombi.Store\Repository\AuditRepository.cs:line 36
   at Ombi.Store.Repository.AuditRepository.Record(AuditType type, AuditArea area, String description) in C:\projects\requestplex\src\Ombi.Store\Repository\AuditRepository.cs:line 22
   at Ombi.Controllers.TokenController.GetToken(UserAuthModel model) in C:\projects\requestplex\src\Ombi\Controllers\TokenController.cs:line 56
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 50
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24
```

#### Problem Description:

Getting SQLite Error 5: 'database is locked' every time when trying to log into Ombi, I have mentioned this on Discord but opening an issue as well so it won't get forgotten. 
Restarting the container doesn't resolve the issue. 

#### Reproduction Steps:

Trying to log in. (Doesn't matter if I am trying with Plex or local user, same result).

**Comment by tidusjar** [comment]
Is a different process potentially accessing/scanning the database?

**Comment by norbertgaal** [comment]
> 
> 
> Is a different process potentially accessing/scanning the database?

No. I just stopped the container and made sure  ```# lsof | grep -i ombi```  didn't show anything. After starting it clean I got the same error.

**Comment by tidusjar** [comment]
Please can you try latest develop

**Comment by norbertgaal** [comment]
Hi, thanks for the quick reply.

Unfortunately still getting the same error. Version Ombi 3.0.4103-develop

```
               Supported formats vary between servers.,
Ombi 3.0.4103-develop,
Hosting environment: Production,
Content root path: /opt/ombi,
   at Ombi.Controllers.TokenController.OAuth(Int32 pinId) in C:\projects\requestplex\src\Ombi\Controllers\TokenController.cs:line 194,
Now listening on: http://[::]:3579,
Application started. Press Ctrl+C to shut down.,
fail: Ombi.ErrorHandlingMiddleware[0],
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior),
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.,
      Something bad happened, ErrorMiddleware caught this,
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db),
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync(),
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments),
   at Microsoft.Data.Sqlite.SqliteConnectionExtensions.ExecuteNonQuery(SqliteConnection connection, String commandText),
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery(),
   at Microsoft.Data.Sqlite.SqliteTransaction.Commit(),
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(DbContext _, ValueTuple`2 parameters, CancellationToken cancellationToken),
   at Microsoft.EntityFrameworkCore.Storage.RelationalTransaction.Commit(),
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IReadOnlyList`1 entriesToSave, CancellationToken cancellationToken),
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken),
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken),
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`9.UpdateAsync(TUser user, CancellationToken cancellationToken),
   at Microsoft.AspNetCore.Identity.UserManager`1.UpdateUserAsync(TUser user),
   at Ombi.Controllers.TokenController.CreateToken(Boolean rememberMe, OmbiUser user) in C:\projects\requestplex\src\Ombi\Controllers\TokenController.cs:line 127,
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync(),
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync(),
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context),
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted),
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter(),
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context),
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted),
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync(),
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync(),
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext),
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context),
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext),
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext),
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 50,
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24,
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext(),
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken),
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken),
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken),
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken),
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken),
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken),
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType),
   at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\First.cs:line 144,
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\Select.cs:line 106,
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\AsyncIterator.cs:line 98,
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken),
   at Microsoft.AspNetCore.Identity.UserManager`1.FindByNameAsync(String userName),
   at Ombi.Controllers.TokenController.OAuth(Int32 pinId) in C:\projects\requestplex\src\Ombi\Controllers\TokenController.cs:line 181
```

**Comment by maran** [comment]
Just to add my voice here, I'm seeing this happening as well. Can't login.

**Comment by marclh** [comment]
Seeing this same issue as well

**Comment by ajkis** [comment]
Have same problem, Ombi keep crashing and restarting 
```
Jan 08 07:42:09 flix Ombi[12565]: info: Ombi.Schedule.Jobs.Ombi.RefreshMetadata[0]
Jan 08 07:42:09 flix Ombi[12565]:       The show 12 Rounds has TheMovieDbId but not ImdbId, searching for ImdbId
Jan 08 07:42:09 flix Ombi[12565]: Application startup exception: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.
Jan 08 07:42:09 flix Ombi[12565]:    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
Jan 08 07:42:09 flix Ombi[12565]:    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
Jan 08 07:42:09 flix Ombi[12565]:    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
Jan 08 07:42:09 flix Ombi[12565]:    at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
Jan 08 07:42:09 flix Ombi[12565]:    at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
Jan 08 07:42:09 flix Ombi[12565]:    at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlCommand(DatabaseFacade databaseFacade, RawSqlString sql, IEnumerable`1 parameters)
Jan 08 07:42:09 flix Ombi[12565]:    at Ombi.Store.Context.ExternalContext.Seed() in C:\projects\requestplex\src\Ombi.Store\Context\ExternalContext.cs:line 64
Jan 08 07:42:09 flix Ombi[12565]:    at Ombi.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IMemoryCache cache, IServiceProvider serviceProvider) in C:\projects\requestplex\src\Ombi\Startup.cs:line 215
Jan 08 07:42:09 flix Ombi[12565]: --- End of stack trace from previous location where exception was thrown ---
Jan 08 07:42:09 flix Ombi[12565]:    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
Jan 08 07:42:09 flix Ombi[12565]:    at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
Jan 08 07:42:09 flix Ombi[12565]: Unhandled Exception: Microsoft.Data.Sqlite.SqliteException: SQLite Error 5: 'database is locked'.
Jan 08 07:42:09 flix Ombi[12565]:    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
Jan 08 07:42:09 flix Ombi[12565]:    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
Jan 08 07:42:09 flix Ombi[12565]:    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
Jan 08 07:42:09 flix Ombi[12565]:    at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
Jan 08 07:42:09 flix Ombi[12565]:    at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
Jan 08 07:42:09 flix Ombi[12565]:    at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlCommand(DatabaseFacade databaseFacade, RawSqlString sql, IEnumerable`1 parameters)
Jan 08 07:42:09 flix Ombi[12565]:    at Ombi.Store.Context.ExternalContext.Seed() in C:\projects\requestplex\src\Ombi.Store\Context\ExternalContext.cs:line 64
Jan 08 07:42:09 flix Ombi[12565]:    at Ombi.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IMemoryCache cache, IServiceProvider serviceProvider) in C:\projects\requestplex\src\Ombi\Startup.cs:line 215
Jan 08 07:42:09 flix Ombi[12565]: --- End of stack trace from previous location where exception was thrown ---
Jan 08 07:42:09 flix Ombi[12565]:    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
Jan 08 07:42:09 flix Ombi[12565]:    at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
Jan 08 07:42:09 flix Ombi[12565]:    at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
Jan 08 07:42:09 flix Ombi[12565]:    at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
Jan 08 07:42:09 flix Ombi[12565]:    at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
Jan 08 07:42:09 flix Ombi[12565]:    at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
Jan 08 07:42:09 flix Ombi[12565]:    at Ombi.Program.Main(String[] args) in C:\projects\requestplex\src\Ombi\Program.cs:line 99
Jan 08 07:42:09 flix systemd[1]: ombi.service: Main process exited, code=dumped, status=6/ABRT
Jan 08 07:42:09 flix systemd[1]: ombi.service: Unit entered failed state.
Jan 08 07:42:09 flix systemd[1]: ombi.service: Failed with result 'core-dump'.
Jan 08 07:42:14 flix systemd[1]: ombi.service: Service hold-off time over, scheduling restart.
Jan 08 07:42:14 flix systemd[1]: Stopped Ombi - PMS Requests System.
Jan 08 07:42:14 flix systemd[1]: Started Ombi - PMS Requests System.
Jan 08 07:42:14 flix Ombi[12776]: Hello, welcome to Ombi
Jan 08 07:42:14 flix Ombi[12776]: Valid options are:
Jan 08 07:42:14 flix Ombi[12776]: Ombi 3.0.4036-master
Jan 08 07:42:14 flix Ombi[12776]: Copyright (C) 2019 Ombi
Jan 08 07:42:14 flix Ombi[12776]:   --host       (Default: http://*:5000) Set to a semicolon-separated (;) list
Jan 08 07:42:14 flix Ombi[12776]:                of URL prefixes to which the server should respond. For example,
Jan 08 07:42:14 flix Ombi[12776]:                http://localhost:123. Use "*" to indicate that the server should
Jan 08 07:42:14 flix Ombi[12776]:                listen for requests on any IP address or hostname using the
Jan 08 07:42:14 flix Ombi[12776]:                specified port and protocol (for example, http://*:5000). The
Jan 08 07:42:14 flix Ombi[12776]:                protocol (http:// or https://) must be included with each URL.
Jan 08 07:42:14 flix Ombi[12776]:                Supported formats vary between servers.
Jan 08 07:42:14 flix Ombi[12776]:   --storage    Storage path, where we save the logs and database
Jan 08 07:42:14 flix Ombi[12776]:   --baseurl    The base URL for reverse proxy scenarios
Jan 08 07:42:14 flix Ombi[12776]:   --help       Display this help screen.
Jan 08 07:42:14 flix Ombi[12776]:   --version    Display version information.
Jan 08 07:42:16 flix Ombi[12776]: We are running on
Jan 08 07:42:16 flix Ombi[12776]: /opt/Ombi
Jan 08 07:42:19 flix Ombi[12776]: info: Ombi.Schedule.Jobs.Ombi.RefreshMetadata[0]
Jan 08 07:42:19 flix Ombi[12776]:       Starting the Metadata refresh
Jan 08 07:42:20 flix Ombi[12776]: info: Ombi.Schedule.Jobs.Ombi.RefreshMetadata[0]
Jan 08 07:42:20 flix Ombi[12776]:       The media item Altitude does not have a ImdbId, searching for ImdbId
Jan 08 07:42:20 flix Ombi[12776]: info: Ombi.Schedule.Jobs.Ombi.RefreshMetadata[0]
Jan 08 07:42:20 flix Ombi[12776]:       The show Altitude has TheMovieDbId but not ImdbId, searching for ImdbId
Jan 08 07:42:20 flix Ombi[12776]: Hosting environment: Production
Jan 08 07:42:20 flix Ombi[12776]: Content root path: /opt/Ombi
Jan 08 07:42:20 flix Ombi[12776]: Now listening on: http://[::]:5000
Jan 08 07:42:20 flix Ombi[12776]: Application started. Press Ctrl+C to shut down.
Jan 08 07:42:20 flix Ombi[12776]: fail: Ombi.Api.Api[1000]
Jan 08 07:42:20 flix Ombi[12776]:       StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/tv/443700/external_ids?api_key=b8eabaf5608b88d0298aa189dd90bf00
Jan 08 07:42:20 flix Ombi[12776]: info: Ombi.Schedule.Jobs.Ombi.RefreshMetadata[0]
```
