### ISSUE TITLE
Ombi JSON error with radarr and sonarr

### ISSUE THREAD

**Issue by jaknoll** [tidusjar/Ombi#2720]
#### Ombi build Version:

V 3.0.4036
Radarr:  0.2.0.1217
Sonarr: 2.0.0.5252

#### Update Branch:

master

#### Media Sever:

Plex

#### Media Server Version:

N/A

#### Operating System:
Container/Linux

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
1/5/2019 10:01:40 PMNewtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Ombi.Api.Radarr.Models.RadarrAddMovieResponse' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
1/5/2019 10:01:40 PMTo fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
1/5/2019 10:01:40 PMPath '', line 1, position 1.
1/5/2019 10:01:40 PM   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)
1/5/2019 10:01:40 PM   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
1/5/2019 10:01:40 PM   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
1/5/2019 10:01:40 PM   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
1/5/2019 10:01:40 PM   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
1/5/2019 10:01:40 PM   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
1/5/2019 10:01:40 PM   at Ombi.Api.Radarr.RadarrApi.AddMovie(Int32 tmdbId, String title, Int32 year, Int32 qualityId, String rootPath, String apiKey, String baseUrl, Boolean searchNow, String minimumAvailability) in C:\projects\requestplex\src\Ombi.Api.Radarr\RadarrApi.cs:line 111
1/5/2019 10:01:40 PMfail: Ombi.Core.Senders.MovieSender[0]
1/5/2019 10:01:40 PM      Error when seing movie to DVR app, added to the request queue
1/5/2019 10:01:40 PMSystem.NullReferenceException: Object reference not set to an instance of an object.
1/5/2019 10:01:40 PM   at Ombi.Core.Senders.MovieSender.SendToRadarr(MovieRequests model, RadarrSettings settings) in C:\projects\requestplex\src\Ombi.Core\Senders\MovieSender.cs:line 161
1/5/2019 10:01:40 PM   at Ombi.Core.Senders.MovieSender.Send(MovieRequests model) in C:\projects\requestplex\src\Ombi.Core\Senders\MovieSender.cs:line 58
```
#### Problem Description:

Requested movies/TV shows result in an error like the above.

#### Reproduction Steps:

Request a movie, with Radarr or Sonarr configured for Movies or TV.

**Comment by tidusjar** [comment]
Are you sure your settings is correct? 

Can you go into the settings and upload a screenshot of the radarr or sonarr settings (Feel free to blank out your API Key)

**Comment by jaknoll** [comment]
I was able to resolve the issue by using the IP address directly.  When it wasn't working, it was passing through traefik as a reverse proxy (no url base) which was also redirecting http to https.  So not entirely sure which portion of that wasn't working.

I'd be happy to reconfigure traefik and capture logs/packets/etc if you'd like to try and debug
