### ISSUE TITLE
Radarr - Auto search feature not working

### ISSUE THREAD

**Issue by kiwijunglist** [tidusjar/Ombi#2723]
#### Ombi build Version:

V 3.0.XX

#### Update Branch:
Master

#### Media Sever: 

Radarr Version
0.2.0.1217
Mono Version
5.18.0.225 (tarball Wed Jan 2 21:25:21 UTC 2019)
AppData directory
/config
Startup directory
/opt/radarr

#### Operating System:

ubuntu server 18.04

#### Ombi Applicable Logs

(from `/logs/` directory or the Admin page):

```

2019-01-08 22:46:43.156 +13:00 [Information] Created User "admin"
2019-01-08 22:46:43.411 +13:00 [Information] Created the roles
2019-01-08 22:46:43.530 +13:00 [Information] Added the Admin role
2019-01-08 22:49:20.673 +13:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/217270?api_key=b8eabaf5608b88d0298aa189dd90bf00
2019-01-08 22:49:20.948 +13:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/217270?api_key=b8eabaf5608b88d0298aa189dd90bf00 Because we got Status Code: TooManyRequests
2019-01-08 22:49:21.188 +13:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/search/movie?api_key=b8eabaf5608b88d0298aa189dd90bf00&query=unforgiven
2019-01-08 22:49:21.411 +13:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/search/movie?api_key=b8eabaf5608b88d0298aa189dd90bf00&query=unforgiven Because we got Status Code: TooManyRequests
2019-01-08 22:50:54.609 +13:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/449772?api_key=b8eabaf5608b88d0298aa189dd90bf00
2019-01-08 22:50:54.694 +13:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/515888?api_key=b8eabaf5608b88d0298aa189dd90bf00
2019-01-08 22:50:54.830 +13:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/449772?api_key=b8eabaf5608b88d0298aa189dd90bf00 Because we got Status Code: TooManyRequests
2019-01-08 22:50:54.914 +13:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/515888?api_key=b8eabaf5608b88d0298aa189dd90bf00 Because we got Status Code: TooManyRequests
2019-01-08 22:50:55.448 +13:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/search/movie?api_key=b8eabaf5608b88d0298aa189dd90bf00&query=SCAREY
2019-01-08 22:50:55.669 +13:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/search/movie?api_key=b8eabaf5608b88d0298aa189dd90bf00&query=SCAREY Because we got Status Code: TooManyRequests
2019-01-08 22:50:59.333 +13:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/search/movie?api_key=b8eabaf5608b88d0298aa189dd90bf00&query=SCAREY MOVIE
2019-01-08 22:50:59.554 +13:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/search/movie?api_key=b8eabaf5608b88d0298aa189dd90bf00&query=SCAREY MOVIE Because we got Status Code: TooManyRequests
2019-01-08 22:51:54.090 +13:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/4260?api_key=b8eabaf5608b88d0298aa189dd90bf00
2019-01-08 22:51:54.129 +13:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/141159?api_key=b8eabaf5608b88d0298aa189dd90bf00
2019-01-08 22:51:54.313 +13:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/4260?api_key=b8eabaf5608b88d0298aa189dd90bf00 Because we got Status Code: TooManyRequests
2019-01-08 22:51:54.348 +13:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/141159?api_key=b8eabaf5608b88d0298aa189dd90bf00 Because we got Status Code: TooManyRequests
2019-01-08 22:53:20.848 +13:00 [Error] Something bad happened, ErrorMiddleware caught this
System.ArgumentNullException: Value cannot be null.
Parameter name: entity
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
   at Microsoft.EntityFrameworkCore.DbContext.Remove[TEntity](TEntity entity)
   at Ombi.Store.Repository.BaseRepository`2.Delete(T request) in C:\projects\requestplex\src\Ombi.Store\Repository\BaseRepository.cs:line 57
   at Ombi.Core.Engine.MovieRequestEngine.RemoveMovieRequest(Int32 requestId) in C:\projects\requestplex\src\Ombi.Core\Engine\MovieRequestEngine.cs:line 416
   at Ombi.Controllers.RequestController.DeleteRequest(Int32 requestId) in C:\projects\requestplex\src\Ombi\Controllers\RequestController.cs:line 117
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 50
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24
2019-01-08 22:54:48.167 +13:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/501954?api_key=b8eabaf5608b88d0298aa189dd90bf00
2019-01-08 22:54:48.388 +13:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/501954?api_key=b8eabaf5608b88d0298aa189dd90bf00 Because we got Status Code: TooManyRequests
2019-01-08 22:54:55.554 +13:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/4248?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates
2019-01-08 23:03:48.121 +13:00 [Error] Something bad happened, ErrorMiddleware caught this
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Controllers.External.PlexController.GetFriends() in C:\projects\requestplex\src\Ombi\Controllers\External\PlexController.cs:line 257
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 50
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24
2019-01-08 23:05:01.011 +13:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/260132?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates
2019-01-08 23:05:01.240 +13:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/260132?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates Because we got Status Code: TooManyRequests
2019-01-08 23:05:01.298 +13:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/281351?api_key=b8eabaf5608b88d0298aa189dd90bf00
2019-01-08 23:05:01.306 +13:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/146012?api_key=b8eabaf5608b88d0298aa189dd90bf00
2019-01-08 23:05:01.319 +13:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/301790?api_key=b8eabaf5608b88d0298aa189dd90bf00
2019-01-08 23:05:01.530 +13:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/281351?api_key=b8eabaf5608b88d0298aa189dd90bf00 Because we got Status Code: TooManyRequests
2019-01-08 23:05:01.551 +13:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/301790?api_key=b8eabaf5608b88d0298aa189dd90bf00 Because we got Status Code: TooManyRequests
2019-01-08 23:05:01.552 +13:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/146012?api_key=b8eabaf5608b88d0298aa189dd90bf00 Because we got Status Code: TooManyRequests
2019-01-08 23:05:02.422 +13:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/search/movie?api_key=b8eabaf5608b88d0298aa189dd90bf00&query=scary
2019-01-08 23:05:02.645 +13:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/search/movie?api_key=b8eabaf5608b88d0298aa189dd90bf00&query=scary Because we got Status Code: TooManyRequests
2019-01-08 23:05:04.208 +13:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/search/movie?api_key=b8eabaf5608b88d0298aa189dd90bf00&query=scary m
2019-01-08 23:05:04.434 +13:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/search/movie?api_key=b8eabaf5608b88d0298aa189dd90bf00&query=scary m Because we got Status Code: TooManyRequests
2019-01-08 23:05:14.146 +13:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/48567?api_key=b8eabaf5608b88d0298aa189dd90bf00
2019-01-08 23:05:14.158 +13:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/4258?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates
2019-01-08 23:05:14.226 +13:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/131916?api_key=b8eabaf5608b88d0298aa189dd90bf00
2019-01-08 23:05:14.282 +13:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/501954?api_key=b8eabaf5608b88d0298aa189dd90bf00
2019-01-08 23:05:14.366 +13:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/48567?api_key=b8eabaf5608b88d0298aa189dd90bf00 Because we got Status Code: TooManyRequests
2019-01-08 23:05:14.400 +13:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/4258?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates Because we got Status Code: TooManyRequests
2019-01-08 23:05:14.420 +13:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/4242?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates
2019-01-08 23:05:14.450 +13:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/131916?api_key=b8eabaf5608b88d0298aa189dd90bf00 Because we got Status Code: TooManyRequests
2019-01-08 23:05:14.551 +13:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/501954?api_key=b8eabaf5608b88d0298aa189dd90bf00 Because we got Status Code: TooManyRequests
2019-01-08 23:05:14.644 +13:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/4242?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates Because we got Status Code: TooManyRequests
2019-01-08 23:05:14.896 +13:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/4247?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates
2019-01-08 23:05:15.122 +13:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/4247?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates Because we got Status Code: TooManyRequests


```

#### Problem Description:

Movies: Radarr, options
Enabled: tick box checked
Radarr tests connectivity = ok
quality profile : 1080p
root folder: /movies/
Min Avail: announced
Do not search : tick box not checked

Click request.
Request populates in radarr under movies : wanted.
However the download doesn't start, ie the search is not triggered

If i manually trigger a search in radar the movie starts downloading but it is not automatically happening.

#### Reproduction Steps:

1. request movie
2. see movie in radarr under monitored / wanted
3. movie doesn't download

**Comment by tidusjar** [comment]
Cannot seem to reproduce this.

**Comment by kiwijunglist** [comment]
I'll try make a separate docker with fresh  radarr and fresh ombi and try to reproduce with logs again then. Thank you. I'll be back :)

**Comment by goldenpipes** [comment]
are you using IP or localhost for radarr connection?

IIRC there is some issue with docker and localhost.

**Comment by kiwijunglist** [comment]
IP address. I'll post my docker compose files with my follow up testing.

**Comment by kiwijunglist** [comment]
yup found it one of the advanced options under setting -> media management is causing the issue.  I'll try figure out which option it is....

**Comment by kiwijunglist** [comment]
Steps to reproduce the issue:

**### Media management advanced settings:**

Rename movies: Yes

Replace illegal characters: Yes

Colon replace format: [Delete]

Standard Movie Format: 
{Movie Title} ({Release Year}) - {[EDITION TAGS]}{[QUALITY FULL]}{[MEDIAINFO AUDIOCODEC}{ MEDIAINFO AUDIOCHANNELS]}{[MEDIAINFO VIDEOCODEC]}{-RELEASE GROUP}

Movie Folder Format:
{Movie Title} ({Release Year}) - {IMDb Id}

Create empty movie folders: Yes

Automatically Rename Folders: Yes

**Movie Paths Default to Static: No** 

Request movie in ombi , movie will add to wanted list, but will not start automatically downloading in your client.  Change Movie Paths Default to Static = Yes, try again, and it will now work.

**Comment by tidusjar** [comment]
What does that option actually do?

**Comment by kiwijunglist** [comment]
well according to my search you can have static or dynamic paths.
eg.

Movie Folder Format: {Movie TitleThe} ({Release Year}) {Quality Full}

This folder or path is dynamic and will change in a monitored movie when it re-downloads a higher quality.

**Comment by kiwijunglist** [comment]
if you can't reproduce this issue it might be that you have to enable all the options in the screenshot above.

**Comment by tidusjar** [comment]
And adding a movie in radarr and searching (the add and search option)
works fine?

**Comment by kiwijunglist** [comment]
yes i can trigger a download via a manual search at any time regardless of the settings.
and if i change static = yes, then save, then the ombi auto request search works as well.

**Comment by kiwijunglist** [comment]
for my personal situation, I'm just gonna have static = yes, and everything is going to work fine for me moving forward, however others may encounter this issue / bug hence the report.

**Comment by d1slact0r** [comment]
Wait what I have had this issue too a couple of times. Only with Radarr (sonarr does a search). How did you fix this? just toggle it off, save and than toggle it on again ?

**Comment by kiwijunglist** [comment]
Just had to use static path = yes
Or if you need to use static path = no then you have to use the default format for renaming the folder

**Comment by d1slact0r** [comment]
So if you enable it this issue is fixed?

**Comment by kiwijunglist** [comment]
It's still an issue in that I can't use dynamic paths. But I prefer auto search in Omni working Vs dynamic paths

**Comment by d1slact0r** [comment]
That is not really an awnser to my question...

**Comment by kiwijunglist** [comment]
The answer is no

**Comment by kiwijunglist** [comment]
Yes the problem is not a problem with Omni, I've raised this with radarr in their discord. I can't remember if I have made an issue. I think this can be closed on the ombi side though as it's not an ombi fault (probably).
