### ISSUE TITLE
newsletter not working, linux

### ISSUE THREAD

**Issue by amanalar** [tidusjar/Ombi#2739]
Ombi build Version:
v3.0.4119/linux-arm64.tar.gz
(The easy Way)

Update Branch:
Master

Media Sever:
Plex

Media Server Version:
Version 1.14.1.5488 

Operating System:
ubuntu-18.04.1.0

Ombi Applicable Logs (from /logs/ directory or the Admin page):

Problem Description:
Newsletter not working, no idea how to troubleshoot

Reproduction Steps:
smtp set up with gmail. test emails working ok. user forgot password email working.
updated database, test user with admin role and receives newsletter role. 
added new content from request. went for lunch ombi reports content available. 

From some initial searching is the linux ombi different. some of the screenshots i've dont look like what i have.

**Comment by tidusjar** [comment]
So the newsletter triggers on a set schedule. Every Friday IIRC. You can change this in the jobs setting page. You can also press trigger now to trigger the newsletter.

**Comment by tidusjar** [comment]
What's in your log file when this happens?

**Comment by amanalar** [comment]
Can you point me to where logs are located? I assumed they would be in /opt/Ombi but i see nothing, or is it in the webinterface somewhere?

**Comment by amanalar** [comment]
I wish that were the case. The only folders in /opt/Ombi are:
cypress
es
Templates
updater
wwwroot
zh
zh-TW

I'm beginning to think installing the easy way was actually the and I should have just used the less easy way :(

![ombi](https://user-images.githubusercontent.com/80619/51570031-0292ff00-1e6c-11e9-9b49-00a2dba3ce3e.jpg)

**Comment by amanalar** [comment]
well never assume anything. after running "dpkg -L ombi" I can see logs are actually in /etc/Ombi/Logs. I did trigger a newsletter to run now as well as tried the test option. Log isn't updating with those. Log file is there and I see a few of these:
2019-01-22 10:03:00.809 -05:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://plex.tv/users/sign_in.json
2019-01-22 10:03:17.836 -05:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/9395?api_key=b8ea...

but nothing to indicate that a newsletter job was initiated. Also I remembered you said it will automatically trigger a newsletter every friday. Well fridays logs were actually empty. 

I'm going to uninstall Ombi and install the hardway. I'll report back

**Comment by amanalar** [comment]
This is the only thing i see in a logfile:

Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Gene$
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. no$
Path 'error', line 2, position 10.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProp$
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 77
   at Ombi.Api.Sonarr.SonarrApi.GetRootFolders(String apiKey, String baseUrl) in C:\projects\requestplex\src\Ombi.Api.Sonarr\SonarrApi.cs:line 33
   at Ombi.Controllers.External.SonarrController.GetRootFolders() in C:\projects\requestplex\src\Ombi\Controllers\External\SonarrController.cs:li$
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodEx$
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 50
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24

**Comment by amanalar** [comment]
Felt like revisiting after the numerous updates to Ombi to see if the newsletter works on linux. I do actually see something of value here.

> 
2019-10-12 20:26:22.610 -04:00 [Debug] Calling Execute on job System.INewsletterJob
2019-10-12 20:26:22.613 -04:00 [Debug] Trigger instruction : DeleteTrigger
2019-10-12 20:26:22.613 -04:00 [Debug] Deleting trigger 
> 

The newsletter is still not being sent however. 

The email is working,


 
--
This is just a test! Success!

any ideas with that info in logfile?

**Comment by tidusjar** [comment]
Very strange, are items being marked as available in Ombi automatically? Are using receiving the availability notification?

**Comment by amanalar** [comment]
Yes to both of those. Do you have any idea on the errors I posted. 

I decided to look in /var/log/syslog and there are more here, thought could be unrelated.

`Nov 16 08:30:00 SERVER Ombi[1535]: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: x.RequestId'.
Nov 16 08:30:00 SERVER Ombi[1535]:    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
Nov 16 08:30:00 SERVER Ombi[1535]:    at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
Nov 16 08:30:00 SERVER Ombi[1535]:    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
Nov 16 08:30:00 SERVER Ombi[1535]:    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
Nov 16 08:30:00 SERVER Ombi[1535]:    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
Nov 16 08:30:00 SERVER Ombi[1535]:    at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
Nov 16 08:30:00 SERVER Ombi[1535]:    at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
Nov 16 08:30:00 SERVER Ombi[1535]:    at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
Nov 16 08:30:00 SERVER Ombi[1535]:    at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.AsyncSelectEnumerable`2.AsyncSelectEnumerator.MoveNext(CancellationToken cancellationToken)
Nov 16 08:30:00 SERVER Ombi[1535]:    at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\First.cs:line 144
Nov 16 08:30:00 SERVER Ombi[1535]:    at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
Nov 16 08:30:00 SERVER Ombi[1535]:    at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\Select.cs:line 106
Nov 16 08:30:00 SERVER Ombi[1535]:    at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\AsyncIterator.cs:line 98
Nov 16 08:30:00 SERVER Ombi[1535]:    at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
Nov 16 08:30:00 SERVER Ombi[1535]:    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)
Nov 16 08:30:00 SERVER Ombi[1535]:    at Ombi.Store.Repository.PlexServerContentRepository.GetFirstContentByCustom(Expression`1 predicate) in C:\projects\requestplex\src\Ombi.Store\Repository\PlexContentRepository.cs:line 90
Nov 16 08:30:00 SERVER Ombi[1535]:    at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessServer(PlexServers servers, Boolean recentlyAddedSearch) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 246
Nov 16 08:30:00 SERVER Ombi[1535]: #033[41m#033[30mfail#033[39m#033[22m#033[49m: Ombi.Schedule.Jobs.Plex.PlexContentSync[2008]
Nov 16 08:30:00 SERVER Ombi[1535]:       Exception when adding new Movie Operation Condor`

**Comment by tidusjar** [comment]
Run build 4887

**Comment by amanalar** [comment]
This is how my setup looks right now
`

Version | 3.0.4892
-- | --
Branch | master
Github | https://github.com/tidusjar/Ombi
Discord | https://discord.gg/Sa7wNWb
Reddit | https://www.reddit.com/r/Ombi/
Issues | https://github.com/tidusjar/Ombi/issues
Wiki | https://github.com/tidusjar/Ombi/wiki
OS Architecture | X64
OS Description | Linux 4.15.0-70-generic #79-Ubuntu SMP Tue Nov 12 10:36:11 UTC 2019
Process Architecture | X64
Application Base Path | /opt/Ombi
Storage Path | /etc/Ombi/
Ombi Database | Sqlite - Data Source=/etc/Ombi/Ombi.db
External Database | Sqlite - Data Source=/etc/Ombi/OmbiExternal.db
Settings Database | Sqlite - Data Source=/etc/Ombi/OmbiSettings.db

`

**Comment by sblees** [comment]
I'm running into the same problem... Newsletter runs if manually triggered, but does not run automatically.  I noticed this started more a month or so ago.  The last time mine automatically triggered was on **Sept 20, 2019**. I'm not sure what version I was on back then.

Below are the logs from this past Friday when it tried to execute:
`2019-11-29 12:00:00.002 -05:00 [Debug] Calling Execute on job System.INewsletterJob
2019-11-29 12:00:00.005 -05:00 [Information] Starting Plex Content Cacher Recently Added Scan
2019-11-29 12:00:00.005 -05:00 [Information] Starting to cache the content on server "***** Server"
2019-11-29 12:00:00.483 -05:00 [Information] Plex Movies to send: 20
2019-11-29 12:00:00.505 -05:00 [Information] Emby Movies to send: 0
2019-11-29 12:00:00.505 -05:00 [Information] Albums to send: 0
2019-11-29 12:00:20.726 -05:00 [Information] Default Quartz.NET properties loaded from embedded resource file
2019-11-29 12:00:20.842 -05:00 [Debug] TaskSchedulingThreadPool configured with max concurrency of 10 and TaskScheduler ThreadPoolTaskScheduler.
2019-11-29 12:00:20.891 -05:00 [Information] Initialized Scheduler Signaller of type: Quartz.Core.SchedulerSignalerImpl
2019-11-29 12:00:20.894 -05:00 [Information] Quartz Scheduler v."3.0.7.0" created.
2019-11-29 12:00:20.899 -05:00 [Information] RAMJobStore initialized.
2019-11-29 12:00:20.908 -05:00 [Information] Scheduler meta-data: Quartz Scheduler (v3.0.7.0) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'Quartz.Core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'Quartz.Simpl.DefaultThreadPool' - with 10 threads.
  Using job-store 'Quartz.Simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2019-11-29 12:00:20.908 -05:00 [Information] Quartz scheduler 'DefaultQuartzScheduler' initialized
2019-11-29 12:00:20.909 -05:00 [Information] Quartz scheduler version: 3.0.7.0
2019-11-29 12:00:20.911 -05:00 [Information] JobFactory set to: Ombi.Schedule.IoCJobFactory
2019-11-29 12:00:21.065 -05:00 [Information] Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
2019-11-29 12:00:21.077 -05:00 [Debug] Batch acquisition of 0 triggers`

I'm running my instance (version 3.0.4892) in an x64 Linux 4.19.41-Unraid #1 SMP docker container.

**Comment by ROODAY** [comment]
Just wanted to bump this as I'm having the same issue, the newsletter works when manually run but not automatically. Running Ombi version 4.0.1131 installed through apt if that helps (Ubuntu 20.04.2 LTS). Would having Requestrr installed as well cause issues if it makes Ombi think that movies have already been announced to people?
