### ISSUE TITLE
Error thrown when attempting to obtain the plex libs

### ISSUE THREAD

**Issue by horrorshow21** [tidusjar/Ombi#2749]
**Describe the bug**
Unable to load Libraries for Plex Media Server. Server info is auto populated after submitting credentials and selecting Plex Server. 

**To Reproduce**
1. Go to 'Settings>Media Server>Plex'
2. Click on 'Load Libraries'
3. Nothing happens

**Expected behavior**
To be presented with a list of Plex libraries.

**Screenshots**

**Logs (Logs directory where Ombi is located)**
```
2019-01-21 12:05:41.368 -05:00 [Warning] Error thrown when attempting to obtain the plex libs
System.OperationCanceledException: The operation was canceled.
   at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request) in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
   at Ombi.Api.Plex.PlexApi.GetLibrarySections(String authToken, String plexFullHost) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 120
   at Ombi.Controllers.External.PlexController.GetPlexLibraries(PlexServers settings) in C:\projects\requestplex\src\Ombi\Controllers\External\PlexController.cs:line 109
2019-01-21 12:05:42.792 -05:00 [Error] Could not test Plex
System.OperationCanceledException: The operation was canceled.
   at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request) in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
   at Ombi.Api.Plex.PlexApi.GetStatus(String authToken, String uri) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 97
   at Ombi.Controllers.External.TesterController.Plex(PlexServers settings) in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 246
```

**Desktop (please complete the following information):**
 - OS: Docker (linuxserver/ombi)

**Ombi Version (please complete the following information):**
 - Version 3.0.4119
- Media Server Plex

**Additional context**

**Comment by horrorshow21** [comment]
Restarted Ombi container. Error has changed slightly.

```
2019-01-21 12:57:43.454 -05:00 [Warning] Error thrown when attempting to obtain the plex libs
System.ObjectDisposedException: Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'SettingsContext'.
   at Microsoft.EntityFrameworkCore.DbContext.CheckDisposed()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Internal.IDbContextDependencies.get_QueryProvider()
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor..ctor(IEvaluatableExpressionFilter evaluatableExpressionFilter, IParameterValues parameterValues, IDiagnosticsLogger`1 logger, DbContext context, Boolean parameterize, Boolean generateContextAccessors)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryModelGenerator.ExtractParameters(IDiagnosticsLogger`1 logger, Expression query, IParameterValues parameterValues, Boolean parameterize, Boolean generateContextAccessors)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, LambdaExpression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, Expression`1 predicate, CancellationToken cancellationToken)
   at Ombi.Store.Repository.SettingsJsonRepository.GetAsync(String settingsName)
   at Ombi.Settings.Settings.SettingsService`1.<GetSettingsAsync>b__11_0() in C:\projects\requestplex\src\Ombi.Settings\Settings\SettingsService.cs:line 51
   at Ombi.Helpers.CacheService.GetOrAdd[T](String cacheKey, Func`1 factory, DateTime absoluteExpiration)
   at Ombi.Settings.Settings.SettingsService`1.GetSettingsAsync()
   at Ombi.Api.OmbiHttpClient.<GetHandler>b__8_0() in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 86
   at Ombi.Helpers.CacheService.GetOrAdd[T](String cacheKey, Func`1 factory, DateTime absoluteExpiration)
   at Ombi.Api.OmbiHttpClient.GetHandler() in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 86
   at Ombi.Api.OmbiHttpClient.Setup() in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 77
   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request) in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
   at Ombi.Api.Plex.PlexApi.GetLibrarySections(String authToken, String plexFullHost) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 120
   at Ombi.Controllers.External.PlexController.GetPlexLibraries(PlexServers settings) in C:\projects\requestplex\src\Ombi\Controllers\External\PlexController.cs:line 109
2019-01-21 12:57:50.171 -05:00 [Error] Could not test Plex
System.ObjectDisposedException: Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'SettingsContext'.
   at Microsoft.EntityFrameworkCore.DbContext.CheckDisposed()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Internal.IDbContextDependencies.get_QueryProvider()
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor..ctor(IEvaluatableExpressionFilter evaluatableExpressionFilter, IParameterValues parameterValues, IDiagnosticsLogger`1 logger, DbContext context, Boolean parameterize, Boolean generateContextAccessors)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryModelGenerator.ExtractParameters(IDiagnosticsLogger`1 logger, Expression query, IParameterValues parameterValues, Boolean parameterize, Boolean generateContextAccessors)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, LambdaExpression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, Expression`1 predicate, CancellationToken cancellationToken)
   at Ombi.Store.Repository.SettingsJsonRepository.GetAsync(String settingsName)
   at Ombi.Settings.Settings.SettingsService`1.<GetSettingsAsync>b__11_0() in C:\projects\requestplex\src\Ombi.Settings\Settings\SettingsService.cs:line 51
   at Ombi.Helpers.CacheService.GetOrAdd[T](String cacheKey, Func`1 factory, DateTime absoluteExpiration)
   at Ombi.Settings.Settings.SettingsService`1.GetSettingsAsync()
   at Ombi.Api.OmbiHttpClient.<GetHandler>b__8_0() in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 86
   at Ombi.Helpers.CacheService.GetOrAdd[T](String cacheKey, Func`1 factory, DateTime absoluteExpiration)
   at Ombi.Api.OmbiHttpClient.GetHandler() in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 86
   at Ombi.Api.OmbiHttpClient.Setup() in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 77
   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request) in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
   at Ombi.Api.Plex.PlexApi.GetStatus(String authToken, String uri) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 97
   at Ombi.Controllers.External.TesterController.Plex(PlexServers settings) in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 246
```

**Comment by tidusjar** [comment]
Have you entered in all the correct information for Plex? E.g. hostname port?

**Comment by horrorshow21** [comment]
It auto-populated the fields below after i put my Plex username and password in and selected my Plex server. I assume it filled it with the correct info, verified IP and port.

Server name
Hostname or IP
Port
Plex Authorization Token
Machine Identifier

**Comment by tidusjar** [comment]
That information is provided from plex.tv 

Please double check it, for me it returns my internal ips and not external.

**Comment by horrorshow21** [comment]
It does return my internal IP 192.186.86.*

**Comment by tidusjar** [comment]
And can ombi container can communicate with that IP?

**Comment by horrorshow21** [comment]
I figured it out. Your internal vs external IP comment gave me the clue. Though it was using my internal IP it was populating the external port. Changed to the proper port and the libraries came up.
