### ISSUE TITLE
Slack Notifications aren't working

### ISSUE THREAD

**Issue by kingwoftam** [tidusjar/Ombi#2752]
**Describe the bug**
I've configured Ombi to use a Slack Webhook for notifications for requests made. This has been configured and successfully tested, multiple times. However even though multiple requests have been made, not a single notification is received.

**To Reproduce**
1. Configure Slack Notifications in Settings, ensuring it's enabled and New Requests are enabled
2. Successfully test to confirm messages can appear in Slack from Ombi
3. User requests a movie

**Expected behavior**
A slack notification is received in the

**Screenshots**

**Logs (Logs directory where Ombi is located)**
Unsure if relevant but I have these errors a handful of times a day:
2019-01-21 00:00:13.761 +13:00 [Error] Something bad happened, ErrorMiddleware caught this
System.Threading.Tasks.TaskCanceledException: The operation was canceled. ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled. ---> System.Net.Sockets.SocketException: Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request) in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
   at Ombi.Api.Radarr.RadarrApi.GetRootFolders(String apiKey, String baseUrl) in C:\projects\requestplex\src\Ombi.Api.Radarr\RadarrApi.cs:line 36
   at Ombi.Controllers.External.RadarrController.<GetRootFolders>b__13_0() in C:\projects\requestplex\src\Ombi\Controllers\External\RadarrController.cs:line 88
   at Ombi.Helpers.CacheService.GetOrAdd[T](String cacheKey, Func`1 factory, DateTime absoluteExpiration)
   at Ombi.Controllers.External.RadarrController.GetRootFolders() in C:\projects\requestplex\src\Ombi\Controllers\External\RadarrController.cs:line 83
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 50
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24

**Desktop (please complete the following information):**
 - OS: OSX

**Ombi Version (please complete the following information):**
 - Version: 3.0.4119 [master]
 - Media Server: Plex

**Comment by tidusjar** [comment]
Those logs you provided are to do with Radarr and not Slack?

**Comment by mindtripper** [comment]
@tidusjar is Slack notofication working for you?
It's not for me. Except the Test button in Slack notification that shows "This is a test from Ombi, if you can see this then we have successfully pushed a notification!" in my Slack channel. There are no other notifications. And yes, I have enabled it :)

I'd like to troubleshoot this further. What logs should I look at? I'm using the official Docker image.

Thanks in advance.

**Comment by tidusjar** [comment]
Closing due to no reply.
