### ISSUE TITLE
System.InvalidOperationException: The AuthorizationPolicy named: 'EditCustomPage' was not found.

### ISSUE THREAD

**Issue by tyxak** [tidusjar/Ombi#2759]
First of all, thanks for the great application and your effort. However, today I had my first application crash. It all started @ 18.04.31. Probably during auto update, as you can see in my logs.

```
Jan 23 18:04:31 tvinas01 systemd[1]: Stopping Ombi - PMS Requests System...
Jan 23 18:04:31 tvinas01 Ombi[26557]: Application is shutting down...
Jan 23 18:04:32 tvinas01 systemd[1]: Stopped Ombi - PMS Requests System.
Jan 23 18:04:40 tvinas01 systemd[1]: Started Ombi - PMS Requests System.
Jan 23 18:04:41 tvinas01 Ombi[31872]: Hello, welcome to Ombi
Jan 23 18:04:41 tvinas01 Ombi[31872]: Valid options are:
Jan 23 18:04:41 tvinas01 Ombi[31872]: Ombi 3.0.4161-develop
Jan 23 18:04:41 tvinas01 Ombi[31872]: Copyright (C) 2019 Ombi
Jan 23 18:04:43 tvinas01 Ombi[31872]: We are running on
Jan 23 18:04:43 tvinas01 Ombi[31872]: /opt/Ombi
Jan 23 18:04:48 tvinas01 Ombi[31872]: Hosting environment: Production
Jan 23 18:04:48 tvinas01 Ombi[31872]: Content root path: /opt/Ombi
Jan 23 18:04:48 tvinas01 Ombi[31872]: Now listening on: http://[::]:5000
Jan 23 18:04:48 tvinas01 Ombi[31872]: Application started. Press Ctrl+C to shut down.
Jan 23 18:07:01 tvinas01 Ombi[31872]: #033[41m#033[30mfail#033[39m#033[22m#033[49m: Ombi.ErrorHandlingMiddleware[0]
Jan 23 18:07:01 tvinas01 Ombi[31872]:       Something bad happened, ErrorMiddleware caught this
Jan 23 18:07:01 tvinas01 Ombi[31872]: System.InvalidOperationException: The AuthorizationPolicy named: 'EditCustomPage' was not found.
Jan 23 18:07:01 tvinas01 Ombi[31872]:    at Microsoft.AspNetCore.Authorization.AuthorizationPolicy.CombineAsync(IAuthorizationPolicyProvider policyProvider, IEnumerable`1 authorizeData)
Jan 23 18:07:01 tvinas01 Ombi[31872]:    at Microsoft.AspNetCore.Mvc.Internal.AuthorizationApplicationModelProvider.GetFilter(IAuthorizationPolicyProvider policyProvider, IEnumerable`1 authData)
Jan 23 18:07:01 tvinas01 Ombi[31872]:    at Microsoft.AspNetCore.Mvc.Internal.AuthorizationApplicationModelProvider.OnProvidersExecuting(ApplicationModelProviderContext context)
Jan 23 18:07:01 tvinas01 Ombi[31872]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.BuildModel()
Jan 23 18:07:01 tvinas01 Ombi[31872]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetDescriptors()
Jan 23 18:07:01 tvinas01 Ombi[31872]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
Jan 23 18:07:01 tvinas01 Ombi[31872]:    at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.UpdateCollection()
Jan 23 18:07:01 tvinas01 Ombi[31872]:    at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.Initialize()
Jan 23 18:07:01 tvinas01 Ombi[31872]:    at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.get_ActionDescriptors()
Jan 23 18:07:01 tvinas01 Ombi[31872]:    at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.GetTreeRouter()
Jan 23 18:07:01 tvinas01 Ombi[31872]:    at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.RouteAsync(RouteContext context)
Jan 23 18:07:01 tvinas01 Ombi[31872]:    at Microsoft.AspNetCore.Routing.RouteCollection.RouteAsync(RouteContext context)
Jan 23 18:07:01 tvinas01 Ombi[31872]:    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Jan 23 18:07:01 tvinas01 Ombi[31872]:    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Jan 23 18:07:01 tvinas01 Ombi[31872]:    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
Jan 23 18:07:01 tvinas01 Ombi[31872]:    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
Jan 23 18:07:01 tvinas01 Ombi[31872]:    at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 55
Jan 23 18:07:01 tvinas01 Ombi[31872]:    at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24
Jan 23 18:07:50 tvinas01 Ombi[31872]: #033[41m#033[30mfail#033[39m#033[22m#033[49m: Ombi.ErrorHandlingMiddleware[0]

```
I'm not familiar with AuthorizationPolicy, so I wonder if one of you could give me a clue how to fix this.

**Comment by tyxak** [comment]
Page is totally down atm with the following JSON:

"The AuthorizationPolicy named: 'EditCustomPage' was not found."

**Comment by tidusjar** [comment]
This has been fixed in the develop branch! 🎉 🎈
