### ISSUE TITLE
Movies / TV Shows will not process - fail with "Object reference not set to an instance of an object "

### ISSUE THREAD

**Issue by locatorr** [tidusjar/Ombi#2761]
**Describe the bug**
When a user requests a movie or TV show, it immediately fails and with an error "Object reference not set to an instance of an object." under Failed Requests.

I have ensured API keys are correct for Radarr, Sonarr, and Plex as well as testing the connection within Ombi settings (all successful). 

I recently set up a reverse proxy using NGINX, about a week ago. Requests seemed to be working post-reverse-proxy setup. 

Radarr / Sonarr logs show nothing.

**To Reproduce**
Request any movie or TV show on or off my home network

**Screenshots**

http://prntscr.com/mbbpob

**Logs (Logs directory where Ombi is located)**
It's 531,000 lines long for some reason, but this seems to be the most relevant: 

```
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Ombi.Api.Radarr.Models.RadarrAddMovieResponse' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Radarr.RadarrApi.AddMovie(Int32 tmdbId, String title, Int32 year, Int32 qualityId, String rootPath, String apiKey, String baseUrl, Boolean searchNow, String minimumAvailability) in C:\projects\requestplex\src\Ombi.Api.Radarr\RadarrApi.cs:line 111
2019-01-23 19:55:09.998 -05:00 [Error] Error when seing movie to DVR app, added to the request queue
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Core.Senders.MovieSender.SendToRadarr(MovieRequests model, RadarrSettings settings) in C:\projects\requestplex\src\Ombi.Core\Senders\MovieSender.cs:line 161
   at Ombi.Core.Senders.MovieSender.Send(MovieRequests model) in C:\projects\requestplex\src\Ombi.Core\Senders\MovieSender.cs:line 58

```

Desktop (please complete the following information):

OS: Windows 10 Pro
Ombi Version (please complete the following information):  Version 3.0.4119

**Comment by locatorr** [comment]
Issue resolved -- I thought I had read all previous issues about the subject, but I was missing my base URL (which I needed to do after I set up nginx and changing those respective settings in Radarr / Sonarr) 

https://github.com/tidusjar/Ombi/issues/1714#issuecomment-353612054
