### ISSUE TITLE
Unable to request the show 'You'

### ISSUE THREAD

**Issue by Viceman256** [tidusjar/Ombi#2779]
I'm getting failed requests for this show.

Ombi logs:
2019-02-01 10:19:44.366 -07:00 [Error] StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://127.0.0.1:8989/api/series/
2019-02-01 10:19:44.409 -07:00 [Error] StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://127.0.0.1:8989/api/series/
2019-02-01 10:19:44.447 -07:00 [Error] StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://127.0.0.1:8989/api/series/0
2019-02-01 10:31:41.398 -07:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: http://127.0.0.1:8989/api/system/status
2019-02-01 10:31:44.585 -07:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: http://127.0.0.1:8989/api/system/status
2019-02-01 10:33:05.863 -07:00 [Error] Something bad happened, ErrorMiddleware caught this
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Controllers.RequestRetryController.GetFailedRequests() in C:\projects\requestplex\src\Ombi\Controllers\RequestRetryController.cs:line 75
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 50
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24
2019-02-01 10:33:16.155 -07:00 [Error] StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://127.0.0.1:8989/api/series/
2019-02-01 10:33:16.192 -07:00 [Error] StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://127.0.0.1:8989/api/series/
2019-02-01 10:33:16.238 -07:00 [Error] StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://127.0.0.1:8989/api/series/0

Sonarr logs:
NzbDrone.Api.REST.BadRequestException: BadRequest :0 is not a valid ID
   at NzbDrone.Api.REST.RestModule`1.ValidateId(Int32 id) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Api\REST\RestModule.cs:line 33
   at CallSite.Target(Closure , CallSite , RestModule`1 , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at NzbDrone.Api.REST.RestModule`1.<set_GetResourceById>b__29_0(Object options) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Api\REST\RestModule.cs:line 82
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

Windows OS.

Version 3.0.4119 

Sonarr is enabled and I've generated a new API key. Other shows do work.

**Comment by Viceman256** [comment]
I haven't heard back on this. Is there perhaps a different forum I need to post this?

**Comment by tidusjar** [comment]
No this is the right place. I've just not had a lot of time recently. I'll look into this soon.

**Comment by tidusjar** [comment]
Can you delete the request from the failed queue and the requests and try again?

**Comment by Viceman256** [comment]
Hello,

I just did this and it correctly added it to Sonarr, despite showing up in Failed Requests too. Thank you!
