### ISSUE TITLE
Movies not being synced from Plex

### ISSUE THREAD

**Issue by TheOnlyYogo** [tidusjar/Ombi#2783]
**Describe the bug**
When a Manual Full Sync with Plex is is run (pre "update database" click), Ombi only gets and adds TV episodes to the DB, no mention of Movies. Additional evidence: when the newsletter feature is manually tested, Ombi console reports "Plex Movies to send: 0" however it reports "Plex Episodes to send: 8503". There are over 1300 movies in 2 libraries in Plex, which Ombi does not scrape.

**Steps to reproduce the behavior:**
1. Click "Manually Run Full Sync" in Media Server -> Plex Configuration
2. Check console to confirm behaviour

**Expected behaviour**
- Movies being scraped (similar to episode scrape) when Manual Full Sync is triggered
- Count of movies that are currently in Plex to display in the console when newsletter is tested

**Screenshots**
Console windows directly after Manual Full Sync is run, then test of newsletter
![screenshot-console](https://user-images.githubusercontent.com/29886470/52173457-3c9fc180-27d9-11e9-8397-c8421fe846c5.PNG)

**Logs**
```
2019-02-03 17:36:08.665 +11:00 [Information] Plex Movies to send: 0
2019-02-03 17:36:08.719 +11:00 [Information] Emby Movies to send: 0
2019-02-03 17:36:08.719 +11:00 [Information] Albums to send: 0
2019-02-03 17:36:21.824 +11:00 [Information] Plex Episodes to send: 8503
2019-02-03 17:36:21.824 +11:00 [Information] Emby Episodes to send: 0
2019-02-03 17:36:23.879 +11:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/tv/?api_key=b8eabaf5608b88d0298aa189dd90bf00
```

**Server:**
 - OS: Server 2012 R2 STD (6.3.9600)

**Version Information:**
- Ombi 3.0.4119-master
- Plex  1.14.1.5488

**Additional context**
Plex and Ombi reside on the same server, same partition, different directories
Tried doing a fresh install of Ombi, tried copying an empty ombi-external.db into an existing install, tried restarting Plex, tried restarting server

[There are 2 other Ombi users who are also having this issue from a post where I asked for help on Reddit](https://www.reddit.com/r/Ombi/comments/ah76pb/new_setup_has_some_issues/)

Users can request movies and it downloads them fine, it knows which movies I already have (when a duplicate is searched for, it says available)

During the TV Show scrape, I saw the DB filesize increase from the action, however it just stopped once it completed, and is currently sitting at 984KB and hasn't budged 

If you need any more info, just let me know

Cheers

**Comment by tidusjar** [comment]
What libraries have you selected in the Plex settings? Are your movie libraries selected?

Are you able to query the PlexContent table in the OmbiExternal.db and look to see if movies are in the table?

**Comment by TheOnlyYogo** [comment]
There are 2 movie libraries which have been selected in "Plex Configuration" and 3 TV Show libraries

and, yep, I'm an idiot... the movies are in the DB ...

But why don't they appear in the newsletter?

**Comment by tidusjar** [comment]
It's probably because it's trying to process 8k episodes in a newsletter. 

What I would do is press the button that says update database (or something along those words). That will set all your content to say it's been sent. From then on only new stuff will appear in the newsletter. Let me know how that goes

**Comment by TheOnlyYogo** [comment]
So I was writing the below, and sometime during typing, this happened:

![image](https://user-images.githubusercontent.com/29886470/52185190-d9fa0480-2870-11e9-8eee-772c1cf50d7e.png)


I'm a terrible tester, I didn't note what I did that triggered the above, but the DB has increased in size, and is now performing as expected with the newsletter...

![image](https://user-images.githubusercontent.com/29886470/52185200-001fa480-2871-11e9-8056-e6853da8fef5.png) 

Thanks for all the help Jamie, and I hope this helps someone in the future... just hit random buttons on Plex and in Ombi, and it will magically start working eventually!

So please disregard the below, as it is now working ...

_um, ok, new problem, unsure you want me to keep going on this post, or submit as a new issue..._

_When I press the "Update Database" button on the newsletter page, it doesn't reset the existing episodes and doesn't add new ones to the newsletter.._

_what I did:_

- _I hit the "Update Database" on the newsletter config page_
- _waited 5 minutes_
- _added 3 new episodes of 2 different shows_
- _Waited for Plex to find them and get the meta for them_
- _I hit the "Manually Run Recently Added Sync" button on the "Plex Configuration" page_
- _waited 10 minutes_
- _Hit the "Test" button for the newsletter_

_Console displays the same amount of episodes plus the three new ones
Newsletter received displays the same newsletter as the previous 4823 times I've tried the test (def not displaying all 8k episodes), but not the new episodes that were newly added_

_It's as if the "Update Database" on the newsletter config page doesn't do anything, and it doesn't add any new episodes to the newsletter (not sure if it just gives up trying to add 8k episodes, and the new ones aren't included)_

**Comment by TheOnlyYogo** [comment]
awesome, thanks!

just as an fyi. unsure whether this matters, I just got the following error in the console:

`fail: Ombi.Core.Senders.MovieSender[0]
      Error when seing movie to DVR app, added to the request queue
System.InvalidOperationException: An exception was thrown while attempting to evaluate a LINQ query parameter expression. To show additional information call EnableSensitiveDataLogging() when overriding DbContext.OnConfiguring. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure )
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor.Evaluate(Expression expression, String& parameterName
)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor.Evaluate(Expression expression, String& parameterName
)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor.TryExtractParameter(Expression expression)
   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor.VisitUnary(UnaryExpression unaryExpression)
   at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor.ExtractParameters(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, LambdaExpression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, Expression`1 predicate, CancellationToken cancellationToken)
   at Ombi.Core.Senders.MovieSender.SendToRadarr(MovieRequests model, RadarrSettings settings)
   at Ombi.Core.Senders.MovieSender.Send(MovieRequests model) in C:\projects\requestplex\src\Ombi.Core\Senders\MovieSender.cs:line 58`

or a pic if it helps to read it:

![image](https://user-images.githubusercontent.com/29886470/52198782-169d1e80-28b8-11e9-8b34-020aa8ee6982.png)

**Comment by TheOnlyYogo** [comment]
Hi Jamie,

Sorry for this, but the newsletter is not displaying any new movie titles (even though 13 have been added since this was closed)...

TV shows are coming through fine, displaying properly, but no movies. The "New Movies" title isn't even there like when it shows up for the "test" from the config. 

Disable movies is not checked, and there is no relevant info in the log files...
