### ISSUE TITLE
Gmail SMTP unable to connect

### ISSUE THREAD

**Issue by pettazz** [tidusjar/Ombi#2826]
**Describe the bug**
Sending emails via gmail smtp fails with "The SMTP server has unexpectedly disconnected."

**To Reproduce**
1. Add email notification configuration:
    - Enable SMTP Authentication: ON
    - SMTP Host: smtp.gmail.com
    - SMTP Port: 465, 587 (have tried both, same result)
    - Email sender, username: gmail address
    - Password: app password (2fa enabled)
2. Click test button, see error in logs

**Expected behavior**
Sent emails

**Logs (Logs directory where Ombi is located)**
````
2019-02-18 19:42:42.943 -05:00 [Error] Exception when attempting to send an email
MailKit.Net.Smtp.SmtpProtocolException: The SMTP server has unexpectedly disconnected.
   at MailKit.Net.Smtp.SmtpStream.ReadAheadAsync(Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpStream.ReadResponseAsync(Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpStream.ReadResponse(CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.SendCommandAsync(String command, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.SendEhloAsync(Boolean ehlo, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.EhloAsync(Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 81
2019-02-18 19:42:42.946 -05:00 [Warning] Exception when testing Email Notifications
MailKit.Net.Smtp.SmtpProtocolException: The SMTP server has unexpectedly disconnected.
   at MailKit.Net.Smtp.SmtpStream.ReadAheadAsync(Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpStream.ReadResponseAsync(Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpStream.ReadResponse(CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.SendCommandAsync(String command, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.SendEhloAsync(Boolean ehlo, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.EhloAsync(Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 81
   at Ombi.Controllers.External.TesterController.Email(EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 225
````

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04

**Ombi Version (please complete the following information):**
 - Version 3.0.4248

**Additional context**
A different app on the same server is able to send mail via the same gmail account and settings. Tried every combination of the two ports (465, 587) and Disable TLS/SSL, Disable Certificate Checking options (just to see), same issue. Seems that it's not even getting to the point of authentication before the connection fails.

**Comment by pettazz** [comment]
Also further evidence that it's not even getting to the point of trying to authenticate, when I look at the app passwords usage on my gmail account, it shows the "last used" for the others, but the one I created specifically for Ombi has no usage.

**Comment by DillonsFlix** [comment]
I am having the same issue ever since updating to the latest release although I have noticed that email is working for some functions.  Welcome messages are not working.  When I go to settings > Notifications > Email > Test reports an error and doesn't send.  New Requests and NewsLetter are working.

**Comment by miklina** [comment]
as of today, same problem here, cant authenticate

this has happended in this update 3.0.4248

**Comment by tidusjar** [comment]
And if you go to the previous version?

**Comment by miklina** [comment]
worked yesterday in previous version

**Comment by tidusjar** [comment]
Please provide your logs

**Comment by DillonsFlix** [comment]
When I try to send a test email from Settings > Notifications > Email I get the following logs.  


2019-02-19 07:56:37.634 -06:00 [Error] Exception when attempting to send an email
MailKit.Net.Smtp.SmtpProtocolException: The SMTP server has unexpectedly disconnected.
   at MailKit.Net.Smtp.SmtpStream.ReadAheadAsync(Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpStream.ReadResponseAsync(Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpStream.ReadResponse(CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.SendCommandAsync(String command, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.SendEhloAsync(Boolean ehlo, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.EhloAsync(Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 81
2019-02-19 07:56:37.638 -06:00 [Warning] Exception when testing Email Notifications
MailKit.Net.Smtp.SmtpProtocolException: The SMTP server has unexpectedly disconnected.
   at MailKit.Net.Smtp.SmtpStream.ReadAheadAsync(Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpStream.ReadResponseAsync(Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpStream.ReadResponse(CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.SendCommandAsync(String command, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.SendEhloAsync(Boolean ehlo, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.EhloAsync(Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 81
   at Ombi.Controllers.External.TesterController.Email(EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 225

**Comment by DillonsFlix** [comment]
Yesterday I was able to send a test newsletter but today I am not. Here are the logs from that.  
2019-02-19 08:08:29.258 -06:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/tv/?api_key=b8eabaf5608b88d0298aa189dd90bf00
2019-02-19 08:08:29.629 -06:00 [Error] Exception when attempting to send email
MailKit.Security.AuthenticationException: AuthenticationInvalidCredentials: 5.7.8 Username and Password not accepted. Learn more at
5.7.8  https://support.google.com/mail/?p=BadCredentials 12sm5190580wme.25 - gsmtp ---> MailKit.Net.Smtp.SmtpCommandException: 5.7.8 Username and Password not accepted. Learn more at
5.7.8  https://support.google.com/mail/?p=BadCredentials 12sm5190580wme.25 - gsmtp
   --- End of inner exception stack trace ---
   at MailKit.Net.Smtp.SmtpClient.AuthenticateAsync(Encoding encoding, ICredentials credentials, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
   at MailKit.MailService.Authenticate(String userName, String password, CancellationToken cancellationToken)
   at Ombi.Notifications.GenericEmailProvider.Send(MimeMessage message, EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 164
2019-02-19 08:08:29.632 -06:00 [Error] Error when attempting to create newsletter
MailKit.Security.AuthenticationException: AuthenticationInvalidCredentials: 5.7.8 Username and Password not accepted. Learn more at
5.7.8  https://support.google.com/mail/?p=BadCredentials 12sm5190580wme.25 - gsmtp ---> MailKit.Net.Smtp.SmtpCommandException: 5.7.8 Username and Password not accepted. Learn more at
5.7.8  https://support.google.com/mail/?p=BadCredentials 12sm5190580wme.25 - gsmtp
   --- End of inner exception stack trace ---
   at MailKit.Net.Smtp.SmtpClient.AuthenticateAsync(Encoding encoding, ICredentials credentials, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
   at MailKit.MailService.Authenticate(String userName, String password, CancellationToken cancellationToken)
   at Ombi.Notifications.GenericEmailProvider.Send(MimeMessage message, EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 164
   at Ombi.Notifications.GenericEmailProvider.Send(NotificationMessage model, EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 129
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.Start(NewsletterSettings settings, Boolean test) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\NewsletterJob.cs:line 261
2019-02-19 08:08:29.642 -06:00 [Error] Could not test Newsletter
MailKit.Security.AuthenticationException: AuthenticationInvalidCredentials: 5.7.8 Username and Password not accepted. Learn more at
5.7.8  https://support.google.com/mail/?p=BadCredentials 12sm5190580wme.25 - gsmtp ---> MailKit.Net.Smtp.SmtpCommandException: 5.7.8 Username and Password not accepted. Learn more at
5.7.8  https://support.google.com/mail/?p=BadCredentials 12sm5190580wme.25 - gsmtp
   --- End of inner exception stack trace ---
   at MailKit.Net.Smtp.SmtpClient.AuthenticateAsync(Encoding encoding, ICredentials credentials, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
   at MailKit.MailService.Authenticate(String userName, String password, CancellationToken cancellationToken)
   at Ombi.Notifications.GenericEmailProvider.Send(MimeMessage message, EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 164
   at Ombi.Notifications.GenericEmailProvider.Send(NotificationMessage model, EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 129
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.Start(NewsletterSettings settings, Boolean test) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\NewsletterJob.cs:line 261
   at Ombi.Controllers.External.TesterController.NewsletterTest(NewsletterNotificationViewModel settings) in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 390

**Comment by DillonsFlix** [comment]
When I try and send a User Welcome email there are no log entries.

**Comment by pettazz** [comment]
I just installed for the first time on v 3.0.4248 via the apt repo. 

Tried increasing logging levels but I don't see anything more relevant in the output. My suspicion based on similar stuff found googling the MailKit error is that it's not setting SSL/TLS and the google server is rejecting it early on.

**Comment by tidusjar** [comment]
Fixed in develop, will push out a new release today

**Comment by pettazz** [comment]
Fix works for me, thanks!

**Comment by Nostradamus1973** [comment]
Good morning,
Running Ombi 4.21.1 and this is happening again. SMTP settings work fine on other applications.

Thank you
