### ISSUE TITLE
Can't connect to couchpotato

### ISSUE THREAD

**Issue by krisklosterman** [tidusjar/Ombi#2829]
**Describe the bug**
I am unable to configure the Couchpotato connection properly. I enter the API key, localhost (its on same server) and port and use get profiles and it just does the spiny sign next to it. Couch potato logs display 
`UNKNOWN UNKNOWN
[31mUncaught exception`

**To Reproduce**
'N/A'

**Expected behavior**
It to connect

**Screenshots**

**Logs (Logs directory where Ombi is located)**
```
Feb 19 14:41:13 zombiedefenceserver Ombi[11598]: fail: Ombi.ErrorHandlingMiddleware[0]
Feb 19 14:41:13 zombiedefenceserver Ombi[11598]:       Something bad happened, ErrorMiddleware caught this
Feb 19 14:41:13 zombiedefenceserver Ombi[11598]: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: Unable to read data from the transport connection: Connection rese
Feb 19 14:41:13 zombiedefenceserver Ombi[11598]:    --- End of inner exception stack trace ---
Feb 19 14:41:13 zombiedefenceserver Ombi[11598]:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
Feb 19 14:41:13 zombiedefenceserver Ombi[11598]:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
Feb 19 14:41:13 zombiedefenceserver Ombi[11598]:    at System.Net.Http.HttpConnection.FillAsync()
Feb 19 14:41:13 zombiedefenceserver Ombi[11598]:    at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
Feb 19 14:41:13 zombiedefenceserver Ombi[11598]:    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
Feb 19 14:41:13 zombiedefenceserver Ombi[11598]:    --- End of inner exception stack trace ---
Feb 19 14:41:13 zombiedefenceserver Ombi[11598]:    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
Feb 19 14:41:13 zombiedefenceserver Ombi[11598]:    at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellati
Feb 19 14:41:13 zombiedefenceserver Ombi[11598]:    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
Feb 19 14:41:13 zombiedefenceserver Ombi[11598]:    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Feb 19 14:41:13 zombiedefenceserver Ombi[11598]:    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
Feb 19 14:41:13 zombiedefenceserver Ombi[11598]:    at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request) in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
Feb 19 14:41:13 zombiedefenceserver Ombi[11598]:    at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
Feb 19 14:41:13 zombiedefenceserver Ombi[11598]:    at Ombi.Api.CouchPotato.CouchPotatoApi.GetProfiles(String url, String apiKey) in C:\projects\requestplex\src\Ombi.Api.CouchPotato\CouchPotatoApi.cs:line 60
Feb 19 14:41:13 zombiedefenceserver Ombi[11598]:    at Ombi.Controllers.External.CouchPotatoController.GetQualityProfiles(CouchPotatoSettings settings) in C:\projects\requestplex\src\Ombi\Controllers\External\CouchPotatoContro
Feb 19 14:41:13 zombiedefenceserver Ombi[11598]:    at lambda_method(Closure , Object )
Feb 19 14:41:13 zombiedefenceserver Ombi[11598]:    at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controll
Feb 19 14:41:13 zombiedefenceserver Ombi[11598]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
Feb 19 14:41:13 zombiedefenceserver Ombi[11598]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
Feb 19 14:41:13 zombiedefenceserver Ombi[11598]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
Feb 19 14:41:13 zombiedefenceserver Ombi[11598]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 19 14:41:13 zombiedefenceserver Ombi[11598]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
Feb 19 14:41:13 zombiedefenceserver Ombi[11598]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
Feb 19 14:41:13 zombiedefenceserver Ombi[11598]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Feb 19 14:41:13 zombiedefenceserver Ombi[11598]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 19 14:41:13 zombiedefenceserver Ombi[11598]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
Feb 19 14:41:13 zombiedefenceserver Ombi[11598]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
Feb 19 14:41:13 zombiedefenceserver Ombi[11598]:    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Feb 19 14:41:13 zombiedefenceserver Ombi[11598]:    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Feb 19 14:41:13 zombiedefenceserver Ombi[11598]:    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
Feb 19 14:41:13 zombiedefenceserver Ombi[11598]:    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
Feb 19 14:41:13 zombiedefenceserver Ombi[11598]:    at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context)
Feb 19 14:41:13 zombiedefenceserver Ombi[11598]:    at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 51
Feb 19 14:41:13 zombiedefenceserver Ombi[11598]:    at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24
```

**Desktop (please complete the following information):**
 - OS: Debian, used APT to install

**Ombi Version (please complete the following information):**
 - Version - 3.0.4256
- Media Server - Plex
- Couchpotato - 1/13/2019

**Additional context**

**Comment by DoomGekicher** [comment]
I tried Couch Potato but overall it was just an annoyance. I use Sonarr for T.V shows, Radarr for Movies and ever since then I haven't had any problems.

**Comment by krisklosterman** [comment]
I've been using CouchPotato for a couple of years now with no issues. I've tried Radarr and was not happy enough with it to switch.

**Comment by tidusjar** [comment]
Please double check your settings, it seems that it's a connection issue

**Comment by krisklosterman** [comment]
I had apache setup to proxy from the outside to the local couchpotato port. I was able to enter the domain into the settings and have it work. I changed it to not proxy anymore and it's now working with localhost.
