### ISSUE TITLE
Welcome email not sending (other emails fine)

### ISSUE THREAD

**Issue by jackyaz** [tidusjar/Ombi#2868]
**Describe the bug**
Welcome email not sending (other emails fine)

**To Reproduce**
Confirm email working via Test and/or Mass Email. Add a user, and click send Welcome Email

**Expected behavior**
Welcome email should be sent. It looks like the Welcome Email isn't using credentials correctly?

**Screenshots**
N/A

**Logs (Logs directory where Ombi is located)**
```

2019-03-06T17:37:58.100645425Z fail: Ombi.Notifications.GenericEmailProvider[0]
2019-03-06T17:37:58.100695128Z       Exception when attempting to send an email
2019-03-06T17:37:58.100705993Z MailKit.Security.AuthenticationException: AuthenticationInvalidCredentials: 5.7.8 Username and Password not accepted. Learn more at
2019-03-06T17:37:58.100715506Z 5.7.8  https://support.google.com/mail/?p=BadCredentials j20sm3699411pfh.141 - gsmtp ---> MailKit.Net.Smtp.SmtpCommandException: 5.7.8 Username and Password not accepted. Learn more at
2019-03-06T17:37:58.100729123Z 5.7.8  https://support.google.com/mail/?p=BadCredentials j20sm3699411pfh.141 - gsmtp
2019-03-06T17:37:58.100738329Z    --- End of inner exception stack trace ---
2019-03-06T17:37:58.100746816Z    at MailKit.Net.Smtp.SmtpClient.AuthenticateAsync(Encoding encoding, ICredentials credentials, Boolean doAsync, CancellationToken cancellationToken)
2019-03-06T17:37:58.100849944Z    at MailKit.Net.Smtp.SmtpClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
2019-03-06T17:37:58.100881466Z    at MailKit.MailService.Authenticate(String userName, String password, CancellationToken cancellationToken)
2019-03-06T17:37:58.101904812Z    at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 87
2019-03-06T17:38:32.017499092Z fail: Ombi.Notifications.GenericEmailProvider[0]
2019-03-06T17:38:32.017527946Z       Exception when attempting to send an email
2019-03-06T17:38:32.017532735Z MailKit.Security.AuthenticationException: AuthenticationInvalidCredentials: 5.7.8 Username and Password not accepted. Learn more at
2019-03-06T17:38:32.017536645Z 5.7.8  https://support.google.com/mail/?p=BadCredentials b6sm3539867pgl.49 - gsmtp ---> MailKit.Net.Smtp.SmtpCommandException: 5.7.8 Username and Password not accepted. Learn more at
2019-03-06T17:38:32.017540610Z 5.7.8  https://support.google.com/mail/?p=BadCredentials b6sm3539867pgl.49 - gsmtp
2019-03-06T17:38:32.017544244Z    --- End of inner exception stack trace ---
2019-03-06T17:38:32.017547733Z    at MailKit.Net.Smtp.SmtpClient.AuthenticateAsync(Encoding encoding, ICredentials credentials, Boolean doAsync, CancellationToken cancellationToken)
2019-03-06T17:38:32.017563036Z    at MailKit.Net.Smtp.SmtpClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
2019-03-06T17:38:32.017566786Z    at MailKit.MailService.Authenticate(String userName, String password, CancellationToken cancellationToken)
2019-03-06T17:38:32.017570302Z    at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 87
```

**Desktop (please complete the following information):**
 - OS: Windows 10 - Chrome

**Ombi Version (please complete the following information):**
 - Version: 3.0.4256
- Media Server: Plex

**Additional context**

**Comment by tidusjar** [comment]
The errors from your log state `Username and Password not accepted.`

Are you sure your credentials are correct?

**Comment by jackyaz** [comment]
Yes. As i said, all other email functions work fine, such as New Requests, Mass email and the test email.

**Comment by jackyaz** [comment]
I will check through the code later to see why the Welcome Email is acting differently.

**Comment by jackyaz** [comment]
This morning it's working fine. The only difference is I'm using mobile Chrome, but I doubt that's a factor. Will test further tonight.

**Comment by garylutz** [comment]
I just installed for the first time today - and all email functions are working for me except for Welcome - just like original poster.  All credentials are correct - newsletter sends fine, tests work.  Welcome will not go out.  I do have the URL entered in customization - as I've read this can also cause Welcome to not go out as well.

**Comment by jackyaz** [comment]
Mine's still working. The only thing I think I did differently was add a user with a role of Subscribe to Newsletter, and after that any users (with or without that role) now receive the welcome email

**Comment by m1lkman** [comment]
Having same issue as OP, I can send all other emails but Welcome never is sent. No errors in the log. Can I turn on debugging or something?

**Comment by wkupike2000** [comment]
I'm in an almost exact same boat. My test email and my newsletter tests send fine, nothing else will send no matter what I try. I'm setup to send from Gmail and can't find any errors anywhere or in the logs

**Comment by lloydie2009** [comment]
I have the same issue. Other emails are sending fine, but the welcome email does not.

**Comment by tidusjar** [comment]
Have you tried develop? Also restarting ombi? I have a feeling that the settings might be cached and it's not looking at the new settings when attempting to send a email

**Comment by lloydie2009** [comment]
Restarting doesn't help. I have not tried develop. All other emails send fine, it's just the welcome email that never arrives.

**Comment by tidusjar** [comment]
Checked spam?

It's it in your sent items?

**Comment by lloydie2009** [comment]
Not in spam, and yes I've checked sent items, nothing there,not even the successful ones.

I figured SMTP submissions don't normally put an item in the sent items of the mailbox though.

**Comment by SanctiMortem** [comment]
I've got the same problem. Just Installed Ombi in a new machine from scratch. I do have the 2 authentication step with gmail, and already added the credentials. I can send test emails and Newsletters without a problem. I can see them in "sent", but the Welcome emails are a no show.

Thank you in advance,
Best Regards!

**Comment by tidusjar** [comment]
Logs?

**Comment by SturmB** [comment]
Restarting the Ombi Docker container fixed this issue for me.

**Comment by Sibicle** [comment]
Same issue here. Got auth working via a G Suite account, and received test email to the said G Suite account. Clicked "Send Welcome Email" button on User Management page, and got a toast indicating success, with nothing in the logs, but never got an email.

Restarting the container seemed to fix it for me as well...thanks!
