### ISSUE TITLE
CPU spiking every minute

### ISSUE THREAD

**Issue by mhbates** [tidusjar/Ombi#2876]
**Describe the bug**
I noticed that Ombi is spiking the CPU every minute, exactly, about 15-20%, specifically iowait according to Netdata (so not really a CPU spike per se, but you get the picture). This stops once the container is stopped. I checked Ombi's cron jobs section and didn't see anything scheduled to run every minute. Has anyone else encountered this?

**Screenshots**
![image](https://user-images.githubusercontent.com/18390027/54064344-36ca4100-41c8-11e9-899b-08baa0aa7ddb.png)

**Logs (Logs directory where Ombi is located)**
I don't think this error is related since it's not happening every minute:

> 2019-03-08 16:48:40.489 -08:00 [Error] Something bad happened, ErrorMiddleware caught this
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 77
   at Ombi.Api.FanartTv.FanartTvApi.GetTvImages(Int32 tvdbId, String token) in C:\projects\requestplex\src\Ombi.Api.FanartTv\FanartTvApi.cs:line 27
   at Ombi.Controllers.ImagesController.GetTvBanner(Int32 tvdbid) in C:\projects\requestplex\src\Ombi\Controllers\ImagesController.cs:line 45
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Objec$
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 51
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24

**Desktop (please complete the following information):**
 - OS: Debian 9 stable

**Ombi Version (please complete the following information):**
 - Version: Running the LSIO docker image, version 3.0.4256
- Media Server: Plex

**Comment by tidusjar** [comment]
There is nothing that runs every minute...

I have absolutely no idea. All I can possibly think is that it might be something in the .Net Core runtime that might be causing it. But then again i'm not seeing this myself on my container (LSIO) with unRaid OS

**Comment by mhbates** [comment]
Hmm. I just tested again and it definitely stops when the container is stopped. Strange. I did some digging with iotop and this is what I've found, hopefully some of this is helpful:

  TID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN     IO>    COMMAND
  210 be/3 root          0.00 B    576.00 K  0.00 % 10.69 % [jbd2/sdb1-8]

That IO% fluctuates of course. With Ombi off, it tends to go no higher than 15%. With Ombi on, it spikes up to 90%+ once a minute. SDB is my primary/system drive, where Ombi's installed.

Not sure if that TID# helps at all. If I run `cat /proc/210/io`, it shows that the process wrote about 12gb so far; `write_bytes: 12281466880`. According to top, the process has been up for about 4 hours.

Does any of this help?

**Comment by tidusjar** [comment]
Can you edit the appsettings.json file inside the container and set the
logging sections to None.

You'll understand what I mean when you see the file.

**Comment by mhbates** [comment]
Default and System set to Information? Too much?

I went ahead and changed that and restarted the container, but still seeing spikes.

**Comment by tidusjar** [comment]
I just thought it might be logging, maybe the logging framework keeps them in a buffer and releases every minute. But that doesn't seem to be the case...

**Comment by mhbates** [comment]
I think I have good news. I went back through the old docker versions and found that v102 (6/29/18) had the issue, but v57 (1/26/18) doesn't. I'll work my way back and see if I can pinpoint where it started.

https://github.com/linuxserver/docker-ombi/releases?after=109

**Comment by mhbates** [comment]
Okay, looks like it started between docker versions 64 and 65. Is this when Ombi v3 came out? I noticed a db change in the config folder, and then from the git: rebase to xenial, update ombi service to .net core, etc.

**Comment by tidusjar** [comment]
Going from V2 to V3 was a complete rewrite...
