### ISSUE TITLE
"Advanced" Button Toggle Invisible

### ISSUE THREAD

**Issue by schmittimillian** [tidusjar/Ombi#2889]
**Describe the bug**
The toggle button for Advanced settings in the Settings pages is invisible. Clicking the element works normally, but there's no button that actually displays. 
Looks like there might be some bug with the js, css, or whatever controls the styling for that element.

**To Reproduce**
>note: this happens on all pages with the ``Advanced`` toggle, but this describes just one page.

1. Go to <ombi_URL>/Settings/Radarr
2. Look for the ``Advanced`` label
3. Notice that there's no button next to the label
4. You can hover over where the element is, and the cursor changes to a "you can click this" cursor
5. Clicking shows/hides Advanced settings, but nothing displays on the page for the button.

**Expected behavior**
element for the advanced toggle button should be visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/22268708/54371422-bc7a4080-464f-11e9-81ff-b0575fc1d429.png)

**Logs (Logs directory where Ombi is located)**
<i>not sure if this is related, but looking at the logs, it looks like ombi is trying to access stuff in some development path.
example:</i>
<code>...at Ombi.Store.Repository.BaseRepository`2.Delete(T request) in <b>C:\projects\requestplex\src\Ombi.Store\Repository\BaseRepository.cs:line 57</b></code>

<b>log-20190313.txt</b>:
```
2019-03-13 09:30:12.975 -04:00 [Error] Something bad happened, ErrorMiddleware caught this
System.ArgumentNullException: Value cannot be null.
Parameter name: entity
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
   at Microsoft.EntityFrameworkCore.DbContext.Remove[TEntity](TEntity entity)
   at Ombi.Store.Repository.BaseRepository`2.Delete(T request) in C:\projects\requestplex\src\Ombi.Store\Repository\BaseRepository.cs:line 57
   at Ombi.Core.Engine.MovieRequestEngine.RemoveMovieRequest(Int32 requestId) in C:\projects\requestplex\src\Ombi.Core\Engine\MovieRequestEngine.cs:line 420
   at Ombi.Controllers.RequestController.DeleteRequest(Int32 requestId) in C:\projects\requestplex\src\Ombi\Controllers\RequestController.cs:line 122
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 51
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24
2019-03-13 09:30:20.309 -04:00 [Error] Something bad happened, ErrorMiddleware caught this
System.ArgumentNullException: Value cannot be null.
Parameter name: entity
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
   at Microsoft.EntityFrameworkCore.DbContext.Remove[TEntity](TEntity entity)
   at Ombi.Store.Repository.BaseRepository`2.Delete(T request) in C:\projects\requestplex\src\Ombi.Store\Repository\BaseRepository.cs:line 57
   at Ombi.Core.Engine.MovieRequestEngine.RemoveMovieRequest(Int32 requestId) in C:\projects\requestplex\src\Ombi.Core\Engine\MovieRequestEngine.cs:line 420
   at Ombi.Controllers.RequestController.DeleteRequest(Int32 requestId) in C:\projects\requestplex\src\Ombi\Controllers\RequestController.cs:line 122
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 51
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24
2019-03-13 09:30:38.846 -04:00 [Error] Something bad happened, ErrorMiddleware caught this
System.ArgumentNullException: Value cannot be null.
Parameter name: entity
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
   at Microsoft.EntityFrameworkCore.DbContext.Remove[TEntity](TEntity entity)
   at Ombi.Store.Repository.BaseRepository`2.Delete(T request) in C:\projects\requestplex\src\Ombi.Store\Repository\BaseRepository.cs:line 57
   at Ombi.Core.Engine.MovieRequestEngine.RemoveMovieRequest(Int32 requestId) in C:\projects\requestplex\src\Ombi.Core\Engine\MovieRequestEngine.cs:line 420
   at Ombi.Controllers.RequestController.DeleteRequest(Int32 requestId) in C:\projects\requestplex\src\Ombi\Controllers\RequestController.cs:line 122
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 51
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24
2019-03-13 09:30:53.965 -04:00 [Error] Something bad happened, ErrorMiddleware caught this
System.ArgumentNullException: Value cannot be null.
Parameter name: entity
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
   at Microsoft.EntityFrameworkCore.DbContext.Remove[TEntity](TEntity entity)
   at Ombi.Store.Repository.BaseRepository`2.Delete(T request) in C:\projects\requestplex\src\Ombi.Store\Repository\BaseRepository.cs:line 57
   at Ombi.Core.Engine.MovieRequestEngine.RemoveMovieRequest(Int32 requestId) in C:\projects\requestplex\src\Ombi.Core\Engine\MovieRequestEngine.cs:line 420
   at Ombi.Controllers.RequestController.DeleteRequest(Int32 requestId) in C:\projects\requestplex\src\Ombi\Controllers\RequestController.cs:line 122
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 51
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24
2019-03-13 09:31:10.152 -04:00 [Error] Something bad happened, ErrorMiddleware caught this
System.ArgumentNullException: Value cannot be null.
Parameter name: entity
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
   at Microsoft.EntityFrameworkCore.DbContext.Remove[TEntity](TEntity entity)
   at Ombi.Store.Repository.BaseRepository`2.Delete(T request) in C:\projects\requestplex\src\Ombi.Store\Repository\BaseRepository.cs:line 57
   at Ombi.Core.Engine.MovieRequestEngine.RemoveMovieRequest(Int32 requestId) in C:\projects\requestplex\src\Ombi.Core\Engine\MovieRequestEngine.cs:line 420
   at Ombi.Controllers.RequestController.DeleteRequest(Int32 requestId) in C:\projects\requestplex\src\Ombi\Controllers\RequestController.cs:line 122
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 51
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24
```

**Desktop (please complete the following information):**
 - OS: Windows Server 2019
 - Browser: Tested on Mozilla Firefox (65.0.2 64-bit) and Google Chrome (72.0.3626.119 64-bit)

**Ombi Version (please complete the following information):**
 - Version 3.0.4256
- Media Server Plex

**Additional context**
<i>Element information:</i> (grabbed from ``Inspect Element``)
```html
<div style="float: right;">
  <span style="vertical-align: top;">Advanced</span>
  <p-inputswitch id="customInputSwitch" class="ng-untouched ng-pristine ng-valid">
    <div role="checkbox" class="ui-inputswitch ui-widget" aria-checked="false">
      <div class="ui-helper-hidden-accessible">
        <input type="checkbox">
      </div>
      <span class="ui-inputswitch-slider">
        ::before
      </span>
    </div>
  </p-inputswitch>
</div>
```
- ombi is running as a service through nssm.
- I have ombi running behind a reverse proxy (base URL: ``/requests``) using nginx. I still see this happen whether I access ombi externally through the reverse proxy (``sub.domain.com/requests``), locally through the reverse proxy (``localhost/requests``) or locally via the direct port (``localhost:5000``). all have the same behavior.
- I have tried the basic stuff - clearing cache/cookies, restarting the service, etc. with no difference.
- it also is not specific to one device - happens on the server itself and a few other computers I use (all Windows if that matters at all).

**Comment by tidusjar** [comment]
Yeah your right, looks like a recent update must have broke the styling.

For now i'm actually not going to fix this unless someone else wants to do it. I'm currently focused on the V4 UI so everything is going to look completely different soon.

**Comment by schmittimillian** [comment]
makes sense. not a big deal to wait until V4.
how about that stuff in the logs where it appears like it's looking for paths in a development environment?

**Comment by tidusjar** [comment]
That's not an issue.

It's not looking there, that's just the path that the program was compiled
at.

**Comment by schmittimillian** [comment]
got it. interesting!

**Comment by kmickeletto** [comment]
Since I can't get into advanced, I'm unable to configure search parameters so something downloads automatically after it's requested and approved.

Is there a URI that I can append to see the advanced settings?

**Comment by tidusjar** [comment]
Download and search after requested is the default option.
