### ISSUE TITLE
TV Show requests to Sonarr not working

### ISSUE THREAD

**Issue by zyphermonkey** [tidusjar/Ombi#2891]
**Describe the bug**
Whenever a TV is requested it doesn't get added to Sonarr. It doesn't matter if it's the series, a season, or just an episode. 

The logs make it seem that there is an issue with the API, but when I do a test from settings>TV>Sonarr>Test Connectivity I get the "Successfully connected to Sonarr!" notification 

**To Reproduce**
Request TV Show

**Expected behavior**
Expect TV Show to be added and monitored in Sonarr, but show never gets added to Sonarr.

**Logs (Logs directory where Ombi is located)**
2019-03-15 07:42:56.805 -04:00 [Error] StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://192.168.1.10:8989/api/series/0

**Ombi Version (please complete the following information):**
- Version [3.0.4256]
- Sonarr Ver. 2.0.0.5301

**Additional context**
192.168.1.10:8989 is the ip:port for my Sonarr installation.

**Comment by tidusjar** [comment]
Does this happen to every show?

Does it happen to shows that are not in sonarr?
does it happen to shows that are already present in sonarr?

**Comment by zyphermonkey** [comment]
> Does this happen to every show?

It's happened for every show so far so I would say yes that is happening for every show. I've had 4 different show requests come in and I added one myself for testing just to make sure it wasn't some weird permissions issue.
> 
> Does it happen to shows that are not in sonarr?

This is what the requests are for. 
> does it happen to shows that are already present in sonarr?

I have not tested this, but if you think it'll help let me know and I'll add a show un-monitored in Sonarr and then request it in Ombi to see what happens.

**Comment by zyphermonkey** [comment]
I added a show to Sonarr un-monitored and then requested an episode in Ombi. I got an error saying 
`it could not be added. This has been added into the requests queue and will keep retrying`
but when I checked in Sonarr the season and episode were marked as monitored, but it was not searched for or downloaded.

**Additional Logs after adding episode to existing show in Sonarr**
```
2019-03-15 08:27:54.436 -04:00 [Error] Exception thrown when attempting to send series over to Sonarr
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Ombi.Api.Sonarr.Models.CommandResult' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 77
   at Ombi.Api.Sonarr.SonarrApi.Command(String apiKey, String baseUrl, Object body) in C:\projects\requestplex\src\Ombi.Api.Sonarr\SonarrApi.cs:line 196
   at Ombi.Api.Sonarr.SonarrApi.EpisodeSearch(Int32[] episodeIds, String apiKey, String baseUrl) in C:\projects\requestplex\src\Ombi.Api.Sonarr\SonarrApi.cs:line 160
   at Ombi.Core.Senders.TvSender.SearchForRequest(ChildRequests model, IEnumerable`1 sonarrEpList, SonarrSeries existingSeries, SonarrSettings s, IReadOnlyCollection`1 episodesToUpdate) in C:\projects\requestplex\src\Ombi.Core\Senders\TvSender.cs:line 521
   at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSeries result, SonarrSettings s) in C:\projects\requestplex\src\Ombi.Core\Senders\TvSender.cs:line 397
   at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSettings s) in C:\projects\requestplex\src\Ombi.Core\Senders\TvSender.cs:line 264
2019-03-15 08:27:54.441 -04:00 [Error] Exception thrown when sending a movie to DVR app, added to the request queue
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Ombi.Api.Sonarr.Models.CommandResult' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 77
   at Ombi.Api.Sonarr.SonarrApi.Command(String apiKey, String baseUrl, Object body) in C:\projects\requestplex\src\Ombi.Api.Sonarr\SonarrApi.cs:line 196
   at Ombi.Api.Sonarr.SonarrApi.EpisodeSearch(Int32[] episodeIds, String apiKey, String baseUrl) in C:\projects\requestplex\src\Ombi.Api.Sonarr\SonarrApi.cs:line 160
   at Ombi.Core.Senders.TvSender.SearchForRequest(ChildRequests model, IEnumerable`1 sonarrEpList, SonarrSeries existingSeries, SonarrSettings s, IReadOnlyCollection`1 episodesToUpdate) in C:\projects\requestplex\src\Ombi.Core\Senders\TvSender.cs:line 521
   at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSeries result, SonarrSettings s) in C:\projects\requestplex\src\Ombi.Core\Senders\TvSender.cs:line 397
   at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSettings s) in C:\projects\requestplex\src\Ombi.Core\Senders\TvSender.cs:line 264
   at Ombi.Core.Senders.TvSender.Send(ChildRequests model) in C:\projects\requestplex\src\Ombi.Core\Senders\TvSender.cs:line 61
```

**Comment by tidusjar** [comment]
Sounds like your settings are not fully correct in Ombi. Can you please double check them?

If you are running Sonarr on a base url then make sure you include that in the ombi settings

**Comment by zyphermonkey** [comment]
Base url was the issue. I forgot I made a change to the sonarr config for letsencrypt/nginx. 

Sorry for the trouble.
