### ISSUE TITLE
User Importer fails to run due to "Unauthorized"

### ISSUE THREAD

**Issue by cybersteel8** [tidusjar/Ombi#2892]
**Describe the bug**
An error occurs when opening Configuration > User Importer

**To Reproduce**
1. Go to Ombi
2. Click on Configuration and then User Importer
3. View logs, there is an error.
4. Run the importer, another error appears.

**Expected behavior**
The user importer should be able to be run successfully and add my new friend to Ombi.

**Logs (Logs directory where Ombi is located)**
```
 fail: Ombi.Api.Api[1000]
       StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://plex.tv/pms/friends/all/
 fail: Ombi.ErrorHandlingMiddleware[0]
       Something bad happened, ErrorMiddleware caught this
 System.InvalidOperationException: There is an error in XML document (2, 2). ---> 
System.InvalidOperationException: <errors xmlns=''> was not expected.
    at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexFriends.Read5_MediaContainer()
    --- End of inner exception stack trace ---
    at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
    at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
    at Ombi.Api.Api.DeserializeXml[T](String receivedString) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 92
    at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 83
    at Ombi.Api.Plex.PlexApi.GetUsers(String authToken) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 200
    at Ombi.Controllers.External.PlexController.GetFriends() in C:\projects\requestplex\src\Ombi\Controllers\External\PlexController.cs:line 259
    at lambda_method(Closure , Object )
    at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
    at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 51
    at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24
```
and then when you attempt to run the Importer, the next two lines appear:
```
fail: Ombi.Api.Api[1000]
      StatusCode: UnprocessableEntity, Reason: Unprocessable Entity, RequestUri: https://plex.tv/users/account.json
```
this log appears every time the UserImporter job attempts to run.

**Desktop (please complete the following information):**
 - Linux 4.18.19-100.fc27.x86_64 is the server running Ombi
- Windows 7 SP1 is the client accessing Ombi via Chrome 74.0.3729.6 

**Ombi Version (please complete the following information):**
 - Version 3.0.1256-master
- Media Server - Plex 

**Additional context**
I am logged in as the user with the Admin role, and I already have 1 other user with various Request and AutoApprove permissions. I would like to add another user. I have logged in via Plex, both of the two users do that and the third user has already been added to my Plex account as a "friend" (sharing the libraries). I am also logged in on plex.tv to avoid any possible token issues, if that's relevant at all.

I am attempting to access the url `https://plex.tv/pms/friends/all` in my browser directly, and I do indeed get a 401 despite being logged in on plex.tv. It returns 401 and a "Please sign in" error in XML.

`https://plex.tv/users/account.json` is showing JSON data about my account though, so this appears to be working but Ombi still added that error.

**Comment by xunil75** [comment]
Please check these things first:

1. have you logged in localy or via Plex OAuth on your Ombi?
2. have you setup your Plex Server under "Settings - Media Server - Plex"?
3. Setup the Plex Server (sign in your Plex account) and do a "Check connectivity" to verify your connection.

**Comment by Ashtonian** [comment]
I had same issue, the api/friends was returning 500. After adding the server correction the /friends request now returns an array with all the user ids however the screen is still blank...

**Comment by cybersteel8** [comment]
Hi, thank you for your responses!

1) Via Plex OAuth
2) Yes 
3) Connectivity worked successfully.

However I did remove and re-add my Plex server since this is clearly an important factor. The only difference was that it received a new Token, so maybe the previous token was invalidated (due to its age?). This also required a restart of the Ombi service before it worked and imported the new user.

Thanks for all your help!
