### ISSUE TITLE
Won't connect to Sonarr

### ISSUE THREAD

**Issue by magauthority** [tidusjar/Ombi#2899]
I've tried multiple times to enter the correct data to connect to Sonarr, but it won't connect!
Here's the relevant error in the log: 
at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 51
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24
2019-03-22 14:34:39.441 -04:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: http://192.168.0.102:8989/api/rootfolder
2019-03-22 14:34:39.441 -04:00 [Error] Something bad happened, ErrorMiddleware caught this
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[Ombi.Api.Sonarr.Models.SonarrRootFolder]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'error', line 2, position 10.

Radarr works perfectly.

**Comment by tidusjar** [comment]
IT's

**Comment by magauthority** [comment]
That's crazy. I copied it directly from Sonarr more than once, but then when I tried it again, it worked. Strange. Thanks for the help.
