### ISSUE TITLE
404 Error in log when clicking Settings in web UI

### ISSUE THREAD

**Issue by dkosburn** [tidusjar/Ombi#2916]
When I do nothing more than click Settings in the web UI, this error shows up in the log:

```fail: Ombi.ErrorHandlingMiddleware[0]
      Something bad happened, ErrorMiddleware caught this
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(Task`1 getTask)
   at Ombi.Api.OmbiHttpClient.GetStringAsync(Uri requestUri) in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 67
   at Ombi.Schedule.Processor.ChangeLogProcessor.Process(String branch) in C:\projects\requestplex\src\Ombi.Schedule\Processor\ChangeLogProcessor.cs:line 36
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.UpdateAvailable(String branch, String currentVersion) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 56
   at Ombi.Controllers.JobController.<CheckForUpdateCached>b__10_0() in C:\projects\requestplex\src\Ombi\Controllers\JobController.cs:line 85
   at Ombi.Helpers.CacheService.GetOrAdd[T](String cacheKey, Func`1 factory, DateTime absoluteExpiration) in C:\projects\requestplex\src\Ombi.Helpers\CacheService.cs:line 36
   at Ombi.Controllers.JobController.CheckForUpdateCached() in C:\projects\requestplex\src\Ombi\Controllers\JobController.cs:line 80
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 51
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24
```

Version | 3.0.4399
Branch | PR
OS Architecture | X64
OS Description | Linux 4.14.83-gentoo-whatbox #1 SMP Fri Dec 21 03:43:28 UTC 2018
Process Architecture | X64

**Comment by tidusjar** [comment]
This is not really an issue. I need to rework this area
