### ISSUE TITLE
Connection refused in log

### ISSUE THREAD

**Issue by KrunchMuffin** [tidusjar/Ombi#2968]
**Describe the bug**
I am unable to login. I click login with plex and a new window just keeps opening each time.

**To Reproduce**
non, but will work when I am inside the network, but not outside using domain.com/ombi

**Expected behavior**
login with plex

**Screenshots**

**Logs (Logs directory where Ombi is located)**
```
2019-05-02 14:20:56.001 -04:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://plex.tv/users/sign_in.json
2019-05-02 14:20:56.147 -04:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://plex.tv/pms/servers.xml
2019-05-02 14:21:37.560 -04:00 [Warning] Error thrown when attempting to obtain the plex libs
System.Net.Http.HttpRequestException: Connection refused ---> System.Net.Sockets.SocketException: Connection refused
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request) in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
   at Ombi.Api.Plex.PlexApi.GetLibrarySections(String authToken, String plexFullHost) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 120
   at Ombi.Controllers.External.PlexController.GetPlexLibraries(PlexServers settings) in C:\projects\requestplex\src\Ombi\Controllers\External\PlexController.cs:line 109
2019-05-02 14:21:49.368 -04:00 [Warning] Error thrown when attempting to obtain the plex libs
System.Net.Http.HttpRequestException: Connection refused ---> System.Net.Sockets.SocketException: Connection refused
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request) in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
   at Ombi.Api.Plex.PlexApi.GetLibrarySections(String authToken, String plexFullHost) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 120
   at Ombi.Controllers.External.PlexController.GetPlexLibraries(PlexServers settings) in C:\projects\requestplex\src\Ombi\Controllers\External\PlexController.cs:line 109
2019-05-02 14:22:03.808 -04:00 [Warning] Error thrown when attempting to obtain the plex libs
System.Net.Http.HttpRequestException: Connection refused ---> System.Net.Sockets.SocketException: Connection refused
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request) in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
   at Ombi.Api.Plex.PlexApi.GetLibrarySections(String authToken, String plexFullHost) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 120
   at Ombi.Controllers.External.PlexController.GetPlexLibraries(PlexServers settings) in C:\projects\requestplex\src\Ombi\Controllers\External\PlexController.cs:line 109
2019-05-02 14:22:23.802 -04:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://plex.tv/users/sign_in.json
2019-05-02 14:22:23.920 -04:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://plex.tv/pms/servers.xml

```

**Desktop (please complete the following information):**
 - OS: win10

**Ombi Version (please complete the following information):**
 - Version 
- Media Server Plex
- unRaid
- linux.io docker

**Additional context**
I also get a CORB warning in chrome
VM111:1 Cross-Origin Read Blocking (CORB) blocked cross-origin response https://plex.tv/api/v2/pins?strong=true with MIME type text/plain. See https://www.chromestatus.com/feature/5629709824032768 for more details.

**Comment by tidusjar** [comment]
Well this I've not seen,
It looks like Plex is refusing your connection `StatusCode: Unauthorized`. They are returning you a HTTP 401.

Not sure what I can do about this.

**Comment by KrunchMuffin** [comment]
After figuring out how to change to the dev build on unRAID, I did that and it is working now.

**Comment by KrunchMuffin** [comment]
I lied. It is happening again.

**Comment by coyotanark** [comment]
Similar issue for me here. I can login, in media server add the server, use my credentials it will auto-populate the left fields but then when trying to load the libraries I got : 

2019-05-20 00:35:25.351 +01:00 [Warning] Error thrown when attempting to obtain the plex libs
System.Net.Http.HttpRequestException: Connection refused ---> System.Net.Sockets.SocketException: Connection refused
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request) in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
   at Ombi.Api.Plex.PlexApi.GetLibrarySections(String authToken, String plexFullHost) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 120
   at Ombi.Controllers.External.PlexController.GetPlexLibraries(PlexServers settings) in C:\projects\requestplex\src\Ombi\Controllers\External\PlexController.cs:line 109

**Comment by coyotanark** [comment]
Forgot to mention, Ombi is installed with Swizzin behind a Nginx reverse proxy, but Plex is running on another machine on the same local network.

**Comment by coyotanark** [comment]
Ok I got it for me. The auto-completion was filling the public port while trying to connect on the local network which has a different port
