### ISSUE TITLE
Plex TV shows list not syncing

### ISSUE THREAD

**Issue by zmiguel** [tidusjar/Ombi#2983]
**Describe the bug**
On the search page, movies in the library show as available, however, it never syncs the available TV Shows.

**To Reproduce**
Steps to reproduce the behaviour:
1. Try to see available TV Shows
2. They don't sync

**Expected behaviour**
TV Shows should sync the same way movies are syncing.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Ombi Version (please complete the following information):**
- Version 3.0.4256
- Media Server Plex
- Running on Debian LXC

**Comment by tidusjar** [comment]
Logs? 

If you search for a series and press Request > Select ... Are the episodes showing as available?

**Comment by zmiguel** [comment]
If I request an existing TV Show I get a pop-up saying that it already exists, but the button stays with "+ request"

As for logs, I didn't know what to look for, but if the entire file helps I'll upload it.

**Comment by tidusjar** [comment]
That error is strange, but unrelated, can you log out and then back in?

> already exists, but the button stays with "+ request

This is because if you do not have every single episode available then there are episodes that can be requested.

Press the Request then Select ... button to see the episodes that are available and not available
![image](https://user-images.githubusercontent.com/6642220/58005514-b2f0d700-7add-11e9-90a4-dc38d7bc8f59.png)

**Comment by zmiguel** [comment]
It's not because I don't have every episode (I do). As I said before TV shows are not syncing. None of them. Not a single episode.

I've tried everything I found online, and yet they don't sync.

**Comment by tidusjar** [comment]
So you are telling me that when you press the Select ... none of the episodes are appearing as available?

Can you please send me a screenshot of that and also an example of it in your Library.

**Comment by kranzel** [comment]
Hi,

Apologies if this is not the correct way to do this, I have actually never submitted a bug through github before and just started using Ombi.

I am experiencing what appears to be the same thing. Radarr is fine but Sonarr is not syncing properly.

As an example,

I have the entire series of Big Bang Theory. Yet, in Ombi, it shows as available to request. When I select the "Select" option from the the "+Request" item, it shows all the shows as available to be requested. The thing that seems odd though is under status it says "Processing Request". This may be normal, but I am new so not sure.

If I try to add the shows, it says it is already there.

I have attached my logs from the Ombi folder and screenshots.

P.S.
This thing is pretty dang slick overall man. Very nice work.
![Ombi Issue 01](https://user-images.githubusercontent.com/50844532/58045715-e7c65380-7b08-11e9-850f-90b11f14aa13.jpg)
![Ombi Issue 02](https://user-images.githubusercontent.com/50844532/58045716-e85eea00-7b08-11e9-8dc2-c1233e5dbd17.jpg)
![Ombi Issue 03](https://user-images.githubusercontent.com/50844532/58045717-e85eea00-7b08-11e9-8bcc-0e8a8e161942.jpg)
[ombilog.txt](https://github.com/tidusjar/Ombi/files/3199436/ombilog.txt)

**Comment by tidusjar** [comment]
Hi thanks for the post,

Your issue is slightly different. It seems that your sonarr instance is not correctly setup, there are errors in your log about the language profile not being correct. 

Please check if you have a URL base set in sonarr v3, if so you need to set it in the sonarr settings inside ombi.

**Comment by zmiguel** [comment]
His issue is the same I'm having, it's not syncing TV Shows, sonarr or plex, whatever, I'm not sure where ombi gets the information from. The same thing is happening

**Comment by kranzel** [comment]
> Hi thanks for the post,
> 
> Your issue is slightly different. It seems that your sonarr instance is not correctly setup, there are errors in your log about the language profile not being correct.
> 
> Please check if you have a URL base set in sonarr v3, if so you need to set it in the sonarr settings inside ombi.
> 
> Ombi will also look at your media server to determine availability

Hi,

I think it is the same issue, although your point about the V3 error is accurate. I actually don't have V3 of Sonarr installed. However, during my various efforts to fix the issue, I selected the V3 option in my config, just to see if that would help. I suspect that is where the error in reference to the Language settings came from.

Since then though and before that, I was not using the V3 selection. Does that make sense? Or perhaps I am missing something. Which is entirely possible. :)

**Comment by tidusjar** [comment]
@kranzel So when you request and approve a tv show does it end up in Sonarr?

**Comment by kranzel** [comment]
@tidusjar If I request/approve a show I do not have, it works. If I request a show I already have, it says i have it.

Something to note, I checked again today and now things seem to be getting better. By that I mean, shows that i have are starting to appear as already requested/existing.  Not everything, but some of the stuff. 

For example, if I look at "The Big Bang Theory" in the example above, it now shows the status as "Available", instead of "Pending Request" for all but the last episode of Season 12. I suspect when i get home today it might show that episode as available as well.

Is it possible, given that I am running this on a VM and I have a library of roughly 4000 episodes of existing shows, that my VM may be under powered and it is just taking a long time to scan through everything? The VM has 2 CPU and 4GB of RAM.

**Comment by zmiguel** [comment]
For me everything still shows as `Processing Request`, if I add a new tv show it will add it to sonarr.

@kranzel I don't think it's specs, I'm running this on a 24 core dual xeon system and it has been like this for months.

Besides, if it works dor radarr it should also work for sonarr.

**Comment by tidusjar** [comment]
Ok by the fact that it's working when sending to sonarr, it's nothing to do with the Ombi => Sonarr connection.

So it's the Ombi => Plex/Emby connection.

Ombi will scan Plex/Emby periodically for new movies and tv shows.

Please can you ensure you have your tv show library monitored (if you have set any specific libraries) and then run a full manual sync. Wait for a bit and if it's still an issue can you please upload a log file.

**Comment by zmiguel** [comment]
@tidusjar 
Here's my Plex config:

![image](https://user-images.githubusercontent.com/4400540/58127886-53deaf80-7c0e-11e9-81ba-c3fe3470793a.png)

Testing connectivity says it's connected.

After doing the manual sync what should I look for in the logs?

**Comment by tidusjar** [comment]
Any errors, feel free to send me the log file at tidusjar@gmail.com if you can't see anything

**Comment by zmiguel** [comment]
@tidusjar 
I monitored the logfile after doing the manual sync and the inly thing there is this:

```2019-05-21 21:21:29.815 +00:00 [Error] Something bad happened, ErrorMiddleware caught this
System.ArgumentNullException: Value cannot be null.
Parameter name: user
   at Microsoft.AspNetCore.Identity.UserManager`1.IsInRoleAsync(TUser user, String role)
   at Ombi.Core.Engine.Interfaces.BaseEngine.IsInRole(String roleName) in C:\projects\requestplex\src\Ombi.Core\Engine\Interfaces\BaseEngine.cs:line 42
   at Ombi.Core.Engine.BaseMediaEngine.HideFromOtherUsers() in C:\projects\requestplex\src\Ombi.Core\Engine\BaseMediaEngine.cs:line 114
   at Ombi.Core.Engine.MovieRequestEngine.GetRequests() in C:\projects\requestplex\src\Ombi.Core\Engine\MovieRequestEngine.cs:line 243
   at Ombi.Controllers.RequestController.GetRequests() in C:\projects\requestplex\src\Ombi\Controllers\RequestController.cs:line 77
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Ombi.ApiKeyMiddlewear.ValidateApiKey(HttpContext context, RequestDelegate next, String key) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 125
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 34
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24

**Comment by tidusjar** [comment]
Can you please send me over the log file and also the time you think the sync happened?

**Comment by zmiguel** [comment]
@tidusjar I sent you logs by email a few weeks ago, any update on this?

let me know if you want some new ones.

I've also recently updated sonarr to V3 and the problem still remains.

**Comment by zmiguel** [comment]
@tidusjar any updates?

**Comment by tidusjar** [comment]
Hey @zmiguel Unfortunately not. 

I did take a look at the logs and nothing stood out to me of causing any issue regarding this.

The next step would be to send me your OmbiExternal.db so i can investigate if it's a data issue.

**Comment by zmiguel** [comment]
@tidusjar I've sent you today's log and OmbiExternal.db

This log appears to have a lot more sync related info, including TV info, but none of it is displayed on the web page. Status for all TV Shows is still "processing request".

I've also updated to 3.0.4654

Hope this helps.

Thanks.

**Comment by tidusjar** [comment]
Looking at the data, it does seem to have episodes present in your DB.

For example if you search for "Attack on Titan" you will see Ombi has recognized there are episodes available.

There is a concerning error:

```
2019-07-02 14:31:55.888 +00:00 [Error] Something bad happened, ErrorMiddleware caught this
System.ArgumentNullException: Value cannot be null.
Parameter name: user
   at Microsoft.AspNetCore.Identity.UserManager`1.IsInRoleAsync(TUser user, String role)
   at Ombi.Core.Engine.Interfaces.BaseEngine.IsInRole(String roleName) in C:\projects\requestplex\src\Ombi.Core\Engine\Interfaces\BaseEngine.cs:line 42
   at Ombi.Core.Engine.BaseMediaEngine.HideFromOtherUsers() in C:\projects\requestplex\src\Ombi.Core\Engine\BaseMediaEngine.cs:line 114
   at Ombi.Core.Engine.TvRequestEngine.GetRequests() in C:\projects\requestplex\src\Ombi.Core\Engine\TvRequestEngine.cs:line 206
   at Ombi.Controllers.RequestController.GetTvRequests() in C:\projects\requestplex\src\Ombi\Controllers\RequestController.cs:line 252
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Ombi.ApiKeyMiddlewear.ValidateApiKey(HttpContext context, RequestDelegate next, String key) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 125
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 34
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24
```

Which means that Ombi is not recognizing your user for some reason, can you log out and back in?

When you state TV Shows are "processing request", is this for shows that have been requested?

**Comment by zmiguel** [comment]
Just logged out and back in, using both plex auth and the regular email/psw combo, they don't show up on either of the options. I usually log-in with Plex.

the TVShow Dexter was added through a request, it was processed correctly on sonarr and after it was imported the state on ombi kept showing "processing request".

If I search for Attack on Titan the state is also at processing request.

**Comment by tidusjar** [comment]
ok, has the shows been added to Plex? Do you have every episode from that request as available?

**Comment by zmiguel** [comment]
Yes and yes.
![image](https://user-images.githubusercontent.com/4400540/60526108-943e4c80-9ce7-11e9-8873-a9c7444818c1.png)
![image](https://user-images.githubusercontent.com/4400540/60526215-c9e33580-9ce7-11e9-9c92-bf8901825274.png)

![image](https://user-images.githubusercontent.com/4400540/60526139-a61fef80-9ce7-11e9-957d-7b4904264c01.png)
![image](https://user-images.githubusercontent.com/4400540/60526177-b768fc00-9ce7-11e9-9c90-249026dcb032.png)

**Comment by zmiguel** [comment]
If I manually mark it as available it shows up fine. however, shouldn't it detect when the episodes are added?

**Comment by Inrego** [comment]
@zmiguel from my own experience, select your libraries with checkmark in your plex config, and then run sync again.

**Comment by zmiguel** [comment]
@Inrego Tried that, didn't work for me, unfortunately.

**Comment by Inrego** [comment]
Ah ok. It's just that the screenshot you uploaded, all of them were deselected..

**Comment by goldenpipes** [comment]
If your plex token ever changes, you have to re-set up your plex server connection to ombi.  I've had it happen a couple times.  Try deleteing the plex server from ombi, log out, clear cache, log in, set up plex, manually run the cacher.

**Comment by zmiguel** [comment]
@goldenpipes Tried that a few hours after you posted your message and about 10 hours later everything is still at `processing request`. No luck.
