### ISSUE TITLE
Ombi Lidarr Connection not working (Link to this #2845)

### ISSUE THREAD

**Issue by mouzzampk2014** [tidusjar/Ombi#2995]
Hi guys, need your help. TV and Movies working perfectly fine but Music is not. I attached the logs let me know if you need more information. 
Request sent to Lidarr but I can't see any requested Album or Artist in Lidarr.
I am running Ombi in Docker 3.0.4256 
```Hosting environment: Production
Content root path: /opt/ombi
Now listening on: http://[::]:3579
Application started. Press Ctrl+C to shut down.
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server CloudServer
fail: Ombi.Schedule.Jobs.Lidarr.LidarrAlbumSync[2000]
      Failed caching queued items from Lidarr Album
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Schedule.Jobs.Lidarr.LidarrAlbumSync.CacheContent() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Lidarr\LidarrAlbumSync.cs:line 58
fail: Ombi.Api.Api[1000]
      StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://lidarr:8686/lidarr/api/v1/artist
fail: Ombi.Core.Senders.MusicSender[0]
      Exception thrown when sending a music to DVR app, added to the request queue
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Ombi.Api.Lidarr.Models.ArtistResult' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 77
   at Ombi.Core.Senders.MusicSender.SendToLidarr(AlbumRequest model, LidarrSettings settings) in C:\projects\requestplex\src\Ombi.Core\Senders\MusicSender.cs:line 114
   at Ombi.Core.Senders.MusicSender.Send(AlbumRequest model) in C:\projects\requestplex\src\Ombi.Core\Senders\MusicSender.cs:line 42
warn: Ombi.Core.Engine.MusicRequestEngine[0]
      Tried auto sending album but failed. Message: Something went wrong!
warn: Ombi.Core.Engine.MusicRequestEngine[0]
      Tried auto sending Album but failed. Message: Something went wrong!
fail: Ombi.Api.Api[1000]
      StatusCode: BadRequest, Reason: Bad Request, RequestUri: https://api.pushover.net/1/messages.json?token=aropuqf9h81ueki5hkuwzq6bgn3wea&user=uczsa9cnd2swhsqi7j7vddamj7kzr8&priority=0&sound=pushover&message=Hello! The user &amp;#39;abc123&amp;#39; has requested Witness but it could not be added. This has been added into the requests queue and will keep retrying
fail: Ombi.Api.Api[1000]
      StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://lidarr:8686/lidarr/api/v1/artist
fail: Ombi.Core.Senders.MusicSender[0]
      Exception thrown when sending a music to DVR app, added to the request queue
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Ombi.Api.Lidarr.Models.ArtistResult' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 77
   at Ombi.Core.Senders.MusicSender.SendToLidarr(AlbumRequest model, LidarrSettings settings) in C:\projects\requestplex\src\Ombi.Core\Senders\MusicSender.cs:line 114
   at Ombi.Core.Senders.MusicSender.Send(AlbumRequest model) in C:\projects\requestplex\src\Ombi.Core\Senders\MusicSender.cs:line 42
warn: Ombi.Core.Engine.MusicRequestEngine[0]
      Tried auto sending album but failed. Message: Something went wrong!
warn: Ombi.Core.Engine.MusicRequestEngine[0]
      Tried auto sending Album but failed. Message: Something went wrong!
fail: Ombi.Api.Api[1000]
      StatusCode: BadRequest, Reason: Bad Request, RequestUri: https://api.pushover.net/1/messages.json?token=aropuqf9h81ueki5hkuwzq6bgn3wea&user=uczsa9cnd2swhsqi7j7vddamj7kzr8&priority=0&sound=pushover&message=Hello! The user &amp;#39;abc123&amp;#39; has requested PRISM (Acoustic Sessions) but it could not be added. This has been added into the requests queue and will keep retrying

**Comment by tidusjar** [comment]
It seems like that your Lidarr connection might not be setup correctly, have you verified your settings are correct? Including the base url if you have one

**Comment by mouzzampk2014** [comment]
Still not working 
```info: Ombi.Schedule.Jobs.Ombi.RefreshMetadata[0]
      Starting the Metadata refresh from RecentlyAddedSync
fail: Ombi.Api.Api[1000]
      StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://lidarr:8686/lidarr/api/v1/artist
fail: Ombi.Core.Senders.MusicSender[0]
      Exception thrown when sending a music to DVR app, added to the request queue
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Ombi.Api.Lidarr.Models.ArtistResult' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 77
   at Ombi.Core.Senders.MusicSender.SendToLidarr(AlbumRequest model, LidarrSettings settings) in C:\projects\requestplex\src\Ombi.Core\Senders\MusicSender.cs:line 114
   at Ombi.Core.Senders.MusicSender.Send(AlbumRequest model) in C:\projects\requestplex\src\Ombi.Core\Senders\MusicSender.cs:line 42
warn: Ombi.Core.Engine.MusicRequestEngine[0]
      Tried auto sending album but failed. Message: Something went wrong!
warn: Ombi.Core.Engine.MusicRequestEngine[0]
      Tried auto sending Album but failed. Message: Something went wrong!
fail: Ombi.Api.Api[1000]
      StatusCode: BadRequest, Reason: Bad Request, RequestUri: https://api.pushover.net/1/messages.json?token=aropuqf9h8gn3wea&user=uczsa97vddamj7kzr8&priority=0&sound=pushover&message=Hello! The user &amp;#39;mouzzam14&amp;#39; has requested reputation but it could not be added. This has been added into the requests queue and will keep retrying

**Comment by tidusjar** [comment]
One of the errors you previous had is fixed. But you never answered my question above.

**Comment by mouzzampk2014** [comment]
> It seems like that your Lidarr connection might not be setup correctly, have you verified your settings are correct? Including the base url if you have one

Everything setup correctly radarr and sonarr requests go normal its only lidarr playing

**Comment by tidusjar** [comment]
The error you have leads me to believe that the connection between Plex and Lidarr is not fully correct. 

Please double check your API key and base URL if applicable

**Comment by mouzzampk2014** [comment]
Connection is fine but issue is if I already have artist in lidarr then ombi successfully send the request but if artist not already in lidarr then I get above error.

**Comment by mouzzampk2014** [comment]
Now I am getting this one ```info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server CloudServer
fail: Ombi.Schedule.Jobs.Lidarr.LidarrAlbumSync[2000]
      Failed caching queued items from Lidarr Album
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Schedule.Jobs.Lidarr.LidarrAlbumSync.CacheContent() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Lidarr\LidarrAlbumSync.cs:line 58
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server CloudServer
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server CloudServer
fail: Ombi.Schedule.Jobs.Lidarr.LidarrAlbumSync[2000]
      Failed caching queued items from Lidarr Album
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Schedule.Jobs.Lidarr.LidarrAlbumSync.CacheContent() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Lidarr\LidarrAlbumSync.cs:line 58
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server CloudServer
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server CloudServer

**Comment by jneljeff** [comment]
I am experiencing the same issue.  Pulled a fresh image of the linuxserver.io docker container to resolve the original issue.  Now getting this:

```
2019-06-16 09:47:39.719 -05:00 [Error] Something bad happened, ErrorMiddleware caught this
System.ArgumentNullException: Value cannot be null.
Parameter name: entity
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
   at Microsoft.EntityFrameworkCore.DbContext.Remove[TEntity](TEntity entity)
   at Ombi.Store.Repository.BaseRepository`2.Delete(T request) in C:\projects\requestplex\src\$
   at Ombi.Core.Engine.MusicRequestEngine.RemoveAlbumRequest(Int32 requestId) in C:\projects\r$
   at Ombi.Controllers.MusicRequestController.DeleteRequest(Int32 requestId) in C:\projects\re$
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableResultExecutor.Execute(I$
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext $
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope$
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext contex$
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object$
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Ap$
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\$
2019-06-16 09:47:46.790 -05:00 [Error] Something bad happened, ErrorMiddleware caught this
System.ArgumentNullException: Value cannot be null.
Parameter name: entity
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
   at Microsoft.EntityFrameworkCore.DbContext.Remove[TEntity](TEntity entity)
   at Ombi.Store.Repository.BaseRepository`2.Delete(T request) in C:\projects\requestplex\src\$
   at Ombi.Core.Engine.MusicRequestEngine.RemoveAlbumRequest(Int32 requestId) in C:\projects\r$
   at Ombi.Controllers.MusicRequestController.DeleteRequest(Int32 requestId) in C:\projects\re$
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
   at Microsoft.EntityFrameworkCore.DbContext.Remove[TEntity](TEntity entity)
   at Ombi.Store.Repository.BaseRepository`2.Delete(T request) in C:\projects\requestplex\src\$
   at Ombi.Core.Engine.MusicRequestEngine.RemoveAlbumRequest(Int32 requestId) in C:\projects\r$
   at Ombi.Controllers.MusicRequestController.DeleteRequest(Int32 requestId) in C:\projects\re$
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableResultExecutor.Execute(I$
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext $
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope$
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext contex$
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object$
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
  at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Ap$
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\$
2019-06-16 09:48:14.756 -05:00 [Error] StatusCode: BadRequest, Reason: Bad Request, RequestUri$
2019-06-16 09:48:14.766 -05:00 [Error] Exception thrown when sending a music to DVR app, added$
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1$
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change th$
Path '', line 1, position 1.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReade$
 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader,$
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader$
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSet$
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings se$
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:$
   at Ombi.Core.Senders.MusicSender.SendToLidarr(AlbumRequest model, LidarrSettings settings) $
   at Ombi.Core.Senders.MusicSender.Send(AlbumRequest model) in C:\projects\requestplex\src\Om$
2019-06-16 09:48:16.806 -05:00 [Warning] Tried auto sending album but failed. Message: "Someth$
2019-06-16 09:48:16.808 -05:00 [Warning] Tried auto sending Album but failed. Message: "Someth$
2019-06-16 09:48:28.086 -05:00 [Error] Something bad happened, ErrorMiddleware caught this
System.NullReferenceException: Object reference not set to an instance of an object.
 at Ombi.Controllers.RequestRetryController.GetFailedRequests() in C:\projects\requestplex\s$
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Exe$
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext $
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope$
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext contex$
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object$
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Ap$
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\$
2019-06-16 09:49:15.290 -05:00 [Error] Something bad happened, ErrorMiddleware caught this
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Controllers.RequestRetryController.GetFailedRequests() in C:\projects\requestplex\s$
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Exe$
 at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext $
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope$
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext contex$
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object$
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
  at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Ap$
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\$
2019-06-16 09:49:36.888 -05:00 [Error] Something bad happened, ErrorMiddleware caught this
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Controllers.RequestRetryController.GetFailedRequests() in C:\projects\requestplex\s$
   at lambda_method(Closure , Object )


```
