### ISSUE TITLE
Ombi not recognising sonarr

### ISSUE THREAD

**Issue by breichholf** [tidusjar/Ombi#3003]
**Bug**
I have ombi, sonarr and radarr in their own docker containers (no reverse proxy involved) and whenever I enter the values for ombi to talk to sonarr. Clicking on "Test Connection", "Load Qualities", "Load Folders" or "Save" on the page for sonarr only leads to ombi simply reply with "Please check your entered values"

**Screenshots**
![image](https://user-images.githubusercontent.com/7795249/59131752-80ffc180-8973-11e9-8103-9fef1729ee27.png)
![image](https://user-images.githubusercontent.com/7795249/59131762-85c47580-8973-11e9-9baa-1a503afeae1f.png)
![image](https://user-images.githubusercontent.com/7795249/59132117-8f9aa880-8974-11e9-9131-6c446ab17517.png)

**Logs (Logs directory where Ombi is located)**
I would love to add log files, but I despite being logged in as administrator and clicking on every single menu in the settings I can not find them.
The log file in the docker container has not been updated, since some initial run at some point, so I don't think they will be helpful and might lead you down the wrong path.

Mind you, despite it mentioning plex connections this works without a hitch now.
Either way, for what it's worth here is the contents:
```
2019-06-06 01:15:44.288 +02:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://plex.tv/users/sign_in.json
2019-06-06 01:19:32.223 +02:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: http://192.168.0.199:8989/api/profile
2019-06-06 01:19:32.353 +02:00 [Error] Something bad happened, ErrorMiddleware caught this
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[Ombi.Api.Sonarr.Models.S>
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, no>
Path 'error', line 2, position 10.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract >
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 77
   at Ombi.Api.Sonarr.SonarrApi.GetProfiles(String apiKey, String baseUrl) in C:\projects\requestplex\src\Ombi.Api.Sonarr\SonarrApi.cs:line 26
   at Ombi.Controllers.External.SonarrController.GetProfiles(SonarrSettings settings) in C:\projects\requestplex\src\Ombi\Controllers\External\SonarrController.cs:line 40
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller,>
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 51
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24
2019-06-06 01:27:37.731 +02:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://plex.tv/users/sign_in.json
2019-06-06 01:27:37.794 +02:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://plex.tv/pms/servers.xml
2019-06-06 01:27:51.919 +02:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://plex.tv/users/sign_in.json
2019-06-06 01:27:51.983 +02:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://plex.tv/pms/servers.xml
2019-06-06 01:28:21.183 +02:00 [Error] Could not test Plex
System.Net.Http.HttpRequestException: Connection refused ---> System.Net.Sockets.SocketException: Connection refused
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request) in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
   at Ombi.Api.Plex.PlexApi.GetStatus(String authToken, String uri) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 97
   at Ombi.Controllers.External.TesterController.Plex(PlexServers settings) in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 246
```

**Desktop (please complete the following information):**
 - OS: unraid 6.7

**Ombi Version (please complete the following information):**
- Ombi Version: 3.0.4256
- Sonarr Version: 2.0.0.5322

**Comment by tidusjar** [comment]
Regarding logs, check the docker output/logs

**Comment by breichholf** [comment]
@tidusjar Edited the issue to add the logs. The docker output does not show any response when I click on the "Test Connection" button.

**Comment by tidusjar** [comment]
Looking at the logs `Unauthorized, RequestUri: http://192.168.0.199:8989/api/profile`

For some reason Sonarr is rejecting our request even know you have the api key.

Try regenerating the API key in sonarr and then put it into ombi (the new one)

**Comment by breichholf** [comment]
Regenerated the API key and restarted sonarr, still no joy.

I have no JS experience whatsoever, but am considering grabbing an npm sonarr_api wrapper to test sonarr in some manner.

**Comment by tidusjar** [comment]
What you could do is just call the API from your browser:
`"192.168.0.199:8989/api/series/lookup?term=The%20Blacklist&apikey=YOURAPIKEY"`
To see if we get a response

**Comment by breichholf** [comment]
Ah nice. That works fine and gives me the expected json response.

**Comment by tidusjar** [comment]
Can you upload new logs with the result with the new api key?

**Comment by breichholf** [comment]
Is there any way I can force ombi to create a new log file? It hasn't created a new one since yesterday.

**Comment by tidusjar** [comment]
There should be an output in the logs button in unraid for that container

**Comment by breichholf** [comment]
So I was fiddling around on unraid, and it turns out the cache drive was almost full. For some bizarre reason cleaning the cash drive out of unnecessary stuff lead to ombi working fine now.

**Comment by breichholf** [comment]
One minor
