### ISSUE TITLE
'UNIQUE constraint failed: ApplicationConfiguration.Id' after upgrade

### ISSUE THREAD

**Issue by davidvermillion** [tidusjar/Ombi#3022]
**Describe the bug**
Program won't start

**To Reproduce**
Try to start the program

**Expected behavior**
The program to start

**Screenshots**
Its a command line, there are no screenshots

**Logs (Logs directory where Ombi is located)**
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> Microsoft.Data.Sqlite.SqliteException: SQLite Error 19: 'UNIQUE constraint failed: ApplicationConfiguration.Id'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(DbContext _, ValueTuple`2 parameters)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Ombi.Program.CheckAndMigrate() in C:\projects\requestplex\src\Ombi\Program.cs:line 135

Unhandled Exception: Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> Microsoft.Data.Sqlite.SqliteException: SQLite Error 19: 'UNIQUE constraint failed: ApplicationConfiguration.Id'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(DbContext _, ValueTuple`2 parameters)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Ombi.Program.CheckAndMigrate() in C:\projects\requestplex\src\Ombi\Program.cs:line 135
   at Ombi.Program.Main(String[] args) in C:\projects\requestplex\src\Ombi\Program.cs:line 53
Aborted (core dumped)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-51-generic x86_64)

**Ombi Version (please complete the following information):**
- Version: Ombi 3.0.4256-master
- Media Server: It doesn't matter cause it WONT START

**Additional context**
Happen regardless of whether I use the service or try to start from the command line.

**Comment by tidusjar** [comment]
Is this just started happening? Can you please give a bit of background info on this issue...

**Comment by davidvermillion** [comment]
> Is this just started happening? Can you please give a bit of background info on this issue...

Well, the auto update script wasn't doing anything, and it seems the repo got disabled (maybe when I did an OS upgrade) so I added the repo key back and did the apt update. 

After the update it seems like it overwrote my db (based on file size,) so I copied my backed up ombi.db file and tried to start and that's when I got the error.

**Comment by tidusjar** [comment]
Do you know what version you went from?

**Comment by davidvermillion** [comment]
I can't say, but it would have been around Oct 2018 since it last upgraded.

**Comment by tidusjar** [comment]
Yeah that was a while ago,

If you want, send me your database and i'll fix the issue manually and send it back to you

tidusjar@gmail.cokm
