### ISSUE TITLE
[Lidarr] View albums does nothing

### ISSUE THREAD

**Issue by Phault** [tidusjar/Ombi#3027]
**Describe the bug**
Searching for an artist and then clicking "View albums" disables the button and logs an "Internal server error" to the console.

This is due to the API for this call [circumventing the Lidarr server](https://github.com/tidusjar/Ombi/blob/1cf1c06e5ea94d32c653fa405d22b840604ba4e8/src/Ombi.Api.Lidarr/LidarrApi.cs#L87), and instead requests it directly from the LidarrMetadata service at _api.lidarr.audio/api/v0.3/_. This however no longer works as that API endpoint has been bumped to v0.4.

**To Reproduce**
1. Go to 'Music'
2. Search for an artist e.g. 'Mercenary'
3. Click 'View albums'
4. Check console

**Expected behavior**
It should show the artist's albums.

**Logs (Logs directory where Ombi is located)**
```
fail: Ombi.Api.Api[1000]
      StatusCode: NotFound, Reason: Not Found, RequestUri: https://api.lidarr.audio/api/v0.3/artist/c8be81ab-b536-4499-9d16-da997125e942
fail: Ombi.ErrorHandlingMiddleware[0]
      Something bad happened, ErrorMiddleware caught this
Newtonsoft.Json.JsonSerializationException: Error converting value 404 to type 'Ombi.Api.Lidarr.Models.AlbumByArtistResponse'. Path '', line 1, position 3. ---> System.ArgumentException: Could not cast or convert from System.Int64 to Ombi.Api.Lidarr.Models.AlbumByArtistResponse.
   at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
   at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 77
   at Ombi.Core.Engine.MusicSearchEngine.GetArtistAlbums(String foreignArtistId) in C:\projects\requestplex\src\Ombi.Core\Engine\MusicSearchEngine.cs:line 90
   at Ombi.Controllers.SearchController.GetAlbumsByArtist(String foreignArtistId) in C:\projects\requestplex\src\Ombi\Controllers\SearchController.cs:line 382
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 51
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24
```

**Desktop (please complete the following information):**
 - OS: Docker image linuxserver/docker-ombi Linux 4.4.59+

**Ombi Version (please complete the following information):**
 - 3.0.4256
 - Plex

**Comment by tidusjar** [comment]
This has been fixed in the develop branch! 🎉 🎈
