### ISSUE TITLE
Ombi not pulling from PLEX Server

### ISSUE THREAD

**Issue by phaelon74** [tidusjar/Ombi#3033]
**Describe the bug**
Configuration of the Plex server is all good including I tell it to test connectivity and it's happy.  it however NEVER pulls a list of movies the plex Server has.  i tell it to manually sync and it says it's going too, but nothing ever updates.  I tell it to do a recent download sync but it still doesn't update anything

**To Reproduce**
Fresh install of OMBI so nothing to really replicate.

**Expected behavior**
It pulls from Plex all the movies and TV is has and then updates it's database.

**Screenshots**
N/A

**Logs (Logs directory where Ombi is located)**
2019-06-21 00:52:10.868 +00:00 [Debug] Batch acquisition of 1 triggers
2019-06-21 00:52:10.869 +00:00 [Debug] Batch acquisition of 0 triggers
2019-06-21 00:52:10.869 +00:00 [Debug] Calling Execute on job Plex.IPlexContentSync
2019-06-21 00:52:10.871 +00:00 [Information] Starting Plex Content Cacher
2019-06-21 00:52:10.871 +00:00 [Information] Starting to cache the content on server "PLEXBOX01"
2019-06-21 00:52:10.871 +00:00 [Debug] Getting all content from server "PLEXBOX01"
2019-06-21 00:52:10.879 +00:00 [Debug] {"MediaContainer":{"size":5,"allowSync":false,"identifier":"com.plexapp.plugins.library","mediaTagPrefix":"/system/bundle/media/flags/","mediaTagVers$
2019-06-21 00:52:11.009 +00:00 [Error] StatusCode: InternalServerError, Reason: Internal Server Error, RequestUri: https://10.1.1.201:32400/library/sections/2/all
2019-06-21 00:52:11.010 +00:00 [Debug] <html><head><title>Internal Server Error</title></head><body><h1>500 Internal Server Error</h1></body></html>
2019-06-21 00:52:11.010 +00:00 [Debug] <html><head><title>Internal Server Error</title></head><body><h1>500 Internal Server Error</h1></body></html>
2019-06-21 00:52:11.013 +00:00 [Warning] Exception thrown when attempting to cache the Plex Content in server "PLEXBOX01"
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 78
   at Ombi.Api.Plex.PlexApi.GetLibrary(String authToken, String plexFullHost, String libraryId) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 127
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.GetAllContent(PlexServers plexSettings, Boolean recentlyAddedSearch) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs$
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessServer(PlexServers servers, Boolean recentlyAddedSearch) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line$
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.StartTheCache(PlexSettings plexSettings, Boolean recentlyAddedSearch) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.c$
2019-06-21 00:52:11.014 +00:00 [Information] Starting EP Cacher
2019-06-21 00:52:11.015 +00:00 [Debug] Batch acquisition of 1 triggers
2019-06-21 00:52:11.015 +00:00 [Error] Job Plex.IPlexContentSync threw an unhandled Exception:
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.Execute(IJobExecutionContext context) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 119
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
2019-06-21 00:52:11.015 +00:00 [Error] Job Plex.IPlexContentSync threw an exception.
Quartz.SchedulerException: Job threw an unhandled exception. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.Execute(IJobExecutionContext context) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 119
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
2019-06-21 00:52:11.015 +00:00 [Error] Job Plex.IPlexContentSync threw an exception.
Quartz.SchedulerException: Job threw an unhandled exception. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.Execute(IJobExecutionContext context) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 119
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
   --- End of inner exception stack trace --- [See nested exception: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.Execute(IJobExecutionContext context) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 119
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)]
2019-06-21 00:52:11.015 +00:00 [Debug] Batch acquisition of 0 triggers
2019-06-21 00:52:11.016 +00:00 [Debug] Calling Execute on job Plex.IPlexEpisodeSync
2019-06-21 00:52:11.018 +00:00 [Debug] Trigger instruction : DeleteTrigger
2019-06-21 00:52:11.018 +00:00 [Debug] Deleting trigger
2019-06-21 00:52:11.024 +00:00 [Debug] {"MediaContainer":{"size":5,"allowSync":false,"identifier":"com.plexapp.plugins.library","mediaTagPrefix":"/system/bundle/media/flags/","mediaTagVers$
2019-06-21 00:52:11.025 +00:00 [Debug] Trigger instruction : DeleteTrigger
2019-06-21 00:52:11.025 +00:00 [Debug] Batch acquisition of 1 triggers
2019-06-21 00:52:11.025 +00:00 [Debug] Deleting trigger
2019-06-21 00:52:11.026 +00:00 [Debug] Batch acquisition of 0 triggers
2019-06-21 00:52:11.026 +00:00 [Debug] Calling Execute on job Plex.IPlexAvailabilityChecker
2019-06-21 00:52:11.031 +00:00 [Debug] Trigger instruction : DeleteTrigger
2019-06-21 00:52:11.031 +00:00 [Debug] Deleting trigger
2019-06-21 00:52:36.452 +00:00 [Debug] Batch acquisition of 0 triggers
2019-06-21 00:53:03.161 +00:00 [Debug] Batch acquisition of 0 triggers
2019-06-21 00:53:27.117 +00:00 [Debug] Batch acquisition of 0 triggers

**Desktop (please complete the following information):**
Linux 4.15.0-47-generic Ubuntu 
Ubuntu 18.04.2 LTS

**Ombi Version (please complete the following information):**
ombi:amd64/jessie 3.0.4639 uptodate
PLEX - Version 3.104.1

**Comment by phaelon74** [comment]
When I open a web browser and go directly to the plex box , I get the 500 Internal Error.  Here is the command I am using, which is what OMBI uses:
https://10.REDACTED:32400/library/sections/2/all?X-Plex-Token=REDACTED

So why is my Plex bos pissed by this ask?

**Comment by tidusjar** [comment]
That's a Plex issue. Your going to have to contact Plex about that.

**Comment by phaelon74** [comment]
I wanted to add additional information here, in case anyone finds themselves in a similar spot.  SQLlite on the Plex box was throwing errors, about Temp files being corrupt.  Plex support stated you need to run SQLlite commands to resolve  the corrupt DB.  Running their analyze commands, our DB was not corrupt, but Plex Support also said even if it says no corrupt, you still might need to fix it.

Instead, we stopped the plex services and then restarted them.  Once back up these problems went away completely.  Here's what we think happened.

We had 3 libraries that were added and then removed.  Plex names libraries by numbers, but NEVER re-uses a number.  Our temp files still had the numbers as valid libraries.  When Ombi went to read them however, the libraries didn't actually exist, and then it bombed.  Basically plex told Ombi "I have 7 libraries" and then when Ombi went to read library number 3,4 and 6, they weren't there and plex threw back a 500 error basically saying "that stuff doesn't exist yo".

So yeah, restarted plex service, which must have deleted/purged temp files and now we are in business, aside from the newsletter not automatically going out, but I'll open a new issue for that.

**Comment by tidusjar** [comment]
yeah sorry about that, I don't know the internal workings of Plex. Glad you got it sorted.
