### ISSUE TITLE
Processing Request Ombi Version 3.0.4256

### ISSUE THREAD

**Issue by bluasoar** [tidusjar/Ombi#3040]
**Describe the bug**
Requesting Movies/Shows on Ombi and it just says "Processing Request" I've setup Radarr and Sonarr they have my Root Folders Quality settings etc. And connection says successful.

**To Reproduce**
Not too sure how to reproduce.

**Expected behavior**
Request Movie/Show --> Approve --> Download.

**Screenshots**

**Logs (Logs directory where Ombi is located)**
2019-06-27 00:36:06.029 -04:00 [Error] Something bad happened, ErrorMiddleware caught this
System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request) in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
   at Ombi.Api.TheMovieDb.TheMovieDbApi.PopularMovies(String langageCode) in C:\projects\requestplex\src\Ombi.TheMovieDbApi\TheMovieDbApi.cs:line 132
   at Ombi.Core.Engine.MovieSearchEngine.<PopularMovies>b__15_0() in C:\projects\requestplex\src\Ombi.Core\Engine\MovieSearchEngine.cs:line 123
   at Ombi.Helpers.CacheService.GetOrAdd[T](String cacheKey, Func`1 factory, DateTime absoluteExpiration)
   at Ombi.Core.Engine.MovieSearchEngine.PopularMovies() in C:\projects\requestplex\src\Ombi.Core\Engine\MovieSearchEngine.cs:line 120
   at Ombi.Controllers.SearchController.Popular() in C:\projects\requestplex\src\Ombi\Controllers\SearchController.cs:line 194
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Ombi Version (please complete the following information):**
 - Version 3.0.4256
 - Media Server Version 3.95.2

**Comment by bluasoar** [comment]
New Issue

**Comment by tidusjar** [comment]
?
