### ISSUE TITLE
Ombi updater - attempt 2

### ISSUE THREAD

**Issue by jonnwhite1** [tidusjar/Ombi#3058]
**Describe the bug**
Using check for updates and then clicking update results in the below error

**To Reproduce**
1. Go to System
2. Click on Update
3. Click Check for update/update

**Expected behavior**
update to initiate

**Screenshots**

fail: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[0]
      Exception thrown in the OmbiUpdater, see previous messages
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Ombi\TempUpdate\cypress\'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, String destinationFileName, Boolean overwrite)
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.Extract(String zipDir, String tempPath) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 300
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.Update(PerformContext c) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 198

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Win 10

**Ombi Version (please complete the following information):**
 - Version 3.0.4256
- Media Server Plex

**Additional context**

**Comment by goldenpipes** [comment]
the updater is completely broken at this time.
