### ISSUE TITLE
Lidarr Exception Thrown in Logs

### ISSUE THREAD

**Issue by jimmarks** [tidusjar/Ombi#3069]
**Describe the bug**
When requesting albums from Ombi via Lidarr, it shows an error.

**Logs (Logs directory where Ombi is located)**
2019-07-16 06:21:36.127 -07:00 [Error] StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://plexrequests.marksemails.com:38083/api/v1/artist
2019-07-16 06:21:36.404 -07:00 [Error] Exception thrown when sending a music to DVR app, added to the request queue
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Ombi.Api.Lidarr.Models.ArtistResult' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 78
   at Ombi.Core.Senders.MusicSender.SendToLidarr(AlbumRequest model, LidarrSettings settings) in C:\projects\requestplex\src\Ombi.Core\Senders\MusicSender.cs:line 120
   at Ombi.Core.Senders.MusicSender.Send(AlbumRequest model) in C:\projects\requestplex\src\Ombi.Core\Senders\MusicSender.cs:line 43
2019-07-16 06:21:36.543 -07:00 [Warning] Tried auto sending album but failed. Message: "Something went wrong!"
2019-07-16 06:21:36.543 -07:00 [Warning] Tried auto sending Album but failed. Message: "Something went wrong!"

**Desktop (please complete the following information):**
 Windows 10 (Both Ombi and Libarr, separate boxes though)

**Ombi Version (please complete the following information):**
Latest versions across the board.

**Comment by tidusjar** [comment]
Please double check your settings including your base url if present.

**Comment by jimmarks** [comment]
All the settings in Ombi and Lidarr are correctly set.  In Ombi I am currently successfully getting and processing requests for Sonarr and CouchPotato.  

I notice however that the directory that is referenced in the log actually doesn't exist at all.  I'm not sure where that is set, but its not in Ombi.

**Comment by tidusjar** [comment]
The directory is just where ombi was compiled, you can ignore that. 

The error you are facing is usually caused by some sort of error with your settings. Can you please post a screenshot of them?

Also double check your API key is correct

**Comment by jimmarks** [comment]
Here is libarr:

![2019-07-17_8-54-55](https://user-images.githubusercontent.com/17133893/61377264-e008fe00-a870-11e9-99bb-5b5004ecccf9.png)

Here is Ombi:
![2019-07-17_8-55-35](https://user-images.githubusercontent.com/17133893/61377315-f44cfb00-a870-11e9-9648-ff2c9f536c98.png)

**Comment by tidusjar** [comment]
The metadata profile is empty?

**Comment by jimmarks** [comment]
Interesting.  I clicked Get Metadata 4 or 5 times, and it finally populated with an option to drop down to standard.  I've filled that in.  I am now not getting an error from Ombi anymore.  Thank you for pointing that out.  I feel completely stupid.

**Comment by tidusjar** [comment]
No problem :)
