### ISSUE TITLE
NullReferenceException: Attempting to add TV show to the request queue

### ISSUE THREAD

**Issue by JordanReich** [tidusjar/Ombi#3077]
**Describe the bug**
When attempting to add any TV show to the request queue I am getting an application error that says something wrong occurred when attempting to process your request.

**To Reproduce**
1. Find any TV show
2. Attempt to add the TV show

**Expected behavior**
A TV show request is added and than submitted to Sickrage for processing.

**Screenshots**
N/A

**Logs (Logs directory where Ombi is located)**
`2019-07-17 10:47:13.772 -07:00 [Error] Exception thrown when sending a movie to DVR app, added to the request queue
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Core.Senders.TvSender.SendToSickRage(ChildRequests model, SickRageSettings settings, String qualityId) in C:\projects\requestplex\src\Ombi.Core\Senders\TvSender.cs:line 484
   at Ombi.Core.Senders.TvSender.Send(ChildRequests model) in C:\projects\requestplex\src\Ombi.Core\Senders\TvSender.cs:line 91
2019-07-17 10:51:01.269 -07:00 [Error] Exception thrown when sending a movie to DVR app, added to the request queue
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Core.Senders.TvSender.SendToSickRage(ChildRequests model, SickRageSettings settings, String qualityId) in C:\projects\requestplex\src\Ombi.Core\Senders\TvSender.cs:line 484
   at Ombi.Core.Senders.TvSender.Send(ChildRequests model) in C:\projects\requestplex\src\Ombi.Core\Senders\TvSender.cs:line 91`

**Desktop (please complete the following information):**
 - OS: Windows 10

**Ombi Version (please complete the following information):**
- Version 3.0.4256
- Media Server Plex
- Sickrage Version 9.4.143.dev1

**Additional context**
N/A

**Comment by tidusjar** [comment]
What do your sickrage settings look like?
