### ISSUE TITLE
Unable to send email after successful test

### ISSUE THREAD

**Issue by the-Dakta** [tidusjar/Ombi#3096]
**Describe the bug**
I am unable to send a welcome email, or mass email. When configuring the email notification settings the test email sent just fine, and I did not change any settings. Any subsequent test emails no longer go through either.

**To Reproduce**
1. Go to User Management
2. Click on "Send Welcome Email" for any user

**Expected behavior**
I expected that after successfully sending a test email, that any of the other emails should have gone through fine.

**Logs (Logs directory where Ombi is located)**
`2019-07-30 17:03:49.035 -05:00 [Error] Exception when attempting to send an email
System.ArgumentException: The domain is invalid.
Parameter name: domain
   at MimeKit.Utils.MimeUtils.GenerateMessageId(String domain)
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings)
2019-07-30 17:03:49.037 -05:00 [Warning] Exception when testing Email Notifications
System.ArgumentException: The domain is invalid.
Parameter name: domain
   at MimeKit.Utils.MimeUtils.GenerateMessageId(String domain)
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings)
   at Ombi.Controllers.External.TesterController.Email(EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 251
2019-07-30 17:04:01.418 -05:00 [Debug] Batch acquisition of 0 triggers
2019-07-30 17:04:27.300 -05:00 [Debug] Batch acquisition of 0 triggers
2019-07-30 17:04:35.403 -05:00 [Error] Exception when attempting to send an email
System.ArgumentException: The domain is invalid.
Parameter name: domain
   at MimeKit.Utils.MimeUtils.GenerateMessageId(String domain)
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings)
2019-07-30 17:04:35.404 -05:00 [Warning] Exception when testing Email Notifications
System.ArgumentException: The domain is invalid.
Parameter name: domain
   at MimeKit.Utils.MimeUtils.GenerateMessageId(String domain)
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings)
   at Ombi.Controllers.External.TesterController.Email(EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 251`

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.0.4.2

**Ombi Version (please complete the following information):**
 - Version 3.0.4680
- Media Server: Plex

I've included only what looks like relevant errors from the logs so as to avoid posting too many identifying email addresses.

**Comment by tidusjar** [comment]
It's complaining about the domain (probably on the recipient). Can you ensure you are using correct email addresses?

**Comment by the-Dakta** [comment]
Yes, it's my email address, I used an app specific password for Google, and nothing has changed since the test email worked. 

I saw other people in the past mention that their emails were getting flagged as spam on the backend. Could that cause this error? If so, is there a solution?

**Comment by tidusjar** [comment]
No that is not the problem. So the recipient email is correct? And the sender, alias and such in the settings also look correct?

**Comment by the-Dakta** [comment]
All of the settings are correct, because they worked to send the first test email. Now I am no longer even able to send a test email (sending to my email address), let alone any other emails.

**Comment by tidusjar** [comment]
Have you set an application url in your settings? Is that a valid domain>

**Comment by the-Dakta** [comment]
Oh shit that was exactly it!

Thanks!

**Comment by tidusjar** [comment]
We set the `X-Message-Id` property on the Mime Message to the domain you set in there. That makes sense now! :)

**Comment by gbdavidx** [comment]
I cant send emails out either, what do you mean by this? Have you set an application url in your settings? Is that a valid domain?

**Comment by abendel** [comment]
@tidusjar im Stil having issues sending emails on v4:

fail: Ombi.Notifications.GenericEmailProvider[0]                                                                                            
      Exception when attempting to send an email                                                                                            
System.ArgumentException: The domain is invalid. (Parameter 'domain')                                                                       
   at MimeKit.Utils.MimeUtils.GenerateMessageId(String domain)                                                                              
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings) in /home/vsts/work/1/
s/src/Ombi.Notifications/GenericEmailProvider.cs:line 47                                                                                    
warn: Ombi.Controllers.V1.External.TesterController[0]                                                                                      
      Exception when testing Email Notifications                                                                                            
System.ArgumentException: The domain is invalid. (Parameter 'domain')                                                                       
   at MimeKit.Utils.MimeUtils.GenerateMessageId(String domain)                                                                              
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings) in /home/vsts/work/1/
s/src/Ombi.Notifications/GenericEmailProvider.cs:line 47                                                                                    
   at Ombi.Controllers.V1.External.TesterController.Email(EmailNotificationSettings settings) in /home/vsts/work/1/s/src/Ombi/Controllers/V1
/External/TesterController.cs:line 284                                                                                                      


Any help here?
