### ISSUE TITLE
Issues searching for Movies

### ISSUE THREAD

**Issue by jonnwhite1** [tidusjar/Ombi#3117]
**Describe the bug**
Having issues when searching for movies. No results are returned and JSON error logged in the console. Error has started in the past hour or so. Experiencing the exact same error in Radarr so not sure if something is down? 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to home
2. Click on movies
3. Search for movie

**Expected behaviour**
Movie results appear

**Screenshots**

**Logs (Logs directory where Ombi is located)**
fail: Ombi.Api.Api[1000]
      StatusCode: ServiceUnavailable, Reason: Service Temporarily Unavailable, RequestUri: http://api.themoviedb.org/3/search/movie?api_key=b8eabaf5608b88d0298aa189dd90bf00&query=harry&language=en
fail: Ombi.ErrorHandlingMiddleware[0]
      Something bad happened, ErrorMiddleware caught this
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: b. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 78
   at Ombi.Api.TheMovieDb.TheMovieDbApi.SearchMovie(String searchTerm, Nullable`1 year, String langageCode) in C:\projects\requestplex\src\Ombi.TheMovieDbApi\TheMovieDbApi.cs:line 122
   at Ombi.Core.Engine.MovieSearchEngine.Search(String search, Nullable`1 year, String langaugeCode) in C:\projects\requestplex\src\Ombi.Core\Engine\MovieSearchEngine.cs:line 60
   at Ombi.Controllers.SearchController.SearchMovie(SearchMovieRefineModel model) in C:\projects\requestplex\src\Ombi\Controllers\SearchController.cs:line 108
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 51
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24

**Desktop (please complete the following information):**
 - OS: Windows 10 1903

**Ombi Version (please complete the following information):**
 - Version3.0.4680
- Media Server Plex 

**Additional context**

**Comment by StuDaBaiker** [comment]
Having the same issue with movie searching, however I am able to search through radarr

**Comment by goku-son** [comment]
Same issue here

**Comment by dpiper01** [comment]
TMDB is down, you could follow their Twitter to know when it's back up. @themoviedb

**Comment by jonnwhite1** [comment]
All good now :) I wasn’t sure if it was that or not!

**Comment by jonnwhite1** [comment]
All good now :) I wasn’t sure if it was that or not!
