### ISSUE TITLE
No search results for movies, can't request any media type

### ISSUE THREAD

**Issue by tzw9373** [tidusjar/Ombi#3118]
**Describe the bug**
When searching for movies in the Ombi request search bar, no results show. When searching for tv shows, results show but no requests can be submitted. 

**To Reproduce**
1. Go to Search
2. Click on "Type here to search"
3. Type search query and hit Enter or click magnifying glass
4. For movies: nothing happens. For TV: click "Request", nothing happens. 

**Expected behavior**
For both movies and tv shows results should show and requests should be logged and completed. 

**Screenshots**
![image](https://user-images.githubusercontent.com/50788362/63063397-0f3b7b00-bec2-11e9-8e04-9179700122d1.png)

![image](https://user-images.githubusercontent.com/50788362/63063420-2d08e000-bec2-11e9-98b7-3044cf41e31c.png)

![image](https://user-images.githubusercontent.com/50788362/63063448-56c20700-bec2-11e9-8439-2715cdc5e990.png)

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

C:\ombi\Logs

2019-08-14 18:32:53.790 -05:00 [Error] StatusCode: ServiceUnavailable, Reason: Service Temporarily Unavailable, RequestUri: http://api.themoviedb.org/3/search/movie?api_key=b8eabaf5608b88d0298aa189dd90bf00&query=carrie&language=en
2019-08-14 18:32:53.857 -05:00 [Error] Something bad happened, ErrorMiddleware caught this
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: b. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 78
   at Ombi.Api.TheMovieDb.TheMovieDbApi.SearchMovie(String searchTerm, Nullable`1 year, String langageCode) in C:\projects\requestplex\src\Ombi.TheMovieDbApi\TheMovieDbApi.cs:line 122
   at Ombi.Core.Engine.MovieSearchEngine.Search(String search, Nullable`1 year, String langaugeCode) in C:\projects\requestplex\src\Ombi.Core\Engine\MovieSearchEngine.cs:line 60
   at Ombi.Controllers.SearchController.SearchMovie(SearchMovieRefineModel model) in C:\projects\requestplex\src\Ombi\Controllers\SearchController.cs:line 108
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 51
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro

**Ombi Version (please complete the following information):**
 - Version 3.0.4680
- Media Server: Plex

**Additional context**

**Comment by dpiper01** [comment]
TMDB is down, you could follow their Twitter to know when it's back up. @themoviedb
