### ISSUE TITLE
base url on initial setup does not work

### ISSUE THREAD

**Issue by paulbovbel** [tidusjar/Ombi#3130]
**Describe the bug**
I'm having a hard time bringing up ombi from scratch. At first startup, I skip the initial media server config and setup and admin account. At this point when I log in, I notice that all my settings are blank (even the default ombi settings like base url and API key), and no changes get persisted.

I also can't connect to plex or sonarr or radarr using the 'Test Connection' buttons.

**To Reproduce**
1. Create a docker container with the provided compose snippet.
2. Start container and make an admin account via the wizard.
3. Login and go into settings.
4. Nothing works.
5. To retry, stop and remove the docker container, and remove the local config folder including the db.

**Expected behavior**
- See the base url
- able to change and commit settings

**Logs (Logs directory where Ombi is located)**
```
Application startup exception: System.InvalidOperationException: The instance of entity type 'GlobalSettings' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Nullable`1 forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode node, Boolean force)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode node, TState state, Func`3 handleNode)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
   at Ombi.Store.Repository.SettingsJsonRepository.Update(GlobalSettings entity) in C:\projects\requestplex\src\Ombi.Store\Repository\SettingsJsonRepository.cs:line 100
   at Ombi.Settings.Settings.SettingsService`1.SaveSettings(T model) in C:\projects\requestplex\src\Ombi.Settings\Settings\SettingsService.cs:line 91
   at Ombi.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IMemoryCache cache, IServiceProvider serviceProvider) in C:\projects\requestplex\src\Ombi\Startup.cs:line 174
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

Unhandled Exception: System.InvalidOperationException: The instance of entity type 'GlobalSettings' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Nullable`1 forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode node, Boolean force)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode node, TState state, Func`3 handleNode)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
   at Ombi.Store.Repository.SettingsJsonRepository.Update(GlobalSettings entity) in C:\projects\requestplex\src\Ombi.Store\Repository\SettingsJsonRepository.cs:line 100
   at Ombi.Settings.Settings.SettingsService`1.SaveSettings(T model) in C:\projects\requestplex\src\Ombi.Settings\Settings\SettingsService.cs:line 91
   at Ombi.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IMemoryCache cache, IServiceProvider serviceProvider) in C:\projects\requestplex\src\Ombi\Startup.cs:line 174
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at Ombi.Program.Main(String[] args) in C:\projects\requestplex\src\Ombi\Program.cs:line 119
```

**Desktop (please complete the following information):**
ubuntu bionic + docker
```
    ombi:
      image: linuxserver/ombi
      container_name: ombi
      networks:
        - media
      environment:
        - "PUID={{ uid }}"
        - "PGID={{ gid }}"
        - "TZ=America/Toronto"
        - BASE_URL=/ombi
      volumes:
        - "{{ app_folder }}/ombi:/config"
      restart: unless-stopped
```

**Ombi Version (please complete the following information):**
Ombi 3.0.4680-master

**Comment by paulbovbel** [comment]
Seems to be related to https://github.com/tidusjar/Ombi/issues/2170#issuecomment-383380244

**Comment by tidusjar** [comment]
Does it only happen when specifying a base URL on startup?

**Comment by paulbovbel** [comment]
Yes, I've dropped the BASE_URL env var and everything works as expected.
