### ISSUE TITLE
Ombi v3.0.4680 can't send TV Show request to Sonarr V3.0.3.616

### ISSUE THREAD

**Issue by mcescoli** [tidusjar/Ombi#3132]
**Describe the bug**
Ombi seems to be able to connect to Sonarr v3 but for some reason it is unable to send a TV show request.

**To Reproduce**
1. In Ombi, request to download a TV show so that it sends to Sonarr.
2. Go to Sonarr.
3. Go to System and click Events.
4. You will then see the error in question.

**Expected behavior**
You should see that after sending the request to download a TV show from Ombi, Sonarr should then add the series to the list and start searching for available media.

**Screenshots**
Not needed.

**Logs (Logs directory where Ombi is located)**

`System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Core.Helpers.TvShowRequestBuilder.GetShowInfo(Int32 id) in C:\projects\requestplex\src\Ombi.Core\Helpers\TvShowRequestBuilder.cs:line 42
   at Ombi.Core.Engine.TvRequestEngine.RequestTvShow(TvRequestViewModel tv) in C:\projects\requestplex\src\Ombi.Core\Engine\TvRequestEngine.cs:line 55
   at Ombi.Controllers.RequestController.RequestTv(TvRequestViewModel tv) in C:\projects\requestplex\src\Ombi\Controllers\RequestController.cs:line 285
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 51
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24`

**Desktop (please complete the following information):**
 - Windows 10 Professional (Version 1903 Build 18362.295)

**Ombi Version (please complete the following information):**
 - Ombi v3.0.4680
 - Plex Media Server
 - Sonarr v3.0.3.616

**Additional context**
For Sonarr V3 logs, I get the following error every time i try to send a TV show request from Ombi;

Invalid request Validation failed: 
 -- Path: Invalid Path
 -- RootFolderPath: Invalid Path

This is all I ever get.

**Comment by tidusjar** [comment]
Hello, Please use the Github template to report an issue. If this is a feature request, please take a look at the readme.
Thanks,

**Comment by MikesTooLz** [comment]
I'm having this same issue with Radarr.

**Comment by almulder** [comment]
I am having the same issue with Ombi not sending to Sonarr or Lidarr, but it works with Radarr.
Ombi v3.0.4817
Sonarr v3.0.3.6.44
Lidarr v0.7.1.1381
Radarr v0.2.0.1358

Ombi Log when trying to get music to lidarr:
`2019-10-18 10:56:44.743 -07:00 [Error] StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://10.1.10.230:8686/api/v1/artist
2019-10-18 10:56:44.744 -07:00 [Error] Exception thrown when sending a music to DVR app, added to the request queue
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Ombi.Api.Lidarr.Models.ArtistResult' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 78
   at Ombi.Core.Senders.MusicSender.SendToLidarr(AlbumRequest model, LidarrSettings settings) in C:\projects\requestplex\src\Ombi.Core\Senders\MusicSender.cs:line 119
   at Ombi.Core.Senders.MusicSender.Send(AlbumRequest model) in C:\projects\requestplex\src\Ombi.Core\Senders\MusicSender.cs:line 43
2019-10-18 10:56:44.798 -07:00 [Warning] Tried auto sending album but failed. Message: "Something went wrong!"
2019-10-18 10:56:44.798 -07:00 [Warning] Tried auto sending Album but failed. Message: "Something went wrong!"
2019-10-18 10:56:59.964 -07:00 [Debug] Batch acquisition of 0 triggers`

Ombi Log when trying to sent tv to Sonarr:
`                                                                                         2019-10-18 10:59:19.232 -07:00 [Debug] Batch acquisition of 0 triggers
2019-10-18 10:59:19.976 -07:00 [Error] StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://10.1.10.230:8989/api/series/
2019-10-18 10:59:20.083 -07:00 [Error] StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://10.1.10.230:8989/api/series/
2019-10-18 10:59:20.124 -07:00 [Error] StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://10.1.10.230:8989/api/series/0`

**Comment by almulder** [comment]
Just a quick update, I decided to uninstall Ombi and all settings and reinstall and set it all back up, Sonarr and Radarr now both work, but lidarr does not still keeps saying something went wrong.

**Comment by gandalf764** [comment]
same problem, no request send to sonarr..
try to: 
- In ombi search TV series: I-land
- Auto approve ok
- In sonarr i cant see my request
- in sonar go to Log and i see this:
API Error: BadRequest :0 is not a valid ID
`NzbDrone.Api.REST.BadRequestException: BadRequest :0 is not a valid ID
  at NzbDrone.Api.REST.RestModule`1[TResource].ValidateId (System.Int32 id) [0x00019] in <20da08f0634d42cf91a879fec9ee7aa5>:0 
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Api.REST.RestModule`1<NzbDrone.Api.Series.SeriesResource>,object)
  at NzbDrone.Api.REST.RestModule`1[TResource].<set_GetResourceById>b__29_0 (System.Object options) [0x000a0] in <20da08f0634d42cf91a879fec9ee7aa5>:0 
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)
  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <63c44d6f8d7e4f339a987bf9eb94d931>:0 `

Invalid request Validation failed: -- Invalid Path -- Invalid Path
Invalid request Validation failed: -- Invalid Path -- Invalid Path

please help
