### ISSUE TITLE
Lidarr - Remove language profile configuration

### ISSUE THREAD

**Issue by frdmn** [tidusjar/Ombi#3150]
**Describe the bug**

Lidarr removed the language profiles (PR https://github.com/lidarr/Lidarr/pull/870). Currently it's not possible to finish the configuration of a Lidarr instance because the wizard asks for said language profiles: 

<img width="532" alt="Bildschirmfoto 2019-09-11 um 17 26 38" src="https://user-images.githubusercontent.com/944459/64713605-777b7d80-d4bd-11e9-9480-56adc713895b.png">

**To Reproduce**

1. Settings -> Music -> Lidarr
2. Try to configure your (latest) Lidarr instance
3. Get stuck at language profile selection

**Expected behavior**

No language selection should be visable.

**Logs (Logs directory where Ombi is located)**

```

ombi          | fail: Ombi.Api.Api[1000]
ombi          |       StatusCode: NotFound, Reason: Not Found, RequestUri: http://192.168.1.250:8686/api/v1/languageprofile
ombi          | fail: Ombi.ErrorHandlingMiddleware[0]
ombi          |       Something bad happened, ErrorMiddleware caught this
ombi          | Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[Ombi.Api.Lidarr.Models.LanguageProfiles]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
ombi          | To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
ombi          | Path 'message', line 2, position 12.
ombi          |    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
ombi          |    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
ombi          |    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
ombi          |    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
ombi          |    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
ombi          |    at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 78
ombi          |    at Ombi.Controllers.External.LidarrController.GetLanguageProfiles(LidarrSettings settings) in C:\projects\requestplex\src\Ombi\Controllers\External\LidarrController.cs:line 71
ombi          |    at lambda_method(Closure , Object )
ombi          |    at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
ombi          |    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
ombi          |    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
ombi          |    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
ombi          |    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
ombi          |    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
ombi          |    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
ombi          |    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
ombi          |    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
ombi          |    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
ombi          |    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
ombi          |    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
ombi          |    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
ombi          |    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
ombi          |    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
ombi          |    at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context)
ombi          |    at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 51
ombi          |    at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24
```

**Ombi Version (please complete the following information):**
 - Version 3.0.4680

**Comment by Bigdesertdon** [comment]
Is this being addressed?    New to OMBI, and immediately upon trying to set up my music through this -- I'm present with this exact issue.  Can not move past the initial setup on OMBI to add Lidarr.

Please advise

**Comment by frdmn** [comment]
@Bigdesertdon we need to be a bit more patient here, since @tidusjar is currently in his well-deserved vacation time (https://github.com/tidusjar/Ombi/issues/3151). 😊

**Comment by tidusjar** [comment]
This has been fixed in the develop branch! 🎉 🎈
