### ISSUE TITLE
Get an error in logs when newsletter tries to run.

### ISSUE THREAD

**Issue by vw-kombi** [tidusjar/Ombi#3219]
**Describe the bug**
click trigger, get no emails.  Unexpected token at offset 26 in log.

**To Reproduce**
1. notifications
2. Click on 'newsletters'
3. click trigger
4. See error in logs as nothing sent

**Expected behavior**
Should work.

**Screenshots**
N/A.

**Logs (Logs directory where Ombi is located)**
2019-10-22 18:48:39.570 +10:00 [Error] Error when attempting to create newsletter
MimeKit.ParseException: Unexpected token at offset 26
   at MimeKit.MailboxAddress.set_Address(String value)
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.Start(NewsletterSettings settings, Boolean test) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\NewsletterJob.cs:line 203
2019-10-22 18:48:39.570 +10:00 [Error] Job System.INewsletterJob threw an unhandled Exception: 
MimeKit.ParseException: Unexpected token at offset 26
   at MimeKit.MailboxAddress.set_Address(String value)
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.Start(NewsletterSettings settings, Boolean test) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\NewsletterJob.cs:line 203
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.Execute(IJobExecutionContext job) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\NewsletterJob.cs:line 295
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
2019-10-22 18:48:39.570 +10:00 [Error] Job System.INewsletterJob threw an exception.
Quartz.SchedulerException: Job threw an unhandled exception. ---> MimeKit.ParseException: Unexpected token at offset 26
   at MimeKit.MailboxAddress.set_Address(String value)
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.Start(NewsletterSettings settings, Boolean test) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\NewsletterJob.cs:line 203
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.Execute(IJobExecutionContext job) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\NewsletterJob.cs:line 295
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
   --- End of inner exception stack trace --- [See nested exception: MimeKit.ParseException: Unexpected token at offset 26
   at MimeKit.MailboxAddress.set_Address(String value)
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.Start(NewsletterSettings settings, Boolean test) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\NewsletterJob.cs:line 203
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.Execute(IJobExecutionContext job) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\NewsletterJob.cs:line 295
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)]
2019-10-22 18:48:39.571 +10:00 [Debug] Trigger instruction : DeleteTrigger

**Desktop (please complete the following information):**
 - OS: Windows

**Ombi Version (please complete the following information):**
 - Version 3.0.4817
- Media Server - Emby

**Additional context**
Running on docker - Unraid.

**Comment by tidusjar** [comment]
Looking at the logs, it seems that one of your users email addresses that are part of the newsletter is incorrect

**Comment by vw-kombi** [comment]
Thanks for that.  No issues I can see with each so I removed newsletter from all users and giving it back one by one to users, with a send after each one.  I am still going in this task to try and find the offending email.  You are correct through - one/more of these is causing the issue.

**Comment by tidusjar** [comment]
Great, when you find out if you could let me know the sort of format it's in I can beef up the validation

**Comment by vw-kombi** [comment]
Hi - The issue seemed to be a training space at the end of two of the email addresses.  Hope that helps.

**Comment by tidusjar** [comment]
I'll add in a fix for that

**Comment by tidusjar** [comment]
This has been fixed in the develop branch! 🎉 🎈

**Comment by mrjohnpoz** [comment]
I know this is old.. But wanted to say thanks..  A quick google for the error I was seeing via notification to one of my users when their request was approved or when it became available.. No email sent, etc.

It indeed was a trailing space on the email address.
