### ISSUE TITLE
Updater won't work built-in or script

### ISSUE THREAD

**Issue by augustechartre** [tidusjar/Ombi#3266]
Hello,

**Describe the bug**
Updater won't work.

**To Reproduce**
1. Go to System > Update
2. See error

**Expected behavior**
Update with or without script : https://github.com/Unimatrix0/update_ombi/blob/master/update_ombi.sh

**Screenshots**

**Logs (Logs directory where Ombi is located)**
```
Nov 16 08:45:48 vmi313323 Ombi[14891]: #033[41m#033[30mfail#033[39m#033[22m#033[49m: Ombi.ErrorHandlingMiddleware[0]
Nov 16 08:45:48 vmi313323 Ombi[14891]:       Something bad happened, ErrorMiddleware caught this
Nov 16 08:45:48 vmi313323 Ombi[14891]: Quartz.JobPersistenceException: The job (System.IOmbiAutomaticUpdater) referenced by the trigger does not exist.
Nov 16 08:45:48 vmi313323 Ombi[14891]:    at Quartz.Simpl.RAMJobStore.StoreTriggerInternal(IOperableTrigger newTrigger, Boolean replaceExisting)
Nov 16 08:45:48 vmi313323 Ombi[14891]:    at Quartz.Simpl.RAMJobStore.StoreTrigger(IOperableTrigger newTrigger, Boolean replaceExisting, CancellationToken cancellationToken)
Nov 16 08:45:48 vmi313323 Ombi[14891]:    at Quartz.Core.QuartzScheduler.TriggerJob(JobKey jobKey, JobDataMap data, CancellationToken cancellationToken)
Nov 16 08:45:48 vmi313323 Ombi[14891]:    at Ombi.Schedule.OmbiQuartz.TriggerJob(String jobName, String group) in C:\projects\requestplex\src\Ombi.Schedule\OmbiQuartz.cs:line 79
Nov 16 08:45:48 vmi313323 Ombi[14891]:    at Ombi.Controllers.JobController.ForceUpdate() in C:\projects\requestplex\src\Ombi\Controllers\JobController.cs:line 41
Nov 16 08:45:48 vmi313323 Ombi[14891]:    at lambda_method(Closure , Object )
Nov 16 08:45:48 vmi313323 Ombi[14891]:    at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Nov 16 08:45:48 vmi313323 Ombi[14891]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
Nov 16 08:45:48 vmi313323 Ombi[14891]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
Nov 16 08:45:48 vmi313323 Ombi[14891]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
Nov 16 08:45:48 vmi313323 Ombi[14891]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Nov 16 08:45:48 vmi313323 Ombi[14891]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
Nov 16 08:45:48 vmi313323 Ombi[14891]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
Nov 16 08:45:48 vmi313323 Ombi[14891]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Nov 16 08:45:48 vmi313323 Ombi[14891]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Nov 16 08:45:48 vmi313323 Ombi[14891]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
Nov 16 08:45:48 vmi313323 Ombi[14891]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
Nov 16 08:45:48 vmi313323 Ombi[14891]:    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Nov 16 08:45:48 vmi313323 Ombi[14891]:    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Nov 16 08:45:48 vmi313323 Ombi[14891]:    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
Nov 16 08:45:48 vmi313323 Ombi[14891]:    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
Nov 16 08:45:48 vmi313323 Ombi[14891]:    at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context)
Nov 16 08:45:48 vmi313323 Ombi[14891]:    at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 51
Nov 16 08:45:48 vmi313323 Ombi[14891]:    at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.04

**Ombi Version (please complete the following information):**
 - Version 3.0.4817
- Media Server Plex

**Additional context**
I tried built-in or by script, same error.
I tried change owner of /opt/Ombi by ombi:seedbox , I created a seedbox group. 
When I execute update_ombi.sh, from ssh, I have error:
```
update_ombi.sh: 47: update_ombi.sh: declare: not found
update_ombi.sh: 58: update_ombi.sh: Bad substitution
```
In script, I modify default port to 5010 because 5000 is use by rtorrent. And change the path of ombi by `/etc/systemd/system/multi-user.target.wants/$ombiservicename.service`

Where is my mistake?
Thanks

**Comment by twanariens** [comment]
I got the same issue. Seems like a link is refering to a local directory that does not exist on my Server: C:\projects\requestplex\src\Ombi\Controllers\JobController.cs

Ombi Version: 3.0.4817

**Comment by tidusjar** [comment]
Updater doesn't currently work and needs reworking. Known issue. Planning to tackle this at some point.
