### ISSUE TITLE
Email SMTP System.IO.IOException

### ISSUE THREAD

**Issue by jeffkeller87** [tidusjar/Ombi#3278]
**Describe the bug**
Email SMTP configuration returns an error now. Same configuration worked fine before, last known successful email sent on 2019-10-17.

**To Reproduce**
1. Configure email with the following settings:
    - [X] Enabled
    - [X] Enable SMTP Authentication
    - [ ] Disable TLS/SSL
    - [ ] Disable Certificate Checking
    - SMTP Host: `mail.privateemail.com`
    - SMTP Port: `465`
    - (Sender Email, Admin Email, Username, Password not shown here)
2. Click "Submit" to save settings
3. Click "Test" to send a test email to admin email addresses
4. Error message in UI: _"There was an error when sending the Email message, please check your settings."_
5. View logs (below)

**Expected behavior**
A test email is sent to all admin email addresses.

**Logs (Logs directory where Ombi is located)**
```
2019-11-21 08:45:13.772 -05:00 [Error] Exception when attempting to send an email
System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at MailKit.Net.Smtp.SmtpStream.ReadAheadAsync(Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpStream.ReadResponseAsync(Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpStream.ReadResponse(CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 92
2019-11-21 08:45:13.774 -05:00 [Warning] Exception when testing Email Notifications
System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at MailKit.Net.Smtp.SmtpStream.ReadAheadAsync(Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpStream.ReadResponseAsync(Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpStream.ReadResponse(CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 92
   at Ombi.Controllers.External.TesterController.Email(EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 251
```

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.2

**Ombi Version (please complete the following information):**
 - Version: 3.0.4900
- Media Server: Emby

**Additional context**
There is only one admin email address configured in Ombi. I have the Geary email client configured on the same machine with the same SMTP configuration details and it works fine.

**Comment by hypnero-sudo** [comment]
I have the same exact issue with the same date as the last known email sent. I am thinking it has to do with the email provider as Private Email had server maintenance during that exact time and has yet to work since the update. It might be a coincidence but I am going to message them today.

**Comment by jeffkeller87** [comment]
I remember that maintenance window, but it's odd that other email clients work just fine with Private Email's SMTP configs, no? I think that points to something on the Ombi side.

**Comment by hypnero-sudo** [comment]
I think you're correct it's just been so long since I have utilized my email account for anything else and I had an issue just trying to send an email now but that was because of a typo lol. Hopefully, someone at OMBI sees this or maybe some other people come forward as I think Im going crazy trying to figure this out.

**Comment by tidusjar** [comment]
Hi guys, sorry about the lack of response. Been very busy with personal stuff.

Regarding this, the way Ombi sends emails is very simple and dumb (as it doesn't need to be anything else). Basically we connect to the SMTP server with the credentials and information you provide.

The exception that is happening above is that we have attempted to connect to the SMTP provider but they refused the connection. This usually happens due to incorrect port for example. So it could be that the provider has changed something on their end?

There's not much I can do from a code point of view regarding this

**Comment by jeffkeller87** [comment]
I tried this again today and somehow (?!) got a more informative error in **Log 1**. I may have gotten this log message to show up when trying out different ports, not sure. At any rate, the message about the server SSL certificate points back to an issue with Private Email (the provider). By the way, here are [Private Email's suggested configs](https://www.namecheap.com/support/knowledgebase/article.aspx/1179/2175/general-private-email-configuration-for-mail-clients-and-mobile-devices).

I disabled certificate checking in the Email Notifications area of Ombi's settings and emails are working again. My other email clients weren't actually using the same outgoing server settings. They were using STARTTLS on port 587 rather than SSL on port 465. Does Ombi support STARTTLS @tidusjar? I tried checking the "Disable TLS/SSL" box and switching to port 587 in Ombi thinking it would use STARTTLS instead, and got the error in **Log 2**.

Even after reading about the [difference between the SSL, TLS, and STARTTLS](https://www.fastmail.com/help/technical/ssltlsstarttls.html) protocols, I still don't quite understand what is going on. But it does seem to be an issue with Private Email. @hypnero-sudo you may want to confirm this information and include it when you reach out to Private Email.

**Log 1**
```
at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 87
2019-11-25 16:35:35.569 -05:00 [Warning] Exception when testing Email Notifications
MailKit.Security.SslHandshakeException: An error occurred while attempting to establish an SSL or TLS connection.

One possibility is that you are trying to connect to a port which does not support SSL/TLS.

The other possibility is that the SSL certificate presented by the server is not trusted by the system for one or more of the following reasons:
1. The server is using a self-signed certificate which cannot be verified.
2. The local system is missing a Root or Intermediate certificate needed to verify the server's certificate.
3. The certificate presented by the server is expired or invalid.

See https://github.com/jstedfast/MailKit/blob/master/FAQ.md#InvalidSslCertificate for possible solutions. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__46_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 87
   at Ombi.Controllers.External.TesterController.Email(EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 251
```

**Log 2**
```
2019-11-25 16:50:12.056 -05:00 [Error] Exception when attempting to send an email
MailKit.Security.AuthenticationException: AuthenticationRequired: Must issue a STARTTLS command first ---> MailKit.Net.Smtp.SmtpCommandException: Must issue a STARTTLS command first
   --- End of inner exception stack trace ---
   at MailKit.Net.Smtp.SmtpClient.AuthenticateAsync(Encoding encoding, ICredentials credentials, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
   at MailKit.MailService.Authenticate(String userName, String password, CancellationToken cancellationToken)
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 98
2019-11-25 16:50:12.057 -05:00 [Warning] Exception when testing Email Notifications
MailKit.Security.AuthenticationException: AuthenticationRequired: Must issue a STARTTLS command first ---> MailKit.Net.Smtp.SmtpCommandException: Must issue a STARTTLS command first
   --- End of inner exception stack trace ---
   at MailKit.Net.Smtp.SmtpClient.AuthenticateAsync(Encoding encoding, ICredentials credentials, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
   at MailKit.MailService.Authenticate(String userName, String password, CancellationToken cancellationToken)
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 98
   at Ombi.Controllers.External.TesterController.Email(EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 251
```

**Comment by tidusjar** [comment]
So regards to log 2, If you disable SSL and use port 587 it should use STARTTSL, so the library we use is MailKit and it does support it. So that might possibly be a bug, but I have no way of confirming it myself.
