### ISSUE TITLE
Database Out Of Sync After Migration To APT

### ISSUE THREAD

**Issue by Kyrluckechuck** [tidusjar/Ombi#3287]
**Describe the bug**
After switching from a previous version (4119 (Jan 2019) was last update) to the latest available, it would appear my database has become (partially) corrupt due to missing db migrations (missing columns such as TotalSeasons, RequestedByAlias, etc).

**To Reproduce**
This would appear to be caused by an large db version jump with missing migrations, not entirely sure how to reproduce.

**Expected behavior**
No DB errors in logs.
UI appears to be working, but unsure. There are a number of requests stuck in 'processing' that could maybe be attributed to this.

**Screenshots**
![image](https://user-images.githubusercontent.com/7606153/69763076-09e50200-113a-11ea-9157-bbaa5a9a7405.png)

**Logs (Logs directory where Ombi is located)**
Attached is the entire log as it's not obvious if it's just a chunk of it needed.
[log-20191127.txt](https://github.com/tidusjar/Ombi/files/3899020/log-20191127.txt)

**Desktop (please complete the following information):**
 - Ubuntu 18.04.3 LTS

**Ombi Version (please complete the following information):**
 - Version 3.0.4892, from v3.0.4119
 -> Used Version 3.0.4887 as per the request of many other threads as it was a 'needed migration update'
- Media Server: Plex, w/ Sonarr & Radarr

**Additional context**
This was upgraded from Linux.tar.gz source to APT repo as I was sick of the auto update process always failing and the manual update process being even more unreliable and full of headaches. This appears to be working fine now, except for the erroneous errors

Any other info I can provide to resolve this, please let me know! (I saw you manually fixing db's in other threads, and would like to avoid rebuilding if possible, but don't want to request that if there are workarounds)

**Comment by tidusjar** [comment]
Oh man that is a big jump. Feel free to send me your dbs and I'll attempt to migrate them

**Comment by frode** [comment]
My instance also crashed. Its failing at another column:


```
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()


   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)


   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)


   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)


   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)


   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ApiKeyMiddlewear.cs:line 51


   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ErrorHandlingMiddlewear.cs:line 24


fail: Ombi.ErrorHandlingMiddleware[0]


      Something bad happened, ErrorMiddleware caught this


Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: x.RequestId'.


   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)


   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()


   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)


   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)


   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)


   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)


   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)


   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)


   at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\First.cs:line 144


   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)


   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\Select.cs:line 106


   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\AsyncIterator.cs:line 98


   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)


   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)


   at Ombi.Store.Repository.PlexServerContentRepository.Get(String providerId) in C:\projects\requestplex\src\Ombi.Store\Repository\PlexContentRepository.cs:line 66


   at Ombi.Core.Rule.Rules.Search.PlexAvailabilityRule.Execute(SearchViewModel obj) in C:\projects\requestplex\src\Ombi.Core\Rule\Rules\Search\PlexAvailabilityRule.cs:line 31


   at Ombi.Core.Rule.RuleEvaluator.StartSearchRules(SearchViewModel obj) in C:\projects\requestplex\src\Ombi.Core\Rule\RuleEvaluator.cs:line 54


   at Ombi.Core.Engine.Interfaces.BaseEngine.RunSearchRules(SearchViewModel model) in C:\projects\requestplex\src\Ombi.Core\Engine\Interfaces\BaseEngine.cs:line 53


   at Ombi.Core.Engine.TvSearchEngine.ProcessResult(SearchTvShowViewModel item) in C:\projects\requestplex\src\Ombi.Core\Engine\TvSearchEngine.cs:line 171
```

**Comment by Kyrluckechuck** [comment]
@tidusjar Apologies, I emailed the database (as I wasn't sure of any other way to send it besides uploading it here, which seemed odd to do), but forgot to post here that I had!

Please let me know if it needs to be sent another way or you didn't receive it! :)

**Comment by mizled** [comment]
@tidusjar 

I think I'm in a similar situation. I recently upgraded to the latest and now things aren't loading in the UI and I am unable to request shows. Not sure what I can do to fix this or where to even start?

**Comment by mizled** [comment]
I think I went straight from the Jan 2019 version to the current latest (but can’t be sure what version I was on). If I downgrade will it fix my database or make things worse? Can I downgrade to a version that will fix my database and then upgrade to the latest?

**Comment by tidusjar** [comment]
This is due to the large jump and also the recent work to change the db over to using MySQL which means I had to re-do all the migrations. 

You have 2 options,
1. Run the release before I added the new database (check the github releases page) and then update to latest (make sure you delete the OmbiExternal.db)
2. Start from scratch

**Comment by mizled** [comment]
@tidusjar Do you know which version I should jump to first? It’s not really clear in the change logs

**Comment by tidusjar** [comment]
v3.0.4892 is the version before the new DB providers

**Comment by mizled** [comment]
@tidusjar That doesn’t seem right. 4892 is the latest version
