### ISSUE TITLE
Database messed up? Cannot search for movies at all

### ISSUE THREAD

**Issue by clifford64** [tidusjar/Ombi#3290]
**Describe the bug**
The basic issue boils down to not being able to search for movies at all. I have tested the connection to radarr and everything seems to be working normally. I looked at my logs and They are just absolutely filled with reoccurring errors.

**To Reproduce**
1. Search for movie and it doesn't. Seems to be isolated to me only. 

**Expected behavior**
Search for movie and it works.

**Logs (Logs directory where Ombi is located)**
2019-11-28 10:30:00.242 -05:00 [Error] Exception when adding new Movie "[REDACTED]"
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: x.RequestId'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, Cancel
lationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.AsyncSelectEnumerable`2.AsyncSelectEnumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\First.cs:line 144
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\Select.cs:line 106
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\AsyncIterator.cs:line 98
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextTyp
e)
   at Ombi.Store.Repository.PlexServerContentRepository.GetFirstContentByCustom(Expression`1 predicate) in C:\projects\requestplex\src\Ombi.Store\Repository\PlexContentRepository.cs:line 90
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessServer(PlexServers servers, Boolean recentlyAddedSearch) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 246

**I am seeing the above logs with just about every movie I have added in the past. I am also seeing the below log as well.**

2019-11-28 10:36:57.372 -05:00 [Error] Something bad happened, ErrorMiddleware caught this
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: x.RequestId'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\First.cs:line 144
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\Select.cs:line 106
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\AsyncIterator.cs:line 98
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)
   at Ombi.Store.Repository.PlexServerContentRepository.Get(String providerId) in C:\projects\requestplex\src\Ombi.Store\Repository\PlexContentRepository.cs:line 66
   at Ombi.Core.Rule.Rules.Search.PlexAvailabilityRule.Execute(SearchViewModel obj) in C:\projects\requestplex\src\Ombi.Core\Rule\Rules\Search\PlexAvailabilityRule.cs:line 31
   at Ombi.Core.Rule.RuleEvaluator.StartSearchRules(SearchViewModel obj) in C:\projects\requestplex\src\Ombi.Core\Rule\RuleEvaluator.cs:line 54
   at Ombi.Core.Engine.Interfaces.BaseEngine.RunSearchRules(SearchViewModel model) in C:\projects\requestplex\src\Ombi.Core\Engine\Interfaces\BaseEngine.cs:line 53
   at Ombi.Core.Engine.TvSearchEngine.ProcessResult(SearchTvShowViewModel item) in C:\projects\requestplex\src\Ombi.Core\Engine\TvSearchEngine.cs:line 171
   at Ombi.Core.Engine.TvSearchEngine.GetShowInformation(Int32 tvdbid) in C:\projects\requestplex\src\Ombi.Core\Engine\TvSearchEngine.cs:line 120
   at Ombi.Controllers.SearchController.GetShowInfo(Int32 tvdbId) in C:\projects\requestplex\src\Ombi\Controllers\SearchController.cs:line 274
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.InvoqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)
   at Ombi.Store.Repository.PlexServerContentRepository.Get(String providerId) in C:\projects\requestplex\src\Ombi.Store\Repository\PlexContentRepository.cs:line 66
   at Ombi.Core.Rule.Rules.Search.PlexAvailabilityRule.Execute(SearchViewModel obj) in C:\projects\requestplex\src\Ombi.Core\Rule\Rules\Search\PlexAvailabilityRule.cs:line 31
   at Ombi.Core.Rule.RuleEvaluator.StartSearchRules(SearchViewModel obj) in C:\projects\requestplex\src\Ombi.Core\Rule\RuleEvaluator.cs:line 54
   at Ombi.Core.Engine.Interfaces.BaseEngine.RunSearchRules(SearchViewModel model) in C:\projects\requestplex\src\Ombi.Core\Engine\Interfaces\BaseEngine.cs:line 53
   at Ombi.Core.Engine.TvSearchEngine.ProcessResult(SearchTvShowViewModel item) in C:\projects\requestplex\src\Ombi.Core\Engine\TvSearchEngine.cs:line 171
   at Ombi.Core.Engine.TvSearchEngine.GetShowInformation(Int32 tvdbid) in C:\projects\requestplex\src\Ombi.Core\Engine\TvSearchEngine.cs:line 120
   at Ombi.Controllers.SearchController.GetShowInfo(Int32 tvdbId) in C:\projects\requestplex\src\Ombi\Controllers\SearchController.cs:line 274
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ApiKeyMiddlewear.cs:line 51
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ErrorHandlingMiddlewear.cs:line 24

**Desktop (please complete the following information):**
 - OS: Docker container within Ubuntu 19.04

**Ombi Version (please complete the following information):**
- Docker container, latest version.

**Additional context**
I am not really sure how to interpret these logs. I don't really want to rebuild ombi if I don't have to. If I do, is there a way to save the requests and general setup? Or is it a full rebuild?

**Comment by clifford64** [comment]
Alright, I am kinda dumb for not looking at the common errors section. I tried running the SQL command for docker, but I get the error of not being able to open the database file.

**Comment by clifford64** [comment]
Looks like I was able to get it working. I ran the actual sqllite3 command as sudo and it went through. Ombi then started loading movies shortly after.

**Comment by GldRush98** [comment]
It seems Ombi has failed to update the database file or something.  I'm having the same issue and getting 
`Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: x.RequestId'. `

**Comment by tidusjar** [comment]
#3253
