### ISSUE TITLE
3.0.4898 Email not sending after fresh install

### ISSUE THREAD

**Issue by thekingswolf** [tidusjar/Ombi#3310]
**Describe the bug**
had some major issues with upgrading to the newest version recently. Had to wipe and start from scratch. Now I can't get email to work and the settings are the same as it was.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Notifications'
3. Scroll down to 'Email'
4. See screenshot for current settings

**Expected behavior**
Email gets sent via Mass Email

**Screenshots**
https://imgur.com/a/UNEIwXC

**Logs (Logs directory where Ombi is located)**
I have replaced the first part of the email with **** for obvious reasons but both of these emails are valid, they are mine.

`2019-12-16 20:44:52.997 -06:00 [Error] Exception when attempting to send an email System.ArgumentException: The domain is invalid. Parameter name: domain at MimeKit.Utils.MimeUtils.GenerateMessageId(String domain) at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings) 2019-12-16 20:44:52.997 -06:00 [Information] Sent mass email to user "Mitchell" @ "****@hotmail.com" 2019-12-16 20:44:52.999 -06:00 [Error] Exception when attempting to send an email System.ArgumentException: The domain is invalid. Parameter name: domain at MimeKit.Utils.MimeUtils.GenerateMessageId(String domain) at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings) 2019-12-16 20:44:52.999 -06:00 [Information] Sent mass email to user "TKW" @ "****@gmail.com" 2019-12-16 20:44:53.001 -06:00 [Error] Something bad happened, ErrorMiddleware caught this System.ArgumentException: The domain is invalid. Parameter name: domain`

**Desktop (please complete the following information):**
 - OS: WIndows 10 x64

**Ombi Version (please complete the following information):**
 - Version 3.0.4898
- Media Server Emby

**Additional context**
Not an issue with gmail settings as I have been using Ombi to send emails with this account for a long time.

**Comment by tidusjar** [comment]
The error is in the log
`The domain is invalid.`

One of your domains is invalid either in your settings or the recipient.

**Comment by thekingswolf** [comment]
you can see for yourself in my settings and the log file that the domain is @gmail.com which i'm pretty sure is a valid domain....

**Comment by thekingswolf** [comment]
i'm a little frustrated man.   I can read for myself what the log says. i'm posting here because the domain is clearly not invalid in my settings or the log.  not that i can see.

**Comment by tidusjar** [comment]
Sorry didn't investigate the logs enough. 

Sis that the only errors you are getting?

**Comment by thekingswolf** [comment]
I restarted Ombi for clear log.  Send email immediately.  Here is the complete log.  

`2019-12-22 19:09:47.584 -06:00 [Information] Default Quartz.NET properties loaded from embedded resource file
2019-12-22 19:09:47.679 -06:00 [Debug] TaskSchedulingThreadPool configured with max concurrency of 10 and TaskScheduler ThreadPoolTaskScheduler.
2019-12-22 19:09:47.710 -06:00 [Information] Initialized Scheduler Signaller of type: Quartz.Core.SchedulerSignalerImpl
2019-12-22 19:09:47.712 -06:00 [Information] Quartz Scheduler v."3.0.7.0" created.
2019-12-22 19:09:47.715 -06:00 [Information] RAMJobStore initialized.
2019-12-22 19:09:47.720 -06:00 [Information] Scheduler meta-data: Quartz Scheduler (v3.0.7.0) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'Quartz.Core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'Quartz.Simpl.DefaultThreadPool' - with 10 threads.
  Using job-store 'Quartz.Simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2019-12-22 19:09:47.721 -06:00 [Information] Quartz scheduler 'DefaultQuartzScheduler' initialized
2019-12-22 19:09:47.721 -06:00 [Information] Quartz scheduler version: 3.0.7.0
2019-12-22 19:09:47.723 -06:00 [Information] JobFactory set to: Ombi.Schedule.IoCJobFactory
2019-12-22 19:09:47.842 -06:00 [Information] Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
2019-12-22 19:09:47.851 -06:00 [Debug] Batch acquisition of 1 triggers
2019-12-22 19:10:00.042 -06:00 [Debug] Batch acquisition of 0 triggers
2019-12-22 19:10:00.083 -06:00 [Debug] Calling Execute on job DVR.ISonarrSync
2019-12-22 19:10:00.109 -06:00 [Debug] Trigger instruction : NoInstruction
2019-12-22 19:10:01.568 -06:00 [Error] Something bad happened, ErrorMiddleware caught this
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(Task`1 getTask)
   at Ombi.Api.OmbiHttpClient.GetStringAsync(Uri requestUri) in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 67
   at Ombi.Schedule.Processor.ChangeLogProcessor.Process(String branch) in C:\projects\requestplex\src\Ombi.Schedule\Processor\ChangeLogProcessor.cs:line 36
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.UpdateAvailable(String branch, String currentVersion) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 55
   at Ombi.Controllers.JobController.<CheckForUpdateCached>b__5_0() in C:\projects\requestplex\src\Ombi\Controllers\JobController.cs:line 72
   at Ombi.Helpers.CacheService.GetOrAdd[T](String cacheKey, Func`1 factory, DateTime absoluteExpiration) in C:\projects\requestplex\src\Ombi.Helpers\CacheService.cs:line 36
   at Ombi.Controllers.JobController.CheckForUpdateCached() in C:\projects\requestplex\src\Ombi\Controllers\JobController.cs:line 67
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ApiKeyMiddlewear.cs:line 51
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ErrorHandlingMiddlewear.cs:line 24
2019-12-22 19:10:16.093 -06:00 [Error] Exception when attempting to send an email
System.ArgumentException: The domain is invalid.
Parameter name: domain
   at MimeKit.Utils.MimeUtils.GenerateMessageId(String domain)
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings)
2019-12-22 19:10:16.097 -06:00 [Information] Sent mass email to user "Mitchell" @ "****@hotmail.com"
2019-12-22 19:10:16.099 -06:00 [Error] Exception when attempting to send an email
System.ArgumentException: The domain is invalid.
Parameter name: domain
   at MimeKit.Utils.MimeUtils.GenerateMessageId(String domain)
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings)
2019-12-22 19:10:16.100 -06:00 [Information] Sent mass email to user "TKW" @ "****@gmail.com"
2019-12-22 19:10:16.114 -06:00 [Error] Something bad happened, ErrorMiddleware caught this
System.ArgumentException: The domain is invalid.
Parameter name: domain
   at MimeKit.Utils.MimeUtils.GenerateMessageId(String domain)
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings)
   at Ombi.Core.Senders.MassEmailSender.SendMassEmail(MassEmailModel model) in C:\projects\requestplex\src\Ombi.Core\Senders\MassEmailSender.cs:line 90
   at Ombi.Controllers.NotificationsController.SendMassEmail(MassEmailModel model) in C:\projects\requestplex\src\Ombi\Controllers\NotificationsController.cs:line 52
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ApiKeyMiddlewear.cs:line 51
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ErrorHandlingMiddlewear.cs:line 24
2019-12-22 19:10:23.869 -06:00 [Debug] Batch acquisition of 0 triggers
2019-12-22 19:10:49.166 -06:00 [Debug] Batch acquisition of 0 triggers
`

**Comment by thekingswolf** [comment]
update.  apparently this is just a problem with the send mass email.  users are getting email notifications of when their requests are available.
