### ISSUE TITLE
Trying to migrate to Mariadb

### ISSUE THREAD

**Issue by saitoh183** [tidusjar/Ombi#3311]
**Describe the bug**
Unable to complete the Migration process from SQLite to Mariadb, when launching Ombi with the dababase.json, webpage  just stays on loading
**To Reproduce**
Followed the instruction in the Wiki

**Expected behavior**
Migrations portion of the instruction succeeds
**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.
[log-20191216.txt](https://github.com/tidusjar/Ombi/files/3971771/log-20191216.txt)
[log-20191217.txt](https://github.com/tidusjar/Ombi/files/3971772/log-20191217.txt)
**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.3

**Ombi Version (please complete the following information):**
- Docker (development tag)
- Version: 3.0.4914-develop

**Additional context**
Error when launching the python file
```
root@5d4ff1f0ba06:/ombi_sqlite_mysql# python2 ombi_sqlite2mysql.py -c /config --host mariadb --db Ombi --user ombi --passwd ombi
Migration tool from SQLite to MySql/MariaDB for ombi (3.0.2) By VSC55

Generate file "database.json":
- Saving in (/config/database.json)... [✓]

MySQL > Connecting... [✓]
- Reading   [############################################################] 1/1
Read tables [✓]

Check migration.json:
- SettingsDatabase [SQLite >> Migrate]
- OmbiDatabase [SQLite >> Migrate]
- ExternalDatabase [SQLite >> Migrate]

Dump SQLite:
- SettingsDatabase  [############################################################] 25/25
Traceback (most recent call last):
  File "ombi_sqlite2mysql.py", line 1038, in <module>
    main()
  File "ombi_sqlite2mysql.py", line 1023, in main
    data_dump = list(_sqlite_dump())
  File "ombi_sqlite2mysql.py", line 687, in _sqlite_dump
    data_get_sqlite = list(_iterdump(con, db_name))
  File "ombi_sqlite2mysql.py", line 759, in _iterdump
    elif cu.execute("SELECT COUNT(*) FROM {0}".format(table_name)).fetchone()[0] < 1:
sqlite3.OperationalError: no such table: HangFire.AggregatedCounter
```
Mariadb:
```
MariaDB [Ombi]> Show tables;
+-----------------------------+
| Tables_in_Ombi              |
+-----------------------------+
| AlbumRequests               |
| ApplicationConfiguration    |
| AspNetRoleClaims            |
| AspNetRoles                 |
| AspNetUserClaims            |
| AspNetUserLogins            |
| AspNetUserRoles             |
| AspNetUserTokens            |
| AspNetUsers                 |
| Audit                       |
| ChildRequests               |
| CouchPotatoCache            |
| EmbyContent                 |
| EmbyEpisode                 |
| EpisodeRequests             |
| GlobalSettings              |
| IssueCategory               |
| IssueComments               |
| Issues                      |
| LidarrAlbumCache            |
| LidarrArtistCache           |
| MovieRequests               |
| NotificationTemplates       |
| NotificationUserId          |
| PlexEpisode                 |
| PlexSeasonsContent          |
| PlexServerContent           |
| RadarrCache                 |
| RecentlyAddedLog            |
| RequestLog                  |
| RequestQueue                |
| RequestSubscription         |
| SeasonRequests              |
| SickRageCache               |
| SickRageEpisodeCache        |
| SonarrCache                 |
| SonarrEpisodeCache          |
| Tokens                      |
| TvRequests                  |
| UserNotificationPreferences |
| UserQualityProfiles         |
| Votes                       |
| __EFMigrationsHistory       |
+-----------------------------+
```

```
MariaDB [Ombi]> select * from __EFMigrationsHistory
    -> ;
+-----------------------+-----------------------+
| MigrationId           | ProductVersion        |
+-----------------------+-----------------------+
| 20191102235852_Inital | 2.2.6-servicing-10079 |
| 20191103205915_Inital | 2.2.6-servicing-10079 |
| 20191103213915_Inital | 2.2.6-servicing-10079 |
+-----------------------+-----------------------+
3 rows in set (0.000 sec)
```

[database.json.txt](https://github.com/tidusjar/Ombi/files/3971788/database.json.txt)
[migration.json.txt](https://github.com/tidusjar/Ombi/files/3971789/migration.json.txt)

**Comment by tidusjar** [comment]
That's not something I can support. It's a community driven tool. Best bet is to contact the author in discord.
