### ISSUE TITLE
Ombi not updating availability, error thrown in log

### ISSUE THREAD

**Issue by burnbrigther** [tidusjar/Ombi#3315]
**Describe the bug**
Development release not updating status of movies/TV Shows.  Status stuck showing "processing".  Movies/TV Shows are already on disk and have been for some time.
Running Media full sync gives error

**To Reproduce**
1. Request a movie - Movie downloads (doesn't matter if NZB or torrent)
2. Validate movie download is completed and shows up in Plex (not totally necessary)
3. Wait time for availability to normally update and mark movie as available
4. Movie/TV Show does not get automatically marked available
5. From Ombi, run Full Manual Sync - error shown below is thrown in log.

**Expected behavior**
Movies / TV Shows should update accordingly

**Screenshots**
![Screen Shot 2019-12-18 at 12 06 01 PM](https://user-images.githubusercontent.com/5279205/71119782-ca856080-218f-11ea-920e-d6bd779239e3.png)

**Logs (Logs directory where Ombi is located)**
```
2019-12-18 12:08:27.820 -08:00 [Debug] Batch acquisition of 0 triggers
2019-12-18 12:08:51.246 -08:00 [Debug] Batch acquisition of 0 triggers
2019-12-18 12:09:15.462 -08:00 [Debug] Batch acquisition of 0 triggers
2019-12-18 12:09:41.588 -08:00 [Debug] Batch acquisition of 1 triggers
2019-12-18 12:10:00.002 -08:00 [Debug] Batch acquisition of 0 triggers
2019-12-18 12:10:00.003 -08:00 [Debug] Calling Execute on job DVR.ISonarrSync
2019-12-18 12:10:01.283 -08:00 [Debug] Trigger instruction : NoInstruction
2019-12-18 12:10:29.023 -08:00 [Debug] Batch acquisition of 0 triggers
2019-12-18 12:10:52.629 -08:00 [Debug] Batch acquisition of 0 triggers
2019-12-18 12:11:08.382 -08:00 [Debug] Batch acquisition of 1 triggers
2019-12-18 12:11:08.384 -08:00 [Debug] Batch acquisition of 0 triggers
2019-12-18 12:11:08.384 -08:00 [Debug] Calling Execute on job Plex.IPlexContentSync
2019-12-18 12:11:08.408 -08:00 [Information] Starting Plex Content Cacher
2019-12-18 12:11:08.413 -08:00 [Information] Starting to cache the content on server "CEDAR"
2019-12-18 12:11:12.987 -08:00 [Information] Starting EP Cacher
2019-12-18 12:11:12.989 -08:00 [Information] Finished Plex Content Cacher, with processed content: 0, episodes: 0. Recently Added Scan: False
2019-12-18 12:11:12.989 -08:00 [Debug] Batch acquisition of 1 triggers
2019-12-18 12:11:12.989 -08:00 [Debug] Batch acquisition of 0 triggers
2019-12-18 12:11:12.989 -08:00 [Debug] Calling Execute on job Plex.IPlexEpisodeSync
2019-12-18 12:11:12.989 -08:00 [Debug] Trigger instruction : DeleteTrigger
2019-12-18 12:11:12.990 -08:00 [Debug] Deleting trigger
2019-12-18 12:11:13.065 -08:00 [Information] Total Epsiodes found for TV Shows = 277
2019-12-18 12:11:13.563 -08:00 [Information] Processed 150 more episodes. Total Remaining 127
2019-12-18 12:11:13.563 -08:00 [Information] We have finished caching the episodes.
2019-12-18 12:11:13.566 -08:00 [Debug] Batch acquisition of 1 triggers
2019-12-18 12:11:13.566 -08:00 [Debug] Trigger instruction : DeleteTrigger
2019-12-18 12:11:13.566 -08:00 [Debug] Deleting trigger
2019-12-18 12:11:13.566 -08:00 [Debug] Batch acquisition of 0 triggers
2019-12-18 12:11:13.567 -08:00 [Debug] Calling Execute on job Plex.IPlexAvailabilityChecker
2019-12-18 12:11:13.598 -08:00 [Information] [PAC] - Movie request "Pulp Fiction - 23" is now available, sending notification
2019-12-18 12:11:13.618 -08:00 [Error] Exception thrown in Plex availability checker
System.InvalidOperationException: The instance of entity type 'MovieRequests' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode node, Boolean force)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode node, TState state, Func`3 handleNode)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
   at Ombi.Store.Repository.Requests.MovieRequestRepository.MarkAsAvailable(Int32 id) in C:\projects\requestplex\src\Ombi.Store\Repository\Requests\MovieRequestRepository.cs:line 59
   at Ombi.Schedule.Jobs.Plex.PlexAvailabilityChecker.ProcessMovies() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexAvailabilityChecker.cs:line 194
   at Ombi.Schedule.Jobs.Plex.PlexAvailabilityChecker.Execute(IJobExecutionContext job) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexAvailabilityChecker.cs:line 41
2019-12-18 12:11:13.618 -08:00 [Debug] Trigger instruction : DeleteTrigger
2019-12-18 12:11:13.618 -08:00 [Debug] Deleting trigger
```

**Desktop (please complete the following information):**
 - OS: Windows 10

**Ombi Version (please complete the following information):**
Version | 3.0.4941
Branch | develop
- Media Server [e.g. Plex]
Version 4.12.3

**Comment by tidusjar** [comment]
This is a brand new bug I must have introduced yesterday. I'll sort it out. Thanks for the report

**Comment by burnbrigther** [comment]
@tidusjar please let me know when you have a fix and I will test for you.  Thanks!

**Comment by tidusjar** [comment]
This has been fixed in the develop branch! 🎉 🎈
