### ISSUE TITLE
Ombi v4 throwing "The SPA default page middleware could not return the default page" error

### ISSUE THREAD

**Issue by smartthingsandme** [tidusjar/Ombi#3349]
**Describe the bug**
Ombi v4 running in a docker container reports the following error:

{"error":"The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.\nYour application is running in Production mode, so make sure it has been published, or that you have built your SPA manually. Alternatively you may wish to switch to the Development environment.\n"}

The same issue seems to be affecting the demo: app.ombi.io

Docker container log shows the call stack:

Something bad happened, ErrorMiddleware caught this
System.InvalidOperationException: The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.
Your application is running in Production mode, so make sure it has been published, or that you have built your SPA manually. Alternatively you may wish to switch to the Development environment.

at Microsoft.AspNetCore.SpaServices.SpaDefaultPageMiddleware.<>c__DisplayClass0_0.<Attach>b__1(HttpContext context, Func`1 next)
at Microsoft.AspNetCore.Builder.UseExtensions.<>c__DisplayClass0_1.<Use>b__1(HttpContext context)
at Microsoft.AspNetCore.Builder.UseExtensions.<>c__DisplayClass0_2.<Use>b__2()
at Microsoft.AspNetCore.SpaServices.SpaDefaultPageMiddleware.<>c__DisplayClass0_0.<Attach>b__0(HttpContext context, Func`1 next)
at Microsoft.AspNetCore.Builder.UseExtensions.<>c__DisplayClass0_1.<Use>b__1(HttpContext context)
at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ApiKeyMiddlewear.cs:line 56
at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ErrorHandlingMiddlewear.cs:line 24

**To Reproduce**
1. Go to 'app.ombi.io'
2. See error

**Expected behavior**
The page should load without errors.

**Desktop (please complete the following information):**
 - OS: Ombi running in docker container on unraid

**Ombi Version (please complete the following information):**
 - Version: 4
 - Media Server: Plex

**Additional context**
Same issue as #3139 which is currently in a 'Closed' state.

**Comment by tidusjar** [comment]
Thanks. 

I'm aware on this and will be fixing it soon

**Comment by tidusjar** [comment]
Please pull V4 builds from here: https://github.com/tidusjar/Ombi.Releases/releases

**Comment by nicolahinssen** [comment]
I get the same issue with the V4 build (174) from the Ombi.Releases repository.

**Comment by Cookie-Monster-Coder** [comment]
> I get the same issue with the V4 build (174) from the Ombi.Releases repository.

Same...

I pulled it from here and it worked. At least for thr Linux version have to extract the second zip file that's in the first .tar file. I spent way to long on figuring that out...: https://ci.appveyor.com/project/tidusjar/requestplex/build/artifacts

**Comment by nicolahinssen** [comment]
In the appveyor artifact package (linux.tar.gz) there is no second .zip file. Only in the Ombi.Releases build there is.
