### ISSUE TITLE
Ombi > Mellow integration

### ISSUE THREAD

**Issue by liamarmitage** [tidusjar/Ombi#3351]
**Describe the bug**
Ombi version: 3.0.3421
Mellow - https://github.com/Cloudbox/Community/wiki/Mellow-Discord-Bot

The bot connects to Ombi and everything works apart from the confirmation response from Ombi to Mellow. The Mellow DEVs have advised that this issue seems to be Ombi related hence me logging it.

The Ombi logs details the following

2020-01-17 14:58:26.622 +01:00 [Debug] Searching : "loser"
2020-01-17 14:58:28.028 +01:00 [Debug] Search Result: "Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.Mo$
2020-01-17 14:58:57.670 +01:00 [Debug] Search Result: "Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.Mo$
2020-01-17 14:59:23.272 +01:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/321457
2020-01-17 14:59:23.272 +01:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/145181
2020-01-17 14:59:23.272 +01:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/79629
2020-01-17 14:59:23.451 +01:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/273826
2020-01-17 14:59:23.451 +01:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/279269
2020-01-17 14:59:23.767 +01:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/256880
2020-01-17 14:59:24.054 +01:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/360779
2020-01-17 14:59:24.779 +01:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/265359

**To Reproduce**
1. Go to discord request tv/movie and accept version

**Expected behavior**
Confirmation message stating X Move/TV Show accepted by user "X"

**Screenshots**
N/A

**Logs (Logs directory where Ombi is located)**
Log extract above

**Desktop (please complete the following information):**
 - OS: Linux

**Ombi Version (please complete the following information):**
 - Version as above

**Comment by tidusjar** [comment]
What the actual API response?

**Comment by liamarmitage** [comment]
> What the actual API response?

Thanks for the prompt reply.. the logs show the following

DiscordAPIError: Invalid Form Body
embed.fields[0].value: Must be 1024 or fewer in length.
    at RequestHandler.execute (/home/mellow/node_modules/discord.js/src/rest/RequestHandler.js:170:25)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  name: 'DiscordAPIError',
  message: 'Invalid Form Body\nembed.fields[0].value: Must be 1024 or fewer in length.',
  method: 'post',
  path: '/channels/XXXXXXXXXXXX/messages',
  code: 50035,
  httpStatus: 400
}
{
  error: null,
  body: '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n' +
    '<html><head>\n' +
    '<title>502 Proxy Error</title>\n' +
    '</head><body>\n' +
    '<h1>Proxy Error</h1>\n' +
    '<p>The proxy server received an invalid\r\n' +
    'response from an upstream server.<br />\r\n' +
    'The proxy server could not handle the request<p>Reason: <strong>Error reading from remote server</stro$
    '</body></html>\n'
}

**Comment by v0idp** [comment]
That error is related to Mellow and not Ombi. Feel free to post this issue on my repo and I will fix it. Thank you !

**Comment by liamarmitage** [comment]
Cool thanks @v0idp
