### ISSUE TITLE
Local user password not updating in database

### ISSUE THREAD

**Issue by maximoosemine** [tidusjar/Ombi#3359]
**Describe the bug**

Whenever I change a local user's password, the new password doesn't work. What I did is created a copy of the ombi database file, and opened it, and looked at the password hash, then I changed the password, copies and opened the database again, and the password hash is still the same.

**To Reproduce**

1. Copy your ombi database file.
2. Log into ombi and change a local user's password from the user management menu.
3. Copy your ombi database file again.
4. Compare the two database files and observe that their password hashes are the same.

**Expected behavior**

The password hash in the database should be different before and after I set a different password.

**Logs (Logs directory where Ombi is located)**

Found this around the time of my issue:

```
2020-01-20 02:11:50.457 +00:00 [Error] Something bad happened, ErrorMiddleware caught this
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Ombi.Controllers.ImagesController.GetBackgroundImage() in C:\projects\requestplex\src\Ombi\Controllers\ImagesController.cs:line 213
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ApiKeyMiddlewear.cs:line 51
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ErrorHandlingMiddlewear.cs:line 24
```

**Desktop (please complete the following information):**
 
Chrome running Windows 10
Browsing database with DB Browser for SQLite

**Ombi Version (please complete the following information):**
 - Version 3.0.4892
- Media Server - Plex

**Additional context**

I am running ombi in linuxserver.io's ombi docker container.

I am using a reverse proxy but I have tried changing the password and logging in directly and to no avail.

I have tried:
-Restarting Ombi
-Resetting Ombi
-chmodding my databases to 7777

Logging in with plex works flawlessly.

Also really annoying since this issue means I can't log into the Ombi app which I just shelled out $5 for.

**Updates**

Added "from the user management menu" under "to reproduce" step 2.

Added logs that I missed previously.

**Comment by tidusjar** [comment]
Where are you updating the password? Where in the UI? The user management screen?

**Comment by maximoosemine** [comment]
Yes, the user management screen.

User Management > Details/Edit on a user.

I type in a password in the password field and click update.

**Comment by maximoosemine** [comment]
Update. Was scrolling through the logs again and found something that happened around the time of my issue. Updated my original post.

**Comment by taylorcox75** [comment]
@maximoosemine Having a similar issue right after last night's update. Care to share your solution? Plex / local users don't work
