### ISSUE TITLE
Requests fail for Plex imported user

### ISSUE THREAD

**Issue by goose-ws** [tidusjar/Ombi#3391]
**Describe the bug**
I have a user who was added via Plex Importer. He has the following permissions:

```
AutoApproveTv
RequestMusic
AutoApproveMusic
AutoApproveMovie
RequestMovie
RequestTv
```

He is able to successfully auth into Ombi, but all of his requests fail (Tested movies and TV). The items go to the retry queue with the following error message: `unexpected character encountered while parsing value: <. Path ", line 0, position 0.`

**To Reproduce**
1. User logs in to Organizr via Plex oauth
2. Organizr logs user into Ombi via oauth
3. User opens Ombi, is already logged in, shows up in Ombi as logged in (Updated last logged in date)
4. User searches and requests item
5. Item fails, is put into re-try queue

**Expected behavior**
Item is added without difficulty. When I request items (though I am the admin), the requests process as they should. Sonarr/Radarr are reachable.

**Screenshots**
![image](https://user-images.githubusercontent.com/874014/74487550-bdce7180-4e8d-11ea-87e3-d9c05a1e0c73.png)

**Logs (Logs directory where Ombi is located)**
```
2020-02-13 18:09:59.114 -05:00 [Debug] Batch acquisition of 1 triggers
2020-02-13 18:09:59.267 -05:00 [Error] Error when sending movie to DVR app, added to the request queue
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 78
   at Ombi.Api.Radarr.RadarrApi.GetMovies(String apiKey, String baseUrl) in C:\projects\requestplex\src\Ombi.Api.Radarr\RadarrApi.cs:line 52
   at Ombi.Core.Senders.MovieSender.SendToRadarr(MovieRequests model, RadarrSettings settings) in C:\projects\requestplex\src\Ombi.Core\Senders\MovieSender.cs:line 156
   at Ombi.Core.Senders.MovieSender.Send(MovieRequests model) in C:\projects\requestplex\src\Ombi.Core\Senders\MovieSender.cs:line 57
2020-02-13 18:09:59.290 -05:00 [Debug] Batch acquisition of 1 triggers
2020-02-13 18:09:59.290 -05:00 [Debug] Batch acquisition of 1 triggers
2020-02-13 18:09:59.290 -05:00 [Debug] Calling Execute on job Notifications.INotificationService
2020-02-13 18:10:00.001 -05:00 [Debug] Batch acquisition of 0 triggers
2020-02-13 18:10:00.001 -05:00 [Debug] Calling Execute on job DVR.ISonarrSync
2020-02-13 18:10:00.051 -05:00 [Error] Exception when trying to cache Sonarr
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 78
   at Ombi.Api.Sonarr.SonarrApi.GetSeries(String apiKey, String baseUrl) in C:\projects\requestplex\src\Ombi.Api.Sonarr\SonarrApi.cs:line 46
   at Ombi.Schedule.Jobs.Sonarr.SonarrSync.Execute(IJobExecutionContext job) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Sonarr\SonarrSync.cs:line 46
2020-02-13 18:10:00.052 -05:00 [Debug] Trigger instruction : NoInstruction
2020-02-13 18:10:01.715 -05:00 [Information] there are no admins to send a notification for Test, for agent Mobile
2020-02-13 18:10:01.718 -05:00 [Information] Template ItemAddedToFaultQueue is disabled for Telegram
2020-02-13 18:10:01.719 -05:00 [Debug] Trigger instruction : DeleteTrigger
2020-02-13 18:10:01.719 -05:00 [Debug] Deleting trigger
2020-02-13 18:10:23.006 -05:00 [Debug] Batch acquisition of 0 triggers
```

**Desktop (please complete the following information):**
 - OS: Debian Stable
 - Install: Docker via `linuxserver/ombi:latest` and `linuxserver/ombi:3.0.5020-ls2`

**Ombi Version (please complete the following information):**
 - Version Currently 3.0.5020-ls2, also replicated on latest
- Media Server Plex

**Additional context**
Will provide as needed/requested

**Comment by tidusjar** [comment]
that error usually indicates your settings are incorrect. can you please check these

**Comment by goose-ws** [comment]
Do you know which settings? As described, Ombi appears to be successfully communicating with Sonarr/Radarr and "Test" successfully. Additionally, my requests process without any issue, it's just this user that's not behaving correctly.

**Comment by tidusjar** [comment]
Possibly the base URL? Do you have a URL base set in sonarr?

**Comment by goose-ws** [comment]
I do have them enabled and set for Sonarr and Radarr, you can see successful test connections here:

![image](https://user-images.githubusercontent.com/874014/74760789-f1701980-5248-11ea-9793-250c5ab26bdf.png)

![image](https://user-images.githubusercontent.com/874014/74760860-0e0c5180-5249-11ea-83e6-ceb2ce363aa9.png)

**Comment by tidusjar** [comment]
can you try using an ip address instead?

**Comment by goose-ws** [comment]
I'd prefer to use Docker's internal DNS resolver, as the container IP may change from time to time.

Does the way the program is resolved have anything to do with the specific user failure? I've proved the connection from Ombi to Sonarr/Radarr to be working.

**Comment by tidusjar** [comment]
It shouldn't be anything to do with the user, but does the user have any set Quality Profiles or Root folders?

**Comment by goose-ws** [comment]
No, the user does not (have any Quality, Profiles, or Root Folders set)

However, after changing my docker tag back to `:latest`, I've found that the issue is more confusing than what I originally stated.

The issue now appears for all users, including myself -- However it's sporadic. Sometimes requests work without any difficulty, sometimes they fail and get sent to the retry queue. When they are sent to retry, sometimes they successful add on the first retry, and I have some that have failed 8 times so far.

Is there any way to turn on a debug level log, or some other way I could get more clues as to what's going on?

**Comment by tidusjar** [comment]
Ok in that case it's due to the connection between ombi and Radarr. Are there any errors in Radarr when ombi sends over a movie?
