### ISSUE TITLE
Unexpected Character

### ISSUE THREAD

**Issue by rrbailey89** [tidusjar/Ombi#3420]
**Describe the bug**
Ombi appears unable to access the movies library in plex.

**To Reproduce**
1. Go to 'Ombi'
2. Click on 'run sync'
3. See error

**Expected behavior**
Successfully sync movies.

**Screenshots**

**info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0],
      Starting Plex Content Cacher,
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0],
      Starting to cache the content on server RayFlex,
fail: Ombi.Api.Api[1000],
      StatusCode: NotFound, Reason: Not Found, RequestUri: http://plex:32400/library/metadata/4059,
fail: Ombi.Schedule.Jobs.Plex.PlexContentSync[2008],
      Exception when adding new Movie Ant-Man,
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.,
   at Newtonsoft.Json.JsonTextReader.ParseValue(),
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter),
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent),
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType),
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings),
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings),
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 78,
   at Ombi.Api.Plex.PlexApi.GetMetadata(String authToken, String plexFullHost, Int32 itemId) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 159,
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessServer(PlexServers servers, Boolean recentlyAddedSearch) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 264,
fail: Ombi.Api.Api[1000],
      StatusCode: NotFound, Reason: Not Found, RequestUri: http://plex:32400/library/metadata/4814,
fail: Ombi.Schedule.Jobs.Plex.PlexContentSync[2008],
      Exception when adding new Movie Guardians of the Galaxy,
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.,
   at Newtonsoft.Json.JsonTextReader.ParseValue(),
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter),
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent),
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType),
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings),
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings),
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 78,
   at Ombi.Api.Plex.PlexApi.GetMetadata(String authToken, String plexFullHost, Int32 itemId) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 159,
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessServer(PlexServers servers, Boolean recentlyAddedSearch) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 264,
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0],
      Starting EP Cacher,
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0],
      Finished Plex Content Cacher, with processed content: 0, episodes: 0. Recently Added Scan: False,
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002],
      Total Epsiodes found for TV Shows = 31111,**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**

**Ombi Version (please complete the following information):**
 - Version 3.0.4892
- Media Server Plex

**Additional context**

**Comment by tidusjar** [comment]
Looks like something is wrong with the metadata in the Plex DB for your instance. Can you delete your ombi external .db and then re-run the sync? Just to rule out Ombi

**Comment by Wursthandschuh** [comment]
I had a similar error in my log. (not using plex). Deleting the external db fixed it for me. thx

**Comment by ezeitoun** [comment]
Is there a way to increase logging to know which character is the problematic one ?
have this issue as well, deleting the external database didnt helped much.

**Comment by PhAzE-Variance** [comment]
I am also seeing this problem. Deleting the external db and running a full resync results in the same error. TV shows sync works but Movie sync fails.

**Comment by edimusxero** [comment]
I too am getting the exact same error

OS - Ubuntu 18

I deleted the OmbiExternal.db with no success

**Comment by PhAzE-Variance** [comment]
The fix is to upgrade to the latest plex server, then refresh all metadata on your libraries.

The "new" plex agent was missing imdb and moviedb IDs or something, and has been added back in with recent plex releases. When you refresh your metadata it'll grab those, and ombi will work again.

**Comment by edimusxero** [comment]
ok, I did just upgrade plex this morning.  I will try that.

**Comment by edimusxero** [comment]
I refreshed all my libraries but I am still having the same issue

**Comment by godofjesters** [comment]
i'm having the same issue but trying to connect my ombi to sickchill.

**Comment by daften** [comment]
I am having this issue and my new plex server was set up last week with all new metadata (fresh scan) and ombi was only set up today.

**Comment by daften** [comment]
Double checked by refreshing all metadata for Movies in Plex, deleting the external db and forcing a sync, and same issue happens again.

**Comment by castanley** [comment]
Same issues:
`Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: [. Path 'MediaContainer.Metadata[0].Guid', line 1, position 5252.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 78
   at Ombi.Api.Plex.PlexApi.GetMetadata(String authToken, String plexFullHost, Int32 itemId) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 159
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessServer(PlexServers servers, Boolean recentlyAddedSearch) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 264
fail: Ombi.Schedule.Jobs.Plex.PlexContentSync[2008]
      Exception when adding new Movie removed
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: [. Path 'MediaContainer.Metadata[0].Guid', line 1, position 3811.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 78
   at Ombi.Api.Plex.PlexApi.GetMetadata(String authToken, String plexFullHost, Int32 itemId) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 159
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessServer(PlexServers servers, Boolean recentlyAddedSearch) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 264`

**Comment by castanley** [comment]
@tidusjar - Can you re-open this? Not sure if it is getting attention since it was closed :D

**Comment by chessmango** [comment]
Same error as https://github.com/tidusjar/Ombi/issues/3420#issuecomment-716484846 here. :/
Fresh install - have recreated external DB and dumped/imported Plex DB in case of trouble, but no dice or signs of other issues. Manual marking it is.

**Comment by rafaelreis-r** [comment]
I'm also having this exact issue. Large library, Ombi uses 100% cpu for 40mins every hour. This is just terrible.

**Comment by swbradshaw** [comment]
Add me to the list having the same problem. I deleted OmbiExternal.db, and re-ran the Plex sync. The logs are filled with this error.

`Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: [. Path 'MediaContainer.Metadata[0].Guid', line 1, position 3059.

..
at Ombi.Api.Plex.PlexApi.GetMetadata(String authToken, String plexFullHost, Int32 itemId) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 159
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessServer(PlexServers servers, Boolean recentlyAddedSearch) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 264`


I removed my Plex server from Ombi, and re-added it.  Same problem.

Plex v1.21.0.3616
Ombo v3.0.5223.

**Comment by tidusjar** [comment]
Update to V4, it's been fixed there.

**Comment by misterjtc** [comment]
Will this be fixed in V3? or is V4 becoming master soon? This doesn't help a lot of us running on docker.

**Comment by tidusjar** [comment]
There's a docker tag available for v4

**Comment by ROODAY** [comment]
@tidusjar Is it possible to get V4 through the APT repo? I tried using the development release link for `ombi.list` but that only has 3.0.5227 as the latest version. Is it simply a matter of it not being available yet through APT (in which case I don't mind waiting, just curious as to whether that was the right place to go)?

**Comment by StudioEtrange** [comment]
Where is the V4 ? Please made a tag into code source on github, not only on docker container

**Comment by jumbi77** [comment]
I also got this error when running "manually run cacher". I am using emby though. Would be nice if ombi would just skip the specific movie instead of stopping the whole sync with emby/plex.

_...
2021-01-06 20:54:34.036 +00:00 [Information] Movie <deleted> does not have a ImdbId or TheMovieDbId, so rechecking emby
2021-01-06 20:54:34.036 +00:00 [Information] Checking server <deleted> for upto date metadata
2021-01-06 20:54:34.039 +00:00 [Error] StatusCode: InternalServerError, Reason: Internal Server Error, RequestUri: https://<deleted>/emby/users/<deleted>/items/341511
2021-01-06 20:54:34.045 +00:00 [Error] Exception when refreshing the Metadata Refresh
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: O. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at Ombi.Api.Emby.EmbyApi.GetInformation[T](String mediaId, String apiKey, String userId, String baseUrl)
   at Ombi.Api.Emby.EmbyApi.GetMovieInformation(String mediaId, String apiKey, String userId, String baseUrl)
   at Ombi.Schedule.Jobs.Ombi.RefreshMetadata.StartEmbyMovies(EmbySettings settings)
   at Ombi.Schedule.Jobs.Ombi.RefreshMetadata.StartEmby(EmbySettings s)
   at Ombi.Schedule.Jobs.Ombi.RefreshMetadata.Execute(IJobExecutionContext job)
2021-01-06 20:54:34.047 +00:00 [Debug] Trigger instruction : DeleteTrigger
2021-01-06 20:54:34.047 +00:00 [Debug] Deleting trigger
..._

**Comment by djsly** [comment]
v4 is broken when being a proxy,

**Comment by johns224** [comment]
This is happening to me too and it's driving me crazy.  Is this not ever going to be fixed in v3?  If not and I must upgrade to v4, can someone tell me roughly how to go about figuring this out in UnRaid?

**Comment by misterjtc** [comment]
> This is happening to me too and it's driving me crazy. Is this not ever going to be fixed in v3? If not and I must upgrade to v4, can someone tell me roughly how to go about figuring this out in UnRaid?

You can update the repository line when you edit the container template.

For example I am using the lsio container and I just put:

linuxserver/ombi:v4-preview

**Comment by johns224** [comment]
Thanks @misterjtc  - that worked.  However, it still didn't fix my problem.  When testing the newsletter I still see this in the logs, with no movies showing up in the newsletter (I made sure that there were new ones added before testing):

StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/tv/?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=external_ids
