### ISSUE TITLE
Failing to add requests to Sonarr

### ISSUE THREAD

**Issue by jes1417** [tidusjar/Ombi#3434]
**Describe the bug**
When trying to approve or add any shows to Sonarr I get the notification that the request was approved but it never gets added to Sonarr. Everything worked fine for months then just stopped one day.

**To Reproduce**
1. Go to 'Requests'
2. Click on 'click on approve'
4. See error 'no error shown it looks like everything is added'

**Expected behavior**
Show should be added to Sonarr

**Screenshots**
```
If applicable, add screenshots to help explain your problem.

**Logs (Logs directory where Ombi is located)**
fail: Ombi.Api.Api[1000]
      StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://192.168.1.243:8989/api/series/
fail: Ombi.Api.Api[1000]
      StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://192.168.1.243:8989/api/series/
fail: Ombi.Api.Api[1000]
      StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://192.168.1.243:8989/api/series/0
fail: Ombi.Notifications.NotificationService[4000]
      Failed to notify for notification: Ombi.Notifications.Agents.MobileNotification
System.Net.Http.HttpRequestException: Cannot assign requested address ---> System.Net.Sockets.SocketException: Cannot assign requested address
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request) in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
   at Ombi.Api.Notifications.OneSignalApi.PushNotification(List`1 playerIds, String message, Boolean isAdminNotification, Int32 requestId, Int32 requestType) in C:\projects\requestplex\src\Ombi.Api.Notifications\OneSignalApi.cs:line 55
   at Ombi.Notifications.Agents.MobileNotification.Send(List`1 playerIds, NotificationMessage model, MobileNotificationSettings settings, NotificationOptions requestModel, Boolean isAdminNotification) 
in C:\projects\requestplex\src\Ombi.Notifications\Agents\MobileNotification.cs:line 222
   at Ombi.Notifications.Agents.MobileNotification.RequestApproved(NotificationOptions model, MobileNotificationSettings settings) in C:\projects\requestplex\src\Ombi.Notifications\Agents\MobileNotification.cs:line 190
   at Ombi.Notifications.BaseNotification`1.NotifyAsync(NotificationOptions model, Settings settings) in C:\projects\requestplex\src\Ombi.Notifications\BaseNotification.cs:line 96
   at Ombi.Notifications.BaseNotification`1.NotifyAsync(NotificationOptions model) in C:\projects\requestplex\src\Ombi.Notifications\BaseNotification.cs:line 58
   at Ombi.Notifications.NotificationService.NotifyAsync(INotification notification, NotificationOptions model) in C:\projects\requestplex\src\Ombi.Notifications\NotificationService.cs:line 49
```

**Desktop (please complete the following information):**
 - OS: Debian 4.19.67 in Docker

**Ombi Version (please complete the following information):**
 - Version 3.0.5083
- Sonarr  3.0.3.728-ls184 by linuxserver.io

**Comment by jes1417** [comment]
Should I just trash my config and start over?

**Comment by jes1417** [comment]
I started over and sonar is working as expected, not sure what went wrong but deleting everything in my config directory and starting fresh fixed my issues.
