### ISSUE TITLE
System.ArgumentNullException: Value cannot be null. Parameter name: user

### ISSUE THREAD

**Issue by ShiroiKuma** [tidusjar/Ombi#3452]
**Describe the bug**
When calling either `/api/v1/Request/tv` or `api/v1/Request/movie` to get a list of request using an ApiKey, the result is a failure.

**To Reproduce**
1. Go to `/swagger/index.html`
2. Scroll down to `/api/v1/Request/tv`
3. Click `Try it out`
4. Enter valid API Key
5. See Error

**Expected behavior**
A 200 response with JSON output as documented.

**Logs (Logs directory where Ombi is located)**
```
2020-03-29 06:42:19.080 +00:00 [Error] Something bad happened, ErrorMiddleware caught this
System.ArgumentNullException: Value cannot be null.
Parameter name: user
   at Microsoft.AspNetCore.Identity.UserManager`1.IsInRoleAsync(TUser user, String role)
   at Ombi.Core.Engine.Interfaces.BaseEngine.IsInRole(String roleName) in C:\projects\requestplex\src\Ombi.Core\Engine\Interfaces\BaseEngine.cs:line 42
   at Ombi.Core.Engine.BaseMediaEngine.HideFromOtherUsers() in C:\projects\requestplex\src\Ombi.Core\Engine\BaseMediaEngine.cs:line 114
   at Ombi.Core.Engine.TvRequestEngine.GetRequests() in C:\projects\requestplex\src\Ombi.Core\Engine\TvRequestEngine.cs:line 206
   at Ombi.Controllers.RequestController.GetTvRequests() in C:\projects\requestplex\src\Ombi\Controllers\RequestController.cs:line 252
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Ombi.ApiKeyMiddlewear.ValidateApiKey(HttpContext context, RequestDelegate next, String key) in C:\projects\requestplex\src\Ombi\Middleware\ApiKeyMiddlewear.cs:line 125
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ApiKeyMiddlewear.cs:line 34
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ErrorHandlingMiddlewear.cs:line 24
```

**Desktop (please complete the following information):**
 - OS: Debian 10.3

**Ombi Version (please complete the following information):**
 - Version 3.0.4892
 - Media Server Plex

**Additional context**
Can be resolved by adding `UserName:` to the header before calling API from application. Doesn't work from swagger though.

**Comment by tidusjar** [comment]
Swagger for Ombi is used for discovery of the API's id recommend reading the wiki and not using swagger for testing the api's

**Comment by ShiroiKuma** [comment]
```
NOTE when using the API Key then everything is assumed as admin and there is no user associated with it, If you want it to be associated with a user you need to pass an additional header "UserName" with the value being the username of the user. If the username does not exist then the API call will not work.
```

Running `curl -i -X GET -H "accept: application/json" -H "ApiKey: <APIKeyFromUI>" "http://localhost:5000/api/v1/Request/tv"` or `curl -i -X GET -H "accept: application/json" -H "ApiKey: <APIKeyFromUI>" "http://localhost:5000/api/v1/Request/movie"`

Both respond with the same error

```
{"error":"Value cannot be null.\nParameter name: user"}
```

The only way to get these to work is to put in a UserName header of a valid User along with the API. The wiki clearly states it should assume as admin and no user is associated with it.

Swagger is just easier replication steps for you. If you prefer CURL examples instead, then so be it.

**Comment by 9Mad-Max5** [comment]
I can confirm that, the header need to be edited as well for the post section. There needs to be a filed to enter a UserName.

**Comment by that1guy151** [comment]
I'm having this issue as well. I am unable to connect Ombi via API to organizr or grafana to get request lists.
