### ISSUE TITLE
Ombi cannot Test Plex Connection

### ISSUE THREAD

**Issue by jahknem** [tidusjar/Ombi#3478]
**Describe the bug**
Ombi throws an Error in the Log when testing connectivity to the Plex Server and when running a Full/added Sync. It does however correctly grab the available servers and the plex token as well as machine identifier.
I also do not get a notification on the website that an error was thrown.

**To Reproduce**
1. Go to 'Mediaserver -> Plex'
2. Click on 'Test Connectivity'
3. Take a log at /etc/Ombi/logs/"latest".txt

**Expected behavior**
I expect Ombi to connect to my Plex Server and run the sync jobs correctly.

**Logs (Logs directory where Ombi is located)**
```
2020-04-07 11:55:47.355 +00:00 [Debug] Batch acquisition of 1 triggers
2020-04-07 11:55:47.355 +00:00 [Debug] Trigger instruction : DeleteTrigger
2020-04-07 11:55:47.355 +00:00 [Debug] Deleting trigger
2020-04-07 11:55:47.356 +00:00 [Debug] Batch acquisition of 0 triggers
2020-04-07 11:55:47.356 +00:00 [Debug] Calling Execute on job Plex.IPlexAvailabilityChecker
2020-04-07 11:55:47.358 +00:00 [Debug] Trigger instruction : DeleteTrigger
2020-04-07 11:55:47.359 +00:00 [Debug] Deleting trigger
2020-04-07 11:56:10.600 +00:00 [Debug] Batch acquisition of 0 triggers
2020-04-07 11:56:38.793 +00:00 [Debug] Batch acquisition of 0 triggers
2020-04-07 11:57:06.433 +00:00 [Debug] Batch acquisition of 0 triggers
2020-04-07 11:57:32.549 +00:00 [Debug] Batch acquisition of 0 triggers
2020-04-07 11:57:54.531 +00:00 [Error] Could not test Plex
System.OperationCanceledException: The operation was canceled.
   at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request) in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
   at Ombi.Api.Plex.PlexApi.GetStatus(String authToken, String uri) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 97
   at Ombi.Controllers.External.TesterController.Plex(PlexServers settings) in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 272
2020-04-07 11:57:57.961 +00:00 [Error] Could not test Plex
System.OperationCanceledException: The operation was canceled.
   at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request) in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
   at Ombi.Api.Plex.PlexApi.GetStatus(String authToken, String uri) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 97
   at Ombi.Controllers.External.TesterController.Plex(PlexServers settings) in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 272
```
**Logs Round Two:**
```
root@somename:~# tail -f /etc/Ombi/Logs/log-20200407.txt
2020-04-07 12:09:54.421 +00:00 [Information] JobFactory set to: Ombi.Schedule.IoCJobFactory
2020-04-07 12:09:54.504 +00:00 [Information] Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
2020-04-07 12:09:54.509 +00:00 [Debug] Batch acquisition of 1 triggers
2020-04-07 12:10:00.008 +00:00 [Debug] Batch acquisition of 0 triggers
2020-04-07 12:10:00.035 +00:00 [Debug] Calling Execute on job DVR.ISonarrSync
2020-04-07 12:10:00.413 +00:00 [Debug] Trigger instruction : NoInstruction
2020-04-07 12:10:28.088 +00:00 [Debug] Batch acquisition of 0 triggers
2020-04-07 12:10:53.234 +00:00 [Debug] Batch acquisition of 0 triggers
2020-04-07 12:11:16.534 +00:00 [Debug] Batch acquisition of 0 triggers
2020-04-07 12:11:42.705 +00:00 [Debug] Batch acquisition of 0 triggers
2020-04-07 12:12:07.369 +00:00 [Debug] Batch acquisition of 0 triggers
2020-04-07 12:12:37.029 +00:00 [Debug] Batch acquisition of 0 triggers
2020-04-07 12:13:05.644 +00:00 [Debug] Batch acquisition of 0 triggers
2020-04-07 12:13:10.188 +00:00 [Warning] Error thrown when attempting to obtain the plex libs
System.OperationCanceledException: The operation was canceled.
   at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request) in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
   at Ombi.Api.Plex.PlexApi.GetLibrarySections(String authToken, String plexFullHost) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 120
   at Ombi.Controllers.External.PlexController.GetPlexLibraries(PlexServers settings) in C:\projects\requestplex\src\Ombi\Controllers\External\PlexController.cs:line 109
2020-04-07 12:13:10.587 +00:00 [Warning] Error thrown when attempting to obtain the plex libs
System.OperationCanceledException: The operation was canceled.
   at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request) in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
   at Ombi.Api.Plex.PlexApi.GetLibrarySections(String authToken, String plexFullHost) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 120
   at Ombi.Controllers.External.PlexController.GetPlexLibraries(PlexServers settings) in C:\projects\requestplex\src\Ombi\Controllers\External\PlexController.cs:line 109
2020-04-07 12:13:29.288 +00:00 [Warning] Error thrown when attempting to obtain the plex libs
System.OperationCanceledException: The operation was canceled.
   at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request) in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
   at Ombi.Api.Plex.PlexApi.GetLibrarySections(String authToken, String plexFullHost) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 120
   at Ombi.Controllers.External.PlexController.GetPlexLibraries(PlexServers settings) in C:\projects\requestplex\src\Ombi\Controllers\External\PlexController.cs:line 109
2020-04-07 12:13:34.186 +00:00 [Debug] Batch acquisition of 0 triggers
2020-04-07 12:13:47.630 +00:00 [Error] Could not test Plex
System.OperationCanceledException: The operation was canceled.
   at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request) in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
   at Ombi.Api.Plex.PlexApi.GetStatus(String authToken, String uri) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 97
   at Ombi.Controllers.External.TesterController.Plex(PlexServers settings) in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 272
2020-04-07 12:14:00.190 +00:00 [Debug] Batch acquisition of 0 triggers
```

**Desktop (please complete the following information):**
 - OS: Debian Buster LXC Container on Proxmox
 - Detailed: Linux 5.3.18-2-pve #1 SMP PVE 5.3.18-2 (Sat, 15 Feb 2020 15:11:52 +0100)

**Ombi Version (please complete the following information):**
 - Version: 3.0.4892 
 - Media Server: Plex Media Server Version Version 1.18.8.2527

**Comment by tidusjar** [comment]
Have you checked to ensure your details are correct in the settings? e.g. Port

**Comment by jahknem** [comment]
Yes I have. I am using the public port (which is the same as the private) as well as the public IP address. I can access the server over the public IP address without a hitch (Tried it from a different network of course)
Also radarr and sonarr have successfully connected using the same network settings.
Shouldn't the GUI throw an error if my network settings where wrong? Instead of the program throwing an exception?

**Comment by jahknem** [comment]
Yes I have and I have also tried to do that, however it did not work even after rebooting the host
