### ISSUE TITLE
Impossible to connect a Jellyfin server to Ombi

### ISSUE THREAD

**Issue by mattthhdp** [tidusjar/Ombi#3505]
**Describe the bug**
Got an error into the debug log when trying to connect jellyfin with ombi

**To Reproduce**
Install both ombi and jellyfin (lastest version available on Linuxserver)

Ombi version 4.0.291.0 (image: linuxserver/ombi:v4-preview)
Jellyfin version 10.5.4   (image: linuxserver/jellyfin)

**Expected behavior**
Ombi should connect to jellyfin

**Screenshots**
![chrome_2020-04-22_13-44-30](https://user-images.githubusercontent.com/10604324/80016961-d49ecf00-84a1-11ea-86c3-2833e9b24105.png)

**Logs (Logs directory where Ombi is located)**
```
Fail: Ombi.Controllers.V1.External.TesterController[1000]


      Could not test Emby


Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.


   at Newtonsoft.Json.JsonTextReader.ParseValue()


   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)


   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)


   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)


   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)


   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)


   at Ombi.Api.Api.Request[T](Request request, CancellationToken cancellationToken) in /home/vsts/work/1/s/src/Ombi.Api/Api.cs:line 81


   at Ombi.Api.Emby.EmbyApi.GetUsers(String baseUri, String apiKey) in /home/vsts/work/1/s/src/Ombi.Api.Emby/EmbyApi.cs:line 33


   at Ombi.Controllers.V1.External.TesterController.Emby(EmbyServers settings) in /home/vsts/work/1/s/src/Ombi/Controllers/V1/External/TesterController.cs:line 326
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Ombi Version (please complete the following information):**
 -Ombi: Version 4.0.291.0
- Jellyfin: Version 10.5.4

**Comment by tidusjar** [comment]
Can you try using the IP address? Very strange since your settings look ok

**Comment by Ashyni** [comment]
Hello, i have the same issue, and it seems related to the base url use by jellyfin not configurable in Ombi v4, adding this settings and make the change in all api url should be enough.
https://github.com/jellyfin/jellyfin/releases/tag/v10.4.1
Before 1.4.1 http://mydomain.com/jellyfin/system/info
Since 1.4.1 http://mydomain.com/system/info
All people that use jellyfin before 1.4.1 and didn't make the change have Ombi v4 working but new user don't.

**Comment by mattthhdp** [comment]
@tidusjar  i got the same error with the ip address (with http and without http)

@Ashyni i do have /jellyfin as my base url into jellyfin, i will try removing it but as you said, it should work.

**Comment by Maltahl** [comment]
I have this same problem
Logs here:
https://pastebin.com/LfwV1fDF
Jellyfin runs on Version: 10.5.4 with base url /jellyfin ( i know but it is required to work with a reverse proxy)
Anything you guys want to me try out ?

@mattthhdp did you try and remove /jellyfin as base url in Jellyfin and now did it go ?

**Comment by mattthhdp** [comment]
Sorry for the wait ... Crazy at the office.
I do have remove the /jellyfin as base URL and it's working !
A big thank you to the team . Keep on the good work.

**Comment by Maltahl** [comment]
I can confirm removing /jellyfin ( or anything from base url inside of Jellyfin) fixes the problem.

I recommend that we can add the base url in Ombi so we dont have to compromise our proxy setups for Ombi to work with Jellyfin.

**Comment by tidusjar** [comment]
Added to V4 and V3

**Comment by Ashyni** [comment]
Hello, it's still a problem for me, `src/Ombi.Api.Emby/JellyfinApi.cs` need change to remove `jellyfin/` from api call.

Logs:
```
fail: Ombi.Api.Api[1000]
      StatusCode: NotFound, Reason: Not Found, RequestUri: http://jellyfin:8096/jellyfin/users
fail: Ombi.Controllers.V1.External.TesterController[1000]
      Could not test Emby
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: U. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request, CancellationToken cancellationToken) in /home/vsts/work/1/s/src/Ombi.Api/Api.cs:line 90
   at Ombi.Api.Emby.JellyfinApi.GetUsers(String baseUri, String apiKey) in /home/vsts/work/1/s/src/Ombi.Api.Emby/JellyfinApi.cs:line 32
   at Ombi.Controllers.V1.External.TesterController.Emby(EmbyServers settings) in /home/vsts/work/1/s/src/Ombi/Controllers/V1/External/TesterController.cs:line 326
```
