### ISSUE TITLE
Notification failure/error

### ISSUE THREAD

**Issue by mhbates** [tidusjar/Ombi#3511]
**Describe the bug**
A user requested a movie. The movie was acquired, but there was no notification about the request, nor was the request stored in the Requests section of Ombi.

**Expected behavior**
Email notification and storing of request in the Requests section.

**Logs (Logs directory where Ombi is located)**
```
2020-04-24 19:57:15.066 -07:00 [Error] Failed to notify for notification: EmailNotification { NotificationName: "EmailNotification" }
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Notifications.BaseNotification`1.LoadTemplate(NotificationAgent agent, NotificationType type, NotificationOptions model) in C:\projects\requestplex\src\Ombi.Notifications\BaseNotification.cs:line 174
   at Ombi.Notifications.Agents.EmailNotification.LoadTemplate(NotificationType type, NotificationOptions model, EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi.Notifications\Agents\EmailNotification.cs:line 59
   at Ombi.Notifications.Agents.EmailNotification.NewRequest(NotificationOptions model, EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi.Notifications\Agents\EmailNotification.cs:line 108
   at Ombi.Notifications.BaseNotification`1.NotifyAsync(NotificationOptions model, Settings settings) in C:\projects\requestplex\src\Ombi.Notifications\BaseNotification.cs:line 87
   at Ombi.Notifications.BaseNotification`1.NotifyAsync(NotificationOptions model) in C:\projects\requestplex\src\Ombi.Notifications\BaseNotification.cs:line 58
   at Ombi.Notifications.NotificationService.NotifyAsync(INotification notification, NotificationOptions model) in C:\projects\requestplex\src\Ombi.Notifications\NotificationService.cs:line 49
```

```
2020-04-24 19:57:45.244 -07:00 [Error] Failed to notify for notification: MobileNotification { NotificationName: "MobileNotification" }
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\First.cs:line 144
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\Select.cs:line 106
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\AsyncIterator.cs:line 98
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)
   at Ombi.Store.Repository.NotificationTemplatesRepository.GetTemplate(NotificationAgent agent, NotificationType type) in C:\projects\requestplex\src\Ombi.Store\Repository\NotificationTemplatesRepository.cs:line 38
   at Ombi.Notifications.BaseNotification`1.LoadTemplate(NotificationAgent agent, NotificationType type, NotificationOptions model) in C:\projects\requestplex\src\Ombi.Notifications\BaseNotification.cs:line 160
   at Ombi.Notifications.Agents.MobileNotification.NewRequest(NotificationOptions model, MobileNotificationSettings settings) in C:\projects\requestplex\src\Ombi.Notifications\Agents\MobileNotification.cs:line 50
   at Ombi.Notifications.BaseNotification`1.NotifyAsync(NotificationOptions model, Settings settings) in C:\projects\requestplex\src\Ombi.Notifications\BaseNotification.cs:line 87
   at Ombi.Notifications.BaseNotification`1.NotifyAsync(NotificationOptions model) in C:\projects\requestplex\src\Ombi.Notifications\BaseNotification.cs:line 58
   at Ombi.Notifications.NotificationService.NotifyAsync(INotification notification, NotificationOptions model) in C:\projects\requestplex\src\Ombi.Notifications\NotificationService.cs:line 49

```

**Desktop (please complete the following information):**
 - OS: Debian 9 running LinuxServer docker image

**Ombi Version (please complete the following information):**
 - Version 3.0.4892
- Media Server Plex

**Comment by mhbates** [comment]
It looks like a container restart may have fixed it. Still strange that it happened though, haven't seen this kind of failure before.

**Comment by mhbates** [comment]
This is still happening occasionally. Here are the logs this time. These same errors seem to be repeating.

```
2020-04-26 19:35:54.895 -07:00 [Error] Something bad happened, ErrorMiddleware caught this
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.WhereEnumerableAsyncIterator`1.MoveNextCore(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\Where.cs:line 106
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\AsyncIterator.cs:line 98
   at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\First.cs:line 144
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\Select.cs:line 106
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\AsyncIterator.cs:line 98
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)
   at Ombi.Core.Rule.Rules.Request.AutoApproveRule.Execute(BaseRequest obj) in C:\projects\requestplex\src\Ombi.Core\Rule\Rules\Request\AutoApproveRule.cs:line 27
   at Ombi.Core.Rule.RuleEvaluator.StartRequestRules(BaseRequest obj) in C:\projects\requestplex\src\Ombi.Core\Rule\RuleEvaluator.cs:line 42
   at Ombi.Core.Engine.Interfaces.BaseEngine.RunRequestRules(BaseRequest model) in C:\projects\requestplex\src\Ombi.Core\Engine\Interfaces\BaseEngine.cs:line 47
   at Ombi.Core.Engine.TvRequestEngine.RequestTvShow(TvRequestViewModel tv) in C:\projects\requestplex\src\Ombi.Core\Engine\TvRequestEngine.cs:line 62
   at Ombi.Controllers.RequestController.RequestTv(TvRequestViewModel tv) in C:\projects\requestplex\src\Ombi\Controllers\RequestController.cs:line 285
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ApiKeyMiddlewear.cs:line 51
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ErrorHandlingMiddlewear.cs:line 24
```

```
2020-04-26 19:37:53.772 -07:00 [Debug] Calling Execute on job Notifications.INotificationService
2020-04-26 19:38:02.621 -07:00 [Error] Something bad happened, ErrorMiddleware caught this
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.WhereEnumerableAsyncIterator`1.MoveNextCore(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\Where.cs:line 106
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\AsyncIterator.cs:line 98
   at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\First.cs:line 144
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\Select.cs:line 106
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\AsyncIterator.cs:line 98
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)
   at Ombi.Core.Engine.Interfaces.BaseEngine.GetUser() in C:\projects\requestplex\src\Ombi.Core\Engine\Interfaces\BaseEngine.cs:line 32
   at Ombi.Core.Engine.TvRequestEngine.RequestTvShow(TvRequestViewModel tv) in C:\projects\requestplex\src\Ombi.Core\Engine\TvRequestEngine.cs:line 52
   at Ombi.Controllers.RequestController.RequestTv(TvRequestViewModel tv) in C:\projects\requestplex\src\Ombi\Controllers\RequestController.cs:line 285
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ApiKeyMiddlewear.cs:line 51
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ErrorHandlingMiddlewear.cs:line 24
```

```
2020-04-26 19:38:23.849 -07:00 [Error] Failed to notify for notification: EmailNotification { NotificationName: "EmailNotification" }
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Notifications.BaseNotification`1.LoadTemplate(NotificationAgent agent, NotificationType type, NotificationOptions model) in C:\projects\requestplex\src\Ombi.Notifications\BaseNotification.cs:line 184
   at Ombi.Notifications.Agents.EmailNotification.LoadTemplate(NotificationType type, NotificationOptions model, EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi.Notifications\Agents\EmailNotification.cs:line 59
   at Ombi.Notifications.Agents.EmailNotification.NewRequest(NotificationOptions model, EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi.Notifications\Agents\EmailNotification.cs:line 108
   at Ombi.Notifications.BaseNotification`1.NotifyAsync(NotificationOptions model, Settings settings) in C:\projects\requestplex\src\Ombi.Notifications\BaseNotification.cs:line 87
   at Ombi.Notifications.BaseNotification`1.NotifyAsync(NotificationOptions model) in C:\projects\requestplex\src\Ombi.Notifications\BaseNotification.cs:line 58
   at Ombi.Notifications.NotificationService.NotifyAsync(INotification notification, NotificationOptions model) in C:\projects\requestplex\src\Ombi.Notifications\NotificationService.cs:line 49
```

**Comment by mhbates** [comment]
Did some more digging and it looks like I can't do anything with users. Can't change their settings. There's also one failed request in Settings->System, but it can't be deleted. Nothing happens when I click delete. I'm guessing this is related. Some DB problem.

**Comment by mhbates** [comment]
I'm assuming it was just SQLite getting overloaded and locking. I went ahead and migrated to a MariaDB database and it seems better, so far.
