### ISSUE TITLE
Discovery remains empty and throws SqliteException in logs

### ISSUE THREAD

**Issue by iammortimer** [tidusjar/Ombi#3524]
**Describe the bug**
Browsing the webinterface on Discover doesn't show any movies.

**To Reproduce**
1. Open the startpage and logon

**Expected behavior**
Show movies

**Screenshots**
![image](https://user-images.githubusercontent.com/44798984/80866071-16432d00-8c8d-11ea-9897-2b0f6d881c3a.png)

**Logs (Logs directory where Ombi is located)**
2020-05-02 15:49:51.785 +02:00 [Error] Something bad happened, ErrorMiddleware caught this
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: p.RequestId'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Ombi.Store.Repository.PlexServerContentRepository.Get(String providerId) in /home/vsts/work/1/s/src/Ombi.Store/Repository/PlexContentRepository.cs:line 66
   at Ombi.Core.Rule.Rules.Search.PlexAvailabilityRule.Execute(SearchViewModel obj) in /home/vsts/work/1/s/src/Ombi.Core/Rule/Rules/Search/PlexAvailabilityRule.cs:line 31
   at Ombi.Core.Rule.RuleEvaluator.StartSearchRules(SearchViewModel obj) in /home/vsts/work/1/s/src/Ombi.Core/Rule/RuleEvaluator.cs:line 54
   at Ombi.Core.Engine.Interfaces.BaseEngine.RunSearchRules(SearchViewModel model) in /home/vsts/work/1/s/src/Ombi.Core/Engine/Interfaces/BaseEngine.cs:line 53
   at Ombi.Core.Engine.V2.MovieSearchEngineV2.ProcessSingleMovie(SearchMovieViewModel viewMovie) in /home/vsts/work/1/s/src/Ombi.Core/Engine/V2/MovieSearchEngineV2.cs:line 318
   at Ombi.Core.Engine.V2.MovieSearchEngineV2.ProcessSingleMovie(MovieSearchResult movie) in /home/vsts/work/1/s/src/Ombi.Core/Engine/V2/MovieSearchEngineV2.cs:line 253
   at Ombi.Core.Engine.V2.MovieSearchEngineV2.TransformMovieResultsToResponse(IEnumerable`1 movies) in /home/vsts/work/1/s/src/Ombi.Core/Engine/V2/MovieSearchEngineV2.cs:line 245
   at Ombi.Core.Engine.V2.MovieSearchEngineV2.PopularMovies(Int32 currentlyLoaded, Int32 toLoad, CancellationToken cancellationToken) in /home/vsts/work/1/s/src/Ombi.Core/Engine/V2/MovieSearchEngineV2.cs:line 124
   at Ombi.Controllers.V2.SearchController.Popular(Int32 currentPosition, Int32 amountToLoad) in /home/vsts/work/1/s/src/Ombi/Controllers/V2/SearchController.cs:line 136
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in /home/vsts/work/1/s/src/Ombi/Middleware/ApiKeyMiddlewear.cs:line 51
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in /home/vsts/work/1/s/src/Ombi/Middleware/ErrorHandlingMiddlewear.cs:line 24

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise 1909

**Ombi Version (please complete the following information):**
 - Version 4.0.300
- Media Server Plex

**Comment by kat953162** [comment]
I have this issue I believe.

**Comment by tidusjar** [comment]
Delete your OmbiExternal.db and restart Ombi. Once you have done this you should be good to go
