### ISSUE TITLE
Notifications fail with Gmail Two-Factor Authentication

### ISSUE THREAD

**Issue by tjsnow** [tidusjar/Ombi#3542]
**Describe the bug**
I have been using gmail for a long time to send out notifications. I recently turned on the two-factor authentication for gmail and my notifications stopped working. I updated my password and tested it still fails. I have looked into the logs and get the below messages...

**To Reproduce**
1. Go to Notifications > Email
2. Fill out all fields for gmail account with two factor authentication turned on (smtp.gmail.com, port 587 with SMTP authentication enabled)
3. Click Test

**Expected behavior**
Expect test email to be sent successfully

**Screenshots**
N/A

**Logs (Logs directory where Ombi is located)**
2020-05-09 23:05:29.932 -06:00 [Warning] Exception when testing Email Notifications
MailKit.Security.AuthenticationException: AuthenticationMechanismTooWeak: 5.7.9 Application-specific password required. Learn more at
5.7.9  https://support.google.com/mail/?p=InvalidSecondFactor t88sm3244494ild.30 - gsmtp ---> MailKit.Net.Smtp.SmtpCommandException: 5.7.9 Application-specific password required. Learn more at
5.7.9  https://support.google.com/mail/?p=InvalidSecondFactor t88sm3244494ild.30 - gsmtp
   --- End of inner exception stack trace ---
   at MailKit.Net.Smtp.SmtpClient.AuthenticateAsync(Encoding encoding, ICredentials credentials, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
   at MailKit.MailService.Authenticate(String userName, String password, CancellationToken cancellationToken)
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 98
   at Ombi.Controllers.External.TesterController.Email(EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 251

**Desktop (please complete the following information):**

**Ombi Version (please complete the following information):**
 - Version [e.g. 3.0.1158]
- Media Server [e.g. Plex]

**Additional context**

**Comment by tjsnow** [comment]
FORGOT TO INCLUDE
**Desktop** 
OS: Windows 10

**Ombi Version (please complete the following information):**
Version 3.0.4680
Media Server Plex

**Comment by tidusjar** [comment]
You need to follow this and generate an app password:
https://support.google.com/mail/answer/185833?hl=en-GB
