### ISSUE TITLE
Not Displaying Movies - Middleware Error

### ISSUE THREAD

**Issue by sublimesed** [tidusjar/Ombi#3548]
**Describe the bug**
When you go to the Movie page (internally or externally) it doesn't load anything. TV Shows load and can be requested just fine. Here is what I see in the logs:

**To Reproduce**
1. Navigate to Movie Search and it never loads

**Expected behavior**
Ability to load and request movies

**Screenshots**
![image](https://user-images.githubusercontent.com/38224321/81830633-efdd8700-9501-11ea-9c0d-5ae317c0407f.png)

**Logs (Logs directory where Ombi is located)**
`2020-05-13 10:01:50.385 -05:00 [Error] Something bad happened, ErrorMiddleware caught this
System.OperationCanceledException: The operation was canceled.
   at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request) in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
   at Ombi.Api.TheMovieDb.TheMovieDbApi.PopularMovies(String langCode) in C:\projects\requestplex\src\Ombi.TheMovieDbApi\TheMovieDbApi.cs:line 148
   at Ombi.Core.Engine.MovieSearchEngine.<PopularMovies>b__15_0() in C:\projects\requestplex\src\Ombi.Core\Engine\MovieSearchEngine.cs:line 123
   at Ombi.Helpers.CacheService.GetOrAdd[T](String cacheKey, Func`1 factory, DateTime absoluteExpiration)
   at Ombi.Core.Engine.MovieSearchEngine.PopularMovies() in C:\projects\requestplex\src\Ombi.Core\Engine\MovieSearchEngine.cs:line 120
   at Ombi.Controllers.SearchController.Popular() in C:\projects\requestplex\src\Ombi\Controllers\SearchController.cs:line 194
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ApiKeyMiddlewear.cs:line 51
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ErrorHandlingMiddlewear.cs:line 24`

**Desktop (please complete the following information):**
 - OS: Win7 Pro SP1 x64

**Ombi Version (please complete the following information):**
- Version: 3.0.5140
- Media Server: Plex

**Additional context**
N/A

**Comment by randybruder** [comment]
Have the same issue on 3.0.4892 (current stable) on macOS 10.13.6

**Comment by hotleadsingerguy** [comment]
Same issue on 3.0.4892 (current stable) on Ubuntu 18.04.

**Comment by sublimesed** [comment]
I didn't change anything and it's working now?

**Comment by randybruder** [comment]
Issue persists for me. Movie searches never load.

**Comment by RedBeer** [comment]
Same issue here.. tried another port and a fresh install.. same problem (win 10)

**Comment by randybruder** [comment]
@sublimesed Please re-open the issue, I don't believe it should be considered closed.

**Comment by sublimesed** [comment]
> @sublimesed Please re-open the issue, I don't believe it should be considered closed.

Done.  It's working for me still, but I'll leave it open for others.

**Comment by philophizer** [comment]
I'm having this same issue, I'm getting an error on the iPhone app as well (see below)

![unnamed (2)](https://user-images.githubusercontent.com/21305714/82522680-7f6fdf00-9b6d-11ea-8e61-6561ce5cb9fe.jpg)

**Comment by randybruder** [comment]
Found this on Discord:

> for some reaseon Movie searching isn't working
> It's bringing up no results
> TV Show searching is working fine, but not movies

> @tidusjar:
> delete your `ombiexternal.db` and restart ombi. This is a one time thing

Worked for me.

**Comment by philophizer** [comment]
100% worked for me also, thanks!

**Comment by brygphilomena** [comment]
I had to apply the following to get movies to show up again in Ombi.db following an update.

```
ALTER TABLE MovieRequests ADD COLUMN RequestedByAlias TEXT NULL;
ALTER TABLE MovieRequests ADD COLUMN LangCode TEXT NULL;
```

**Comment by RedBeer** [comment]
I tried both.. didn't work for me. 
I get the error message:  
`fail: Ombi.Api.Api[1000]
      StatusCode: Forbidden, Reason: Forbidden, RequestUri: http://api.themoviedb.org/3`

I tried downloading ombi again.. clean install.. nothing changed.

**Comment by tidusjar** [comment]
This issue is pretty hard to diagnose the issue since the original issue has been fixed. If you are still having problems please raise a new issue
