### ISSUE TITLE
Ombi v4 Caching Fails

### ISSUE THREAD

**Issue by soccerdmon11** [tidusjar/Ombi#3557]
**Describe the bug**
When running a Full Scan for Plex, it fails part way through the caching stating an issue with a translation.

**To Reproduce**
1. Go to: Settings -> Media Server -> Plex
2. Click on: Manually Run Full Scan

**Expected behavior**
All Movies and TV Shows in my Library are linked in Ombi to determine whether the item is available or not.

**Logs (Logs directory where Ombi is located)**
2020-05-21 09:39:10.799 -07:00 [Information] Total Epsiodes found for TV Shows = 30259
2020-05-21 09:39:10.934 -07:00 [Information] Processed 150 more episodes. Total Remaining 30109
2020-05-21 09:39:11.017 -07:00 [Information] Processed 150 more episodes. Total Remaining 29959
2020-05-21 09:39:11.102 -07:00 [Information] Processed 150 more episodes. Total Remaining 29809
2020-05-21 09:39:11.182 -07:00 [Information] Processed 150 more episodes. Total Remaining 29659
2020-05-21 09:39:11.264 -07:00 [Information] Processed 150 more episodes. Total Remaining 29509
2020-05-21 09:39:11.346 -07:00 [Information] Processed 150 more episodes. Total Remaining 29359
2020-05-21 09:39:11.427 -07:00 [Information] Processed 150 more episodes. Total Remaining 29209
2020-05-21 09:39:11.511 -07:00 [Information] Processed 150 more episodes. Total Remaining 29059
2020-05-21 09:39:11.592 -07:00 [Information] Processed 150 more episodes. Total Remaining 28909
2020-05-21 09:39:11.673 -07:00 [Information] Processed 150 more episodes. Total Remaining 28759
2020-05-21 09:39:11.754 -07:00 [Information] Processed 150 more episodes. Total Remaining 28609
2020-05-21 09:39:11.839 -07:00 [Information] Processed 150 more episodes. Total Remaining 28459
2020-05-21 09:39:11.928 -07:00 [Information] Processed 150 more episodes. Total Remaining 28309
2020-05-21 09:39:12.008 -07:00 [Information] Processed 150 more episodes. Total Remaining 28159
2020-05-21 09:39:12.089 -07:00 [Information] Processed 150 more episodes. Total Remaining 28009
2020-05-21 09:39:12.169 -07:00 [Information] Processed 150 more episodes. Total Remaining 27859
2020-05-21 09:39:12.249 -07:00 [Information] Processed 150 more episodes. Total Remaining 27709
2020-05-21 09:39:12.332 -07:00 [Information] Processed 150 more episodes. Total Remaining 27559
2020-05-21 09:39:12.419 -07:00 [Information] Processed 150 more episodes. Total Remaining 27409
2020-05-21 09:39:12.505 -07:00 [Information] Processed 150 more episodes. Total Remaining 27259
2020-05-21 09:39:12.591 -07:00 [Information] Processed 150 more episodes. Total Remaining 27109
2020-05-21 09:39:12.672 -07:00 [Information] Processed 150 more episodes. Total Remaining 26959
2020-05-21 09:39:12.756 -07:00 [Information] Processed 150 more episodes. Total Remaining 26809
2020-05-21 09:39:12.836 -07:00 [Information] Processed 150 more episodes. Total Remaining 26659
2020-05-21 09:39:12.917 -07:00 [Information] Processed 150 more episodes. Total Remaining 26509
2020-05-21 09:39:13.002 -07:00 [Information] Processed 150 more episodes. Total Remaining 26359
2020-05-21 09:39:13.083 -07:00 [Information] Processed 150 more episodes. Total Remaining 26209
2020-05-21 09:39:13.170 -07:00 [Information] Processed 150 more episodes. Total Remaining 26059
2020-05-21 09:39:13.252 -07:00 [Information] Processed 150 more episodes. Total Remaining 25909
2020-05-21 09:39:13.337 -07:00 [Information] Processed 150 more episodes. Total Remaining 25759
2020-05-21 09:39:13.419 -07:00 [Information] Processed 150 more episodes. Total Remaining 25609
2020-05-21 09:39:13.503 -07:00 [Information] Processed 150 more episodes. Total Remaining 25459
2020-05-21 09:39:13.584 -07:00 [Information] Processed 150 more episodes. Total Remaining 25309
2020-05-21 09:39:13.667 -07:00 [Information] Processed 150 more episodes. Total Remaining 25159
2020-05-21 09:39:13.749 -07:00 [Information] Processed 150 more episodes. Total Remaining 25009
2020-05-21 09:39:13.832 -07:00 [Information] Processed 150 more episodes. Total Remaining 24859
2020-05-21 09:39:13.916 -07:00 [Information] Processed 150 more episodes. Total Remaining 24709
2020-05-21 09:39:14.001 -07:00 [Information] Processed 150 more episodes. Total Remaining 24559
2020-05-21 09:39:14.083 -07:00 [Information] Processed 150 more episodes. Total Remaining 24409
2020-05-21 09:39:14.166 -07:00 [Information] Processed 150 more episodes. Total Remaining 24259
2020-05-21 09:39:14.251 -07:00 [Information] Processed 150 more episodes. Total Remaining 24109
2020-05-21 09:39:14.335 -07:00 [Information] Processed 150 more episodes. Total Remaining 23959
2020-05-21 09:39:14.418 -07:00 [Information] Processed 150 more episodes. Total Remaining 23809
2020-05-21 09:39:14.500 -07:00 [Information] Processed 150 more episodes. Total Remaining 23659
2020-05-21 09:39:14.584 -07:00 [Information] Processed 150 more episodes. Total Remaining 23509
2020-05-21 09:39:14.667 -07:00 [Information] Processed 150 more episodes. Total Remaining 23359
2020-05-21 09:39:14.753 -07:00 [Information] Processed 150 more episodes. Total Remaining 23209
2020-05-21 09:39:14.838 -07:00 [Information] Processed 150 more episodes. Total Remaining 23059
2020-05-21 09:39:14.923 -07:00 [Information] Processed 150 more episodes. Total Remaining 22909
2020-05-21 09:39:15.016 -07:00 [Information] Processed 150 more episodes. Total Remaining 22759
2020-05-21 09:39:15.101 -07:00 [Information] Processed 150 more episodes. Total Remaining 22609
2020-05-21 09:39:15.185 -07:00 [Information] Processed 150 more episodes. Total Remaining 22459
2020-05-21 09:39:15.264 -07:00 [Information] Processed 150 more episodes. Total Remaining 22309
2020-05-21 09:39:15.349 -07:00 [Information] Processed 150 more episodes. Total Remaining 22159
2020-05-21 09:39:15.434 -07:00 [Information] Processed 150 more episodes. Total Remaining 22009
2020-05-21 09:39:15.517 -07:00 [Information] Processed 150 more episodes. Total Remaining 21859
2020-05-21 09:39:15.599 -07:00 [Information] Processed 150 more episodes. Total Remaining 21709
2020-05-21 09:39:15.682 -07:00 [Information] Processed 150 more episodes. Total Remaining 21559
2020-05-21 09:39:15.761 -07:00 [Information] Processed 150 more episodes. Total Remaining 21409
2020-05-21 09:39:15.843 -07:00 [Information] Processed 150 more episodes. Total Remaining 21259
2020-05-21 09:39:15.925 -07:00 [Information] Processed 150 more episodes. Total Remaining 21109
2020-05-21 09:39:15.996 -07:00 [Information] Processed 150 more episodes. Total Remaining 20959
2020-05-21 09:39:16.081 -07:00 [Information] Processed 150 more episodes. Total Remaining 20809
2020-05-21 09:39:16.153 -07:00 [Information] Processed 150 more episodes. Total Remaining 20659
2020-05-21 09:39:16.240 -07:00 [Information] Processed 150 more episodes. Total Remaining 20509
2020-05-21 09:39:16.325 -07:00 [Information] Processed 150 more episodes. Total Remaining 20359
2020-05-21 09:39:16.407 -07:00 [Information] Processed 150 more episodes. Total Remaining 20209
2020-05-21 09:39:16.493 -07:00 [Information] Processed 150 more episodes. Total Remaining 20059
2020-05-21 09:39:16.578 -07:00 [Information] Processed 150 more episodes. Total Remaining 19909
2020-05-21 09:39:16.643 -07:00 [Error] Caching Episodes Failed
System.InvalidOperationException: The LINQ expression 'DbSet<PlexServerContent>
    .Where(p => p.Title.Equals(
        value: __episode_grandparentTitle_0, 
        comparisonType: CurrentCultureIgnoreCase))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|8_0(ShapedQueryExpression translated, <>c__DisplayClass8_0& )
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, LambdaExpression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, Expression`1 predicate, CancellationToken cancellationToken)
   at Ombi.Schedule.Jobs.Plex.PlexEpisodeSync.ProcessEpsiodes(Metadata[] episodes, IQueryable`1 currentEpisodes)
   at Ombi.Schedule.Jobs.Plex.PlexEpisodeSync.GetEpisodes(PlexServers settings, Directory section) in /home/vsts/work/1/s/src/Ombi.Schedule/Jobs/Plex/PlexEpisodeSync.cs:line 140
   at Ombi.Schedule.Jobs.Plex.PlexEpisodeSync.Cache(PlexServers settings) in /home/vsts/work/1/s/src/Ombi.Schedule/Jobs/Plex/PlexEpisodeSync.cs:line 94
   at Ombi.Schedule.Jobs.Plex.PlexEpisodeSync.Execute(IJobExecutionContext job) in /home/vsts/work/1/s/src/Ombi.Schedule/Jobs/Plex/PlexEpisodeSync.cs:line 55
2020-05-21 09:39:16.643 -07:00 [Debug] Batch acquisition of 1 triggers
2020-05-21 09:39:16.644 -07:00 [Debug] Trigger instruction : DeleteTrigger
2020-05-21 09:39:16.644 -07:00 [Debug] Deleting trigger
2020-05-21 09:39:16.644 -07:00 [Debug] Batch acquisition of 1 triggers
2020-05-21 09:39:16.644 -07:00 [Debug] Calling Execute on job System.IRefreshMetadata
2020-05-21 09:39:16.644 -07:00 [Debug] Batch acquisition of 0 triggers
2020-05-21 09:39:16.644 -07:00 [Debug] Calling Execute on job Plex.IPlexAvailabilityChecker
2020-05-21 09:39:16.650 -07:00 [Information] Starting the Metadata refresh

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.3

**Ombi Version (please complete the following information):**
- Version 4.0.332.0
- Media Server: Plex

**Comment by tidusjar** [comment]
Thanks! I'll get this fixed

**Comment by tidusjar** [comment]
Fixed
