### ISSUE TITLE
Ombi4 - Recently Added Sync Not Working

### ISSUE THREAD

**Issue by dmike3** [tidusjar/Ombi#3563]
**Describe the bug**
When using Ombi4 it's not syncing recently added content.

**To Reproduce**
Do a manual Recently Added Sync after adding a movie or TV show that was requested under Ombi4.

**Expected behavior**

It should be up the movie or tv show and mark it available

**Screenshots**
N/A

**Logs (Logs directory where Ombi is located)**
.

**Desktop (please complete the following information):**
Ubuntu

**Ombi Version (please complete the following information):**
 
Ombi4 - v4.0.339
Plex Media Server - Version 1.19.3.2843

**Additional context**
When using Ombi3 it works just fine. When I'm bouncing back between Ombi4 and Ombi3 I'm pointing it at the same database/config directory.

**Comment by patrick-motard** [comment]
@dmike3 this is used by the newsletter correct? Ive noticed that my newsletter hasn't been sending out lately. When I test it, it's supposed to send me an email with recently added within the past week or two, but instead it sends me an email with no new content added.

**Comment by dmike3** [comment]
> @dmike3 this is used by the newsletter correct? Ive noticed that my newsletter hasn't been sending out lately. When I test it, it's supposed to send me an email with recently added within the past week or two, but instead it sends me an email with no new content added.

I'm not getting anything when I tested.

I have to run a new test, I'm running the older version right now. I'm waiting for this version to go live and out of beta before using.

**Comment by soccerdmon11** [comment]
Hi,

Adding to this as I updated to Ombi v4.0.346.0 and Recently Added is erroring on me with these errors:

2020-06-06 13:08:19.882 -07:00 [Debug] Calling Execute on job Plex.IPlexContentSyncRecentlyAdded
2020-06-06 13:08:19.888 -07:00 [Information] Starting Plex Content Cacher Recently Added Scan
2020-06-06 13:08:19.888 -07:00 [Information] Starting to cache the content on server "HomeMediaServer"
2020-06-06 13:08:20.373 -07:00 [Warning] Exception thrown when attempting to cache the Plex Content in server "HomeMediaServer"
System.ArgumentException: An item with the same key has already been added. Key: 0
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessServer(PlexServers servers, Boolean recentlyAddedSearch) in /home/vsts/work/1/s/src/Ombi.Schedule/Jobs/Plex/PlexContentSync.cs:line 220
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.StartTheCache(PlexSettings plexSettings, Boolean recentlyAddedSearch) in /home/vsts/work/1/s/src/Ombi.Schedule/Jobs/Plex/PlexContentSync.cs:line 164
2020-06-06 13:08:20.373 -07:00 [Information] Finished Plex Content Cacher, with processed content: "Ombi.Schedule.Jobs.Plex.Models.ProcessedContent", episodes: 0. Recently Added Scan: True
2020-06-06 13:08:20.374 -07:00 [Debug] Trigger instruction : DeleteTrigger
2020-06-06 13:08:20.374 -07:00 [Debug] Deleting trigger

**Comment by esticle** [comment]
To confirm, this happens with Plex for me on version 4.0.358.0 still.

```
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server fblix
warn: Ombi.Schedule.Jobs.Plex.PlexContentSync[2008]
      Exception thrown when attempting to cache the Plex Content in server fblix
System.ArgumentException: An item with the same key has already been added. Key: 0
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessServer(PlexServers servers, Boolean recentlyAddedSearch) in /home/vsts/work/1/s/src/Ombi.Schedule/Jobs/Plex/PlexContentSync.cs:line 220
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.StartTheCache(PlexSettings plexSettings, Boolean recentlyAddedSearch) in /home/vsts/work/1/s/src/Ombi.Schedule/Jobs/Plex/PlexContentSync.cs:line 164
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Finished Plex Content Cacher, with processed content: Ombi.Schedule.Jobs.Plex.Models.ProcessedContent, episodes: 0. Recently Added Scan: True

```

Performing a full sync with Plex resolves this but is of course not a good solution.

**Comment by tidusjar** [comment]
Thanks for the logs guys, please try the new V4 version :D

**Comment by esticle** [comment]
Thanks, can confirm - looks good on v4.0.362.0

```
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher Recently Added Scan
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server mystuff
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Finished Plex Content Cacher, with processed content: Ombi.Schedule.Jobs.Plex.Models.ProcessedContent, episodes: 0. Recently Added Scan: True
```
