### ISSUE TITLE
Can't log in to Ombi (Resource Temporarily Unavailable)

### ISSUE THREAD

**Issue by leftovernick** [tidusjar/Ombi#3566]
**Describe the bug**
When I try to log in to Ombi it says wrong password even though there have been no password changes. I also can't connect using the app. I can get to the log in page, but can't get logged in. None of my other users can log in either.

I deleted the Ombi.db and let it recreate itself, but no change.

**Expected behavior**
Standard usage

**Logs (Logs directory where Ombi is located)**
[log-20200522.txt](https://github.com/tidusjar/Ombi/files/4671138/log-20200522.txt)
2020-05-22 21:05:51.466 -07:00 [Error] Something bad happened, ErrorMiddleware caught this
System.Net.Http.HttpRequestException: Resource temporarily unavailable ---> System.Net.Sockets.SocketException: Resource temporarily unavailable
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request) in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
   at Ombi.Api.FanartTv.FanartTvApi.GetMovieImages(String movieOrImdbId, String token) in C:\projects\requestplex\src\Ombi.Api.FanartTv\FanartTvApi.cs:line 42
   at Ombi.Controllers.ImagesController.GetBackgroundImage() in C:\projects\requestplex\src\Ombi\Controllers\ImagesController.cs:line 198
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ApiKeyMiddlewear.cs:line 51
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ErrorHandlingMiddlewear.cs:line 24

**Desktop (please complete the following information):**
 - OS: [Unraid]

**Ombi Version (please complete the following information):**
 - Version [Can't log in to see]
- Media Server [Plex]

**Comment by tidusjar** [comment]
That error is unfortunately nothing related to the login. 

You sure you have the correct accounts? Including entering the correct username and password?

Have you ever been able to login?

**Comment by leftovernick** [comment]
I think that the logging in issue may have been due to a DNS issue with setting up Pi-Hole. That's been resolved and I can log in again. I'm still getting the ErrorMiddleWare and am not getting many or any results when searching for titles. Movies won't return anything at all and tv shows only return a very limited set of results. Since I can log in now, I do have some more info.


Version | 3.0.4892
-- | --
Branch | master
Github | https://github.com/tidusjar/Ombi
Discord | https://discord.gg/Sa7wNWb
Reddit | https://www.reddit.com/r/Ombi/
Issues | https://github.com/tidusjar/Ombi/issues
Wiki | https://github.com/tidusjar/Ombi/wiki
OS Architecture | X64
OS Description | Linux 4.19.107-Unraid #1 SMP Thu Mar 5 13:55:57 PST 2020
Process Architecture | X64
Application Base Path | /opt/ombi
Storage Path | /config
Ombi Database | Sqlite - Data Source=/config/Ombi.db
External Database | Sqlite - Data Source=/config/OmbiExternal.db
Settings Database | Sqlite - Data Source=/config/OmbiSettings.db

Logs: [log-20200522.txt](https://github.com/tidusjar/Ombi/files/4672468/log-20200522.txt)

at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ApiKeyMiddlewear.cs:line 51
at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ErrorHandlingMiddlewear.cs:line 24

**Comment by tidusjar** [comment]
Delete the Ombi External.db and restart ombi

**Comment by leftovernick** [comment]
That resolved it, thank you,.
