### ISSUE TITLE
Ombi V4: Error requesting Movies, languageCode: null

### ISSUE THREAD

**Issue by GeneralDoddi** [tidusjar/Ombi#3579]
**Describe the bug**
While requesting a movie Ombi throws a Null reference error and doesn't request said movie.

**To Reproduce**
1. Go to 'Discover'
2. Click on  any kind of movie
3. Open network tab on inspect element 
4. Request a Movie
5. see response from Ombi 500 Internal Error

**Expected behavior**
Should request the movie and give a popup that it has been requested

**Screenshots**

![request](https://user-images.githubusercontent.com/3849042/82819021-367e9a00-9e8f-11ea-8988-7a6df5b5902e.JPG)

**Logs (Logs directory where Ombi is located)**
`2020-05-24 23:19:49.388 +00:00 [Error] Something bad happened, ErrorMiddleware caught this
System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , MovieRequests )
   at System.Linq.AsyncEnumerable.WhereEnumerableAsyncIterator`1.MoveNextCore(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\Where.cs:line 110
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\AsyncIterator.cs:line 112
   at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\First.cs:line 151
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\Select.cs:line 118
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\AsyncIterator.cs:line 112
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)
   at Ombi.Core.Rule.Rules.Request.ExistingMovieRequestRule.Execute(BaseRequest obj) in /home/vsts/work/1/s/src/Ombi.Core/Rule/Rules/Request/ExistingMovieRequestRule.cs:line 43
   at Ombi.Core.Rule.RuleEvaluator.StartRequestRules(BaseRequest obj) in /home/vsts/work/1/s/src/Ombi.Core/Rule/RuleEvaluator.cs:line 42
   at Ombi.Core.Engine.Interfaces.BaseEngine.RunRequestRules(BaseRequest model) in /home/vsts/work/1/s/src/Ombi.Core/Engine/Interfaces/BaseEngine.cs:line 47
   at Ombi.Core.Engine.MovieRequestEngine.RequestMovie(MovieRequestViewModel model) in /home/vsts/work/1/s/src/Ombi.Core/Engine/MovieRequestEngine.cs:line 95
   at Ombi.Controllers.V1.RequestController.RequestMovie(MovieRequestViewModel movie) in /home/vsts/work/1/s/src/Ombi/Controllers/V1/RequestController.cs:line 96
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in /home/vsts/work/1/s/src/Ombi/Middleware/ApiKeyMiddlewear.cs:line 58
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in /home/vsts/work/1/s/src/Ombi/Middleware/ErrorHandlingMiddlewear.cs:line 30`

**Desktop (please complete the following information):**
 - OS: Windows 10 (Ombi on Ubuntu 18.04.4)

**Ombi Version (please complete the following information):**
 - Version [4.0.186.0]
- Media Server [Plex]

**Additional context**
It seems like requesting TV shows works fine. but the UI gives no indication on this is failing other than not popping up the notification. My guess is this object reference because of the null languageCode

**Comment by tidusjar** [comment]
Is this with only certain movies?

**Comment by GeneralDoddi** [comment]
> Is this with only certain movies?

it seems to be all movies, (i've tried more movies so far and same result on all of them)

the ones i've picked so far just from the discover list:

Fun with Dick and Jane (2005)
Scoob!
Extraction
Inception

It seems like there is a difference between the inputs, back from when you select Request from the movie page itself it sends languageCode: null, but when you request from the modal it sends languageCode : ""

From the modal:
{theMovieDbId: 385103, languageCode: ""}
languageCode: ""
theMovieDbId: 385103

From the movie page 
{theMovieDbId: "385103", languageCode: null}
languageCode: null
theMovieDbId: "385103"

**Comment by tidusjar** [comment]
And just to confirm then, when requesting via the movie details page it works, but when requesting via the modal popup on the discover page it does not work?

**Comment by GeneralDoddi** [comment]
> And just to confirm then, when requesting via the movie details page it works, but when requesting via the modal popup on the discover page it does not work?

Sorry to not clarify, the request is broken on both types requests.

**Comment by GeneralDoddi** [comment]
The difference is that the modal request waits for a response which is stuck in loading

![asdasdsasd](https://user-images.githubusercontent.com/3849042/82956739-f6a7d780-9fa0-11ea-9712-7a8037e92184.JPG)

**Comment by GeneralDoddi** [comment]
I have tried to update to various releases to see if this has been fixed in later releases, it turns out the transition from v.4.0.186 to v4.0.356 did break the whole program. by rollbacking and stepping through each version after v4.0.186, the whole application breaks at v4.0.196. I am not quite sure why. v4.0.191 is the latest release that works as an application for me, i don't know why tho.

**Comment by GeneralDoddi** [comment]
From the source code i saw this line in /ClientApp/src/app/search/moviesearchgrid.component.ts

 this.requestService.requestMovie({ theMovieDbId: searchResult.id, languageCode: "en" })

for some reason languageCode is being sent as null

**Comment by tidusjar** [comment]
Please try the latest release from last night, if it's still and issue can you please upload some server logs

**Comment by GeneralDoddi** [comment]
> Please try the latest release from last night, if it's still and issue can you please upload some server logs

I have been trying that, but it seems like all versions after v4.0.192 simply break. The server runs without any logs coming, while the UI just has ERR:CONN_REFUSED all around the place

It also happens with a clean install of the newest release, am i missing something ?

I am using the tarballs from the releases on headless Ubuntu server

**Comment by tidusjar** [comment]
Do you have anything in the stdout?

**Comment by GeneralDoddi** [comment]
> Do you have anything in the stdout?

nothing from serverside, only /api/v1/Request/Movie/: 500 Internal Server Error","error":{"error":"Object reference not set to an instance of an object."}}

from request payload {theMovieDbId: "634649", languageCode: null}

it's like the system isn't carrying the selected language for the input, might it be a config issue?

**Comment by tidusjar** [comment]
Do you have the rest of the error for that internal server error?

**Comment by GeneralDoddi** [comment]
fail: Ombi.ErrorHandlingMiddleware[0]
      Something bad happened, ErrorMiddleware caught this
System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , MovieRequests )
   at System.Linq.AsyncEnumerable.WhereEnumerableAsyncIterator`1.MoveNextCore(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\Where.cs:line 110
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\AsyncIterator.cs:line 98
   at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\First.cs:line 144
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\Select.cs:line 106
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\AsyncIterator.cs:line 98
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)
   at Ombi.Core.Rule.Rules.Request.ExistingMovieRequestRule.Execute(BaseRequest obj) in /home/vsts/work/1/s/src/Ombi.Core/Rule/Rules/Request/ExistingMovieRequestRule.cs:line 43
   at Ombi.Core.Rule.RuleEvaluator.StartRequestRules(BaseRequest obj) in /home/vsts/work/1/s/src/Ombi.Core/Rule/RuleEvaluator.cs:line 42
   at Ombi.Core.Engine.Interfaces.BaseEngine.RunRequestRules(BaseRequest model) in /home/vsts/work/1/s/src/Ombi.Core/Engine/Interfaces/BaseEngine.cs:line 47
   at Ombi.Core.Engine.MovieRequestEngine.RequestMovie(MovieRequestViewModel model) in /home/vsts/work/1/s/src/Ombi.Core/Engine/MovieRequestEngine.cs:line 95
   at Ombi.Controllers.V1.RequestController.RequestMovie(MovieRequestViewModel movie) in /home/vsts/work/1/s/src/Ombi/Controllers/V1/RequestController.cs:line 96
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in /home/vsts/work/1/s/src/Ombi/Middleware/ApiKeyMiddlewear.cs:line 51
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in /home/vsts/work/1/s/src/Ombi/Middleware/ErrorHandlingMiddlewear.cs:line 24


this is what the stdout says

**Comment by GeneralDoddi** [comment]
and for the update thing,  i pretty much am not sure what is happening. the Stdout says nothing and the UI goes crazy

![errors](https://user-images.githubusercontent.com/3849042/85147460-6e82be00-b23e-11ea-9590-09410a74f149.JPG)

**Comment by GeneralDoddi** [comment]
Is there any other information needed ?

**Comment by GeneralDoddi** [comment]
I finally managed to install the latest version, imported the databases and it's up and running again. I'll close this case as i feel it's irrelevant due to the old version. Thank you for your time
