### ISSUE TITLE
v4 - 'load forever' TV searches

### ISSUE THREAD

**Issue by esticle** [tidusjar/Ombi#3607]
**Describe the bug**

It appears that some searches still 'load forever' even after the Putin fix.

**To Reproduce**
1. Go to the search bar
2. Type 'Close to home' or 'Top Wing' or 'Old Jack's Boat'
3. Choose the 2nd TV result

**Expected behavior**

- It should not load forever - but does not always happen 
- Possibly would be nice of TV search results included start year (like movies)
- Possibly would be nice to group by content type / filter of a kind - this specific search result is mostly flooded with music results and the the TV results is not strictly alphabetical in order, ie. "Closer to home" is between the 1st  and 2nd/3rd "Close to home" 

**Logs (Logs directory where Ombi is located)**

```
fail: Ombi.ErrorHandlingMiddleware[0]
      Something bad happened, ErrorMiddleware caught this
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Core.Engine.V2.TvSearchEngineV2.GetShowInformation(Int32 tvdbid) in /home/vsts/work/1/s/src/Ombi.Core/Engine/V2/TvSearchEngineV2.cs:line 84
   at Ombi.Controllers.V2.SearchController.GetTvInfoByMovieId(Int32 moviedbid) in /home/vsts/work/1/s/src/Ombi/Controllers/V2/SearchController.cs:line 120
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in /home/vsts/work/1/s/src/Ombi/Middleware/ApiKeyMiddlewear.cs:line 58
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in /home/vsts/work/1/s/src/Ombi/Middleware/ErrorHandlingMiddlewear.cs:line 30

```

**Desktop (please complete the following information):**
 - Linux_x64

**Ombi Version (please complete the following information):**
 - Dockered v4.0.362.0
- Plex

Thanks!

**Comment by PotatoQuality** [comment]
We seeing multiple issues on searching on a title and it will spin / search forever. Can you pull the last update? Some fixes are pushed to fix that, but not all is fixed yet.

**Comment by tidusjar** [comment]
See parent bug
