### ISSUE TITLE
V4 - Setting up Sonarr V3

### ISSUE THREAD

**Issue by Repooc** [tidusjar/Ombi#3624]
**Describe the bug**
When setting up sonarr, I can get every setting set except the Language option.  It appears that I can pull from sonarr the languages but when I go to select it and submit my changes, I get no feedback.  I also try to test connection after selecting English and connection fails but worked before trying to set the language.

Sonarr Info:
Version: 3.0.3.885
Package Version: 3.0.3.885-ls25 by linuxserver.io

**To Reproduce**
1. Go to 'TV/Sonarr'
2. Fill in everything except language.
3. Click submit
4. You can navigate away or not up to you but if you do and come back, you can click test connectivity and it will connect but then try to set language and connection fails and language doesnt set.

Below is the end of the log where I clicked Load Languages, set to English, then clicked submit.
`2020-06-17 19:04:43.745 -04:00 [Debug] Batch acquisition of 1 triggers
2020-06-17 19:04:43.745 -04:00 [Debug] Calling Execute on job DVR.ISonarrSync
2020-06-17 19:04:55.726 -04:00 [Error] Could not test Sonarr
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Controllers.V1.External.TesterController.Sonarr(SonarrSettings settings) in /home/vsts/work/1/s/src/Ombi/Controllers/V1/External/TesterController.cs:line 369
2020-06-17 19:05:00.001 -04:00 [Debug] Batch acquisition of 0 triggers
2020-06-17 19:05:00.001 -04:00 [Debug] Calling Execute on job Emby.IEmbyContentSync
2020-06-17 19:05:00.013 -04:00 [Debug] Trigger instruction : NoInstruction`

I then proceeded to click Load Languages for no reason to see what it would do and this is what started in the log.
[https://pastebin.com/5EUbZ2Ye](url)

**Expected behavior**
I expect to be able to set all my options up and click submit and then be able to click test connection and it work.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro v2004

**Ombi Version (please complete the following information):**
 - Version 4.0.377.0
 - linuxserver/ombi:v4-preview

**Comment by PotatoQuality** [comment]
I have the same problem. I can get the language settings from Sonarr. But if you click on "Load Languages" it will also triggers a save action (you will see a popup below "Successfully saved Sonarr settings")

After selecting the correct settings in the dropdown menu, the save button doesn't respond.

Maybe a quick fix is possible @tidusjar @twanariens  I love Sonarr V3, but i need Ombi to send the request to Sonarr <3

An error is also logged:

```
2020-07-26 02:11:56.320 +02:00 [Debug] Batch acquisition of 1 triggers
2020-07-26 02:11:56.320 +02:00 [Debug] Batch acquisition of 0 triggers
2020-07-26 02:11:56.320 +02:00 [Debug] Calling Execute on job DVR.ISonarrSync
2020-07-26 02:11:56.325 +02:00 [Debug] Trigger instruction : DeleteTrigger
2020-07-26 02:11:56.325 +02:00 [Debug] Deleting trigger
2020-07-26 02:12:02.332 +02:00 [Error] Something bad happened, ErrorMiddleware caught this
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Controllers.V1.External.SonarrController.GetLanguageProfiles(SonarrSettings settings) in /home/vsts/work/1/s/src/Ombi/Controllers/V1/External/SonarrController.cs:line 144
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in /home/vsts/work/1/s/src/Ombi/Middleware/ApiKeyMiddlewear.cs:line 58
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in /home/vsts/work/1/s/src/Ombi/Middleware/ErrorHandlingMiddlewear.cs:line 30
2020-07-26 02:12:13.298 +02:00 [Debug] Batch acquisition of 1 triggers
2020-07-26 02:12:13.299 +02:00 [Debug] Batch acquisition of 0 triggers
2020-07-26 02:12:13.299 +02:00 [Debug] Calling Execute on job DVR.ISonarrSync
2020-07-26 02:12:13.304 +02:00 [Debug] Trigger instruction : DeleteTrigger
2020-07-26 02:12:13.304 +02:00 [Debug] Deleting trigger
```

**Comment by PotatoQuality** [comment]
<3 <3
