### ISSUE TITLE
V4 - GlobalSettings {'Id'} value is already being tracked

### ISSUE THREAD

**Issue by PearsonFlyer** [tidusjar/Ombi#3640]
**Describe the bug**
On first run:
Unhandled exception. System.InvalidOperationException: The instance of entity type 'GlobalSettings' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.

**To Reproduce**

1. Shut down V3.
2. Unzipped V4 into a new directory.
3. Dropped to Admin command line.
4. Fired up V4.
5. Got error.

**Expected behavior**
Expected Ombi to start without issue and create empty fresh install.

**Logs (Logs directory where Ombi is located)**
c:\Ombi4>Ombi --host http://*:3580 --baseurl /ombi
Hello, welcome to Ombi
Valid options are:
Ombi 4.0.392
Copyright (C) 2020 Ombi

We are running on http://*:3580
c:\Ombi4
Unhandled exception. System.InvalidOperationException: The instance of entity type 'GlobalSettings' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap1.ThrowIdentityConflict(InternalEntityEntry entry) at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap1.Add(TKey key, InternalEntityEntry entry) at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap1.Add(InternalEntityEntry entry)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean modifyProperties, Nullable1 forceStateWhenUnknownKey) at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode1 node)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode1 node, Func2 handleNode)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState targetState, EntityState storeGeneratedWithKeySetTargetState, Boolean forceStateWhenUnknownKey)
at Microsoft.EntityFrameworkCore.DbContext.SetEntityState(InternalEntityEntry entry, EntityState entityState)
at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
at Microsoft.EntityFrameworkCore.DbContext.Update[TEntity](TEntity entity)
at Ombi.Store.Repository.SettingsJsonRepository.Update(GlobalSettings entity) in /home/vsts/work/1/s/src/Ombi.Store/Repository/SettingsJsonRepository.cs:line 104
at Ombi.Settings.Settings.SettingsService`1.SaveSettings(T model) in /home/vsts/work/1/s/src/Ombi.Settings/Settings/SettingsService.cs:line 91
at Ombi.Startup.Configure(IApplicationBuilder app, ILoggerFactory loggerFactory, IServiceProvider serviceProvider) in /home/vsts/work/1/s/src/Ombi/Startup.cs:line 171
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.b__0(IApplicationBuilder builder)
at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.b__2(IApplicationBuilder app)
at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.b__0(IApplicationBuilder app)
at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
at Ombi.Program.Main(String[] args) in /home/vsts/work/1/s/src/Ombi/Program.cs:line 131

My log directory is unhelpful, but here's the file anyway:

2020-06-23 10:12:44.318 -04:00 [Information] Default Quartz.NET properties loaded from embedded resource file
2020-06-23 10:12:44.408 -04:00 [Debug] TaskSchedulingThreadPool configured with max concurrency of 10 and TaskScheduler ThreadPoolTaskScheduler.
2020-06-23 10:12:44.430 -04:00 [Information] Initialized Scheduler Signaller of type: Quartz.Core.SchedulerSignalerImpl
2020-06-23 10:12:44.432 -04:00 [Information] Quartz Scheduler v."3.0.7.0" created.
2020-06-23 10:12:44.433 -04:00 [Information] RAMJobStore initialized.
2020-06-23 10:12:44.436 -04:00 [Information] Scheduler meta-data: Quartz Scheduler (v3.0.7.0) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
Scheduler class: 'Quartz.Core.QuartzScheduler' - running locally.
NOT STARTED.
Currently in standby mode.
Number of jobs executed: 0
Using thread pool 'Quartz.Simpl.DefaultThreadPool' - with 10 threads.
Using job-store 'Quartz.Simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2020-06-23 10:12:44.436 -04:00 [Information] Quartz scheduler 'DefaultQuartzScheduler' initialized
2020-06-23 10:12:44.436 -04:00 [Information] Quartz scheduler version: 3.0.7.0
2020-06-23 10:12:44.437 -04:00 [Information] JobFactory set to: Ombi.Schedule.IoCJobFactory
2020-06-23 10:12:44.508 -04:00 [Information] Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
2020-06-23 10:12:44.513 -04:00 [Debug] Batch acquisition of 0 triggers

**Desktop (please complete the following information):**
Windows 10

**Ombi Version (please complete the following information):**
Ombi version 4.0.493
Plex version 1.19.4.2935

**Additional context**
Previous version 3 installed in a different directory. Shut down during this run. I was trying to get a clean v4 install not using the existing DB's from version 3.

Subsequent runs of Ombi 4 do not display this error message, they simply hang at that spot in the run.

**Comment by SiliconMachine** [comment]
I am having the exact same error and couldn't find anything around. 
Any solution for this issue?

**Comment by PearsonFlyer** [comment]
I have not been able to resolve it. Stuck on the older version until this is resolved.

**Comment by PearsonFlyer** [comment]
Still getting this even in the newest version.

c:\Ombi4>ombi.exe --host http://*:3580 --baseurl /ombi4
Hello, welcome to Ombi
Valid options are:
Ombi 4.0.411
Copyright (C) 2020 Ombi

  --host       (Default: http://*:5000) Set to a semicolon-separated (;) list of
               URL prefixes to which the server should respond. For example,
               http://localhost:123. Use "localhost" to indicate that the server
               should listen for requests on any IP address or hostname using
               the specified port and protocol (for example,
               http://localhost:5000). The protocol (http:// or https://) must
               be included with each URL. Supported formats vary between
               servers.

  --storage    Storage path, where we save the logs and database

  --baseurl    The base URL for reverse proxy scenarios

  --demo       Demo mode, you will never need to use this, fuck that fruit
               company...

  --help       Display this help screen.

  --version    Display version information.



We are running on http://*:3580
c:\Ombi4
Unhandled exception. System.InvalidOperationException: The instance of entity type 'GlobalSettings' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode`1 node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState targetState, EntityState storeGeneratedWithKeySetTargetState, Boolean forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState(InternalEntityEntry entry, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.Update[TEntity](TEntity entity)
   at Ombi.Store.Repository.SettingsJsonRepository.Update(GlobalSettings entity) in /home/vsts/work/1/s/src/Ombi.Store/Repository/SettingsJsonRepository.cs:line 104
   at Ombi.Settings.Settings.SettingsService`1.SaveSettings(T model) in /home/vsts/work/1/s/src/Ombi.Settings/Settings/SettingsService.cs:line 91
   at Ombi.Startup.Configure(IApplicationBuilder app, ILoggerFactory loggerFactory, IServiceProvider serviceProvider) in /home/vsts/work/1/s/src/Ombi/Startup.cs:line 171
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Ombi.Program.Main(String[] args) in /home/vsts/work/1/s/src/Ombi/Program.cs:line 131

**Comment by albertsj1** [comment]
I have the latest version of v4-preview and hitting this exact same error message.  Same error message with a clean config directory as well.
I've confirmed this ONLY happens when using the `--baseurl` option.
Should I open another GH issue or can this one be re-opened?

Thanks
