### ISSUE TITLE
Cannot connect to Sonarr and Jellyfin behind reverse proxy

### ISSUE THREAD

**Issue by piiot** [tidusjar/Ombi#3668]
**Describe the bug**
Attempting to connect to both Sonarr and Jellyfin k8s deployments fail.  These services sit behind a Traefik ingress in k8s and are accessible and functioning fine.  The reverse proxy uses a private CA's certificate for all sites.   I have checked Ombi > "Ignore any certificate errors" and restarted the container.

**To Reproduce**
1. Go to Media Server > Emby/Jellyfin > Add Server (OR) TV > Sonarr 
2. Click on Test Connectivity/Discover Server info

**Expected behavior**
Ability to communicate to Sonarr and Jellyfin

**Logs (Logs directory where Ombi is located)**
```
fail: Ombi.Controllers.External.TesterController[1000]
      Could not test Emby
System.OperationCanceledException: The operation was canceled.
   at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request) in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
   at Ombi.Api.Emby.EmbyApi.GetUsers(String baseUri, String apiKey) in C:\projects\requestplex\src\Ombi.Api.Emby\EmbyApi.cs:line 33
   at Ombi.Controllers.External.TesterController.Emby(EmbyServers settings) in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 293
fail: Ombi.ErrorHandlingMiddleware[0]
      Something bad happened, ErrorMiddleware caught this
System.OperationCanceledException: The operation was canceled.
   at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request) in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
   at Ombi.Api.Emby.EmbyApi.GetPublicInformation(String baseUrl) in C:\projects\requestplex\src\Ombi.Api.Emby\EmbyApi.cs:line 55
   at Ombi.Controllers.External.EmbyController.GetServerInfo(EmbyServers server) in C:\projects\requestplex\src\Ombi\Controllers\External\EmbyController.cs:line 67
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ApiKeyMiddlewear.cs:line 51
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ErrorHandlingMiddlewear.cs:line 24

```

**Desktop (please complete the following information):**
 - OS: linuxserver/ombi:amd64-v4.0.407-ls4; also tried amd64-v3.0.4892-ls62

**Ombi Version (please complete the following information):**
 - Version: amd64-v3.0.4892-ls62
- Media Server: Jellyfin

**Additional context**
This configuration is fresh and has never worked.

**Comment by piiot** [comment]
It seems like Ombi doesn't like being behind a privateCA's certificate?  I have tested a connection successfully going from a Windows deployment hosted behind reverse proxy using a Lets Encrypt certificate  -> Sonarr + Jellyfin behind reverse proxy w/ PrivateCA certificate.  No issues. 


This successful test was on:

```
Version | 3.0.4119
OS Architecture | X64
OS Description | Microsoft Windows 6.3.9600
```

I moved the k8s deployment down to this same version, but no luck.  I deleted and recreated all config storage when doing this as well (i.e. .aspnet, Logs,  Ombi.db  OmbiExternal.db  OmbiSettings.db  Schedules.db)

```
Version | 3.0.4119
OS Architecture | X64
OS Description | Linux 4.15.0-109-generic #110-Ubuntu SMP Tue Jun 23 02:39:32 UTC 2020
```

**Comment by piiot** [comment]
Ok apparently the privateCA certificate is not the issue.  I recreated the same k8s deployment, but on an ingress that uses a Lets Encrypt certificate and still got failures.

```
2020-07-15 20:10:47.477 +00:00 [Error] Something bad happened, ErrorMiddleware caught this
System.Threading.Tasks.TaskCanceledException: The operation was canceled.
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request) in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
   at Ombi.Api.Sonarr.SonarrApi.GetRootFolders(String apiKey, String baseUrl) in C:\projects\requestplex\src\Ombi.Api.Sonarr\SonarrApi.cs:line 33
   at Ombi.Controllers.External.SonarrController.GetRootFolders(SonarrSettings settings) in C:\projects\requestplex\src\Ombi\Controllers\External\SonarrController.cs:line 53
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 50
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24
```

Two differences between the working and non-working setups:
1.  Windows deployment is working vs Linux even though they are on the same version.
2.  Windows deployment is not using Traefik as a reverse proxy - it is using NGINX.

I will try using MetalLB to get a specific IP assigned to Ombi rather than using an Ingress.  Maybe Traefik is causing issues somewhere..

**Comment by piiot** [comment]
Just tried connecting to the k8s ClusterIP rather than using the ingress, and I can get through.  It has to be some issue with the reverse proxy.  Everything is now working as expected, so I'm not sure I'll get around to testing out the potential MetalLB solution.

![image](https://user-images.githubusercontent.com/26583558/87593413-4735da00-c6a0-11ea-8d04-e46094429a3c.png)

**Comment by piiot** [comment]
MetalLB confirmed works - no issues.
