### ISSUE TITLE
Gmail SMTP

### ISSUE THREAD

**Issue by brandonheley** [tidusjar/Ombi#3716]
**Describe the bug**
Ive been through most of the other SMTP posts on the sub and im still getting the error “There was an error when sending the email message, please check your settings”

These are the settings im using

Enabled: checked
Enable smtp Authentication: checked
Dissable tls/ssl: unchecked
Disable certificate checking: unchecked
Smtp host: smtp.gmail.com
Smtp port: 587 also tried 465
Email sender: new email i made with 2fa off and less secure app access on
Sender name: my first name
Admin email: gmail different to email sender
Username: same as email sender no gmail.com
Password: my password for email sender
Ive also swapped my email sender and admin email around and the password.

**To Reproduce**
Go to Settings, Notifications, Email
Put in same settings
Click submit, email saves, click test, gives error message There was an error when sending the email message, please check your settings

**Expected behavior**
Should add the email

**Logs (Logs directory where Ombi is located)**
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 87
   at Ombi.Controllers.External.TesterController.Email(EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 277
Not sure if these are the right logs i just chose latest logs i had

**Desktop (please complete the following information):**
 - OS: Windows 10

**Ombi Version (please complete the following information):**
 - Version: 3.0.5202

- Media Server plex

**Additional context**
I added this to the reddit but also here as i thought it would be better to post here

**Comment by tidusjar** [comment]
With the logs I'm missing the full stack trace, can you please include the whole error

**Comment by tidusjar** [comment]
What was the issue?
