### ISSUE TITLE
V4 Error "Settings> System> Logs"

### ISSUE THREAD

**Issue by vsc55** [tidusjar/Ombi#3733]
**Describe the bug**
I run ombi on a docker. The docker executes ombi with the argument `--storage /config`.
Ombi boots successfully and creates the log files in `/config/Logs/log-***.log`.
But if we access "**Settings> System> Logs**" on the web, there are errors of access denied or that the path does not exist since this section tries to access "`/opt/Ombi/Logs`" instead of using the path "`/config/Logs`".

**To Reproduce**
1. Create Docker
2. Click on Settings
3. Click on System
4. Click on Logs
5. see error in log file

**Expected behavior**
Show files and read logs.

**Ombi Version (please complete the following information):**
 - Version 4.0.454.0

**Logs (Logs directory where Ombi is located)**
```
2020-08-11 18:21:37.104 +02:00 [Error] Something bad happened, ErrorMiddleware caught this
System.IO.DirectoryNotFoundException: Could not find a part of the path '/opt/ombi/Logs'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.EnumerateFiles(String path, String searchPattern, SearchOption searchOption)
   at Ombi.Controllers.V2.SystemController.GetLogFiles() in /home/vsts/work/1/s/src/Ombi/Controllers/V2/SystemController.cs:line 25
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in /home/vsts/work/1/s/src/Ombi/Middleware/ApiKeyMiddlewear.cs:line 58
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in /home/vsts/work/1/s/src/Ombi/Middleware/ErrorHandlingMiddlewear.cs:line 30
```

**Comment by vsc55** [comment]
My temporary solution has been to create the container on the following volume:
` -v </path/to/appdata/config/Logs>:/opt/ombi/Logs`

**Comment by adamskoog** [comment]
Mine gives the error: System.IO.DirectoryNotFoundException: Could not find a part of the path '/app/Logs'.

I'm using the hotio/ombi:unstable container. This could be something related to the container configuration as well and not directly and Ombi issue. What container are you using @vsc55?

**Comment by vsc55** [comment]
Use the docker: linuxserver/ombi:v4-preview

Issue: https://github.com/linuxserver/docker-ombi/pull/72

**Comment by tidusjar** [comment]
Plausible Analytics
