### ISSUE TITLE
Jellfin Login not working

### ISSUE THREAD

**Issue by geilername** [tidusjar/Ombi#3751]
**Describe the bug**
After upgrading v3 to v4 no jellyfin users can authenticate

**To Reproduce**
1. Try to login.

**Expected behavior**
working Login

**Screenshots**

**Logs (Logs directory where Ombi is located)**
`2020-09-08T09:14:32.308230096Z System.NotImplementedException: The method or operation is not implemented.
2020-09-08T09:14:32.308234342Z    at Ombi.Api.Emby.JellyfinApi.LoginConnectUser(String username, String password) in /home/vsts/work/1/s/src/Ombi.Api.Emby/JellyfinApi.cs:line 177
2020-09-08T09:14:32.30823968Z    at Ombi.Core.Authentication.OmbiUserManager.CheckEmbyPasswordAsync(OmbiUser user, String password) in /home/vsts/work/1/s/src/Ombi.Core/Authentication/OmbiUserManager.cs:line 154
2020-09-08T09:14:32.308251706Z    at Ombi.Core.Authentication.OmbiUserManager.CheckPasswordAsync(OmbiUser user, String password) in /home/vsts/work/1/s/src/Ombi.Core/Authentication/OmbiUserManager.cs:line 84
2020-09-08T09:14:32.308256779Z    at Ombi.Controllers.V1.TokenController.GetToken(UserAuthModel model) in /home/vsts/work/1/s/src/Ombi/Controllers/V1/TokenController.cs:line 68
2020-09-08T09:14:32.308260935Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
2020-09-08T09:14:32.308281644Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
2020-09-08T09:14:32.308286527Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2020-09-08T09:14:32.308291327Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
2020-09-08T09:14:32.308295792Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2020-09-08T09:14:32.30830065Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2020-09-08T09:14:32.308306462Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2020-09-08T09:14:32.308311345Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
2020-09-08T09:14:32.308315633Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2020-09-08T09:14:32.308320154Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2020-09-08T09:14:32.308324825Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2020-09-08T09:14:32.308329461Z    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
2020-09-08T09:14:32.308333996Z    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
2020-09-08T09:14:32.30833829Z    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
2020-09-08T09:14:32.308342685Z    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
2020-09-08T09:14:32.308346926Z    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
2020-09-08T09:14:32.308354044Z    at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in /home/vsts/work/1/s/src/Ombi/Middleware/ApiKeyMiddlewear.cs:line 51
2020-09-08T09:14:32.308358676Z    at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in /home/vsts/work/1/s/src/Ombi/Middleware/ErrorHandlingMiddlewear.cs:line 24`

**Desktop (please complete the following information):**
 - Arch Linux - Firefox (same problem on all clients)

**Ombi Version (please complete the following information):**
 - Version Ombi 4.0.471 (linuxserver.io v4-preview)
- Media Server Jellyfin
- Database Type: MySQL - MariaDB 1:10.5.5

**Additional context**
v3 did work just fine

**Comment by gnouts** [comment]
I can confirm this error.

Setup using docker. Jellyfin 10.6.4 using official image (x64). Ombi, using linuxserver v4-preview and sqlite.

**Comment by geilername** [comment]
> I can confirm this error.
> 
> Setup using docker. Jellyfin 10.6.4 using official image (x64). Ombi, using linuxserver v4-preview and sqlite.
> 
> V3 works fine. Only local users work on V4.

I think I found a hotfix. The Users get Type 4 after the upgrade which equals EmbyConnect, but we need 3 for it to work which is EmbyUser.
You need to change somethin in the AspNetUser Table:
`update AspNetUsers set UserType=3 where UserType=4;`
after that it should work.

**Comment by tidusjar** [comment]
Just looked into this, yes this is a mistake.

So basically currently in ombi there is no way to know if it's a Emby user vs Jellyfin user. So one of my internal migrations fixed an issue with Emby but then had this knock on effect.

The solution currently is what @geilername has suggested.

**Comment by gnouts** [comment]
The solution is to go into the database manually ? Or did you just implement something that do the change automagicaly ?
If the former, maybe keep this issue open to have a proper migration fix for noob users :)

**Comment by Extarys** [comment]
I'm confused, which database this need to be applied to? I just started a v4 container and I can't make this work too. Maybe add a small note in the documentation about this?

@geilername @tidusjar

**Comment by geilername** [comment]
@Extarys Sorry I'm no longer using Ombi so I can't take screenshots.

You need to open the database Ombi is using (so sqlite3 for standard installation i think?) and execute the query i posted eralier. So v4 can understand the data from v3.

**Comment by Extarys** [comment]
Hey @geilername Thanks for the reply, might be useful I appreciate you took the time :heart: 

For others, in the setup page of v4 I had a jellyfin error but after the setup was completed, the jellyfin settings were all there and seems to work, so fingers crossed :crossed_fingers:
