### ISSUE TITLE
Ombi won't start when config location from --storage argument points to a network share.

### ISSUE THREAD

**Issue by DFKnight** [tidusjar/Ombi#3764]
**Describe the bug**
I am trying to start Ombi on a system with the config/data stored on a network share. when I run the application using **/opt/Ombi/Ombi --config /path/to/share**, I get the following error. I'm not sure if this is a bug, or if there's a workaround for this issue, but any help would be appreciated. 

**Error Message**
Application startup exception: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.Data.Sqlite.SqliteConnectionExtensions.ExecuteNonQuery(SqliteConnection connection, String commandText)
   at Microsoft.Data.Sqlite.SqliteTransaction.Commit()
   at Microsoft.EntityFrameworkCore.Storage.RelationalTransaction.Commit()
   at Ombi.Store.Repository.SettingsJsonRepository.Update(GlobalSettings entity) in C:\projects\requestplex\src\Ombi.Store\Repository\SettingsJsonRepository.cs:line 105
   at Ombi.Settings.Settings.SettingsService`1.SaveSettings(T model) in C:\projects\requestplex\src\Ombi.Settings\Settings\SettingsService.cs:line 91
   at Ombi.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IMemoryCache cache, IServiceProvider serviceProvider) in C:\projects\requestplex\src\Ombi\Startup.cs:line 149
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

Unhandled Exception: Microsoft.Data.Sqlite.SqliteException: SQLite Error 5: 'database is locked'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.Data.Sqlite.SqliteConnectionExtensions.ExecuteNonQuery(SqliteConnection connection, String commandText)
   at Microsoft.Data.Sqlite.SqliteTransaction.Commit()
   at Microsoft.EntityFrameworkCore.Storage.RelationalTransaction.Commit()
   at Ombi.Store.Repository.SettingsJsonRepository.Update(GlobalSettings entity) in C:\projects\requestplex\src\Ombi.Store\Repository\SettingsJsonRepository.cs:line 105
   at Ombi.Settings.Settings.SettingsService`1.SaveSettings(T model) in C:\projects\requestplex\src\Ombi.Settings\Settings\SettingsService.cs:line 91
   at Ombi.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IMemoryCache cache, IServiceProvider serviceProvider) in C:\projects\requestplex\src\Ombi\Startup.cs:line 149
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at Ombi.Program.Main(String[] args) in C:\projects\requestplex\src\Ombi\Program.cs:line 128

**Desktop (please complete the following information):**
 - Ubuntu 20.04

**Ombi Version (please complete the following information):**
- Version: 3.0.5202-master
- Media Server: Plex
- Database Type: SQLite

**Comment by tidusjar** [comment]
It is not recommended to run a SQLite database on a network share. I suggest you use a different database e.g. MySql (see wiki on how to do this)
