### ISSUE TITLE
movie requests get sent to 'Failed Requests' queue, but data is sent to radarr fine.

### ISSUE THREAD

**Issue by monalisa-overdrive** [tidusjar/Ombi#3774]
**Describe the bug**
when a movie is requested, ombi thinks it failed and sends it to the 'Failed Requests' queue with the error `Unexpected chatacter encountered while parsing value: {. Path 'images', line 10, position 5.`. 
the movie is sent to radarr and radarr picks it up and searches, but the movie remains in the failed queue.

**To Reproduce**
1. request any movie
2. watch it report that it failed
3. check the failed queue
4. see error

**Expected behavior**
I expect the movies to be sent to radarr without error.

**Logs (Logs directory where Ombi is located)**
```
2020-09-26 19:06:47.457 -04:00 [Debug] Batch acquisition of 0 triggers
2020-09-26 19:07:15.113 -04:00 [Debug] Batch acquisition of 0 triggers
2020-09-26 19:07:35.170 -04:00 [Error] Error when sending movie to DVR app, added to the request queue
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path 'images', line 12, position 5.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty con$
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty membe$
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerCo$
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonPro$
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty mem$
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Radarr.RadarrApi.AddMovie(Int32 tmdbId, String title, Int32 year, Int32 qualityId, String rootPath, String apiKey, String baseUrl, Boolean$
   at Ombi.Core.Senders.MovieSender.SendToRadarr(MovieRequests model, RadarrSettings settings) in C:\projects\requestplex\src\Ombi.Core\Senders\MovieSend$
   at Ombi.Core.Senders.MovieSender.Send(MovieRequests model) in C:\projects\requestplex\src\Ombi.Core\Senders\MovieSender.cs:line 57
2020-09-26 19:07:35.180 -04:00 [Debug] Batch acquisition of 1 triggers
2020-09-26 19:07:35.181 -04:00 [Debug] Batch acquisition of 0 triggers
2020-09-26 19:07:35.181 -04:00 [Debug] Calling Execute on job Notifications.INotificationService
2020-09-26 19:07:36.388 -04:00 [Information] there are no admins to send a notification for Test, for agent Mobile
2020-09-26 19:07:36.390 -04:00 [Debug] Trigger instruction : DeleteTrigger
2020-09-26 19:07:36.391 -04:00 [Debug] Deleting trigger
2020-09-26 19:08:01.657 -04:00 [Debug] Batch acquisition of 0 triggers

```

**Desktop (please complete the following information):**
 - OS: docker

**Ombi Version (please complete the following information):**
 - Version 3.0.5202
- Media Server plex
- Database Type: SQLite

**Comment by monalisa-overdrive** [comment]
radarr version 3.0.0.3775

**Comment by eltiel** [comment]
I'm experiencing this issue as well, but only after I upgraded to Radarr v3. It used to work fine on Radarr v2, so something must have changed along the way.

**Comment by PotatoQuality** [comment]
by my knowledge, Radarr v3 isn't supported yet by Ombi.

**Comment by g4m3r7ag** [comment]
Radarr V0.2 is end of life. From the Radarr Wiki

develop (Default/Stable): It has been tested by users on nightly branch and it's not known to have any major issues. This is currently v0.2. This version is end of life and no longer receiving updates

https://github.com/Radarr/Radarr/wiki/Release-Branches

Ombi should probably be updated for Radarr V3 at this point. Not sure how much trouble it would be to adapt the Sonarr V3 code and checkbox over to the Radarr settings.

**Comment by Qstick** [comment]
It’s true, we are beta. And soon will be pushing v3 to the entire user base... we may want to get Ombi support fixed up soon

**Comment by PotatoQuality** [comment]
> It’s true, we are beta. And soon will be pushing v3 to the entire user base... we may want to get Ombi support fixed up soon

Oof. Maybe @tidusjar can look into this?

**Comment by tidusjar** [comment]
Sorry, been super busy, Radarr V3 is supported, i'll get this fixed

**Comment by tidusjar** [comment]
Just had a look into this, it's already been fixed in V4 version of Ombi, I've not yet ported the change into v3

**Comment by shortbloke** [comment]
@tidusjar  I've updated to the latest Ombi (v3) and Radarr 3.0.0.3790. When I request a movie, it seems to work, but I get a notification on my mobile: "Hello! The user '<removed user name>' has requested <removed movie name> but it could not be added. This has been added into the requests queue and will keep retrying.

I can see in Radarr the  request has been made and in Ombi going to Settings -> System -> Failed requests. The list is empty.

Checking the logs shows the following errors:
```
2020-10-11 10:58:25.161 +01:00 [Error] Error when sending movie to DVR app, added to the request queue
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path 'images', line 10, position 5.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProper
ty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract container
Contract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Radarr.RadarrApi.AddMovie(Int32 tmdbId, String title, Int32 year, Int32 qualityId, String rootPath, String apiKey, String baseUrl, Boolean searchNow, String minimumAvailabili
ty) in C:\projects\requestplex\src\Ombi.Api.Radarr\RadarrApi.cs:line 111
   at Ombi.Core.Senders.MovieSender.SendToRadarr(MovieRequests model, RadarrSettings settings) in C:\projects\requestplex\src\Ombi.Core\Senders\MovieSender.cs:line 160
   at Ombi.Core.Senders.MovieSender.Send(MovieRequests model) in C:\projects\requestplex\src\Ombi.Core\Senders\MovieSender.cs:line 57
2020-10-11 10:58:25.228 +01:00 [Debug] Batch acquisition of 1 triggers
2020-10-11 10:58:25.229 +01:00 [Debug] Batch acquisition of 0 triggers
2020-10-11 10:58:25.230 +01:00 [Debug] Calling Execute on job Notifications.INotificationService
2020-10-11 10:58:25.609 +01:00 [Error] Something bad happened, ErrorMiddleware caught this
System.Net.Http.HttpRequestException: Resource temporarily unavailable ---> System.Net.Sockets.SocketException: Resource temporarily unavailable
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request) in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
   at Ombi.Api.TheMovieDb.TheMovieDbApi.GetMovieInformationWithExtraInfo(Int32 movieId, String langCode) in C:\projects\requestplex\src\Ombi.TheMovieDbApi\TheMovieDbApi.cs:line 113
   at Ombi.Core.Engine.MovieSearchEngine.LookupImdbInformation(Int32 theMovieDbId, String langCode) in C:\projects\requestplex\src\Ombi.Core\Engine\MovieSearchEngine.cs:line 48
   at Ombi.Controllers.SearchController.GetExtraMovieInfo(SearchMovieExtraInfoRefineModel model) in C:\projects\requestplex\src\Ombi\Controllers\SearchController.cs:line 147
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] a
rguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ApiKeyMiddlewear.cs:line 51
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ErrorHandlingMiddlewear.cs:line 24
```

**Comment by tidusjar** [comment]
Fixed in ombi v4
