### ISSUE TITLE
V4 - Email Notifications for Issues aren’t working

### ISSUE THREAD

**Issue by dpiper01** [tidusjar/Ombi#3779]
**Describe the bug**

Ombi V4 is not sending out emails regarding issues (Issue Created or Issue Resolved)

However, it does send out request emails and test emails

**To Reproduce**

User creates an issue
Admin does not receive email

Admin marks issue as resolved
User does not receive email

**Expected Behaviour**

Email should be sent to admin that an issue was created and an email should be sent to the user when the issue is resolved

**Screenshots**

N/A

**Logs**

`2020-10-01 18:21:11.748 -04:00 [Error] Failed to notify for notification: EmailNotification { NotificationName: "EmailNotification" }
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Notifications.NotificationMessageCurlys.Setup(NotificationOptions opts, ChildRequests req, CustomizationSettings s, UserNotificationPreferences pref) in /home/vsts/work/1/s/src/Ombi.Notifications/NotificationMessageCurlys.cs:line 124
   at Ombi.Notifications.BaseNotification`` 1.Parse(NotificationOptions model, NotificationTemplates template, NotificationAgent agent) in /home/vsts/work/1/s/src/Ombi.Notifications/BaseNotification.cs:line 218
   at Ombi.Notifications.BaseNotification`` 1.LoadTemplate(NotificationAgent agent, NotificationType type, NotificationOptions model) in /home/vsts/work/1/s/src/Ombi.Notifications/BaseNotification.cs:line 187
   at Ombi.Notifications.Agents.EmailNotification.LoadTemplate(NotificationType type, NotificationOptions model, EmailNotificationSettings settings) in /home/vsts/work/1/s/src/Ombi.Notifications/Agents/EmailNotification.cs:line 59
   at Ombi.Notifications.Agents.EmailNotification.NewIssue(NotificationOptions model, EmailNotificationSettings settings) in /home/vsts/work/1/s/src/Ombi.Notifications/Agents/EmailNotification.cs:line 122
   at Ombi.Notifications.BaseNotification`` 1.NotifyAsync(NotificationOptions model, Settings settings) in /home/vsts/work/1/s/src/Ombi.Notifications/BaseNotification.cs:line 90
   at Ombi.Notifications.BaseNotification`` 1.NotifyAsync(NotificationOptions model) in /home/vsts/work/1/s/src/Ombi.Notifications/BaseNotification.cs:line 58
   at Ombi.Notifications.NotificationService.NotifyAsync(INotification notification, NotificationOptions model) in /home/vsts/work/1/s/src/Ombi.Notifications/NotificationService.cs:line 49
`

**Desktop**

- OS: Docker

**Ombi Version**

- Version 4.0.483.0
- Media Server: Plex
- Database Type: MySQL 

**Additional Context**

This problem only happens with Issues and not Requests. This problem only started occurring a few updates ago.

**Comment by tidusjar** [comment]
![image](https://user-images.githubusercontent.com/6642220/94969583-ec6f8a00-04fa-11eb-9f38-8030c49b8b22.png)

Cannot reproduce, are you able to provide any further information?

**Comment by tidusjar** [comment]
Nevermind, found it
