### ISSUE TITLE
Discover Screen Not Functioning

### ISSUE THREAD

**Issue by relctisgerg** [tidusjar/Ombi#3811]
**Describe the bug**
Discover screen remains on the spining load screen and does not display anything.  I can do a search and suggestions pop up, but when I select one, the load screen just keeps spinning and never displays anything.  

It has been a while since I upgraded and I went for build win10-x64(v4.0.519), but found that I could not change the Theme.  Then I tried build windows(Ombi v3.0.5202) and noticed this issue.  I did not have this issue with the old interface.  

I do not have/use Radarr/Sonarr or anything else like that and never have.  I just use Ombi as a centralized place for users to request new content.  Then I manually search for it.  

I have tried every combination of Movie, Combined, TV, Popular, Trending, and Upcoming all with the same results.  It will not show what I have, or things that can be requested.  I can see previous things that have been requested, but when I click on details I just get the spinning load screen again.

I have also tried it as if I was one of my users.

I am running Emby and Plex.  Currently Plex is down, but if I bring it up I can connect to it.  Emby also reports I am connected to it.

**To Reproduce**
1. Go to Discover

**Expected behavior**
I should see Movies, TV Shows, or Both on the Discover screen

**Screenshots**
![image](https://user-images.githubusercontent.com/48181819/95855837-0b55f380-0d27-11eb-853f-4e0421625068.png)

![image](https://user-images.githubusercontent.com/48181819/95856450-0b0a2800-0d28-11eb-87f9-12675e8ac9c3.png)

![image](https://user-images.githubusercontent.com/48181819/95862919-8de3b080-0d31-11eb-8073-282293fd6a71.png)

**Logs (Logs directory where Ombi is located)**
2020-10-13 07:48:23.750 -04:00 [Error] Something bad happened, ErrorMiddleware caught this
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: p.RequestId'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Ombi.Store.Repository.PlexServerContentRepository.Get(String providerId) in /home/vsts/work/1/s/src/Ombi.Store/Repository/PlexContentRepository.cs:line 66
   at Ombi.Core.Rule.Rules.Search.PlexAvailabilityRule.Execute(SearchViewModel obj) in /home/vsts/work/1/s/src/Ombi.Core/Rule/Rules/Search/PlexAvailabilityRule.cs:line 31
   at Ombi.Core.Rule.RuleEvaluator.StartSearchRules(SearchViewModel obj) in /home/vsts/work/1/s/src/Ombi.Core/Rule/RuleEvaluator.cs:line 54
   at Ombi.Core.Engine.Interfaces.BaseEngine.RunSearchRules(SearchViewModel model) in /home/vsts/work/1/s/src/Ombi.Core/Engine/Interfaces/BaseEngine.cs:line 54
   at Ombi.Core.Engine.V2.MovieSearchEngineV2.ProcessSingleMovie(SearchMovieViewModel viewMovie) in /home/vsts/work/1/s/src/Ombi.Core/Engine/V2/MovieSearchEngineV2.cs:line 337
   at Ombi.Core.Engine.V2.MovieSearchEngineV2.ProcessSingleMovie(MovieSearchResult movie) in /home/vsts/work/1/s/src/Ombi.Core/Engine/V2/MovieSearchEngineV2.cs:line 272
   at Ombi.Core.Engine.V2.MovieSearchEngineV2.TransformMovieResultsToResponse(IEnumerable`1 movies) in /home/vsts/work/1/s/src/Ombi.Core/Engine/V2/MovieSearchEngineV2.cs:line 259
   at Ombi.Core.Engine.V2.MovieSearchEngineV2.PopularMovies(Int32 currentlyLoaded, Int32 toLoad, CancellationToken cancellationToken) in /home/vsts/work/1/s/src/Ombi.Core/Engine/V2/MovieSearchEngineV2.cs:line 137
   at Ombi.Controllers.V2.SearchController.Popular(Int32 currentPosition, Int32 amountToLoad) in /home/vsts/work/1/s/src/Ombi/Controllers/V2/SearchController.cs:line 163
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in /home/vsts/work/1/s/src/Ombi/Middleware/ApiKeyMiddlewear.cs:line 58
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in /home/vsts/work/1/s/src/Ombi/Middleware/ErrorHandlingMiddlewear.cs:line 30
2020-10-13 07:48:25.411 -04:00 [Error] Something bad happened, ErrorMiddleware caught this
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: p.RequestId'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Ombi.Store.Repository.PlexServerContentRepository.Get(String providerId) in /home/vsts/work/1/s/src/Ombi.Store/Repository/PlexContentRepository.cs:line 66
   at Ombi.Core.Rule.Rules.Search.PlexAvailabilityRule.Execute(SearchViewModel obj) in /home/vsts/work/1/s/src/Ombi.Core/Rule/Rules/Search/PlexAvailabilityRule.cs:line 31
   at Ombi.Core.Rule.RuleEvaluator.StartSearchRules(SearchViewModel obj) in /home/vsts/work/1/s/src/Ombi.Core/Rule/RuleEvaluator.cs:line 54
   at Ombi.Core.Engine.Interfaces.BaseEngine.RunSearchRules(SearchViewModel model) in /home/vsts/work/1/s/src/Ombi.Core/Engine/Interfaces/BaseEngine.cs:line 54
   at Ombi.Core.Engine.V2.MovieSearchEngineV2.ProcessSingleMovie(SearchMovieViewModel viewMovie) in /home/vsts/work/1/s/src/Ombi.Core/Engine/V2/MovieSearchEngineV2.cs:line 337
   at Ombi.Core.Engine.V2.MovieSearchEngineV2.ProcessSingleMovie(MovieSearchResult movie) in /home/vsts/work/1/s/src/Ombi.Core/Engine/V2/MovieSearchEngineV2.cs:line 272
   at Ombi.Core.Engine.V2.MovieSearchEngineV2.TransformMovieResultsToResponse(IEnumerable`1 movies) in /home/vsts/work/1/s/src/Ombi.Core/Engine/V2/MovieSearchEngineV2.cs:line 259
   at Ombi.Core.Engine.V2.MovieSearchEngineV2.PopularMovies(Int32 currentlyLoaded, Int32 toLoad, CancellationToken cancellationToken) in /home/vsts/work/1/s/src/Ombi.Core/Engine/V2/MovieSearchEngineV2.cs:line 137
   at Ombi.Controllers.V2.SearchController.Popular(Int32 currentPosition, Int32 amountToLoad) in /home/vsts/work/1/s/src/Ombi/Controllers/V2/SearchController.cs:line 163
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in /home/vsts/work/1/s/src/Ombi/Middleware/ApiKeyMiddlewear.cs:line 58
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in /home/vsts/work/1/s/src/Ombi/Middleware/ErrorHandlingMiddlewear.cs:line 30
2020-10-13 07:48:47.001 -04:00 [Debug] Batch acquisition of 0 triggers
2020-10-13 07:48:56.698 -04:00 [Error] Something bad happened, ErrorMiddleware caught this
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: p.RequestId'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Ombi.Store.Repository.PlexServerContentRepository.Get(String providerId) in /home/vsts/work/1/s/src/Ombi.Store/Repository/PlexContentRepository.cs:line 66
   at Ombi.Core.Rule.Rules.Search.PlexAvailabilityRule.Execute(SearchViewModel obj) in /home/vsts/work/1/s/src/Ombi.Core/Rule/Rules/Search/PlexAvailabilityRule.cs:line 31
   at Ombi.Core.Rule.RuleEvaluator.StartSearchRules(SearchViewModel obj) in /home/vsts/work/1/s/src/Ombi.Core/Rule/RuleEvaluator.cs:line 54
   at Ombi.Core.Engine.Interfaces.BaseEngine.RunSearchRules(SearchViewModel model) in /home/vsts/work/1/s/src/Ombi.Core/Engine/Interfaces/BaseEngine.cs:line 54
   at Ombi.Core.Engine.V2.MovieSearchEngineV2.ProcessSingleMovie(FullMovieInfo movie) in /home/vsts/work/1/s/src/Ombi.Core/Engine/V2/MovieSearchEngineV2.cs:line 281
   at Ombi.Core.Engine.V2.MovieSearchEngineV2.GetFullMovieInformation(Int32 theMovieDbId, CancellationToken cancellationToken, String langCode) in /home/vsts/work/1/s/src/Ombi.Core/Engine/V2/MovieSearchEngineV2.cs:line 51
   at Ombi.Controllers.V2.SearchController.GetMovieInfo(Int32 movieDbId) in /home/vsts/work/1/s/src/Ombi/Controllers/V2/SearchController.cs:line 62
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in /home/vsts/work/1/s/src/Ombi/Middleware/ApiKeyMiddlewear.cs:line 58
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in /home/vsts/work/1/s/src/Ombi/Middleware/ErrorHandlingMiddlewear.cs:line 30
2020-10-13 07:49:11.564 -04:00 [Debug] Batch acquisition of 0 triggers

**Desktop (please complete the following information):**
 - OS: Windows 10 x64

**Ombi Version (please complete the following information):**
 - Current Ombi Version:  win10-x64(v4.0.530)
Other Versions I have tried:
 - windows(Ombi v3.0.4256)
 - windows(Ombi v3.0.4892)
 - windows(Ombi v3.0.5202)
 - win10-x64(v4.0.514)
 - win10-x64(v4.0.517)
 - win10-x64(v4.0.519)

- Media Server
Plex Version 1.20.0.3133 
Emby Verson 4.5.2.0

- Database Type: SQLite

**Additional context**
None

**Comment by tidusjar** [comment]
Looks like you have skipped a migration when going from V3 to V4. So what you need to do is delete the OmbiExternal.db and restart ombi. Let me know how that goes

**Comment by relctisgerg** [comment]
That did it.  Thank you much!
