### ISSUE TITLE
Requests not sent to Sonarr

### ISSUE THREAD

**Issue by ReenigneArcher** [tidusjar/Ombi#3813]
**Describe the bug**
Requests not sent to Sonarr

**To Reproduce**
1. Request a TV show (I requested from Requestrr)
2. Request gets added in Ombi under "Requests"
3. Received a discord notification saying "Hello! The user 'Api' has requested _some tv show_ but it could not be added. This has been added into the requests queue and will keep retrying"

**Expected behavior**
Request should be sent to Sonarr

**Screenshots**
n/a

**Logs (Logs directory where Ombi is located)**
Possibly another issue, but the last modified date of the log is from 7/2/2020. Nothing here to to help with the issue.
**Edit:** I found the logs, I must have changed the location where Ombi saves everything. This should be the relevant part.
```
2020-10-11 03:46:20.691 -04:00 [Error] Exception thrown when attempting to send series over to Sonarr
System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request) in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
   at Ombi.Api.Sonarr.SonarrApi.GetEpisodes(Int32 seriesId, String apiKey, String baseUrl) in C:\projects\requestplex\src\Ombi.Api.Sonarr\SonarrApi.cs:line 126
   at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSeries result, SonarrSettings s) in C:\projects\requestplex\src\Ombi.Core\Senders\TvSender.cs:line 296
   at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSettings s) in C:\projects\requestplex\src\Ombi.Core\Senders\TvSender.cs:line 257
2020-10-11 03:46:20.710 -04:00 [Error] Exception thrown when sending a movie to DVR app, added to the request queue
System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request) in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
   at Ombi.Api.Sonarr.SonarrApi.GetEpisodes(Int32 seriesId, String apiKey, String baseUrl) in C:\projects\requestplex\src\Ombi.Api.Sonarr\SonarrApi.cs:line 126
   at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSeries result, SonarrSettings s) in C:\projects\requestplex\src\Ombi.Core\Senders\TvSender.cs:line 296
   at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSettings s) in C:\projects\requestplex\src\Ombi.Core\Senders\TvSender.cs:line 257
   at Ombi.Core.Senders.TvSender.Send(ChildRequests model) in C:\projects\requestplex\src\Ombi.Core\Senders\TvSender.cs:line 61
2020-10-11 03:46:20.722 -04:00 [Error] Exception thrown when attempting to send series over to Sonarr
System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request) in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
   at Ombi.Api.Sonarr.SonarrApi.GetEpisodes(Int32 seriesId, String apiKey, String baseUrl) in C:\projects\requestplex\src\Ombi.Api.Sonarr\SonarrApi.cs:line 126
   at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSeries result, SonarrSettings s) in C:\projects\requestplex\src\Ombi.Core\Senders\TvSender.cs:line 296
   at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSettings s) in C:\projects\requestplex\src\Ombi.Core\Senders\TvSender.cs:line 257
2020-10-11 03:46:20.725 -04:00 [Error] Exception thrown when sending a movie to DVR app, added to the request queue
System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request) in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
   at Ombi.Api.Sonarr.SonarrApi.GetEpisodes(Int32 seriesId, String apiKey, String baseUrl) in C:\projects\requestplex\src\Ombi.Api.Sonarr\SonarrApi.cs:line 126
   at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSeries result, SonarrSettings s) in C:\projects\requestplex\src\Ombi.Core\Senders\TvSender.cs:line 296
   at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSettings s) in C:\projects\requestplex\src\Ombi.Core\Senders\TvSender.cs:line 257
   at Ombi.Core.Senders.TvSender.Send(ChildRequests model) in C:\projects\requestplex\src\Ombi.Core\Senders\TvSender.cs:line 61
```

**Desktop (please complete the following information):**
 - OS: Win 10 Pro

**Ombi Version (please complete the following information):**
 - Version 3.0.4892
- Media Server Plex
- Database Type: SQLite (default, never changed anything relating to this)

**Additional context**
I've tried updating Ombi through the web ui, but it doesn't ever update. Possibly related? Also added a Movie to radarr just a few days before the tv show failures and it went through just fine. Sonarr version is 3.0.4.982... I received this message in discord for 2 different shows, which are the only recent requests.
**Edit:** I saw in the FAQ that update doesn't work.
The machine running Ombi and Sonarr are both the same. Ombi says it can connect to Sonarr in the Sonarr configuration page.

**Comment by ReenigneArcher** [comment]
Just to clarify, Sonarr is connected.
![image](https://user-images.githubusercontent.com/42013603/96053455-887b8880-0e4d-11eb-9b72-6f66d7f72377.png)

I've also updated Ombi to v 3.0.5202.

**Comment by ReenigneArcher** [comment]
I manually updated Ombi. I'm still not sure what the request wasn't sent.

Even though the message said it would keep trying it appears it never tried again.

I deleted the requests from Ombi, and re-requested them. They then went through immediately.
