### ISSUE TITLE
v4 - infinite loading for some shows, exception in logs

### ISSUE THREAD

**Issue by mmozeiko** [tidusjar/Ombi#3861]
**Describe the bug**
Some shows cannot be loaded, shows infinite spinning loading icon.

**To Reproduce**
1. Enter 'The Queen's Gambit' into search
2. Click on found item in results

Now you'll see infinite loading icon, and information about tv show will not load.

**Expected behavior**
TV show loads all the information.

**Screenshots**
Here's how you search:
![image](https://user-images.githubusercontent.com/1665010/98493544-8d82ec00-21ef-11eb-8461-92e21603c7c8.png)

Here's what you get:
![image](https://user-images.githubusercontent.com/1665010/98493578-a2f81600-21ef-11eb-97a2-d2c52c4b6af2.png)

**Logs (Logs directory where Ombi is located)**
I see following information in logs:
```
2020-11-09 04:23:55.448 +02:00 [Error] Something bad happened, ErrorMiddleware caught this
TraktSharp.Exceptions.TraktNotFoundException: Not Found - method exists, but no record found
   at TraktSharp.Request.TraktRequest`2.SendAsync()
   at TraktSharp.Modules.TraktModuleBase.SendAsync[T](ITraktRequest`1 request)
   at TraktSharp.Modules.TraktShowsModule.GetShowAsync(String showId, TraktExtendedOption extended)
   at Ombi.Api.Trakt.TraktApi.GetTvExtendedInfo(String imdbId) in /home/vsts/work/1/s/src/Ombi.Api.Trakt/TraktApi.cs:line 51
   at Ombi.Core.Engine.V2.TvSearchEngineV2.GetExtraInfo(Task`1 showInfoTask, SearchFullInfoTvShowViewModel model) in /home/vsts/work/1/s/src/Ombi.Core/Engine/V2/TvSearchEngineV2.cs:line 174
   at Ombi.Core.Engine.V2.TvSearchEngineV2.ProcessResult(SearchFullInfoTvShowViewModel item, Task`1 showInfoTask) in /home/vsts/work/1/s/src/Ombi.Core/Engine/V2/TvSearchEngineV2.cs:line 156
   at Ombi.Core.Engine.V2.TvSearchEngineV2.GetShowInformation(Int32 tvdbid) in /home/vsts/work/1/s/src/Ombi.Core/Engine/V2/TvSearchEngineV2.cs:line 106
   at Ombi.Controllers.V2.SearchController.GetTvInfoByMovieId(Int32 moviedbid) in /home/vsts/work/1/s/src/Ombi/Controllers/V2/SearchController.cs:line 121
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in /home/vsts/work/1/s/src/Ombi/Middleware/ApiKeyMiddlewear.cs:line 58
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in /home/vsts/work/1/s/src/Ombi/Middleware/ErrorHandlingMiddlewear.cs:line 30
```

**Desktop (please complete the following information):**
- OS: ArchLinux

**Ombi Version (please complete the following information):**
- Version: 4.0.681

**Comment by tidusjar** [comment]
Working for me? Can you try now?

**Comment by mmozeiko** [comment]
Yes, it works now for me too. I guess it was issue with Trakt API?
It would be nice though if Ombi showed some error message about internal error or whatever. Instead of spinning never ending progress bar - which makes me wonder if my server is slow, if internet is hanging, etc...

**Comment by gandalf764** [comment]
same bug.... i search tv series: petra (2018) and same bug... loading forever..
![1](https://user-images.githubusercontent.com/41706025/99585923-46fb7180-29e7-11eb-9b81-c2dbb9e21fe0.png)
![2](https://user-images.githubusercontent.com/41706025/99585925-482c9e80-29e7-11eb-80b3-152ba0a5d70c.png)

**Comment by escservices** [comment]
Same issue here as well, had user search for "seduced inside the nxivm cult", the show exists on trakt but it just keeps spinning.  Same error in the logs as well.  
I'm on 4.0.721.0, Windows Server 2019, MySQL.

**Comment by mmozeiko** [comment]
Got the same infinite spinning again when clicking on TV show "Dead Mountain: The Dyatlov Pass Incident" in search results.

**Comment by tidusjar** [comment]
This should be resolved with the latest version
