### ISSUE TITLE
V4 - Exception when browsing to the swagger help (http://localhost:5000/swagger/index.html)

### ISSUE THREAD

**Issue by PolliSoft** [tidusjar/Ombi#3874]
**Describe the bug**
When trying to read up on the Swagger API, Ombi gets an exception.

**To Reproduce**
1. Go to 'http://localhost:5000/swagger/index.html'

**Expected behavior**
API help is shown

**Screenshots**
![image](https://user-images.githubusercontent.com/563252/99441984-f74e7480-2918-11eb-82a5-962cec36d4dc.png)

**Logs (Logs directory where Ombi is located)**
```
2020-11-17 20:56:21.688 +01:00 [Error] Something bad happened, ErrorMiddleware caught this

System.NotSupportedException: Conflicting method/path combination "POST api/v1/Radarr/tags" for actions - Ombi.Controllers.V1.External.RadarrController.GetTags (Ombi),Ombi.Controllers.V1.External.RadarrController.GetTags (Ombi). Actions require a unique method/path combination for Swagger/OpenAPI 3.0. Use ConflictingActionsResolver as a workaround

   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)

   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)

   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath)

   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)

   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)

   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)

   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in /home/vsts/work/1/s/src/Ombi/Middleware/ApiKeyMiddlewear.cs:line 56

   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in /home/vsts/work/1/s/src/Ombi/Middleware/ErrorHandlingMiddlewear.cs:line 24
```

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (19042.630)

**Ombi Version (please complete the following information):**
 - Version 4.0.483.0
- Media Server - Plex
- Connected to Plex, Sonarr and Radarr
- Database Type: SQLite 

**Additional context**

**Comment by PolliSoft** [comment]
Working on 4.0.728.0. Can be closed.
