### ISSUE TITLE
After migration to MySQL Ombi will not start - Table 'applicationconfiguration' already exists

### ISSUE THREAD

**Issue by KierenConnell** [tidusjar/Ombi#3879]
**Describe the bug**
I followed the steps outlined here with not problems:
https://github.com/tidusjar/Ombi/wiki/Using-a-different-database
https://github.com/tidusjar/Ombi/wiki/Migration-procedure-from-SQLite-to-MySQL-or-MariaDB

**To Reproduce**
Followed these steps with no errors:
https://github.com/tidusjar/Ombi/wiki/Using-a-different-database
https://github.com/tidusjar/Ombi/wiki/Migration-procedure-from-SQLite-to-MySQL-or-MariaDB

**Expected behavior**
Everything to start fine

**Logs (Logs directory where Ombi is located)**
Running the migration process gives me this output
````
C:\Users\Administrator\AppData\Local\Programs\Python\Python38>python C:\Plex\Ombi\ombi_sqlite2mysql_multi.py -c  C:\Plex\Ombi
Migration tool from SQLite to Multi MySql/MariaDB for ombi (1.0.0) By VSC55

- Processing DataBase (OmbiDatabase)...
  -------------------

- Saving in (C:\Plex\Ombi\migration.json)... [✓]
Generate file "database.json":
- Saving in (C:\Plex\Ombi\database.json)... [✓]

MySQL > Connecting... [✓]
- Reading   [############################################################] 1/1
Read tables [✓]

Check migration.json:
- OmbiDatabase [SQLite >> Migrate]
- SettingsDatabase [No Config >> Skip]
- ExternalDatabase [No Config >> Skip]

Dump SQLite:
- OmbiDatabase      [############################################################] 748/748

Start clean tables:
- [CLEAN ] -> aspnetusers -> rows: 1
- [CLEAN ] -> notificationtemplates -> rows: 100
- [CLEAN ] -> __efmigrationshistory -> rows: 6

- Running   [############################################################] 3/3
Clean tables [✓]

Start Migration:
- Preparing [############################################################] 754/754
- Running   [############################################################] 697/697
- [!!] -> __efmigrationshistory -> [SQLite (0) / MySQL (5)] = -5
- [!!] -> aspnetroles -> [SQLite (0) / MySQL (12)] = -12
- [!!] -> aspnetuserroles -> [SQLite (0) / MySQL (38)] = -38
- [!!] -> aspnetusers -> [SQLite (0) / MySQL (15)] = -15
- [!!] -> childrequests -> [SQLite (0) / MySQL (13)] = -13
- [!!] -> episoderequests -> [SQLite (0) / MySQL (308)] = -308
- [!!] -> issuecategory -> [SQLite (0) / MySQL (4)] = -4
- [!!] -> mobiledevices -> [SQLite (0) / MySQL (1)] = -1
- [!!] -> movierequests -> [SQLite (0) / MySQL (23)] = -23
- [!!] -> notificationtemplates -> [SQLite (0) / MySQL (100)] = -100
- [!!] -> notificationuserid -> [SQLite (0) / MySQL (1)] = -1
- [!!] -> requestlog -> [SQLite (0) / MySQL (36)] = -36
- [!!] -> requestqueue -> [SQLite (0) / MySQL (4)] = -4
- [!!] -> seasonrequests -> [SQLite (0) / MySQL (25)] = -25
- [!!] -> tvrequests -> [SQLite (0) / MySQL (13)] = -13
- [!!] -> usernotificationpreferences -> [SQLite (0) / MySQL (88)] = -88
- [!!] -> userqualityprofiles -> [SQLite (0) / MySQL (11)] = -11
- Checking  [############################################################] 29/29

MySQL > Disconnecting... [✓]

----------------------------------------------------------------
----------------------------------------------------------------

- Processing DataBase (SettingsDatabase)...
  -------------------

- Saving in (C:\Plex\Ombi\migration.json)... [✓]
Generate file "database.json":
- Saving in (C:\Plex\Ombi\database.json)... [✓]

MySQL > Connecting... [✓]
- Reading   [############################################################] 1/1
Read tables [✓]

Check migration.json:
- OmbiDatabase [No Config >> Skip]
- SettingsDatabase [SQLite >> Migrate]
- ExternalDatabase [No Config >> Skip]

Dump SQLite:
- SettingsDatabase  [############################################################] 24/24

Start clean tables:
- [CLEAN ] -> applicationconfiguration -> rows: 4
- [CLEAN ] -> globalsettings -> rows: 2
- [CLEAN ] -> __efmigrationshistory -> rows: 1

- Running   [############################################################] 3/3
Clean tables [✓]

Start Migration:
- Preparing [############################################################] 30/30
- Running   [############################################################] 15/15
- [!!] -> __efmigrationshistory -> [SQLite (0) / MySQL (1)] = -1
- [!!] -> applicationconfiguration -> [SQLite (0) / MySQL (4)] = -4
- [!!] -> globalsettings -> [SQLite (0) / MySQL (10)] = -10
- Checking  [############################################################] 3/3

MySQL > Disconnecting... [✓]

----------------------------------------------------------------
----------------------------------------------------------------

- Processing DataBase (ExternalDatabase)...
  -------------------

- Saving in (C:\Plex\Ombi\migration.json)... [✓]
Generate file "database.json":
- Saving in (C:\Plex\Ombi\database.json)... [✓]

MySQL > Connecting... [✓]
- Reading   [############################################################] 1/1
Read tables [✓]

Check migration.json:
- OmbiDatabase [No Config >> Skip]
- SettingsDatabase [No Config >> Skip]
- ExternalDatabase [SQLite >> Migrate]

Dump SQLite:
- ExternalDatabase  [############################################################] 31705/31705

Start clean tables:
- [CLEAN ] -> __efmigrationshistory -> rows: 1

- Running   [############################################################] 1/1
Clean tables [✓]

Start Migration:
- Preparing [############################################################] 31711/31711
- Running   [############################################################] 31684/31684
- [!!] -> __efmigrationshistory -> [SQLite (0) / MySQL (2)] = -2
- [!!] -> plexepisode -> [SQLite (0) / MySQL (14865)] = -14865
- [!!] -> plexseasonscontent -> [SQLite (0) / MySQL (1032)] = -1032
- [!!] -> plexservercontent -> [SQLite (0) / MySQL (1925)] = -1925
- [!!] -> radarrcache -> [SQLite (0) / MySQL (1066)] = -1066
- [!!] -> sonarrcache -> [SQLite (0) / MySQL (237)] = -237
- [!!] -> sonarrepisodecache -> [SQLite (0) / MySQL (12557)] = -12557
- Checking  [############################################################] 14/14

MySQL > Disconnecting... [✓]

----------------------------------------------------------------
----------------------------------------------------------------

> Updating database.json...
- Saving in (C:\Plex\Ombi\database.json)... [✓]
````

When I try to start Ombi I get this output
````
C:\Plex\Ombi>ombi
Hello, welcome to Ombi
Valid options are:
Ombi 4.0.721
Copyright (C) 2020 Ombi

  --host       (Default: http://*:5000) Set to a semicolon-separated (;) list of
               URL prefixes to which the server should respond. For example,
               http://localhost:123. Use "localhost" to indicate that the server
               should listen for requests on any IP address or hostname using
               the specified port and protocol (for example,
               http://localhost:5000). The protocol (http:// or https://) must
               be included with each URL. Supported formats vary between
               servers.

  --storage    Storage path, where we save the logs and database

  --baseurl    The base URL for reverse proxy scenarios

  --demo       Demo mode, you will never need to use this, fuck that fruit
               company...

  --help       Display this help screen.

  --version    Display version information.



Unhandled exception. MySqlConnector.MySqlException (0x80004005): Table 'applicationconfiguration' already exists
 ---> MySqlConnector.MySqlException (0x80004005): Table 'applicationconfiguration' already exists
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior)
   at MySqlConnector.MySqlDataReader.ActivateResultSet()
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken)
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken)
   at MySqlConnector.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken)
   at MySqlConnector.MySqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at Ombi.Store.Context.MySql.SettingsMySqlContext..ctor(DbContextOptions`1 options)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Ombi.Program.Main(String[] args)
````

**Desktop (please complete the following information):**
 - OS: Windows Server 2019

**Ombi Version (please complete the following information):**
 - Version: 4.0.721
- Media Server: Plex
- Database Type: MySQL

**Comment by vsc55** [comment]
It looks like an error in the migration or in the update of tables by ombi.

Can you try to do the migration again?
If it keeps giving you an error, can you report the content of the tabas "__efmigrationshistory"?

**Comment by KierenConnell** [comment]
Re-ran the migration process with the --force argument, and when I start Ombi I'm now getting a similar, but different error.
Now it's telling me the table 'mobiledevices' already exists.

```
C:\Plex\Ombi>ombi
Hello, welcome to Ombi
Valid options are:
Ombi 4.0.721
Copyright (C) 2020 Ombi

  --host       (Default: http://*:5000) Set to a semicolon-separated (;) list of
               URL prefixes to which the server should respond. For example,
               http://localhost:123. Use "localhost" to indicate that the server
               should listen for requests on any IP address or hostname using
               the specified port and protocol (for example,
               http://localhost:5000). The protocol (http:// or https://) must
               be included with each URL. Supported formats vary between
               servers.

  --storage    Storage path, where we save the logs and database

  --baseurl    The base URL for reverse proxy scenarios

  --demo       Demo mode, you will never need to use this, fuck that fruit
               company...

  --help       Display this help screen.

  --version    Display version information.



We are running on http://*:5000
C:\Plex\Ombi
Unhandled exception. MySqlConnector.MySqlException (0x80004005): Table 'mobiledevices' already exists
 ---> MySqlConnector.MySqlException (0x80004005): Table 'mobiledevices' already exists
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior)
   at MySqlConnector.MySqlDataReader.ActivateResultSet()
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken)
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken)
   at MySqlConnector.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken)
   at MySqlConnector.MySqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at Ombi.Store.Context.MySql.OmbiMySqlContext..ctor(DbContextOptions`1 options)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Ombi.Startup.Configure(IApplicationBuilder app, ILoggerFactory loggerFactory, IServiceProvider serviceProvider)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Ombi.Program.Main(String[] args)
```

__efmigrationhistory from ombi database

MigrationID | ProductVersion
------------- | -------------
20191102235658_Inital | 3.1.8
20191102235852_Inital | 2.2.6-servicing-10079
20200218231003_MobileDevices | 3.1.8
20200516200222_IssueCreatedDate | 3.1.8
20200610223651_UserProfile | 3.1.8
20200731151356_RemoveEmbyConnectionid | 3.1.8

__efmigrationhistory from ombi_external database
MigrationID | ProductVersion
------------- | -------------
20191103205133_Inital | 3.1.8
20191103213915_Inital | 2.2.6-servicing-10079
20191113213617_RequestIdPatch | 3.1.8

__efmigrationhistory from ombi_settings database
MigrationID | ProductVersion
------------- | -------------
20191103205204_Inital | 3.1.8
20191103205915_Inital | 2.2.6-servicing-10079

**Comment by KierenConnell** [comment]
Weird Windows based issue.
--migrate resolves the issue.
Thanks to @vsc55 for kindly shipping through pre-migrated DB's

**Comment by dataham** [comment]
It looks like I'm experiencing the exact same issue as @KierenConnell . @vsc55 what was the solution that worked?

**Comment by vsc55** [comment]
Hi @dataham,
What operating system are you using?

**Comment by dataham** [comment]
I'm using Windows 10 Version 21H1. 

I'm not able to get Ombi to start with the database.json file. I have the same error message as Kieren. Using the --force argument gave me the same result with 'mobiledevices' already existing. 

What I was able to do was rename the database.json file, start Ombi, rename the file back, refresh and it says it's using MySQL. However if I try to restart Ombi I get the same error again.

**Comment by vsc55** [comment]
Hi @dataham,
A couple of questions.
1. Are you going to use one database for all the tables, or are you going to separate the tables into different databases?
2. You can copy the content of the file "database.json" and "migration.json".

**Comment by dataham** [comment]
I tried both one database for all the tables and separate tables into different databases. Currently it's setup separately.

database.json
`{"OmbiDatabase": {"Type": "MySQL", "ConnectionString": "Server=localhost;Port=3306;Database=Ombi;User=ombi;Password=ombi"}, "SettingsDatabase": {"Type": "MySQL", "ConnectionString": "Server=localhost;Port=3306;Database=Ombi_Settings;User=ombi;Password=ombi"}, "ExternalDatabase": {"Type": "MySQL", "ConnectionString": "Server=localhost;Port=3306;Database=Ombi_External;User=ombi;Password=ombi"}}`

migration.json
`{"ExternalDatabase": {"ConnectionString": "Data Source=C:\\Apps\\Ombi\\OmbiExternal.db", "Type": "sqlite"}}`

**Comment by vsc55** [comment]
Hi @dataham,
From what I see the file "migration.json" is not complete, 2 sqlite databases are missing:
This would be an example of how it should be: 

```
{
	"OmbiDatabase": {
		"Type": "sqlite",
		"ConnectionString": "Data Source=C:\\Apps\\Ombi\\Ombi.db"
	},
	"SettingsDatabase": {
		"Type": "sqlite",
		"ConnectionString": "Data Source=C:\\Apps\\Ombi\\OmbiSettings.db"
	},
	"ExternalDatabase": {
		"Type": "sqlite",
		"ConnectionString": "Data Source=C:\\Apps\\Ombi\\OmbiExternal.db"
	}
}
```

**Comment by dataham** [comment]
I just tried those steps and it leads me back to the same error above. It looks like it migrated the data, but I still can't launch Ombi after. 

`Unhandled exception. MySqlConnector.MySqlException (0x80004005): Table 'applicationconfiguration' already exists
 ---> MySqlConnector.MySqlException (0x80004005): Table 'applicationconfiguration' already exists
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior)
   at MySqlConnector.MySqlDataReader.ActivateResultSet()
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken)
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken)
   at MySqlConnector.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken)
   at MySqlConnector.MySqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at Ombi.Store.Context.MySql.SettingsMySqlContext..ctor(DbContextOptions`1 options)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Ombi.Program.Main(String[] args)
   at Ombi.Program.<Main>(String[] args)`

**Comment by vsc55** [comment]
After running the migration that contains the file "migration.json"? 
When executing the migration process, did the script give any error or warning message?

**Comment by vsc55** [comment]
Hi @dataham,
I have been doing tests and I have detected that when you run "ombi.exe --migrate" you have to be in the directory where ombi is installed because if you are not in that directory the creation of tables fails.

This is the test I have done, with the database without any table and the file "ombi_sqlite2mysql.py" in the same folder where ombi is installed. 

CMD Windows:
```
c:\>cd C:\Apps\Ombi
c:\Apps\Ombi> python ombi_sqlite2mysql.py -c C:\Apps\Ombi --only_db_json --host localhost --db Ombi --user ombi --passwd ombi
Migration tool from SQLite to MySql/MariaDB for ombi (3.0.4) By VSC55

Generate file "database.json":
- Saving in (C:\Apps\Ombi\database.json)... [✓]

C:\Apps\Ombi>Ombi.exe --migrate
Hello, welcome to Ombi
Valid options are:
Ombi 4.0.1458
Copyright (C) 2021 Ombi

  --host       (Default: http://*:5000) Set to a semicolon-separated (;) list of
               URL prefixes to which the server should respond. For example,
               http://localhost:123. Use "localhost" to indicate that the server
               should listen for requests on any IP address or hostname using
               the specified port and protocol (for example,
               http://localhost:5000). The protocol (http:// or https://) must
               be included with each URL. Supported formats vary between
               servers.

  --storage    Storage path, where we save the logs and database

  --baseurl    The base URL for reverse proxy scenarios

  --demo       Demo mode, you will never need to use this, fuck that fruit
               company...

  --migrate    Will run the migrations then exit the application

  --help       Display this help screen.

  --version    Display version information.



Migrate in progress...
Migrate complete.

C:\Apps\Ombi> python ombi_sqlite2mysql.py -c C:\Apps\Ombi --host localhost --db Ombi --user ombi --passwd ombi
Migration tool from SQLite to MySql/MariaDB for ombi (3.0.4) By VSC55

Generate file "database.json":
- Saving in (C:\Apps\Ombi\database.json)... [✓]

MySQL > Connecting... [✓]
- Reading   [############################################################] 1/1
Read tables [✓]

Check migration.json:
- OmbiDatabase [SQLite >> Migrate]
- SettingsDatabase [SQLite >> Migrate]
- ExternalDatabase [SQLite >> Migrate]

Dump SQLite:
- OmbiDatabase      [############################################################] 174/174
- SettingsDatabase  [############################################################] 17/17
- ExternalDatabase  [############################################################] 7/7

Start clean tables:
- [BACKUP] -> __EFMigrationsHistory
- [SKIP  ] -> __EFMigrationsHistory -> rows: 13

- Running   [############################################################] 2/2
Clean tables [✓]

Start Migration:
- Preparing [############################################################] 210/210
- Running   [############################################################] 153/153
- Checking  [############################################################] 46/46
Migration [✓]

MySQL > Disconnecting... [✓]

C:\Apps\Ombi>Ombi.exe
Hello, welcome to Ombi
Valid options are:
Ombi 4.0.1458
Copyright (C) 2021 Ombi

  --host       (Default: http://*:5000) Set to a semicolon-separated (;) list of
               URL prefixes to which the server should respond. For example,
               http://localhost:123. Use "localhost" to indicate that the server
               should listen for requests on any IP address or hostname using
               the specified port and protocol (for example,
               http://localhost:5000). The protocol (http:// or https://) must
               be included with each URL. Supported formats vary between
               servers.

  --storage    Storage path, where we save the logs and database

  --baseurl    The base URL for reverse proxy scenarios

  --demo       Demo mode, you will never need to use this, fuck that fruit
               company...

  --migrate    Will run the migrations then exit the application

  --help       Display this help screen.

  --version    Display version information.



Wrote new baseurl at C:\Apps\Ombi\ClientApp\dist\index.html
Total Requests to migrate 1
Finished Migration
We are running on http://*:5000
C:\Apps\Ombi
```

**Comment by dataham** [comment]
There's no error when running migration. I tried deleting the table and trying again with ombi_sqlite2mysql.py in the same directory. I get the same result 

I did a query of the table, and the information for movierequests is populated with everything I had in the SQLite database so I think the migration worked. Just something is preventing Ombi from starting with the MySQL table. 
Unhandled exception. MySqlConnector.MySqlException (0x80004005): Table 'applicationconfiguration' already exists

Here are the results of the _efmigrationhistory

<HTML>
<BODY>
<TABLE><TR><TD>20191102235658_Inital</TD><TD>2.2.6-servicing-10079</TD></TR><TR><TD>20191103205133_Inital</TD><TD>2.2.6-servicing-10079</TD></TR><TR><TD>20191103205204_Inital</TD><TD>2.2.6-servicing-10079</TD></TR><TR><TD>20191113213617_RequestIdPatch</TD><TD>2.2.6-servicing-10079</TD></TR><TR><TD>20200218231003_MobileDevices</TD><TD>5.0.1</TD></TR><TR><TD>20200516200222_IssueCreatedDate</TD><TD>5.0.1</TD></TR><TR><TD>20200610223651_UserProfile</TD><TD>5.0.1</TD></TR><TR><TD>20200731151356_RemoveEmbyConnectionid</TD><TD>5.0.1</TD></TR><TR><TD>20201212014227_Jellyfin</TD><TD>5.0.1</TD></TR><TR><TD>20210106134000_UserStreamingCountry</TD><TD>5.0.1</TD></TR><TR><TD>20210305151854_TvRequestProviderId</TD><TD>5.0.1</TD></TR><TR><TD>20210408073232_SonarrProfileOnRequest</TD><TD>5.0.1</TD></TR><TR><TD>20210615145321_SonarrSyncMovieDbData</TD><TD>5.0.1</TD></TR></TABLE>

</BODY>
</HTML>

I just joined in on the Discord channel.

**Comment by Khazaztroph** [comment]
> 

Cheers, your post fixed my issue with MySQL and latest build of OMBi and Sonarr v4
