### ISSUE TITLE
v4 - Unable to upgrade to any version higher than 4.0.681.0

### ISSUE THREAD

**Issue by masterzxz** [tidusjar/Ombi#3881]
**Describe the bug**
When I upgrade Ombi v4 to any version higher than 4.0.681.0, I get the following output after which I get "Ombi.exe has stopped working.". Both the x64 and x86 are producing the same behaviour (I normally run x64):

```
Hello, welcome to Ombi
Valid options are:
Ombi 4.0.710
Copyright (C) 2020 Ombi

  --host       (Default: http://*:5000) Set to a semicolon-separated (;) list of
               URL prefixes to which the server should respond. For example,
               http://localhost:123. Use "localhost" to indicate that the server
               should listen for requests on any IP address or hostname using
               the specified port and protocol (for example,
               http://localhost:5000). The protocol (http:// or https://) must
               be included with each URL. Supported formats vary between
               servers.

  --storage    Storage path, where we save the logs and database

  --baseurl    The base URL for reverse proxy scenarios

  --demo       Demo mode, you will never need to use this, fuck that fruit
               company...

  --help       Display this help screen.

  --version    Display version information.



We are running on http://*:5000
C:\OMBI
Unhandled exception. System.IO.FileLoadException: 0x80131621
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.RelatedAssemblyAttribute.AssemblyLoadContextWrapper.LoadFromAssemblyPath(String assemblyPath)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.RelatedAssemblyAttribute.GetRelatedAssemblies(Assembly assembly, Boolean throwOnError, Func`2 fileExists, AssemblyLoadContextWrapper assemblyLoadContext)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.RelatedAssemblyAttribute.GetRelatedAssemblies(Assembly assembly, Boolean throwOnError)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.GetAssemblyClosure(Assembly assembly)+MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateDefaultParts(String entryAssemblyName)
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.GetApplicationPartManager(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.AddMvcCore(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddControllersCore(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddControllersWithViewsCore(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddControllersWithViews(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(IServiceCollection services)
   at Ombi.Startup.ConfigureServices(IServiceCollection services)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Ombi.Program.Main(String[] args)

```

**To Reproduce**
1. Upgrade Ombi v4.0.681.0 to any version released after it.
2. Try to start Ombi.
3. Ombi crashes.

**Expected behavior**
I expect Ombi to start and work.

**Screenshots**
See output above.

**Logs (Logs directory where Ombi is located)**
No output in logs.

**Desktop (please complete the following information):**
 - OS: Windows Server 2019 Datacenter edition (1809)

**Ombi Version (please complete the following information):**
 - Version: any version above v4.0.681.0
- Media Server: Plex
- Database Type: SQLite 

**Additional context**
N/A.

**Comment by masterzxz** [comment]
After performing a clean install of Ombi, and copying only the 3 .db files + the Swagger.xml file, I got it to work. Before I was making a backup of the Ombi directory, and would unpack the update archive to the existing installation folder and choose to overwrite existing files. This has always worked for me without issues, but it seemed to be causing issues now. Problem solved, closing this issue.
