### ISSUE TITLE
The library libhostfxr.so was found, but loading it from /opt/Ombi/libhostfxr.so failed

### ISSUE THREAD

**Issue by polklabs** [tidusjar/Ombi#3882]
**Describe the bug**
When manually running a plex full sync or recently added sync the sync fails with the following error message in the console repeated dozens of times. Requested movies are not being marked as available.

```
The library libhostfxr.so was found, but loading it from /opt/Ombi/libhostfxr.so failed
 - Installing .NET Core prerequisites might help resolve this problem.
    https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
ombi.service: Main process exited, code=exited, status=130/n/a
ombi.service: Failed with result 'exit-code'.
ombi.service: Service hold-off time over, scheduling restart.
ombi.service: Scheduled restart job, restart counter is at 5.
Stopped Ombi - PMS Requests System.
Started Ombi - PMS Requests System.
```

I tried going to the link and installing dotnet and core but it seemed to make no difference.

Could this be a permission issue?

**To Reproduce**
1 Install Ombi on Ubuntu Server
1. Go to Settings->Media Server->Plex
2. Click on 'Manually Run Recently Added Sync'
3. Look at `sudo systemctl status ombi.service`

**Expected behavior**
The sync should work and requested movies should be marked as available

**Screenshots**

**Logs (Logs directory where Ombi is located)**
Logs are filled with the following errors, not sure if related

```
2020-11-22 11:50:13.166 -08:00 [Error] Exception when adding new Movie "Enola Holmes"
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: [. Path 'MediaContainer.Metadata[0].Guid', line 1, position 10373.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 78
   at Ombi.Api.Plex.PlexApi.GetMetadata(String authToken, String plexFullHost, Int32 itemId) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 159
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessServer(PlexServers servers, Boolean recentlyAddedSearch) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 264
```

**Desktop (please complete the following information):**
 - OS: Ubuntu Server18.04.5

**Ombi Version (please complete the following information):**
 - Version 3.0.5223
- Media Server Plex
- Database Type: SQLite

**Additional context**

**Comment by tidusjar** [comment]
update to V4, this is due to the metadata change that Plex introduces with their new media agent
