### ISSUE TITLE
"Item added to fault queue" notification triggered for all requests despite sucessful add

### ISSUE THREAD

**Issue by gribboa** [tidusjar/Ombi#3883]
**Describe the bug**
When any user (including admin) requests to add a film, the "could not be added. This has been added into the requests queue" message is triggered - however the film is successfully requested and send onwards to Radarr.

**To Reproduce**
1. Search for any film
2. Click Request
3. Item added to fault queue notifications triggered
4. Error visible in log
5. Film is requested successfully

**Expected behavior**
Film added to requests with no "item added to fault queue" notifications received. 

**Logs (Logs directory where Ombi is located)**
```
2020-11-22 22:29:11.203 +00:00 [Error] Error when sending movie to DVR app, added to the request queue
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path 'images', line 10, position 5.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty contai>
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, >
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContr>
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProper>
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member>
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Radarr.RadarrApi.AddMovie(Int32 tmdbId, String title, Int32 year, Int32 qualityId, String rootPath, String apiKey, String baseUrl, Boolean se>
   at Ombi.Core.Senders.MovieSender.SendToRadarr(MovieRequests model, RadarrSettings settings) in C:\projects\requestplex\src\Ombi.Core\Senders\MovieSender.>
   at Ombi.Core.Senders.MovieSender.Send(MovieRequests model) in C:\projects\requestplex\src\Ombi.Core\Senders\MovieSender.cs:line 57
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.01.1 LTS
- Docker: 19.03.13
- Docker image: linuxserver/ombi

**Ombi Version (please complete the following information):**
 - Version: OMBI_RELEASE=v3.0.5223 VERSION=v3.0.5223-ls76
- Media Server: Plex
- Database Type: SQLite

**Additional context**
Unsure when issue started as only recently enabled notifications.

**Comment by escservices** [comment]
This may be the same issue as mine, I can't delete the failed request from Ombi (throws an error in the log) and it was successfully added to Sonarr.  #3870

**Comment by gribboa** [comment]
> This may be the same issue as mine, I can't delete the failed request from Ombi (throws an error in the log) and it was successfully added to Sonarr. #3870

Perhaps related, however in my case the request is never actually added to the failed request queue (unless it is and then immediately cleared).

**Comment by goose-ws** [comment]
Same issue. Relevant log lines:

```
2020-12-02 20:32:44.427 -05:00 [Error] Error when sending movie to DVR app, added to the request queue
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path 'images', line 10, position 5.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Radarr.RadarrApi.AddMovie(Int32 tmdbId, String title, Int32 year, Int32 qualityId, String rootPath, String apiKey, String baseUrl, Boolean searchNow, String minimumAvailability) in C:\projects\requestplex\src\Ombi.Api.Radarr\RadarrApi.cs:line 111
   at Ombi.Core.Senders.MovieSender.SendToRadarr(MovieRequests model, RadarrSettings settings) in C:\projects\requestplex\src\Ombi.Core\Senders\MovieSender.cs:line 160
   at Ombi.Core.Senders.MovieSender.Send(MovieRequests model) in C:\projects\requestplex\src\Ombi.Core\Senders\MovieSender.cs:line 57
```

**Comment by tidusjar** [comment]
Fixed in V3 develop and V4
