### ISSUE TITLE
`--help` call needlessly tries to write to the Database

### ISSUE THREAD

**Issue by hashworks** [tidusjar/Ombi#3941]
**Describe the bug**
When one starts ombi with `--help` it tries to write to a database.

**To Reproduce**
1. Run `/usr/lib/ombi/Ombi --help` as an unprevileged user
2. Notice the exception

**Expected behavior**
A `--help` call should not try to do any IO operations at all.

**Logs**
```
$ /usr/lib/ombi/Ombi --help
Ombi 3.0.5223-master
Copyright (C) 2020 Ombi

  --host       (Default: http://*:5000) Set to a semicolon-separated (;) list of URL prefixes to which the server should respond. For example, http://localhost:123. Use "*" to indicate that the server should
               listen for requests on any IP address or hostname using the specified port and protocol (for example, http://*:5000). The protocol (http:// or https://) must be included with each URL. Supported
               formats vary between servers.

  --storage    Storage path, where we save the logs and database

  --baseurl    The base URL for reverse proxy scenarios

  --demo       Demo mode, you will never need to use this, fuck that fruit company...

  --help       Display this help screen.

  --version    Display version information.

CommandLine.HelpRequestedError
Hello, welcome to Ombi
Valid options are:
Ombi 3.0.5223-master
Copyright (C) 2020 Ombi

  --host       (Default: http://*:5000) Set to a semicolon-separated (;) list
               of URL prefixes to which the server should respond. For example,
               http://localhost:123. Use "*" to indicate that the server should
               listen for requests on any IP address or hostname using the
               specified port and protocol (for example, http://*:5000). The
               protocol (http:// or https://) must be included with each URL.
               Supported formats vary between servers.

  --storage    Storage path, where we save the logs and database

  --baseurl    The base URL for reverse proxy scenarios

  --demo       Demo mode, you will never need to use this, fuck that fruit
               company...

  --help       Display this help screen.

  --version    Display version information.


Unhandled Exception: Microsoft.Data.Sqlite.SqliteException: SQLite Error 8: 'attempt to write a readonly database'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.Data.Sqlite.SqliteConnectionExtensions.ExecuteNonQuery(SqliteConnection connection, String commandText)
   at Microsoft.Data.Sqlite.SqliteTransaction..ctor(SqliteConnection connection, IsolationLevel isolationLevel)
   at Microsoft.Data.Sqlite.SqliteConnection.BeginTransaction(IsolationLevel isolationLevel)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionWithNoPreconditions(IsolationLevel isolationLevel)
   at Ombi.Program.Main(String[] args) in C:\projects\requestplex\src\Ombi\Program.cs:line 92
zsh: abort (core dumped)  /usr/lib/ombi/Ombi --help
```

**Ombi Version (please complete the following information):**
 - Version [e.g. 3.0.5223-master]
- Database Type: SQLite

**Comment by hashworks** [comment]
Additionally:
* The exception should be catched and a proper error should be displayed
* The help text is shown twice

**Comment by hashworks** [comment]
This is still an issue with `4.0.779`.

**Comment by tidusjar** [comment]
The help text is always shown on startup, so I don't support the --help command.

The reason why it's trying to write to the database, is because the application is starting up. Dont really see this as an issue.
