### ISSUE TITLE
Mobile Notification Failed - SSL Error

### ISSUE THREAD

**Issue by jaykder** [tidusjar/Ombi#3958]
**Describe the bug**
Mobile Notifications Not Working with SSL Error

**To Reproduce**
1. Go to Notifications - Mobile
2. Click on - Users
3. Scroll down to - User to test
4. Click Send Test Notification

**Expected behavior**
Test notification appears on registered mobile device.

**Logs from /etc/Ombi/Logs**
Logs from time of triggered test notification - 

2021-01-05 16:25:00.113 -05:00 [Error] Could not test Mobile Notifications
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__47_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request) in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
   at Ombi.Api.Notifications.OneSignalApi.PushNotification(List`1 playerIds, String message, Boolean isAdminNotification, Int32 requestId, Int32 requestType) in C:\projects\requestplex\src\Ombi.Api.Notifications\OneSignalApi.cs:line 55
   at Ombi.Notifications.Agents.MobileNotification.Send(List`1 playerIds, NotificationMessage model, MobileNotificationSettings settings, NotificationOptions requestModel, Boolean isAdminNotification) in C:\projects\requestplex\src\Ombi.Notifications\A$
   at Ombi.Notifications.Agents.MobileNotification.Test(NotificationOptions model, MobileNotificationSettings settings) in C:\projects\requestplex\src\Ombi.Notifications\Agents\MobileNotification.cs:line 241
   at Ombi.Notifications.BaseNotification`1.NotifyAsync(NotificationOptions model, Settings settings) in C:\projects\requestplex\src\Ombi.Notifications\BaseNotification.cs:line 99
   at Ombi.Controllers.External.TesterController.MobileNotificationTest(MobileNotificationTestViewModel settings) in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 456

**Desktop (please complete the following information):**
 - OS: Mobile = Android, Ombi = Raspberry Pi 4

**Ombi Version (please complete the following information):**
 - Version = 3.0.5223
- Media Server = Plex
- Database Type: SQLite

**Additional context**
No additional context, paid for the mobile app and the admin upgrade hoping for these notifications to work. Tested ping and nslookup for https://onesignal.com, succesfull for both, not being blocked by pihole.

**Comment by tidusjar** [comment]
Are you running pihole?

**Comment by jaykder** [comment]
I am, and thought I had verified onesignal was not being blocked as I could ping it, nslookup it, and browse to it....but looking at pihole logs it was being blocked. That's...odd. Anyways just whitelisted, seems to be working now. Now to figure out what's up with the pihole! Closing.
