### ISSUE TITLE
Status page (admin) gives a warning in f12

### ISSUE THREAD

**Issue by SuperPotatoMen** [tidusjar/Ombi#830]
See error:

```
moment.min.js:7 Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.
Arguments: [object Object]
Error
    at Function.createFromInputFallback (https://xxx/Content/moment.min.js:7:2787)
    at na (https://rxxxx/Content/moment.min.js:7:11632)
    at Ha (https://xxxt/Content/moment.min.js:7:16453)
    at Ga (https://xxx/Content/moment.min.js:7:16292)
    at Fa (https://xxx/Content/moment.min.js:7:15945)
    at Ia (https://xxx/Content/moment.min.js:7:16837)
    at Ja (https://xxxt/Content/moment.min.js:7:16878)
    at a (https://xxxx/Content/moment.min.js:7:44)
    at utcToLocal (https://XXXXXX/Content/site.js?v=1.10.1:24:12)
    at HTMLDivElement.<anonymous> (https://xxxxx/admin/scheduledjobs:300:27)

```

**Comment by tidusjar** [comment]
This will be removed when migrating to Angular 2
