### ISSUE TITLE
New install, Newsletter never goes out.

### ISSUE THREAD

**Issue by dunecokc** [tidusjar/Ombi#841]
#### Ombi Version:

V 1.10.1

#### Update Branch:

Stable

#### Operating System:

Windows Server 2012 Standard

#### Mono Version (only if your not on windows)

N/A

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

2016/12/25 18:18:15.902 PlexRequests.Services.Jobs.PlexContentCacher Error: Failed to obtain Plex libraries Mono.Data.Sqlite.SqliteException (0x80004005): Abort due to constraint violation
NOT NULL constraint failed: PlexContent.ProviderId
   at Mono.Data.Sqlite.SQLite3.Reset(SqliteStatement stmt)
   at Mono.Data.Sqlite.SQLite3.Step(SqliteStatement stmt)
   at Mono.Data.Sqlite.SqliteDataReader.NextResult()
   at Mono.Data.Sqlite.SqliteDataReader..ctor(SqliteCommand cmd, CommandBehavior behave)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command)
   at SQLiteAdapter.Insert(IDbConnection connection, IDbTransaction transaction, Nullable`1 commandTimeout, String tableName, String columnList, String parameterList, IEnumerable`1 keyProperties, Object entityToInsert)
   at Dapper.Contrib.Extensions.SqlMapperExtensions.Insert[T](IDbConnection connection, T entityToInsert, IDbTransaction transaction, Nullable`1 commandTimeout)
   at PlexRequests.Store.Repository.BaseGenericRepository`1.Insert(T entity) in C:\projects\requestplex\PlexRequests.Store\Repository\BaseGenericRepository.cs:line 86
   at PlexRequests.Services.Jobs.PlexContentCacher.CachedLibraries(PlexSettings plexSettings) in C:\projects\requestplex\PlexRequests.Services\Jobs\PlexContentCacher.cs:line 253
2016/12/25 19:00:15.726 PlexRequests.Services.Jobs.RecentlyAdded Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at PlexRequests.Helpers.StringHelper.<SplitEmailsByDelimiter>d__3.MoveNext() in C:\projects\requestplex\PlexRequests.Helpers\StringHelper.cs:line 81
   at PlexRequests.Services.Jobs.RecentlyAdded.Send(NewletterSettings newletterSettings, String html, PlexSettings plexSettings, Boolean testEmail) in C:\projects\requestplex\PlexRequests.Services\Jobs\RecentlyAdded.cs:line 475
   at PlexRequests.Services.Jobs.RecentlyAdded.Start(NewletterSettings newletterSettings, Boolean testEmail) in C:\projects\requestplex\PlexRequests.Services\Jobs\RecentlyAdded.cs:line 204
   at PlexRequests.Services.Jobs.RecentlyAdded.Execute(IJobExecutionContext context) in C:\projects\requestplex\PlexRequests.Services\Jobs\RecentlyAdded.cs:line 93 System.NullReferenceException: Object reference not set to an instance of an object.
   at PlexRequests.Helpers.StringHelper.<SplitEmailsByDelimiter>d__3.MoveNext() in C:\projects\requestplex\PlexRequests.Helpers\StringHelper.cs:line 81
   at PlexRequests.Services.Jobs.RecentlyAdded.Send(NewletterSettings newletterSettings, String html, PlexSettings plexSettings, Boolean testEmail) in C:\projects\requestplex\PlexRequests.Services\Jobs\RecentlyAdded.cs:line 475
   at PlexRequests.Services.Jobs.RecentlyAdded.Start(NewletterSettings newletterSettings, Boolean testEmail) in C:\projects\requestplex\PlexRequests.Services\Jobs\RecentlyAdded.cs:line 204
   at PlexRequests.Services.Jobs.RecentlyAdded.Execute(IJobExecutionContext context) in C:\projects\requestplex\PlexRequests.Services\Jobs\RecentlyAdded.cs:line 93
```

#### Problem Description:

I can make requests, have the requests filled, and get an email back from Ombi saying its now available.
This told me that Ombi is communicating with the Plex Server correctly and SMTP is working. Both Tests in the WebUI pass as expected. Originally Ombi had the wrong token, but I opened the XML on a media assest from the Server and changed the Auth Token to match. Restared service, same results, although before i did this, there were a lot more Failed to obtain Plex Libraries in the logs.
Was using old Meteor version on old Plex server. New server, new installs of everything. Everything works except sending out the Recently added email.

#### Reproduction Steps:

Unknown, since it has always been in a failed state for the Newsletter.

**Comment by tidusjar** [comment]
This is live in the Early Access Preview Branch
