### ISSUE TITLE
Unable to update 1.10.1106 to 2.0.1186

### ISSUE THREAD

**Issue by Ublala** [tidusjar/Ombi#901]
#### Ombi Version:

V 1.10.1106

#### Update Branch:

Stable/Early Access Preview

#### Operating System:

Windows 10

#### Problem Description:

I'm still at PlexRequests .net 1.10.1106 (stable branch). I selected the EAP branch and saved. Then I got a notice there was an update available (2.0.1186). I ran the auto update feature. PlexRequests .net runs the autoupdater, restarts but then just gives me the notice that there is an update available. I'm still at 1.10.1106 and it still says the available update is 2.0.1186. Am I doing something wrong? Is there a way to manually update to 2.0.1186 and if so, where do I get it from?

#### Reproduction Steps:

?

**Comment by Zirus1701** [comment]
I also have this issue, fresh install, I change the code branch to EAP and a few seconds later it shows an update is available. I click update, it spins like it's downloading/installing, and a few seconds later the page reloads. After the page reloads I'm at the login screen. After login, I'm still on the older version, and an update still shows as available. 

I'm using the same plexrequests.net version as OP, and my OS is Windows Server 2016.

Before clicking update, I've cleared the log in an attempt to grab the relevant section. So this log is everything that happens after clicking update, and until the page reloads. Hope this helps: 

`2017/01/08 11:37:25.774 PlexRequests.Api.ApiRequest Error: System.Xml.XmlException: 'doctype' is an unexpected token. The expected token is 'DOCTYPE'. Line 2, position 3.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(String expectedToken1, String expectedToken2)
   at System.Xml.XmlTextReaderImpl.ParseDoctypeDecl()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
   at RestSharp.Deserializers.XmlDeserializer.Deserialize[T](IRestResponse response)
   at RestSharp.RestClient.Deserialize[T](IRestRequest request, IRestResponse raw) System.Xml.XmlException: 'doctype' is an unexpected token. The expected token is 'DOCTYPE'. Line 2, position 3.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(String expectedToken1, String expectedToken2)
   at System.Xml.XmlTextReaderImpl.ParseDoctypeDecl()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
   at RestSharp.Deserializers.XmlDeserializer.Deserialize[T](IRestResponse response)
   at RestSharp.RestClient.Deserialize[T](IRestRequest request, IRestResponse raw)
2017/01/08 11:37:25.837 PlexRequests.Api.CouchPotatoApi Error: Exception when calling GetProfiles for CP, Retrying 00:00:05 PlexRequests.Helpers.Exceptions.ApiRequestException: Error retrieving response. Check inner details for more info. ---> System.Xml.XmlException: 'doctype' is an unexpected token. The expected token is 'DOCTYPE'. Line 2, position 3.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(String expectedToken1, String expectedToken2)
   at System.Xml.XmlTextReaderImpl.ParseDoctypeDecl()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
   at RestSharp.Deserializers.XmlDeserializer.Deserialize[T](IRestResponse response)
   at RestSharp.RestClient.Deserialize[T](IRestRequest request, IRestResponse raw)
   --- End of inner exception stack trace ---
   at PlexRequests.Api.ApiRequest.Execute[T](IRestRequest request, Uri baseUri) in C:\projects\requestplex\PlexRequests.Api\ApiRequest.cs:line 71
   at PlexRequests.Api.CouchPotatoApi.<>c__DisplayClass8_0.<GetProfiles>b__0() in C:\projects\requestplex\PlexRequests.Api\CouchPotatoApi.cs:line 123
   at Polly.Policy.<>c__DisplayClass8_0`1.<Execute>b__0()
   at Polly.RetrySyntax.<>c__DisplayClass14_0.<WaitAndRetry>b__1()
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`1 action, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory)
2017/01/08 11:37:30.073 PlexRequests.Core.Setup Info: Begin executing GetProfiles call to Sonarr for quality profiles 
2017/01/08 11:37:32.809 PlexRequests.Api.ApiRequest Error: System.InvalidOperationException: There is an error in XML document (1, 2). ---> System.InvalidOperationException: <html xmlns=''> was not expected.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexLibraries.Read4_MediaContainer()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at PlexRequests.Api.ApiRequest.DeserializeXml[T](String input) in C:\projects\requestplex\PlexRequests.Api\ApiRequest.cs:line 137 System.InvalidOperationException: There is an error in XML document (1, 2). ---> System.InvalidOperationException: <html xmlns=''> was not expected.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexLibraries.Read4_MediaContainer()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at PlexRequests.Api.ApiRequest.DeserializeXml[T](String input) in C:\projects\requestplex\PlexRequests.Api\ApiRequest.cs:line 137
`

**Comment by escservices** [comment]
@Ublala @Zirus1701 I was able to manually upgrade by switching to EAP, attempt the update, where it says Plex Requests Early Access Preview it's a link to the compiled update which as of right now is here https://ci.appveyor.com/api/buildjobs/p2d13prkr8cs59ie/artifacts/Ombi.zip download that and unblock it.  Overwriting the existing files isn't really an option because of the new name change to Ombi so most of the files have different names, so make a new folder called Ombi copy the contents of the download into the folder then go into your plexrequests.net folder and grab the PlexRequests.sqlite move it to the Ombi folder and rename it Ombi.sqlite then follow procedure to re setup nssm but now instead of plexrequests.exe its ombi.exe etc... then once I started it up again I just had to switch to EAP branch again and it was updated and data seemed to be all there.  I might be missing something but if you wanted to try it manually this seems to be working.

**Comment by Zirus1701** [comment]
@escservices Thanks a bunch! Followed that process and appears to be up and running.

**Comment by escservices** [comment]
@Zirus1701 No Problem!

**Comment by Zirus1701** [comment]
@escservices Don't mean to be a bother, but Got another error. I just let the application create a new database instead of copying mine over to it. That way my old CouchPotato settings would be removed. I configured it for Watcher and tried add a request to the "Movies" section. It adds the request successfully, however I have this error in the log and it never adds to watcher. 

This path at the end of the error: "C:\projects\requestplex" doesn't exist on my system. Could that be part of the issue? Perhaps the install needs to be in that location? 

`Unexpected character encountered while parsing value: <. Path '', line 0, position 0.	Ombi.Core.MovieSender	Error	1/8/2017 4:41:35 PM`

`Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0. at Newtonsoft.Json.JsonTextReader.ParseValue() at Newtonsoft.Json.JsonTextReader.Read() at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings) at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings) at Ombi.Api.WatcherApi.AddMovie(String imdbId, String apiKey, Uri baseUrl) in C:\projects\requestplex\Ombi.Api\WatcherApi.cs:line 55	Ombi.Api.WatcherApi	Error	1/8/2017 4:41:35 PM`

**Comment by tidusjar** [comment]
Hello. The path you are seeing is the path it was compiled on, so don't worry about that. 

The error is possibly that we cannot connect to Watcher. Make sure your settings are correct and that the test button comes back with a success

**Comment by Zirus1701** [comment]
Looking at the Watcher settings, they look correct. When clicking the "Test Connection" button, green popup says it was successful. When clicking "Submit" green popup says the settings were updated successfully. No errors on that part. However, looking back at the log, I have the same error as above. 

I do have a rule to allow inbound access to Watcher (just opened tcp 9090) in the windows firewall on that box. I'm not sure what else it would be.

**Comment by escservices** [comment]
@Zirus1701 Might be stupid but did you remember to set the AppDirectory when setting up nssm.  `nssm set Ombi AppDirectory "C:\YourOmbiDirectory"
`

**Comment by Zirus1701** [comment]
You mean this parameter (below)? Or maybe I missed something. 

![image](https://cloud.githubusercontent.com/assets/24596332/21754579/e3a13186-d5c8-11e6-818e-9b4295c48982.png)

**Comment by escservices** [comment]
That looks right, AppDirectory would be "Startup directory" and you have the right path. Not sure

**Comment by SuperPotatoMen** [comment]
Auto updater is still broken. See master ticket: https://github.com/tidusjar/Ombi/issues/236
