### ISSUE TITLE
Sonarr "Invalid Path"

### ISSUE THREAD

**Issue by Oogar** [tidusjar/Ombi#906]
#### Ombi Version:

v1.10.1

#### Update Branch:

Stable

#### Operating System:

Widows Server 2016 (Virtual)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

2017/01/10 00:59:46.686 PlexRequests.Api.SonarrApi Error: Exception when calling AddSeries for Sonarr, Retrying 00:00:02 Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'PlexRequests.Api.Models.Sonarr.SonarrAddSeries' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at PlexRequests.Api.ApiRequest.ExecuteJson[T](IRestRequest request, Uri baseUri) in C:\projects\requestplex\PlexRequests.Api\ApiRequest.cs:line 123
   at PlexRequests.Api.SonarrApi.<>c__DisplayClass7_1.<AddSeries>b__2() in C:\projects\requestplex\PlexRequests.Api\SonarrApi.cs:line 123
   at Polly.Policy.<>c__DisplayClass8_0`1.<Execute>b__0()
   at Polly.RetrySyntax.<>c__DisplayClass14_0.<WaitAndRetry>b__1()
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`1 action, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory)
2017/01/10 00:59:48.755 PlexRequests.Api.SonarrApi Error: Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'PlexRequests.Api.Models.Sonarr.SonarrAddSeries' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at PlexRequests.Api.ApiRequest.ExecuteJson[T](IRestRequest request, Uri baseUri) in C:\projects\requestplex\PlexRequests.Api\ApiRequest.cs:line 123
   at PlexRequests.Api.SonarrApi.<>c__DisplayClass7_1.<AddSeries>b__2() in C:\projects\requestplex\PlexRequests.Api\SonarrApi.cs:line 123
   at Polly.Policy.<>c__DisplayClass8_0`1.<Execute>b__0()
   at Polly.RetrySyntax.<>c__DisplayClass14_0.<WaitAndRetry>b__1()
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`1 action, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory)
   at Polly.RetrySyntax.<>c__DisplayClass14_1.<WaitAndRetry>b__0(Action action, Context context)
   at Polly.Policy.Execute[TResult](Func`1 action, Context context)
   at PlexRequests.Api.SonarrApi.AddSeries(Int32 tvdbId, String title, Int32 qualityId, Boolean seasonFolders, String rootPath, Int32 seasonCount, Int32[] seasons, String apiKey, Uri baseUrl, Boolean monitor, Boolean searchForMissingEpisodes) in C:\projects\requestplex\PlexRequests.Api\SonarrApi.cs:line 123 Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'PlexRequests.Api.Models.Sonarr.SonarrAddSeries' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at PlexRequests.Api.ApiRequest.ExecuteJson[T](IRestRequest request, Uri baseUri) in C:\projects\requestplex\PlexRequests.Api\ApiRequest.cs:line 123
   at PlexRequests.Api.SonarrApi.<>c__DisplayClass7_1.<AddSeries>b__2() in C:\projects\requestplex\PlexRequests.Api\SonarrApi.cs:line 123
   at Polly.Policy.<>c__DisplayClass8_0`1.<Execute>b__0()
   at Polly.RetrySyntax.<>c__DisplayClass14_0.<WaitAndRetry>b__1()
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`1 action, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory)
   at Polly.RetrySyntax.<>c__DisplayClass14_1.<WaitAndRetry>b__0(Action action, Context context)
   at Polly.Policy.Execute[TResult](Func`1 action, Context context)
   at PlexRequests.Api.SonarrApi.AddSeries(Int32 tvdbId, String title, Int32 qualityId, Boolean seasonFolders, String rootPath, Int32 seasonCount, Int32[] seasons, String apiKey, Uri baseUrl, Boolean monitor, Boolean searchForMissingEpisodes) in C:\projects\requestplex\PlexRequests.Api\SonarrApi.cs:line 123
2017/01/10 00:59:48.820 PlexRequests.Api.SonarrApi Error: Invalid Path 

```

#### Problem Description:

Seem to have an issue with setting up plexrequests.net (ombi) with Sonarr - specifically setting the proper root directory. Directory I am pointing to is a NFS mounted share in Windows Server 2016 using the native NFS support. Just want to determine whether it's my setup that's causing issues or something else.

Sonarr connects fine in test. Couchpotato works without a hitch.

**Comment by tidusjar** [comment]
What sonarr version are you using?

**Comment by Oogar** [comment]
Version
2.0.0.4472

Mono Version
4.2.3 (Stable 4.2.3.4/832de4b Wed Mar 16 13:19:08 UTC 2016)

**Comment by tidusjar** [comment]
And your path is what it should be for Sonarr? So if you are running Ombi on a different server, the path needs to be what it would look like on the Sonarr Server.

**Comment by Oogar** [comment]
I think the issue may have something to do with how I was setup. Sonarr docker running in FreeNAS and ombi running on a Windows VM. FreeNAS creates a symbolic link between local docker folders and folders in your actual storage.

So Sonarr sees the path like this - \series

Which points to the actual location of media - \mnt\Storage\Vault\Media\Series

Windows Server NFs network share - \\10.0.0.2\mnt\Storage\Vault\Media\ as drive letter Z:

Anyways it's a bit of a convoluted setup and I have, for the time being, moved Sonarr to the Windows VM instead of having it in a Docker.

I guess my question for this would be, what is ombi looking for when it checks that path? Does it want it to look the same as sonarr, or actually be pointing the the same directory as sonarr? How does it validate whether it is a correct path or not?

**Comment by tidusjar** [comment]
Ombi doesn't look for anything or validate the path, we just send it to Sonarr which then in turn validates the path.

So from what you said, `\series` should work

**Comment by Oogar** [comment]
Thanks for the response :) I'll test again tomorrow and let you know...I think I tried it with that path but will try again.
