### ISSUE TITLE
Not receiving email notifications for anything being requested

### ISSUE THREAD

**Issue by chrisausbun** [tidusjar/Ombi#935]
#### Ombi Version:

V 2.0.1224

#### Update Branch:

Development

#### Operating System:

Windows 10 Home x64

#### Problem Description:

Not receiving email notifications for any TV Shows and/or Movies being requested. I am however, receiving emails for issues being reported.

#### Reproduction Steps:

Request any movie or tv show.

**Comment by SuperPotatoMen** [comment]
Logs?

**Comment by dbershev** [comment]
I'm also having the issue. I'm on Ubuntu 16.04. http://pastebin.com/Qtmadgpu

**Comment by chrisausbun** [comment]
2017/01/16 12:04:18.954 Ombi.UI.Program Info: This is not Mono 
2017/01/16 19:15:52.383 Ombi.Api.ApiRequest Error: System.Net.WebException: The remote name could not be resolved: 'cyrusthevirus'
   at System.Net.HttpWebRequest.GetResponse()
   at RestSharp.Http.GetRawResponse(HttpWebRequest request)
   at RestSharp.Http.GetResponse(HttpWebRequest request) System.Net.WebException: The remote name could not be resolved: 'cyrusthevirus'
   at System.Net.HttpWebRequest.GetResponse()
   at RestSharp.Http.GetRawResponse(HttpWebRequest request)
   at RestSharp.Http.GetResponse(HttpWebRequest request)
2017/01/16 19:15:52.414 Ombi.Api.SonarrApi Error: Exception when calling GetProfiles for Sonarr, Retrying 00:00:02 Ombi.Helpers.Exceptions.ApiRequestException: Error retrieving response. Check inner details for more info. ---> System.Net.WebException: The remote name could not be resolved: 'cyrusthevirus'
   at System.Net.HttpWebRequest.GetResponse()
   at RestSharp.Http.GetRawResponse(HttpWebRequest request)
   at RestSharp.Http.GetResponse(HttpWebRequest request)
   --- End of inner exception stack trace ---
   at Ombi.Api.ApiRequest.ExecuteJson[T](IRestRequest request, Uri baseUri) in C:\projects\requestplex\Ombi.Api\ApiRequest.cs:line 116
   at Ombi.Api.SonarrApi.<>c__DisplayClass6_0.<GetProfiles>b__1() in C:\projects\requestplex\Ombi.Api\SonarrApi.cs:line 60
   at Polly.Policy.<>c__DisplayClass8_0`1.<Execute>b__0()
   at Polly.RetrySyntax.<>c__DisplayClass14_0.<WaitAndRetry>b__1()
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`1 action, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory)
2017/01/16 19:15:56.721 Ombi.Api.ApiRequest Error: System.Net.WebException: The remote name could not be resolved: 'cyrusthevirus'
   at System.Net.HttpWebRequest.GetResponse()
   at RestSharp.Http.GetRawResponse(HttpWebRequest request)
   at RestSharp.Http.GetResponse(HttpWebRequest request) System.Net.WebException: The remote name could not be resolved: 'cyrusthevirus'
   at System.Net.HttpWebRequest.GetResponse()
   at RestSharp.Http.GetRawResponse(HttpWebRequest request)
   at RestSharp.Http.GetResponse(HttpWebRequest request)
2017/01/16 19:15:56.736 Ombi.Api.SonarrApi Error: Exception when calling GetProfiles for Sonarr, Retrying 00:00:05 Ombi.Helpers.Exceptions.ApiRequestException: Error retrieving response. Check inner details for more info. ---> System.Net.WebException: The remote name could not be resolved: 'cyrusthevirus'
   at System.Net.HttpWebRequest.GetResponse()
   at RestSharp.Http.GetRawResponse(HttpWebRequest request)
   at RestSharp.Http.GetResponse(HttpWebRequest request)
   --- End of inner exception stack trace ---
   at Ombi.Api.ApiRequest.ExecuteJson[T](IRestRequest request, Uri baseUri) in C:\projects\requestplex\Ombi.Api\ApiRequest.cs:line 116
   at Ombi.Api.SonarrApi.<>c__DisplayClass6_0.<GetProfiles>b__1() in C:\projects\requestplex\Ombi.Api\SonarrApi.cs:line 60
   at Polly.Policy.<>c__DisplayClass8_0`1.<Execute>b__0()
   at Polly.RetrySyntax.<>c__DisplayClass14_0.<WaitAndRetry>b__1()
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`1 action, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory)
2017/01/16 19:16:04.057 Ombi.Api.ApiRequest Error: System.Net.WebException: The remote name could not be resolved: 'cyrusthevirus'
   at System.Net.HttpWebRequest.GetResponse()
   at RestSharp.Http.GetRawResponse(HttpWebRequest request)
   at RestSharp.Http.GetResponse(HttpWebRequest request) System.Net.WebException: The remote name could not be resolved: 'cyrusthevirus'
   at System.Net.HttpWebRequest.GetResponse()
   at RestSharp.Http.GetRawResponse(HttpWebRequest request)
   at RestSharp.Http.GetResponse(HttpWebRequest request)
2017/01/16 19:16:04.074 Ombi.Api.SonarrApi Error: Exception when calling GetProfiles for Sonarr, Retrying 00:00:10 Ombi.Helpers.Exceptions.ApiRequestException: Error retrieving response. Check inner details for more info. ---> System.Net.WebException: The remote name could not be resolved: 'cyrusthevirus'
   at System.Net.HttpWebRequest.GetResponse()
   at RestSharp.Http.GetRawResponse(HttpWebRequest request)
   at RestSharp.Http.GetResponse(HttpWebRequest request)
   --- End of inner exception stack trace ---
   at Ombi.Api.ApiRequest.ExecuteJson[T](IRestRequest request, Uri baseUri) in C:\projects\requestplex\Ombi.Api\ApiRequest.cs:line 116
   at Ombi.Api.SonarrApi.<>c__DisplayClass6_0.<GetProfiles>b__1() in C:\projects\requestplex\Ombi.Api\SonarrApi.cs:line 60
   at Polly.Policy.<>c__DisplayClass8_0`1.<Execute>b__0()
   at Polly.RetrySyntax.<>c__DisplayClass14_0.<WaitAndRetry>b__1()
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`1 action, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory)
2017/01/16 19:16:16.391 Ombi.Api.ApiRequest Error: System.Net.WebException: The remote name could not be resolved: 'cyrusthevirus'
   at System.Net.HttpWebRequest.GetResponse()
   at RestSharp.Http.GetRawResponse(HttpWebRequest request)
   at RestSharp.Http.GetResponse(HttpWebRequest request) System.Net.WebException: The remote name could not be resolved: 'cyrusthevirus'
   at System.Net.HttpWebRequest.GetResponse()
   at RestSharp.Http.GetRawResponse(HttpWebRequest request)
   at RestSharp.Http.GetResponse(HttpWebRequest request)
2017/01/16 19:16:36.543 Ombi.Api.ApiRequest Error: System.Net.WebException: The remote name could not be resolved: 'cyrusthevirus'
   at System.Net.HttpWebRequest.GetResponse()
   at RestSharp.Http.GetRawResponse(HttpWebRequest request)
   at RestSharp.Http.GetResponse(HttpWebRequest request) System.Net.WebException: The remote name could not be resolved: 'cyrusthevirus'
   at System.Net.HttpWebRequest.GetResponse()
   at RestSharp.Http.GetRawResponse(HttpWebRequest request)
   at RestSharp.Http.GetResponse(HttpWebRequest request)
2017/01/16 19:16:36.559 Ombi.Api.SonarrApi Error: Exception when calling GetProfiles for Sonarr, Retrying 00:00:02 Ombi.Helpers.Exceptions.ApiRequestException: Error retrieving response. Check inner details for more info. ---> System.Net.WebException: The remote name could not be resolved: 'cyrusthevirus'
   at System.Net.HttpWebRequest.GetResponse()
   at RestSharp.Http.GetRawResponse(HttpWebRequest request)
   at RestSharp.Http.GetResponse(HttpWebRequest request)
   --- End of inner exception stack trace ---
   at Ombi.Api.ApiRequest.ExecuteJson[T](IRestRequest request, Uri baseUri) in C:\projects\requestplex\Ombi.Api\ApiRequest.cs:line 116
   at Ombi.Api.SonarrApi.<>c__DisplayClass6_0.<GetProfiles>b__1() in C:\projects\requestplex\Ombi.Api\SonarrApi.cs:line 60
   at Polly.Policy.<>c__DisplayClass8_0`1.<Execute>b__0()
   at Polly.RetrySyntax.<>c__DisplayClass14_0.<WaitAndRetry>b__1()
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`1 action, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory)
2017/01/16 19:16:40.887 Ombi.Api.ApiRequest Error: System.Net.WebException: The remote name could not be resolved: 'cyrusthevirus'
   at System.Net.HttpWebRequest.GetResponse()
   at RestSharp.Http.GetRawResponse(HttpWebRequest request)
   at RestSharp.Http.GetResponse(HttpWebRequest request) System.Net.WebException: The remote name could not be resolved: 'cyrusthevirus'
   at System.Net.HttpWebRequest.GetResponse()
   at RestSharp.Http.GetRawResponse(HttpWebRequest request)
   at RestSharp.Http.GetResponse(HttpWebRequest request)
2017/01/16 19:16:40.902 Ombi.Api.SonarrApi Error: Exception when calling GetProfiles for Sonarr, Retrying 00:00:05 Ombi.Helpers.Exceptions.ApiRequestException: Error retrieving response. Check inner details for more info. ---> System.Net.WebException: The remote name could not be resolved: 'cyrusthevirus'
   at System.Net.HttpWebRequest.GetResponse()
   at RestSharp.Http.GetRawResponse(HttpWebRequest request)
   at RestSharp.Http.GetResponse(HttpWebRequest request)
   --- End of inner exception stack trace ---
   at Ombi.Api.ApiRequest.ExecuteJson[T](IRestRequest request, Uri baseUri) in C:\projects\requestplex\Ombi.Api\ApiRequest.cs:line 116
   at Ombi.Api.SonarrApi.<>c__DisplayClass6_0.<GetProfiles>b__1() in C:\projects\requestplex\Ombi.Api\SonarrApi.cs:line 60
   at Polly.Policy.<>c__DisplayClass8_0`1.<Execute>b__0()
   at Polly.RetrySyntax.<>c__DisplayClass14_0.<WaitAndRetry>b__1()
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`1 action, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory)
2017/01/16 19:16:48.213 Ombi.Api.ApiRequest Error: System.Net.WebException: The remote name could not be resolved: 'cyrusthevirus'
   at System.Net.HttpWebRequest.GetResponse()
   at RestSharp.Http.GetRawResponse(HttpWebRequest request)
   at RestSharp.Http.GetResponse(HttpWebRequest request) System.Net.WebException: The remote name could not be resolved: 'cyrusthevirus'
   at System.Net.HttpWebRequest.GetResponse()
   at RestSharp.Http.GetRawResponse(HttpWebRequest request)
   at RestSharp.Http.GetResponse(HttpWebRequest request)
2017/01/16 19:16:48.228 Ombi.Api.SonarrApi Error: Exception when calling GetProfiles for Sonarr, Retrying 00:00:10 Ombi.Helpers.Exceptions.ApiRequestException: Error retrieving response. Check inner details for more info. ---> System.Net.WebException: The remote name could not be resolved: 'cyrusthevirus'
   at System.Net.HttpWebRequest.GetResponse()
   at RestSharp.Http.GetRawResponse(HttpWebRequest request)
   at RestSharp.Http.GetResponse(HttpWebRequest request)
   --- End of inner exception stack trace ---
   at Ombi.Api.ApiRequest.ExecuteJson[T](IRestRequest request, Uri baseUri) in C:\projects\requestplex\Ombi.Api\ApiRequest.cs:line 116
   at Ombi.Api.SonarrApi.<>c__DisplayClass6_0.<GetProfiles>b__1() in C:\projects\requestplex\Ombi.Api\SonarrApi.cs:line 60
   at Polly.Policy.<>c__DisplayClass8_0`1.<Execute>b__0()
   at Polly.RetrySyntax.<>c__DisplayClass14_0.<WaitAndRetry>b__1()
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`1 action, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory)
2017/01/16 19:17:00.549 Ombi.Api.ApiRequest Error: System.Net.WebException: The remote name could not be resolved: 'cyrusthevirus'
   at System.Net.HttpWebRequest.GetResponse()
   at RestSharp.Http.GetRawResponse(HttpWebRequest request)
   at RestSharp.Http.GetResponse(HttpWebRequest request) System.Net.WebException: The remote name could not be resolved: 'cyrusthevirus'
   at System.Net.HttpWebRequest.GetResponse()
   at RestSharp.Http.GetRawResponse(HttpWebRequest request)
   at RestSharp.Http.GetResponse(HttpWebRequest request)

**Comment by chrisausbun** [comment]
I'm not too sure why it keeps trying to connect to my Sonarr API when I unchecked Enabled.

**Comment by tidusjar** [comment]
Please log a separate issue.
