### ISSUE TITLE
Start Error

### ISSUE THREAD

**Issue by english06** [tidusjar/Ombi#962]
#### Ombi Version:

V 2.0.1

#### Update Branch:

Stable/Early Access Preview/development

#### Operating System:

Windows 10

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

 System.IO.FileLoadException: Could not load file or assembly 'file:///C:\Program Files\Ombi\Ninject.Extensions.ChildKernel.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
File name: 'file:///C:\Program Files\Ombi\Ninject.Extensions.ChildKernel.dll' ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.

   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Ninject.Modules.AssemblyNameRetriever.AssemblyChecker.GetAssemblyNames(IEnumerable`1 filenames, Predicate`1 filter)
   at Ninject.Modules.AssemblyNameRetriever.AssemblyChecker.GetAssemblyNames(IEnumerable`1 filenames, Predicate`1 filter)
   at Ninject.Modules.AssemblyNameRetriever.GetAssemblyNames(IEnumerable`1 filenames, Predicate`1 filter)
   at Ninject.Modules.CompiledModuleLoaderPlugin.LoadModules(IEnumerable`1 filenames)
   at Ninject.Modules.ModuleLoader.LoadModules(IEnumerable`1 patterns)
   at Ninject.KernelBase.Load(IEnumerable`1 filePatterns)
   at Ninject.KernelBase..ctor(IComponentContainer components, INinjectSettings settings, INinjectModule[] modules)
   at Ombi.UI.Startup.Configuration(IAppBuilder app) in C:\projects\requestplex\Ombi.UI\Startup.cs:line 66


```

#### Problem Description:

Error when running Ombi.exe (as user or admin). Attempted to run from nssm, shows as successful but localhost:3579 does not work. Log is from ombi.exe direct run.

**Comment by tidusjar** [comment]
Hi! it looks like you didn't unblock the .zip file before extracting!
